### ISSUE TITLE
Script Map Buttons (SiMaKiDD) übernehmen [9]

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#10]
[Wunschliste: 9]
Funktionalität aus Script Map Buttons (SiMaKiDD) prüfen und im GClh übernehmen, falls noch nicht vorhanden. 

- Ein echter Mehrwert ist womöglich nicht vorhanden, weil beide Scripte parallel betrieben werden können.

**Comment by 2Abendsegler** [comment]
[MAP_BUTTONS.user.zip](https://github.com/2Abendsegler/GClh/files/816125/MAP_BUTTONS.user.zip)

**Comment by CachingFoX** [comment]
Floop's Map: Tutorial: Permalinks
http://blog.flopp-caching.de/2013/03/tutorial-permalinks/

**Comment by CachingFoX** [comment]
URL for Flopp's Map
http://www.flopp.net/?
c=49.614583:8.397383
&z=17
&t=OSM
&m=
L:49.614583:8.397383:0:GC5W9ZD_LISTINGCOORDS
*A1:49.6131833:8.3998:0:01
*A2:49.6138833:8.39835:0:02
*A3:49.61445:8.39755:0:03
*A4:49.61475:8.3971667:0:04
*A5:49.6149833:8.3968:0:05*A6:49.61605:8.3951667:0:06*A7:49.6166833:8.39435:0:07*A8:49.6174:8.3934667:0:08*A9:49.61835:8.3924:0:09&d=

-----------
Mystery with changed listing coordinates (aka final)
http://www.flopp.net/?
c=49.08237:11.371267&z=17&t=OSM&m=F:49.08237:11.371267:161:GC2WZY2_CHANGED*O:49.064717:11.380367:3000:GC2WZY2_ORIGIN*A1:11.1851833:11.1851833:0:STAGE1*A2:49.1696667:11.42305:0:STAGE2*A3:49.2133333:11.5014667:0:STAGE3&d=O:F

**Comment by 2Abendsegler** [comment]
Eingespielt und getested.
