### ISSUE TITLE
Note of thanks.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1004]
**Describe the solution you'd like**
Note of thanks.

Es stört mich schon lange, dass die Entwickler nicht irgendwo wenigstens an einer kleinen Stelle benannt werden. Es geht mir hier weniger um die drei aus der Copyright Zeile, sondern vielmehr um die ganzen anderen Entwickler, insbesondere auch CachingFoX, der ja auch ziemlich viel beigetragen hat. 

@Ruko2010 
Ich hab also mal etwas rumgespielt im Config. Es ist noch nicht testreif, ich wollte es zuerst mal mit dir abstimmen. Kannst natürlich trotzdem etwas rumspielen. Und ich könnte auch noch etwas Input zum Textinhalt und zur Gestaltung gebrauchen. 
(Daneben habe ich noch etwas Kosmetik im Config betrieben, das werde ich etwas später noch im Einzelnen auflisten damit es einfacher wird die Änderungen zu prüfen.)

Thanks Link oben im Menü beim Config:
![grafik](https://user-images.githubusercontent.com/22332216/54260308-d8ef7d80-4568-11e9-99f0-c32009f7c802.png)

Ähnlich wie beim Reset Link wird ein neuer Config Screen aufgebaut.
Reihenfolge im Bereich Development entspricht der bei [GitHub contributors](https://github.com/2Abendsegler/GClh/graphs/contributors).
![grafik](https://user-images.githubusercontent.com/22332216/54260417-1bb15580-4569-11e9-8742-1ccfd3d68b43.png)

**Comment by Ruko2010** [comment]
Das sieht doch schonmal gut aus. Die Idee ist klasse!

Zum Wording:
Ich würde für uns (erster Abschnitt):
"Lead Developer and Project Manager"

und für den zweiten Abschnitt
"Development Contributers" oder nur "Contributers"
vorschlagen.

Vielleicht machen wir noch einen Abschnitt, in dem wir solche Leute wir PontiacCZ aufnehmen können, sowas wie "Input Contributers" (das gefällt mir noch nicht, aber vielleicht bekommst du die Idee von dem was ich meine).

**Comment by 2Abendsegler** [comment]
Gute Idee auch die Ticket Melder aufzulisten.

Mir fällt aber die Gruppierung schwer. Beispielsweise machst du oder CachingFoX ja auch Tickets auf. Und wenn wir beispielsweise noch eine Übersetzung ins Deutsche und eine ins Tschechische haben, haben wir noch zwei weitere Gruppen. PontiacCZ könnte also beispielsweise für die Tschechische Übersetzung und CachingFoX für die Deutsche Übersetzung verantwortlich sein. 

Ohne Mehrfachnennungen von Usern geht es dann nicht, es sei denn wir machen eine Tabelle mit Spalten und setzen entsprechend einen Haken bzw. bei der Übersetzung die Sprache. 

Ach was ist das doch immer kompliziert, mimimi ;)

**Comment by 2Abendsegler** [comment]
Hab mal meine Ex Cheffin um Rat gefragt, sie hats mehr mit dem Englisch als ich. Rausgekommen sind folgende Rollen:
Project Management, Development Lead, Development, Testing, Error Reporting, Translation
Was hälst du davon?

In einer Tabelle könnte man die Rollen in schräg geneigter Schrift darstellen, falls das geht, damit die Spalten nicht so breit werden, also so von links unten nach rechts oben. In den Zeilen dann die User mit entsprechenden Haken in den Spalten. 
Macht das Sinn?

**Comment by Ruko2010** [comment]
Ja das macht Sinn. Aber ich würde dich, torsten und mich dann etwas gesondert abheben. Nicht das die Leute die die Seite sehen denken, sie können alle leute einfach kontaktieren falls sie Probleme haben. 
Die Rollen klingen gut. ich würde aber Testing und Translation weg lassen....die anderen 4 gefallen mir.

**Comment by Ruko2010** [comment]
Für die Rotation des Textes, Sollte gehen:
https://www.html-seminar.de/css3-transform-rotate.htm

**Comment by 2Abendsegler** [comment]
Zu Rotation: Super, hab ich nicht mehr gewußt, obwohl ich das ja schon für Icons verwendet hab. Super. 

- [ ] Lead gesondert abheben und Reihenfolge wie im 1. Draft
- [ ] Rollen Project Management, Development Lead, Development und Error Reporting verwenden
- [ ] Rotation der Spaltentexte

**Comment by Ruko2010** [comment]
bin gespannt 😃

**Comment by 2Abendsegler** [comment]
Eigentlich wollte ich ja nur mal kurz die Entwickler würdigen. Das ist alles viel mehr geworden als beabsichtigt.

Ich bin nun soweit fertig und habe auf Win 8.1 FF und Chrome und auf Android 9.0 FF getestet.

1. Note of thanks

1.1 Ermittlung User und Rollen:
- Die Ermittlung der User und insbesondere deren Rollen ist beschwerlich. Machinell vermutlich gar nicht machbar, schon weil die GitHub User Namen nicht immer mit den GC User Namen übereinstimmen. Das gilt für etwa 1/3 der User. Den GitHub User gboye kann ich überhaupt nicht zuordnen. 
- Zudem haben wir in der Vergangenheit insbesondere den Status der Issues nicht immer korrekt gepflegt, was aber wichtig ist weil wir ja keine Hilferufe oder Feature Requests mit auswerten wollen sondern nur das Bug Reporting. 
- Außerdem wollen wir auch nur die Bugs berücksichtigen, die zu einer Korrektur geführt haben und nicht etwa die mit Status rejected. 
- Die Ermittlung erfolgt komplett händisch und wird im Code eingetragen. Zukünftig muß man das beobachten und Änderungen, also neue User und auch die Anzahl der gefixten Bugs, auf dem Laufenden halten. Das ist also so etwas wie die Pflege des Changelogs für jeden Bug, so muss nun auch das hier mitgepflegt werden. Coding Bereich habe ich mit $$006 gekennzeichnet.
@Ruko2010 Was meinst du, ist das machbar?

1.2 Issue Statuspflege:
- Wenn die Issues korrekt gepflegt werden, sollte der Status fixed der einzig Relevante sein. Status completed ist für Enhancements und Improvements und auch für Hilferufe oder sonstiges. Ein Status sollte für ein Issue in jedem Fall vergeben werden.      
- @Ruko2010 Ist das auch dein Verständnis?
- [ ] Ich werde dann alle fehlerhaften Bug Issues nacharbeiten und die User nochmal auswerten.

1.3 Anzahl gefixter Bugs je User:
- Die Anzahl wird lediglich im title des Icons in der Spalte Bug Reporting ausgewiesen. Ich wollte zuerst die tatsächliche Anzahl in der Spalte benennen, das ist mir aber unangenehm, weil ich mit Abstand derjenige mit den Meisten bin. 
@Ruko2010 Können wir das so lassen?
- Die User sind hier nach Anzahl sortiert und dann nach Namen, sofern nur Spalte Bug Reporting gepflegt ist. Bei uns und den Development Usern zählen ja andere Kriterien für die Sortierung. 

1.4 Development User:
- Die Development User ergeben sich aus der Darstellung Contributions to collector https://github.com/2Abendsegler/GClh/graphs/contributors. Hier wird sich nicht viel ändern, trotzdem sollte das zu jeder neuen Version geprüft werden.
- Als Development Lead habe ich nur uns beide gelistet. Torsten hat ja auch faktisch hier nicht mitgewirkt und das würde nur Probleme machen weil er ja nicht von den Usern angeschrieben werden soll.

1.5 Last Update der Tabelle
- Unterhalb der Tabelle wird ein Datum ausgegeben das den Stand der Tabellendaten wiederspiegeln soll. Dieses Datum muß auch bei jeder neuen Version angepaßt werden. Coding Bereich habe ich mit $$007 gekennzeichnet.

---
2. Etwas Kosmetik im Config:
Sofern du damit einverstanden bist, etwas Kosmetik im Config zu Dingen die mich stören seit ich sie eingebaut habe. ;)
@Ruko2010 Ist das so in Ordnung oder soll ich noch was ändern.

2.1 Title zum Link "Changelog" oben im Menü des Config angepaßt: 
```
Alt title: "Documentation of changes and new features in GClh II on GitHub"
Neu title: "Documentation of changes and new features on GitHub"
```

2.2 Title und Text zum Link "Check for Upgrade" oben im Menü des Config angepaßt: 
```
Alt text: "Check for Upgrade"
Neu text: "Upgrade"
Alt title: "Check for Upgrade"
Neu title: "Check for new version"
```

2.3 Title zum Link "GitHub" oben im Menü des Config angepaßt: 
```
Alt title: "Development plattform and issue system of GClh II"
Neu title: "Development plattform and issue system"
```

2.4 Title zum Link "Warranty" ganz unten im Config angepaßt: 
```
Alt title: "Development plattform and issue system of GClh II"
Neu title: "Development plattform and issue system"
```

2.5 Title für die Copyright User ganz unten im Config ergänzt:
```
Alt title: ""
Neu title: "GC profile for Torsten-"
...
```

**Comment by Ruko2010** [comment]
> 1.1 Ermittlung User und Rollen:
> 
> * Die Ermittlung der User und insbesondere deren Rollen ist beschwerlich. Machinell vermutlich gar nicht machbar, schon weil die GitHub User Namen nicht immer mit den GC User Namen übereinstimmen. Das gilt für etwa 1/3 der User. Den GitHub User gboye kann ich überhaupt nicht zuordnen.

Diese User können wir doch einfach ohne Link eintragen. 

> * Zudem haben wir in der Vergangenheit insbesondere den Status der Issues nicht immer korrekt gepflegt, was aber wichtig ist weil wir ja keine Hilferufe oder Feature Requests mit auswerten wollen sondern nur das Bug Reporting.
> * Außerdem wollen wir auch nur die Bugs berücksichtigen, die zu einer Korrektur geführt haben und nicht etwa die mit Status rejected.
> * Die Ermittlung erfolgt komplett händisch und wird im Code eingetragen. Zukünftig muß man das beobachten und Änderungen, also neue User und auch die Anzahl der gefixten Bugs, auf dem Laufenden halten. Das ist also so etwas wie die Pflege des Changelogs für jeden Bug, so muss nun auch das hier mitgepflegt werden. Coding Bereich habe ich mit $$006 gekennzeichnet.
>   @Ruko2010 Was meinst du, ist das machbar?
> 

Das finde ich viel zu viel Aufwand für diese Seite! Ich bin der Meinung, dass wir das nicht sortieren müssen nach Anzahl der Bug/fixes! Das du es jetzt gemacht hast ist schön, aber ich bin der Meinung, wir fügen einfach neue Leute unten an die Liste an. Es soll ja an sich keine "Rangliste" sein. Ich würde da weniger Arbeit reinstecken. Wenn wir jemand vergessen haben, dann ist das entweder so, oder der jenige meldet sich und wir fügen ihn noch hinzu.

> 1.2 Issue Statuspflege:
> 
> * Wenn die Issues korrekt gepflegt werden, sollte der Status fixed der einzig Relevante sein. Status completed ist für Enhancements und Improvements und auch für Hilferufe oder sonstiges. Ein Status sollte für ein Issue in jedem Fall vergeben werden.
> * @Ruko2010 Ist das auch dein Verständnis?
> * [ ]  Ich werde dann alle fehlerhaften Bug Issues nacharbeiten und die User nochmal auswerten.
> 
> 1.3 Anzahl gefixter Bugs je User:
> 
> * Die Anzahl wird lediglich im title des Icons in der Spalte Bug Reporting ausgewiesen. Ich wollte zuerst die tatsächliche Anzahl in der Spalte benennen, das ist mir aber unangenehm, weil ich mit Abstand derjenige mit den Meisten bin.
>   @Ruko2010 Können wir das so lassen?
> * Die User sind hier nach Anzahl sortiert und dann nach Namen, sofern nur Spalte Bug Reporting gepflegt ist. Bei uns und den Development Usern zählen ja andere Kriterien für die Sortierung.
> 

Ich würde wie gesagt nicht so viel Aufwand für eine Seite machen, die sich wahrscheinlich (leider) nicht viele Leute ansehen werden. Lass uns die Leute einfach eintragen und gut ist, ohne Anzahl der gefixten Bugs.

> 1.4 Development User:
> 
> * Die Development User ergeben sich aus der Darstellung Contributions to collector https://github.com/2Abendsegler/GClh/graphs/contributors. Hier wird sich nicht viel ändern, trotzdem sollte das zu jeder neuen Version geprüft werden.
> * Als Development Lead habe ich nur uns beide gelistet. Torsten hat ja auch faktisch hier nicht mitgewirkt und das würde nur Probleme machen weil er ja nicht von den Usern angeschrieben werden soll.

klingt gut

> 
> 1.5 Last Update der Tabelle
> 
> * Unterhalb der Tabelle wird ein Datum ausgegeben das den Stand der Tabellendaten wiederspiegeln soll. Dieses Datum muß auch bei jeder neuen Version angepaßt werden. Coding Bereich habe ich mit $$007 gekennzeichnet.
> 
> 1. Etwas Kosmetik im Config:
>    Sofern du damit einverstanden bist, etwas Kosmetik im Config zu Dingen die mich stören seit ich sie eingebaut habe. ;)
>    @Ruko2010 Ist das so in Ordnung oder soll ich noch was ändern.

Ich bin da schmerzbefreit 😉. Wenn es dich stört, dann ändere es.

> 
> 2.1 Title zum Link "Changelog" oben im Menü des Config angepaßt:
> 
> ```
> Alt title: "Documentation of changes and new features in GClh II on GitHub"
> Neu title: "Documentation of changes and new features on GitHub"
> ```
> 2.2 Title und Text zum Link "Check for Upgrade" oben im Menü des Config angepaßt:
> 
> ```
> Alt text: "Check for Upgrade"
> Neu text: "Upgrade"
> Alt title: "Check for Upgrade"
> Neu title: "Check for new version"
> ```
> 2.3 Title zum Link "GitHub" oben im Menü des Config angepaßt:
> 
> ```
> Alt title: "Development plattform and issue system of GClh II"
> Neu title: "Development plattform and issue system"
> ```
> 2.4 Title zum Link "Warranty" ganz unten im Config angepaßt:
> 
> ```
> Alt title: "Development plattform and issue system of GClh II"
> Neu title: "Development plattform and issue system"
> ```
> 2.5 Title für die Copyright User ganz unten im Config ergänzt:
> 
> ```
> Alt title: ""
> Neu title: "GC profile for Torsten-"
> ...
> ```

**Comment by 2Abendsegler** [comment]
Einen User ohne Link eintragen macht jetzt noch mehr Aufwand, weil der Link ja automatisch generiert wird. Ich würde mal sagen der hat geloost. :)

**Comment by Ruko2010** [comment]
Achso, das wusste ich nicht 😂. Dann lass ihn weg.

**Comment by Ruko2010** [comment]
Gerade wollte ich das Changelog pflegen, da sind mir noch zwei Sachen aufgefallen.
1. Soll ich einen direktlink auf die Thanks Note machen (geht das überhaupt?), oder reicht ein Screenshot?
2. Man kommt von der Note nicht zurück zur Config. Kannst du da vielleicht noch was bauen? Sonst muss man das Fenster zu und wieder auf machen um an die Config zu kommen.

**Comment by 2Abendsegler** [comment]
zu 1. Einen Direktlink gibt es hier nicht. Ich würde auch keinen Screenshot der Thanksseite ins Changelog hängen sondern nur das Config Menü mit dem Link zu der Thanks Seite
![grafik](https://user-images.githubusercontent.com/22332216/54619575-1d958000-4a65-11e9-847d-b6406e1fd8e9.png)

zu 2. Erledigt.

**Comment by 2Abendsegler** [comment]
Zum Go-Live Dokument: Es gibt nur noch den Punkt $$006, das Datum steht dierekt unterhalb der Userliste. $$007 ist also entfallen.

**Comment by Ruko2010** [comment]
Danke!
