### ISSUE TITLE
Download Bookmark List as GPX

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#1014]
Bin ich total verwirrt, oder gab es mal einen Button, mit dem man eine BML als GPX Datei herunter laden konnte? Finde ich den nur nicht mehr? War der von GC, falls ja haben die den Weg rationalisiert?

**Comment by 2Abendsegler** [comment]
Ich glaube man mußte schon immer ein PQ daraus machen um eine GPX Datei downloaden zu können. Es gab in der alten Übersicht der Bookmarklisten einen Download als .kml und in den Bookmarklisten selbst einen Download als .loc . [Hier](https://github.com/2Abendsegler/GClh/blob/collector/docu/overview_screenshots.md#user-content-bookmark-list) kannst du das noch sehen. Falls der Link nicht an der richtigen Stelle landet, suche nach "Bookmark List".

**Comment by Ruko2010** [comment]
Ach mist, dann war es der loc Download den ich meinte. Den hat GC wohl entfernt. Ich hatte mir immer die BML per Loc gezogen und dann auf dem handy aktualisiert, so hatte ich schnell die BML in meiner App, ohne erst eine PQ erstellen zu müssen. Naja, dann muss ich nun wohl den Weg über die PQ gehen. Zumindest die kann meine App zum Glück direkt von der GC Seite laden.
Ich mach hier mal dicht...

**Comment by Ruko2010** [comment]
Ich mach das hier doch nochmal auf.
Ich glaube meinen Programm reicht es schon, wenn es eine Liste der GCCodes bekommt, es muss nur im richtigen Format sein. Den Rest der Daten holt es sich dann über die Update Funktion im Programm selbst.

So muss das XML dazu aussehen:

```
<?xml version="1.0" encoding="UTF-8"?>
<loc version="1.0" src="Groundspeak">
<waypoint>
     <name id="GCQQK3"><![CDATA["Red House" by mgo]]></name>
     <coord lat="48.8958166666667" lon="9.15391666666667"/>
     <type>Geocache</type>
     <link text="Cache Details">http://www.geocaching.com/seek/cache_details.aspx?wp=GCQQK3</link>
</waypoint></loc>
```

**Comment by 2Abendsegler** [comment]
Im neuen Design der Bookmarklisten gibt es nun einen Download als gpx Datei. Das issue kann vermutlich geschlossen werden.

**Comment by Ruko2010** [comment]
Ich glaubs nicht...endlich mal was, das GS gut gemacht hat. Ja, dass ist genau die Funktionalität die mir gefehlt hatte.
