### ISSUE TITLE
On Google Maps page icon to GC Map is missing.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1018]
Per Mail 05.04.2019 um 18:55 Uhr 
...
Bei Google konnte man immer einen Ort eingeben auf Maps klicken und rechts konnte man direkt zur Geocaching Karte switchen... Das war sehr praktisch und erleichtert einem die Suche auf der GC Homepage nach einem Ort..
Seit ein paar Tagen ist das Icon leider verschwunden
...

**Comment by 2Abendsegler** [comment]
erledigt

**Comment by 2Abendsegler** [comment]
Gesendet per Mail: Freitag, 05. April 2019 um 23:00 Uhr

---
Hallo,

Goggle hat Änderungen an der Google Maps Seite gemacht. Der Bug ist in der nächsten Version korrigiert. Hab ein Issue aufgemacht und auch gleich korrigiert. https://github.com/2Abendsegler/GClh/issues/1018

Alternative kannst du auch im "Search" Feld (im Menü rechts neben der Linklist) oder auf der GC Karte im Feld "Search for Geocaches" einen Ort eingeben.

Liebe Grüße

**Comment by 2Abendsegler** [comment]
... Frau fragt an wann es eine neue Version gibt ... 
Sind auch schon gut 7 Wochen seit der Letzten.

**Comment by Ruko2010** [comment]
😃. Deine Frau fragt an wann es eine neue Version gibt 😃? Wie cool 😃. Ich machs im laufe der nächsten Woche, oder Morgen. Gerade ist es etwas stressig wegen dem Event. Waren doch noch ein paar Dinge zu tun. Ich hoffe es klappt Morgen alles... 😃.

**Comment by 2Abendsegler** [comment]
:) Nicht meine ... sondern die die sich bei mir per Mail mit dem Bug gemeldet hat.

**Comment by 2Abendsegler** [comment]
ach ja ... und viel Spaß auf eurem Event. :)

**Comment by Ruko2010** [comment]
Achso 😂, dann hab ich das falsch verstanden. Aber ja, sie hat recht. Es sind wieder viele Sachen die gefixt wurden. Vielleicht mach ich noch das GreatStory Feature fertig vor dem nächsten Release. Dann kann ich mich wirklich mit der neuen Karte beschäftigen.

**Comment by Ruko2010** [comment]
Ich druck gerade die letzten Give-Aways 😃
![IMG_1594](https://user-images.githubusercontent.com/2239440/55675442-e7f4f180-58c2-11e9-9bca-9f92414c9733.jpg)

**Comment by 2Abendsegler** [comment]
Ist das eigentlich ein 3D Drucker?

Wenn du magst kann ich heute noch ne neue Version raushauen. Ab morgen bin ich dann im Urlaub. Jippie. Hab schon alles gepackt und weiss jetzt gar nichts mit mir anzufangen, hihi. Wenn du also dein Zeug in den Collector spielst dann kann ich das noch übernehmen.

**Comment by Ruko2010** [comment]
Ja das ist ein 3D-Drucker. Ist cool, gerade wenn man Caches verstecken will, oder wie wir ein paar Sachen für unser Campingmobil selbst ausdrucken kann.

Ich mach die Version diese Woche noch fertig. Ich hoffe ich komme noch dazu das Great Story Ding fertig zu machen. Dann ist das mal vom Tisch. Genieß deinen Urlaub und sammel nicht nur viele Dosen, sondern auch viele Eindrücke 😉.

**Comment by 2Abendsegler** [comment]
Danke! Es geht fast immer um die Eindrücke und die Abenteuer ... die Caches sind halt gute Wegbereiter. Aber wem sag ich das. ;)

Ich werde insbesondere die nächsten Tage gar keine Zeit haben zum Testen. Das Great Story Ding sollte aber am besten von Mehreren ausführlich getestet werden ... vielleicht ja doch ohne?

Bin dann jetzt weg ... :)
