### ISSUE TITLE
The change log functinality integrates the signature once again. 

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1023]
**Describe the bug**
Hola.
The change log functinality integrates the signature once again. 
Haben wir nicht vor kurzem daran rumgebastelt, vielleicht habenwir da etwas kaputt gemacht.

**To Reproduce**
1. Enter a new log and submit it
2. Choose icon edit
3. See integration of signature once again

**Desktop (please complete the following information):**
 - Win 8.1
 - FF 66.0.2 (64-Bit)
 - GClh v0.9.17

**Comment by 2Abendsegler** [comment]
Ich kann das gerade nicht mehr nachstellen. Dabei ist es heute bei den neuen Logs drei Mal passiert. Einen Unterschied kann ich nicht erkennen, außer dass die Logs nun schon etwas länger gespeichert sind. Voll dubios.

**Comment by Ruko2010** [comment]
Kannst du deine "Steps to reproduce the behavior" nochmal konkretisieren? Was genau meinst du mit "Choose icon change"? Bist du beim "editieren" von Logs? Oder bei den Drafts?
dann schau ich mal, ob ich es nachstellen kann.

**Comment by 2Abendsegler** [comment]
Das ging gestern im Schnellverfahren. Hoffe das passt jetzt. :D 
Aber warte, ich werde heute Abend oder so nochmal mit neuen Logs versuchen, weil es womöglich nur dort nicht funktioniert.
Ich melde mich dann noch mal.

**Comment by 2Abendsegler** [comment]
Der Fehler tritt scheinbar nur auf, wenn man direkt nach dem submit eines Logs auf das Änderungsicon klickt um sofort noch etwas zu ändern. Ich weiß dass das mal funktionierte, weil ich schon gelegentlich nochmal nachbessern muss. Probiers mal aus bei einem deiner nächsten Logs.

**Comment by Ruko2010** [comment]
Ich habs heute mal versucht nachzustellen (da ich ein paar Logs vom Osterwochenende habe). Hier mein Ablauf:

1. Seite Draft aufrufen
2. Log schreiben/einfügen (Signatur wird angehangen)
3. Log absenden
4. Ich werde zur Listingseite geleitet, dort klick auf "View / Edit Log / Images"
5. Klick auf den "Stift" um den Log zu bearbeiten.

Wenn ich dort etwas ändere, dann passiert mit der Signatur nichts. Sie bleibt wie sie ist, und wird nicht erneut eingefügt. Falls du einen anderen Weg gehst, dann bitte nochmal erläutern.

**Comment by 2Abendsegler** [comment]
Ja, der Effekt stellt sich nur auf der alten Log Seite ein, nur dort bleibt man nach dem submit auf der Log Seite. Hab ich vergessen zu erwähnen, jahahaha. Blöd gelaufen ...

**Comment by Ruko2010** [comment]
Ach mist. Na ich schau mal wenn ich den nächsten Log habe, ob ich es nachstellen kann...

**Comment by Ruko2010** [comment]
So, nun konnte ich es nachstellen. Das Problem ist glaube ich, dass der Editieren-Link nach dem Loggen kein "richtiger" Link ist, sondern es wird ein "doPostBack" gemacht. Dann wird wahrscheinlich auf der Logging Page nicht mehr geprüft, ob die Signatur schon eingefügt ist oder nicht.
Ich hab noch einen Cache den ich loggen muss, mal schauen ob ich es hin bekomme, das zu fixen.

**Comment by Ruko2010** [comment]
Wir haben den Check auf Duplikat nur bei der neuen Logpage gemacht, dass ist nun für die alte Page auch nachgeholt.
