### ISSUE TITLE
Show Google-Maps Link on Cache Listing Page does not work.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1025]
**Describe the bug**
Show Google-Maps Link on Cache Listing Page generate error.

Folgende Zeile verursacht Abbruch
`var matches = ref_link.href.match(/\?lat=(-?[0-9.]*)&lng=(-?[0-9.]*)/);`
In href bei #ctl00_ContentBody_uxViewLargerMap stehen nur noch "kryptische Werte" und keine lat und lng Werte mehr. 

Vermutlich können wir die Koordinaten von ganz oben im Cache Listing aus #uxLatLonLink nehmen. Die müssen dann nur noch umgewandelt werden, machen wir aber sowieso an anderer Stelle schon.

**To Reproduce**
1. Go to https://coord.info/GCH0P8 or another cache listing
2. See error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22332216/56847198-69470f00-68d8-11e9-9d06-d72dc81d3eec.png)

**Desktop (please complete the following information):**
 - All

**Comment by BlueEagle23** [comment]
Is this something that will be fixed with the next update? I'm still getting the error.

Show google maps link: Cannot read property '1' of null

**Comment by Ruko2010** [comment]
@BlueEagle23 This is fixed in 0.9.18 which will be released soon.
