### ISSUE TITLE
Remove all links to unsecure pages.

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#1037]
There are several Links that lead to unsecure pages (http instead of https). Since today SSL is mostly the standard on all (good) Servers, we should change the Links to https.

**Comment by 2Abendsegler** [comment]
@Roku2010
Kann ich mir das mal ansehen, oder hast du hier schon begonnen?
Brauch was einfaches fürs Gemüt. 🙄

**Comment by Ruko2010** [comment]
an sich sollte das doch schnell gehen, oder? Einfach suchen nach "http://" und ersetzen mit "https://" 😬

Nein angefangen hab ich damit noch nicht. Kannst du gern machen wenn du Lust hast. Ich kann es aber auch machen. In meinem Editor sollte dass recht schnell gehen.

**Comment by 2Abendsegler** [comment]
Hm, ich dachte man müsse prüfen ob es https gibt. Geoclub hat beispielsweise keine. Ist das richtig dass man sie dann mit https aufruft?
Wie fast immer, hab ich mal wieder keine Ahnung.

**Comment by 2Abendsegler** [comment]
Geoclub ist wohl ein schlechtes Beispiel gewesen, die haben doch https. Aber die Frage bleibt.

**Comment by Ruko2010** [comment]
Oh man, an sowas hab ich gar nicht gedacht. Da hast du natürlich völlig recht. Man muss das prüfen. Wenn man eine Seite die kein https hat mit https aufruft, bekommt man einen Fehler.

**Comment by 2Abendsegler** [comment]
Hab alle abgeändert, waren quasi auch alle verfügbar. Beim Aufruf der Seiten wurde auch automatisch auf https umgestellt wenn sie mit http aufgerufen wurden. Trotzdem gut dass wirs umgestellt haben. 

`// @namespace        http://www.amshove.net` darf nicht umgestellt werden, weil das dann ein neues Script in Tampermonkey zur Folge hätte.

merged

**Comment by Ruko2010** [comment]
> Hab alle abgeändert, waren quasi auch alle verfügbar. Beim Aufruf der Seiten wurde auch automatisch auf https umgestellt wenn sie mit http aufgerufen wurden. Trotzdem gut dass wirs umgestellt haben.

Sehr gut. 

> `// @namespace http://www.amshove.net` darf nicht umgestellt werden, weil das dann ein neues Script in Tampermonkey zur Folge hätte.

Macht Sinn. Das ist ja auch an sich kein Link, sondern der Namespace unseres Scripts. Das war wohl etwas unglücklich gewählt von Torsten damals.

**Comment by 2Abendsegler** [comment]
> Das war wohl etwas unglücklich gewählt von Torsten damals.

Ja, aber ich habs dann auch beibehalten. 😉
