### ISSUE TITLE
Selecting "last cache-log" on the "Log this geocache" page is not activating the "Post" button

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#1038]
**Describe the bug**
When selecting "last cache-log" on the "Log this geocache" page the text is shown correctly below, but the log-Preview area is not showing the text. When pressing the "Post" button an error message is shown "Please leave a comment."

**To Reproduce**
1. Go to 'last cache-log' page from the drafts-page
2. selecting "last cache-log"
3. pressing the "Post" button
4. error message is shown "Please leave a comment."
5. to save the log I enter an additional space in the log-text-area. After that the log-Preview area is not showing the text an I can press the "Post" button without an error.

**Expected behavior**
the log-Preview should be filled, when selecting "last cache-log" and there is no error when I press the "Post" button

**Screenshots**
![Image 10](https://user-images.githubusercontent.com/7745027/60364599-e3823580-99e6-11e9-98c5-c1bae217b484.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox 67.0.4
 - GCLH v0.9.18

**Comment by Ruko2010** [comment]
HI @Donnerknispel and thanks for reporting. Can you do me a favor and try the following:
After Adding the Logtemplate, please click into to Textarea and simply type in a Character, or hit Space. This should update the Log-Preview and fix the Problem with sending the log.

**Comment by Donnerknispel** [comment]
This is exactly what I am doing now already. Nevertheless thanks for the hint.

> to save the log I enter an additional space in the log-text-area. After that the log-Preview area is not showing the text an I can press the "Post" button without an error.

**Comment by Ruko2010** [comment]
Ok, Thanks for reproducing. I'll try to fix it by simulating a keydown event in the textarea.

**Comment by Ruko2010** [comment]
I've tried simulating the keypress, but this will not activate the "Post"-Button. It only updates the preview. I think GroundSpeak is using another mechanism to store the data entered in the textarea. But I'm not able to find which one.
So for now, I have no Idea how to solve this, sorry.
I'll leave this open for a while. Maybe @2Abendsegler or @CachingFoX are willing to give it a shot on it.

**Comment by 2Abendsegler** [comment]
Man kann über das alte Log Formular die Logs posten, dort geht es ja.

@Ruko2010 Kannst du mal den Link einstellen in dem der Preview schon funktioniert? Ich hab die Tage vielleicht einen Rechner auf dem ich mir das mal ansehen kann.

**Comment by Ruko2010** [comment]
Na klar, hier ist die Branch:

https://github.com/Ruko2010/GClh/raw/issue/1038-last_log/gc_little_helper_II.user.js


Was ich versucht habe:
- Ich wollte einen Keypress Simulieren, also nicht nur das Event feuern (das geht, denn darum wird nun auch die Preview geupdated), sondern richtig ein Taste eingeben, so das GC denkt, es wird was ins Feld getippt und somit alles nötige macht, um den Log absenden zu können.
Leider verstößt das wohl gegen Browser-Richtlinien, so dass das nicht möglich ist. Darum komm ich erstmal nicht weiter.
Man müsste heraus finden, was GC noch macht, wenn man einen Text eingibt (zum Beispiel irgendeine Validierungsfunktion aufrufen oder so und die dann ggf. auch feuern.

**Comment by 2Abendsegler** [comment]
Das dauert alles etwas weil ich zur Zeit ohne Rechner bin und einen in Aussicht gestellten doch nicht für Scripte nutzen konnte. Vermutlich habe ich nun aber endlich das Problem in meinem Rechner lokalisieren können. Ich warte noch auf ein Ersatzteil, dann sollte ich mir das Issue mal ansehen können, hoffe ich. ;)

**Comment by 2Abendsegler** [comment]
Ich kann hier nichts ausrichten.

Dubios ist folgendes:
(Das nur der Vollständigkeit halber, vielleicht bringt es jemanden auf Ideen.)

- Mit 
`$('#LogText')[0].value = "test";`
funktioniert alles. Sprich ein Click auf den Post Button speichert ein Log mit dem Inhalt "test".
- Warte ich jedoch 2 Sekunden bis der Code läuft funktioniert auch das nicht.

**Comment by Ruko2010** [comment]
Ich glaube wir laufen hier in eine Sackgasse.
Sorry, aber ich würde das als "wont-fix" eingliedern und schließen.

**Comment by 2Abendsegler** [comment]
@Donnerknispel 
Sorry, wir bekommen das im Moment nicht hin. Ich lege es aufs Lager, vielleicht haben wir später nochmal ne Idee.
Workaround: Im neuen Log Formular ein Leerzeichen einfügen. Oder das alte Log Formular nutzen, dort funktioniert es ja.
