### ISSUE TITLE
BRouter with empty waypoint in URL.

### ISSUE THREAD

**Issue by radlerandi** [2Abendsegler/GClh#1042]
2 Sachen: 

a) der waypointSeparator hat sich bei Brouter (wiedermal) geändert. Nun wird ";" verwendet. Leider funktionieren mit dem aktuell verwendeten GClh generierte Links aktuell nicht, werden auch nicht umgewandelt auf der Seite.  Wollte für das eine Zeichen jetzt nicht einen eigenen Pull Request aufmachen, weil ->

b) in einer Brouter-URL von der Deutschlandtour Ost-West https://coord.info/GC6128Z , die ich von meinem wegen ";" modizierten Skript habe erstellen lassen, scheinen doppelte Semikolon nach dem ersten Waypoint in der Liste dazu zu führen, dass keine Route berechnet wird. Es wird nur der erste Waypoint auf der Karte angezeigt. Entferne ich das doppelte ; in der URL funktioniert die Berechnung. Ich vermute, dass ein return value leer ist in der function brouterWaypoint. Allerdings steige ich dann nicht dahinter, wie und wo man das abfangen könnte, dass leere Waypoints nicht der Waypointliste hinzugefügt werden, scheinbar in der function mapservice_open.

http://brouter.de/brouter-web/#map=8/50.95075/10.453967/OpenStreetMap&lonlats=5.800,51.000;;15.04113,51.27297;15.00057,51.20102;14.56937,51.16923;14.17123,51.01622;13.49683,50.99802;13.109,50.84482;12.72288,50.81173;11.88048,50.93523;11.48918,50.93857;10.96248,50.90068;10.80378,50.65622;10.56292,50.7653;10.49427,50.84168;10.29067,50.9411;9.7854,50.86585;9.35928,50.84103;9.06777,50.81962;8.66613,50.84693;8.46122,50.92233;7.95032,50.82218;7.28553,50.77698;6.76283,50.65335;6.45257,50.62853;6.15588,50.65872;6.00425,50.98333;5.8668,51.0503

... **Nachtrag**, weil ich das kompliziert geschriebene unter b) jetzt nicht umstricken möchte:
Der leere Waypoint wird nur hinzugefügt, wenn ich im Listing eine korrigierte Koordinate verwende (_hoppla, schnell noch den Spoiler in der URL abändern. ;-)_ )
Nachdem ich die korrigierte Koordinate im Listing entfernt habe, wird die URL normal erzeugt.
Vielleicht wäre es in dem Zusammenhang auch möglich, korrigierte Koordinaten auf jeden Fall ans Ende der Waypointliste hinzuzufügen, weil am Anfang führt es ja zu einer verkorksten "hin-und-her-Routenberechnung"

**Comment by Ruko2010** [comment]
Puh, das klingt aber kompliziert 😃. Ich glaub das muss ich mir mal in ruhe anschauen, aber ich denke ich habe vertstanden was du meinst.
Ich würde es aber glaube ich sinnvoller finden einfach abzufragen, ob der Waypoint leer ist und wenn ja, ihn nicht hinzuzufügen, also irgendwas an der Reihenfolge zu ändern, oder war das mit der Reihenfolge ein "drittes" Problem?

**Comment by radlerandi** [comment]
ja, ich würde auch einfach auf leere Waypoints überprüfen und weglassen.
Das "Hin-und-Her-Routing" ist ja eher ein theoretisches Problem. Man wird ja kaum Multis mit Wegpunkten abfahren, wenn man schon eine korrigierte Listing/Final-Koordinate hat.

**Comment by 2Abendsegler** [comment]
- Der Separator scheint mittlerweile auf der Seite von BRouter umgesetzt zu werden. Ich habe den Separator aber trotzdem auf ";" angepaßt.
- Quasi leere Waypoints scheint es tatsächlich nur bei korrigierten Koordinaten zu geben. Diese Waypoints werden nicht mehr übergeben.

Vorabkorrektur:
https://github.com/2Abendsegler/GClh/raw/brouter_empty_wp/gc_little_helper_II.user.js
(Allerdings sind hier bereits einige weitere Änderungen enthalten. Die zu den neuen Bookmarklisten laufen dabei noch nicht ganz sauber.) 

Zurück auf Original.
https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js
