### ISSUE TITLE
Hide Found Counter

### ISSUE THREAD

**Issue by jagodzinska** [2Abendsegler/GClh#1044]
Hi,

it would be nice if there would be a checkbox to hide the found counter.
Especially in the logs a̶b̶o̶v̶e̶ below every listing.

Cheers
Jago

**Comment by Ruko2010** [comment]
Hi @jagodzinska 
Just to be sure, do you mean this counter above the logs?
![image](https://user-images.githubusercontent.com/2239440/63009510-f2cd1d80-be84-11e9-8c84-c68bd097bf85.png)

**Comment by jagodzinska** [comment]
Hi @Ruko2010 
thanks for your answer.
And sorry, I was to unclear, I mean these found logs:
![Bildschirmfoto von 2019-08-14 11-22-17](https://user-images.githubusercontent.com/30044284/63010056-f57c4280-be85-11e9-911d-9139ad561550.png)

**Comment by Ruko2010** [comment]
Ah ok. A Screenshot is always helpful to be sure to talk about the same thing 😉. 
Sure, no Problem to hide them. But just one question, why 😃?

**Comment by jagodzinska** [comment]
Sorry about the confusion :)

Some cachers are mostly interested in large found counter, often called "statistic cachers". And that is completly fine, everbody can play it like he wants.

But there are also a lot of cachers who play the game for going out & enjoy natures. I often see requests (e.g. in forums) to the HQ to cancel all statistic stuff so that the caches become more qualitative.
When there would be no statistic stuff no one would hide a film can on a street sign beside a busy road I guess ;)

It is very likely that the statistic stuff will stay forever on gc.com but it would be nice if GClh would have an option to hide statistic stuff for those who don't want the "competition".

Of course I just can ignore the numbers below the users name but imho ones brain automatically judges a little bit like "oh just a noob" or "wow some kind of an expert" ;)

Cheers,
Jago

**Comment by Ruko2010** [comment]
Thanks for the explanation. I'll implement a switch in the configuration to hide the logcount. Should be an easy task.

**Comment by Ruko2010** [comment]
This is also done. You can install the development-branch here:
https://github.com/Ruko2010/GClh/raw/issue/1044-hide_find_count/gc_little_helper_II.user.js

Be aware, that you can't test both features at the same time 😉. Tell me if this is what you want. If so, I'll deploy the changes in the next version.

**Comment by jagodzinska** [comment]
Also this one works flawless, thanks :+1:

**Comment by Ruko2010** [comment]
OK great. I'll merge it in the collector and give you the link, so you can install it before the next version come out.

**Comment by Ruko2010** [comment]
You can install the current dev-brache with both features from here:
https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js
