### ISSUE TITLE
Button for hiding lot of stuff in the logs

### ISSUE THREAD

**Issue by jagodzinska** [2Abendsegler/GClh#1045]
Hi,

for checking if the online logger is truly in the offline logbook it would be nice to have a button above the logs like "Hide unimportant stuff" so that you only see username, found and date.

![Bildschirmfoto von 2019-08-14 11-06-01](https://user-images.githubusercontent.com/30044284/63008960-e4323680-be83-11e9-8bbf-d93c0aace79a.png)

Cheers
Jago

**Comment by Ruko2010** [comment]
I'll try something and come back with a screenshot, to see if it fits your needs...

**Comment by jagodzinska** [comment]
Wow that was quick :)

**Comment by Ruko2010** [comment]
Something like this?
![Kapture 2019-08-14 at 12 14 38](https://user-images.githubusercontent.com/2239440/63013721-2744d780-be8d-11e9-8c90-b0dcbaed7d6d.gif)

**Comment by jagodzinska** [comment]
Wow, that is just perfect! Thanks a lot :)

Is it by chance or on purpose that there are only the found logs? It is definitely the desired behaviour :)

**Comment by Ruko2010** [comment]
No Problem. This is just the first draft. I have to make some more changes and make more tests, but I'll come back to you when i'm finished.
This cache was an event, so the last logs were all Attended Logs. But since I just hide some stuff via css, you can use the other "normal" filter logbook functions like showing only the found logs by pressing the found log icon above the logs.

**Comment by jagodzinska** [comment]
Thanks :)

**Comment by Ruko2010** [comment]
Hi @jagodzinska 
I'm finished. You can install the development-branch, if you install it from here:
https://github.com/Ruko2010/GClh/raw/issue/1045-hide_stuff/gc_little_helper_II.user.js

Just click the Link and install it via tampermonkey. You can test it and give me feedback. If everything works as expected, i'll deploy it in the next version of gclh.

**Comment by jagodzinska** [comment]
That's just perfect, tanks! :)

I select the compressed logs and print the selection: ready is my offline checklist :)
