### ISSUE TITLE
Save/Post Log by pressing F2

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#1046]
**Is your feature request related to a problem? Please describe.**
When logging I always have to click the Button "Post" to save the log.

**Describe the solution you'd like**
I would like to just press F2 to post my log as when saving my pocket queries.

**Comment by Ruko2010** [comment]
Hi @Donnerknispel This is already implemented. If it is not working for you, can you describe the bug more in detail.
Please post the following things if possible:
- on which page is the problem (new or old log page)
- OS: [e.g. Windows, MacOS, Linux]
- Browser: [e.g. firefox, chrome, safari]
- Version: [e.g. 22]

**Comment by Donnerknispel** [comment]
Hmmmm, new or old log page?
No idea. On the upper right corner is says "Logging has a new look. Learn more"
So it might be the old log page.

    OS: Windows
    Browser: firefox 68.0.2

**Comment by Donnerknispel** [comment]
![Image 1](https://user-images.githubusercontent.com/7745027/63047818-7b73aa00-bed5-11e9-9aa1-7107b3098588.png)

**Comment by Ruko2010** [comment]
Thanks for the Screenshot. This is the new Logpage. I'll look into this.

**Comment by Ruko2010** [comment]
I'll made an implementation that works for me (on mac). Can you please install it and test it on your system? Just click the link and install it via tampermonkey:

https://github.com/Ruko2010/GClh/raw/issue/1046-save_log_f2/gc_little_helper_II.user.js

**Comment by Donnerknispel** [comment]
It does not work for me. I can see the F2 "hint" on the button and the script is trying to post, but then the "please leave a comment" problem occurs. the text I entered in the textarea was not recognized (see #1038).

how do I get the original script back? Tampermonkey seems to be hanging in a updateloop after installing your script. I even had to deactivate the autoupdate of tampermonkey to open the groundspeak site.

![grafik](https://user-images.githubusercontent.com/7745027/63089692-fb8f2380-bf58-11e9-93ef-55b79d1dc248.png)

**Comment by Ruko2010** [comment]
Have you entered the text in the textbox, or have you inserted a logtemplate (like last log)?

**Comment by Donnerknispel** [comment]
I entered the text directly in the textbox. I did not insert a template do to the known problem.

**Comment by Ruko2010** [comment]
Then it is really strange, because the hit of F2 is just emulating a click on the post button.
Are you able the click the "Post"-Button? Are there any Red-Error Messages in the Console (You can open the console in Firefox by pressing Ctrl+Shift+K). If yes, can you post a screenshot?

**Comment by Donnerknispel** [comment]
Clicking the Post-Button works. Pressing F2 does not work when the Console is not opened.
When the Console is opened F2 does work. Hmmm more than strange.

When opening the Console it looks like this, before pressing F2.
![grafik](https://user-images.githubusercontent.com/7745027/63161955-b256d680-c021-11e9-8992-ee934cfa910c.png)

**Comment by Ruko2010** [comment]
WTF? I'll try to reproduce this. Which Windows Version do you use?

**Comment by Donnerknispel** [comment]
I am on Windows 10.

**Comment by 2Abendsegler** [comment]
Wir hatten das schon mal versucht. Weil es aber nicht stabil lief, haben wir es wieder ausgebaut.
Siehe Changelog v0.9.1 ganz unten (ohne issue).

**Comment by Ruko2010** [comment]
@2Abendsegler Jetzt wo du es sagst, du hast völlig recht. Dann lassen wir das (leider). Tut mir leid @Donnerknispel
