### ISSUE TITLE
Improve new and old log form.

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#1047]
**Describe the bug**
When selecting [Last Cache-Log] as a log template on the "Log this geocache" page, the last log is inserted and an unwanted /unnecessary "log signature" is added too.

**To Reproduce**
1. Go to "Log this geocache" page
2. Selecting the log template [Last Cache-Log]

**Expected behavior**
When selecting [Last Cache-Log] there is no need to add a "log signature" because the signature is already part of the [Last Cache-Log].

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser: firefox 68.0.1

**Comment by Ruko2010** [comment]
Thanks for reporting. I'll look into this.

**Comment by 2Abendsegler** [comment]
@Donnerknispel
Du hast recht, im letzten Log sollte die Signatur bereits vorhanden sein. Ich wollte auch schon Anpassungen am Coding machen als mir auffiel, dass es einen Parameter gibt der unter Anderem genau das steuert. Ich hatte den Parameter "Replace log by last log template" deaktiviert, deshalb kam bei mir die Signatur auch nochmal dazu. 

[Schau mal bitte ob nicht bei Dir dieser Parameter auch deaktiviert ist.](https://www.geocaching.com/my/#GClhShowConfig#a#settings_replace_log_by_last_log) 
![grafik](https://user-images.githubusercontent.com/22332216/68678912-2b04fa80-055f-11ea-83af-88e5aa446ee1.png)

Mir fällt jetzt nicht wirklich eine Situation ein, wann man den deaktivierten Parameter nutzen könnte. Aber es gibt den Parameter nun mal und ich will ihn auch nicht entfernen.

Ist damit das Problem auch bei dir gelöst?

**Comment by Donnerknispel** [comment]
Bei mir war die Option „Replace log by last log template“ nicht deaktiviert, sondern bereits aktiviert.

Dennoch hatte ich das Problem mit der Signatur.

Könnte es sein, dass zwar das aktuelle Log (Initial ist das die „Cache log signature“) durch das Log-Template ersetzt wird, dann aber danach auch wieder die „Cache log signature“ hinzugefügt wird?

 

Schönen Gruß

Olaf

 

Von: 2Abendsegler <notifications@github.com> 
Gesendet: Dienstag, 12. November 2019 15:29
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: Donnerknispel <Donnerknispel@Kaffeeschluerfer.com>; Mention <mention@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Selecting [Last Cache-Log] as a log templates adds an unwanted log signature (#1047)

 

@Donnerknispel <https://github.com/Donnerknispel> 
Du hast recht, im letzten Log sollte die Signatur bereits vorhanden sein. Ich wollte auch schon Anpassungen am Coding machen als mir auffiel, dass es einen Parameter gibt der unter Anderem genau das steuert. Ich hatte den Parameter "Replace log by last log template" deaktiviert, deshalb kam bei mir die Signatur auch nochmal dazu.

Schau mal bitte ob nicht bei Dir dieser Parameter auch deaktiviert ist. <https://www.geocaching.com/my/#GClhShowConfig#a#settings_replace_log_by_last_log> 
 <https://user-images.githubusercontent.com/22332216/68678912-2b04fa80-055f-11ea-83af-88e5aa446ee1.png> 

Mir fällt jetzt nicht wirklich eine Situation ein, wann man den deaktivierten Parameter nutzen könnte. Aber es gibt den Parameter nun mal und ich will ihn auch nicht entfernen.

Ist damit das Problem auch bei dir gelöst?

**Comment by Donnerknispel** [comment]
Ich habe gerade noch einmal getestet.

Die aktivierte Option „Replace log by last log template“ funktioniert bei mir nur, wenn ich als Log-Template das Last-Cachelog wähle. Bei den anderen, d.h. den echten Templates, nicht. Bei den anderen wird dies das Template an der aktuellen Cursor-Position eingefügt.

Das eigentliche Problem bekomme ich aktuell gar nicht mehr reproduziert. Keine Ahnung ob es seit dem eröffnen des Tickets eine neue Version vom GClh gegeben hat, der das gefixt hat.

**Comment by 2Abendsegler** [comment]
> Könnte es sein, dass zwar das aktuelle Log (Initial ist das die „Cache log signature“) durch das Log-Template ersetzt wird, dann aber danach auch wieder die „Cache log signature“ hinzugefügt wird?

Es gibt eine Zeitspanne von 0,1 Sekunden in der

- der Bildschirm im Browser aufgebaut wird und
- man manuell das aktuelle Log mit Hilfe des  "Last Cache-Log"-Template ersetzen muss (mindestens 2 Mausklicks).

Das funktioniert aber nur, wenn im "Last Cache-Log"-Template, also im letzten Log, keine oder eine andere Signatur als in den Einstellungen (GClh Config) vorhanden ist. Und es funktioniert auch nur auf der neuen Logseite.

Es ist also theoretisch möglich, aber unwahrscheinlich, insbesondere wenn es mehrfach passierte.

> Die aktivierte Option „Replace log by last log template“ funktioniert bei mir nur, wenn ich als Log-Template das Last-Cachelog wähle. Bei den anderen, d.h. den echten Templates, nicht. Bei den anderen wird dies das Template an der aktuellen Cursor-Position eingefügt.

Ja, die Option „Replace log by last log template“ gilt nur für das "Last Cache-Log"-Template. 

Ja, bei den anderen Templates soll quasi das Log nur ergänzt werden. Du kannst aber Text mit der Maus markieren und damit diesen markierten Text mit einem der anderen Templates ersetzen. Markierst du also den gesamten Text dann wird auch der gesamte Text ersetzt, also wie beim "Last Cache-Log"-Template. 

> Das eigentliche Problem bekomme ich aktuell gar nicht mehr reproduziert. 

Ich kann das nur wie oben beschrieben reproduzieren, wenn ich die Zeitspanne durch eine Programmänderung auf 5 Sekunden erhöhe.

> Keine Ahnung ob es seit dem eröffnen des Tickets eine neue Version vom GClh gegeben hat, der das gefixt hat.

Die letzte Version ist vom Mai 2019, ist also theoretisch möglich wenn du diese Version etwa 6 Monate verspätet implementiert hättest.

Fragen:

- Warst du auf der neuen Logseite?
- Kannst du dich erinnern, ob es damals mehrfach passiert ist?

**Comment by Donnerknispel** [comment]
Ich war auf der neuen Logseite
Damals konnte ich das auch mehrfach machen.

Im Grund kann das Ticket mit der aktuellen GClh Version geschlossen werden.

Mein Fehler war, dass ich den Begriff "Log-Template" anders interpretiert habe!!
Ich bin davon ausgegangen, dass mit dem "Log-Template"  der **gesamte** Log Eintrag **ersetzt** wird, statt Text an der aktuellen Stelle bzw. dem markierten Text **einzufügen**.
Mit der Erkenntnis passe ich gleich meine paar "Log-Templates" an und entferne aus denen die Signatur. Danach sollte das Problem verschwunden sein. Bei einem Aufruf des Log-Dialogs enthält das Feld lediglich die Signatur und der Cursor steht darüber. Wenn ich dann ein Template wähle, dann wird die wie bisher auch eingefügt. Da die "Log-Templates" aber jetzt keine Signatur mehr enthalten haben ich keine doppelten Signaturen mehr.
So ein Mist. Tut mit Leid, dass ich das erst jetzt kapiert habe.

**Comment by 2Abendsegler** [comment]
Ok, jetzt verstehe ich wie du es hinbekommen hast.

> So ein Mist. Tut mit Leid, dass ich das erst jetzt kapiert habe.

Hey, das ist überhaupt nicht schlimm. Das Thema Logs schreiben ist von der Programmierung her ziemlich aufwendig und es gibt zahlreiche Besonderheiten und Gedöhns. Ich blick da auch manchmal nicht mehr durch, siehe Option „Replace log by last log template“ 🙄. Ist doch gut, so hatte ich Gelegenheit es mir mal wieder anzusehen. 😉

Wir sind froh wenn uns die User Bugs melden weil wir ja auch nicht die gesamte Funktionalität selbst nutzen. Daß dann mal was dabei ist was gar kein Bug ist, so what. Also weiter so ... 😊

_(Ich kann und werde die genannte Zeitspanne reduzieren. Dafür werde ich dieses Issue verwenden. Ich schließe es also erst wenn das durch ist.)_

**Comment by 2Abendsegler** [comment]
Improve new and old log form. Show log preview on log page direct after automatic adding log signature, using log templates and using smilies. Make sure that signature is not generated multiple times.
