### ISSUE TITLE
Hide own found counter

### ISSUE THREAD

**Issue by jagodzinska** [2Abendsegler/GClh#1051]
I am not sure if I should re-open the old feature request https://github.com/2Abendsegler/GClh/issues/1044 for this or create a new one.

I hope creating a new one was right. It is the same topic as described in the link above but technically it is different.

It would be also nice to be able to hide the own found counter one sees on every page

![Bildschirmfoto von 2019-08-23 15-05-21](https://user-images.githubusercontent.com/30044284/63594737-8d310d80-c5b7-11e9-84c5-43665d7425b7.png)

The reasons for this are the same as in the other issue.

This request isn't urgent it just would be nice to be integrated sometime :)

Cheers 
Jago

**Comment by Ruko2010** [comment]
Hi Jago,

I'm affraid, this is a feature that is not used by other people than you, so it's nothing I'll implement in GClh II.

But you can add this function for yourself, just for you. Go to the Tampermonkey-Script Overview and hit the littel "Plus" to add a new Script. Paste this code there:

```
// ==UserScript==
// @name         MyOwnGeocachingScript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @include      http*://www.geocaching.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    var css = ".li-user .cache-count{display: none !important;}";
    var head = document.getElementsByTagName('head')[0];
    var s = document.createElement('style');
    s.setAttribute('type', 'text/css');
    if (s.styleSheet) {   // IE
        s.styleSheet.cssText = css;
    } else {                // the world
        s.appendChild(document.createTextNode(css));
    }
    head.appendChild(s);
})();
```
