### ISSUE TITLE
[New BML] New designed list of bookmarklists and bookmarklist - 1. Header

### ISSUE THREAD

**Issue by anvanlaer** [2Abendsegler/GClh#1052]
Hi,

There is a new list interface rolled out.  Of course now the buttons for a list don't appaer ;(
I would love to see the button show additional information back.

An

**Comment by 2Abendsegler** [comment]
Hi,
can you please let us know some more information? Do we talk about bookmark lists or pocket queries? Which buttons do not appear?
Thanks.

**Comment by anvanlaer** [comment]
Groundspeak is rolling out a new interface for the lists.  So the pages My lists and when you open a list are changed.

Attached are 2 screenshots from the pages (in Dutch).

![2019-10-11 19_05_47-Window](https://user-images.githubusercontent.com/4437672/66670494-3a401200-ec5a-11e9-832d-3d42bc2f808f.png)
![2019-10-11 19_05_28-Window](https://user-images.githubusercontent.com/4437672/66670495-3a401200-ec5a-11e9-9622-146fda44ae3c.png)

**Comment by 2Abendsegler** [comment]
Release Notes: https://forums.geocaching.com/GC/index.php?/topic/353571-release-notes-website-progressive-release-lists-september-23-2019/

> When will you see the new List experience?
As mentioned above, we recently began deploying this feature. It will slowly roll out to geocachers over a period up to 8 weeks. This is to ensure a quality release with minimal bugs. You may see the new List experience today or you might not see it until the release is fully rolled out in late October. ....


New: https://www.geocaching.com/plan/lists
Old: https://www.geocaching.com/account/lists
...

We in germany don't  see the new list. I'm afraid we have to wait with our changes until we can see the new lists also.
If you don't prefer the new list, you can try to change the links manually as a workaround. Replace "plan" with "account".

Thanks for the message.

**Comment by 2Abendsegler** [comment]
Message geoclub: https://geoclub.de/forum/viewtopic.php?p=1301252#p1301252

**Comment by anvanlaer** [comment]
Sadly manually changing the URL doesn't work.  It gets redirected to the new links.

**Comment by 2Abendsegler** [comment]
That is bad. 

I tried to change my home location to Amsterdam, but this don't bring me to the new designed pages. I don't know at the moment how the new pages is controlled. Perhaps @Ruko2010 has an idea, tomorrow. 

You could try to change your home location temporary to a location in germany. It is not very probable, but more ideas I don't have at this moment.

**Comment by Ruko2010** [comment]
Sorry, I‘m on vacation without access to an computer. But i‘ll look at it when I come back next weekend.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Noch schöne Tage!

**Comment by Ruko2010** [comment]
I can see the new List now, I'll look into it.

**Comment by Ruko2010** [comment]
@2Abendsegler Groundpeak changed the header again. Now it's even an other header than used in the new map, thats why all header changes are not working.
Also, we have to check with of the old bookmark/lists buttons/features we want to implement on the new lists.

I think the Main goal should be to adapt the header of lists page and maps page.

@anvanlaer what function exectly do you need on the new listview? Things like "Show number of caches in bookmark lists" is implemented by Groundspeak itself, so we don't need to reproduce it.

**Comment by anvanlaer** [comment]
@ruko2010. I would love to see the function again to show if a cache has corrected coördinates

**Comment by 2Abendsegler** [comment]
@Ruko2010 
• Header: Maybe we only need to include the links in is_page. I have not looked in yet.
• Button Corrected Coordinates: Yes
• Buttons to choose caches: All, Invert, found, archived, past events.
• The map links in the list of bookmarklists and in the bookmark lists go to the search-map: Optional browse-map would be nice.

My computer is still not repaired (shame on me). Maybe this is good pressure for me finally to tackle the topic.

**Comment by 2Abendsegler** [comment]
• Show as maximum 1000 caches and not only 500: How it could work: https://forums.geocaching.com/GC/index.php?/topic/353571-release-notes-website-progressive-release-lists-september-23-2019/&do=findComment&comment=5798938

**Comment by 2Abendsegler** [comment]
• Percentage of favorites

To • Button Corrected Coordinates: GS works on a solution. https://forums.geocaching.com/GC/index.php?/topic/353571-release-notes-website-progressive-release-lists-september-23-2019/&do=findComment&comment=5799121

Perhaps we should wait with development until GS has a final version of the bookmarklists.

**Comment by Ruko2010** [comment]
> @Ruko2010. I would love to see the function again to show if a cache has corrected coördinates

I read in the GS-Forum, that GS is working an this, so we will leave the feature out of our roadmap for now.

@2Abendsegler 
I'd like to see (in this order):
1. Header
2. Show 1000 Caches instead of 500
3. Buttons to select the caches
4. Link to browsemap

**Comment by Ruko2010** [comment]
@2Abendsegler also ich weis nicht was sich GS da wieder hat einfallen lassen. Man kann unseren Helper aktivieren, wenn man die Zeile 1021 folgendermaßen ändert:
```// Wenn nicht angeloggt, dann aussteigen.
   if (
        !$('.li-user-info')[0] &&
        !$('.username-display') &&  // Aktivierung auf "neuer Listen" Seite
        !$('.profile-panel-user')   // Aktivierung auf neuer Searchmap
    ){
        return;
   }```

Leider gibt es unterschiedliche Header auf der SearchMap und der Listenseite. Die Aktivierung des Scripts auf der Listenseite macht schon mal ein paar Kleinigkeiten, aber noch längst nichts alles:

Ich habe ein wenig die Befürchtung, dass wir hier einiges an Arbeit investieren müssen, und das es am Ende doch nur Flickwerk wird. Aber ich hab aktuell noch keine Idee, wie man es besser machen kann. Da muss ich erstmal drüber nachdenken.

**Comment by Ruko2010** [comment]
@2Abendsegler ich hab mal etwas drüber nachgedacht. Vielleicht wäre es Sinnvoll die Header Funktionen so zu bauen, dass man sich erst die Daten die man braucht erzeugt (welche Links sollen angezeigt werden, wie viele Drafts hat man, usw.) und die Daten dann in eine "Ausgabefunktion" schickt. Diese entscheidet dann anhand der aktuellen Seite, welchen Header man gerade vor sich hat und wie die Daten in diesem angezeigt werden müssen.
So könnte man 1. relativ "schnell" neue Ausgaben hinzufügen, wenn sich GS wieder einen neuen Header ausdenkt und 2. könnte man im code schnell die Stellen finden, die an gepasst werden müssen, falls es wieder eine Headeränderung gibt.

Ich werde das mal beispielhaft für das Draft Icon am Benutzername in einem Branch implementieren, damit du weist was ich meine.

**Comment by 2Abendsegler** [comment]
Alles was zur Vereinfachung zukünftiger Entwicklungen beiträgt, ist in der Regel eine gute Sache. Hier speziell bin ich mir nicht sicher ob sich der vermutlich hohe Aufwand und Testaufwand lohnt. So  viele neue Header wird es nicht mehr geben, es sind doch schon fast alle Seiten umgestellt. Und womöglich haben wir dringendere Dinge zu tun.
Ich werde mir aber Implementierungen ansehen.

Vielleicht kann ich mir das die Tage auch mal ansehen, schließlich stammt ja noch ziemlich viel für den Header aus meiner ungeübten Feder.

**Comment by Ruko2010** [comment]
Naja, hoher Aufwand kann man so nicht sagen. Ich weis leider nicht wie Aufwendig es wird. Aber wenn wir nun Stück für Stück die Ausgabe an 3 verschiedene Header anpassen müssen, dann macht es eher sinn das an einer Stelle im Code zu tun (pro Funktion) und nicht im aktuellen Code "herumzuwurschteln".

Ich werde mal schauen ob sich folgendes vorgehen gut umsetzen lässt:

1. Ausgaben in der Funktion bündeln
2. Ausgaben in eine eigene Funktion auslagern
3. Weichen für einen neuen Header einbauen
4. Ausgabe für die einzelnen Header umsetzen.

**Comment by Ruko2010** [comment]
Schau mal hier: https://github.com/Ruko2010/GClh/tree/feature/newheader

**Comment by 2Abendsegler** [comment]
Ja, so könnte man es machen, das wäre sicherlich sauberer.

Andererseits kennst du aber meine Devise, nichts an einem laufenden System zu ändern es sei denn es ist absolut notwendig. Hinzu kommt dass bei mir ziemlich die Luft raus zu sein scheint was die Arbeiten hier angehen, und irgendwie sehe ich auch Zeichen dafür bei dir. Vielleicht sollten wir uns auf die wirklich notwendigen Sachen konzentrieren: Bookmarkliste und scheiß Karte und ?

Aber das ist deine Entscheidung.

---
Echt zum k... . Die haben tatsächlich den kompletten Header neu erfunden, dabei hatten sie die Dinge gerade einigermaßen vereinheitlicht. Logo, Menüs, Menünamen, und den Schrott rechts im Header den du ja schon kennst. Es funktioniert also rein gar nichts mehr im Header.

**Comment by 2Abendsegler** [comment]
Laß uns vielleicht für die Punkte eigene Issues aufmachen. Header könnten wir hier machen. 2, 3 und 4 in eigenen Issues. Was meinst du?
1. Header
2. Show 1000 Caches instead of 500
3. Buttons to select the caches
4. Link to browsemap

**Comment by Ruko2010** [comment]
> Andererseits kennst du aber meine Devise, nichts an einem laufenden System zu ändern es sei denn es ist absolut notwendig.

das ist klar, aber wie wollen wir es machen? Willst du für jeden header die Ausgaben einzeln schreiben? Ich denke wir müssen es so oder so umbauen, da können wir es auch gleich "richtig" machen.
Leider ist GS in letzter Zeit nicht sehr gnädig mit uns und baut viel um und die Frage ist, wann sie damit fertig sind. Leider hat die Seite für mich kein ganzheitliches Konzept mehr.

> header könnten wir hier machen. 2, 3 und 4 in eigenen Issues.

Ja das klingt gut.

<hr>
Offtopic: Ich hab zur Zeit irgendwie keine Motivation hier im GClh was zu machen. Geocaching tritt bei mir gerade ein wenig in den Hintergrund, da mich die Familie zeitlich sehr beansprucht (was aber natürlich positiv gemeint ist 😉, nur halt negativ für den GClh). Das sieht man schon an der Statistik. 2019 ist mein Jahr mit den zweitwenigsten Funden.
Das sieht man glaube ich auch daran, wie viel (bzw. wie wenig) in den letzten Monaten geschehen ist.
Leider baut GS ja anscheinend alle auf Asynchronität, so dass wir es mit unseren Sachen schwer haben da einzugreifen, weil man ständig warten muss, ob irgendwelche Elemente da sind oder nicht. Irgendwie macht es das sehr schwer zu arbeiten und zu erfolgen zu kommen. Vielleicht wird es in den Wintermonaten nun wieder etwas besser (hoffe ich zumindest)

**Comment by 2Abendsegler** [comment]
Offtopic: So etwas in der Art habe ich mir schon gedacht.
Ich würde gerne selbst wieder in den collector mergen. Insbesondere damit ich bei den nächsten issues auf die anderen aufbauen kann. Ist das ok?

**Comment by Ruko2010** [comment]
Na klar, gerne. Ich sehe es immer noch so, dass wir hier gleichberechtigt arbeiten 😉. Darum tu dir keinen Zwang an.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Nicht genug damit dass die Daten auf der neuen BML Seite "irgendwann" geladen werden, das gleiche passiert auch mit den drei Buttons und insbesondere auch mit dem Header. Zu Beginn ist der Header auch noch nicht da. Auf so etwas sind wir aber nicht vorbereitet und bevor ich jetzt an dem gesamten Coding zum Header bastele und noch nicht mal weiß ob ich es hinbekomme habe ich einen anderen Weg versucht. Bitte schau dir den Weg mal an, ob wir das so machen wollen. Sieh mal darüber hinweg, dass das Menü noch nicht richtig ist, ich habe an dieser Stelle noch nichts gemacht. Es geht mir nur um den Weg.

Ich habe Teile des CoreCSS, bekannt von allen anderen GC Seiten, bei uns integriert.
https://github.com/2Abendsegler/GClh/blob/coreCSS/data/coreCSS.css

Im Coding vor dem Aufruf von mainGC wird der Zwischenschritt asynchronGC eingelegt. Dort wird mit $.get eine andere kleine GC Seite geladen um von dort das html vom Header zu entnehmen. Anschließend wird dieses hmtl in die BML Seite eingebaut und der dortige Header ausgeblendet. 
https://github.com/2Abendsegler/GClh/raw/coreCSS/gc_little_helper_II.user.js

Anschließend wird dann ganz normal mainGC aufgerufen, das noch quasi unverändert ist was den Header betrifft. Wie geschrieben funktioniert noch nicht alles, drei vier Kleinigkeiten müssen dort noch gemacht werden. Bevor ich jedoch hier weitermache möchte ich mich zum Weg abstimmen.

Danke und LG Frank

**Comment by Ruko2010** [comment]
Also wenn ich es richtig verstehe, dann holst du dir den Header von einer anderen Seite, und lädst diesen dann in die aktuelle Seite? Das ist aber echt von hinten durch die Brust 😃.
Klar hat das den Vorteil, dass wir den Header nicht neu machen müssen, aber seien wir mal ehrlich, irgendwann wir GS sicher alle Seiten umbauen, dann stehen wir vor dem gleichen Problem.

Wie wäre folgender Ansatz:
Wir bauen vor dem mainGC eine Funktion ein, die wartet bis der Header da ist.
Im "normalen" Fall sollte das ja sofort sein. In den Fällen von Maps und BML halt etwas später.
Überwachen könnte man das ganze mit dem "[MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver)". Den haben wir auch schon im Einsatz beim MapPopup und bei der Personal Cache Note.

Was hälst du davon?
Klar müssen wir dann den Header trotzdem neu bauen für die beiden Seiten, aber dann wäre es wenigstens "richtig".

**Comment by 2Abendsegler** [comment]
Es geht doch genau darum dass GS noch weitere Seiten umstellen wird und wir dann jedesmal eine Menge Arbeit haben alleine um den Header richtig aufzubauen.

Mein Ansatz geht nun den Weg, dass wir die Seiten mit einem anderen Header betreiben um uns eine Menge Arbeit sparen. 

Ich warte auch bereits auf den Header, aber nur dafür damit ich ihn austauschen kann.

Um den beiden neuen Seiten BML und Searchmap einen funktionierenden Header zu verpassen, habe ich die Seiten lediglich an zwei Stellen eingetragen und im asynchronGC den Punkt festgelegt, an dem der Code zum Header eingefügt werden soll. 

Weiter habe ich noch nichts gemacht. Das würde auch für neue Seiten gelten. Im Idealfall funktioniert der Header auf Anhieb, so wie bei der BML.

Auf der BML Seite ist schon alles ok, nichts weiter notwendig.

Auf der Searchmap Seite muss das Menü etwas nach oben geschoben werden und das neue Ladeicon muss verschwinden. Ansonsten ist auch schon alles ok.

Lade dir mal das geänderte [Script](https://github.com/2Abendsegler/GClh/raw/bml_header/gc_little_helper_II.user.js). Und schau dir die beiden neuen Seiten BML und Searchmap an. Ich habe hier quasi den Header noch nicht angepaßt. Ich habe die Seiten nur mit wenigen Handgriffen für die neue Verarbeitung vorbereitet, wie oben beschrieben.

**Comment by Ruko2010** [comment]
Ok, das sieht tatsächlich gut aus 😃. Dann machen wir das so und hoffen, dass die Seite von der du dir den header klaust noch lange erhalten bleibt 😉

**Comment by 2Abendsegler** [comment]
Die Seite verwenden wir nur, damit wir Neuerungen in den GC Menüs mitbekommen. Ich hab mir natürlich den Code auch gesichert, falls es irgendwann keine alten Seiten mehr gibt.

Dann mach ich mal damit weiter.

Danke fürs das Feedback.

**Comment by 2Abendsegler** [comment]
Die Änderungen kommen mit der nächsten Version.
