### ISSUE TITLE
One click ignoring/restoring.

### ISSUE THREAD

**Issue by MarcusBi** [2Abendsegler/GClh#1053]
Is it possible to remove the extra page with the confirmation buttons to put a cache on the ignore list? An "one click ignore" would be great ;-)

**Comment by Ruko2010** [comment]
Year, should be possible. We put it on the roadmap.

**Comment by 2Abendsegler** [comment]
@MarcusBi 
Hey,

die Erweiterung ist soweit fertig. Magst du mal drüberschauen?

[Hier](https://www.geocaching.com/my/#GClhShowConfig#a#settings_use_one_click_ignoring)  geht es zu den Einstellungen. Gegebenenfalls muss hier noch der Parameter _Show "Stop Ignoring", if cache is already ignored_ aktiviert werden.
Du kannst [hier](https://github.com/2Abendsegler/GClh/raw/one_click_ignoring/gc_little_helper_II.user.js) den GClh mit den Änderungen installieren um zu testen. 
Anschließend kannst du [hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) den GClh im Original wieder installieren. 

Bitte gib bescheid wenn noch etwas zu tun ist oder wenn wir es so für die nächste Version vorsehen können.

**Comment by MarcusBi** [comment]
Hallo Frank,

funktionier perfekt - genau so hab ich mir das vorgestellt. Analog könnte man jetzt diese Funktion auch für die Watchlist umsetzen. Ist ja manchmal auch ein wenig nervig dass, wenn man einen Cache auf die Watchlist setzen möchte, immer einen neue Seite geladen wird, man dort den Vorgang bestätigen und dann anschließend manuell wieder zurück ins Listing muss. Ich denke mal, dass es von der Implementierung her recht ähnlich sein wird. Soll ich dafür einen neuen Issue aufmachen?

LG und schönes WE,
   Marcus aka Herr Ma

**Comment by 2Abendsegler** [comment]
Hallo Marcus,

> Analog könnte man jetzt diese Funktion auch für die Watchlist umsetzen. Ist ja manchmal auch ein wenig nervig dass, wenn man einen Cache auf die Watchlist setzen möchte, immer einen neue Seite geladen wird, man dort den Vorgang bestätigen und dann anschließend manuell wieder zurück ins Listing muss. Ich denke mal, dass es von der Implementierung her recht ähnlich sein wird.

Ja genau, das war auch mein Gedanke, muss doch in einem gehen. Aber es wäre nicht GS, wenn sie auch hier nicht das Rad wieder mal neu erfunden hätten. 🤣
So wie wenn man es manuell macht, die Prozesse sind völlig anders. Einen Cache in die Watchliste ablegen, das geht vermutlich noch. Wie man den Cache dort wieder rausbekommen soll, erschließt sich mir aber im Moment gar nicht. 

Ich mach jetzt das hier mal für die neue Version fertig und mach mir keinen Kopf um die Watchliste. 🙄

LG, dir auch ein schönes WE,
Frank
