### ISSUE TITLE
Show unpublished caches in dashboard and show compact layout on unpublished caches page.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1055]
>  Moin,
> ist es Möglich in das Dashboard zwei weitere Felder einzufügen:
> - Benötigt Wartung
> - Unpublished Caches
>
> Benötigt Wartung gibt es ja schon von GC, aber das basiert auf irgend einem Algorithmus, der nicht gerade viel bringt. Besser ist es die Liste so zu haben wie bei PGC (https://project-gc.com/Profile/NeedsMaintenance)
> Für nicht veröffentlichte Caches gibt es ja auch eine Seite, aber die ist unübersichtlich, wenn man mehr als 10 hat.

https://geoclub.de/forum/viewtopic.php?p=1301377#p1301377

(Mir ist im Moment nicht ganz klar um was es hier geht.)

**Comment by Ruko2010** [comment]
Hi @capoaira
Zu benötigt Wartung:  Die Liste bei Project GC ist bei mir leider leer (anscheinend sind meine Caches gut gewartet 😃). Darum weis ich nicht wie die aussieht und welche Kriterien für deren Erstellung genutzt werden. Vielleicht kannst du das rausfinden und hier nochmal genau aufschreiben, gern auch mit Screenshot.

Zu Unpublished Caches: 
Auch hier wäre eine konkrete Vorstellung gut, was genau du haben willst. Nur zu sagen "Die ist unübersichtlich" ist leider keine gute Aufgabenstellung 😉. Du kannst auch gern eine kleine Zeichnung machen, wie du es dir vorstellst, muss nicht hübsch sein, nur informativ.

**Comment by capoaira** [comment]
Moin, 
bei den Benötigt Wartung von GS werden nur die Aufgelistet, die in irgend soeinem Algorithmus auffallen. Das müssen nicht unbedingt Caches sein, die wirklich Wartung benötigen.
Bei PGC werden als erstes die mit NM oder NA logs auflistet, dann die mit DNFs und zum Schluss die deaktivierten. 

Die unpublished Caches sind im alten Profil nach Namen sortiert. Im  euen Design kann ich nicht sagen, wonach die sortiert sind. Ich hatte mir soetwas wie ein kompaktes Layout (wie im Dashboard) und eine neue Sortierung vorgestellt.

Heute Nachmittag folgen noch Zeichnungen.

PS.: Wie habt ihr JavaScript gelernt? Ich habe mich schon etwas damit beschäftigt, aber komme nicht wirklich weiter.

**Comment by 2Abendsegler** [comment]
Off-Topic:
Die kleinen Aufgabenstellungen waren es auch hauptsächlich bei mir, zusammen mit Beispielcoding. Ich habe beim GClh einfach irgendwo im Coding begonnen und mir angesehen was das Coding macht und ob es noch funktioniert. Wenn nicht, was gefühlt quasi immer der Fall gewesen ist, hatte ich ja eine gute Vorlage wie es ursprünglich mal funktionierte. 
Das war ziemlich zeitaufwendig, insgesamt, aber ich war damals über Monate krank, insofern nicht schlimm. Und ich hatte halt keine Lust, trocken vor mich hin zu lesen. 
Besonders nett war die Tatsache, dass ich auch relativ schnell kleinere Erfolgserlebnisse hatte, weil es oft ja nur an Kleinigkeiten lag, dass etwas nicht mehr funktionierte. 
Wenn ich nicht weiterkam wurde ich häufig bei https://wiki.selfhtml.org fündig.

**Comment by capoaira** [comment]
Moin,
das Bild ist nicht so schön geworden, aber sollte (hoffentlicht) informativ sein ;)

![GClh](https://user-images.githubusercontent.com/50927164/68220319-d48c3f00-ffe7-11e9-8083-123f525a7b59.png)
Sortiert nach Status (wenn das geht) sonst nach GC-Code
Ich weiß nicht, wie oder ob das mit dem Status umsetzbar ist, aber wenn es geht wäre folgendes schön:
Deaktiviert => Cache nicht eingereicht oder wurde vom Owner/Reviewer deaktiviert
Waiting for Review => Cache eingereicht. Noch keine Antwort
Publish um ... => Der Cache ist vom Reviewer bis zum Publish gesperrt.

Off-Topic:
Ok, danke. Bei mir ist es auch meistens so, dass es nicht funktioniert. Nur das ich bei js meine Fehler meistens nicht finde. Das habe bei HTML, CSS, PHP, Google App Inventor uns scratch besser hinbekommen. Meistens habe bei js immer entnervt aufgegeben. Ich werde aber auf jeden Fall weiter machen.

**Comment by capoaira** [comment]
Off-Topic:
ich habe mich in den letzten Tagen nach der Schule intensiv mit js beschäftigt und selber ein Script für Tampermonkey geschrieben: https://github.com/capoaira/MyQuickLinks
Erst war ich voll Stolz, da alles funktioniert hat (in meinem Test Dokument), doch jetzt funktioniert nicht mal mehr das aufklappen... gibt es irgendetwas was man beachten muss zwischen Scripten in einem HTML-Dokument und Scripten, die von Tampermonkey hinzugefügt werden? Denn auf einmal gibt es eine existierende Function nicht mehr.

**Comment by Ruko2010** [comment]
Wenn dein Script lokal, aber nicht in Tampermonkey funktioniert dann kann es daran liegen, dass TM gewisse zugriffsrechte nicht hat (und auch nie bekommen wird 😉). Eventuell schaust du dich mal in TM Foren um, ob du da die Funktion (bzw. ein equivalent) findest, dass eventuell TM bereit stellt.
Manche Sachen gehen aber auch einfach nicht. Gerade der Zugriff auf Lokal Storage und ähnliches ist schwierig.

**Comment by 2Abendsegler** [comment]
Off-Topic:
Ich hab eigentlich keine Ahnung von Javascript und Web Entwicklungen, insofern sind meine Aussagen mit Vorsicht zu genießen. 
Ich glaube du hast dir mit dem Thema Interaktionen mit der lokalen Plattform ein schwieriges Thema ausgesucht um mit Javascript unter Tampermonkey anzufangen. Meines Erachtens wäre es einfacher in diesem Umfeld auf etwas Vorhandenes aufzubauen, also beispielsweise in einem anderen, bereits vorhandenen Script, Kleinigkeiten zu ändern, eben in winzigen Schritten. Ich hab mich in dieser Art und Weise an Javascript angenähert.

**Comment by capoaira** [comment]
> Manche Sachen gehen aber auch einfach nicht. Gerade der Zugriff auf Lokal Storage und ähnliches ist schwierig.

Ah, ich habe den Fehler gefunden `onclick="function"` funktioniert bei Tampermonkey nicht...

> Ich glaube du hast dir mit dem Thema Interaktionen mit der lokalen Plattform ein schwieriges Thema ausgesucht um mit Javascript unter Tampermonkey anzufangen. Meines Erachtens wäre es einfacher in diesem Umfeld auf etwas Vorhandenes aufzubauen, also beispielsweise in einem anderen, bereits vorhandenen Script, Kleinigkeiten zu ändern, eben in winzigen Schritten. Ich hab mich in dieser Art und Weise an Javascript angenähert.

Wahrscheinlich ist das das Problem bei mir, ich nehme mir zu viel vor und scheitere dann. 

Ich versuche trotzdem dran zu bleiben und irgendwann klappt es dann (hoffentlich)

Danke für die Hilfe und Tipps

**Comment by capoaira** [comment]
Moin,
mein Script läuft jetzt endlich zufriedenstellend. Und zum Üben habe ich dann nochmal TicTacToe Programmiert. Funktioniert auch :)

Jetzt wollte ich mich an diesen Issue setzten, aber den GM_xmlhttpRequest verstehe ich nicht mal ansatzweise... Im Netz habe ich nichts gefunden, zu mindestens nichts, was ich verstehe. Englisch ist leider nicht so mein Fall...
Könnt ihr mir das vielleicht erklären?

Gruß capoaira

**Comment by 2Abendsegler** [comment]
Ein klein wenig englisch:
https://wiki.greasespot.net/GM.xmlHttpRequest
Es geht also in der Sache um einen XMLHttpRequest:
https://wiki.selfhtml.org/wiki/JavaScript/XMLHttpRequest

**Comment by Ruko2010** [comment]
@capoaira den brauchst du doch nicht unbedingt, oder? Schau vielleicht mal in den Code vom Helper, Irgendwo um Zeile 1534 in die Funktion
`// Show draft indicator in header`
Vielleicht hilft dir das weiter. Du kannst eine andere Seite auch mit jQuery abfragen. In der Funktion suchen wir die Anzahl der Drafts um Sie als Icon am Useraccount zu zeigen.

```
$.get('https://www.geocaching.com/account/dashboard', null, function(text){

    // Look for drafts in old layout
    draft_list = $(text).find('#uxDraftLogs span');
    if(draft_list != null){
        drafts = draft_list[0];
    }else{
        drafts = false;
    }

    if(!drafts){
        // if not found, Look for drafts in new layout
        draft_list = $(text).find("nav a[href='/my/fieldnotes.aspx']");
        if(draft_list != null){
            drafts = draft_list[0];
        }else{
            drafts = false;
        }
    }

    if(drafts){
        var draft_count = parseInt(drafts.innerHTML.match(/\d+/));
        if(Number.isInteger(draft_count) && draft_count > 0){
            // we found drafts, so show them in the header
            displayDraftCount(draft_count);
        }else{
            // No drafts found
        }
    }else{
        // Non of the content was found
        // This should not happen, only if GC changes something
    }
});
```

**Comment by capoaira** [comment]
Danke für den Tipp. Ich habe zwar noch nie mit jQuery gearbeitet, aber das sieht wesentlich verständlicher aus, als der request. Wenn ich nicht so viele Hausaufgaben bekomme setzte ich mich nach der Schule mal daran.

Gruß capoaira

**Comment by 2Abendsegler** [comment]
Wie jetzt? Und mein Tipp war nichts gut? 🤣
Der zweite Link war sogar in Deutsch. 😁

**Comment by capoaira** [comment]
Ich wollte dich nicht beleidigen 😊😉
Ich habe ja selber schon gegoogelt, bevor ich gefragt hatte, aber hatte es nicht verstanden. Die XMLHttpRequest ist mir einfach zu hoch😣😊

**Comment by 2Abendsegler** [comment]
... ja, der ist ja auch nicht ohne. Ruk2010 hat schon recht. 😊

**Comment by capoaira** [comment]
Moin,
ich bin es schon wieder... ;)
Mit `$.get` komme ich besser klar und habe nun auch [etwas vorzeigbares ](https://github.com/capoaira/GClh/tree/Issue-%231055)😊
Hat einer von euch zufällig ein Cache der in den nächsten Tagen gepublished wird? Ich bräuchte die id für die grüne oder blaue Infobox, wenn ein Cache vom Reviewer geprüft wurde und an einem bestimmtem Datum gepublished wird. 
Wie macht ihr das eigentlich mit den GClh Einstellungen? Ich weiß nicht, wo ich was und wie einfügen soll.

**Comment by 2Abendsegler** [comment]
> Wie macht ihr das eigentlich mit den GClh Einstellungen? Ich weiß nicht, wo ich was und wie einfügen soll.

Was meinst du hier genau? 
Falls es um einen neuen Parameter geht, der im GClh Config aufgenommen werden soll, dann wäre der Bereich Dashboard hier wohl der richtige Platz. Nimm dir am Besten einen anderen Parameter als Beispiel und mach all das was auch für den alten gemacht wurde.

**Comment by capoaira** [comment]
> Nimm dir am Besten einen anderen Parameter als Beispiel und mach all das was auch für den alten gemacht wurde.
Ok, hat funktioniert. Ich habe nun auch ein Cache im Review und sobald ich die letzte id für die Statusmeldungen habe ist die Unpublished liste Fertig. Wenn ich das richtig verstanden habe muss ich dann ein Pull request machen, oder?

**Comment by 2Abendsegler** [comment]
Genau, einen Pull Request zu uns in die Branch Collector.

**Comment by capoaira** [comment]
Moin,
für das Benötigt Wartung Tool muss ich einige requests (oder wie das mit jquery heißt) machen. Das dauert relativ lange, aber das Script läuft weiter bevor das Array mit den Caches voll ist.
Im Netz finde ich nichts passendes. Habt ihr eine Idee?

**Comment by capoaira** [comment]
Ich habe das Kompakte Layout für die nicht gepublishten Caches schon mal hinzugefügt.
Die anderen beiden folgen dann später...

**Comment by capoaira** [comment]
Moin,
das sollte nun die fertige Lösung sein. 

Zu den Need Maintenance: Man muss alle eigenen, aktiven Caches anfragen, das heißt, dass (zu mindestens bei meiner Anzahl an Caches) die "Zuletzt aufgerufenen" immer die Eigenen Caches zeigen. Das nervt noch mehr, als ein fehlendes NM-Tool. 

Wenn der Pull Request angenommen wurde, kann dieser Issue von mir aus geschlossen werden, es sei denn, es gibt noch eine andere Möglichkeit...

**Comment by 2Abendsegler** [comment]
> Ich will mich nochmal für Eure Hilfe bedanken

Gerne! Und es ist schön einen neuen Mitstreiter zu haben. 😊

**Comment by 2Abendsegler** [comment]
merged
