### ISSUE TITLE
Prepare go live v0.10

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1056]
- [x] [01] Prepare changelog for new version.
- [x] [02] Set new version ($$000).
- [x] [03] Set new counter ($$002).
- [x] [03.1] Set new worldflagcounter ($$002).
- [x] [04] Adjust opacity for newer parameters in GClh Config ($$001) and using of opacity.
- [x] [05] Maintain thanks area ($$006).
- [x] [05] Maintain changelog.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Moin, 
ich habe das changelog gesplittet in ein aktuelles und ein früheres. Man kann von dem Einen ins Andere springen und umgekehrt. Grund ist die Reduzierung des Ladevolumens beim Aufruf des changelogs. Es soll ja auch noch kleine Leitungen und Voluminas geben. 🙄 Der der will kann ja in die frühere Version springen.
Schaus dir bitte mal an. 
Was meinst du? Können wir es so belassen?
https://github.com/2Abendsegler/GClh/blob/Prepare-go-live-v0.10/docu/changelog.md
LG

**Comment by Ruko2010** [comment]
Klar das sieht gut aus.
Da wir nun als Versionsnummer die 10 haben könnte man den Cut sogar auch da machen und alle was kleiner gleich 9 ist auf eine neue Seite verbannen. Dann könnte man bei jeder neuen Major Version einen Cut machen um die Sache zu verschlanken.
Aber das kannst du gern entscheiden. Ich habe genug Leitung 😃

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Ok, danke fürs Feedback. 
Ich überlege nochmal ob ich auch die 8er noch ablege, mal sehen was da alles drin war und wie alt die Dinge sind.

**Comment by 2Abendsegler** [comment]
@Ruko2010
Die 8er sind ja schon weg. Jetzt verstehe ich erst, nur die Major Version. Hm, mal sehen, weiß nicht. :)

**Comment by Ruko2010** [comment]
Wie gesagt, freie Hand 😉

**Comment by Ruko2010** [comment]
Off: Echt toll wie du hier gerade durchziehst, Respekt! Meine Woche ist schon wieder total vollgestopft :/. Ich komm nichtmal dazu die neuen Caches in der Homezone zu finden
