### ISSUE TITLE
[New BML] - 2. Show 1000 caches

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1059]
2. Show 1000 caches instead of 500
#1052

**Comment by 2Abendsegler** [comment]
Nach den letzten Änderungen von GS funktioniert das nicht mehr. Scheinbar wird das take=1000 in der url nicht mehr vollständig umgesetzt.

**Comment by 2Abendsegler** [comment]
Ich habe keine andere Lösung gefunden.

**Comment by capoaira** [comment]
Ich versuche mich die Tage mal hier dran

**Comment by 2Abendsegler** [comment]
@capoaira 
Vermutlich willst du das über einen iframe im iframe lösen. Ich weiß nicht ob das Sinn macht, weil vermutlich bei allen Standard Aktionen wie beispielsweise sortieren erneut die Daten ermittelt werden müssen. Und es scheint mir viel Aufwand für einen doch überschaubaren Nutzen der in der Regel noch nicht mal verwendet wird. Ich habe beispielsweise gar keine BML die mehr als 500 Caches beinhalten. 
Du kannst ja mal kleinere Versuche machen. Zumindest wenn immer wieder erneut Daten ermittelt werden müssen dann erscheint mir das nicht so sinnvoll.

**Comment by capoaira** [comment]
Ja, ich löse das mit dem iframe. Meine Hoffnung war, dass GS die vorhandenen Daten nutzt. `take=1000` wird ja auch teilweise umgesetzt.
Leider stehe ich gerade vor dem Problem, dass ich immer nur die Mobile ansicht bekomme und es so noch nicht ausprobieren konnte.

**Comment by capoaira** [comment]
So, ich habe einige Sachen ausprobiert. Aber es gibt immer wieder Bugs... Groundspeaks asynchrone Scheiße nervt mich.... 
Vielleicht will ja jemand anderes....
Mein versuch, der teilweise funktioniert, ist hier zu finden: https://github.com/capoaira/GClh/tree/BML-show-1000

**Comment by 2Abendsegler** [comment]
@capoaira 
Ich hab mir das mal kurz angesehen. Hast ja schon einiges hinbekommen. Andererseits sind bestimmt noch viele Punkte offen insbesondere was das Handling in den Listen angeht. Ich bin mir auch nicht sicher ob das Löschen oder Hinzufügen von Caches ohne viel Aufwand abgebildet werden kann. Eigentlich nerven uns doch die asynchronen Dinge und wir benötigen für Kleinigkeiten viele Stunden. 
Der Aufwand um diese kleine Verbesserung zu implementieren rechnet sich in keiner Weise. Ich habe noch nicht mal ne Liste über 500 Einträge, außer die Ignoreliste. Und vielen geht es doch genauso. Lass uns doch unsere Arbeitskräfte lieber in Themen stecken die uns und auch anderen viel mehr bringen und die auch nicht so sehr nervig sind.
Ich setze den Status "no Solution found". Eigentlich wird es auch Zeit den Mist woanders hin zu schieben, zusammen mit #1117, damit wir ihn nicht ständig sehen. Das ist schon älter als ein Jahr. Wir haben ein Lager mit alten Sachen. Ich mach das nach der nächsten Version.

**Comment by 2Abendsegler** [comment]
Ich schließe die  beiden Issues bei denen wir keine Lösung gefunden haben.
Die kommen fürs nächste Jahr ins Lager (label: storage). Vielleicht werden wir während des Jahres noch etwas schlauer. Ich will die nur hier nicht mehr sehen, die nerven. 😬
