### ISSUE TITLE
One click watching.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1072]
Möglichst ähnlich dem One click ignoring.

@MarcusBi 
Extra für dich. 😊

**Comment by 2Abendsegler** [comment]
@MarcusBi
Hallo Marcus,

ich habe mir nochmal die Watchlist angesehen und noch ein One Click Feature implementiert um einen Cache in die Watchliste hinzuzufügen. 
Um einen Cache aus der Watchliste zu entfernen gibt es zwei Möglichkeiten, entsprechend wie im Online auch. Ich habe beide Möglichkeiten versucht, bin aber immer gescheitert mit einem Servererror, sprich der GS Server hat mich nicht verstanden. Obwohl es klar ist was zu liefern ist, weil ich aufzeichnen kann was im Online passiert, hat das nicht funktioniert. Und es ist auch sowieso problematisch, weil hier die gesamte Watchliste übergeben werden muss. Ein Fehler im Coding könnte deshalb die gesamte Watchliste killen.

Also: Hinein geht mit einem Klick, hinaus wie bisher.

Du kannst [hier](https://github.com/2Abendsegler/GClh/raw/one_click_watching/gc_little_helper_II.user.js) den GClh mit den Änderungen installieren um mal vorab reinzuschauen. 
Anschließend kannst du [hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) den GClh im Original wieder installieren. 

Ich werde das Issue im Anschluß schließen.

LG Frank

**Comment by MarcusBi** [comment]
Hallo Frank,

entschuldige die späte Antwort…blödes Arbeitsleben nebenbei ;-)

Das mit der Watchlist funktioniert ebenso einwandfrei. Dass das runternehemen von der Watchlist nicht geht, ist absolut verschmerzbar. Klasse gemacht - Danke!

LG,
   Marcus aka Herr Ma

**Comment by 2Abendsegler** [comment]
Ja ... blödes Arbeitsleben ... seh ich auch so 🤣

**Comment by MarcusBi** [comment]
Hallo Frank,

als vor einiger Zeit der Button zum Kopieren des GC-Codes ins Clipboard hinzugekommen ist, ist mir der Wunsche gekommen, auch andere Daten ins Clipboard zu kopieren. Also habe ich selber mal angefangen…

Zuerst habe ich den Button quasi kopiert und neben den Listingkoordinaten eingefügt, um ebenjene mit eine Click ins Clipboard zu kopieren. Danach wollte ich noch mehr, aber nicht überall Buttons einfügen. Also habe ich ein kleines Popupmenü hinzugefügt, um allerlei andere Daten zu kopieren (siehe Screenshot, der Punkt „Orginal Coords“ wird natürlich nur angezeigt, wenn es solche auch gibt). Ich benötige diese Funktionen immer wieder mal, daher merge ich meinen Code seitdem immer wieder in jede neue Version - was natürlich dumm ist. Apropos dumm: ich habe es der Allgemeinheit nicht zur Verfügung gestellt, weil ich zu doof bin nach einem Klick auf einen Menüeintrag des Popupmenüs ebenjenes wieder zu schließen. Daher hat das Ganze für mich einen Makel. Wenn du dafür noch eine Lösung hast, wäre ich dir sehr dankbar. Das heißt nicht, dass DU das Ganze offiziell einbauen musst…

Ich wäre einfach happy, wenn du mal drüber guckn könntest, deine Meinung dazu äußern würdest und ggf. das „nicht-schließende-Popup“-Problem lösen könntest ;-)

Anbei mein aktueller Code (mit den Änderungen für Ignore und Watchlist) sowie meine krampfhaften Versuche… ;-)

Und jetz: blödes Arbeitsleben *muhahahahrrrr*

LG,
   Marcus aka Herr Ma

**Comment by 2Abendsegler** [comment]
Hallo Marcus,

hört sich gut an. 
Lass mir ein paar Tage Zeit weil ich ziemlich viel um die Ohren habe hier mit dem GClh, dann schau ich mir das mal an. 

Die Datei ist verloren gegangen, womöglich durch das Routen von Mail Account über GitHub, keine Ahnung. Vielleicht schickst du mir die Datei einfach über meinen GC Account, oder du lädst das Programm auf deinen GitHub Account, geforked hast du den GClh ja. Also am Besten, Fork aktualisieren, neue Branch anlegen und dort dann den Code hochladen. GC Account ist aber auch völlig ausreichend. Ich schick dir im Anschluss mal ne Mail über deinen GC Account, weiß gar nicht ob du meine Mailadresse schon hattest.

LG Frank

**Comment by 2Abendsegler** [comment]
@MarcusBi 
Ja, hab den Code.
War eigentlich egal ob du ihn bei uns oder bei dir reinstellst. Letztlich muss er sowieso zu uns. 
Hattest du schon die Schweißperlen auf der Stirn. 😁
Ich werde es mir die Tage anschauen und dann auch ein neues Issue aufmachen.

**Comment by MarcusBi** [comment]
Guten Morgen Frank,

…die Schweißperlen waren sogar blutrot ;-)

Ich habe übrigens versucht etwas Verstand einzublenden und es damit jetzt doch geschafft, dass Popupmenü automatisch auszublenden. Ob das die eleganteste Art ist, weiß ich allerdings nicht - aber es funktioniert. Ist in meinem Branch mit drin... 

LG,
   Marcus aka Herr Ma

**Comment by 2Abendsegler** [comment]
Guten Morgen Marcus,

was man mit dem Verstand so alles ausblenden kann. 😂

Sieht klasse aus!

Wenn du magst kannst du es so rüberschieben. Wie das genau geht weiß ich nicht, hab ich noch nie gemacht. Ich vermute du kannst in deiner Branch einen Pull Request aufmachen. Den Pull Request mußt du dann nicht für deinen Collector sondern für unseren Collector vorsehen. Aber wie gesagt, ich weiß nicht wie es geht. Falls du nicht klar kommst kann Ruku2010 sicherlich helfen.

Mach aber bitte zuvor noch ein Issue auf. Das werden wir auch dann zu dir assignen, das geht mittlerweile. 

Wenn dein Code dann gemerged ist, würde ich noch winzige Kleinigkeiten ändern. Den Link im Cachelisting sollte man auch über den Config deaktivieren können. Und ich würde auch noch das ein oder andere vereinheitlichen. Beispielsweise steht in meinem Copy Button GC Code, in der Sidebar verwendest du GC-Code und in deinem Copy Button steht coordinate, und in der Sidebar verwendest du coords. 

Das sind aber wirklich Kleinigkeiten, die ich nachträglich noch ändern werde. Du kannst es natürlich auch machen, mußt du aber wirklich nicht, bei mir geht das vermutlich auch schneller.  

LG Frank

**Comment by MarcusBi** [comment]
Guten Morgen Frank,

wann habt ihr denn vor die nächste Version zu releasen? Falls es nicht an diesem Wochenende schon der Fall ist, werde ich das Ganze aufhübschen. Sprich:


- Einheitliche Texte
- Menü via Config anzeigen/ausblenden (default an oder aus?)
- Issue anlegen
- bei euch einen Branch anlegen, damit ihr dann pullen könnt (wie war das mit dem schwarzen Peter? ;-)

LG,
   Marcus aka Herr Ma

**Comment by 2Abendsegler** [comment]
Wir brauchen noch etwas bis zur nächsten Version. Wir kämpfen noch mit den neuen Seiten Bookmarklisten und Search Map. 

Ok, dann mach es mal hübsch. ;)

Im Menü zu Beginn natürlich angeschaltet.

Bei uns eine Branch anlegen ist nicht der richtige Weg. Man macht in seiner eigenen GitHub Umgebung eine Branch fürs Thema auf. Bei uns kommt dann nur der Pull Request an. 
Das Issue aber bei uns anlegen, weil wir im Changelog darauf verweisen wollen.

**Comment by MarcusBi** [comment]
Ok, dann eben wieder blutrote Schweißperlen ;-)

LG,
   Marcus aka Herr Ma

**Comment by 2Abendsegler** [comment]
😂
Du kannst hier nichts kaputtschlagen. Bei dir kannst du es deshalb nicht weil das Original ja bei uns steht. Und bei uns kannst du es nicht weil nur wir approven/mergen können. Spiel etwas rum, irgendwann klappt das was du wolltest.

**Comment by Herr-Ma** [comment]
Hallo Frank,

ich bin dann mal fertig ;-)

- Code überarbeitet
- Configmöglichkeit eingebaut
- Issues erstellt (1095 und 1096)
- Pull Request erzeugt (solltet ihr sehen)

Zur Info: …ich habe meinen Github Username von MarcusBi auf Herr-Ma geändert 

LG,
   Marcus aka Herr Ma
