### ISSUE TITLE
Button to copy coordinates to the clipboard

### ISSUE THREAD

**Issue by Herr-Ma** [2Abendsegler/GClh#1095]
Zusätzlicher Button zum Kopieren der angezeigten Koordinaten (analog zum Button "Copy GC Code to clipboard")

![grafik](https://user-images.githubusercontent.com/23725271/69408113-64c7c500-0d06-11ea-85c4-41206a422735.png)

**Comment by Herr-Ma** [comment]
Hab ich bereits umgesetzt...Pull Request kommt!

**Comment by Ruko2010** [comment]
Ich mag das feature jetzt schon 😃. Sehr gute Idee 👍

**Comment by 2Abendsegler** [comment]
Auch super!
