### ISSUE TITLE
Copy various cache informations to clipboard

### ISSUE THREAD

**Issue by Herr-Ma** [2Abendsegler/GClh#1096]
Zusätzliches Menü zum Kopieren verschiedener Cachedaten ins Clipboard

![grafik](https://user-images.githubusercontent.com/23725271/69408399-11a24200-0d07-11ea-82e4-4c3921e13764.png)

Falls für den Cache korrigierte Koordinaten eingegeben wurden, so sieht das Menü wie folgt aus:

![grafik](https://user-images.githubusercontent.com/23725271/69408478-444c3a80-0d07-11ea-8fdc-908efa148941.png)

Die Anzeige des Menüs kann hier konfiguriert werden:

![grafik](https://user-images.githubusercontent.com/23725271/69408585-95f4c500-0d07-11ea-985a-644f72521071.png)

**Comment by Herr-Ma** [comment]
Bereits umgesetzt...Pull Request kommt!

**Comment by Ruko2010** [comment]
Auch das find ich sehr gut! Danke @Herr-Ma

**Comment by 2Abendsegler** [comment]
Super!
