### ISSUE TITLE
New found / hidden in a summary in the beginning of the Friends page

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#111]
I have 23 friends on my Friends page. I love to read their new geocaching stories so I often visit this page. I always scroll down through all of them and search for "plus" numbers by their finds count (and hides as well, sometimes :) ). But this is inconvenient and I happen to overlook someone's new finds occasionally.

How about to add a summary called "What's new?" (or differently, it doesn't matter) right to the top of the Friends page? The "plus numbers" would be links directly to one's finds / hides.

This summary would not display if there were no new finds / hides.

Is it possible to do in GClh II?

![friends_page_summary](https://cloud.githubusercontent.com/assets/9153595/22502593/cde0deca-e86d-11e6-98f1-32e218877277.png)

**Comment by 2Abendsegler** [comment]
I think this "What's new" at the top of the friends page should be possible.

Please can you give me the both links to solitare.cz and the one link to Beerplease.cs as example? 
This is only to ensure that I have understand it right.

**Comment by PontiacCZ** [comment]
No problem. That would be:

for solitare.cz:
- Found: https://www.geocaching.com/seek/nearest.aspx?ul=solitare.cz&disable_redirect=
- Hidden: https://www.geocaching.com/seek/nearest.aspx?u=solitare.cz&disable_redirect=

for Beerplease.cz:
- Found: https://www.geocaching.com/seek/nearest.aspx?ul=Beerplease_CZ&disable_redirect=

**Comment by 2Abendsegler** [comment]
Fine.
We will include it in one of the next versions.

**Comment by 2Abendsegler** [comment]
Development request:
https://geoclub.de/forum/viewtopic.php?f=117&t=79463&p=1264924#p1264924

**Comment by MarcusBi** [comment]
Issue implemented ☺️

Summary for new founds/hides for friends on the friends page will be shown as follow:

![grafik](https://cloud.githubusercontent.com/assets/23725271/23063834/e74943ce-f50c-11e6-8809-745fe65d75ce.png)


There is also a timestamp with the date/time of the last check. After using the _Reset counter-Button_ the summary is hidden and only the timestamp is visible:

![grafik](https://cloud.githubusercontent.com/assets/23725271/23063897/46f9d3e2-f50d-11e6-91f8-a4c183e504bf.png)


To use the new summary feature you have to set the checkbox 

_Show summary for new founds/hides in friends list_.

Special feature. If you set the checkbox _Show summary only for friends in VIP list_ the summary will be shown only for friends which are marked as VIPs.

![grafik](https://cloud.githubusercontent.com/assets/23725271/23064243/2bcf50b8-f50f-11e6-9240-d6eceb31d852.png)

**Comment by PontiacCZ** [comment]
Wow, that looks awesome! :) When is it going to be released?

**Comment by PontiacCZ** [comment]
I am starting to like the additional option "Show summary only for friends in VIP list" - that is so great idea! In my Friends list I have users that offered me their friendship. I did not want to be rude so I accepted but I am not actually interested in being notified about their new finds as they write logs not worth reading. So I will definitely tick this checkbox to only see my VIP friends news. :-)

**Comment by MarcusBi** [comment]
That's exactly the reason why i've implemented this additional option :-)

**Comment by PontiacCZ** [comment]
Just noticed a minor mistype in the screenshot: "New founds by" -> "New finds by"

**Comment by 2Abendsegler** [comment]
Yes, you are right, thanks. 
I have changed it.

**Comment by PontiacCZ** [comment]
Yep, just verified the new function. Looks great, will test it more thoroughly later. Closing this issue and sending a big THANK YOU. :-)
