### ISSUE TITLE
Set color on days with own events to green

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1113]
![Eventkalender](https://user-images.githubusercontent.com/50927164/69919506-c104b480-147d-11ea-8f50-e377f15f15a3.png)

So soll es aussehen:
![Eventkalender](https://user-images.githubusercontent.com/50927164/69919522-e42f6400-147d-11ea-8f6b-f5c16f80d906.png)

**Comment by 2Abendsegler** [comment]
@capoaira:
Kannst du und magst du das Thema übernehmen?

**Comment by capoaira** [comment]
Hatte ich eigentlich von, aber mein erstes Problem ist, dass nicht an Events komme, solange der Tag nicht angeklickt ist.
Ein weiteres Problem (dass mir vorher hätte einfallen müssen) ist, dass man alle Events aufrufen müsste, um an den original Owner zu kommen. Denn der Link zum Owner funktioniert nicht. Ich hatte da schon mal einen Bug Report im GS Forum erstellt, aber auf Deutsch wurde dem wohl keine Beachtung geschenkt. Dann hätte man die Zuletzt aufgerufenen immer voll mit den Events. Oder man guckt sich nur den geschriebenen Namen an, aber bei Teamnamen o.ä. funktioniert das dann nicht...

**Comment by 2Abendsegler** [comment]
Es wird ja auch nicht der Owner des Events angezeigt, sondern gegebenenfalls das Pseudonym. Deshalb bekommt GS das wohl auch nicht einfach in den Griff mit dem Link. Ein Beispiel aus deiner Umgebung ...

![grafik](https://user-images.githubusercontent.com/22332216/69993301-d3e5ba80-154b-11ea-9c7e-6394130f6508.png)
Der echte User heißt Urs015, angezeigt wird aber Urs015 & Luni1420. Vermutlich ist das das Gleiche wie du mit den Teamnamen bereits angesprochen hast.

Anstatt die Cache Listings nachzulesen, kann man auch über die Suchfunktion nachlesen. Also der Link Search events. Der sieht dann etwa so aus ...
https://www.geocaching.com/play/search/?origin=home&radius=20km&types=6,13,453,1304,3653,3774,4738,7005&sort=PlaceDate&asc=True&ed=2019-12-12

Das dann 31 mal und du hast alle Events des Monats. Leider werden dort aber auch gegebenenfalls die Pseudonyme und nicht die korrekten Owner angezeigt.

Mir fällt jetzt auch nichts ein.

**Comment by capoaira** [comment]
Ah, das mit der Suche hört sich gut an. Ich versuche das mal. Dann wird es zwar keine 100%ige Lösung, aber solange der Owner zu seinem Namen nur andere Namen hinzufügt...

**Comment by 2Abendsegler** [comment]
Vergleiche besser nur den kompletten Event Ownernamen und nicht ob der Username im Event Ownernamen enthalten ist. Das kann dann zu dubiosen Ergebnissen führen, und wir müssen korrigieren. 

Ich habe dich im Issue assigned. Viel Erfolg.

**Comment by capoaira** [comment]
Danke. 
Habt ihr schon eine Funktion, die den Userernamen ermittelt?
Es dauert eine Weile, bis alle Ownernamen ermittelt sind. Wie kann ich warten bis alle geladen sind? Beim warten auf den Kalender habe habe ich ja eine Variable, wie kann ich dass mit den Ownernamen machen?

**Comment by 2Abendsegler** [comment]
> Habt ihr schon eine Funktion, die den Userernamen ermittelt?

In global_me steht der User aus der Anmeldung.

> Es dauert eine Weile, bis alle Ownernamen ermittelt sind. Wie kann ich warten bis alle geladen sind? Beim warten auf den Kalender habe habe ich ja eine Variable, wie kann ich dass mit den Ownernamen machen?

Ich hab eigentlich keine Ahnung von Javascript ... 😂
Vielleicht kann @Ruko2010 hier was zu sagen, der hat nämlich Ahnung? 😊

**Comment by capoaira** [comment]
>In global_me steht der User aus der Anmeldung.
>
Ah, global_me, dass ist wahrscheinlich eine besser als meine Lösung
> 
> > Es dauert eine Weile, bis alle Ownernamen ermittelt sind. Wie kann ich warten bis alle geladen sind? Beim warten auf den Kalender habe habe ich ja eine Variable, wie kann ich dass mit den Ownernamen machen?
> 
> Ich hab eigentlich keine Ahnung von Javascript ... 😂
> Vielleicht kann @Ruko2010 hier was zu sagen, der hat nämlich Ahnung? 😊
>
Ich habe schon eine andere Möglichkeit gefunden. Hatte nicht weit genug gedacht 😊
Das wichtiges funktioniert jetzt schon mal. 

Eine kleine ToDo-Liste für mich:
- [ ] Beim Datum wechseln muss die Funktion auch ausgeführt werden
- [ ] Beim aufklappen muss auch die Funktion auch ausgeführt werden

**Comment by capoaira** [comment]
Moin,
langsam wird es peinlich zu fragen... 😊
Ich habe jetzt eine schnellere Lösung gefunden, die zudem zuverlässig alle Daten markiert, solange der Owner nicht mehr als 20 aktive Events hat.
Aber wenn man den nächsten, oder letzten Monat aufruft, wird die Funktion nur beim ersten mal aufgerufen. Egal, ob ich die EventListener einmal oder nach jedem klick hinzufüge.
Hast du eine Idee?

**Comment by 2Abendsegler** [comment]
Ruko2010 würde jetzt sicherlich sagen Mutation Observer. Beim Popup in der Karte wird das genutzt. Schaus dir mal an.

**Comment by capoaira** [comment]
Ok danke, das schaue ich mir mal an, aber lieber wenn ich richtig wach bin😂, das sieht komplizierter aus.

**Comment by capoaira** [comment]
So, ich bin theoretisch fertig: https://github.com/capoaira/GClh/tree/%231113-Set-color-to-green-by-own-Events
Auch habe ich dort alles Mögliche geprüft: Englisch/Deutsch, mit und ohne anderen GClh-Einstellungen und auch mit anderen Daten-Formaten.

Zu folgendem würde mich Eure Meinung interessieren:
Wenn ich bei einem Event "will Attend" logge und das Event außerhalb des eingestellten Radius liegt, wird dieses trotzdem angezeigt.
Das selbe würde ich gerne für die eigenen machen. Das markieren geht auch einfach, aber die Infobox unten:
1) Ich müsste auf die Entfernungsangaben verzichten, denn in einigen Sprachen wird die anders angezeigt.
2) Der Tag wird je nach ausgewähltem Daten-Formate angezeigt. Ich müsste also an die Einstellungen des Users und dann das Datum formatieren. Das ist bei der Menge an Formaten sehr aufwändig.

Soll ich es einfach lassen, wie es jetzt ist, oder nur das Datum grün markieren?
Oder soll ich den Infokasten einblenden und auf Entfernung und Datum verzichten?

**Comment by 2Abendsegler** [comment]
Hm, ... vielleicht mal überlegen, ob wir die Darstellung der Entfernungsangaben und die Darstellung des Datums irgendwo anders abgreifen können. Wo sind denn die Angaben noch zu finden?

**Comment by 2Abendsegler** [comment]
Für die Darstellung der eigenen Events außerhalb der Entfernungsangabe sollten wir vielleicht auch noch einen Parameter im Config vorsehen.

**Comment by 2Abendsegler** [comment]
Die Darstellung der Entfernungsangaben und die Darstellung des Datums finden wir im Listing. Hast du aber sicherlich selbst herausgefunden. Vielleicht können wir uns dort bedienen.

Wie war hier eigentlich der Stand.

Ich wollte die Tage eine neue Version raushauen.

**Comment by capoaira** [comment]
Moin,
das User Datum hole ich mir auch aus der Event-Übersicht. Die Entfernungsangabe ist ja nach Sprache unterschiedlich im Listing. Deswegen hole ich diesen aus der Suche. 
Ich muss leider beides abfragen, da ich bei der Suche kein immer gleich formatiertes Datum bekomme. 

Im Moment hänge ich bei der Infobox unten, die ist irgendwie frustrierend. Jetzt liegen erst mal vier Klausuren vor mir. Danach habe ich glaube ich wieder etwas Ruhe.

Für die nächste Version kann ich nur anbieten, die Events im Radius zu grün zu markieren und außerhalb dann in der darauf folgenden Version nach Zuliefern.

**Comment by capoaira** [comment]
@2Abendsegler Ich habe jetzt eine [fertige Version **ohne** Events](https://github.com/capoaira/GClh/tree/%231113-Set-color-to-green-by-own-Events) außerhalb des Radius. Wenn das reicht könnte die so in die nächste Version. 
Mit Events außerhalb des Radius muss ich noch etwas rumprobieren.

**Comment by 2Abendsegler** [comment]
Machs doch in Ruhe fertig, wenn du wieder Zeit hast. Das eilt ja jetzt nicht sonderlich.

Viel Erfolg bei deinen Klausuren.

**Comment by capoaira** [comment]
Moin,
ich bin gerade kurz vorm aufgeben. 
https://github.com/capoaira/GClh/tree/Show-also-own-Events-outside-of-your-radius
Kannst du, wenn du Zeit hast, dir das Coding bitte angucken. Ab Zeile 7535, dir Funktion addList. Es funktioniert nicht, und finde meinen Fehler seit Tagen nicht.

**Comment by 2Abendsegler** [comment]
Es ist schwierig, weil ich nicht weiß was genau nicht funktioniert und ich vermutlich wegen fehlender eigener Events nicht an die entsprechende Stelle komme. Erzähl mal etwas mehr.

Wenn es ein Error ist, dann könnte das damit zusammenhängen, dass du das Coding zu `let eventLiInnerHTML = '...'` nie mit einem `;` abschließt. Der Abschluss liegt in einem `/* ... */` Bereich.

**Comment by capoaira** [comment]
Daran lag es nicht. Ich beschreibe das morgen nochmal genauer.

**Comment by capoaira** [comment]
Ich werde diesen Issue nochmal neu mit jQuery schreiben, dann ist das ganze deutlich übersichtlicher und verkürzt den Code. Ich weiß im Moment nicht wann ich wie viel Zeit habe, und dieser Issue ist etwas größer. Ein weiteres Problem ist, dass ich an dem Tag bei einem anderen Event WA geloggt habe und der Tag somit grün ist. Das ändern des WA in eine Note hat nichts gebracht. Vielleicht dauert es bei GS auch nur, bis der Kalender die Änderungen bemerkt.

**Comment by 2Abendsegler** [comment]
@capoaira 
Bereinige gegebenenfalls dein Coding, gib uns einen Link zum Coding und beschreibe mal was nicht geht.

**Comment by 2Abendsegler** [comment]
Da haben wir uns überschnitten.

> 
> 
> Ich werde diesen Issue nochmal neu mit jQuery schreiben, dann ist das ganze deutlich übersichtlicher und verkürzt den Code. Ich weiß im Moment nicht wann ich wie viel Zeit habe, und dieser Issue ist etwas größer. Ein weiteres Problem ist, dass ich an dem Tag bei einem anderen Event WA geloggt habe und der Tag somit grün ist. Das ändern des WA in eine Note hat nichts gebracht. Vielleicht dauert es bei GS auch nur, bis der Kalender die Änderungen bemerkt.

Mach das.

Ich finde du solltest eins nach dem anderen machen.
Ich nehme dir das neue Issue wieder weg und wir behalten uns, dass du das gerne machen möchtest.

Mach zuerst mal das hier.
Dann schau dir noch die Dinge zum Hide Header an. 

Wenn du mit den beiden teilen fertig bist oder nicht mehr weiterkommst, kannst du das neue Issue wieder haben.

**Comment by capoaira** [comment]
Dieses Issue kann ich vorerst nicht bearbeiten. Durch das loggen des anderen Events ist der Tag grün markiert. Scheinbar lässt sich das nicht Rückgängig machen. Wenn ich ein neues eigenes Event habe, arbeite ich weiter hier dran.

**Comment by capoaira** [comment]
Der Nutzen dieser Funktion wird dem Aufwand nicht gerecht. Ich schmeiß das mal weg ;)
