### ISSUE TITLE
[FF] cannot save to Dropbox

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#113]
I don't know whether the issue is on my side but I wanted to save the settings to Dropbox. This used to work correctly with the old GClh.

But with **GClh II** I am experiencing this: I open the "GC little helper Sync II" window and click on "Dropbox". This launches a new window and loads my profile page into it (see the attached pic). Not sure why.

Both buttons ("Save to DropBox" and "Load from DropBox") appear to be active links (the cursor goes to the hand symbol when over them) but clicking either one invokes no reaction. No configuration gets saved to my DropBox.

![gclh_ii_dropbox](https://cloud.githubusercontent.com/assets/9153595/22590294/c6c48c0c-ea0e-11e6-8102-82ddbf49ddf0.png)

**Comment by 2Abendsegler** [comment]
Hi,

this functionality was not tested for GClh II ... , yes ..., really. :)
It is a wonder that some users report that the dropbox works. Your type of error is known.

From my perspective it is not a necessary, only a fancy utility for saving the settings. Please save the settings manual.

Perhaps someday, someone will look to this feature. I will not look in the moment, sorry. :) 
But I will let the issue open. We will see if someone will help GClh II to communicate with Dropbox.

Regards.

**Comment by PontiacCZ** [comment]
I see. OK, no problem, just thought it was supposed to work.  It really is something "extra" and manual export is enough for me.  Maybe just add a note "(not yet fully functional)" next "(Click to hide/show)" so others are not as confused as I was. :-)

**Comment by 2Abendsegler** [comment]
You are right, good idea. I will add a note in the sync with the next version.

**Comment by Cappa-d** [comment]
FYI -- received this last night from Dropbox:


Hallo     Peter Vollmer,          am 28. September 2017 werden bei Dropbox Änderungen vorgenommen, die     sich voraussichtlich auf die folgenden mit Ihrem Dropbox-Konto verknüpften     Drittanbieter-Apps auswirken werden: GCLittleHelper. Sie erhalten diese     Mail, weil Sie diese Apps im letzten Monat mindestens einmal verwendet     haben.           Selbstverständlich haben wir alle Entwickler rechtzeitig über die     anstehenden Änderungen informiert. Die Entwickler der unten aufgeführten     Apps haben die Apps jedoch bisher noch nicht entsprechend aktualisiert.     Falls dies nicht bis zum 28. September nachgeholt wird, haben diese     Apps keinen Zugriff mehr auf Dropbox. Bereits in Dropbox gespeicherte     Dateien sind davon nicht betroffen und Sie können nach wie vor über unsere     offiziellen Clients für Web, Mobilgeräte und den Desktop darauf zugreifen.           Da Sie diese Apps in letzter Zeit genutzt haben, raten wir Ihnen Folgendes:           Prüfen Sie          Ihre Nutzung dieser Apps – besonders, wenn Sie damit auf Dropbox          zugreifen      Wenn Sie mit          diesen Apps Inhalte in Dropbox speichern, sollten Sie alle Inhalte aus          diesen Apps vor dem 28. September exportieren oder sichern          Solche     Änderungen kommen nicht immer gelegen. Hoffentlich finden Sie die obigen     Empfehlungen aber hilfreich. Bei Fragen zu diesen Apps wenden Sie sich     bitte an den Support für die jeweilige App.           Das Dropbox-Team |   |   | Hallo     Peter Vollmer,          am 28. September 2017 werden bei Dropbox Änderungen vorgenommen, die     sich voraussichtlich auf die folgenden mit Ihrem Dropbox-Konto verknüpften     Drittanbieter-Apps auswirken werden: GCLittleHelper. Sie erhalten diese     Mail, weil Sie diese Apps im letzten Monat mindestens einmal verwendet     haben.           Selbstverständlich haben wir alle Entwickler rechtzeitig über die     anstehenden Änderungen informiert. Die Entwickler der unten aufgeführten     Apps haben die Apps jedoch bisher noch nicht entsprechend aktualisiert.     Falls dies nicht bis zum 28. September nachgeholt wird, haben diese     Apps keinen Zugriff mehr auf Dropbox. Bereits in Dropbox gespeicherte     Dateien sind davon nicht betroffen und Sie können nach wie vor über unsere     offiziellen Clients für Web, Mobilgeräte und den Desktop darauf zugreifen.           Da Sie diese Apps in letzter Zeit genutzt haben, raten wir Ihnen Folgendes:           Prüfen Sie          Ihre Nutzung dieser Apps – besonders, wenn Sie damit auf Dropbox          zugreifen      Wenn Sie mit          diesen Apps Inhalte in Dropbox speichern, sollten Sie alle Inhalte aus          diesen Apps vor dem 28. September exportieren oder sichern          Solche     Änderungen kommen nicht immer gelegen. Hoffentlich finden Sie die obigen     Empfehlungen aber hilfreich. Bei Fragen zu diesen Apps wenden Sie sich     bitte an den Support für die jeweilige App.           Das Dropbox-Team |   |  
-- | -- | -- | -- | -- | --
 
  | Hallo     Peter Vollmer,          am 28. September 2017 werden bei Dropbox Änderungen vorgenommen, die     sich voraussichtlich auf die folgenden mit Ihrem Dropbox-Konto verknüpften     Drittanbieter-Apps auswirken werden: GCLittleHelper. Sie erhalten diese     Mail, weil Sie diese Apps im letzten Monat mindestens einmal verwendet     haben.           Selbstverständlich haben wir alle Entwickler rechtzeitig über die     anstehenden Änderungen informiert. Die Entwickler der unten aufgeführten     Apps haben die Apps jedoch bisher noch nicht entsprechend aktualisiert.     Falls dies nicht bis zum 28. September nachgeholt wird, haben diese     Apps keinen Zugriff mehr auf Dropbox. Bereits in Dropbox gespeicherte     Dateien sind davon nicht betroffen und Sie können nach wie vor über unsere     offiziellen Clients für Web, Mobilgeräte und den Desktop darauf zugreifen.           Da Sie diese Apps in letzter Zeit genutzt haben, raten wir Ihnen Folgendes:           Prüfen Sie          Ihre Nutzung dieser Apps – besonders, wenn Sie damit auf Dropbox          zugreifen      Wenn Sie mit          diesen Apps Inhalte in Dropbox speichern, sollten Sie alle Inhalte aus          diesen Apps vor dem 28. September exportieren oder sichern          Solche     Änderungen kommen nicht immer gelegen. Hoffentlich finden Sie die obigen     Empfehlungen aber hilfreich. Bei Fragen zu diesen Apps wenden Sie sich     bitte an den Support für die jeweilige App.           Das Dropbox-Team |

**Comment by 2Abendsegler** [comment]
The Dropbox account is the account of Thorsten. We have no access to his account and could not do anything. And this is not a primary feature. So, I think this feature will not be saved after the 28 of september.
At this moment we don't work on any construction sites, sorry. We are taking a break.

**Comment by 2Abendsegler** [comment]
(Only in german, sorry I'm in a hurry, wants to go to the Karvendel for hiking and climbing.)

Unser lieber Kollege [url=https://www.geocaching.com/profile/?u=Ruko2010]Ruko2010[/url] hat die neue DropBox API zur Synchronisierung der Konfigurationsdaten im GC little helper II eingebaut. Sie steht im Moment als Beta Version zur Verfügung und kann manuell installiert werden. Aus technichen Gründen verbleibt es dabei bei Versionsnummer 0.8.6. 

Die neue Funktionalität kommt regulär vorraussichtlich erst Ende Oktober. 

Nach der Installation der Beta Version kann über den GClh Sync (F10 Taste) eine Synchronisation der GClh Konfigurationsdaten in den eigenen DropBox Account durchgeführt werden. Bei der Authentifizierung wird ein "Token" gespeichert, sodass die Authentifizierung nur einmalig durchgeführt werden muss. Der "Token" kann im Rahmen der GClh Config Funktionalität "Reset / Reset dynamic and unused data" wieder gelöscht werden, so dass man eine Authentifizierung mehrfach testen kann bzw. sich auf unterschiedlichen DropBox Accounts anmelden kann.

Die Beta Version kann [url=https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js]hier[/url] installiert werden.
Zurück zur regulären Version kommt man [url=https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js]hier[/url].

Falls ihr mit der Beta Version arbeitet, dann meldet bitte eure Ergebnisse (OKs bzw. Fehler) hier an dieser Stelle.

Vielen Dank an [url=https://www.geocaching.com/profile/?u=Ruko2010]Ruko2010[/url] für die super Implementierung und die tolle Zusammenarbeit. :)

LG Frank

**Comment by 2Abendsegler** [comment]
@DrakMrak has test it
https://github.com/2Abendsegler/GClh/issues/85#issuecomment-333297855

**Comment by DrakMrak** [comment]
Yes I tested DropBox and havn't problem
- tested at two computers with Firefox and Edge and both have instaled TamperMonkey and last beta GC_LH

**Comment by GFEMajor** [comment]
@2Abendsegler wollen wir die Tickets (auch #85) offen lassen bis die Funktion in der 0.8.7 drin ist, oder können die schon zu?

**Comment by 2Abendsegler** [comment]
Issues von Usern schließen die User selbst.

**Comment by GFEMajor** [comment]
Dann ist hier schluss 😃
