### ISSUE TITLE
Error or missing elevation data of Google elevation or Open elevation.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1131]
Moin,
Folgender Error tritt bei mir regelmäßig mal auf:
![2019-12-14](https://user-images.githubusercontent.com/50927164/70848484-a1ed2600-1e72-11ea-8cd5-13cfa65bd58d.png)

**Comment by 2Abendsegler** [comment]
Ja, du hast recht. 
Das können wir aber leider nicht abstellen. Sowohl bei google als auch bei open elevation klappt das immer wieder mal nicht mit den Anfragen. Bei google vermutlich sogar ständig, da bin ich mir nicht sicher. Eigentlich sollte man geonames verwenden, die haben zur Zeit das zuverlässigste Antwortverhalten. Ich habe geonames als primary eingestellt und open als secondary.  Für die seltenen Fälle in denen geonames nichts zu Tage bringt, geht dann vermutlich open, so die Überlegung. Das scheint gut zu funktionieren, hab schon seit Monaten keine Fehlermeldung mehr bekommen. 

Also, vielleicht kann das Issue wieder zugemacht werden, oder wir geben nochmal ne Anweisung übers Changelog raus wie es einzustellen ist. Hatten wir aber schon mal gemacht, glaube ich. Können wir aber nochmal machen. Was meinst du?

**Comment by capoaira** [comment]
Ah ok, das wusste ich noch nicht. Ich habe es bei mir umgestellt und es funktioniert. 
Ich weiß nicht seit wann ich den GClh nutze und für die Elevation habe ich mich nie Interessiert, erst seit dem ich die Error Nachrichten angeschaltet habe. Es kann also gut sein, dass ich das nicht gelesen habe.
Ich fände es gut wenn es noch einmal im Changelog erwähnt wird.

**Comment by 2Abendsegler** [comment]
Ok, dann machen wir das.

- [ ] 2Abendsegler: 
Nachschlagen, was wir bei der Erweiterung von geonames geschrieben haben. Ähnliches nochmal beschreiben zur nächsten Version.

**Comment by Ruko2010** [comment]
Kurzer Nachtrag. Macht es eventuell sinn das einfach im nächsten Release zu ändern und die Leute nur zu informieren? Wenn es eh nicht geht, sollten wir die option der „freien wahl“ vielleicht ganz streichen und das hart rein codieren?

**Comment by 2Abendsegler** [comment]
Ja, wenn sie nicht mehr gegen, wäre das letztlich richtig. Ich glaube aber Open Elevation funktioniert schon, wenn die nicht überlastet sind. @capoaira, ist doch so, die funktionieren schon auch, oder. 
Es könnte sein dass Google Elevation nur noch mit key funktioniert. Wenn ich mich recht erinnere dann sind ne bestimmte Anzahl von Aufrufen mit key gratis, bin mir aber nicht sicher, das heißt man kann auch die womöglich wieder ans Laufen bringen. Ob das bei der Begrenzung auf ne Anzahl von Aufrufen Sinn macht, weiß ich nicht. Ich wollte hier kein Fass aufmachen, weil wir ja genug andere Baustellen haben. 

Und empfohlen hatten wir ja schon mal was. Ich wollte das einfach nochmal in ähnlicher Form schreiben, weil ja nicht jeder immer die Changelogs ließt. Etwa die Hälfte der User rufen das Changelog auf, was ja ziemlich viel ist, aber es sind eben nicht alle.

Wir können es auch als Issue offen lassen mit kleiner prio und wir schauen uns das irgendwann mal nochmal genau an. Was meinst du?

**Comment by capoaira** [comment]
Also ohne Google hat es gestern bei mir ohne Probleme geklappt. 
Im Changelog steht das bei Version 0.9.15, das war im Januar dieses Jahres.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Hab nochmal explizit mit Open elevation getestet. Es ist zwar langsam, aber es funktionierte gestern und heute Mittag und gerade eben auch.

@capoaira 
Ok, Version 0.9.15 war es.

**Comment by 2Abendsegler** [comment]
merged
