### ISSUE TITLE
Show length of logtext on new logging page and show length of hint, cachename and placed by on hide edit page.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1143]
On the old logging page, the logging length is shown by the GClh (x/4000). This feature is missing on the new logging page.
The length for a geocache hint and for the geocache name is also limited and it is frustrating when I write the name or and see that it is too long.
I'm trying to work on the issue.

**Comment by capoaira** [comment]
Screens für den Changelog:
![Log](https://user-images.githubusercontent.com/50927164/71930377-d0250380-319b-11ea-9b1b-63245cce3039.png)
Editpage:
![Edit](https://user-images.githubusercontent.com/50927164/71930376-d0250380-319b-11ea-9d14-7802df8d7fa7.png)
![Hint](https://user-images.githubusercontent.com/50927164/71930375-cf8c6d00-319b-11ea-907e-dcb900642a82.png)

**Comment by 2Abendsegler** [comment]
Ich dachte wir machen alles rechtsbündig zum Eingabefeld. Jetzt hast du es beim Log aber linksbündig gemacht. Warum denn das? Nur weil es auf der alten Log Page ganz links und sogar außerhalb ist?

**Comment by 2Abendsegler** [comment]
... Ansonsten sieht das gut aus.

**Comment by capoaira** [comment]
Nein, bei der Logpage habe ich mir etwas dabei gedacht. 
Rechts ist "Report a Problem". Dahinter finde ich es nicht so schön, so gequetscht. Wenn man "Report a Problem" in die Mitte packen würde, würde es sich verschieben, weil bei allen Logs die nicht Found sind das Fav-Herz fehlt. Deswegen habe ich das Fav-Herz in die Mitte gepackt und den Counter nach links.
Wenn das nicht ok ist, kann ich es auch gerne ändern.

**Comment by 2Abendsegler** [comment]
Ok, verstehe jetzt.
Dann lassen wir es so. :)

**Comment by 2Abendsegler** [comment]
merged
