### ISSUE TITLE
Show button to display all, only active or only archived caches in owned caches list.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1145]
Bisher konnte man die nur die archivierten Caches ausblenden und musste dies im config ändern. Mit dem Button ist das ganze flexibler. 
PR kommt...

**Comment by 2Abendsegler** [comment]
![grafik](https://user-images.githubusercontent.com/22332216/71556869-fb8e4c80-2a3d-11ea-8de3-c843b10e5cdd.png)

**Comment by 2Abendsegler** [comment]
Screen02
Settings -> Others: Screen01
