### ISSUE TITLE
Cache Listing with many errors.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1153]
![grafik](https://user-images.githubusercontent.com/22332216/71601098-4305fd00-2b52-11ea-932d-39e104edb696.png)

In Cache Listings werden massenhaft GClh Fehler angezeigt. Die VIPs sind nicht vollständig, die Logs werden nicht durch GClh angezeigt, Favoriten % wird nicht angezeigt, obere Karte wird nicht angezeigt ... .
Gemäß Aussage eines Message Center Kontakts treten die Fehler unter Chrome auf. 
Unter FF Android treten sie bei mir auch auf. Ich hab keinen Rechner zur Verfügung und mach mit meinem Smartphone rum. 

@Ruko2010, @capoaira 
Kann sich das vielleicht jemand von euch ansehen?

**Comment by capoaira** [comment]
Bei mir treten sie auch in Chrome auf, aber auch in FF. IE kann ich nicht testen.
Scheinbar tritt der Bug erst seit heute Abend auf, denn heute Nachmittag wurden mir die Fehler noch nicht angezeigt.

**Comment by diundbi** [comment]
Diese Probleme tauchten nach einem kurzen Serverausfall der geocaching.com Seite auf:
Logs werden im Listing nicht automatisch dargestellt,
keine Logs von Freunden,
die kleine untere Übersichtskarte fehlt.
Aufgetreten bei zwei Rechner unter Chrome

**Comment by 2Abendsegler** [comment]
> Serverausfall der geocaching.com Seite

Ah, ok, der war bei gc. Vielleicht sollten wir noch etwas warten und hoffen. 😊

**Comment by have-moicy** [comment]
Problem seems to be associated with a change in chrome cookie policy:

A cookie associated with a cross-site resource at https://www.google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by 2Abendsegler** [comment]
@have-moicy 
Thanks for this information. We will look at this.
But I am afraid that the problems are due to the changes of Groundspeack on the geocaching websites. It affects all browsers and even without scripts the geocaching websites do not all work correctly.

**Comment by 2Abendsegler** [comment]
A solution for all the problems seems to be a blocking of address "cookiebot.com". The Addon uBlock Origin 1.24.2 can do that for example. 
https://geoclub.de/forum/viewtopic.php?f=117&t=81216&start=30#p1303961

**Comment by 2Abendsegler** [comment]
@Ruko2010, @capoaira und andere

Hab die Info in den Foren (geoclub.de/forum, forums.geocaching.com, swissgeocacheforum.ch) getriggert, siehe unten.

Jetzt können wir uns überlegen, ob wir vielleicht selbst noch etwas im GClh tun können weil die Info sicherlich nicht jeden erreicht und einige auch damit überfordert sein könnten. Wenn wir die Adresse im GClh blockieren könnten, wäre das sicherlich keine schlechte Idee. Ich habe aber im Moment keine Ahnung wie wir das machen können. Habt ihr Ideen, Vorschläge?

---
Eine mögliche Lösung, der seit dem 31.12.2019 bestehenden Probleme mit Scripten, ist wohl die Blockierung der Adresse "cookiebot.com".
Arnos hat [hier](https://geoclub.de/forum/viewtopic.php?f=117&t=81216&start=30#p1303961) beschrieben wie man dazu vorgehen kann.
Frohe Neues Jahr.
Frank
PS: Das gilt für viele Scripte, so auch für GC Tour und Geocaching Map Enhancements.

**Comment by Ruko2010** [comment]
I have the same problem in Chrome and FF. I think it has something to do with the changes Groundspeak made to the cookie guidelines. Since the server breakdown I have to accept the cookie policy. this is new.

**Comment by 2Abendsegler** [comment]
Moin, kurz mal überschnitten. :)
Du hast recht.

**Comment by Ruko2010** [comment]
Ich schau es mir gerade näher an. Mal gucken ob wir was machen können. @2Abendsegler vielleicht finden ja GCTour oder andere Scripte vorher eine Lösung 😉.

**Comment by PontiacCZ** [comment]
I have just read your note about cookiebot.com on CZ forum, Frank, but I'm still not sure how to block cookiebot.com with uBlock origin. Never done such thing. I hope we won't be supposed to tweak our ad-blockers to restore the functionality of GClh...

**Comment by 2Abendsegler** [comment]
Hi PontiacCZ,

your describtion is correct. That is one way to solve the problems. If you have another ad blocker, it can probably do that too.

> I consider this a temporary solution, majority of people sure won't be able to achieve this...

Yes, that is our opinion also.

But the topic is problematic and complex. GS tries to transpose the EU General Data Protection Regulation and something comparable from the USA with cookiebot. That's actually a good thing. However, cookiebot apparently use mechanisms that interfere with the execution of scripts. I am not yet sure whether we should attack here ourselves with the GClh. We would probably take some responsibility for this topic and I don't know how to explain it to our users. 

If we find a solution to deactivate cookiebot itself, we will have to consult if we really want to implement it.

Actually it should be a topic for GS and cookiebot to implement the whole thing so that it also works with scripts. GS pays for the use of cookiebot.

**Comment by Ruko2010** [comment]
I think disabling Cookiebot (IF we find a way to do this) is not the right approach.
We should find out why it is not working with cookiebot and find a solution to work in coexistens with cookiebot.
But we should wait for some days, if GC make more changes.

**Comment by Chrono81** [comment]
Hello !
I am from France and I use Firefox 71.0 (64 bits) with TamperMonkey 4.10.6105 on a Windows 10 computer. 
Before I read your temporary workaround (blocking cookiebot.com) that works well I found another way to work anyway. 
It is certainly not an effective and lasting solution but it can possibly help you. 
The GC Little Helper II script works fully if you deactivate TamperMonkey (left click on TM Icon et left click on Activated) then refresh the web page and finally reactivate TamperMonkey (same way as before). 
You have to do it on every page but it works !
As you already know this is probably due to the new way used by Groundspeak to display geocaching data. 
Thank you for your understanding and your work ! ! !

**Comment by 2Abendsegler** [comment]
Hello,
thanks for this great information! I tried it and it works as described. :)
I think you are the guy from the french forum, who translated some things from the new start of the GClh for the french forum, years ago. Thanks for that too. :) 

When Tampermonkey is reactivated, the page is automatically redisplayed by Tampermonkey, without reloading. The GClh can therefore work with the pages, but apparently not simultaneously as the changes of GS around cookiebot. Or maybe not before the page is fully loaded. Our errors always seem to have something to do with unsafeWindow. In my understanding, these are queries to the GS resources on the loaded page. A solution could be, to wait until the necessary things are loaded, whatever these things are.
I tested with https://coord.info/GC3HA0P

(Off-Topic: France GClh community consists of about 25 users. Maybe that interests one or the other. That only because I just looked at the current numbers.)

**Comment by PontiacCZ** [comment]
Hint was affected as well by the recent HQ change and will not decode correctly.

For instance https://coord.info/GC4YJ68

**Comment by Vylda** [comment]
Hi,

 

this is problem of another GM script, Mystery Wizard. This script blocked lazy loades scripts (fo logbook, for decoding hints etc.).

**Comment by 2Abendsegler** [comment]
I have already seen it.
It's annoying, sorry.
I am working on it.

**Comment by 2Abendsegler** [comment]
To do:
- [ ] Show favorite percentage in cache listing run into error because of GSs GDPR changes.
- [ ] Build map overview in cache listing run into error because of GSs GDPR changes.
- [ ] Activate fancybox??? in cache listing run into error because of GSs GDPR changes.
- [ ] Decrypt hints in cache listing run into error because of GSs GDPR changes.
- [ ] Replace Log-Loading function in cache listing run into error because of GSs GDPR changes.
- [ ] Hide hints in cache listing behind a link with show/hide do not decrypt.
- [ ] Improve print page cache listing with hide disclaimer, decrypt hints, show other coord formats and hide side rights does not run.
