### ISSUE TITLE
Show the searched caches from the 81 matrix in a map doesn't work.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1168]
**Describe the bug**
If I open the link to missing combinations from my 81 matrix, only the list opens, not the map.

**To Reproduce**
1. Open https://www.geocaching.com/p/default.aspx?tab=stats#profilepanel
2. Click in the 81-matrix on the combination you are looking for
3. You will be directed to the search page, but not to the map

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox, Chrome

Ich habe mir das Coding nur kurz angeschaut. Scheinbar wird das #GClhMap nicht erkannt

**Comment by 2Abendsegler** [comment]
Ja, vermutlich gibt es den Map Button noch nicht. Das gehört sicherlich zu den Fehlern die durch GSs Änderungen entstehen.
Ich übernehm das.

**Comment by 2Abendsegler** [comment]
@capoaira: Issue gut beschrieben!

**Comment by 2Abendsegler** [comment]
Hängt nur damit zusammen, dass auf die neue Karte verlinkt wird und wir aber einen Link zur alten Karte erwarten..

**Comment by 2Abendsegler** [comment]
merged

**Comment by capoaira** [comment]
> @capoaira: Issue gut beschrieben!
Danke

Danke auch für den Fix
