### ISSUE TITLE
Error when you open a TB-Listing without logs

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1169]
Wenn man einen TB neu anlegt und noch nicht geloggt wurde, wird folgende Fehlermeldung angezeigt:
![grafik](https://user-images.githubusercontent.com/50927164/71923758-0491c300-318e-11ea-96c6-27da2886029e.png)

**Comment by 2Abendsegler** [comment]
Hast du vielleicht einen TB für mich?
Ich hatte hier etwas geändert zum letzten Release. Ich werde mir das mal ansehen.

**Comment by capoaira** [comment]
https://coord.info/TB9GHG8
Hier ist mir das aufgefallen. Ich denke man muss nur einmal prüfen, ob Logs vorhanden sind.

**Comment by 2Abendsegler** [comment]
GS geben hier eine weitere Zeile aus. 
`data on this page is cached for 3 mins`
Hat doch nichts mit meinen Änderungen zu tun, aber egal.

**Comment by 2Abendsegler** [comment]
merged
