### ISSUE TITLE
At latest logs in cache listing, title of picture is shown as a second box next to the log.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1191]
**Describe the bug**
The title of the picture is shown as a second box next to the log instead of next to the picture

**To Reproduce**
1. Go to a Cachelisting e.g. https://coord.info/GC8920C
2. Hover the Latest logs

![Bug](https://user-images.githubusercontent.com/50927164/72091294-1f8c4080-3310-11ea-8a0f-7058a099cc85.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox, chrome

Wenn mehr als 2 Bilder dem Log hinzugefügt wurden, wird eine leere Box angezeigt.

**Comment by 2Abendsegler** [comment]
Bei mir sieht das so aus wie bisher. Bilder werden hier gar nicht angezeigt, auch nicht die Box und auch nicht der Name des Bildes. 
Aber ich sehe es ja hier bei dir.

1. Prüfe mal bitte deine Add ons und deine Scripte, schalte mal alles aus, bis auf den GClh.

Es könnte damit zusammenhängen, dass wir länger warten müssen, bis die Latest Logs aufgebaut werden können. Auf den ersten Blick etwas dubios ist es dass die Box und der Platzhalter in GS Manier angezeigt werden und gleichzeitig der Name des Bildes durch den GClh.

2. Siehst du auch irgendwo das Bild? Das kann auch viel weiter unten stehen. Blätter mal mit der Maus nach unten.

**Comment by 2Abendsegler** [comment]
...
Hey, du bist ja Owner.

3.) Schau mal ob es hier auch ist. Die letzten beiden Logs haben auch Bilder.
https://coord.info/GC5BRZ6

**Comment by capoaira** [comment]
Alle Add ons mal abgeschaltet. Fehler leider immer noch. In der Vip list und der alten Karte werden die Logs normal ohne Bilder angezeigt.
Wenn ich auf den Bildplatzhalter klicke, öffnet sich das Bild. Also nicht wie in den Logs, sondern nur das Bild z.B. https://s3.amazonaws.com/gs-geo-images/6289a2e6-c95f-4f11-97ed-a55df5b01fb4_l.jpg
Das Bild sehe ich nirgends unten.
Bei deinem Beispiel ist das bei mir auch....
Ich gucke mir das morgen im wacheren Zustand nochmal in der Konsole an.

**Comment by Ruko2010** [comment]
Ich hab auch gerade mal reingeschaut. Ich kann den Fehler nicht nachstellen. Bei mir wird sowohl im FF als auch im Chrome kein Bild in der Logvorschau angezeigt. Ich arbeite aber auch auf dem Mac.

**Comment by capoaira** [comment]
Moin,
vieleicht hängt das mit FF-update zusammen. Ich gucke heute Nachmittag mal, welche Version ich jetzt habe.

**Comment by Ruko2010** [comment]
Ich nutz die neuste 72.0.1 (64-Bit), nur zur Info.

**Comment by 2Abendsegler** [comment]
Ja, und schau mal ob du mit der aktuellen GClh Version arbeitest ohne eigene Änderungen. Ist mir nur auch noch eingefallen. 

Ich hatte mir das schon mal angesehen. Eigentlich weiß ich gar nicht wie das funktionieren soll, weil die Bilder gar nicht an einer Stelle stehen die wir verarbeiten. Wir verarbeiten .LogContent und die Bilder stehen auf gleicher Höhe. Wir dürften die gar nicht bekommen.

**Comment by capoaira** [comment]
Die Idee war mir auch schon gekommen. Aber auch bei der aktuellen Version gab es den Fehler.

**Comment by capoaira** [comment]
Ich nutze auch Firefox 72.0.1 (64-Bit), daran scheint es also nicht zu liegen.

>Wir verarbeiten .LogContent und die Bilder stehen auf gleicher Höhe. Wir dürften die gar nicht bekommen.

Scheinbar werden die Bilder mitgeliefert, sie sind bei mir in der Klasse .LogContent enthalten.
![grafik](https://user-images.githubusercontent.com/50927164/72193099-44fc7580-3408-11ea-90a1-e9fc4d598293.png)

**Comment by 2Abendsegler** [comment]
Bei mir sieht es so aus:
![grafik](https://user-images.githubusercontent.com/22332216/72197455-cad8ea80-3421-11ea-91c7-c52085385ea0.png)

---
Du hast die Thumbnails of images ausgeschaltet. 
Boah eh, mir war nicht klar dass das solche Auswirkungen hat.
![grafik](https://user-images.githubusercontent.com/22332216/72197519-65d1c480-3422-11ea-8e6b-4f0492fb5e13.png)

---
### Aber wir haben jetzt den Übertäter. 😄

**Comment by 2Abendsegler** [comment]
Eigentlich wollte ich die Bilder aus den Logs mit in die Latest Logs aufnehmen, so wie es fälschlich bei der Deaktivierung der Thumbnails war. Das macht aber so viel Arbeit, weil dann auch die Icons in den VIP Tabellen geändert werden müssen und voe allem auch die Ausrichtung der Hover Bilder. Insbesondere auf letzteres habe ich keinen Bock. 

Hab also die Bilder aus den Latest Logs entfernt, so wie es eigentlich sein sollte.

@capoaira 
Kannst du dir das bitte ansehen und testen?
https://github.com/2Abendsegler/GClh/pull/1203

**Comment by 2Abendsegler** [comment]
@capoaira
Was mir gerade noch einfällt. Kannst du abschätzen ob das Problem erst mit der letzten Version gekommen ist?

**Comment by capoaira** [comment]
>Kannst du dir das bitte ansehen und testen?
#1203

Ja, so funktioniert das. Danke für den Fix

>Was mir gerade noch einfällt. Kannst du abschätzen ob das Problem erst mit der letzten Version gekommen ist?

Nein, leider nicht. Ich nutzt die Latest Logs eigentlich nicht um die Logs zu lesen. War ehr ein Zufall, das ich drauf gestoßen bin.

**Comment by 2Abendsegler** [comment]
merged

**Comment by 2Abendsegler** [comment]
Das Problem ist im derzeitigen master vorhanden. Das gilt jedoch NICHT bei blockiertem cookiebot.com. Hier handelt es sich mit sehr hoher Wahrscheinlichkeit also auch um ein Problem das durch die letzten Änderungen von GS zum Thema GDPR verursacht wird. Bezeichnung des Issue entsprechend angepasst.
