### ISSUE TITLE
Clicks on the latest logs icons or the log icons in the VIP tables do not work because of GSs GDPR changes.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1193]
Clicks on the latest logs icons or the log icons in the VIP tables do not work because of GSs GDPR changes.

Apparently GS simply creates the 25 logs again when they are gone. And that in the form `<table> <tr>`, there is no `<tbody>`. There was earlier an error in the Release Notes that no logs are shown.

![grafik](https://user-images.githubusercontent.com/22332216/72121379-2b512480-335b-11ea-9ed5-b60e0f0f621a.png)

As a result, the log IDs exist twice and a link no longer works.

**Comment by 2Abendsegler** [comment]
Da bekommt man echt einen Anfall. 🤪

**Comment by 2Abendsegler** [comment]
merged

**Comment by Ruko2010** [comment]
> Da bekommt man echt einen Anfall. 🤪

Ich kann dir das nachempfinden. Diese ganzen blöden Änderungen und das ganze asynchrone gelade macht echt keinen Spaß! Das wird immer komplizierter für Entwickler.
Aber du machst echt einen Klasse Job bei dem ganzen DSGVO scheiß! Das musste mal gesagt werden 😉.
