### ISSUE TITLE
Make "copy to clipboard" a function to reduce code duplication

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#1195]
Try to make a function out of the code for copy to clipboard to make it easy to use in the code and reduce code duplication.

**Comment by Ruko2010** [comment]
Folgende Funktion gibt es (nach dem Merge):

`/*
        element_to_copy:    innerHtml of this element will be copied. If you pass
                            a string, the string will be the copied text. In this 
                            case you have to pass an anker_element!!!

        anker_element:      after this element the copy marker will be inserted,
                            if you set this to null, the element_to_copy will be
                            used as an anker

        title:              you can enter a text that will be displayed between 
                            Copy --TEXT OF TITLE-- to clipboard. If you leave it 
                            blank, it will just "Copy to clipboard" be displayed

        style               You can add styles to the surrounding span by passing
                            it in this variable
     */
    function addCopyToClipboardLink(element_to_copy, anker_element= null, title="", style= "")`

**Comment by 2Abendsegler** [comment]
Ist ja schon gemerged. Close.
