### ISSUE TITLE
[New Map] Copy GC-Code to clipboard

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1196]
In Bearbeitung

**Comment by Ruko2010** [comment]
Vielleicht wartest du damit lieber noch, bis ich die Copy Sache in eine Funktion gepackt habe. Dann hast du weniger Aufwand.

**Comment by capoaira** [comment]
Ja, ich habe erstmal des Issue Erstellt. Ich Ändere das dann später oder willst du das gleich in einem Rutsch erledigen?
Meine Pause ist jetzt vorbei...

**Comment by Ruko2010** [comment]
Dann nehm ich das gleich mit auf meine Liste. Dann hab ich auch gleich ein Testobjekt.
