### ISSUE TITLE
[New Map] Strike through title of disabled caches

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1197]
In Bearbeitung

**Comment by 2Abendsegler** [comment]
Der Config Parameter zu den Bookmark Listen hat den Vorteil dass man den Cachenamen durchstreichen kann, oder ihm eine andere Farbe geben kann, oder beides machen kann. Bei deinem Config Parameter geht nur beides.
![a3](https://user-images.githubusercontent.com/22332216/72323258-8ca12c80-36a8-11ea-80bd-daf984445232.JPG)

Das könntest du vielleicht noch anpassen. 
Und wenn du schon dabei bist, dann könntest du noch ein Komma bei den beiden Config Parametern zu den Bookmark Listen setzen: `... strike through, in color ...`

**Comment by capoaira** [comment]
Ok, wird gemacht.
Dabei fällt mir auf, dass ich den Namen nur die in den Cache Details durchstreiche, aber nicht in der Liste. Das hole ich gleich nach.
Soll es dafür 2 Parameter geben? Weil "Show name of disabled caches" wird ja in den Cachedetails nicht gebraucht, in der Liste schon.
Oder man macht Tatsächlich ein Parameter im Globalen Config (und führt die Funktion auch im Dashboard ein), wie du es kurz in #1192 vorgeschlagen hattest. Ist ein Frage von Aufwand und Nutzen...

**Comment by 2Abendsegler** [comment]
Meinst du "Show name of ARCHIVED caches" wird nicht gebraucht? Ansonsten verstehe ich das nicht.

Ein Parameter sollte hier reichen. Vielleicht muss man die Beschreibung des Parameters noch etwas anpassen. Wenn in der Liste auch archivierte stehen können, dann zwei Parameter.

Lass uns die Vereinheitlichung in globale Parameter irgendwann anschließend machen, wenn überhaupt

**Comment by 2Abendsegler** [comment]
Das mit der Liste habe ich dann auch endlich verstanden.
Funktioniert prima, beides.

merged
