### ISSUE TITLE
[New Map] Show button to collapse activity

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1198]
In Bearbeitung

**Comment by 2Abendsegler** [comment]
Ich kann nicht so wirklich den Mehrwert dieses Buttons erkennen. Insofern hätte man das aus meiner Sicht gar nicht einbauen müssen. Mit meiner Meinung bin ich aber etwas spät dran, schließlich gibt es das Issue schon 4 Tage. 

Ich finde man sollte kein Feature deshalb einbauen, weil man Lust zum entwickeln hat oder einfach weil man es kann. Man sollte es einbauen, weil es für uns und die anderen User einen Mehrwert bringt. Das hängt auch damit zusammen, dass wir das Feature warten müssen.

Ansonsten sieht das gut aus.

**Comment by 2Abendsegler** [comment]
Funktioniert prima.

merged
