### ISSUE TITLE
[New Map] Show hint automatically

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1199]
In Bearbeitung

**Comment by 2Abendsegler** [comment]
1.) `Hide hint` funktioniert erst beim zweiten Klick.

2.) Eigentlich sollte das gar kein Link sein, sondern ein Button. 

2.1) Wir könnten also vielleicht den Schiebebutton verwenden, den wir auch schon beim Hide Header verwendet haben.

2.2) Oder wir machen es als Link, aber dann so wie im Cache Listing.
Im Cache Listing sieht es so aus:
![a1](https://user-images.githubusercontent.com/22332216/72319165-c2411800-369e-11ea-939a-5d8489cbf37c.JPG)
![a2](https://user-images.githubusercontent.com/22332216/72319170-c53c0880-369e-11ea-869a-e24aba7d6caf.JPG)
- Also in Klammern und nur Show bzw. Hide.
- Und der Text wird tatsächlich ausgeblendet und nicht übermalt.

Ich weiß, das sind Erfindungen von GS, aber wenn wir schon dran gehen ...

3.) Könntest du die Bezeichnung im Config anpassen?
Show hint of cache automatically on cache detail screen

**Comment by capoaira** [comment]
Ich würde mich für 2.1 entscheiden. Persönlich finde ich den grauen Balken gut, weil man so auf einen Blick sieht, dass es einen Hint gibt. Den würde ich ungern entfernen. Meine Meinung. Damit würde dann auch Punkt 1 behoben sein.

**Comment by 2Abendsegler** [comment]
Wenn kein Hint vorhanden ist, dann wird der ganze Hintkram auch nicht angezeigt. Dann gibt es nur die Description. Hab ich gerade ausprobiert. Grauer Balken ist dazu also nicht notwendig. :)

**Comment by capoaira** [comment]
Ich meine nur, dass man ja dann nur `Hint` da stehen hätte, dass kann man (bzw. ich ;)) auch übersehen.

**Comment by 2Abendsegler** [comment]
Ok, dann lass den Balken ... blindes Huhn. 😂

**Comment by 2Abendsegler** [comment]
Sieht klasse aus.

Nur noch ne Kleinigkeit:
Wenn man einen anderen Cache aus der Karte per Klick auswählt, wird der Hint nicht entschlüsselt. Si wie es aussieht wird er nur beim ersten Mal entschlüsselt.

**Comment by 2Abendsegler** [comment]
Bitte mach vor erneuten Änderungen eine neue Branch aus dem collector.

**Comment by 2Abendsegler** [comment]
merged
