### ISSUE TITLE
Consider script GCTour also in feature "copy corrected coordinates".

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1200]
Consider script GCTour also in feature "copy corrected coordinates".

xxx und yyy habe ich ersetzt.

![grafik](https://user-images.githubusercontent.com/22332216/72176024-d30f3680-33dd-11ea-9fef-ad07d89afc87.png)

Folgendes wird kopiert:
`<small><div style="font-weight:bold;">N 49°28.xxx E 008°35.xxx&nbsp;&nbsp;-&nbsp;&nbsp;changed by GCTour</div> (N 49° 28.yyy E 008° 35.yyy)</small>`

Example for me: https://coord.info/GC5FQDG

**Comment by 2Abendsegler** [comment]
merged

**Comment by 2Abendsegler** [comment]
Der Button rechts "Copy Data to Clipboard" funktioniert noch nicht sauber. Hier darf der Aufbau der Punkte im Dropdown erst stattfinden wenn man mit der Maus darüber geht. Und er muss auch immer wieder erneut stattfinden, weil sich zwischenzeitlich die GCTour Koordinaten geändert haben könnten. Es werden zwar im Moment die richtigen Koordinaten ermittelt, es wird aber nicht bemerkt, dass es keine geänderten Koordinaten mehr gibt und deshalb der Punkt aus dem Dropdown entfernt werden müßte und umgekehrt.

**Comment by Herr-Ma** [comment]
Sorry, da ist was an mir vorbei gegangen: wie ändere ich denn mit GC-Tour die Koordinaten?

**Comment by 2Abendsegler** [comment]
Schön dass du dich kümmern möchtest!

Ich bin aber schon dran. Und ich hatte bei der Implementierung auch nicht daran gedacht. So was passiert.

Zum Nachstellen:
Bei GCTour gibt es im Listing 3 Buttons.  Einer ist zum Verschieben der Koordinaten. Schau dir anschließend die Stelle mal an wo die Koordinaten stehen. Das ist aber bereits gefixt. 
Jetzt muss nur noch dafür gesorgt werden, dass die Einträge im Menü erst beim Klick aufgebaut werden, damit Änderungen durch GCTour mitgenommen werden. Wie gesagt, ich bin bereits dran. Leg die Füße hoch. :)

**Comment by 2Abendsegler** [comment]
@Herr-Ma 

Moin,

schau dir bitte mal die Änderungen vorab an.

[Link zum Pull Request.](https://github.com/2Abendsegler/GClh/pull/1223) 
[Pull Request installieren.](https://github.com/2Abendsegler/GClh/raw/2a87275532bd1eff4dae4546fdd7bd12521f5e92/gc_little_helper_II.user.js)
([Master installieren.](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js))

**Copy Data Menü:**

1. Das Copy Data Menü wird jedesmal wenn man mit der Maus drüberfährt neu aufgebaut. Damit ist sichergestellt, dass das Menü immer die aktuellen Einträge enthält.
2. Sind GCTour Koordinaten vorhanden, werden sie über einen GCTour Menü Eintrag kopiert. Die anderen Einträge im Menü bleiben unverändert.
3. Das Menü steht erst zur Verfügung, wenn die notwendigen unsafeWindow Felder von GS zur Verfügung gestellt wurden. Der Zeitverzug entsteht durch die aktuellen Änderungen von GS zur Datenschutz-Grundverordnung ... .

**Copy Data Button:**

1. Per Button werden immer die angezeigten Koordinaten kopiert. Das sind die Korrigierten Koordinaten oder die Original Koordinaten. Der title zum Button wird entsprechend der Koordinaten angepasst gesetzt. 
2. GCTour Koordinaten werden mit diesem Button nicht verarbeitet.
3. Der Button steht auch erst zur Verfügung, wenn die notwendigen unsafeWindow Felder von GS zur Verfügung gestellt wurden. Der Zeitverzug entsteht durch die aktuellen Änderungen von GS zur Datenschutz-Grundverordnung ... .

Ich habe auf die Schnelle keinen Cache mit GS Checker und bekannten Koordinaten gefunden. Ein solcher Test steht also noch aus. Kannst du hier vielleicht aushelfen? 
Es geht darum zu prüfen, was beim automatischen Update eines erfolgreichen Checkers passiert. Gibt es GCTour Koordinaten, werden diese vermutlich überschrieben. Nach einem Refresh der Seite sind sie aber wieder da. Ansonsten sollte das nicht anders laufen als bei einer manuellen Korrektur der Koordinaten. Ich hoffe mal der Button verschwindet nicht. 

Bitte gib Bescheid wenn noch etwas zu ändern ist und auch wenn es ok ist. Und bitte teile gegebenenfalls das Ergebnis des Checkertests.

LG 

@Ruko2010 
Ich habe noch einige Dinge geändert die sicherlich auch dein Issue #1195 betreffen. Warte aber mal bis @Herr-Ma sich geäußert hat, bevor du weitere Anpassungen machst.
Falls alles so bleibt vermute ich dass dieser Button beim #1195 nicht ohne weiteres zu integrieren ist, weil hier vieles anders ist. Aber das weißt du besser.

**Comment by Herr-Ma** [comment]
Guten Morgen,

(ich hoffe du schläfst jetzt...deine Mail um 3:04 Uhr lässt so einiges
erahnen :-)

*Test Step 1*:
Schritt: Öffnen eines Listings (ohne korrigierte Koordinaten, ohne
GCTour-Koordinaten)

Copy Data Menü:
1. Erwartet: nur Anzeige von 'Coordinates'
Test: ok
2. Erwartet: nach Auswahl werden die angezeigten Koordinaten ins Clipboard
kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten
Test: ok

*Test Step 2*:
Zustand: Listing geöffnet, keine korrigierten oder GCTour Koordinaten
gesetzt
Schritt : Manuelles Setzen von Korrigierten Koordinaten

Copy Data Menü:
1. Erwartet: Anzeige von 'Corrected Coordinates' und 'Original Coordinates'
Test: ok
2. Erwartet: nach Auswahl von 'Corrected Coordinates'  'werden die
korrigierten Koordinaten ins Clipboard kopiert
Test: ok
3. Erwartet: nach Auswahl von 'Original Coordinates'  'werden die original
Koordinaten ins Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden die korrigierten Koordinaten)
Test: ok

*Test Step 3*:
Zustand: Listing geöffnet, keine korrigierten oder GCTour Koordinaten
gesetzt
Schritt : Setzen von Korrigierten Koordinaten über den GC-internen
Solution-Checker

Copy Data Menü:
1. Erwartet: Anzeige von 'Corrected Coordinates' und 'Original Coordinates'
Test: fail - nur Eintrag 'Coordinates' vorhanden
Das war aber schon immer so!
2. nach Auswahl von 'Coordinates'  'werden die korrigierten Koordinaten ins
Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden die korrigierten Koordinaten)
Test: ok

*Nach einem Refresh der Seite funktioniert alles, wie es sein sollte. Auch
sind alle Anzeigen und alle Menüeinträge vorhanden *

*Test Step 4*:
Zustand: Listing geöffnet, keine korrigierten oder GCTour Koordinaten
gesetzt
Schritt : Verschieben der Koordinaten mit GCTour

Copy Data Menü:
1. Erwartet: Anzeige von 'Coordinates' und 'GCTour Coordinates'
Test: ok
2. Erwartet: nach Auswahl von 'Coordinates'  'werden die original
Koordinaten ins Clipboard kopiert
Test: ok
3. Erwartet: nach Auswahl von 'GCTour Coordinates'  'werden die mit GCTour
verschobenen Koordinaten ins Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden neben dem Button die original und darüber die GCTour Koordinaten,
das ganze fett in schwarz (SEHR GUT!))
Test: ok

*Test Step 5*:
Zustand: Listing geöffnet, korrigierten Koordinaten gesetzt
Schritt : Verschieben der Koordinaten mit GCTour

Copy Data Menü:
1. Erwartet: Anzeige von 'Corrected Coordinates', 'Original Coordinates'
und 'GCTour Coordinates'
Test: ok
2. Erwartet: nach Auswahl von 'Corrected Coordinates'  'werden die
korrigierten Koordinaten ins Clipboard kopiert
Test: ok
3. Erwartet: nach Auswahl von 'Original Coordinates'  'werden die original
Koordinaten ins Clipboard kopiert
Test: ok
4. Erwartet: nach Auswahl von 'GCTour Coordinates'  'werden die mit GCTour
verschobenen Koordinaten ins Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden neben dem Button die korrigierten und darüber die GCTour
Koordinaten, das ganze fett in rot)
Test: ok

*Test Step 6*:
Zustand: Listing geöffnet, mit GC-Tour verschobene Koordinaten vorhanden
Schritt : Manuelles Setzen von Korrigierten Koordinaten

Copy Data Menü:
1. Erwartet: Anzeige von 'Corrected Coordinates', 'Original Coordinates'
und 'GCTour Coordinates'
Test: ok
2. Erwartet: nach Auswahl von 'Corrected Coordinates'  'werden die
korrigierten Koordinaten ins Clipboard kopiert
Test: ok
3. Erwartet: nach Auswahl von 'Original Coordinates'  'werden die original
Koordinaten ins Clipboard kopiert
Test: ok
4. Erwartet: nach Auswahl von 'GCTour Coordinates'  'werden die mit GCTour
verschobenen Koordinaten ins Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden neben dem Button die korrigierten und darüber die GCTour
Koordinaten, das ganze fett in rot)
Test: ok

*Test Step 7*:
Zustand: Listing geöffnet, mit GC-Tour verschobene Koordinaten vorhanden
Schritt : Setzen von Korrigierten Koordinaten über den GC-internen
Solution-Checker

Copy Data Menü:
1. Erwartet: Anzeige von 'Corrected Coordinates', 'Original Coordinates'
und 'GCTour Coordinates'
Test: fail - es gibt nur den Eintrag 'Coordinates'
Dieser kopiert die vom Solution-Checker korrigierten Koordinaten

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden neben dem Button die korrigierten und darüber die GCTour
Koordinaten, das ganze fett in rot)
Test: ok
Aber. es werden keine GCTour-Koordinaten angezeigt

*Nach einem Refresh der Seite funktioniert alles, wie es sein sollte. Auch
sind alle Anzeigen und alle Menüeinträge vorhanden*

*Test Step 8*:
Zustand: Listing geöffnet, korrigierte Koordinaten vorhanden, mit GC-Tour
verschobene Koordinaten vorhanden
Schritt : Löschen der GCTour Koordinaten

Copy Data Menü:
1. Erwartet: Anzeige von 'Corrected Coordinates' und  'Original
Coordinates'
Test: ok
2. Erwartet: nach Auswahl von 'Corrected Coordinates'  'werden die
korrigierten Koordinaten ins Clipboard kopiert
Test: ok
3. Erwartet: nach Auswahl von 'Original Coordinates'  'werden die original
Koordinaten ins Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (die
Korrigierten, fett in rot)
Test: ok

*Test Step 9*:
Zustand: Listing geöffnet, korrigierte Koordinaten vorhanden, mit GC-Tour
verschobene Koordinaten vorhanden
Schritt : Löschen der korrigierten Koordinaten

Copy Data Menü:
1. Erwartet: Anzeige von 'Coordinates' und 'GCTour Coordinates'
Test: ok
2. Erwartet: nach Auswahl von 'Coordinates'  'werden die original
Koordinaten ins Clipboard kopiert
Test: ok
3. Erwartet: nach Auswahl von 'GCTour Coordinates'  'werden die mit GCTour
verschobenen Koordinaten ins Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden neben dem Button die original und darüber die GCTour Koordinaten,
das ganze fett in schwarz)
Test: ok

*Test Step 10*:
Zustand: Listing geöffnet, korrigierte Koordinaten vorhanden
Schritt : Löschen der korrigierten Koordinaten

Copy Data Menü:
1. Erwartet: Anzeige von 'Coordinates'
Test: ok
2. Erwartet: nach Auswahl von 'Coordinates'  'werden die original
Koordinaten ins Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden die original Koordinaten)
Test: ok

*Test Step 11*:
Zustand: Listing geöffnet, mit GC-Tour verschobene Koordinaten vorhanden
Schritt : Löschen der GCTour Koordinaten

Copy Data Menü:
1. Erwartet: Anzeige von 'Coordinates'
Test: ok
2. Erwartet: nach Auswahl von 'Coordinates'  'werden die original
Koordinaten ins Clipboard kopiert
Test: ok

Copy Data Button:
Erwartet: Kopieren der neben dem Button angezeigen Koordinaten (angezeigt
werden die original Koordinaten)
Test: ok


Testergebnis:
Das automatische Setzen des GC-internen Solution-Checkers spukt uns noch in
die Suppe (Siehe Test 3 und Test 7). Ansonsten funktioniert alles wie
gewünscht. Insbesondere gefällt mir, dass der Button auch wirklich immer
die direkt rechts daneben stehenden Koordinaten kopiert und nicht durch
GCTour-Koordinaten beeinflusst wird. Inwieweit sich der Aufwand lohnt, das
automatische Korrigieren der Koordinaten via Solution-Checker zu erkennen
und entsprechend zu reagieren, kann ich nicht abschätzen - insbesondere, da
nach einem Refresh der Seite alles in Ordnung ist

VG, Marcus

Am Mi., 15. Jan. 2020 um 03:04 Uhr schrieb 2Abendsegler <
notifications@github.com>:

**Comment by 2Abendsegler** [comment]
Yeah, super getestet!

Ich hatte ja schon vermutet dass der GC-interne Solution-Checker Probleme machen könnte. Wir sind aber eigentlich gut aufgestellt, weil wir das Menü immer neu erstellen wenn die Maus drüberhuscht. Ich würde mir das gerne ansehen. Gib mir doch bitte einen Cache mit GC-internem Solution-Checker und Lösungskoordinaten per Mail, dann muss ich nicht auf die Suche gehen. Ich werde die Daten nur hier für die Tests verwenden.

Der Button erscheint zuerst mal in Pastellfarben und ohne die Möglichkeit ihn anzuwählen. Wenn das bei dir nicht so ist, dann hängt das vermutlich damit zusammen dass du die Seite cookiebot.com blockst. Die ist nämlich dafür verantwortlich dass es zur Zeit etwas länger dauert.

**Comment by Ruko2010** [comment]
Wow. das nenn ich mal ausführlich getestet, danke @Herr-Ma . Ich schau mal was ich ändern kann, damit wir alle Tests "grün" bekommen 😉.

**Comment by 2Abendsegler** [comment]
@Herr-Ma 

Danke für die Daten!

GS macht auf die eigenen Felder keinen Update, klar ne. 😲

Magst du nochmal drüberschauen. Passt jetzt auch für den GC-internen Solution-Checker. Lediglich die 'GCTour Coordinates' werden überschrieben (bis zum nächsten Refresh). Damit können leben.

[Link zum Pull Request.](https://github.com/2Abendsegler/GClh/pull/1223) 
[Pull Request installieren.](https://github.com/2Abendsegler/GClh/raw/bbf1246dd68624eaf3b784b3513fb66b5ba7f201/gc_little_helper_II.user.js)
([Master installieren.](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js))

---
*Test Step 3*:
Zustand: Listing geöffnet, keine korrigierten oder GCTour Koordinaten gesetzt
Schritt : Setzen von Korrigierten Koordinaten über den GC-internen Solution-Checker

Copy Data Menü:
1. Erwartet: Anzeige von 'Corrected Coordinates' und 'Original Coordinates'
Test: ok

*Test Step 7*:
Zustand: Listing geöffnet, mit GC-Tour verschobene Koordinaten vorhanden
Schritt : Setzen von Korrigierten Koordinaten über den GC-internen Solution-Checker

Copy Data Menü:
1. Erwartet: Anzeige von 'Corrected Coordinates', 'Original Coordinates' und 'GCTour Coordinates'
Test: fail - es gibt die Einträge 'Corrected Coordinates' und 'Original Coordinates'. 'GCTour Coordinates' fehlen.
Damit können wir leben.

---
@Ruko2010 
Bin schon dran. Scheint nun ok.

**Comment by Ruko2010** [comment]
> @Ruko2010
> Bin schon dran. Scheint nun ok.

Heißt das ich muss auch hier nix mehr machen? https://github.com/2Abendsegler/GClh/pull/1218

**Comment by 2Abendsegler** [comment]
> Heißt das ich muss auch hier nix mehr machen? #1218

Sorry, aber du musst noch was machen. 
Ich würde den Button zum Kopieren der Koordinaten nicht über die function laufen lassen, nur die GC Codes.
Ich würde als nächsten den PR hier mergen. Im 1218 solltest du nur die Änderungen zum Button zum Kopieren der Koordinaten zurücknehmen, dann sollte es passen. Ich kann aber auch nochmal mit drüberschauen.

**Comment by Herr-Ma** [comment]
Jetzt ist komplett was im argen, so kann ich nicht testen :(

![grafik](https://user-images.githubusercontent.com/23725271/72416095-35698d80-3776-11ea-9c8a-deb248a6ad82.png)

**Comment by Herr-Ma** [comment]
Jetzt ist komplett was im argen - so macht das testen keinen Sinn, da die Grundvoraussetzungen nicht gegeben sind :(

![grafik](https://user-images.githubusercontent.com/23725271/72416189-6b0e7680-3776-11ea-8636-0376d08d50aa.png)

**Comment by 2Abendsegler** [comment]
Ja, stimmt, nochmal schnell was geändert und schon scheiße.
Mein Fehler.

**Comment by Ruko2010** [comment]
> Ich würde den Button zum Kopieren der Koordinaten nicht über die function laufen lassen, nur die GC Codes.

ok, aber wenn ich die Änderungen für das Copy des Buttons zurück nehme, dann haben wir doch immer noch die gleichen Probleme, da der Ursprüngliche Code doch auch bei Seitenladen kopiert hat, und nicht erst wenn man auf den Button klickt, oder?
D.h. die Funktion fürs Kopieren der Koords müssen wir dann dennoch neu machen, richtig?

**Comment by 2Abendsegler** [comment]
@Ruko2010  
Die Änderungen für die Koords habe ich alle gemacht. Das ist so umgestellt dass erst beim Klicken Daten ermittelt werden.

**Comment by Herr-Ma** [comment]
Gib bitte Bescheid, wenn ich nochmal testen soll (incl. Link). Hab jetzt erstmal Daily Scrum *facepalm*

**Comment by Ruko2010** [comment]
> @Ruko2010
> Die Änderungen für die Koords habe ich alle gemacht. Das ist so umgestellt dass erst beim Klicken Daten ermittelt werden.

ok, dann nehm ich das Coding für die Koords aus meinem PR wieder raus.

**Comment by 2Abendsegler** [comment]
@Herr-Ma

> Hab jetzt erstmal Daily Scrum _facepalm_ 😂 

[Link zum Pull Request.](https://github.com/2Abendsegler/GClh/pull/1223) 
[Pull Request installieren.](https://github.com/2Abendsegler/GClh/raw/71901c89480d6f6e3fc47f74e6c81652846c8ec4/gc_little_helper_II.user.js)
([Master installieren.](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js))

Die Koordinaten werden manchmal mit Komma und manchmal ohne abgelegt. Die Dinge hatte ich ersetzt. Dachte aber kurz vor Ende das bräuchte sie doch nicht. Peinlich. 🙄

Bitte nochmal drüberschauen.

**Comment by 2Abendsegler** [comment]
(Ich bin jetzt mal kurz weg zum Frühstücken außer Haus.)

**Comment by Ruko2010** [comment]
Ich hab die Funktion zum Kopieren der Koordinaten wieder raus genommen bei mir. Außerdem ist die ctoc funktion nun an der richtigen stelle im Coding.

**Comment by Herr-Ma** [comment]
> @Herr-Ma
> 
> > Hab jetzt erstmal Daily Scrum _facepalm_ 😂
>

Das ist nicht lustig 😭 ... eher 🤢
 
> Bitte nochmal drüberschauen.

Jetzt funktioniert alles einwandfrei 👍🏻 (Bis auf das Sonderzeichen, das bei dir irgendwie ganz vorne im Script reingekommen ist und es damit gar nicht läuft 😉)

**Comment by 2Abendsegler** [comment]
merged
