### ISSUE TITLE
The TB autovisit feature on the old log page does not work because of GSs GDPR changes.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1205]
The TB autovisit feature on the old log page does not work because of GSs GDPR changes.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Hab zum Testen wieder deinen archivierten Lobdepark genommen. Und es ist mir auch leider wirklich wieder ein Log durchgerutscht. 🙄 Habs wieder gelöscht.

**Comment by 2Abendsegler** [comment]
merged

**Comment by Ruko2010** [comment]
Kannst du gern nutzen. Kein Problem.
