### ISSUE TITLE
"add multiple caches to Flopp" feature

### ISSUE THREAD

**Issue by ztNFny** [2Abendsegler/GClh#1213]
I've implemented for myself a little script and was wondering whether there's interest to have this in GClh.

I often want to view multiple caches on a Flopp map (as it's a lot better than the GC map). To achieve this I've added "add/remove/view" buttons to the listing page. "Add" adds the current cache to a list (stored with GM_setValue), "remove" obviously removes it again. "View" will then open Flopp with all caches currently in the list.
Example of generated URL: https://flopp.net/?z=15&t=OSM&d=O:C&m=*O:47.64897:-122.34812:161:GCK25B:ffffff*O:47.64998:-122.34842:161:GC1F79P:E68334*O:47.64945:-122.34255:161:GC3Z3PE:8D1C1F*O:47.65103:-122.34718:161:GC20Y24:208552

If there's interest in having this feature in GClh I'll create a cleaner version and integrate it.
One issue I'm currently struggling with - maybe you have a recommendation - is how to store the list. I'm using GM_setValue which works fine in Tampermonkey on desktop but not in Firefox Android.

I'm attaching my current standalone script: [GCMyOwnStuff.user.js.txt](https://github.com/2Abendsegler/GClh/files/4050422/GCMyOwnStuff.user.js.txt)

**Comment by 2Abendsegler** [comment]
Yes, I think that's a nice feature. 😀
If you want, you can implement it.

I would like to give you a few tips and rules, so that the implementation is pleasant for you. It's mainly about where to do what in the script. If something isn't perfect, it doesn't matter. We will then adjust one or the other.
I can't do that today, but only in the next few days.

Is that okay for you?

**Comment by 2Abendsegler** [comment]
@Ruko2010, @capoaira 
(Der Issue Owner kann deutsch.)

Ich fand das Feature auf den ersten Blick ganz gut. Beim zweiten Blick kamen mir jedoch Bedenken, ob wir das Feature implementieren sollten.

Ich hatte noch etwas damit rumgespielt und dabei ist mir aufgefallen, dass man damit versuchen könnte einen Mystery zu knacken anhand der freien Flächen auf der Karte gemäß der Abstandsregeln. Manche Mysteries sind natürlich nur so oder mit Hilfe anderer lösbar. Und man kann die Karte auch manuell in dieser Art verwenden. Biedes ist schon klar.

Ich möchte den Cachern aber kein Werkzeug an die Hand geben, um ein solches Knacken in einfachster Form durchzuführen. Ich schätze hier könnte es auch einen Shitstorm geben von denjenigen die Mysteries legen. Und sie hätten auch irgendwie recht damit.

Was meint ihr dazu.
Ihr könnt mal den Link ganz oben anwählen und euch das Erklärte dann vorstellen. Das sollte schon reichen.

**Comment by ztNFny** [comment]
Das gleiche Ergebnis ist übrigens mit PGC erreichbar, nur da halt nicht mit der schönen Karte von Flopp. Man könnte natürlich auf den 161m Kreis verzichten (oder ihn konfigurierbar machen und Default=0)

![PGC.jpg](https://user-images.githubusercontent.com/1258173/72325115-bb210680-36ac-11ea-8125-07e2c03e73bd.jpg)

**Comment by Ruko2010** [comment]
Ich sehe das nicht als Problem. In meinem Geocaching App (Looking4Cache) kann ich das auch ganz easy machen. Da geht es sogar direkt über die Suche von Caches auf der Karte und dann dran Kreis anmachen. Also ich denke nicht, dass wir hier jemand Hilfe beim Lösen von Mysteries geben .
Ich nutze dieses Feature gern, denn bei uns in der Stadt sind die Versteckmöglichkeiten recht dürftig, da schon viele Caches liegen. So kann man sich schnell einen Überblick verschaffen, wo man noch etwas legen kann.

![IMG_7DEA8E847013-1](https://user-images.githubusercontent.com/2239440/72329539-34bcf280-36b5-11ea-8fb9-7988ec9f785c.jpeg)

**Comment by capoaira** [comment]
Moin,
mir hätte dieses Tool einiges an Arbeit gespart. Ich habe eine solche Karte von Hand erstellt habe, um zu sehen ob ich an einer Stelle noch einen Cache verstecken kann.
Dann wäre es schön, wenn das Script auch WPs zu Flopps überträgt.


>Ich möchte den Cachern aber kein Werkzeug an die Hand geben, um ein solches Knacken in einfachster Form durchzuführen. Ich schätze hier könnte es auch einen Shitstorm geben von denjenigen die Mysteries legen. Und sie hätten auch irgendwie recht damit.

Es ist evt. nicht unbedingt ein Feature welches zum GClh passt, aber an sich finde ich es gut.

**Comment by ztNFny** [comment]
> Dann wäre es schön, wenn das Script auch WPs zu Flopps überträgt.
Da sehe ich das Problem, dass es nicht möglich ist (zumindest ist mir nichts bekannt), zwischen virtuellen und physischen Wegpunkten zu unterscheiden. Für die Suche nach möglichen Verstecken sind ja nur letztere relevant. 
Oder optional?

**Comment by capoaira** [comment]
Man könnte es anhand der WP-Icons abfragen:
![2020-01-15](https://user-images.githubusercontent.com/50927164/72472694-587f5600-37e5-11ea-84b0-7aeeab64a7b0.png)

**Comment by ztNFny** [comment]
ach Tatsache, da gibt's nen Unterschied zwischen virtuellen und physischen Stationen. Dann ist's kein Problem nur die aufzunehmen.
Xpath: //*[@id="ctl00_ContentBody_Waypoints"]//tr[td/img/@alt="Physical Stage"]

**Comment by ztNFny** [comment]
bzw noch schöner "cmapAdditionalWaypoints" ist ein Array der Wegpunkte, type=219 ist physical stage. Dann muss man nicht das blöde DOM parsen.

**Comment by ztNFny** [comment]
Wobei ... dann würde das ja der bestehenden Flopp-Funktion recht nahe kommen. Nur statt den Link zu öffnen halt in eine Liste schreiben. Sollte man also möglichst dort integrieren statt es als eigenständige Funktion zu schreiben. Da muss ich mich mal mit dem bestehenden Flopp-Code auseinandersetzen um zu schauen ob/wie man den wiederverwenden oder erweitern kann.

**Comment by 2Abendsegler** [comment]
@ztNFny 
Moin,
wie bereits per Message angekündigt, bereitet mir diese Implementierung nach wie vor Bauchschmerzen. Ich möchte daher von einer Implementierung dieses Features im GClh absehen. Eine entsprechende interne Abstimmung ist erfolgt. 
Sorry.
Ich werde das Issue nun schließen.
