### ISSUE TITLE
Show both tabs in list of pocket queries of one page does not work because of GSs GDPR changes.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1214]
**Screenshots**
With firefox:
![firefox](https://user-images.githubusercontent.com/50927164/72221116-c3b3f880-3557-11ea-9692-d92de64f3f44.png)
With chrome:
![chrome](https://user-images.githubusercontent.com/50927164/72221141-ed6d1f80-3557-11ea-9073-dbd3a9b12b81.png)
My Settings
![Config](https://user-images.githubusercontent.com/50927164/72221132-ddedd680-3557-11ea-93dd-7eee789f175d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox, chrome

Wenn ich cookiebot.com blockiere, funktioniert es.

**Comment by 2Abendsegler** [comment]
Ok, danke. Ich werde das übernehmen.

**Comment by 2Abendsegler** [comment]
@capoaira 
Toll dass du dich auch fleißig bei der Meldung von Fehlern beteiligst und auch immer etwas am Mitlesen bist, kann ja schon nervig sein wenn ständig was kommt wie im Moment. 
Eigentlich war ich alles durchgegangen und hatte gehofft alle Fehler erwischt zu haben vor der letzten Version, aber es sind leider nicht nur die `unsafeWindow` Dinge. Die Einstellungsmöglichkeiten sind aber mittlerweile so groß geworden, dass man unmöglich alles ausprobieren kann.
Also nochmal, toll, und die Beschreibungen sind auch super. 😄

**Comment by 2Abendsegler** [comment]
In beiden Browsern getestet.

merged
