### ISSUE TITLE
[New Map] Adapt the width of the pop up

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1219]
![Map pop up](https://user-images.githubusercontent.com/50927164/72271193-bb76be80-3626-11ea-8ddb-57b0cb632900.png)
Durch Zufall habe ich das Map pop up entdeckt, welches sich öffnet, wenn mit rechtsklick auf einen Cache der Karte klickt.
Bei langen Namen wird der Name durch ... gekürzt.

Ich würde daran arbeiten.

**Comment by Ruko2010** [comment]
Is ja cool. Das Feature mit dem Rechtsklick kannte ich auch noch nicht.

**Comment by 2Abendsegler** [comment]
Die rechte Maustaste war mal ne Anforderung. Die gabs also nicht schon immer.

Du hast das schön gemacht und du hast die Punkte auch etwas zusammengeschoben, insofern gut. 
Andererseits ist auch das hier etwas was nicht wirklich einen Mehrwert bringt.

**Comment by 2Abendsegler** [comment]
`Adapt the width of the pop up`
 
Die Bezeichnung im Config ist nicht selbsterklärend. Jetzt kannten wir noch nicht mal das Pop-Up, dann werden sich viele andere fragen, von was hier die Rede ist. Außerdem machst du ja auch mehr als nur die Breite anzupassen.

Vielleicht benötigen wir hier aber auch gar keinen Config parameter. Vielleicht verzichten wir darauf. Aus meiner Sicht, deine Entscheidung, sofern @Ruko2010 keine anderen Vorstellungen hat.

**Comment by Ruko2010** [comment]
genehmigt 😉

**Comment by capoaira** [comment]
Ok, habe es auf dem Config entfernt.

 >Andererseits ist auch das hier etwas was nicht wirklich einen Mehrwert bringt.

Ob es ein Mehrwert ist, den ganzen Namen lesen zu können, darüber kann man streiten. Ich finde es so schöner. Aber letztendlich sind es auch nur 2 Zeilen CSS

**Comment by 2Abendsegler** [comment]
Ich finde es so auch schöner. Das ist aber nicht der Punkt.

Man hat zuvor den Namen doch schon gesehen, und weil man gesehen hat, dass es dieser Cache ist, entschließt man sich doch erst die rechte Maustaste zu wählen. Diese kurze Zeitspanne kann sich das doch jeder behalten, weißt du.

Es geht darum dass gegebenenfalls Wartungsarbeiten anfallen wenn Änderungen erfolgt sind. Ich weiß das, weil ich derjenige bin, der einmal im Jahr oder auch öfter versucht die gesamte Funktionalität durchzugehen um Fehlern auf die Spur zu kommen. Weil gemeldet werden sie ja nur in den wenigsten Fällen. Und es sind immer zahlreiche Fehler vorhanden. 

Das ist der Grund warum man lediglich Änderungen machen sollte die einen echten Mehrwert bringen.

**Comment by capoaira** [comment]
> Es geht darum dass gegebenenfalls Wartungsarbeiten anfallen wenn Änderungen erfolgt sind. Ich weiß das, weil ich derjenige bin, der einmal im Jahr oder auch öfter versucht die gesamte Funktionalität durchzugehen um Fehlern auf die Spur zu kommen. Weil gemeldet werden sie ja nur in den wenigsten Fällen. Und es sind immer zahlreiche Fehler vorhanden.

Ok, das kann ich nachvollziehen. Alles durchzusehen stelle ich mir sehr anstrengend vor.
Mein Respekt wie viel Zeit und Mühe du in dieses Projekt steckst. 👍

**Comment by 2Abendsegler** [comment]
Das ist aber jetzt kein Grund gemachte Änderungen zurückzunehmen. 

Es geht doch darum ein Verständnis zu entwickeln, welche Dinge wir brauchen und welche wir eigentlich nicht brauchen, unter anderem deshalb weil sie keinen oder kaum Mehrwert bringen, oder auch weil man sich damit einfach nicht wohlfühlt. 

Zum Beispiel deine Änderungen im Dashboard zu den Unveröffentlichen, das ist wirklich ein riesen Mehrwert. Das gesamt Gebiet zu den Unveröffentlichen wurde auch total vernachlässigt, von GS und auch durch uns. Das GS hier nun dazwischenfunkt, das ist bitter, aber die Abstimmungen und Korrekturen sind es wert, weil doch ein richtiger Mehrwert für die meisten User entstanden ist. 

Jetzt sei nicht bockig und lass die Änderungen drin.

**Comment by Ruko2010** [comment]
@2Abendsegler zum Thema Durchtesten will ich das hier mal in den Raum werfen: https://www.cypress.io/
Das ist ein Tool für automatisches Frontend-Testing. Eventuell wäre es eine Idee, das man sich mal näher damit befasst und ein paar Tests schreibt, so dass man das Testen dem Computer überlassen kann 😃.

**Comment by 2Abendsegler** [comment]
merged
