### ISSUE TITLE
Unpublished hides were shown in recently viewed list after an update from GS.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1220]
![Recently Viewed](https://user-images.githubusercontent.com/50927164/72283198-8f673780-363e-11ea-8960-96bf763b9321.png)
Seit heute werden die unveröffentlichte Caches auch in den Zuletzt aufgerufen angezeigt. Wenn man viele hat, kann es (wie bei mir) dazu kommen, dass alle anderen überdeckt werden, da sie für die Statusmeldung aufgerufen werden.
Ich werde wohl überlegen die Statusmeldung raus zu nehmen ~~oder sie einmal Täglich zu aktualisieren~~.
Eine andere Möglichkeit ist es, die unveröffentlichten Caches nicht in den Zuletzt aufgerufen anzuzeigen und die Daten hier raus zu nehmen: https://www.geocaching.com/my/recentlyviewedcaches.aspx
Was würdet ihr empfehlen?

Kleine liste für mich:
- [x] **Button zu laden der Statusmeldung**
- [x] Caches mit fadeIn/fadeOut ein- bzw ausblenden
- [x] Config Parameternamen an restliches Config anpassen.

**Comment by 2Abendsegler** [comment]
Ich verstehe das noch nicht ganz. Verursachen wir, dass die unveröffentlichten Caches in der recently viewed Liste angezeigt werden, oder macht das GS? Was ist es das du als Statusmeldung bezeichnest und was würde es bringen sie nur einmal täglich zu aktualisieren?

**Comment by capoaira** [comment]
Bei den recently viewed wurden bis heute keine unveröffentlichten Caches angezeigt.
Jedes mal wenn das Dashboard aufgerufen wird ruft das Script alle unveröffentlichten Caches auf um die Statusmeldung anzuzeigen, also ob z.B. schon ein Reviewer geantwortet hat.
Jetzt überlagern die unveröffentlichten Caches alle anderen recently viewed (siehe Screenshot), weil sie ja jedes mal aufgerufen werden, sobald das Dashboard geladen wird.
Wenn die Statusmeldungen nur einmal am Tag abgerufen werden, werden die Caches nicht so oft geladen. Aber ich denke, dass das auch nicht so vielen etwas bringt...

**Comment by Ruko2010** [comment]
Ich denke es bringt nichts, die nur einmal am Tag abzurufen, denn dann hast du sie ja trotzdem mindestens einmal am Tag in der Liste.
Die Frage ist, wie viele Recently viewed Caches GS bereit stellt. Sind es mehr als man sieht, dann könnte man die Unveröffentlichten einfach ausblenden und sieht wieder die normalen Caches. Ist es aber eine Fixe Anzahl, dann bringt auch das ausblenden nichts. Dann wirst du entweder damit leben müssen, oder die Statusmeldungen wieder raus nehmen.

**Comment by 2Abendsegler** [comment]
Ich seh das auch ähnlich wie Ruko2010.

Ich finde wir sollten keine Caches in der Recently viewed Caches Liste ausblenden. Und wir sollten auch keine im Dashboard ausblenden und andere dazubauen. Wenn du manuell den Status deiner Unveröffentlichten ansiehst, dann werden sie in dieser Liste auch erscheinen.

Man könnte sich vielleicht überlegen, ob man die Statusmeldungen nicht automatisch aufbaut wenn das Dashboard aufgerufen wird, sondern nur auf Wunsch des Users. Also beispielsweise den Kopf der Statusmeldungen darstellen und dort einen Button vorsehen mit dem die Statusmeldungen dann abgerufen werden. Gegebenenfalls sollte man das dann auch über den Config steuern.

Ansonsten fällt mir auch nichts ein. 
Man sollte damit leben. Und wenn man das nicht möchte, dann muss man auf die Statusmeldung verzichten und sie im Config abwählen.

**Comment by Ruko2010** [comment]
> Man könnte sich vielleicht überlegen, ob man die Statusmeldungen nicht automatisch aufbaut wenn das Dashboard aufgerufen wird, sondern nur auf Wunsch des Users.

Die Idee finde ich sehr gut.

**Comment by 2Abendsegler** [comment]
Gibt es nicht eine andere Stelle, wo man diese Informationen abgreifen kann? Steht das nur im unveröffentlichen Listing?
(Sorry, ich kenn mich mit Unveröffentlichten nicht aus.)

**Comment by Ruko2010** [comment]
Soweit ich weis nicht.

> (Sorry, ich kenn mich mit Unveröffentlichten nicht aus.)

Es wird mal Zeit das zu ändern 😉

**Comment by 2Abendsegler** [comment]
> Es wird mal Zeit das zu ändern 😉

Ja, stimmt ... irgendwie kommt immer was dazwischen.

**Comment by capoaira** [comment]
@2Abendsegler 
Ich habe gesehen, dass du den Prepare go live vorbereitest. Wann willst du die neue Version rausbringen? Ich würde gerne diesen Bug noch beheben. Mindestens den Status rausnehmen, damit man die Liste wieder anzeigen kann.
Am WE habe ich haber nicht viel Zeit und ob ich Abends noch Energie habe, weiß ich nicht.

**Comment by 2Abendsegler** [comment]
Die neue Version hat noch Zeit. 
Ich habe nur den PR aufgemacht damit man sehen kann dass deine neuen Parameter schon gepflegt sind.

Dein Bug und die Änderungen zum Compact Layout sollen da noch mit rein. Und vielleicht auch noch andere Dinge von Dir, da hab ich gerade keinen Überblick.
Und auch die Ergänzungen auf der neuen Karte von Ruko2010 sollen da noch rein.

Ich peil mal so den 24.01 für ne neue Version an, das ich heute in einer Woche.

**Comment by capoaira** [comment]
Ich hätte von Anfang an mit jQuery arbeiten sollen, das ist soviel einfacher und übersichtlicher...🤣

Das ganze sieht jetzt so aus:
![grafik](https://user-images.githubusercontent.com/50927164/72741033-1cfad800-3ba7-11ea-875f-bf2a3c9b92aa.png)

Beim klicken auf Load Status wird der Status geladen, und es sieht aus wie vorher.
Eigentlich wollte ich noch ein Dropdown machen um die Caches direkt im Dashboard sortieren zu können. Aber ich bekomme einfach kein Dropdown hin.

Ist das mit dem Link so ok?

**Comment by 2Abendsegler** [comment]
Ja, finde ich prima.
Rechts neben dem Icon wird dann der Status angezeigt, wie zuvor, oder?

> Aber ich bekomme einfach kein Dropdown hin.

Man muss ja auch nicht immer alles sofort 100 prozentig machen. Kannst ja irgendwann wenn du mal wieder Lust hast wieder dran gehen.

**Comment by capoaira** [comment]
>  Rechts neben dem Icon wird dann der Status angezeigt, wie zuvor, oder?

Jip

**Comment by Ruko2010** [comment]
> Aber ich bekomme einfach kein Dropdown hin.

ich weis nicht wo genau dein Problem liegt, aber schau mal in den Helper um Zeile 1004, dort erzeuge ich ein Dropdown mit folgendem Code:

```
var output_email = document.createElement("select");
output_email.setAttribute("id", "output_email_"+table_index);
output_email.appendChild(new Option("Primary", "1"));
output_email.appendChild(new Option("Secondary", "2"));
```

**Comment by capoaira** [comment]
> Das ganze sieht jetzt so aus:
> ![grafik](https://user-images.githubusercontent.com/50927164/72741033-1cfad800-3ba7-11ea-875f-bf2a3c9b92aa.png)
> 
> Beim klicken auf Load Status wird der Status geladen, und es sieht aus wie vorher.

Das gilt weiterhin.
Ehrlich gesagt hatte ich Schwierigkeiten, durch mein Coding vernünftig durchzusteigen. Deswegen habe ich nun jQuery genutzt, damit das ganze übersichtlicherer ist, als nur mit js.
Ich habe also (für die user) nichts geändert, außer den Button hinzugefügt. Dafür ist das überarbeiten des Codings einfacher geworden.

**Comment by 2Abendsegler** [comment]
merged
