### ISSUE TITLE
Show user profile for user with "+" in the name does not work.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1234]
**Describe the bug**

**To Reproduce**
1. Go to https://www.geocaching.com/seek/nearest.aspx?u=Willy%252bFrancina
2. Click on 
![grafik](https://user-images.githubusercontent.com/22332216/72677962-e71ffb80-3aa1-11ea-917f-6a80bab329a6.png)
3. See error
![grafik](https://user-images.githubusercontent.com/22332216/72677969-f606ae00-3aa1-11ea-9822-e73dcb687626.png)

**Comment by capoaira** [comment]
Komisch, bei mir funktioniert das ganz normal. 
Ich komme auf die Seite https://www.geocaching.com/p/default.aspx?u=Willy%2BFrancina und bei mir gibt es die auch:
![grafik](https://user-images.githubusercontent.com/50927164/72686169-faf34e00-3af1-11ea-9155-89d97dfc849a.png)

**Comment by capoaira** [comment]
Ups, ich hatte übersehen, dass du noch die alte Profil Page nutzt, sorry.
Es ist aber ein Fehler von GS:
Öffne das Profil mal mit folgendem Link: https://www.geocaching.com/p/default.aspx?u=Willy%252bFrancina (du musst vorher aber bei einem anderen User das Profil auf das neue Umstellen)
Dann klicke oben auf "back to the old page". Dann kommt der selbe Fehler. Es liegt also nicht am GClh sondern an GS...

**Comment by 2Abendsegler** [comment]
Danke für die Info.

Was ist denn die richtige Umsetzung eines plus Zeichens für die url. Wir setzen dafür `%2B`.

Wenn GS es falsch macht, dann sollten wir bemüht sein deren Fehler auszumerzen, sofern das möglich ist. Ich muss mir das morgen mal in Ruhe ansehen.

**Comment by 2Abendsegler** [comment]
@capoaira 
Du hast recht, ich lasse das. Es funktioniert weder die korrekte Umsetzung fürs Pluszeichen in %2B noch die von GS fehlerhaft Umsetzung in %252b. 

Close

**Comment by 2Abendsegler** [comment]
Ich hatte den Link ins Forum unterschlagen.
https://forums.geocaching.com/GC/index.php?/topic/354863-hiddenfound-by-co-on-cachepage-incorrect-with-special-characters-in-co-name/
