### ISSUE TITLE
Implement the newer GC logo in the page header.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1237]
Implement the newer GC logo in the page header.

![gclogo 02](https://user-images.githubusercontent.com/22332216/72733042-57f50f80-3b97-11ea-95e5-2b145b39a3ab.jpg)

**Comment by Ruko2010** [comment]
Wenn ich es richtig sehe, dann kann man das Logo reicht einfach ändern. Es geht doch nur darum, dass "Geocaching" weg zu schneiden, oder? Das kann man über die CSS Klasse ".logo" machen. Dort einfach folgendes Eintragen: "flex: 0 0 35px;"

**Comment by 2Abendsegler** [comment]
Hab jetzt erst deine Info gesehen, blöd. 🙁
Ja, das wäre vermutlich noch einfacher gewesen, wenn das mit dem Flex geht. Jetzt ist es in alter Manier drin und auch schon im collector. Das Icon ist auch schon im master.

**Comment by Ruko2010** [comment]
War nur eine Idee. Die alte Version ist auch ok 😉
