### ISSUE TITLE
GCLH is still runing ? was kann ich machen

### ISSUE THREAD

**Issue by bimbo67** [2Abendsegler/GClh#1243]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, Linux]
 - Browser: [e.g. firefox, chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by bimbo67** [comment]
The script "GC little helper II" is already running.
Please make sure that it runs only once.

Do you want to see tips on how this could happen 
and what you can do about i

das ist was ich immer habe .. aber nur ein mal GCLH installiert! was kann ich machen ??

**Comment by 2Abendsegler** [comment]
Hallo,
welche Script Manager hast du installiert? Tampermonkey und Greasemonkey? 
Wie lange nutzt du den _GC little helper II_ schon?
Wie lange kommt die Meldung schon?

**Comment by bimbo67** [comment]
Hallo

Ich benutze Tampermonkey und GCLH seit schon Jahren !!

 


Die Meldung habe ich seit ich die letze version v0.10.3 installiert habe.


 

 

De : 2Abendsegler <notifications@github.com> 
Envoyé : mercredi 22 janvier 2020 13:14
À : 2Abendsegler/GClh <GClh@noreply.github.com>
Cc : bimbo67 <bimbocaching@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [2Abendsegler/GClh] GCLH is still runing ? was kann ich machen (#1243)

 

Hallo,
welche Script Manager hast du installiert? Tampermonkey und Greasemonkey?
Wie lange nutzt du den GC little helper II schon?
Wie lange kommt die Meldung schon?

**Comment by 2Abendsegler** [comment]
Hast du auch den Script Manager Greasemonkey installiert?

**Comment by bimbo67** [comment]
Nein diesen habe ich schon lange nicht mehr !

 

De : 2Abendsegler <notifications@github.com> 
Envoyé : mercredi 22 janvier 2020 20:04
À : 2Abendsegler/GClh <GClh@noreply.github.com>
Cc : bimbo67 <bimbocaching@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [2Abendsegler/GClh] GCLH is still runing ? was kann ich machen (#1243)

 

Hast du auch den Script Manager Greasemonkey installiert?

**Comment by bimbo67** [comment]
Es tut mir richtig leid !!! Graysemonkey war noch installiert !!!  tut mir echt leid !!!

 

Nochmals vielen dank für deine hilfe … 

 

Bénédict aus Strasbourg in Frankreich .

 

De : 2Abendsegler <notifications@github.com> 
Envoyé : mercredi 22 janvier 2020 20:04
À : 2Abendsegler/GClh <GClh@noreply.github.com>
Cc : bimbo67 <bimbocaching@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [2Abendsegler/GClh] GCLH is still runing ? was kann ich machen (#1243)

 

Hast du auch den Script Manager Greasemonkey installiert?

**Comment by 2Abendsegler** [comment]
Schön dass wir das Problem gefunden haben. 
Au revoir et bonne soirée.
Frank
