### ISSUE TITLE
GClh nach jedem Browserstart neu installieren

### ISSUE THREAD

**Issue by Mezzek4711** [2Abendsegler/GClh#1244]
Hallo!

Ich habe das problem, dass ich jedesmal wenn ich den Browser zu und wieder auf mache GClh neu installieren muß, weil er einfach nicht mehr da ist. Woran kann das liegen. Vielleicht hängt das auch mit dem Problem zusammen, dass auch AdBocker Plus sich seine einstellungen nicht merkt.

Rainer

**Comment by Ruko2010** [comment]
Hallo @Mezzek4711 bist du vielleicht im PrivateMode? Oder darf dein Browser keine lokalen Daten speichern?
Ist Tampermonkey auch verschwunden, oder nur GClh? Wie sieht es mit anderen Scripten bei Tampermonkey aus? Sind diese auch weg?

**Comment by Mezzek4711** [comment]
Hi!

Also ich glaube nicht dass ich private mode bin, aber wie kann ich das überprüfen? GClitte Helper ist das einzige script das ich verwende. 
Nein Tampermonkey ist immer da und auch meine anderen Addons wie Ghostery oder adblocker, der sich aber wie gesagt auch die Einstellungen nicht merkt.

**Comment by 2Abendsegler** [comment]
Du arbeitest mit Firefox, oder?

**Comment by Mezzek4711** [comment]
Ja 71.0 zur Zeit, ab es aber auch schon mit 72 probiert

**Comment by 2Abendsegler** [comment]
Leider kommt es bei Firefox immer mal wieder zu Problemen, weil das Firefox Profil demoliert ist. Es hört sich ganz danach an, dass es bei dir auch so sein könnte.

Vielleicht schaust du dir mal die folgenden Beiträge im Link an. Dort geht es darum das Profil wieder gerade zu biegen bzw. ein neues zu generieren. Bisher haben diese Informationen immer geholfen. Quäl dich mal da durch ... 
https://forums.geocaching.com/GC/index.php?/topic/343005-gc-little-helper-ii/&page=4&tab=comments#comment-5771435

**Comment by Mezzek4711** [comment]
Danke werde ich machen

**Comment by 2Abendsegler** [comment]
Konntest du das Problem lösen?

**Comment by 2Abendsegler** [comment]
Close
(user response missing 15 days)
