### ISSUE TITLE
Search Map output of "undefined" behind the favorite points. 

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1268]
Search Map output of "undefined" behind the favorite points. 

Der Fehler tritt bei unterschiedlichen Caches auf. Ich kann ihn aber nicht direkt reproduzieren, weil er nicht immer kommt. Wenn ich lang genug schnell rumklicke dann kommt er irgendwann.
Konsole zeigt nichts an.

**To Reproduce**
1. Go to https://www.geocaching.com/play/map/?lat=49.8716275570999&lng=8.41827392578125&zoom=11&asc=true&sort=distance

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/22332216/74405761-31409680-4e2e-11ea-9010-46788ab3b2bd.JPG)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: FF
 - Version: 72.0.2 (64-Bit)

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Kannst Du Dir das bitte mal ansehen?
Kann es sein, dass das ein Fehler von uns ist oder kommt das von GS?

**Comment by Ruko2010** [comment]
Ich kann es leider nicht nachstellen. Ist das bei allen caches auf der Seite?
![image](https://user-images.githubusercontent.com/2239440/74412770-753b9780-4e3e-11ea-87bf-fa358485499f.png)

**Comment by 2Abendsegler** [comment]
Nein, nicht bei allen. Ich kann auch keine bestimmten Caches ausmachen. Es kommt nur selten. Scheinbar immer dann wenn man im Tumult der Caches schnell zahlreiche Caches anwählt.

Überleg dir mal wo es herkommen könnte. Ich habe nichts gefunden.

**Comment by Ruko2010** [comment]
Ahh, das klingt doch mal nach eine Fehlerbeschreibung 😉. Damit konnte ich es nun auch nachstellen. Bei mir kommt der Fehler nur, wenn ich richtig schnell zwischen den caches wechsel. Ich hab so eine Ahnung und schau es mir an.

**Comment by Ruko2010** [comment]
> Wenn ich lang genug schnell rumklicke dann kommt er irgendwann

Asche auf mein Haupt, das hattest du ja schon geschrieben...Das hab ich wohl überlesen (hatte heute ne Nachtschicht und musste einen Server umziehen)

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Stop, den Fehler hab ich schon.

**Comment by 2Abendsegler** [comment]
```
	<li>
		<strong>Fix:</strong> Search Map output of "undefined" behind the favorite points. [<a href="https://github.com/2Abendsegler/GClh/issues/1268" title="Issue 1268">1268</a> / <a href="https://www.geocaching.com/profile/?u=2Abendsegler" title="Thanks to 2Abendsegler">2Abendsegler</a> / <a href="https://www.geocaching.com/profile/?u=Ruko2010" title="Thanks to Ruko2010">Ruko2010</a>]<br><br>
	</li>
```

**Comment by Ruko2010** [comment]
Alles gut, ich hätte eh erst heute Abend angefangen 😃. aber gut, dass du aufpasst...
