### ISSUE TITLE
Empty VIP-list

### ISSUE THREAD

**Issue by simply89** [2Abendsegler/GClh#1269]
Since a month or so, my VIP-list is empty. 
My settings are OK, everything regarding he VIP-list is enabled.

How can I solve this?

![image](https://user-images.githubusercontent.com/61022337/74459572-d3429c00-4e8b-11ea-8e7f-9ba80d254f66.png)

**Comment by 2Abendsegler** [comment]
Hi,
I see there is running another script - white question mark in blue background. Can you please deactivate it and test it again?
Which browser and operating system do you use?
Which GClh version do you use?

**Comment by simply89** [comment]
I had another script running.
I disabled it, but the VIP-list is still empty.

I'm using Chrome on Windows 10, and the latest version of GClh, version 0.10.4

I'm using Tampermonkey with the GClh script, I saw there is a Chrome plugin available.
I tried this earlier today, but the problem still exists.

**Comment by 2Abendsegler** [comment]
I can not reproduce it in the moment.

Please try the following:

1. What do you mean with Chrome plugin? Have you installed perhaps also the old "GC little helper", without the "II" in the end of the name? I think this should be an add-on. Please deinstall it, it does not run correct.

2. Can you please deactivate all scripts and also all add-ons. Let only GClh script running.

3. Have you perhaps installed Greasemonkey as additional script manager beside Tampermonkey? If here is also a GClh installed, please deinstall it, it does not run correct.

**Comment by ChiefController** [comment]
I had a similar problem. After some investigation I found out that it was caused by the Adblocker (here: uBlock Origin) which denied access to cookiebot.com. Without access, GClh was not able to load the logs.

**Comment by 2Abendsegler** [comment]
Thank you for your comment.

I also use the uBlock Origin. But my logs and the VIP lists are loaded. What exactly did you type in My Filters in uBlock Origin?

**Comment by ChiefController** [comment]
There were three lists which included cookiebot: AdGuard Annoyances, EasyList Cookie and Fanboy’s Annoyance.

**Comment by 2Abendsegler** [comment]
> 
> 
> There were three lists which included cookiebot: AdGuard Annoyances, EasyList Cookie and Fanboy’s Annoyance.

That is probably the reason, why nothing works anymore. More doesn't always help. Why is cookiebot.com entered in these three programs? If you have entered cookiebot.com in uBlock Origin, then that's enough because it is blocked. 

Please deactivate the three programs or deactivate the cookiebot.com entries in the three programs and let only run uBlock Origin and the GClh ... you will see everything works ...
Please try it!

**Comment by simply89** [comment]
> I can not reproduce it in the moment.
> 
> Please try the following:
> 
> 1. What do you mean with Chrome plugin? Have you installed perhaps also the old "GC little helper", without the "II" in the end of the name? I think this should be an add-on. Please deinstall it, it does not run correct.
Yes, that was what I ment. The add-on is uninstalled.
> 2. Can you please deactivate all scripts and also all add-ons. Let only GClh script running.
Done that, but still no VIP-list..
> 3. Have you perhaps installed Greasemonkey as additional script manager beside Tampermonkey? If here is also a GClh installed, please deinstall it, it does not run correct.
No, I'm only using Tampermonkey with GClh script.

**Comment by 2Abendsegler** [comment]
@simply89 
I'm slowly running out of ideas.

Please answer some questions again:

4. The logs in the cache listing look fine and also have VIP icons, right?
5. The VIPs are missing in several cache listings, not only in one, right?
6. There is probably a list of VIPs in the lower left corner of the newer dashboard. Looks the list ok, all VIPs are included, or missing some?
7. Go to the cache listing again and simultaneously press the Ctrl, the Shift and the k keys. The console should open. If something is red here, please make a screenshot.

**Comment by simply89** [comment]
Meanwhile, I reinstalled Tampermonkey and GClh and now everything works again as it just to be.
I don't know what I did wrong, but I'm happy now...

To answer your questions:
4: Yes, all the logs were fine (I disabled the option for VIP-buttons behind the nickname).
5: They where missing in all caches.
6: I thought this was OK, but i'm not 100% sure.
7: This doesn't work in Chrome.

**Comment by 2Abendsegler** [comment]
Thank you for the feedback. That's dubious. I think Gremlins were at work there. 😄
Nice that it works again.

I will leave the issue open for a day or two. Maybe ChiefController is still responding.

Nice weekend.

**Comment by ChiefController** [comment]
As I wrote: Disabling these lists (and therefore not blocking cookiebot at all) worked for me.

**Comment by 2Abendsegler** [comment]
Ok, thank you for your feedback.

Nice weekend.
