### ISSUE TITLE
Sync mit Google Drive

### ISSUE THREAD

**Issue by MarkusKn** [2Abendsegler/GClh#1289]
Es wäre super, wenn zusätzlich zum Sync per Dropbox noch eine Möglichkeit zum Sync per Google Drive gegeben wäre. Ist dies umsetzbar?

**Comment by 2Abendsegler** [comment]
Das ist möglich, wenn auch sicherlich etwas Aufwand. Die Frage ist aber auch, für wie viele Personen wir so etwas einrichten und ob es nicht eine Lösung gibt, die nicht abhängig von Anbietern von Cloud Diensten ist.

Vielleicht kannst du hier mal mit deinen Erfahrungen aushelfen. Du nutzt sicherlich Google Drive bereits für andere Zwecke, beispielsweise für Daten auf deinem Rechner zu sichern. Wie kommen die Daten dann von deinem Rechner auf Google Drive?

**Comment by 2Abendsegler** [comment]
@MarkusKn 
Vielleicht kannst du hier mal mit deinen Erfahrungen aushelfen. Du nutzt sicherlich Google Drive bereits für andere Zwecke, beispielsweise für Daten auf deinem Rechner zu sichern. Wie kommen die Daten dann von deinem Rechner auf Google Drive?

**Comment by MarkusKn** [comment]
An sich arbeite ich direkt im WebFrontEnd von GoogleDrive ([https://drive.google.com/drive/my-drive](https://drive.google.com/drive/my-drive))
Vorstellen würde ich mir, dass entweder der Login aus meinem Google Chrome direkt per SingleSignOn (SSO) durchgeschliffen wird, oder, um auch mit anderen Browsern kompatibel zu sein, es eine Login Möglichkeit im Script selber gibt.

Derzeit "synche" ich manuell, was eher mühselig ist über das Textfeld. Wenn der GoogleDrive Sync nicht klappt, kann man nicht einen Synch direkt als Textfile einbringen? Sync anklicken, es öffnet sich (bei Windows) der Datei Explorer und ich kann meine Einstellungen direkt speichern. Beim Import genauso.

**Comment by Ruko2010** [comment]
Also als ich damals Dropbox angebunden habe, war das schon ein ganz schöner Aufwand. Hier sieht es ähnlich aus. Ich denke es sollte möglich sein, aber ich weis nicht ob ich aktuell die Zeit dazu finde. Hier gibt es ein Tutorial, von dem man sich sicher einiges abschauen kann:
https://bytutorial.com/tutorials/google-api/introduction-to-google-drive-api-using-javascript

@MarkusKn was spricht denn für dich gegen den Sync mit Dropbox?

**Comment by MarkusKn** [comment]
@Ruko2010 an sich spricht dagegen, dass Dropbox eine geringere Speichermenge zur Verfügung stellt als Google Drive. Daher habe ich alles von Dropbox zu Google Drive migriert.

Wenn der Aufwand zu hoch ist, dann lasst es dabei. Wäre es denn möglich, dass für den manuellen Sync der Datei Explorer aufgeht, ich mir einen Ordner aussuche und dort eine TXT abgespeichert wird?

**Comment by Ruko2010** [comment]
Der Download der aktuellen Konfig als txt datei sollte kein Problem sein. Ich bastel mal was und sende dann einen Link zur Testversion

**Comment by Ruko2010** [comment]
Ich hab dazu ein neues Issue aufgemacht, da es ja mit dem hier nichts zu tun hat: https://github.com/2Abendsegler/GClh/issues/1312
