### ISSUE TITLE
The alignment of the new logging form is not correct

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1290]
**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/74682413-44ed5380-51c6-11ea-9949-b1648fd487d3.png)

**Desktop:**
 - OS: Windows
 - Browser: firefox, chrome

**Additional context:**
Das Datum überdeckt die log templates. Ich weiß, dass es nach dem Update funktioniert hat. Ich habe zum überprüfen auch die aktuelle Version 0.10.4 ohne die neuen Änderungen getestet.

**Comment by 2Abendsegler** [comment]
Bei mir sieht es gerade so aus:
![grafik](https://user-images.githubusercontent.com/22332216/74685685-8cc4a880-51cf-11ea-93a4-9b5b06256dcf.png)

**Comment by 2Abendsegler** [comment]
Bei mir sieht es mit 0.10.4 ja ok aus.
![grafik](https://user-images.githubusercontent.com/22332216/74685926-3efc7000-51d0-11ea-8c35-8fd441f1d67f.png)

@capoaira 
Kannst du mal nochmal checken ob du andere Scripte bzw. Add-ons am laufen hast? Versuch bitte gegebenenfalls rauszufinden wo vielleicht ein Konflikt ist. Dann schau ich es mir an.

**Comment by capoaira** [comment]
Ich habe alle Scripte und Add ons deaktiviert. Es sieht immer noch so aus...

Hier meine Einstellungen:
![grafik](https://user-images.githubusercontent.com/50927164/74686497-f9d93d80-51d1-11ea-8d62-cb640ba4ab59.png)

**Comment by 2Abendsegler** [comment]
Danke.
Kannst du bitte nochmal was prüfen?
Schau mal ob das auch bei fremden Caches so ist bei einem Found it anstatt Owner Maintenance.

**Comment by capoaira** [comment]
Ja, auch bei Found und Attend ist das bei mir so.

**Comment by Ruko2010** [comment]
Bei mir sieht es auch gut aus:
![image](https://user-images.githubusercontent.com/2239440/74712483-b2c96780-5226-11ea-8cab-13523bc709b8.png)

@capoaira  hast du eventuell eine Logvorlage mit langem Namen?

**Comment by capoaira** [comment]
Ja, aber daran scheint es nicht zu liegen. Ich habe das komplette Script gelöscht und neu installiert. Es war immer noch falsch ausgerichtet...

**Comment by capoaira** [comment]
Habe auch nochmal versucht, alle Cookies und Tracker zu entfernen. Auch ohne Erfolg. Habe auch nochmal cookiebot an gemacht, aber auch das hat nicht geholfen.

**Comment by 2Abendsegler** [comment]
Ruko2010 hat recht, war mir noch gar nicht aufgefallen. Bei dir scheint das Feld "- Log Templates -" etwas verlängert, weshalb die Smileys auch nicht mehr am rechten Rand ausgerichtet sind. Wollte das nur nochmal in der Vordergrund rücken.

**Comment by 2Abendsegler** [comment]
Off-Topic:
- [ ] To do: Log Templates in Breite begrenzen, so dass Größe des Feldes nicht mehr verändert wird, Smileys am rechten Rand ausgerichtet bleiben und das Datum nicht mehr nach links wandert.
![grafik](https://user-images.githubusercontent.com/22332216/74718401-6e43c900-5232-11ea-9769-719628ede725.png)

**Comment by 2Abendsegler** [comment]
Wenn ich im Firefox den Zoom auf "Nur Text zoomen" einstelle
![grafik](https://user-images.githubusercontent.com/22332216/74720278-d0ea9400-5235-11ea-835f-cd637f1ecde4.png)

und den Zoom auf 80 reduziere, dann sieht das so aus.
![grafik](https://user-images.githubusercontent.com/22332216/74720367-f8d9f780-5235-11ea-8e39-63c0d982a08b.png)

**Comment by capoaira** [comment]
Interessant. Wenn ich rein oder raus Zoome, sieht es fast so aus wie es soll, überdeckt aber leicht den Logtype:
![2020-02-18](https://user-images.githubusercontent.com/50927164/74769775-4d5b9200-528b-11ea-9006-e5a8c94a15f7.png)

**Comment by 2Abendsegler** [comment]
@capoaira 
Moin,
kannst du bitte mal meine Änderungen testen. [Hier](https://github.com/2Abendsegler/GClh/raw/b2c16bedccaa35ec8b05dfc0c93dc29504f263eb/gc_little_helper_II.user.js) geht es zum Script.

**Comment by capoaira** [comment]
Sieht gut aus. Danke!

**Comment by 2Abendsegler** [comment]
Hast du auch mit einem eigenen Cache getestet, also so wie in deinem ersten Beispiel?

**Comment by capoaira** [comment]
Jip, funktioniert auch bei eigenen und Events

**Comment by 2Abendsegler** [comment]
Ok.
Dann übernehmen wir es so.

**Comment by 2Abendsegler** [comment]
<li>
	<strong>Fix:</strong> The alignment of the new logging form is not correct. [<a href="https://github.com/2Abendsegler/GClh/issues/1290" title="Issue 1290">1290</a> / <a href="https://www.geocaching.com/profile/?u=2Abendsegler" title="Thanks to 2Abendsegler">2Abendsegler</a>]<br>
</li>
