### ISSUE TITLE
Convert TB autovisit feature of old log form to asynchronous, and integrate new log form.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1301]
- [ ] Convert the TB autovisit feature of the old log form to asynchronous.
- [ ] Try to integrate the new log form. 
- [ ] Note add on uBlock Origin.
 
Optional:
- [ ] Config parameter to delete old autovisit entries as soon as the trackables are deleted from inventory or maybe a month later.
- [ ] Also provide the tracking code in the trackables log form.

**Comment by 2Abendsegler** [comment]
#1288

**Comment by capoaira** [comment]
Ich sehe gerade, dass du dein assignment entfernt hast. Darf ich mich hierdran versuchen?

**Comment by 2Abendsegler** [comment]
Klar, kannst du gerne machen.

**Comment by capoaira** [comment]
> Convert the TB autovisit feature of the old log form to asynchronous.

Was ist hiermit gemeint? Bei mir klappt es mit und ohne cookiebot auf der alten Seite.

**Comment by 2Abendsegler** [comment]
Es funktioniert nicht immer bzw. nicht bei jedem. Das liegt so weit ich mich erinnere an asynchronem Laden.

**Comment by capoaira** [comment]
Ok, ich habe mir die Bescheibung in #1288 angeschaut. Evt. frage ich dort nochmal nach, weil ich den Fehler nicht repruduzieren kann.
