### ISSUE TITLE
[New Map] Port hide found/own caches, cache types and sidebar to searchmap (set filter on map load).

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#1304]
We implemented this feature for the old browsemap, we need to port it to the new searchmap.

When the map is loaded, all Filter set in the config should be applied
![image](https://user-images.githubusercontent.com/2239440/76288113-45997700-62a6-11ea-8853-1dec3d277936.png)

**Comment by Ruko2010** [comment]
Wir könnten einfach einen Link einfügen, der die gleiche URL wie aktuell aufruft, nur mit `?hf=1` bzw. `&hf=1` hinten dran. So ruf ich die Karte aus meinen Lesezeichen auf. Was anderes macht der Filter auch nicht.

**Comment by 2Abendsegler** [comment]
Gute Idee, und ziemlich einfach!

**Comment by Ruko2010** [comment]
Das einzige was da schief gehen könnte wäre, dass aktuell gesetzte Filter gelöscht werden. Aber ich glaube GS bildet alle Filter über die URL ab, das heißt es müsste klappen.

**Comment by 2Abendsegler** [comment]
Vielleicht könnte man auch sehen welche der anderen Einstellungen aus "Hide map elements" genauso übernommen werden können.

**Comment by Ruko2010** [comment]
Auf deinen Kommentar hin habe ich mir das ganze nochmal angeschaut. An sich bauen wir hier ein Feature, dass GS schon selbst implementiert hat, und das nur einen Klick (auf Filter) entfernt ist. So betrachtet finde ich das nicht sinnvoll.
Im Nachgang betrachtet ging es dem User auch nicht darum einen link zu haben, sondern das wenn man die Karte lädt, dass dann die eigenen Caches ausgeblendet werden sollen, wenn die entsprechende Option im Config gesetzt ist.
![image](https://user-images.githubusercontent.com/2239440/76287995-00754500-62a6-11ea-981c-644c33382b73.png)
Da habe ich wohl bei der Erstellung des Tickets etwas geschludert und mir ist das jetzt erst klar geworden.
Es geht also nicht um zusätzliche Links, sondern um die Filter, die beim ersten Laden der Karte gesetzt sein sollen.

**Comment by Ruko2010** [comment]
Ich hab mich gerade hier dran versucht, aber es klappt nichts. Ich wollte die Filter einfach setzen, aber die Controls für die Filter sind noch nicht da wenn man nicht auf "Filter" geklickt hat. Leider bin ich irgendwie ratlos...

**Comment by 2Abendsegler** [comment]
Nachdem die Seite geladen ist habe ich die Internetverbindung getrennt. Trotzdem kann ich den Button Filter anwählen und Filtereinstellungen vornehmen. Lediglich der Button Done führt die Änderungen nicht mehr durch.
Vielleicht sind die Filtereinstellungen also schon vorhanden, nur noch nicht an der richtigen Stelle.

Hilft das?
Du bist technisch viel versierter, magst du es nochmal versuchen bevor ich mit meinen Fuppes Kenntnissen dran gehe? 😂

**Comment by Ruko2010** [comment]
Ich glaube der Filter wird durch ein Javascript erst aufgebaut. Dafür braucht es natürlich kein Internet. Die Idee war gut, aber ich glaube das hilft mir nicht, leider.

**Comment by 2Abendsegler** [comment]
Kann man nicht das Javascript von GS dass den Filter aufbaut ausfindig machen und ausführen? An anderer Stelle wie beispielsweise der Ermittlung der Favoritenprozente machen wir das doch auch. Nur mal laut gedacht.

**Comment by 2Abendsegler** [comment]
Additional issue to this topic. #1369

**Comment by DieBatzen** [comment]
Für das Setzen der Filter aus der Konfig kann ich eine Lösung anbieten:
Die Filter lassen sich per Programm-Klick setzen, ohne dass die URL geändert oder die Seite neu geladen werden muss.
- Filter öffnen: `$('.filter-toggle').click();`
- Filter setzen (z.B. Gefundene ausblenden): `$('input[name="hideFinds"][value="1"]').click();`
- Filter anwenden: `$('.control-apply').click();`

Das schöne dabei ist, dass alles im Hintergrund abläuft, ohne dass sich der Filter oder die Sidebar öffnet.

Dabei gibt es, wie könnte es bei GS-Code auch anders sein, einige Besonderheiten:
1. Wartezeit, bis die Sidebar geladen ist --> das wird im Code mit einem MutationObserver glücklicherweise schon erledigt
2. Jeder zu setzende Filter muss nicht nur einmal, sondern zweimal direkt nacheinander geklickt werden, sonst werden einige Filter gesetzt, andere aber nicht. Ursache ist vielleicht ein Timingproblem, jedenfalls hat ein `setTimeout(...)` um jeden Filterklick das Problem auch gelöst.
Ist aber sehr unschön und die Wartezeit vergrößert sich mit jedem zu setzenden Filter.
Da ist der Doppelklick `$('input[name="hideFinds"][value="1"]').click().click();` eleganter und robuster ... und funktioniert.
3. Jeder gesetzte Filter bleibt nach einem Neuladen der Seite erhalten. Das heißt für die Konfig-Filter, dass sie nur einmalig, beim ersten Aufruf der Seite, gesetzt werden dürfen.
Damit werden auch keine gesetzten Filter des Anwenders überschrieben.

Einige Filter sind auf der neuen Karte nicht verfügbar (spielte für die Umsetzung keine Rolle, nur der Vollständigkeit halber):
- Hide header by default
- Hide DNF smileys by default
- Mega/Giga Events (es gibt nur einen einzelnen Eventfilter, der alle Events abdeckt)

Ich habe das mal in die aktuelle Collector-Version eingebaut, hier ein Downloadlink auf die Datei:
[https://www.dropbox.com/s/vya5kvggopmoitg/gc_little_helper_II.user.js?dl=1](https://www.dropbox.com/s/vya5kvggopmoitg/gc_little_helper_II.user.js?dl=1)


Wenn ihr Muße habt, könnt ihr euch das ja mal anschauen und testen.

Gruß,
Thomas

**Comment by capoaira** [comment]
Ich habe es gerade mal ausprobiert und es funktioniert bei mir ohne Probleme.
Ich denke du kannst einfach ein PR erstellen und @2Abendsegler merged es dann.

**Comment by DieBatzen** [comment]
OK, PR ist raus.

**Comment by 2Abendsegler** [comment]
Wie geil. Daran haben wir uns schon ganz schön die Zähne ausgebissen. Danke!
Ich bin unterwegs und habe gerade keine Zeit zu mergen. Ich machs ende nächster Woche.
Schönes WE

**Comment by 2Abendsegler** [comment]
Super Arbeit, danke nochmal Thomas!

---

To do 2Abendsegler im Prepare go live v0.10.8:

- [ ]  Im config dokumentieren/anzeigen welche Punkte nur auf der alten Karte funktionieren bzw. auf der neuen Karte mehr machen als gedacht. Am Besten über Hilfstexte, also die ?:
- Hide header by default
- Hide DNF smileys by default
- Mega/Giga/Cito Events (es gibt nur einen einzelnen Eventfilter, der alle Events abdeckt.)
- Events (alle Events)
- Homezone circles (das auch gleich mitmachen)
- Layers in map (das auch gleich mitmachen)
- [ ]  Auch im Changelog sollten diese Dinge Erwähnung finden.
- [ ]  Tabs ersetzen

**Comment by 2Abendsegler** [comment]
- [ ] Die Filter dürfen auch dann nicht gesetzt werden, wenn es sich bei der Karte um eine Bookmarkliste handelt. (Ich bin dran.)
