### ISSUE TITLE
Coords related functions does not work on unpublished caches.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1305]
**Describe the bug**
All function they are related to the Coords (Link to Flopps, openrouter, Copydata) does not work on unpublished hides. Also "Map this Location" is located at an other place and the elevation is not shown

**To Reproduce**
1. Go to a unpublish cache
2. See error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/75262494-e7bc5800-57ec-11ea-9fdc-6bff69d54e37.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox

**Additional context**
Ich habe das ganze mit und ohne uBlock getestet. Der Fehler bleibt. Der einzige was mir aufgefallen ist, ist dass es bei unpublished Caches keine Möglichkeit zum ändern der Koords gibt und es deswegen den span block `<span class="edit-cache-coordinates" id="uxLatLonLink" data-hasqtip="2">`  nicht gibt. 
Ich gucke mir das heute Abend nochmal genauer an.

**Comment by 2Abendsegler** [comment]
Aus meinem Verständnis heraus waren diese Features bei den Unveröffentlichen nie vorgesehen. Ich habe das immer als temporären Zustand betrachtet, in dem nur das wiedergegeben werden muss was der Normaluser (ohne den GClh) sieht. Entsprechend hätten wir eigentlich vieles explizit für die Unveröffentlichen herausnehmen müssen. Mir war die Sichtweise immer recht lieb, weil es mitunter schwierig sein kann ein Testbeispiel zu erschaffen wenn dort etwas nicht funktioniert.
 
Wenn wir anfangen die komplette Funktionalität bereits hier anzubieten, dann könnte das durchaus noch mehr Aufwand sein. Beispielsweise funktionieren die Karten Features aus der rechten Sidebar und das Clipboard meines Wissens auch nicht oder nicht korrekt. Womöglich laufen sogar irgendwelche Dinge gegen die Wand.

Ich will damit nicht sagen dass wir es nicht machen sollen, ich sehe nur die Priorität total gering und sehe mich auch eher nicht aktiv mitwirkend in diesem Gebiet. Ich würde also ungern Aufwand bei mir produzieren zum Testen oder gar zum Entwickeln.

@Ruko2010: Was meinst du?

**Comment by capoaira** [comment]
Soweit ich das beurteilen kann, funktionieren nur die Funktionen nicht, die `#uxLatLonLink` nutzen. Da es diese id bei unpublished Caches nicht gibt.
Wenn ich mehrere Caches in einer Gegend verstecken wollte, habe ich aber oft die Koords kopiert und bei Flopps eingefügt um eine Übersicht zu haben. Da wäre die Copy Funktion hilfreich.

Wenn es zu viel Aufwand ist, würde ich es wahrscheinlich auch lassen.

**Comment by Ruko2010** [comment]
Ich habe die Funktionen bei meinen unveröffentlichten Caches nie gebraucht. Ich sehe das daher wie 2Abendsegler. Ich kann mir die Sache gern mal anschauen und abschätzen wie viel Aufwand es ist. Vielleicht ist es ja nur eine Kleinigkeit die wir ändern müssen. 
@capoaira welche Funktionen brauchst du denn im speziellen? Nur die Copy Funktion der Koordinaten?

**Comment by capoaira** [comment]
Ja, die Copy Funktion wäre schön. Wenn es aber zu viel Aufwand ist, ist es nicht so schlimm.

**Comment by jakedot** [comment]
Der unveröffentlichte Cache hat statt #uxLatLonLink ein #uxLatLon. Ich verstehe nicht ganz warum nicht das genommen wird, denn das ist auch bei den veröffentlichten vorhanden (im #uxLatLonLink enthalten) und es sind immer die richtigen Koordinaten enthalten.

**Comment by 2Abendsegler** [comment]
Danke für die Info. Wir schauen uns das mal an.

**Comment by Ruko2010** [comment]
Ich hab das ganze schon angefangen, bin aber noch nicht weiter. Danke für den Hinweis @jakedot , aber da die Koordinaten ein zentraler Bestandteil sind, müssen wir schauen, dass nichts kaputt geht, wenn wir das nun ändern.

**Comment by jakedot** [comment]
Das ist natürlich klar, danke für die Rückmeldung!

**Comment by Ruko2010** [comment]
Ich habe die Sidebar- und Copy Funktionen wiederhergestellt. Sie klappen nun auch auf Seiten von unpublished Caches.
Da @2Abendsegler keine eigenen Caches hat, könnten vielleicht @capoaira und @jakedot mal durchtesten?

Mit diesem Link könnt ihr die Version testen:
[Neue Version zum testen](https://github.com/Ruko2010/GClh/raw/issue/1305-unpublished_caches_sidebar_functions/gc_little_helper_II.user.js)

und mit diesem kommt ihr wieder zurück auf die aktuelle stabile Version:
[Zurück zur aktuellen Version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js)

**Comment by jakedot** [comment]
die Copy-Funktion macht was der zweite Teil ihres Namens andeutet: Funktionieren! sidebar sind die Funktionen wie Flopp's Mal usw? das sieht auch ok aus.

Danke für deine Arbeit! Ich werde mich beim Whereyougo-Player revanchieren ;)

**Comment by capoaira** [comment]
Danke für die Arbeit. Der div mit der id `unpublishedMessage` ist aber nicht bei jedem unveröffentlichtem Cache.
Hier ein Auszug aus meiner Statusmeldung im Dashboard: #1242
```javascript
switch ($(text).find('#divContentMain div')[0].id) {
	case 'unpublishedMessage': html += '<b>Status:</b> <em>Disabled</em>'; break;
	case 'unpublishedReviewerNoteMessage': html += '<b>Status:</b> <em>Your reviewer has responded</em>'; break;
	case 'unpublishedEnabledMessage': html += '<b>Status:</b> <em>Waiting for review</em>'; break;
	case 'ctl00_ContentBody_lockedMessage': html += '<b>Status:</b> <em>Ready to publish</em>'; break;
	default: gclh_error('Show status for', name.href.substring(19, 26));
}
```
Bei denen mit `#unpublishedMessage` funktioniert es super. Der c2c Button direkt neben den Koords wird mir gar nicht angezeigt. Die Sidebar funktioniert aber super.

**Comment by jakedot** [comment]
komisch, bei meinen unpublished caches geht das mit dem button. kommts vielleicht aufs alter des listings an, dass sie da mal was geändert haben oder so??

**Comment by Ruko2010** [comment]
Danke @capoaira ich wusste nicht das es da unterschiedliche messages gibt. Aber dein switch führt ja alle auf. Ich werd das noch ändern. Ist ja zum Glück alles in einer Funktion 😃

**Comment by Ruko2010** [comment]
> komisch, bei meinen unpublished caches geht das mit dem button. kommts vielleicht aufs alter des listings an, dass sie da mal was geändert haben oder so??

Nein, das liegt daran wie die Message über dem Cache aussieht. Wenn der Rewiever schon geantwortet hat ist es zum Beispiel eine andere Nachricht als wenn man das Listing grad erst angelegt hat.

**Comment by jakedot** [comment]
aha, ja da haben sie eh noch was broken in dem flow. Wenn man da oben "antwortet" wird man gezwungen 2 reviewer notes zu loggen anstatt nur einer, plus dem koordinaten log...

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Ist der PR schon zum mergen oder musst du noch was ändern?

**Comment by Ruko2010** [comment]
Muss noch was geändert werden...mach ich heute

**Comment by 2Abendsegler** [comment]
... wollte nicht drängeln ... wollte nur den Stand wissen

**Comment by capoaira** [comment]
> ```js
> case 'ctl00_ContentBody_lockedMessage': html += '<b>Status:</b> <em>Ready to publish</em>'; break;
> ```

Mir ist gerade aufgefallen, dass die locked Message auch für gesperrte, veröffentlichte Caches gilt.
Eventuell sollte man unveröffentlichte Cache mit
```js
case "unpublished_cache":
     if (is_page('cache_listing') && !$('#uxLatLonLink')[0]) !== null) status = true;
     break;
```
abfragen.

**Comment by Ruko2010** [comment]
@capoaira weist du ob die Funktion "Post Reviewer Note" da ist, wenn man das Listing eingereicht hat und auf Review wartet?

**Comment by capoaira** [comment]
Ja, die ist dann auch noch da.

**Comment by Ruko2010** [comment]
Dann könnte man doch darauf testen, denn das verschwindet doch, wenn ein Cache eingereicht wird...oder sehe ich das falsch?

**Comment by Ruko2010** [comment]
ctl00_ContentBody_GeoNav_uxPostReviewerNoteLogType das ist die betreffende ID, kannst du mal schauen ob die gleich bleibt?

**Comment by Ruko2010** [comment]
Ich frag in der Zeit mal bei einer befreundeten Reviewerin nach...vielleicht weis die mehr.

**Comment by capoaira** [comment]
Ja, die ist in jedem Zustand noch da. Nur kurz vorm Publish (also im locked Zustand) weiß ich nicht, aber dass ist ja nicht so schlimm.

**Comment by Ruko2010** [comment]
Ich telefonier 15 Uhr mit ner Reviewerin, vielleicht kann die mir genaueres sagen. Ansonsten können wir ja auch eine Kombination aus mehrere "oder" Statements machen...

**Comment by Ruko2010** [comment]
Also Sie meinte auch, dass der Button "Post Reviewer Note" immer da sein müsste, nur nich wenn der Cache "ready to publish", also gelockt ist. Aber wie du schon sagtest sollte es dann auch kein Problem mehr sein. Ich bau es also auf den NoteButton um

**Comment by capoaira** [comment]
Ok. Das hört sich gut an 👍🏻

**Comment by Ruko2010** [comment]
Ist gefixt und gepushed testest du/ihr nochmal?

Mit diesem Link könnt ihr die Version testen:
[Neue Version zum testen](https://github.com/Ruko2010/GClh/raw/issue/1305-unpublished_caches_sidebar_functions/gc_little_helper_II.user.js)

und mit diesem kommt ihr wieder zurück auf die aktuelle stabile Version:
[Zurück zur aktuellen Version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js)

**Comment by capoaira** [comment]
Sieht gut aus und funktioniert alles. Der c2c Button neben den Koords fehlt aber immer noch.

**Comment by Ruko2010** [comment]
Der hier? Oder welchen meinst du? Wie du siehst ist der bei mir da?!
![image](https://user-images.githubusercontent.com/2239440/77355094-238f0280-6d44-11ea-90d0-2ced18d769f7.png)

**Comment by Ruko2010** [comment]
@capoaira hattest du schon Zeit nochmal drüber zu schauen?

**Comment by capoaira** [comment]
Oh, hatte vergessen nochmal drüber zu gucken.
Ab Zeile 1943:
```js
// Copy coordinates to clipboard.
    if (is_page("cache_listing") && $('#uxLatLonLink')[0]) {
        try {
            var cc2c = false;
            var span2 = document.createElement('span');
            span2.innerHTML = '<a href="javascript:void(0);" class="working" id="gclh_cc2c"><img src="'+global_copy_icon+'" style="vertical-align: text-top;"></a> ';
            $('#uxLatLonLink')[0].parentNode.insertBefore(span2, $('#uxLatLonLink')[0] );
```

Das Problem ist `#uxLatLonLink`, da diese id nicht existiert wird die Funktion gar nicht durchgeführt. Komischerweise funktioniert es aber bei dir.

Bei mir funktioniert es mit folgender Änderung (bei unveröffentlichten und veröffentlichten):

```js
// Copy coordinates to clipboard.
    if (is_page("cache_listing") && $('#uxLatLon')[0]) {
        try {
            var cc2c = false;
            var span2 = document.createElement('span');
            span2.innerHTML = '<a href="javascript:void(0);" class="working" id="gclh_cc2c"><img src="'+global_copy_icon+'" style="vertical-align: text-top;"></a> ';
            var cc2c_pos = ($('#uxLatLonLink')[0] ? $('#uxLatLonLink')[0] : $('#uxLatLon')[0])
            cc2c_pos.parentNode.insertBefore(span2, cc2c_pos);
```

**Comment by Ruko2010** [comment]
Ich bin leicht verwirrt...warum sollte es  bei mir klappen, aber bei dir nicht? Das macht doch keinen Sinn. Das ist ein Programm, dass sollte immer das gleiche machen...
Da schau ich nochmal genauer rein, aber danke für den Hinweis im Coding. Ich erwähne dich nochmal, wenn ich was gefunden habe.

**Comment by capoaira** [comment]
![grafik](https://user-images.githubusercontent.com/50927164/77636657-b900e100-6f54-11ea-84a2-b5fe571761d6.png)

Bei mir sieht es so aus (mit meinen Änderungen mit cc2c Button). Ich würde nicht so viel Wert drauf legen, aber bei mir verrutscht "Map this Location" und die Höhenangabe wird nicht angezeigt.
Damit es bei mir funktioniert müsste bei "Map this Location" in Zeile 2052 `else var link = $('#uxLatLon')[0].parentNode.parentNode;` stehen. Also ein `parentNode` mehr.

> Ich bin leicht verwirrt...warum sollte es bei mir klappen, aber bei dir nicht? Das macht doch keinen Sinn. Das ist ein Programm, dass sollte immer das gleiche machen...

Denke ich eigentlich auch. Ich nutze Firefox auf Windows 10. Eventuell wird die Seite unterschiedlich aufgebaut?

![grafik2](https://user-images.githubusercontent.com/50927164/77638603-b2c03400-6f57-11ea-9820-16fc64f46b95.png)

So sieht es bei mir aus

**Comment by Ruko2010** [comment]
@capoaira welchen Status hat dein unveröffentlichter Cache? Ist der normal angelegt und noch nicht eingereicht? Nicht, dass es da auch noch unterschiede gibt.

**Comment by capoaira** [comment]
Der ist noch nie eingereicht worden. Aber auch bei anderen mit anderen Status ist es bei mir so...

**Comment by capoaira** [comment]
> und die Höhenangabe wird nicht angezeigt.

Die wird bei mir angezeigt wenn man Zeile 3296 (`$("#uxLatLonLink").after('<span title="Elevation">&nbsp;&nbsp;&nbsp;Elevation:&nbsp;<span class="'+classAttribute+'" id="'+idAttribute+'"></span></span>');`) durch

```js
var elevation_pos = ($('#uxLatLonLink')[0] ? $('#uxLatLonLink')[0] : $('#uxLatLon')[0].parentNode)
$(elevation_pos).after('<span title="Elevation">&nbsp;&nbsp;&nbsp;Elevation:&nbsp;<span class="'+classAttribute+'" id="'+idAttribute+'"></span></span>');
```
ersetzt.

**Comment by Ruko2010** [comment]
@capoaira ich hab mir gerade mal das Listing eines unveröffentlichen Caches angeschaut, wenn ich den aktuellen Collector nutze. Schon da habe ich das Symbol für die Copy Funktion, nur dass sie nicht funktioniert. Bei dir ist das Symbol überhaupt nicht da. Kann es sein, dass du irgendwas anders konfiguriert hast?

Dein Bild aus dem ersten Post hier:
![image](https://user-images.githubusercontent.com/2239440/77731156-aba23000-7002-11ea-8c9d-f407d338d4c4.png)

Und mein Listing mit dem aktuellen Collector (ohne alle Änderungen die ich gemacht hatte):
![image](https://user-images.githubusercontent.com/2239440/77731198-bfe62d00-7002-11ea-895d-fbebaafb741a.png)


Irgendwas ist also anders bei dir (oder bei mir 😉).

**Comment by 2Abendsegler** [comment]
Ich hab mir auch mal die passende Version aufgespielt.
https://github.com/Ruko2010/GClh/raw/issue/1305-unpublished_caches_sidebar_functions/gc_little_helper_II.user.js

Es hat bei mir ziemlich viel Ähnlichkeit mit dem Aussehen von capoairas Beispiel (FF und Chrome).
![grafik](https://user-images.githubusercontent.com/22332216/77749557-81606a80-7022-11ea-9204-ef9cf6e18528.png)

Mit dem aktuellen Collector ist der Button bei mir nicht vorhanden (FF und Chrome). Also so wie bei capoaira.
![grafik](https://user-images.githubusercontent.com/22332216/77749795-ecaa3c80-7022-11ea-835f-2236685f5455.png)

Womöglich hängt es damit zusammen, dass die Seite unterschiedlich schnell geladen wird bzw. Teile in unterschiedlicher Reihenfolge geladen werden. Vielleicht könnte man das Coding zum Button mit allen Abfragen mal testweise etwas warten lassen und eine Sekunde später ausführen lassen. 

Blöde Idee, aber mehr fällt mir auch nicht ein. 🙄

**Comment by 2Abendsegler** [comment]
Noch vergessen. Fehler in der Console gibt es bei mir nicht.

**Comment by capoaira** [comment]
Mir ist noch etwas aufgefallen. Wenn man schnell genug guckt, sieht man wie der Stift zum bearbeiten der Koords verschwindet. Ich konnte das im Code nicht beobachten, aber die id `#uxLatLonLink` hängt bei veröffentlichten damit zusammen. Wenn der GClh geladen wird, während der Stift und somit auch die id noch da ist, wird der Button angezeigt. Wenn der Stift und die id entfernt sind nicht.
@Ruko2010 kannst du dir mal `#uxLatLonLink`  in der Konsole ausgeben lassen. Bei mir spuckt die Konsole dann `undefined` aus. Wenn das der Fall ist, müsste https://github.com/2Abendsegler/GClh/issues/1305#issuecomment-604346208 das Problem beheben.

**Comment by capoaira** [comment]
Meine Einstellungen für das Cachelisting:
![2020-03-27](https://user-images.githubusercontent.com/50927164/77753686-482bf880-702a-11ea-9981-fafebabf817b.png)
![2020-03-27 (1)](https://user-images.githubusercontent.com/50927164/77753688-495d2580-702a-11ea-9090-13217817930e.png)
![2020-03-27 (2)](https://user-images.githubusercontent.com/50927164/77753689-4a8e5280-702a-11ea-9aca-59210271df68.png)

**Comment by Ruko2010** [comment]
Ja das war nach @2Abendsegler aussage auch meine erste idee. Vielleicht muss ich auch einfach mal meine Internetverbindung drosseln um den Effekt zu sehen.

**Comment by Ruko2010** [comment]
So Freunde, lange hat es gedauert (ja ich hab kein Corona-Zwangs-Frei und Langeweile, sondern volle Arbeit im Homeoffice + Kinderbetreuung 😉).
Ich bin nochmal durch den Code gegangen und habe nun hoffentlich alle Schwachstellen gefixt. Auch mit Slow3G klappte es nun ohne Probleme. @2Abendsegler und @capoaira könntet ihr bitte nochmal testen? Änderungen sind wieder in meinem Repo:

[Neue Version zum testen](https://github.com/Ruko2010/GClh/raw/issue/1305-unpublished_caches_sidebar_functions/gc_little_helper_II.user.js)

und mit diesem kommt ihr wieder zurück auf die aktuelle stabile Version:
[Zurück zur aktuellen Version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js)

**Comment by capoaira** [comment]
Jip, sieht gut aus. Funktioniert alles super. Vielen Dank für Arbeit

**Comment by 2Abendsegler** [comment]
Hab mir die Version angesehen. Nur ein Punkt ist mir aufgefallen.
Beim Click auf "Copy Coordinates to Clipboard" im Listing eines bereits veröffentlichen Caches, und nur dort, öffnet der Koordinaten Änderungsdialog. Ob das was mit deinen Änderungen zu tun hat, habe ich nicht geprüft. Vielleicht war auch Seattle mal wieder dran. Vielleicht kannst du dir das noch ansehen.

Passt auf euch auf!

**Comment by Ruko2010** [comment]
Nein, dass liegt leider an meinen Änderungen :/. Ich schau es mir nochmal an.

**Comment by Ruko2010** [comment]
So, ich hoffe der Bug ist nun gefixt. Bei mir klappte es bei allen Varianten. @2Abendsegler schaust du nochmal drüber? Kannst dann auch gern mergen.

**Comment by capoaira** [comment]
Bei den Veröffentlichten sieht es gut aus, aber den unveröffentlichten gibt es jetzt einen Zeilenumbruch:
![grafik](https://user-images.githubusercontent.com/50927164/80923090-9b0f7300-8d81-11ea-866a-fa72c918a96a.png)

**Comment by Ruko2010** [comment]
Das ist doch nervig....bei mir sieht alles gut aus, auch bei unveröffentlichten 😃.

![image](https://user-images.githubusercontent.com/2239440/80923537-b3cd5800-8d84-11ea-8b7a-1ae8e1fb1f58.png)


Welchen Browser, OS nutzt du? Ich test am Mac mit Chrome

**Comment by jakedot** [comment]
Vielleicht haben sie da unterschiedliches HTML je nach Browser/OS, meinst du? Ach Mensch, ich dachte die Browserschranken wären inzwischen alle geöffnet, so wie die Grenzen. Oh.

**Comment by Ruko2010** [comment]
@capoaira hast du auch wirklich die neuste Version installiert? Bei dir fehlt auch die Elevation, die eigentlich drin sein sollte.

**Comment by capoaira** [comment]
Ich habe den Link vom 1. April genommen, der müsste die neuste Version installiert haben.
Ich nutze Firefox unter Windows 10

**Comment by Ruko2010** [comment]
ok, dann schau ich nochmal. Ich glaub ich hab ne VM mit Windows 10. Vielleicht liegt es auch wieder an der Geschwindigkeit. Danke für die Info.

**Comment by Ruko2010** [comment]
Gerade nochmal mit Windoof 10 und Firefox getestet. Sowohl unpublished als auch published gehen ohne Probleme.
![image](https://user-images.githubusercontent.com/2239440/81009779-8bf9f500-8e55-11ea-9858-23461982fa9d.png)
![image](https://user-images.githubusercontent.com/2239440/81009757-82708d00-8e55-11ea-849c-f99abadb09e6.png)

Auch mit Slow 3G im Chrome klappt alles.
@2Abendsegler kannst du mal schauen wie es bei dir aussieht?

**Comment by 2Abendsegler** [comment]
Bei mir sieht es bei den Veröffentlichen prima aus.
![grafik](https://user-images.githubusercontent.com/22332216/81169017-63c6df00-8f98-11ea-999f-a7074b0bedf9.png)

Bei den Unveröffentlichen zeigt es sich so wie bei capoaira.
![grafik](https://user-images.githubusercontent.com/22332216/81169395-15661000-8f99-11ea-8ffd-fbd0202e4f42.png)

Ich habe mit dem aktuellen Stand im PR #1329 getestet. @Ruko2010 Kann es sein, dass der PR deine letzten Änderungen noch nicht beinhaltet? Dann gib mir einen anderen Link.

**Comment by Ruko2010** [comment]
> @Ruko2010 Kann es sein, dass der PR deine letzten Änderungen noch nicht beinhaltet? Dann gib mir einen anderen Link.

Du hast völlig recht. Irgendwie spinnt Github. Ich habe natürlich die Änderung schon gepushed und die sollte im PR mit drin sein, aber es wird nicht angezeigt. Ich hab nun einen neuen PR auf gemacht, der sollte alles beinhalten. hier könnt ihr euch die Version installieren:

https://github.com/Ruko2010/GClh/raw/issue/1305-unpublished_caches_sidebar_functions/gc_little_helper_II.user.js

**Comment by Ruko2010** [comment]
Neuen PR findet ihr hier: https://github.com/2Abendsegler/GClh/pull/1338

**Comment by 2Abendsegler** [comment]
Merged

```
	<li>
		<strong>New:</strong> Coords related functions does not work on unpublished caches. [<a href="https://github.com/2Abendsegler/GClh/issues/1305" title="Issue 1305">1305</a> / <a href="https://www.geocaching.com/profile/?u=Ruko2010" title="Thanks to Ruko2010">Ruko2010</a>]<br>
		<img src="../images/0.10.6/Screen04.jpg" alt="Screen04.jpg"><br><br>
	</li>
```
