### ISSUE TITLE
New placeholders for own stuff in copy to clipboard menu in cache listing.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1308]
New placeholders for own stuff in copy to clipboard menu in cache listing.

**Comment by 2Abendsegler** [comment]
#GCLink# : GC link
#Coords# : Shown coordinates
#GCNote# : User note (if not empty)
#newline# : Add new line

**Comment by 2Abendsegler** [comment]
@Herr-Ma 
Sag hier mal noch Hallo mit einem Posting. Danach kann ich das Teil auch assignen.
Schönes WE

**Comment by 2Abendsegler** [comment]
Hab auch noch ein paar Platzhalter dazugebaut.

Insgesamt haben wir folgende Platzhalter:
```
  #GCName# : GC name
  #GCCode# : GC code
  #GCLink# : GC link
  #GCNameLink# : GC name as a link
  #Owner# : Username of the owner
  #Diff# : Difficulty
  #Terr# : Terrain
  #Size# : Size of the cache box
  #Favo# : Favorites
  #FavoPerc# : Favorites percentage
  #Elevation# : Elevation
  #Coords# : Shown coordinates
  #GCNote# : User note
  #Founds# : Number of found logs
  #FoundsPlus# : Number of found or synonym logs
  #DNFs# : Number of DNF logs
  #Date# : Actual date
  #Time# : Actual time in format hh:mm
  #DateTime# : Actual date actual time
  #yyyy# : Current year
  #mm# : Current month
  #dd# : Current day
  #newline# : Add new line
```

**Comment by Herr-Ma** [comment]
Wow - da hast du aber jetzt viele Dinge ermöglicht. Ob da jetzt etwas fehlt oder nicht, wird sich erst bei Benutzung der Anwender zeigen. Jeder hat da ja seine eigenen Bedürfnisse, daher werden dann (hoffentlich) Meldungen kommen, wenn jemand zusätzlich noch etwas braucht.

...ich geh' jetzt erst mal nach Bonn 👋🏻

Mit beethöflichen Grüßen, 
Marcus alias Herr Ma

**Comment by Herr-Ma** [comment]
Sieht gut aus - keine Beanstandung ;-)

...außer vielleicht, dass mit einem mehrzeiligen Eingabefeld der Palceholder #newline# im Grunde genommen überflüssig geworden ist

**Comment by 2Abendsegler** [comment]
Stimmt, ich werde das #newline# noch entsorgen.

**Comment by 2Abendsegler** [comment]
"Additional hints" noch dazugebaut

```
	<li>
		<strong>New:</strong> New placeholders for own stuff in copy to clipboard menu in cache listing. [<a href="https://github.com/2Abendsegler/GClh/issues/1308" title="Issue 1308">1308</a> / <a href="https://www.geocaching.com/profile/?u=Herr-Ma" title="Thanks to Herr-Ma">Herr-Ma</a> / <a href="https://www.geocaching.com/profile/?u=2Abendsegler" title="Thanks to 2Abendsegler">2Abendsegler</a>]<br>
		<img src="../images/0.10.5/Screen15.jpg" alt="Screen15.jpg"><br><br>
	</li>
```


![Screen15](https://user-images.githubusercontent.com/22332216/76108833-9d508d80-5fdb-11ea-95c0-4473294af2c1.jpg)

**Comment by frenkovo** [comment]
Hi, and type cache?
#GCType# ? ;)

**Comment by Ruko2010** [comment]
Hi @frenkovo 
Since this ticket is already done, can you please open a new one with your request? @2Abendsegler is surely happy to implement it 😉

**Comment by frenkovo** [comment]
> Hi @frenkovo
> Since this ticket is already done, can you please open a new one with your request? @2Abendsegler is surely happy to implement it 😉

I didn't notice that, I'm sorry.
