### ISSUE TITLE
Multi entries for own stuff in copy to clipboard menu in cache listing.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1309]
Multi entries for own stuff in copy to clipboard menu in cache listing.

**Comment by 2Abendsegler** [comment]
@Herr-Ma, @Ruko2010, @capoaira 
Vielleicht hat jemand Lust etwas drüberzuschauen. Hier geht es weniger ums Testen als um eine Überprüfung ob noch was fehlt. 

[Temporärer Link zum Script](https://github.com/2Abendsegler/GClh/raw/b19dc5c22af5ce0c1373d691205588ff608f783c/gc_little_helper_II.user.js)

Settings -> Listing:
![1](https://user-images.githubusercontent.com/22332216/75595889-80bdce00-5a8e-11ea-9e47-32d57cd6a646.JPG)

Copy Data Menu im Listing:
![2](https://user-images.githubusercontent.com/22332216/75595895-85828200-5a8e-11ea-9909-db149ec36562.JPG)

Kopiert in Zwischenablage:
```
  Seenot : GC name
  GC2RGFX : GC code
  https://coord.info/GC2RGFX : GC link
  [Seenot](https://coord.info/GC2RGFX) : GC name as a link
  nichtsnutz & Daria74 : Username of the owner
  4 : Difficulty
  2.5 : Terrain
  small : Size of the cache box
  42 : Favorites
  29% : Favorites percentage
  +86m : Elevation
  N 49° 29.111 E 008° 30.222 : Shown coordinates
  gelöst : User note
  175 : Number of found logs
  175 : Number of found or synonym logs
  2 : Number of DNF logs
  29.02.2020 : Actual date
  00:56 : Actual time in format hh:mm
  29.02.2020 00:56 : Actual date actual time
  2020 : Current year
  02 : Current month
  29 : Current day
  
 : Add new line
```

**Comment by 2Abendsegler** [comment]
#1308

**Comment by capoaira** [comment]
Wow, nicht schlecht. Das sieht sehr vielversprechend aus. Im Moment fällt mir nichts ein, was fehlt. Ich schaue morgen nochmal genauer drüber.

**Comment by Ruko2010** [comment]
@2Abendsegler Ich hab es mir angeschaut und es sieht klasse aus.
Was ich noch hinzufügen würde ist
Anzahl der Will Attend Logs und Anzahl der Attended.
Gerade bei Events bringen ja die Fund zahlen nicht viel. Ansonsten kann das meiner Meinung nach Live gehen...

**Comment by 2Abendsegler** [comment]
Das attended funktioniert schon mit #FoundsPlus# Number of found or synonym logs. Naja, sofern nicht jemand mit found gelogged hat.

Ich werde beides noch einzeln einbauen.

**Comment by Ruko2010** [comment]
Ah ok. Das mit dem FoundsPlus hatte ich nicht verstanden.

**Comment by 2Abendsegler** [comment]
Wie kann ich die Bezeichnung verständlicher machen?

**Comment by Ruko2010** [comment]
Mit einem Beispiel: Number of found or synonym logs, for example Attend Logs for Events

**Comment by 2Abendsegler** [comment]
Ja, danke, das mache.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Habs jetzt so benannt:
#FoundsPlus# : Number of found, attended, webcam photo taken logs
Ist das ok?

**Comment by Ruko2010** [comment]
Sorry, für das rummäckeln, aber ich würde es:

#FoundsPlus# : Number of found, attended or webcam photo taken logs

nennen. Ansonsten passt es.

**Comment by 2Abendsegler** [comment]
Schon ok. 
Das ging halt nicht in eine Zeile. Aber ich mach das jetzt so wie du schreibst, hast schon recht.

**Comment by 2Abendsegler** [comment]
```
	<li>
		<strong>New:</strong> Multi entries for own stuff in copy to clipboard menu in cache listing. [<a href="https://github.com/2Abendsegler/GClh/issues/1309" title="Issue 1309">1309</a> / <a href="https://www.geocaching.com/profile/?u=2Abendsegler" title="Thanks to 2Abendsegler">2Abendsegler</a>]<br>
		You can create for example something like this.<br>
		<a href="https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_copydata_menu" title="Link to your GClh Config">Settings -> Listing:<br>
		<img src="../images/0.10.5/Screen12.jpg" alt="Screen12.jpg"></a><br>
		Cache Listing:<br>
		<img src="../images/0.10.5/Screen13.jpg" alt="Screen13.jpg"><br>
		Clipboard:<br>
		<img src="../images/0.10.5/Screen14.jpg" alt="Screen14.jpg"><br><br>
	</li>
```

![Screen12](https://user-images.githubusercontent.com/22332216/76109564-fb31a500-5fdc-11ea-95ff-f21bb3715dd9.jpg)

![Screen13](https://user-images.githubusercontent.com/22332216/76109571-fec52c00-5fdc-11ea-9f83-228311d85384.jpg)

![Screen14](https://user-images.githubusercontent.com/22332216/76109578-0258b300-5fdd-11ea-8274-78e6e597d0d3.jpg)
