### ISSUE TITLE
Download current config as txt-file

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#1312]
Add a Button to directly download the current GClh-Configuration as textfile.

**Comment by Ruko2010** [comment]
Hallo @MarkusKn
Es ging viel schneller als gedacht 😃. Hier der Link für dich zum Testen:

https://github.com/Ruko2010/GClh/raw/issue/1312-download_config_as_file/gc_little_helper_II.user.js

Einfach draufklicken und installieren. Wenn du zurück zur aktuellen Version willst, bitte hier klicken:
https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js

**Comment by MarkusKn** [comment]
Top @Ruko2010, funktioniert wie erwartet, vielen Dank dafür!

**Comment by 2Abendsegler** [comment]
```
	<li>
		<strong>New:</strong> Download current config as txt-file. [<a href="https://github.com/2Abendsegler/GClh/issues/1312" title="Issue 1312">1312</a> / <a href="https://www.geocaching.com/profile/?u=Ruko2010" title="Thanks to Ruko2010">Ruko2010</a>]<br>
		<a href="//#GClhShowSync" title="Link to your GClh Sync">GClh Sync<br>
		<img src="../images/0.10.5/Screen16.jpg" alt="Screen16.jpg"></a><br>
		<img src="../images/0.10.5/Screen17.jpg" alt="Screen17.jpg"><br>
		<img src="../images/0.10.5/Screen18.jpg" alt="Screen18.jpg"><br><br>
	</li>
```

![Screen16](https://user-images.githubusercontent.com/22332216/76113214-02a87c80-5fe4-11ea-9f35-f2e4544e4a99.jpg)

![Screen17](https://user-images.githubusercontent.com/22332216/76113221-05a36d00-5fe4-11ea-8aed-fea3d845213a.jpg)

![Screen18](https://user-images.githubusercontent.com/22332216/76113228-089e5d80-5fe4-11ea-9b80-1ed920afb35e.jpg)
