### ISSUE TITLE
Flopp's Map distance line between coords and corrected coords does not work. Add parameter to show radius around caches on Flopp's Map.

### ISSUE THREAD

**Issue by AndyPuma** [2Abendsegler/GClh#1334]
Hi,
wenn ihr O & L verwendet dann aber in der URL &d=O:C verwendet funktioniert es nicht

https://github.com/2Abendsegler/GClh/blob/a4d060fe8bc51509bcdce1ffec9e1e3d9e5ac2c4/gc_little_helper_II.user.js#L2594

https://github.com/2Abendsegler/GClh/blob/a4d060fe8bc51509bcdce1ffec9e1e3d9e5ac2c4/gc_little_helper_II.user.js#L2654

PS.: Die 2 Kreise mit 3200m Radius lassen durch die Überlagerung kaum noch was von der Karte zu erkennen übrig - meine Empfehlung nur noch die Distanzline - da kann jeder selber entscheiden ob die 3000m eingehalten werden.

**Comment by Ruko2010** [comment]
Ich bin leicht verwirrt. Kannst du nochmal genau schreiben was das Problem ist und wenn du sie parat hast, eine Lösung 😃?

**Comment by capoaira** [comment]
Wenn ich es richtig verstanden habe, wird die Distanzline nicht angezeigt, da zwei verschiedene IDs verwendet werden.#
Ich habe mir das gerade mal angeguckt. Man muss nur bei `&d=O:C` das C durch L ersetzten

Dabei ist mir aufgefallen, dass die google Maplayer doppelt angezeigt werden.
Also `Google Maps` ist das selbe wie `Google Maps Hybrith` und `Googe Maps Terrain` ist das selbe wie `Googe Maps Satellite`

**Comment by AndyPuma** [comment]
wollen wir kurz tel.?
0152 29 26 40 81

wir kennen uns übrigens von einem Cache der EF Radrunde wo uns mit Locke
und Leiter über dem Kopf begenet bist.

Andy Puma66

Ruko2010 <notifications@github.com> schrieb am So., 3. Mai 2020, 15:04:

**Comment by Ruko2010** [comment]
@2Abendsegler Ich hab einen Pull dazu auf gemacht. Gefixt ist der Link und ich habe eine Option für den Radius eingebaut, da ich selbst den nicht brauche, aber vielleicht jemand anders. So kann man es aus schalten bei Bedarf.

@AndyPuma Wenn du willst kannst du hier die neue Version schon installieren:
https://github.com/Ruko2010/GClh/raw/issue/1334-link-to-flopps/gc_little_helper_II.user.js

**Comment by Ruko2010** [comment]
@AndyPuma was nebenbei, wie hast du den Link auf die Codezeile erstellt? Die Funktion kannte ich noch nicht.

**Comment by Ruko2010** [comment]
Test:
https://github.com/2Abendsegler/GClh/blob/a4d060fe8bc51509bcdce1ffec9e1e3d9e5ac2c4/gc_little_helper_II.user.js#L2511-L2519

**Comment by 2Abendsegler** [comment]
@capoaira 
Bitte möglichst keinen Text mehr löschen, weil man sonst Änderungen nicht mehr nachvollziehen kann. Ich hab gerade ewig nach dem Posting zu den doppelten Links Google Maps ... gesucht. 🙄
Besser mit `<del> ... </del>` arbeiten. Das ist dann <del>durchgestrichener</del> Text. 😊

**Comment by capoaira** [comment]
Ok, tut mir leid.
Ich habe gemerkt, dass es doch Unterschiede gibt.

**Comment by 2Abendsegler** [comment]
```
	<li>
		<strong>Fix:</strong>Flopp's Map distance line between coords and corrected coords does not work. [<a href="https://github.com/2Abendsegler/GClh/issues/1334" title="Issue 1334">1334</a> / <a href="https://www.geocaching.com/profile/?u=Ruko2010" title="Thanks to Ruko2010">Ruko2010</a>]<br>
	</li>

	<li>
		<strong>New:</strong> Add parameter to show radius around caches on Flopp's Map. [<a href="https://github.com/2Abendsegler/GClh/issues/1334" title="Issue 1334">1334</a> / <a href="https://www.geocaching.com/profile/?u=Ruko2010" title="Thanks to Ruko2010">Ruko2010</a>]<br>
		<img src="../images/0.10.6/Screen02.jpg" alt="Screen02.jpg"><br>
		<a href="https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_radius_on_flopps" title="Link to your GClh Config">Settings -> Listing:<br>
		<img src="../images/0.10.6/Screen03.jpg" alt="Screen03.jpg"></a><br><br>
	</li>
```

![Screen02](https://user-images.githubusercontent.com/22332216/81176489-827fa280-8fa5-11ea-82e7-188acd20a874.jpg)

![Screen03](https://user-images.githubusercontent.com/22332216/81176501-857a9300-8fa5-11ea-90f7-aed016b92a6b.jpg)
