### ISSUE TITLE
Scroll Bar at statistik page is missing respectively number of caches not recognizable everywhere.

### ISSUE THREAD

**Issue by jet2mike** [2Abendsegler/GClh#1344]
Hallo,

mit aktiviertem GC little helper II, wedern im Firefox keine Scroll Bars in der Statistik angezeigt.
Somit kann man nicht mehr zum aktuellen Monat wechseln, um z.B. die Anzahl der Funde von Mai zu checken.
Vermutlich passiert das bei Mitgliedern ~10 Jahre, wenn eine gewisse Monatsanzahl erreicht ist.
Bitte um check.

lg jet2mike

**Comment by jet2mike** [comment]
![grafik](https://user-images.githubusercontent.com/64960050/81285228-7fe18380-905f-11ea-925c-4f757a3e3258.png)

**Comment by 2Abendsegler** [comment]
Hallo, 
wenn ich mir deine Statistik ansehe, sieht das eigentlich in Ordnung aus. Es gibt keine Scrollbalken, das soll so sein. Trotzdem wird der gesamte Zeitraum angezeigt.

![grafik](https://user-images.githubusercontent.com/22332216/81285902-81f81200-9060-11ea-8c9e-01b78a193284.png)

Mit welchem System und Browser arbeitest du?
Kannst du bitte mal alle anderen Scripte und Add-Ons abschalten bis auf den GClh?

**Comment by 2Abendsegler** [comment]
Welche Auflösung ([Page width](https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width)) verwendest du im GClh?

**Comment by jet2mike** [comment]
Windows 10  

Auflösung: 1920x1080

Zoom 130 % (Firefox)

Ändert aber auch bei 100% + Refresh nichts 

 

Andere Scrips sind nicht in Verwendung

 

 



 



 

Von: 2Abendsegler [mailto:notifications@github.com] 
Gesendet: Donnerstag, 7. Mai 2020 12:47
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: jet2mike <jet2mike@a1.net>; Author <author@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Scroll Bar at statistik page is missing (#1344)

 

Hallo,
wenn ich mir deine Statistik ansehe, sieht das eigentlich in Ordnung aus. Es gibt keine Scrollbalken, das soll so sein. Trotzdem wird der gesamte Zeitraum angezeigt.

 <https://user-images.githubusercontent.com/22332216/81285902-81f81200-9060-11ea-8c9e-01b78a193284.png> 

Mit welchem System und Browser arbeitest du?
Kannst du bitte mal alle anderen Scripte und Add-Ons abschalten bis auf den GClh?

**Comment by 2Abendsegler** [comment]
Klick mal bitte auf den [Link](https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width) und gib mir die "Page width" aus dem GClh Config.

**Comment by jet2mike** [comment]
Super, danke das wars

 

Ich habe die 950 aber nie eingetragen – war Standard

 

Lg Michi

 

Von: 2Abendsegler [mailto:notifications@github.com] 
Gesendet: Donnerstag, 7. Mai 2020 13:10
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: jet2mike <jet2mike@a1.net>; Author <author@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Scroll Bar at statistik page is missing (#1344)

 

Klick mal bitte auf den Link <https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width>  und gib mir die "Page width" aus dem GClh Config.

**Comment by jet2mike** [comment]
Jetzt habe ich wieder einen Scroll-Bar ;-)

Es wäre noch cool wenn er „ganz rechts“ stehen würde, damit das aktuelle Monat gleich (ohne ihn zu bewegen) angezeigt wird, aber ich kann auch so damit leben.

 

Lg Michi

 

Von: Michael Hrbek [mailto:jet2mike@a1.net] 
Gesendet: Donnerstag, 7. Mai 2020 14:09
An: '2Abendsegler/GClh' <reply@reply.github.com>; '2Abendsegler/GClh' <GClh@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Betreff: AW: [2Abendsegler/GClh] Scroll Bar at statistik page is missing (#1344)

 

Super, danke das wars

 

Ich habe die 950 aber nie eingetragen – war Standard

 

Lg Michi

 

Von: 2Abendsegler [mailto:notifications@github.com] 
Gesendet: Donnerstag, 7. Mai 2020 13:10
An: 2Abendsegler/GClh <GClh@noreply.github.com <mailto:GClh@noreply.github.com> >
Cc: jet2mike <jet2mike@a1.net <mailto:jet2mike@a1.net> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [2Abendsegler/GClh] Scroll Bar at statistik page is missing (#1344)

 

Klick mal bitte auf den Link <https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width>  und gib mir die "Page width" aus dem GClh Config.

**Comment by capoaira** [comment]
@2Abendsegler ich glaube, dass der Mouseover gemeint ist. Wenn man mit der Maus über die Balken geht, wird die Anzahl der Caches in dem Monat angezeigt. Bei den letzten Monate  verschwindet das aber. (Auch bei mir ca. 5½ Jahre)

**Comment by 2Abendsegler** [comment]
Seit einigen Monaten werden die Grafiken etwas zu groß angezeigt, deshalb entsteht der Balken. Dabei ist es unerheblich, ob man schon lange oder nicht so lange dabei ist. Die Grafik ist immer gleich groß und der Balken ist immer da. Das ist eine Änderung von GS.  

Wir hatten versucht den fehlenden Platz für die Grafik zu beschaffen und die Grafik komplett anzuzeigen und ohne Balken und damit auch so, dass für alle Monate die Anzahl der Caches noch aufpoppt. Bei mir funktioniert das auch aber wohl nicht überall. 

@Capoaira, arbeitest du auch mit Zoom größer 100%?

Ich werde das Issue als Bug kennzeichnen und die Codingstelle heraussuchen. @Capoaira, du könntest dann vielleicht man schauen, ob du es etwas justieren kannst, damit die komplette Grafik, ohne Balken angezeigt wird.

**Comment by capoaira** [comment]
Klar, ich versuche mich daran

**Comment by capoaira** [comment]
> @capoaira, arbeitest du auch mit Zoom größer 100%?

Ich arbeite mit Zoom 100%

**Comment by jet2mike** [comment]
Ich arbeite mit 130% aber es macht keinen Unterschied, egal ob 90, 100 oder 130 einstelle, der Mittelteil der GC Seiten bleibt unverändert, es werden nur die Ränder bzw, Hintergrundgrafik schmäler und der Rest größer dargestellt.

Natürlich habe ich nach dem Zoomen auch refrehed.

 

Hier ein Screenshot mit 130% darunter der mit 100% ist mir zu klein – da bleibt der halbe Monitor weiß ;-)

Die Scloll Bars habe ich aber in beiden Fällen – trotz refresh

 



 



Von: capoaira [mailto:notifications@github.com] 
Gesendet: Freitag, 8. Mai 2020 10:35
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: jet2mike <jet2mike@a1.net>; Author <author@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Scroll Bar at statistik page is missing respectively number of caches not recognizable everywhere. (#1344)

 

@capoaira <https://github.com/capoaira> , arbeitest du auch mit Zoom größer 100%?

Ich arbeite mit Zoom 100%

**Comment by 2Abendsegler** [comment]
@jet2mike, @capoaira:

Ich habe Anpassungen vorgenommen. Ich hoffe nun funktioniert es sowohl auf der eigenen Statistik Seite wie auch auf dem Reiter Statistik im Profil. Es sollten keine Balken angezeigt werden, trotzdem sollten alle Grafiken und auch die Anzeigen, wenn man mit der Maus drüber geht, funktionieren. Das sollte für [page-width im Config](https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width) von 950 und größer gelten.  

Könnt ihr bitte das angepasste Script installieren:
[Hier](https://github.com/2Abendsegler/GClh/raw/6844b2c3cb333f7b987ccafb0a2cd9183296fb65/gc_little_helper_II.user.js) geht es zum angepassten Script.
[Hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) geht es wieder zurück zum Original.

Könnt ihr bitte mal testen:
[Eigene Statistik Seite](https://www.geocaching.com/my/statistics.aspx)
[Profil von jet2mike](https://www.geocaching.com/profile/?guid=9e979d02-3eeb-465e-bf38-2cc4a8a257ed), dort dann Reiter Statistik anwählen.

**Comment by capoaira** [comment]
Sieht gut aus

**Comment by jet2mike** [comment]
Vielen Dank, das schaut jetzt auch bei mir gut aus

Wahnsinn, wie schnell das Problem gelöst war – ich habe mich damit schon 3 Monate abgeärgert ;-)

 

Lg Michi

 

Von: 2Abendsegler [mailto:notifications@github.com] 
Gesendet: Samstag, 9. Mai 2020 15:41
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: jet2mike <jet2mike@a1.net>; Mention <mention@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Scroll Bar at statistik page is missing respectively number of caches not recognizable everywhere. (#1344)

 

@jet2mike <https://github.com/jet2mike> , @capoaira <https://github.com/capoaira> :

Ich habe Anpassungen vorgenommen. Ich hoffe nun funktioniert es sowohl auf der eigenen Statistik Seite wie auch auf dem Reiter Statistik im Profil. Es sollten keine Balken angezeigt werden, trotzdem sollten alle Grafiken und auch die Anzeigen, wenn man mit der Maus drüber geht, funktionieren. Das sollte für page-width im Config <https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width>  von 950 und größer gelten.

Könnt ihr bitte das angepasste Script installieren:
Hier <https://github.com/2Abendsegler/GClh/raw/6844b2c3cb333f7b987ccafb0a2cd9183296fb65/gc_little_helper_II.user.js>  geht es zum angepassten Script.
Hier <https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js>  geht es wieder zurück zum Original.

Könnt ihr bitte mal testen:
Eigene Statistik Seite <https://www.geocaching.com/my/statistics.aspx> 
Profil von jet2mike <https://www.geocaching.com/profile/?guid=9e979d02-3eeb-465e-bf38-2cc4a8a257ed> , dort dann Reiter Statistik anwählen.

**Comment by 2Abendsegler** [comment]
In Zukunft einfach direkt melden. 😉

Danke euch Beiden für die Tests.
LG Frank

**Comment by 2Abendsegler** [comment]
Close

---
```
	<li>
		<strong>Fix:</strong> Scroll Bar at statistik page is missing respectively number of caches not recognizable everywhere. [<a href="https://github.com/2Abendsegler/GClh/issues/1344" title="Issue 1344">1344</a> / <a href="https://www.geocaching.com/profile/?u=2Abendsegler" title="Thanks to 2Abendsegler">2Abendsegler</a>]<br>
	</li>
```
