### ISSUE TITLE
Additional link for logging premium caches for non-premium cachers.

### ISSUE THREAD

**Issue by V60GC** [2Abendsegler/GClh#1345]
Der Link zum Loggen für Nicht-Premiumuser auf Premiumcaches wurde von Groundspeak scheinbar geändert.

Aktuell muss er wie folgt sein:

https://www.geocaching.com/play/geocache/gc5hnne/log

**Comment by 2Abendsegler** [comment]
Ich weiß nicht genau was du meinst. Gibt es einen Link den wir ändern müssen? Vielleicht kannst du die Sache etwas genauer beschreiben und vielleicht einen Screenshot hier reinhängen.

**Comment by 2Abendsegler** [comment]
@V60GC 
Hallo, kannst du uns bitte die Frage beantworten.

**Comment by V60GC** [comment]
Ich könnte wetten, dass ich die Frage schon beantwortet habe :-(  Es ist nur die Frage, wo ?????

 Es geht um den Link, mit dem ein nicht PMO-User einen PMO-cache loggen kann. Da scheint Groundspeak mal wieder etwas verändert zu haben. Auf jeden Fall führt der Link zu nichts.

![Unbenannt](https://user-images.githubusercontent.com/43401329/82758760-c9182e00-9de8-11ea-9d19-f4c87115ded7.JPG)

**Comment by 2Abendsegler** [comment]
Ah, ok, jetzt ist es mir klar was du meinst. Das werden wir uns ansehen.
Danke für die Meldung.

**Comment by 2Abendsegler** [comment]
@V60GC
Ich habe mich mal mit einem Basisuser angemeldet. Ich kann hier keinen Fehler feststellen. Der Link öffnet direkt unterhalb des "Log It" Buttons einen Bereich zum Loggen. Kannst du dir das vielleicht nochmal ansehen. Vielleicht hattest du übersehen, dass unterhalb des Buttons ein Bereich zum Loggen aufgemacht wird. Bei einem kleinen Bildschirm kann das schon passieren.
Das ganze sieht dann so aus:

![grafik](https://user-images.githubusercontent.com/22332216/83358255-90410180-a372-11ea-9e6e-ee6543f8ca04.png)

**Comment by V60GC** [comment]
Hmmm,

ich habe den selben Cache gewählt. Und es klappt bei mir leider nicht.

Hier jetzt mal meine Systemeinstellungen:

Win 10
Firefox 76.0.1
Tampermonkey 4.10.6112
GClh 0.10.6

Es wird folgender Link aufgerufen:
https://www.geocaching.com/geocache/GC5HNNE#gclhLogIt

Und es erscheint nur der Upgradehinweis. Egal wie oft ich den Button drücke.

Ich habe das Ganze an einem zweiten Rechner probiert und das gleiche
Ergebnis erziehlt.

Mit folgendem Link, den wir sonst immer nutzen klappt es:

https://www.geocaching.com/play/geocache/gc5hnne/log

Viele Grüße
Uwe




Am 31.05.2020 um 19:15 schrieb 2Abendsegler:

**Comment by 2Abendsegler** [comment]
@V60GC:
Sorry, das hat lange gedauert, ich war ziemlich faul.
Bei dir wird das wohl nicht angezeigt, weil ein Add on zum Blocken von vermutlich Werbung wie beispielsweise uBlock den eingebetteten Screen nicht zulässt. Um das abzustellen musst du in der Whitelist oder in etwas ähnlichem folgende Einträge aufnehmen:
```
www.geocaching.com
geocaching.com
```
Danach sollte es funktionieren.

Hier ist es nicht angedacht über einen Link wie beispielsweise https://www.geocaching.com/play/geocache/gc5hnne/log ins Log zu springen. Hier soll im bestehenden Screen ein Log Formular eingebettet werden, deshalb kann ich ach nicht deinen Link hier einfach setzen.

Versuch bitte mal ob du das mit deinem Add on hinbekommst und gib noch mal bescheid.

**Comment by 2Abendsegler** [comment]
@V60GC:
Gib bitte mal bescheid ob du das hinbekommen hast.

**Comment by V60GC** [comment]
Ja, bei abgeschaltetem Blocker poppt ein entsprechendes Formular auf.

Ist natürlich etwas unschön, da man ja, wenn man einen Blocker einsetzt,
diesen i.d.R. immer eingeschaltet hat und nur einzelne Seiten davon
ausnimmt. Und wenn man GC nicht ausgenommen hat, bekommt man halt dieses
Formular nicht, aber auch keinen Hinweis.




Am 31.08.2020 um 14:34 schrieb 2Abendsegler:

**Comment by 2Abendsegler** [comment]
Wir können keinen Hinweis ausgeben, ob ein Blocker eine solche Aktion blockt. Wir können nur allgemein darüber informieren, was bei solchen "Inline Logs" zu beachten ist. Genau das werden wir zur nächsten Version auch machen. Wir werden im Changelog etwas dazu schreiben und im Config bei den entsprechenden Parametern in Hilfstext.
Letzteres sieht dann so aus:
![grafik](https://user-images.githubusercontent.com/22332216/91748737-b750de80-ebc0-11ea-9a51-8abe02b4f5cb.png)

Zudem gibt es in einigen Listen eine andere Möglichkeit für das Loggen von Premium Caches durch Basismember.
![grafik](https://user-images.githubusercontent.com/22332216/91748302-12360600-ebc0-11ea-8c76-6a16a0c78cca.png)

Ich habe mich entschlossen neben dem derzeitigen "Log It" Button für Inline Logs noch einenzusätzlichen Button im Listing unterzubringen, so wie in der Liste oben. Dann solltest auch du glücklich sein ... 😃

**Comment by 2Abendsegler** [comment]
@V60GC:
Bitte teste mal. 
Du musst dazu die neue Version laden, kannst aber später wieder zurück zur aktuellen Version wenn du möchtest.

[Hier](https://github.com/2Abendsegler/GClh/raw/a2c1968fc48f4478a15c9209e96cdd694d26ca14/gc_little_helper_II.user.js) geht es zur Version mit den Änderungen.

[Hier](https://www.geocaching.com/my/#GClhShowConfig#a#settings_log_inline_pmo4basic) geht es zum Parameter 'Log cache from listing for PMO (for basic members)' im Config. Ist er aktiviert, gibt es einen Button zum Inline Logging und einen Link zum Log Formular. Das sieht dann so aus:
![Screen12](https://user-images.githubusercontent.com/22332216/91797590-3bd44900-ec23-11ea-9ea5-9191ae755317.jpg)

Ist der Parameter deaktiviert, gibt es nur einen Link zum Log Formular. Das sieht dann so aus:
![Screen13](https://user-images.githubusercontent.com/22332216/91797603-3f67d000-ec23-11ea-806b-945215210447.jpg)

[Hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) geht es zurück zur aktuellen Version.

**Comment by V60GC** [comment]
Bei mir passiert genau das, wie Du es beschrieben hast. Entweder habe
ich den Link und den Button oder nur den Link.


Am 01.09.2020 um 07:19 schrieb 2Abendsegler:

**Comment by 2Abendsegler** [comment]
Dann schließe ich das Issue mal. In der neuen Version in einigen Tagen ist das dann enthalten.

Die Änderungen sind gemerged.

**Comment by 2Abendsegler** [comment]
@V60GC:
Nachtrag: 
Du wolltest die Möglichkeit haben als Basis User aus einem Listing eines Premium Caches heraus das Log Formular aufzurufen. Das funktioniert nun mit der Anpassung die ich nur für dich gemacht habe. Für diese Anpassung und die Kommunikation habe ich einige Stunden investiert.
Der GClh wird von mir und einigen Gleichgesinnten in unserer Freizeit entwickelt. Eine Entlohnung erhalten wir dafür nicht. Auch deshalb freuen wir uns über ein paar nette Worte, über ein kleines Danke oder über den Ausdruck der eigenen Freude dass es wie gewünscht funktioniert.

**Comment by V60GC** [comment]
Gerne bringe ich "die eigene Freude" zum Ausdruck, dass es so funktioniert, wie gewünscht. ;-)
Und ich bin auch gerne bereit noch an andere Stellen zum Ausdruck zu bringen, dass ich mir die Groundspeak-Webpage ohne dieses Skript kaum noch vorstellen kann. 
Denn ich gehöre nicht zu den Zeitgenossen, zu den vielzuviele Führungskräfte gehören, die der Meinung sind:

**Nicht geschimpft ist Lob genug.**

Also bitte, bitte, macht mit der Entwicklung des Skriptes weiter. Und ich hätte auch kein Problem ab und an mal nen Kaffee oder Bier zu spendieren.

**Comment by 2Abendsegler** [comment]
@V60GC
Danke für die liebe Nachricht! 😊
