### ISSUE TITLE
Incorrect navigation menu location on page upload trackable log image.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1347]
Incorrect navigation menu location on page upload trackable log image.

Example for me: https://www.geocaching.com/track/upload.aspx?LID=1129052613

![grafik](https://user-images.githubusercontent.com/22332216/82435779-17e66080-9a95-11ea-9115-e9980255c6f8.png)

**Comment by Ruko2010** [comment]
Same for me: Chrome and Mac

![image](https://user-images.githubusercontent.com/2239440/82436174-b07ce080-9a95-11ea-8c44-9a74e7990ed4.png)

**Comment by 2Abendsegler** [comment]
New:
![grafik](https://user-images.githubusercontent.com/22332216/84590667-cbdecf80-ae38-11ea-9c9e-586be06356b8.png)
