### ISSUE TITLE
"Photo file name" in "Copy Data to Clipboard" feature in cache listings use invalid characters.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1348]
"Photo file name" in "Copy Data to Clipboard" feature in cache listings use invalid characters.

![grafik](https://user-images.githubusercontent.com/22332216/82724768-ca5a3580-9cd8-11ea-96c5-4b26064e2e0b.png)

Für den Platzhalter `GCName` sollte eine Variante gebildet werden, die aus dem Cachenamen diejenigen Zeichen herausfiltert, die in Dateinamen nicht verwendet werden dürfen.

![grafik](https://user-images.githubusercontent.com/22332216/82724910-a0edd980-9cd9-11ea-8afa-2d5e90e155c5.png)

Folgende Zeichen sind betroffen unter Windows: `\/:*?"<>|`

@Ruko2010 
Gibt es beim Mac noch andere Zeichen die nicht erlaubt sind?
Weißt du wie das unter Linux aussieht?

**Comment by Ruko2010** [comment]
Ich glaube so einfach ist das nicht, da es nicht nur aufs OS sondern auch auf das Dateisystem ankommt. hier bei Wiki gibt es eine Tabelle, dort sollte alles aufgeführt sein:
https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations

**Comment by 2Abendsegler** [comment]
Ok, danke für die Info, werde ich mir genau ansehen. Bin nur mal kurz drüber geflogen. Gibts eigentlich noch Amigas oder Commodores in Betrieb ... jahahaha.

**Comment by 2Abendsegler** [comment]
Ich habe vor folgende Zeichen wie folgt zu ändern:

`"` wird zu `'`
`<` wird zu `(`
`>` wird zu `)`
`/\|:*?` wird entfernt

@Ruko2010, @capoaira: Macht das Sinn? Oder soll ich hier insbesondere die letzten Zeichen durch `-` oder durch etwas anderes ersetzen.

**Comment by capoaira** [comment]
Für den "Photo file name" macht es auf jeden Fall sinn. Ich würde die Zeichen glaube ich einfach löschen. Wenn man sich die aber einen copy data Eintrag macht um sich den Cache z.B. verlinkt als HTML ausgeben lassen will, ist es blöde, wenn die Zeichen entfernt werden...

**Comment by 2Abendsegler** [comment]
Das wird auf jedenfall nur für den "Photo file name" gemacht. Andere copy datas mit dem Namen werden nicht geändert.

Ja, ich kann auch alle nicht verwendbaren Zeichen entfernen. Das ist auch eine Option. Mal sehen was Ruko2010 sagt. :)

**Comment by Ruko2010** [comment]
Entfernen finde ich gut. Falls du sie aber ersetzen willst, dann lieber durch ein Leerzeichen.

**Comment by 2Abendsegler** [comment]
Hab die Zeichen entfernt. :)
