### ISSUE TITLE
[New Map] Wrong position of "size" area in detail screen of a cache on new map page.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1349]
Wrong position of "size" area in detail screen of a cache on new map page.
Ist schon falsch ohne Add-Ons. Die size Angabe gehört wieder oben in die Reihe.

![grafik](https://user-images.githubusercontent.com/22332216/82726271-275ae900-9ce3-11ea-89c4-2a2debac7302.png)

**Comment by Ruko2010** [comment]
Das ist aber nicht unser Bug, sondern einer von GS. der ist auch da, wenn man GClh aus macht. Die Frage ist, wollen wir es fixen, oder warten bis GS es selbst tut?

**Comment by 2Abendsegler** [comment]
Ja ich weiß. 
Ich dachte wir fixen es.
