### ISSUE TITLE
Logs shown twice with disabled VIP list

### ISSUE THREAD

**Issue by gcPhil** [2Abendsegler/GClh#1350]
Today i noticed that cache logs are displayed twice when I watch the listing with active GClh.

I use Firefox 76.0.1 with Tampermonkey 4.10.6112 and GClh 0.10.6

Screenshot attached:
![shot](https://user-images.githubusercontent.com/2893036/82798474-d977e980-9e78-11ea-840b-63a30708e571.png)

**Comment by gcPhil** [comment]
Ich habe den Fehler bei allen Cache-Listings, er fällt aber halt nur wirklich auf, wenn es erst wenige Logs gibt.
**Anbei meine Config-Datei, vielleicht hilft das beim reproduzieren des Problems.**
[2020_05_25_config.txt](https://github.com/2Abendsegler/GClh/files/4677114/2020_05_25_config.txt)

**Comment by 2Abendsegler** [comment]
@gcPhil: In den Config Daten stehen die Homekoordinaten. Die sollen hier nicht öffentlich gemacht werden. Ich habe die Datei zwischengespeichert auf meinem privaten Rechner.
@capoaira, @Ruko2010: Falls ihr die Datei möchtet, gebt bescheid, ich schick sie euch dann auf die GC Mail Adresse.

**Comment by 2Abendsegler** [comment]
@gcPhil:
1. Hast du Greasemonkey im Einsatz? 
1a. Falls ja, schau dort mal nach dem GClh, vielleicht ist er dort noch am Laufen, vermutlich in einer total veralteten Version. Hier und da gabs das schon.
1b. Falls nein, deaktiviere Greasemonkey mal und teste mal.
2. Außerdem kannst du auch mal nachschauen ob der GClh nicht zweifach unter Tampermonkey laüft. Scheinbar kann das passieren wenn man mal testweise selbst was über Tampermonkey entwickelt. Das ließ sich aber nicht abschließend klären. Schau einfach mal.
3. Deaktiviere mal alle Add-Ons und alle Scripte in allen Scriptmanagern, bis auf den GClh, und versuchs dann nochmal.

Wenn das nicht weiterhilft werde ich mal deine Config Datei aufspielen und dann mal schauen ob es daran liegt. Gib bescheid.

**Comment by 2Abendsegler** [comment]
Das Beispiel von gcPhil ist tatsächlich gut weil gut überschaubar: https://coord.info/GC8RCZV

@gcPhil: Noch ne Frage: Welches Betriebssystem?

**Comment by 2Abendsegler** [comment]
@capoaira: Hatte übersehen dass du ihn schon benannt hast. 😁  Gut, gut.

**Comment by capoaira** [comment]
Ich hatte mir die config datei schon aufgespielt und geguckt. Bei mir ist auch da alles normal.

**Comment by gcPhil** [comment]
- Die Homekoordinaten habe ich ausreichend grob eingestellt, aber trotzdem danke dass ihr auf sowas ein Auge habt!
1.  Kein Greasemonkey installiert
2.  beim klick auf Tempermonkey wird Gclh nur einmal angezeigt
3.  Alle anderen Scripts sind deaktiviert
- Betriebsystem Windows 10

- **Ich habe gerade das GClh Script gelöscht und neu installiert. Danach war mit den logs erstmal wieder alles OK. Nachdem ich meine Konfiguration wieder importiert habe ist das Problem nun wieder da.**

**Comment by gcPhil** [comment]
Ich konnte das Problem jetzt auf mehreren Rechnern/Accounts reproduzieren indem ich den Haken bei "Show VIP list" entferne.

**Comment by 2Abendsegler** [comment]
@gcPhil: Super rausgefunden. 

---
Es könnte damit zusammenhängen, dass wir die anfänglichen GS Logs nicht löschen. Das müsste man dann auch erkennen, weil das ja dann nur so etwa 30 Logs betrifft die doppelt sind. Das ist eine reine Vermutung. Man sollte also zuerst mal die Anzahl der doppelten Logs checken.
@Ruko2010: Hast du vielleicht Zeit dir das mal anzusehen? Ich bin noch ne Weile in Urlaub.

**Comment by 2Abendsegler** [comment]
@capoaira: Du kannst es dir natürlich auch gerne ansehen. Aber das ist womöglich nicht ganz ohne.

**Comment by Ruko2010** [comment]
Ich schau es mir heute Abend mal an.

**Comment by gcPhil** [comment]
Ich habe gerade mal nachgezählt: Wenn entsprechend viele Logs vorhanden sind werden bei mir 25davon angezeigt bevor beim runterscrollen nachgeladen wird. Sobald ich die Anzeige der VIP-Liste ausgeschaltet habe sind es dann entsprechend 2x die ersten 25. Sobald dann nachgeladen wird, sind die _weiteren_ Logs nicht doppelt, nur die ersten 25.

**Comment by 2Abendsegler** [comment]
Ja super, hört sich so an wie schon vermutet. Wenn keine VIPs angezeigt werden löschen wir die anfänglichen Logs von GS scheinbar nicht.

**Comment by Ruko2010** [comment]
Ich kann den Fehler nachstellen. Sobald die VIPs aus sind, sind die ersten Logs noch da. Ich investigiere 😃

**Comment by Ruko2010** [comment]
@2Abendsegler Ich habe das Problem gefunden. Ich hoffe ich kann es erklären.
Wenn man die VIP-Funktion in der Konfig aus macht, dann werden die Optionen "unten drunter" ausgegraut, können also nicht mehr geändert werden.
![GClh 1](https://user-images.githubusercontent.com/2239440/83338762-a940a880-a2c7-11ea-883b-3286ea8f50fc.gif)
Nun ist es aber so, dass die Optionen trotzdem noch aktiv sind. Zum Beispiel die VUP-Liste. 
Das Problem mit den Doppellogs ist dabei kein "Fehler" in der Logik, sondern dass das Script versucht die VUPs zu verarbeiten. Hierbei wird versucht die Funktion "gclh_build_vipvup" auszuführen, die es aber nicht gibt, da sie unter dem Punkt VIP (den wir ja gerade deaktiviert haben) definiert ist. Das Problem ist also, dass die Funktion nicht aufgerufen werden kann, was einen Javascriptfehler auslöst und somit die weitere Verarbeitung unterbindet.

Ich habe als Lösung nun ein Return in die Funktionen eingebaut, wenn die VIP Liste nicht verarbeitet wird.

@gcPhil Ich habe einen Pull Request mit dem Fix aufgemacht. Kannst du die Version mal bitte installieren und schauen ob es bei dir klappt? Dazu einfach auf folgenden Link klicken:
https://github.com/Ruko2010/GClh/raw/issue/1350-double-logs/gc_little_helper_II.user.js
Zur aktuellen Version kommst du mit diesem Link wieder zurück:
https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js


Ps.: @2Abendsegler Im Gif sieht man übrigens noch den Bug, dass die Option "Show reviewer/publisher in VIP list" nicht abhängig ist 😉. Ich erinnere mich, dass das meine Funktion war 😬. Den Bug hab ich gleich mit gefixt.

**Comment by 2Abendsegler** [comment]
@gcPhil
Die Änderungen stehen nun im Collector und können hier angewählt werden:
https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js
Schau bitte selbst nochmal drüber.

**Comment by gcPhil** [comment]
Ich konnte es gerade ausprobieren und mit der neuen Version von @Ruko2010 funktioniert nun alles wie es soll, keine doppelten Logs mehr!

Vielen Dank für die schnelle Fehlerbehebung!

Soll ich das Issue hier schließen oder macht ihr das lieber selbst? (Ich habe gerade nicht den Überblick ob die Änderungen schon in ein offizielles Update eingeflossen sind...)

**Comment by 2Abendsegler** [comment]
Ins offizielle Update kommt es erst in einigen Tagen. Du kannst aber schon mal damit arbeiten.
Wir warten für gewöhnlich einen Kommentar des Issue Öffnenden ab, bis wir das Issue schließen. Du hättest das aber auch machen dürfen.
Ich schließe dann jetzt.
