### ISSUE TITLE
[Dashboard] Create direct "Edit log"-links on the dashboard to make logs editable without an extra-step.

### ISSUE THREAD

**Issue by gcPhil** [2Abendsegler/GClh#1353]
Feature request:

Auf der "neuen" Dashboard-Seite (und bestimmt auch an anderen Stellen auf gc.com) kann man sich seine letzten Logs anzeigen lassen. Dazu wird auch jeweils ein "Edit log" Link angezeigt, der allerdings nur zur Seite des entsprechenden Logs führt, dort muss man noch einmal auf das Stift-Symbol klicken um sein Log wirklich zu bearbeiten. Es wäre praktisch wenn der Link entsprechend verändert werden könnte, so dass man gleich mit den Änderungen los legen kann.

Beispiel:
**Anzeige im Dashboard verweist auf:** https://coord.info/GL11GTZMR
**Beim aufrufen wird man dort weitergeleitet auf:** https://www.geocaching.com/seek/log.aspx?LUID=kryptischeKombination (ich bin gerade nicht sicher ob ich die URL gefahrlos posten kann oder ob sie personalisiert ist, deshalb habe ich die LUID ersetzt)
**Erst beim klick auf den Stift wird man weitergeleitet auf:** https://www.geocaching.com/seek/log.aspx?LUID=kryptischeKombination&edit=true

Es wäre toll wenn man direkt auf der URL mit "&edit=true" landen könnte.

**Comment by 2Abendsegler** [comment]
Ja, verstehe. Allerdings dient der erste Button auch dazu ins Log zu kommen um ein Bild hochzuladen, oder auch um das Log zu löschen. Wenn wir den Link nun wie gewünscht ändern, würde man immer in den Editmodus kommen. Wenn man die Zurücktaste verwenden würde wäre man wieder im Dashboard. Man müsste nun also einen Submit des Logs machen um an die andere Funktionalität zu kommen. Man macht also ein Submit obwohl man nichts ändern möchte und wählt dann Log löschen oder Bild hochladen. Das wäre unschön. 

Vermutlich sollten wir besser einen zusätzlichen Button integrieren, so dass wir einen View Log und einen Edit Log haben. Dann brauchen wir auch keinen config Parameter.

**Comment by gcPhil** [comment]
Den Vorschlag mit den zwei Links finde ich gut, an den Bildupload hatte ich in dem Moment gar nicht gedacht.
Vielleicht ganz kompakt nur **View** und **Edit**?

Wichtig ist natürlich, dass nur Links zu eigenen Logs entsprechend behandelt werden. Im Dashboard kann man ja auf Logs von Freunden anzeigen lassen, da muss es dann "View log page" bleiben.

**Comment by capoaira** [comment]
Die größte Herausforderung wird es, an die LUID zu kommmen. An das `coords.info/GLXXXXXX` ein `&edit=true` anzuhängen funktioniert leider nicht.

**Comment by 2Abendsegler** [comment]
@capoaira 
Willst du es trotzdem mal versuchen? 😁

**Comment by capoaira** [comment]
Ich würde es versuchen. Viele Ideen habe ich aber leider nicht.

**Comment by 2Abendsegler** [comment]
Super, dann Versuchs mal. Wenn's nicht klappt ist ja auch nicht schlimm. Ich trag dich mal ein.

**Comment by gcPhil** [comment]
Ich weiß nicht ob das hilft, aber auf der [alten Dashboard-Seite](https://www.geocaching.com/my/default.aspx) wurden noch alle Links zu den Logs mit der ausführlichen URL inkl. LUID angegeben.

**Comment by capoaira** [comment]
Meiner erst Versuch schlug wegen der CORS-Regeln fehl. Das mit dem altem Dashboard ist ein vielleicht keine schlechte Idee. Danke.
Jetzt muss ich aber nochmal raus und das gute Wetter nutzen 😊

**Comment by capoaira** [comment]
Moin,
entweder stelle ich mich ziemlich blöde an, oder es ist komplizierter als es aussieht.
Wenn ich die Logs aus dem altem Dashboard aufrufe, stellt sich die Seite automatisch auf das Alte. Rückgängig kann ich das nicht machen, da dies nicht per Link sondern per js gemacht wird... @2Abendsegler, @Ruko2010 hat einer von Euch eine Idee?
Dann hänge ich gerade auch beim abgleichen der Logs, da nicht alle Logs aus dem altem Dashboard auch im neuen gebraucht werden. Wie kann ich (unabhängig der Sprache) erkennen, welcher feed (Hides, Own, Community) gerade geöffnet ist?

**Comment by 2Abendsegler** [comment]
Ich glaub ich kann dir bei den Fragen im Moment nicht behilflich sein.

Ich wäre das Thema vermutlich etwas anders angegangen, nämlich so wie bei der Ermittlung der Favoriten Prozente. Ich hätte versucht das Javascript zu finden, mit dem GS die Funktionalität abbildet ...

Eigentlich ist das was wir vorhaben ne relativ kleine Verbesserung, wir müssen nicht Unmengen an Stunden reinhängen.

**Comment by gcPhil** [comment]
Mir ist das ganze jetzt auch nicht so wichtig, dass da tagelange Arbeit rein gesteckt werden muss obwohl es nicht so leicht ist wie gedacht.

**Comment by 2Abendsegler** [comment]
@capoaira 
Wie das mit den Fav Proz ermittelt wird ist doch zuerst mal egal. Bei meiner Idee ging es doch darum dass man sich ansieht wie GS es macht. Wenn wir also die Stelle finden, dann wissen wir ja schon wie es funktioniert. Ich glaube dieses Ajax Gedöhns wurde so von GS verwendet und wir haben es nur abgeschrieben. ;)

Ich weiss natürlich auch nicht ob dieser Weg besser ist. So etwas weiss man ja häufig nicht.

Ich dachte eigentlich das Lesen des alten Dashboards sollte gar nicht funktionieren weil für den User ja das neue Dashboard gewählt ist.

Ich habe auch nicht wirklich ne super Idee. Für so was ist üblicherweise Ruko2010 zuständig, der technisch ja viel versierter ist. :)

**Comment by capoaira** [comment]
Ich habe mir mal die Sourcecode von GS angesehen. In Zeile 1340 findet man folgendes:
```html
{{#if hasEditLink}}
    <a href="{{links.edit}}" class="edit-link">
        {{#if isYou}}
            Edit log
        {{else}}
            View log page
        {{/if}}
    </a>
{{/if}}
```

GS macht also keinen unterschied zwischen dem Link, sondern nur ob es ein eigener Log ist, oder nicht. Mit der Funktion `links.edit` bekommt man nur den Kurzlink.
Im Alten Dashboard habe ich leider kein Tamplate gefunden, aus dem man evt. auf eine Funktion schließen könnte, mit der man an den luid kommen könnte.
Ich habe diese ganze Tamplate-Sache aber auch noch nicht so richtig verstanden. Also vielleicht übersehe ich etwas ;)
Ich gebe dieses Thema gerne ab.

**Comment by 2Abendsegler** [comment]
Ok.
In welcher Datei hast du das Coding gefunden?

**Comment by capoaira** [comment]
Wenn man Strg+U drückt: view-source:https://www.geocaching.com/account/dashboard

**Comment by 2Abendsegler** [comment]
Ich habe auch keine Funktion gefunden, mit der wir aus dem CoordInfoLink eine Url mit LUID machen können. Ich glaube es ist so gedacht, dass der CoordInfoLink selbst die Umsetzung auf eine Url mit LUID macht, denn genau das passiert, wenn man den CoordInfoLink aufruft.

Folgendes liefert unter anderem eine Url mit LUID:
 ```
GM_xmlhttpRequest({
    method: "GET",
    url: "https://coord.info/GL123GG30",
    onload: function(response) {
        var urlMitLUID = response.finalUrl;
        ...
    }
});
```

Das nur zur Bildung von uns allen. 😃

Ich bin das Thema auch nur angegangen, weil es mir langsam stinkt, dass wir immer mehr Baustellen haben bei denen wir einfach nicht mehr weiter kommen, hauptsächlich dank dem ganzen asynchronen Mist von GS. Natürlich war der Aufwand für die eigentliche Sache nicht gerechtfertigt, ich will ihn auch gar nicht erst benennen. 😓 

Erfreuliche Spielergebnisse von Heute: 1 : 0 im Spiel 2Abendsegler gegen GS 🤣

Jetzt läuft das aber fast und wird vermutlich mit der nächsten Version kommen. 😉

**Comment by capoaira** [comment]
Stimmt. Das ist auch eine gute Idee👍🏻, aber sind das nicht zu viele abfragen, nur für den Link? Dann muss die Seite ja ziemlich viele Seiten laden...

**Comment by 2Abendsegler** [comment]
Pro eigenem Log ein Aufruf. Die Datenmenge ist relativ gering, nicht so wie bei einem Listing. Aber du hast schon recht. Hier wird es einen Parameter geben der deaktiviert ist. Wer ihn anschaltet sollte dann wissen was er tut.
Schönes WE.

**Comment by capoaira** [comment]
Ah ok. Das macht sinn👍🏻

**Comment by 2Abendsegler** [comment]
@capoaira, @gcPhil:
Die "Edit log"-links sind eingebaut. Ich kann allerdings nicht alles testen, weil meine Community gerade nicht cachen geht. Könnt ihr das bitte testen?

[Hier](https://github.com/2Abendsegler/GClh/raw/77853f52e1cbc185d2203c8f7feea23b05371104/gc_little_helper_II.user.js) geht es zur Version mit den Änderungen.
[Hier](https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_edit_links_for_logs) geht es zum Parameter 'Show edit links for your own logs' im Config, der aktiviert werden muss.
[Hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) geht es zurück zur aktuellen Version.

**Comment by gcPhil** [comment]
> @capoaira, @gcPhil:
> Die "Edit log"-links sind eingebaut. Ich kann allerdings nicht alles testen, weil meine Community gerade nicht cachen geht. Könnt ihr das bitte testen?
> 
> [Hier](https://github.com/2Abendsegler/GClh/raw/77853f52e1cbc185d2203c8f7feea23b05371104/gc_little_helper_II.user.js) geht es zur Version mit den Änderungen.
> [Hier](https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_edit_links_for_logs) geht es zum Parameter 'Show edit links for your own logs' im Config, der aktiviert werden muss.
> [Hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) geht es zurück zur aktuellen Version.

Das klingt gut! Ich bin gerade unterwegs und habe leider erst in einer Woche wieder einen Laptop mit tempermonkey zur Hand aber dann kann ich die Funktion natürlich gern ausgiebig testen.

**Comment by capoaira** [comment]
👍🏻
Auch ich  habe gerade keine Möglichkeit vernünftigt zu testen.
Samstagabend/Sonntag habe ich wieder ein PC mit Tampermonky und gclh

**Comment by gcPhil** [comment]
**Vielen Dank an @2Abendsegler für die viele Arbeit an dieser Funktion!**

Ich konnte das ganze nun testen und die Funktion funktioniert grundsätzlich gut.

Es scheint nach dem Aufrufen des Dashboards manchmal ein paar Sekunden zu dauern bis auch die geänderten "Edit log/View log" Links angezeigt werden. Der Austausch geschieht dann aber "automatisch" ohne weiteres Zutun.

(Vermutlich nur) nach dem Wechsel der Ansicht (von _Owner_ oder _Community_ zu _Your Hides_) hatte ich ein paar Versuche bei denen es beim unveränderten Link blieb, hier half nur ein neu-laden der Seite. Ich kann aber leider nicht zuverlässig reproduzieren wann genau das auftritt und wann nicht.

**Comment by 2Abendsegler** [comment]
@gcPhil
Mir ist das Gleiche auch schon passiert. Ich glaube es hängt damit zusammen dass man "zu" schnell zwischen den beiden Ansichten hin und her schaltet. Ich konnte es aber auch nicht weiter eingrenzen.

Besonders wenn die Geocaching Seiten langsam sind weil gerade viele User unterwegs sind, ist auch das Nachladen der Logs entsprechend langsam. Und je mehr Logs vorhanden sind, desto mehr müssen geladen werden. Das kann schon mal 2, 3 Sekunden dauern. Da hast du recht.

Im Moment ist es außerdem so, dass alle eigenen Logs auf einmal geladen werden. Besser wäre es, wenn zuerst nur die neueren Logs geladen werden, dann sind diese Ergebnisse schneller da. Und die neueren Logs kommen vermutlich eher für Edits in Frage. 
Das werde ich mir noch überlegen.

Ich werde zuerst mal noch warten bis @capoaira mir noch mal Feedback gibt, scheinbar funktioniert es bei ihm gar nicht.

**Comment by gcPhil** [comment]
@2Abendsegler
Im Dashboard wird ja glaube ich eh nur ein gewisser Zeitraum an Logs gezeigt, für links auf dieser Seite bräuchte man also keine wesentlich älteren Daten laden (falls ich es richtig verstanden habe und das momentan so gemacht wird).

Ich will jetzt auf keinen Fall, dass du die Funktion noch einmal komplett umkrempeln musst, aber ich hatte gerade noch einen Gedanken dazu, der vielleicht hilft: ist es vielleicht irgendwie möglich Links anzuzeigen ohne alle Daten vorher zu laden? Also ein unsichtbarer Zwischenschritt, so dass das entgültige Ziel erst ermittelt wird wenn man auch auf den Link klickt (und somit nur ein Datensatz statt alle auf einmal geladen werden muss).

**Comment by 2Abendsegler** [comment]
@gcPhil 
Wir laden nur diejenigen eigenen Logs, die auch im Dashboard angezeigt werden, keine älteren.

Eigentlich eine gute Idee mit dem unsichtbaren Schritt. Ich hatte es schon mal ausprobiert. Das war ziemlich blöd, weil aufgrund des Klicks zuerst mal nichts geschah, man also schon geneigt war nochmal und nochmal drauf zu klicken. Wir können ja quasi noch nichts machen, bis wir den Link besorgt haben, und so lange steht dann alles still. Das ging also nicht.

**Comment by capoaira** [comment]
> Hast du die Sache im Config angeschaltet?

Ja, habe ich

> Hast du viele Logs im Dashboard stehen?

Ja, bei mir sind eigene Logs, bei den eigenen logs sind es nicht ganz so viele.

> Das kann schon mal 2, 3 Sekunden dauern. Da hast du recht.

Daran könnte es bei mir liegen. Da ich noch im Urlaub bin, habe ich meinen Hotspot genutzt, der ist natürlich nicht so schnell wie WLAN, aber einige sekunden habe ich immer gewartet.

**Comment by 2Abendsegler** [comment]
Wenn du wieder zu Hause bist, dann kannst du ja noch mal testen. Und falls es dann nicht funktioniert, mal die Add ons abschalten.

**Comment by gcPhil** [comment]
> Eigentlich eine gute Idee mit dem unsichtbaren Schritt. Ich hatte es schon mal ausprobiert. Das war ziemlich blöd, weil aufgrund des Klicks zuerst mal nichts geschah, man also schon geneigt war nochmal und nochmal drauf zu klicken. Wir können ja quasi noch nichts machen, bis wir den Link besorgt haben, und so lange steht dann alles still. Das ging also nicht.

Kann man nicht stattdessen so lange eine weiße Seite anzeigen? Oder eine eine mit dem Wort "Weiterleitung..." oder einer kleinen kreiselnden Grafik?

**Comment by 2Abendsegler** [comment]
Doch, man könnte eine kreiselnde Grafik anzeigen. Und man würde damit vermutlich länger warten müssen als man Zeit für die zwei Klicks benötigen würde. 

Ich glaube wir machen uns jetzt zu viele Gedanken. Die Praxis sieht doch häufig so aus, dass man im Dashboard ist, dort liest und dann einen Fehler sieht den man berichtigen möchte. Und bis dahin sollten die Links doch vorhanden sein.

**Comment by gcPhil** [comment]
👍

**Comment by Ruko2010** [comment]
Ich habe den Branch auch mal getestet. Bei mir klappt alles. Am Anfang ging es nicht, aber ich hatte in meinem Development-Script (Stub) vergessen den neuen Connect
`// @connect          coord.info`
hinzuzufügen. Ich hab  aber auch den Fehler in der Console bekommen, dass er nicht auf coord.info zugreifen kann.

Bei mir werden nun die Links eingefügt. Sieht für mich also gut aus.

**Comment by 2Abendsegler** [comment]
Bitte noch nicht mergen, ich werde noch etwas anpassen.

@Ruko2010 
Danke für die Rückmeldung.

@capoaira 
Kann es nicht sein dass bei dir auch noch das connect fehlt.

**Comment by 2Abendsegler** [comment]
@capoaira
Kann es nicht sein dass bei dir auch noch das connect fehlt, du arbeitest doch auch wie Ruko2010 mit einem Development-Script, oder?

(Off-Topic: Da gabs ne kleine Überschneidung. Finde ich echt gut, dass du auch bei solchen Dingen cool mitmachst. 😄)

**Comment by capoaira** [comment]
Wie meinst du Developer Script? Ich nutze immer den collector, bzw zum testen den jeweiligen Branch (gc_little_helper_II.user.js und dann auf den link raw). Damit aktualisiert sich das dann in Tampermonkey. 
Das connect steht bei mir drin. Im Script und auch bei Tampermonkey unter `XHR-Sicherheit`


> (Off-Topic: Da gabs ne kleine Überschneidung. Finde ich echt gut, dass du auch bei solchen Dingen cool mitmachst. 😄)

Danke 😊

**Comment by 2Abendsegler** [comment]
Ich dachte du entwickelst auch über ein externes Tool, so wie Ruko2010. Dort kann man den Bereich `==UserScript== ... ==/UserScript==` aus dem Script gesondert definieren. Testet man dann über dieses Tool, fehlen Neuerungen aus diesem Bereich. 
So zumindest mein Verständnis.

Wenn du das Script aus dem PR in Tampermonkey installiert hattest und auch darüber testest, dann ist ein fehlendes connect  wohl nicht das Problem.

Ich habe ja nur keine Ahnung warum es bei dir nicht funktioniert, und ich habe auch keine Ideen mehr. So können wir es halt nicht an die User geben, wenn scheinbar bei uns schon etwas nicht funktioniert. 😕

Kannst du nicht vielleicht versuchen rauszubekommen woran es hängt?

**Comment by capoaira** [comment]
Interessant mit der Dev Skript.... das muss ich auch mal ausprobieren. 
Ich versuche es heute nach der Schule oder Samstag etwas zu debuggen um zu gucken wo es bei mir hakt.
Ich jabe das schonmal verschucht, da wurde es nicht eingefügt, alles andere hat funktioniert.

**Comment by 2Abendsegler** [comment]
Ok, super!

**Comment by capoaira** [comment]
So, ich habe endlich mal die Ruhe und Motivation gefunden und habe etwas rum probiert. Folgendes: Ich klicke um den ganzen Log zu sehen nie auf "More" sondern auf den Text, der EventListener ist aber nur auf dem More Button.
Wenn ich in Zeile 7868 (aktueller collector)
```javascript
$(log).find('.expand-activity')[0].addEventListener("click", function(){buildLinksWaitAF($(this).closest('.activity-item'), 0);}, false); 
```
das `.find('.expand-activity')` weglasse funktioniert es auch bei mir. Also

```javascript
$(log)[0].addEventListener("click", function(){buildLinksWaitAF($(this).closest('.activity-item'), 0);}, false);
```

**Comment by 2Abendsegler** [comment]
@capoaira: Super!

**Comment by 2Abendsegler** [comment]
Schwere Geburt!
merged

**Comment by gcPhil** [comment]
Ich habe gerade festgestellt, dass die neuen "Edit Log" links schon nicht mehr funktionieren. Ich bin mir nicht sicher ob GS hier mal wieder etwas dauerhaft geändert hat, oder ob es nur vorübergehend nicht funktioniert. Ich fürchte aber ersteres.

**Unsere "Edit Log" Links sind im Format:** https://www.geocaching.com/seek/log.aspx?code=GL12NVZ7F&edit=true - Damit erreicht man zwar das Log, kann es aber (auch nach nochmaligem Klick auf den Stift) nicht bearbeiten.
**Groundspeaks Links im Listing haben nun dieses Format:** https://www.geocaching.com/seek/log.aspx?LUID=c3e0c3cb-63e2-4e4f-ac18-41445f4118e2&edit=true - Damit kann man eigene Logs bearbeiten

**Comment by capoaira** [comment]
Hier hat GS eindeutig etwas geändert. Vorher hatten wir das richtige Format. 
Die neue Form `?code=` + kurzen Code, scheint wohl Standard zu werden. Auch im Profil haben sie das versucht, da allerdings noch mit einem erheblichen Bug, sodass es rückgänig gemacht wurde....

**Comment by capoaira** [comment]
Gerade mal getestet, GS hat den selben Bug. Wenn du auf den Link mit `code=GL...` klickst, und dann auf den Bearbeiten-Stift, kannst du den Log nicht bearbeiten...
Habe den Bug gleich mal bei GS gemeldet: https://forums.geocaching.com/GC/index.php?/topic/358548-edit-log-button-doesnt-work/
Mal sehen, wie sie den Bug fixen...

**Comment by 2Abendsegler** [comment]
GS hats angepasst. Es funktioniert wieder, auch wenn wir nicht mehr mit LUID arbeiten. 

@gcPhil
Wenns auch bei dir klappt, dann kannst du das Issue schließen, wenn du möchtest.

**Comment by 2Abendsegler** [comment]
Ich schließ das Issue hier. 
Zur Code Vereinfachung und damit dem Verzicht aufs Nachlesen gibt es ein neues Issue #1465.
Edit Button bei Trackable Logs funktioniert im Standard noch nicht. Dazu hatte ich die Meldung bei GS erweitert.
