### ISSUE TITLE
Submitting new log with F2 don't work

### ISSUE THREAD

**Issue by gcPhil** [2Abendsegler/GClh#1355]
Wenn ich die GClh Settings nicht falsch verstehe sollte es möglich sein einen geschriebenen Log-Text per Tastendruck F2 abzusenden. Das funktioniert bei mir aber leider nicht.

System: Windows 10 pro 64bit, Firefox 76.0.1 mit Tampermonkey 4.10.6112 und GClh 0.10.6

**Comment by 2Abendsegler** [comment]
Siehst du denn das F2 im Button?

**Comment by gcPhil** [comment]
Nein, das sehe ich auf der Seite nicht. An anderen Stellen (z.B. GClh Settings) sehe ich die F2 Beschriftung und dort funktioniert es auch. Aber nicht auf der Seite zum loggen, dort steht nur "Post".

**Comment by 2Abendsegler** [comment]
Im neuen Log Formular funktioniert das auch nicht.

**Comment by gcPhil** [comment]
Also kein Bug, sondern eine bekannte Einschränkung.

**Comment by 2Abendsegler** [comment]
Im Config ist der F2 Parameter unter "old logging page only" aufgelistet. Insofern ist es kein Bug. Wir hatten es mal versucht im Neuen Formular zu bauen, lief aber nicht stabil.
Ich mach dann mal zu hier.
