### ISSUE TITLE
Founds on new map

### ISSUE THREAD

**Issue by anvanlaer** [2Abendsegler/GClh#1369]
Hi,

For the old map, you have a setting to hide found/own caches by default.  On the new map you don't have that setting.  Is it an idea to implement that also? 

Thanks for all your great work!

**Comment by 2Abendsegler** [comment]
Hi, 
wir haben bereits ein issue zu diesem thema. It is #1304.
Wir haben auch bereits einiges versucht, aber bisher haben wir die Dinge noch nicht zum Laufen gebracht.
I close this issue and refer between the issues.

**Comment by 2Abendsegler** [comment]
Hi,
we already have an issue on this topic. #1304
We have already tried a lot, but so far we have not got things going.
I close this issue and refer between the issues.

**Comment by anvanlaer** [comment]
sorry i didn't see that there was a topic yet.  Ill turn on the notifications on that one, so i can keep track of the progress.
And i'm sure you guys will find a way.
