### ISSUE TITLE
Unpublished caches in new dashboard have disappeared

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1371]
**Describe the bug**
Unpublished caches in new dashboard have disappeared

**To Reproduce**
1. Go to 'https://www.geocaching.com/account/dashboard.'
2. See under Calender

**Expected behavior**
The unpublished caches should be there

**Screenshots**

**Additional context**
The page for unpublished caches has changed. That's the reason for the bug.

**Comment by capoaira** [comment]
Ich habe in einem ersten Schritt die Sortierfunktion auf der (alten) Seite für unveröffentlichte Caches entfernt, da die Seite ersetzt wurde. Müssen die Parameter dann auch aus `config_standard.txt` entfernt werden?

Ich habe versucht die unveröffentlichten wieder im Dashboard einzublenden, doch ohne Erfolg. Bei der neuen Seite der unveröffentlichten werden die Caches erst nach dem laden der Seite geladen. Wenn ich `$.get()` nutze bekomme ich sozusagen ein leere Seite.

**Comment by 2Abendsegler** [comment]
> Müssen die Parameter dann auch aus `config_standard.txt` entfernt werden?
Ja.

> Bei der neuen Seite der unveröffentlichten werden die Caches erst nach dem laden der Seite geladen.
Das scheint ja die Regel zu werden, dass die Dinge asynchron geladen werden, echt doof. 
Hier kann ich nichts beisteuern, habe ja noch keine Caches und auch noch keine in Planung. 😮

Ich habe das Issue mal an dich assigned und den Status in progress gesetzt. Können wir ja wieder ändern, wenn sich was ändern sollte.

**Comment by capoaira** [comment]
Hier komme ich nicht weiter, ich habe keine Idee, wie ich Daten von einer asynchronen Seite bekommen soll. Hat einer von Euch eine Idee?

**Comment by 2Abendsegler** [comment]
Hab keine Idee. Und ausprobieren kann ich ja zuerst mal nichts. Ruko2010 ist vermutlich im Moment nicht greifbar.

**Comment by 2Abendsegler** [comment]
@capoaira 
Mir ist eine Möglichkeit eingefallen, glaube ich. Ich weiß nicht ob wir sie nutzen sollten, aber es ist zumindest theoretisch eine Möglichkeit. 

Kennst du die Funktionalität [Log cache from listing (inline)](https://www.geocaching.com/my/#GClhShowConfig#a#settings_log_inline), gegebenenfalls das Teil aktivieren. Danach findest du im Cache Listing etwas oberhalb der Additional Waypoints folgenden Button:
![Unbenannt](https://user-images.githubusercontent.com/22332216/90319544-72c71100-df39-11ea-9f46-52c3a3df9f42.jpg)
Damit wird im Listing das Logformular quasi in einem Screen im Screen aufgebaut. 

Für dein Problem muss der Screen im Screen dann ausgeblendet werden. Die benötigten Daten sollten dann in diesem Screen im Screen geladen werden.

**Comment by capoaira** [comment]
Das klingt nach einer guten Idee. Ab heute habe ich wieder ein Laptop mit Github und gclh, sowie fließend Strom :). Ich werde mich die Tage dran setzten.

**Comment by capoaira** [comment]
Das war ein super Tipp, so klappt es.
Ich habe das ganze als eine generelle function `getAsynData()` zusammengefasst, falls man so etwas nochmal benötigt.

**Comment by 2Abendsegler** [comment]
Ich hab mir das auch noch mal angesehen, weil ich in Erinnerung hatte dass das Laden im Dashboard ziemlich lange dauert. Das ist auch immer noch so. Wenn ich mir das auf der Originalseite ansehe dann wird mein Cache so etwa in einer Sekunde angezeigt. Im Dashboard dauert es etwa 9 bis 10 Sekunden. 
Gibt es dafür eine Erklärung?

**Comment by capoaira** [comment]
Ja, nach den Caches werden Events gesucht, wenn es aber keine gibt, dauert es die default Zeit der getAsynData() function.
Ich könnte vielleicht noch ein Abfrage einbauen, dass wenn die Anzahl der Caches mit der Anzahl der unpublished hides übereinstimmt, keine Events mehr abgefragt werden. Wenn man dann allerdings nur Events und keine Caches hat, dauert es wieder so lange.

**Comment by 2Abendsegler** [comment]
Mittlerweile scheint das anders zu laufen. Wenn keine Events vorhanden sind, dann wird die Seite mit den Caches angezeigt. Vermutlich ist das bei den Caches auch so, falls nur Events vorhanden sind. 

Wenn es weder Caches noch Events gibt, dann könnte es so sein wie du schreibst. Oder fängst du das schon ab?

Ich habe nur einen Cache und keine Events.

Im Moment sieht es so aus, dass ich etwa 6 Sekunden im waitForContent auf die Caches warte. Anschließend warte ich 4 Sekunden im waitForContent auf die Events. 

Ich verstehe nicht warum es 6 Sekunden dauert, wo es auch der Seite wenn ich sie direkt anwähle gefühlt nur eine Sekunde dauert. Und das scheint immer etwa so lange zu dauern. Hab zahlreiche Tests gemacht. Das ist dubios. Und es ist auch ziemlich lange.

**Comment by 2Abendsegler** [comment]
Naja, es dauert auch 3-4 Sekunden wenn ich die Seite direkt anwähle, bis die Seite komplett aufgebaut ist.

Lass gut sein. Alles ok.

**Comment by 2Abendsegler** [comment]
Kannst du bitte noch ein Bild rein hängen fürs Changelog. Und dann kannst du das Issue schließen.

**Comment by capoaira** [comment]
> Wenn es weder Caches noch Events gibt, dann könnte es so sein wie du schreibst. Oder fängst du das schon ab?

Jip, das fange ich bereits ab.


> Mittlerweile scheint das anders zu laufen. Wenn keine Events vorhanden sind, dann wird die Seite mit den Caches angezeigt. Vermutlich ist das bei den Caches auch so, falls nur Events vorhanden sind.

Stimmt, das ist so und wird abgefangen. Eigentlich könnte ich das aber auch nutzen um die Wartezeit zu verringern. 


Ich mache nochmal die Änderungen und stelle dann einen PR. Das Bild für den changelog kommt dann auch. 
Ich weiß nicht ob ich das morgen schaffe, aber Samstag sollte ich Zeit finden.

**Comment by capoaira** [comment]
So, ich habe nochmal ein PR mit kleinen Änderungen gemacht.

Bild für den Changelog
![grafik](https://user-images.githubusercontent.com/50927164/92950015-4d57f500-f45c-11ea-88c9-9d0c0e7c70e9.png)
