### ISSUE TITLE
[Owner Dashboard] Build VIP, VUP, Mail icons

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1372]
Build VIP, VUP, Mail icons for the users.

**Comment by capoaira** [comment]
Ich versuche mich mal hier dran. Gibt es etwas wichtiges zu beachten?

**Comment by 2Abendsegler** [comment]
Nimm dir eine Beispielseite die schon funktioniert und orientiere dich daran. Vielleicht das Public Profile. 
Hier werden die VIP Icons im Public Profile gesetzt.
`} else if (is_page("publicProfile") && $('#ctl00_ContentBody_ProfilePanel1_lblMemberName,`

Hier werden die Mail-, und Message Icons gesetzt:
`// Show eMail and Message Center Link beside user.`

**Comment by capoaira** [comment]
Super, danke

**Comment by 2Abendsegler** [comment]
@capoaira, @Ruko2010 
Hab noch zwei Kleinigkeiten und möchte fragen ob wir die Anpassungen noch machen wollen?

1. Anstatt dem blau unterlegten bleibt nun der grüne Rand stehen, wenn man auf den VIP oder VUP Button drückt. Schöner wäre es ohne grünen Rand.
![grafik](https://user-images.githubusercontent.com/22332216/100092874-0e302200-2e57-11eb-882f-7e9418cb0488.png)

2. Wir geben normalerweise bei der Mail neben dem Cachername noch weitere Informationen mit um gegebenenfalls weitere Platzhalter im Mail Formular zu ersetzen. So zum Beispiel GC Code und GC Name. Damit kann man dann in der Mail auf den Cache verweisen um den es geht. Das könnte dann wie folgt aussehen mit GC Name und GC Link.
![grafik](https://user-images.githubusercontent.com/22332216/100094301-17ba8980-2e59-11eb-9589-db5bb0a6f27a.png)

---
Off Topic: Wir haben jetzt auch unseren ersten Cache. 😁

**Comment by capoaira** [comment]
1. Finde ich an sich gut. Diese hässlichen Ränder hat allerdings jeder Link/Button. Deswegen hatte ich ihn drin gelassen.
2. Das kann ich gerne noch erweitern.

Off-topic: cool wie ist der gccode?

**Comment by 2Abendsegler** [comment]
[MTB - Rundstrecke Lindenfels, Li1 (17 km)](https://coord.info/GC8ZB5F) 😁

**Comment by capoaira** [comment]
> Off-topic: [MTB - Rundstrecke Lindenfels, Li1 (17 km)](https://coord.info/GC8ZB5F) 😁

Sich nach einem interessanten Multi aus👍🏻
Schade, dass ich soweit weg wohne...

**Comment by Ruko2010** [comment]
Ich würde auch 1 und 2 umsetzen.

**Comment by 2Abendsegler** [comment]
@capoaira 
Es gibt noch einen weiteren Punkt den wir berücksichtigen sollten.

3. Wenn die VIPs deaktiviert sind, parameter "settings_show_vip_list", dann ist Function "gclh_build_vipvupmail" nicht erreichbar. Üblicherweise wird das alles im VIP ... Block abgehandelt und dort kommt es in diesen Fällen schon gar nicht zu einem Aufruf der Funktion. Da es hier aber ausgelagert wurde wird die Funktion aufgerufen und verursacht einen Fehler:
![grafik](https://user-images.githubusercontent.com/22332216/100177440-5b9da500-2ed2-11eb-83fd-5be4373764dc.png)
Vor dem Aufruf der Funktion muss also auf den Parameter geprüft werden.

**Comment by capoaira** [comment]
Bei Nummer 2 habe ich keine Idee wie ich das umsetzen soll. Ich habe kein vergleichbares Beispiel gefunden, bei dem ich abkupfern könnte, wie man die Namen/GCcodes/Links von mehreren Caches einsetzten könnte. Bis jetzt sind alle Fälle so, dass diese Angabe klar ist. Hier benötigt man aber für jeden Button einen anderen Namen/GCCode/Link

**Comment by 2Abendsegler** [comment]
Das verstehe ich nicht. Pro Button gibt es doch genau einen Namen ... . Wir wollen ja gar nicht mehrere Caches in einem Button abhandeln. Oder verstehe ich hier etwas falsch?

**Comment by capoaira** [comment]
Klar, aber bis jetzt hat sich der Cache Name nie unterschieden, egal wie viele Buttons es gibt. Jetzt gibt es auf einer Seite mehrere Buttons, die jeweils unterschiedliche Cachenamen haben.

**Comment by 2Abendsegler** [comment]
Achso, ja, ich glaube ich verstehe. 

Ich hoffe ich hab jetzt auf die Schnelle nichts übersehen und das funktioniert.

In `function gclh_vipvupmail` wird für die Mail irgendwann `function buildSendTemplate` aufgerufen. Dort werden die Platzhalter aus globalen Variablen ersetzt und das Template für die Mail zusammengebaut. Wenn du also pro zu erzeugendem Mail Button die globalen Variablen füllst, dann sollte das funktionieren.

Hier sind die globalen Variablen ersichtlich:
```
        tpl = tpl.replace(/#Found#/ig, global_founds+1).replace(/#Found_no#/ig, global_founds).replace(/#Me#/ig, global_activ_username);
        tpl = tpl.replace(/#Date#/ig, global_date).replace(/#Time#/ig, global_time).replace(/#DateTime#/ig, global_dateTime);
        tpl = tpl.replace(/#GCTBName#/ig, global_name).replace(/#GCTBCode#/ig, global_code).replace(/#GCTBLink#/ig, global_link);
```
Du must also vor der `function gclh_vipvupmail` beispielsweise den Namen des Caches in die globale Variable `global_name` setzen.

**Comment by Ruko2010** [comment]
@capoaira Der Button sollte ja irgendwo in Relation zum Cache irgendwo in der "Nähe" sein. Da kann man den Cachenamen und ähnliches eigentlich über jQuery und die "find" Funktion die passenden Daten herausfinden können, oder?

**Comment by capoaira** [comment]
@2Abendsegler, die Globalen Variabel zu füllen ist ne gute Idee, das werde ich gleich mal ausprobieren. 
@Ruko2010 An die Daten zu kommen ist nicht schwer. Das übergeben ist komplizierter.

**Comment by capoaira** [comment]
Hat funktionert 👍

**Comment by 2Abendsegler** [comment]
Merged
Changelog maintained
