### ISSUE TITLE
add "Go to ..." to al maps

### ISSUE THREAD

**Issue by hakuchi** [2Abendsegler/GClh#1373]
On `geocaching.com/map` is no "Go to ..." option
Can there be added also the "Go to ..." OSM, Flopp's, etc. as on `geocaching.com/play/map/`

If not, the link from Google Maps to the Geocaching map should be changet to `geocaching.com/play/map/`

**Comment by 2Abendsegler** [comment]
Hi,

but we have the "Go to ..." button on both maps.

Old Map:
![old map](https://user-images.githubusercontent.com/22332216/86998225-37099080-c1b0-11ea-9e70-c47abdfef334.JPG)

New Map:
![new map](https://user-images.githubusercontent.com/22332216/86998243-412b8f00-c1b0-11ea-9d73-03b38de604ac.JPG)

If you can not see the button on old map, like you wrote, then please tell us your operating system, browser and the version of the GClh. Then we try to reproduce a possible error.

**Comment by 2Abendsegler** [comment]
#1374

**Comment by hakuchi** [comment]
Sorry ... My fault ...
I have missed to switch in the "Map Preferences" from Google to Leaflet.

Now it is all present and works perfect!

**Comment by 2Abendsegler** [comment]
No problem.
Thank you for this information. 
I will close the issue.
