### ISSUE TITLE
[Owner Dashboard] Add links to cachetypes.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1377]
![grafik](https://user-images.githubusercontent.com/50927164/87245754-4c005100-c448-11ea-8612-e02f8ec6ec3a.png)
Add a link to the cache types as in the public profile
https://www.geocaching.com/p/default.aspx?tab=geocaches#profilepanel

**Comment by capoaira** [comment]
Am besten kann man wohl den Cachetyp wohl über das `aria-label` ermitteln:
Diese kenne ich:
```
Traditional Cache    => tx=32bc9333-5e52-4957-b0f6-5a2c8fc7b257
Multi-Cache          => tx=a5f6d0ad-d2f2-4011-8c14-940a9ebf3c74
Virtual Cache        => tx=294d4360-ac86-4c83-84dd-8113ef678d7e
Letterbox Cache      => tx=4bdd8fb2-d7bc-453f-a9c5-968563b15d24
Mystery Cache        => tx=40861821-1835-4e11-b666-8d41064d03fe
Wherigo Cache        => tx=0544fa55-772d-4e5c-96a9-36a51ebcf5c9
Event Cache          => tx=69eb8534-b718-4b35-ae3c-a856a55b0874
```
Der Link zur Liste ist so Aufgebaut: https://www.geocaching.com/seek/nearest.aspx?tx=[Cachetyp]&u=[ich]

Folgende habe ich nicht:

- Lab Cache
- Community Celebration Event
- Cito Event
- Earth Cache
- Webcam Cache

Habe ich Cachetypen vergessen, die noch versteckt werden können?

@Ruko2010 Du hast doch ein Cito-Event und Labcaches. Kannst du mal nach gucken, wie das `aria-label` für die Cachetypen heißt

**Comment by AndyPuma** [comment]
lt:
https://west468.wordpress.com/2006/03/22/gc-klug-suchen-nach-geocaching-seiten-2/


   - Traditional:
   tx=32bc9333-5e52-4957-b0f6-5a2c8fc7b257
   - Multi:
   tx=a5f6d0ad-d2f2-4011-8c14-940a9ebf3c74
   - Mystery:
   tx=40861821-1835-4e11-b666-8d41064d03fe
   - Letterbox Hybrid
   <https://west468.wordpress.com/2005/12/15/gc-letterbox-hybrid-caches-verkappte-traditionals/>
   :
   tx=4bdd8fb2-d7bc-453f-a9c5-968563b15d24
   - Event:
   tx=69eb8534-b718-4b35-ae3c-a856a55b0874
   - Mega-Event
   <https://west468.wordpress.com/2006/05/27/gc-neuer-cachetyp-mega-event/>:
   tx=69eb8535-b718-4b35-ae3c-a856a55b0874
   - CITO
   <https://west468.wordpress.com/2006/02/21/cache-in-trash-out-events-cito/>
   :
   tx=57150806-bc1a-42d6-9cf0-538d171a2d22
   - Virtual:
   tx=294d4360-ac86-4c83-84dd-8113ef678d7e
   - Earthcache:
   tx=c66f5cf3-9523-4549-b8dd-759cd2f18db8
   - Webcam:
   tx=31d2ae3c-c358-4b5f-8dcd-2185bf472d3d
   - Reverse
   <https://west468.wordpress.com/2006/01/04/gc-reverse-locationless-caches-alle-archiviert/>
   :
   tx=8F6DD7BC-FF39-4997-BD2E-225A0D2ADF9D
   - APE:
   tx=2555690d-b2bc-4b55-b5ac-0cb704c0b768


Am So., 12. Juli 2020 um 18:36 Uhr schrieb capoaira <
notifications@github.com>:

**Comment by Ruko2010** [comment]
> @Ruko2010 Du hast doch ein Cito-Event und Labcaches. Kannst du mal nach gucken, wie das `aria-label` für die Cachetypen heißt

Ich steh grad total auf dem Schlauch. Wo finde ich denn das aria-label des Cachetyps?

**Comment by capoaira** [comment]
Oh, das habe ich vergessen. Sorry.
Im CO Dashboard in den `li` tags.

**Comment by Ruko2010** [comment]
Hmm, da hatte ich geschaut, da ist bei mir nix drin, nur die Namen:
![image](https://user-images.githubusercontent.com/2239440/87296432-0787ba80-c507-11ea-9b7e-ad9cd7ebd8e9.png)

**Comment by capoaira** [comment]
Achso, ich meinte direkt in dem Tag also `<li aria-lable="xxx">`
Steht im Screenshot: Cito ist also `CITO Event` und Lab ist `Lab Cache`

**Comment by capoaira** [comment]
Gibt es für eigene Labs einen Link? Da klappt es ja nicht mit `tx=...`

**Comment by capoaira** [comment]
> Gibt es für eigene Labs einen Link? Da klappt es ja nicht mit `tx=...`

@Ruko2010 hier bräuchte ich kurz dein Wissen ;)

**Comment by Ruko2010** [comment]
@capoaira hast du den Link gefunden? Die Labs werden ja über eine extra Seite verwaltet. Ich glaube auf der Seite von GS gibt es keine Übersicht über die eigenen Labs.

**Comment by Ruko2010** [comment]
Es gibt einen Link, aber der führt nur Extern zu: https://labs.geocaching.com/

![image](https://user-images.githubusercontent.com/2239440/91052707-1e4f2000-e622-11ea-9899-34770ecfbdc8.png)

**Comment by capoaira** [comment]
Jip, nutze den Link https://labs.geocaching.com/builder/adventures.

**Comment by 2Abendsegler** [comment]
merged
