### ISSUE TITLE
[Owner Dashboard] Add the favorite percentage in the cache list

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1378]
**Describe the solution you'd like**
Add the favorite percentage in the cache list for hidden caches

**Additional context**
![grafik](https://user-images.githubusercontent.com/50927164/87245948-0e042c80-c44a-11ea-8323-85db82fbd32c.png)

**Comment by capoaira** [comment]
Hierfür müsste jeder Cache aufgerufen werden, dadurch würden diese immer in den Recently Viewed auftauchen. Das fände ich nicht so schön.
Das selbe gilt für #1379 

@2Abendsegler, @Ruko2010 was ist eure Meinung?

**Comment by 2Abendsegler** [comment]
Schau mal ob du hiermit weiterkommst. Damit wird in den PQ der Prozentsatz ermittelt. Ich weiß nicht ob du die notwendigen Daten zur Verfügung hast. Ist auch nur ne Idee.
`if ((settings_fav_proz_pqs && li0 == "p")`

Wenn die Recently Viewed Liste voll mit den eigenen Caches wäre, das würde ich auch nicht so gut finden.

**Comment by capoaira** [comment]
Manchmal muss man einfach mehrfach drauf gucken, bis man eine Idee hat. Jetzt hat es endlich geklappt ;)

**Comment by capoaira** [comment]
Screenshot for the Changelog
![grafik](https://user-images.githubusercontent.com/50927164/120896028-ea2c7500-c61f-11eb-9922-468e1553585b.png)

**Comment by 2Abendsegler** [comment]
Merged with #1795

**Comment by capoaira** [comment]
Ich will hierdran nochmal arbeiten, bevor es live geht, um nicht immer die requests zu machen.

**Comment by capoaira** [comment]
@2Abendsegler hast du eine Idee, wie man das Favoriten-Herz Logo von z.B. der Karte ins cod kopieren könnte?
Ich finde im cod nur das FP Symbol: 
![grafik](https://user-images.githubusercontent.com/50927164/124289343-7d3ec900-db52-11eb-9665-14c58764334a.png)
Und das finde ich als Button nicht so schön...

**Comment by 2Abendsegler** [comment]
Ich weiß nicht ob ich dich richtig verstanden habe.

Das ist das blaue Herz plus die Prozente, so wie wir es beispielsweise auf der alten Karte im Popup verwenden.
```
<span class="favi_points" title="Favorites in percent">
    <svg height="16.5" width="16.5">
        <image xmlns:xlink="https://www.w3.org/1999/xlink" xlink:href="/images/icons/fave_fill_16.svg" src="/images/icons/fave_fill_16.png" width="16" height="16" alt="Favorite points"></image>
    </svg> 2%
</span>
```

Das grüne Herz sollte eigentlich im cod als symbol zur Verfügung stehen. Such mal nach #heart_filled_circle. Falls nicht können wir das übernehmen, so wie wir es beispielsweise für das search_map_icon gemacht haben. Schau mal in die Datei init.js (bis vor kurzem noch gclh_defi.js).
Also so etwas, nur ohne use und symbol oder so.
```
<svg aria-hidden="true">
    <use xlink:href="#heart_filled_circle">
        <symbol xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" id="heart_filled_circle">
            <circle cx="12" cy="12" r="12" fill="#fff"></circle>
            <path fill="#00b265" d="M12.14 2a10.14 10.14 0 1010.15 10.14A10.14 10.14 0 0012.14 2zm5.26 11.67a9.5 9.5 0 01-1 1.17A10.62 10.62 0 0115.16 16c-.58.46-1.21 1-1.83 1.48l-.6.45-.24.16-.24.16-.25-.19-.24-.16-.6-.45C10.56 17 9.8 16.36 9.35 16s-.86-.78-1.22-1.13a9.57 9.57 0 01-1-1.17 3.89 3.89 0 01-1-2.46 3.25 3.25 0 016.05-1.57h.14a3.26 3.26 0 016.13 1.54 3.89 3.89 0 01-1.05 2.46z"></path>
        </symbol>
    </use>
</svg>
```

Hilft das?

**Comment by capoaira** [comment]
Oh, ich habe mich nicht verständlich ausgedrückt. Ich möchte als Button zum Laden der Caches das Fav Symbol wie es auf der neuen Karte genutzt wird. Das ist im selben Stil wie das Map Icon.
Gefunden habe ich nur das Icon im Screenshot (`#heart_filled_circle`). Das ist aber vom Stil nicht wie der Karten Button
Die symbole `#heart` und `heart_open` lassen sich nicht anzeigen. Auf der Karte heißt das Icon `#favoritepoints`. Das würde ich gerne Kopieren nutzen.

**Comment by capoaira** [comment]
Ah, hat sich erledigt. Mit `/play/app/ui-icons/sprites/global.svg#icon-heart-svg-fill` kommt man an das Icon

**Comment by capoaira** [comment]
Für den Changelog (zusätzlich zu https://github.com/2Abendsegler/GClh/issues/1378#issuecomment-855252625)
![grafik](https://user-images.githubusercontent.com/50927164/124312520-bcc7de00-db6f-11eb-999f-710f764a54ab.png)

**Comment by 2Abendsegler** [comment]
Second Merge with #1833
