### ISSUE TITLE
The placeholders "founds" and "founds_no" are not up to date.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1381]
**Describe the bug**
The placeholders "founds" and "founds_no", which are used on the logging page are not up to date. It seems to be a bug on all geocaching pages that the counter for the "Finds" in the header right are not up to date. It doesn't seem to be updated immediately. I have an example by myself, with old logging page on 23.07.2020 around 14 o'clock, with a delay of at least 1.5 hours. 

The delay is not always there. I made logs for three days, with old logging page later then 23 o'clock, the counter of which were then in order.

Questions:
1. Is it also the case when tampermonkey (and GClh) is deactivated? I believe that is also the case, but I'm not sure any more.
2. Is it only occurs with logs of the old pages or even if logs are created with the new logging page?
3. Is there a way to get the "Finds" counter from another current location?

**To Reproduce**
1. Go to old logging page for example here https://www.geocaching.com/seek/log.aspx?ID=7474669&lcn=1
2. Post a new log.
3. Go to dashboard or another geocaching page and see the counter in the header.
4. Deactivate Tampermonkey.
5. Go to dashboard or another geocaching page and see the counter in the header.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22332216/88320453-e51f4980-cd1d-11ea-9238-2f89a960167a.png)

**Desktop (please complete the following information):**
 - Windows 10
 - FF 78.0.2 (64-Bit) 
 - GClh 0.10.7

**Additional context**
Error posted at first in a frenche forum [here](https://france-geocaching.fr/forum/viewtopic.php?f=9&t=7804).

According to the contribution, it seems that there are two different places where the counter is, which are also updated differently quickly. Maybe this could also be related to the browser memory. Where the second counter is I did not understand from the French.

**Comment by Ruko2010** [comment]
I would believe, that this has something to do with caching on gc.com. Maybe GS Caches the header of a user and does not update it immediately after a log is posted. I'll go caching on the weekend and will try to reproduce the issue.

**Comment by Chrono81** [comment]
Hi, 
I am from the french forum quoted by 2Abendsegler.
I continue to experiment the two counters. 

**Dashboard**
![Compteur non synchronisé !](https://user-images.githubusercontent.com/5096970/88468289-91f5f400-cee1-11ea-8ed4-bcd1e3b75a4c.png)

**My log of the day !**
![Compteur non synchronisé ! (2)](https://user-images.githubusercontent.com/5096970/88468292-97ebd500-cee1-11ea-9159-4719744c97e6.png)

I hope the two pictures may be helpful. 

-----------------------------------------------
Tampermonkey®v4.11.6114 by Jan Biniok
GC little helper II v0.10.7
Firefox 78.0.2 (64 bits)
Windows 10 Family - 64 bits - Up to date
**Using the logging old page !**

**Comment by 2Abendsegler** [comment]
> Thanks for your comment, this could be helpful.
>
> We are just trying to reproduce the error again and then check whether the problem is possibly related to cookies that GS is setting.
>
> If someone has further ideas, please let us know, here or as comment in the issue on GitHub. 

(https://france-geocaching.fr/forum/viewtopic.php?f=9&t=7804&p=99118#p99118)

**Comment by capoaira** [comment]
´Today I logged the caches from my vacation. The found counter was always up to date.
Maybe GS have fixed the bug?

**Comment by 2Abendsegler** [comment]
Have you used the old log form? It seems to happen only with the old log form, but not always. I have logged on three different days with the old log form. Two times around without problems and once with the described effect.

**Comment by capoaira** [comment]
Oh ok. I use the new log form. I'll try the next days the old one.

**Comment by Chrono81** [comment]
I only use the old log form. The last time I have logged it was OK !
-------- Message d'origine --------De : 2Abendsegler <notifications@github.com> Date : 02/08/2020  19:12  (GMT+01:00) À : 2Abendsegler/GClh <GClh@noreply.github.com> Cc : Chrono81 <cp.gps@free.fr>, Comment <comment@noreply.github.com> Objet : Re: [2Abendsegler/GClh] The placeholders "founds" and "founds_no" are not up to date. (#1381) 
Have you used the old log form? It seems to happen only with the old log form, but not always. I have logged on three different days with the old log form. Two times around without problems and once with the described effect.

**Comment by Chrono81** [comment]
Hello !
I am logging a few founds with the old log form this night. 
I am experiencing the problem again with a lag that is beyond 20 minutes.

**Comment by 2Abendsegler** [comment]
Hi, 

thank you for the update.

I had tried to work out a solution in which we count up a counter ourselves. However, we do not necessarily get all the information. For example when a log is deleted. Or if someone write on different computers, in a short time, and GS shows a wrong counter at the same time. 

Independent of this, the following would be conceivable:

1. If the own counter is older than a few hours, take the counter of GS.
2. If the own counter is higher, take it.
3. Otherwise, take the counter of GS.

But, I'm not really happy with that yet. 

It would be nicer, if we can find a place where the counter of GS is correct, if there is such a place. The statbar cannot be used because it is only a picture. 
If someone notices a lag again, please check the counter on the following pages. Maybe we can use one of these.

https://www.geocaching.com/my/statistics.aspx
https://www.geocaching.com/p/default.aspx?u=Chrono81

Nice weekend.
Frank

Off topic: You wrote a very nice explanation in your forum. You know what I mean. 😄

**Comment by Tungstene** [comment]
I had the same bug a few days ago. I noticed then, while the number of finds showed in the upper right corner was not incrementing, but the number showed in https://www.geocaching.com/p/default.aspx was correct. The wrong number updated sometimes after without any explanation (not immediately after having checked the profile page).

**Comment by 2Abendsegler** [comment]
That sounds good. I'll try to take this into account for the next version. Maybe optionally with a parameter in GClh Config.
Merci beaucoup

**Comment by Tungstene** [comment]
Confirmed today. See this screenshot where you can see the differences between the two counters:
![Screenshot_2020-08-14 Get the free Official Geocaching app and join the world's largest treasure hunt ](https://user-images.githubusercontent.com/17686032/90253060-dae5fc00-de40-11ea-8c0e-cf4e2eddc761.png)

**Comment by Tungstene** [comment]
Same difference on the statistics' page:
![Screenshot_2020-08-14 Get the free Official Geocaching app and join the world's largest treasure hunt ](https://user-images.githubusercontent.com/17686032/90253235-1e406a80-de41-11ea-8b43-22d95c865456.png)

**Comment by Tungstene** [comment]
Bug probably fixed. See https://forums.geocaching.com/GC/index.php?/topic/357996-bug-inconsistency-between-number-of-finds/&do=findComment&comment=5850195

**Comment by 2Abendsegler** [comment]
I had also tested with drafts today, and could not create inconsistencies.

@Tungstene
Merci beaucoup, great job. 

@Chrono81 
Can you confirm that too?

**Comment by 2Abendsegler** [comment]
@Chrono81
Salut,
have you tested it in the meantime?
The adjustments of GS were successful, right?
So we can close the issue, right?
Meilleures salutations.
Frank
