### ISSUE TITLE
[Owner Dashboard / Wonders of the World] Header

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1382]
Add the header functions also for the CO dashboard. (Like the new map and bml)

**Comment by 2Abendsegler** [comment]
Leider haben sie mal wieder alles neu erfunden was das Menü angeht. So weit ich mich erinnere war das beim neuen Dashboard ähnlich, das wurde dann aber etwas später angepasst. Wir sollten vielleicht mit Anpassungen zum Owner Dashboard noch etwas warten, vielleicht wird auch hier noch etwas sinnvoller angepasst.

**Comment by 2Abendsegler** [comment]
Auch für die neue Seite [Wonders of the World](https://www.geocaching.com/promos/campaigns/2) den Header aufbauen. Leider gilt auch hier das zuvor bereits Beschriebene.

**Comment by capoaira** [comment]
Ich habe da nicht so große Hoffnungen, denn bei der neuen Karte und BML haben sie es nicht gemacht. Aber ich habe schonmal ausprobiert, dass dein Workaround für diese beiden Seiten auch bei den neuen funktioniert.

**Comment by 2Abendsegler** [comment]
> 
> 
> Ich habe da nicht so große Hoffnungen, denn bei der neuen Karte und BML haben sie es nicht gemacht. Aber ich habe schonmal ausprobiert, dass dein Workaround für diese beiden Seiten auch bei den neuen funktioniert.

Ich gehe im Moment noch davon aus, dass wir nicht den asynchronen Weg für die beiden neuen Seiten gehen müssen. Das muss man noch prüfen. Mir ging es um etwas anderes.  

Der Header mit den Dropdown Listen wurde nicht wie gewöhnlich eingeleitet, so dass wir nicht ohne weiteres der Header für diese Seiten aufbauen können. Der Header sollte beispielsweise wie überall mit `<nav id=...` eingeleitet werden, hier ist jedoch nur `<nav>` vorhanden ohne eine id. Außerdem ist auch der angeloggte User nicht wie gewöhnlich zu ermitteln, weil auch er anders aufgebaut ist. Auch hier müssten wir basteln. 
Bei den letzten neuen Seiten My List und Search Map waren diese beiden Punkt genauso unsinnig realisiert. Das wurde jedoch nach einigen Wochen korrigiert. Auf so etwas hoffe ich noch, in den nächsten Wochen.

**Comment by capoaira** [comment]
Ah ok. So genau habe ich mir das noch nicht angeschaut.

**Comment by 2Abendsegler** [comment]
> Bei den letzten neuen Seiten My List und Search Map waren diese beiden Punkt genauso unsinnig realisiert. Das wurde jedoch nach einigen Wochen korrigiert. Auf so etwas hoffe ich noch, in den nächsten Wochen.

Das ist falsch. Die Punkte wurden gar nicht geändert. Wir ändern diese Punkte dadurch dass wir eine andere Seite laden und von dort den Header übernehmen. Das gilt auch für `if (!$('.li-user-info')[0]) return;`. Wir müssen also überhaupt nicht warten.

Siehe auch [hier](https://github.com/2Abendsegler/GClh/pull/1403#issue-465209918).

**Comment by 2Abendsegler** [comment]
merged
