### ISSUE TITLE
[Owner Dashboard] Add link to own profile

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1402]
**Is your feature request related to a problem? Please describe.**
I often try to open my Profile page from the new CO Dashboard. (Like from the normal Dashboard)

**Describe the solution you'd like**
Two ideas:
1) Add the link to the username
2) Add a button like in the normal Dashboard

**Additional context**
Für Variante 1 würde ich keinen weitern config Parameter anlegen. Für Variante 2 würde ich zusätzlich einen Parameter anlegen, da nicht jeder einen zusätzlichen Button haben möchte.
Ich tendiere zu Variante 1

**Comment by 2Abendsegler** [comment]
merged

@capoaira 
Kannst du bitte noch einen kleinen Screenshot fürs Changelog hier reinhängen?

**Comment by capoaira** [comment]
![grafik](https://user-images.githubusercontent.com/50927164/91727694-561a1280-eba2-11ea-917e-13469d30ad80.png)

**Comment by 2Abendsegler** [comment]
Danke.
