### ISSUE TITLE
[Drafts] Wrong link to cache listing (coords.info instead of coord.info).

### ISSUE THREAD

**Issue by Tungstene** [2Abendsegler/GClh#1415]
**Bug description**
In Drafts view, GClhII adds an "Open Listing" link button (northeast facing arrow icon) next to the "Delete" link button (trash can icon). This button generates a link beginning with https://coords.info which is not the correct URL. It should be https://coord.info.

**To Reproduce**
1. Upload a draft to your account.
2. [Go to the Drafts page](https://www.geocaching.com/account/drafts).
3. Click on the "Open Listing" icon.
4. See error.

**Expected behavior**
Opened page URL should begin with https://coord.info/.

**Screenshots**
The icon I'm referring to is the one I surrounded with red color.
![Screenshot_2020-08-14 Brouillons](https://user-images.githubusercontent.com/17686032/90250352-38c41500-de3c-11ea-86bd-83cb8c74713d.png)

**Desktop (please complete the following information):**
 - OS: Linux (not relevant)
 - Browser: Firefox (not relevant)
 - Version: 79.0 (not relevant)

**Additional context**
I never met this problem before. Maybe it's because Groundspeak owned both domains (with and without "s")?

**Comment by 2Abendsegler** [comment]
Many thanks for your message.
It is really crazy. This mistake must have existed for a very long time. Merde. 😕

**Comment by 2Abendsegler** [comment]
> I never met this problem before. Maybe it's because Groundspeak owned both domains (with and without "s")?

Oh yes, this is a better explanation.

**Comment by 2Abendsegler** [comment]
Merged to collector

**Comment by 2Abendsegler** [comment]
I have opened it only for presence in the list of issues.
