### ISSUE TITLE
GClh-Links on Drafts Page contain an error

### ISSUE THREAD

**Issue by gcPhil** [2Abendsegler/GClh#1424]
Nachdem einige Links auf GC.com nicht zu funktionieren schienen (Fehler 404) ist mir aufgefallen, dass diese scheinbar alle von GClh 0.10.7 stammen und einen Fehler enthalten: statt zu https://coord.info/GC320YZ wird zu https://**coords**.info/GC320YZ verlinkt. Aufgefallen ist es mir gerade in den "open listing" Links auf der Drafts-Seite, es kann aber auch gut sein, das auch andere Stellen betroffen sind.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 0.10.7

**Comment by capoaira** [comment]
Duplicate of #1415
Fixed in  #1416

GS scheint etwas geändert zu haben. Für die nächste Version hat 2Abensegeler den Fehler gefixed

**Comment by gcPhil** [comment]
Danke für die Rückmeldung und sorry für das Duplikat. Ich mache hier wieder zu.

**Comment by capoaira** [comment]
>  sorry für das Duplikat. 

Alles gut, kann ja passieren
