### ISSUE TITLE
[Drafts] Coords.info instead of coord.info in Open listing link

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#1425]
**Describe the bug**
There is a mistype in the URL of the "Open listing" link on the Drafts page - coords.info instead of correct coord.info.

**To Reproduce**
1. Make a draft & open the new Drafts page
2. Click the arrow icon within your log entry to open the cache page

![image](https://user-images.githubusercontent.com/9153595/90833812-186aed80-e349-11ea-9fa4-6bc9b10cf268.png)

3. The browser launches a new tab and unsuccessfully attempts to open an invalid URL - e. g. https://coords.info/GC6Y847

**Expected behavior**
There is an additional "s" in the URL - it is supposed to be https://coord.info/GC6Y847

**Comment by 2Abendsegler** [comment]
Thanks for the message.
We have fixed it with issue #1415.

**Comment by 2Abendsegler** [comment]
Please close the issue.

**Comment by PontiacCZ** [comment]
I see. I searched for this problem among open issues before posting and didn't find any so I decided to file my own one.... :-(

**Comment by 2Abendsegler** [comment]
Here it has been unfortunate to close resolved problems.
We close them so that we have a better overview.
Sorry for the unnecessary effort. :(
