### ISSUE TITLE
GClh hides Logs

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1429]
**Describe the bug**
If I open a Cache Listings, the Logs where hide

**To Reproduce**
1. Go to e.g. https://www.geocaching.com/geocache/GC86AHV
2. Scroll down

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox/Chrome
 - Version: Current collector

**Additional context**
Der Master funktioniert bei mir ohne Probleme, aber im Collector werden die Logs nicht geladen. Wenn man schnell genug runter scrollt kann man sehen, wie die Logs wieder verschwinden.
Ich habe "Load Logs with GClh" aktiviert, wenn ich es deaktiviere werden die Logs angezeigt.
Bei "Show at least x Logs" habe ich 0 (=all) stehen, aber auch mit 5 o.ä. werden die Logs versteckt.

**Comment by 2Abendsegler** [comment]
Nicht relevant für Milestone.
