### ISSUE TITLE
[Drafts] Open listing button (arrow) links to the wrong link.

### ISSUE THREAD

**Issue by nwpvr** [2Abendsegler/GClh#1439]
**Describe the bug**
The link of the button Open Listing in de Drafts page (https://www.geocaching.com/account/drafts) links to the wrong link.

It links to https://coords.info/GC#### instead of https://coord.info/GC6####

The s in coords.info is not correct.

**To Reproduce**
1. Go to https://www.geocaching.com/account/drafts
2. Click on the arrow between the cachetitle and the bin

**Comment by capoaira** [comment]
Thanks for reporting the bug. 2Abendsegler has already fix it in #1415 for the next version.

**Comment by 2Abendsegler** [comment]
Thanks for the message.

We have fixed it already with issue #1415.

A new version will be available in a few days. You can install an [advance correction](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js), if you want. However, other adjustments are already included there.

I will close the issue.
