### ISSUE TITLE
Mystery Coords get Spoiled on own Mysteries

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#1462]
Hat mich gerade per Sms erreicht:

Hi Christian,
schon gelesen:

Tipp: Wer das Tampermonkey-Skript "little helper II" nutzt und bei seinem eigenen Mystery die Listingkoords korrigiert hat, muss beim Überarbeiten seiner Mysteries, z. B. Hinzufügen der neuen Attribute, vor dem Speichern die Originalkoords eintragen bzw. die korrigierten Koords wieder rausnehmen, sofern der GC-eigene Geochecker verwendet wird. Ansonsten stehen im Checker die Finalkoords. 🤭 Ist mir passiert, aber es gab einen ehrlichen Cacher, der mich darauf aufmerksam machte 👍🏼

**Comment by Ruko2010** [comment]
@2Abendsegler ich bin bis heute Abend unterwegs aber dann könnte ich es mir anschauen. Das sollten wir auf jeden Fall schnell fixen.

**Comment by 2Abendsegler** [comment]
Ich weiß nicht so recht wo das herkommen kann, weil wir doch an den Koordinaten bis auf Styles gar nichts ändern, dachte ich. Und am Checker machen wir doch auch nichts. Das hängt aber vermutlich mit den Änderungen zusammen, die wir mit 0.10.irgendwas gemacht haben um im Edit Modus, oder so, auch die Funktionalität zum GClh anzubieten. 

Ja, sehe ich auch als dringend.

Ich kann das nicht bearbeiten, in meinem Unpublished kann man die Koordinaten noch nicht korrigieren. Ich kann das also nicht nachstellen. Ich könnte heute Abend oder frühestens in etwa 2 Stunden, bin noch unterwegs, eine neue Version raushauen, mehr kann ich im Moment nicht tun.

@capoaira 
Hast du vielleicht Zeit?

**Comment by Ruko2010** [comment]
Ich schau es mir heute Abend an. Ich kann dann gern ein Hotfix release 10.8.1 machen wenn ich es nachgestellt/gefixt habe. Hab ja Myteries.

**Comment by 2Abendsegler** [comment]
Ok, machs so.

**Comment by capoaira** [comment]
Ich kann den Bug nicht nachstellen. Im Checker werden immer die Original Koords angezeigt, oder die **eigenen** korrigierten.

Wenn ich die Beschreibung richtig verstanden habe werden im Checker die korrigierten Koords des Owners bei anderen angezeigt. Ich denke nicht das der GClh so etwas mache kann. Wenn das nach dem bearbeiten geschieht, würde es heißen, dass der GClh die Original Koords ändert. Das geht aber nur mit einem Log.
Oder habe ich etwas falsch verstanden?

**Comment by 2Abendsegler** [comment]
> Wenn ich die Beschreibung richtig verstanden habe werden im Checker die korrigierten Koords des Owners bei anderen angezeigt. Ich denke nicht das der GClh so etwas mache kann.

Der GClh macht das meines Erachtens auch nicht. Ich vermute dass die Vorbelegung im Checker das Problem ist. Vermutlich ermittelt GS die Vorbelegung aus den Koordinaten. Und weil wir hier etwas eingefügt haben, den Button, kommt dort irgend etwas durcheinander.

**Comment by Ruko2010** [comment]
So, hier nun meine Tests:
A1. Ich habe in einem Browser **ohne** irgendein Script den Solution Checker für meinen Mystery aktiviert. Vorher waren die Koordinaten korigiert. Nun gehe ich mit meinem Account auf meine Cacheseite und sehe die Korigierten Koords im Checker.
A2. Ich gehe mit einem **anderen** Account auf die Cachepage. Hier sehe ich **nicht** die korigierten Koords, sondern die originalen.
=> Alles ok.

B1. Ich aktiviere GClh im Browser und aktiviere den Solution Checker erneut bei meinem Cache. Nun gehe ich mit meinem Account auf meine Cacheseite und sehe die Korigierten Koords im Checker.
B2. Ich gehe mit einem **anderen** Account auf die Cachepage. Auch hier sehe ich **nicht** die korigierten Koords, sondern die originalen.
=> Alles ok.

Es gibt dieses Problem also nicht :). Eventuell war der Owner etwas verwirrt, weil die Korigierten Koordinaten auf der **eigenen** Cachepage im Solutionchecker stehen. Bei anderen ist das aber nicht der Fall, nur wenn man selbst schon die Korigierten Koordinaten hat.

**Comment by Ruko2010** [comment]
Das Verhalten ist also mit und ohne GClh gleich. Wenn man korigierte Koords hat, dann werden die immer im SolutionChecker stehen, aber eben nur bei einem selbst, nicht bei anderen.

**Comment by 2Abendsegler** [comment]
Hm, kannst du bitte noch einmal testen wie folgt: 
(Man möge mir verzeihen dass ich die richtige Terminologie nicht kenne. :D )

1. Entferne gegebenenfalls korrigierte Koordinaten.
2. Gehe in den Edit Modus und aktiviere den Solution Checker.
3. Gehe in den normalen Modus und gebe korrigierte Koordinaten ein. Damit hast du die Ausgangssituation.
4. Gehe in den Edit Modus und setze ein weiteres Attribut.
Frage zu 4: Welche Koordinaten werden dabei als Vorbelegung des Solution Checkers angezeigt. Wenn der Kollege recht hat, dann sollten hier schon die korrigierten Koordinaten vorbelegt sein, was nicht sein sollte?
5. Gehe in den normalen Modus.
Frage zu 5: Welche Koordinaten werden im Solution Checker angezeigt?
6. Gehe mit einem anderen User in den normalen Modus, ohne selbst korrigierte Koordinaten im Cache zu haben.
Frage zu 6: Welche Koordinaten werden im Solution Checker angezeigt?

So wie ich es verstehe werden bei 6. die korrigierten Koordinaten angezeigt, weil sie mit GClh bei 4. vorbelegt werden. Ansonsten werden bei 6. die original Koordinaten angezeigt, weil sie ohne GClh bei 4. vorbelegt werden.

Der Unterschied zu deinen Tests: 
Du setzt den Solution Checker. Laut dem Kollegen ist er aber schon gesetzt und es wird ein Attribut geändert. Am Solution Checker wird nichts gemacht. Verstehst du?

Das ist nur eine Idee? 

Es kommt mir etwas komisch vor dass der dritte User korrigierte Koordinaten im Cache stehen hat und sich dann wundert, dass im Solution Checker auch die korrigierten Koordinaten angezeigt werden. Vermutlich hat er sogar vorher auch schon den Solution Checker mit vermeintlichen Lösungskoordinaten bemüht. Die Schlussfolgerung, dass hier fälschlich die korrigierten Koordinaten im Solution Checker erscheinen, finde ich irgendwie nicht naheliegend. Naheliegend ist für mich hier, dass man sich denkt dass die korrigierten Koordinaten auch im Solution Checker angezeigt werden, weil ich sie im Cache als korrigierte Koordinaten eingegeben habe bzw. der Solution Checker nach korrekter Eingabe der Lösungskoordinaten diese auch behält.

Man steckt nicht drin was sich andere für Gedanken machen. Ich finde es aber so naheliegender.

**Comment by capoaira** [comment]
Ich habe es in genau diesen schritten getestet. Es wird alles richtig angezeigt. Wenn nichts geändert ist, werden die Originalen Koords angezeigt, wenn die Koords geändert sind werden diese angezeigt. Wenn ich dann ein Attribut hinzufüge und mich nach dem Speichern mit einem anderen Account anmelde, werden mir die originalen Koords angezeigt. 
Ich sehe es wie Ruko
> Es gibt dieses Problem also nicht :). Eventuell war der Owner etwas verwirrt, weil die Korigierten Koordinaten auf der **eigenen** Cachepage im Solutionchecker stehen. Bei anderen ist das aber nicht der Fall, nur wenn man selbst schon die Korigierten Koordinaten hat.

**Comment by 2Abendsegler** [comment]
Ok, super, um so besser.

**Comment by Ruko2010** [comment]
Ich bin die Schritte auch nochmal durchgegangen.

zu 4: Im Edit Modus kann man keine Koordinaten für den Solutionchecker eingeben. Die zieht er sich automatisch aus dem Final.
zu 5/6: Hier werden im Owner Profil die Korrigierten angezeigt, mit einem anderen Profil aber nicht. => Alles ok

So wie ich es verstehe, können wir an der Anzeige, was im Solutionchecker "vorbelegt" sein soll auch gar nichts ändern. Das zieht sich GS direkt, entweder aus den Header-Koordinaten oder aus den Korrigierten. Je nachdem was man eingetragen hat.

Dazu ein Test: Mit einem anderen Profil hab ich einfach mal willkürlich Koords eingetragen bei den Korrigierte und diese werden dann im Checker angezeigt, auch wenn Sie nicht stimmen.
![image](https://user-images.githubusercontent.com/2239440/93049794-0a676e80-f662-11ea-9a71-6759013fd3aa.png)

**Comment by Ruko2010** [comment]
Ich bin also auch der Meinung, dass es kein Fehler ist, sondern vielleicht nur Verwirrung. ich hab die Dame, die das Problem hat auch auf FB angeschrieben. Ich warte noch auf Reaktion. Solange lasse ich das Ticket noch offen.

**Comment by Ruko2010** [comment]
Aufgrund der fehlenden Userreaktion schließen wir das Ticket.
