### ISSUE TITLE
Show behind the "Add to list" button if cache is available in own bookmarklists.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1463]
[Old Map] Show in cache popup behind the "Add to list" button if cache is available in own bookmarklists.
![Screen01](https://user-images.githubusercontent.com/22332216/93093294-cfd0f680-f6a0-11ea-8040-daa88f3e0381.jpg)

[New Map] Show in cache detail screen behind the "Add to list" button if cache is available in own bookmarklists.
![Screen02](https://user-images.githubusercontent.com/22332216/93093307-d3647d80-f6a0-11ea-9259-ee03dfb43b07.jpg)

[Cache listing] Show behind the "Add to list" button if cache is available in own bookmarklists.
![Screen03](https://user-images.githubusercontent.com/22332216/93093322-d6f80480-f6a0-11ea-874d-0e77959945d8.jpg)

**Comment by 2Abendsegler** [comment]
merged
changelog maintained

**Comment by barnoldGEOC** [comment]
with me this does not work, am I the only one?  (not working in FF, Chrome nor Edge)

**Comment by 2Abendsegler** [comment]
Hey,

please explain what you see in a cache listing. The minimum should be "Add to list (0)". Please use FF. 
Maybe you can post a screenshot of a cache listing?

You can also press the "ctrl", "shift" and "k" keys together. Then the console will open. Maybe you can take a screenshot of this too.

Cheers
Frank

**Comment by barnoldGEOC** [comment]
![2020-11-08 00_28_45-Window top](https://user-images.githubusercontent.com/40668510/98453504-26672800-215a-11eb-8555-030e65b4a124.png)
![2020-11-08 00_29_30-Window bkmrk](https://user-images.githubusercontent.com/40668510/98453506-29621880-215a-11eb-8ef5-c86ee4a2e448.png)

**Comment by barnoldGEOC** [comment]
in FF 82.0.2

**Comment by 2Abendsegler** [comment]
Ok, thanks so far.

Can you please open the FF console with pressing the "ctrl", "shift" and "k" keys together. Please post a screenshot of this also. Perhaps there is an error or an info message and we can see why the feature doesn't run.

**Comment by 2Abendsegler** [comment]
Hey,

can you please open the FF console with pressing the "ctrl", "shift" and "k" keys together. Please post a screenshot of this.
Without this we can not check the errors in the console.

Cheers
Frank

**Comment by barnoldGEOC** [comment]
Like thuis ???

 

No errors, just warnings, the text is in dutch, but I hope you can understand…

 

 

 





 

Van: 2Abendsegler <notifications@github.com> 
Verzonden: vrijdag 13 november 2020 20:53
Aan: 2Abendsegler/GClh <GClh@noreply.github.com>
CC: Bert Arnold <team.barnold@planet.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [2Abendsegler/GClh] Show behind the "Add to list" button if cache is available in own bookmarklists. (#1463)

 

Hey,

can you please open the FF console with pressing the "ctrl", "shift" and "k" keys together. Please post a screenshot of this.
Without this we can not check the errors in the console.

Cheers
Frank

**Comment by 2Abendsegler** [comment]
You has not send a screenshot, but it doesn't matter. No errors.

Then the next idea. In your first screenshot I can see that other add-ons (an ad blocker) are running and other scripts are running.
Can you please deactivate all add-ons except for Tampermonkey?
Can you please deactivate all scripts except for the GClh?
Then does the problem still exist?

**Comment by barnoldGEOC** [comment]
I did as you requested.

No other extensions than Tampermonkey.

And only GClh.

 

Does not help.

But as always you can in a split second see how GClh modifies the screen.

It often goes fast, but I noted once that it showed first 

*  Add to list (1)

Which is correct as it should be

But a split second later it changed to

*  Add to list (0)

 

I cannot reproduce it.

 

My idea would be that something happens after the initial modification of the item by GClh ???

 

 

Bert

 

Van: 2Abendsegler <notifications@github.com> 
Verzonden: vrijdag 13 november 2020 21:41
Aan: 2Abendsegler/GClh <GClh@noreply.github.com>
CC: Bert Arnold <team.barnold@planet.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [2Abendsegler/GClh] Show behind the "Add to list" button if cache is available in own bookmarklists. (#1463)

 

You has not send a screenshot, but it doesn't matter. No errors.

Then the next idea. In your first screenshot I can see that other add-ons (an ad blocker) are running and other scripts are running.
Can you please deactivate all add-ons except for Tampermonkey?
Can you please deactivate all scripts except for the GClh?
Then does the problem still exist?

**Comment by 2Abendsegler** [comment]
Ok, that could be one approach. I'll take a closer look at it on Sunday.
Thanks

**Comment by 2Abendsegler** [comment]
Hi Bert,

@capoaira, a colleague in the development of the GClh, found and corrected the bug in another issue #1500. The correction will be included in the next version of GClh in a few days.

I will close this older issue here now.

Cheers
Frank

**Comment by barnoldGEOC** [comment]
I am glad it was not something on my configuration only.

It seems to be solved, indeed.

 

Thank you for the effort.

I have a little smile on my face as I read what was the cause of the problem.

In my working life in IT things like this happened to me too.

 

Bert

 

Van: 2Abendsegler <notifications@github.com> 
Verzonden: woensdag 25 november 2020 09:23
Aan: 2Abendsegler/GClh <GClh@noreply.github.com>
CC: Bert Arnold <team.barnold@planet.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [2Abendsegler/GClh] Show behind the "Add to list" button if cache is available in own bookmarklists. (#1463)

 

Hi Bert,

@capoaira <https://github.com/capoaira> , a colleague in the development of the GClh, found and corrected the bug in another issue #1500 <https://github.com/2Abendsegler/GClh/issues/1500> . The correction will be included in the next version of GClh in a few days.

I will close this older issue here now.

Cheers
Frank
