### ISSUE TITLE
Flopp: circle around mystery corrected coordinates has wrong diameter

### ISSUE THREAD

**Issue by ztNFny** [2Abendsegler/GClh#1475]
When a Mystery has corrected coordinates both original + corrected are drawn with 3200m circles. But the 3200m should only apply to the listing coordinates, on the actual physical location it's only 161m.

Having some trouble with my git setup, so can't make a pull request, but here's a diff for changed code.
If there's a waypoint with source original it means that there's also a corrected one, in that case make the radius 161.

2641a2642,2648
>         var hasCorrectedCoordinates = false;
>         for (var i=0; i<data.waypoints.length; i++) {
>             if (data.waypoints[i].source == "original" ) {
>                 hasCorrectedCoordinates = true;
>             }
>         }
> 
2670,2671c2677,2678
<                     if (waypoint.typeid == 2 /* Traditional Geocache */ ) radius = 161; //  161m radius
<                     else if (waypoint.typeid == 8 /* Mystery cache */) radius = 3200; // Mystery cache 3200m radius
---
>                     if (waypoint.typeid == 2 /* Traditional Geocache */) radius = 161; //  161m radius
>                     else if (waypoint.typeid == 8 /* Mystery cache */) radius = (hasCorrectedCoordinates ? 161 : 3200); // Mystery cache 3200m radius for unsolved, 161 for corrected coordinates

**Comment by Ruko2010** [comment]
@ztNFny thanks for this bug report. I adjusted the code just a little bit and will create a pull request. After testing it will be in the next release.

**Comment by 2Abendsegler** [comment]
merged
changelog maintained
