### ISSUE TITLE
[New Map] Hide found/own caches, cache types does not work

### ISSUE THREAD

**Issue by anvanlaer** [2Abendsegler/GClh#1478]
The new maps shows found and own caches.  It worked fine untill a couple days ago.  The last days the filters aren't activated in the search.

**Comment by capoaira** [comment]
Thank you for reporting the bug.

@2Abendsegler 
GS made some internal changes to the map. https://forums.geocaching.com/GC/index.php?/topic/359138-release-notes-website-progressive-release-search-map-code-refactor-october-26-2020/ Maybe all features need to be checked for functionality.

**Comment by 2Abendsegler** [comment]
I think the work is still in progress, so we have to be patient a little longer. We should observe the status of the work. When the work seems to be done, we can start to make the necessary adjustments in the GClh. I will set the status "on hold".

Yes, you are right, all features need to be checked for functionality. We do it here in this issue.

- [ ] Check all GClh features in new map.
- [ ] Repair hide found/own caches, cache types.
- [ ] #1489

**Comment by 2Abendsegler** [comment]
It appears that the changes to the site are complete. Maybe we can start with our adjustments.
Volunteers? 😊

**Comment by capoaira** [comment]
I'm maybe a voulenteer, but without much time....

**Comment by capoaira** [comment]
I found the following bugs

- [ ] Link to Browsemap is missing
- [ ] compact Layout does not work correct. 
- [ ] strike through disabled caches does not work
- [ ] Show hint of cache automatically on cache detail screen does not work
- [ ] Hide Cachetypes by default
- [ ] Links to other map services like flopps is missing

**Comment by capoaira** [comment]
Strange, sometimes some functions of the compact layout and also the "Show hint automatically" work, and sometimes they don't ...

Does anyone have an idea why?

**Comment by capoaira** [comment]
@2Abendsegler Should an issue be opened (bit by bit) for each of the points?

**Comment by 2Abendsegler** [comment]
> Should an issue be opened (bit by bit) for each of the points?

Yes, makes sense.

**Comment by 2Abendsegler** [comment]
@capoaira 
Great job!

---
Merged
Changelog maintained
