### ISSUE TITLE
[New log form] Wrong alignment of smileys on new logging page.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1490]
**Describe the bug**
Wrong alignment of smileys on new logging page. The smileys are to height.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/98468669-cb761500-21db-11eb-8972-9c883041cc04.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - current collector

**Comment by 2Abendsegler** [comment]
Moin @Ruko2010 und @capoaira,

@Yannick-XY ist dabei dieses Ticket zu bearbeiten. Er möchte einen Pull Request rüberschicken. Könnt ihr bitte kurz erklären wie er das machen kann?

LG Frank

**Comment by Ruko2010** [comment]
Hallo @Yannick-XY,

schön, dass du dich beteiligen willst. Das mit dem Pull Request ist eigentlich ganz einfach. Du machst einen Fork von diesem Projekt, so dass du es in deinen eigenen Git-Repos hast. Dann erstellst du bei dir einen neuen Feature-Branch. Dort machst du deine Änderungen. Wenn du fertig bist, dann kannst du wieder hier in dieses Repo zurück kommen und einen neuen PR erstellen. Wichtig ist dabei, dass du auf den Link "compare across folks" klickst, da du sonst dein Repo nicht siehst wo die Änderung ja gemacht wurden.

![image](https://user-images.githubusercontent.com/2239440/98781044-0c497600-23f6-11eb-8fbe-f94884c6b288.png)


Ich weis leider nicht wie viel Erfahrung du mit Github hast. Falls das alles Bömische Dörfer für dich waren was ich gerade geschrieben habe, dann sag Bescheid und wir machen mal eine 1-on-1 Session wo wir die Schritte durch gehen.

@2Abendsegler An sich könnten wir dafür auch mal ein HowTo-Dokument anlegen, oder?

**Comment by Yannick-XY** [comment]
@Ruko2010 passt, danke, hab alles verstanden 😎 
...Kannte das "compare across forks" bisher nicht, aber leuchtet ein. Sonst müsste man ja jeden der was machen will zum Projekt hinzufügen..

**Comment by 2Abendsegler** [comment]
> An sich könnten wir dafür auch mal ein HowTo-Dokument anlegen, oder?

Ja, gute Idee. Und wir könnten das im [readme - How you can help?](https://github.com/2Abendsegler/GClh#how-can-you-help) integrieren und verlinken.

**Comment by capoaira** [comment]
> > An sich könnten wir dafür auch mal ein HowTo-Dokument anlegen, oder?
> 
> Ja, gute Idee. Und wir könnten das im [readme - How you can help?](https://github.com/2Abendsegler/GClh#how-can-you-help) integrieren und verlinken.

Find ich auch gut. Für mich war GitHub zum Anfang komplettes Neuland und echt schwer. Eine Anleitung würde es deutlich einfacher machen👍🏻

**Comment by 2Abendsegler** [comment]
merged
changelog erfasst

@Yannick-XY 
Wir haben eine "Thanks" Seite im GClh in die wir alle Helfer eintragen. Darf ich dich auch dort eintragen? Damit kann man dann von deinem GitHub Account auf deinen GC Namen schließen und umgekehrt.
Falls ja, gib mir bitte noch mal deinen GC Namen, kann deine Mails gerade nicht finden. 🙄

**Comment by Yannick-XY** [comment]
> merged
> changelog erfasst
> 
> @Yannick-XY
> Wir haben eine "Thanks" Seite im GClh in die wir alle Helfer eintragen. Darf ich dich auch dort eintragen? Damit kann man dann von deinem GitHub Account auf deinen GC Namen schließen und umgekehrt.
> Falls ja, gib mir bitte noch mal deinen GC Namen, kann deine Mails gerade nicht finden. 🙄

Super gerne: Sunhillduo - https://coord.info/PR4PENN
