### ISSUE TITLE
[Statistic] Rebuild D/T Matrix functionality together with implemented enhancements of GS.

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#1491]
https://forums.geocaching.com/GC/index.php?/topic/359306-release-notes-website-difficultyterrain-grid-november-9-2020/

GS has implemented the function for searching for a specific D/T Combination itself, so we can remove the Function in GCLH II

**Comment by 2Abendsegler** [comment]
Das ist nicht das Gleiche das wir implementiert haben. GS macht mit dem neuen Button eine Selektion der Caches zur nächsten Füllung der Matrix. Bei uns kann man die nächsten bis zu 4 Füllungen abrufen, jedoch nur einzeln. Der Button ist also eine nette Erweiterung. 

Allerdings funktionieren unsere Markierungen nicht mehr und auch unsere Anzeige mit dem ... complete ??/?? funktioniert nicht mehr richtig. Das sollten wir korrigieren.

**Comment by 2Abendsegler** [comment]
![grafik](https://user-images.githubusercontent.com/22332216/98599590-84bc1400-22dc-11eb-872f-e8926fac2c2b.png)

**Comment by 2Abendsegler** [comment]
Hab gerade gesehen dass die auch ne Klickmöglichkeit eingebaut haben. Also können wir das doch rausschmeißen. :D

**Comment by 2Abendsegler** [comment]
Vielleicht können wir die farbliche Hervorhebung noch belassen.

**Comment by Ruko2010** [comment]
Ja die farbliche Markierung finde ich gut, die können wir gern drin lasen. Aber der Rest kann raus.

**Comment by 2Abendsegler** [comment]
Merged
Changelog maintained
