### ISSUE TITLE
[New Map] Buttons to "Search Map" and "Go to ..." are missing.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1493]
Buttons on the right are missing:
- Button to other map services
- Relocate button to browsemap

**Comment by 2Abendsegler** [comment]
Super, passt.
Getestet mit und ohne: Relocate buttons "Search" and "Browse geocaches" to the other buttons
Getestet mit und ohne: Add link to ... on GC Maps

![grafik](https://user-images.githubusercontent.com/22332216/100072822-06fc1a80-2e3d-11eb-9c55-88c515f7f169.png)

merged
changelog maintained
