### ISSUE TITLE
[Info] How to contribute.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1498]
@2Abendsegler An sich könnten wir dafür auch mal ein HowTo-Dokument anlegen, oder?

_Originally posted by @Ruko2010 in https://github.com/2Abendsegler/GClh/issues/1490#issuecomment-725251883_

Damit wir das nicht vergessen ;)

**Comment by Ruko2010** [comment]
(Für mich) Grober Ablauf:

1. A developer 'forks' an 'official' server-side repository. This creates their own server-side copy.
2. The new server-side copy is cloned to their local system.
3. A Git remote path for the 'official' repository is added to the local clone.
4. A new local feature branch is created.
5. The developer makes changes on the new branch.
6. New commits are created for the changes.
7. The branch gets pushed to the developer's own server-side copy.
8. The developer opens a pull request from the new branch to the 'official' repository.
9. The pull request gets approved for merge and is merged into the original server-side repository

**Comment by 2Abendsegler** [comment]
Was meint ihr?

F1. Vielleicht könnten wir das auch in die FAQs einbinden und bräuchten dann kein eigenes Dokument.
F2. Falls wir ein eigenes Dokument erzeugen, sollten wir vielleicht trotzdem noch einen Eintrag in die FAQs aufnehmen mit Verweis.
F3. Und im Readme sollte man vielleicht auch darauf verweisen.

**Comment by capoaira** [comment]
F1/2: je nach dem wie umfangreich das wird, würde ich sagen.
F3: würde ich auch sagen

**Comment by Ruko2010** [comment]
Ich würde es auf jeden Fall in ein eigene Dokument packen, da ich es mit vielen Screenshots unterlegen möchte.

Die Verlinkung in den einzelnen Sektionen (FAQ / Readme) würde ich auf jeden Fall machen.

**Comment by Ruko2010** [comment]
Ich habe das Dokument in Deutsch erstellt. 
@2Abendsegler, @capoaira Könnt ihr mal drüber lesen ob das verständlich ist und ob alles passt?
https://github.com/Ruko2010/GClh/blob/issue/1498-how-to-contribute/docu/how_to_contribute.md

**Comment by 2Abendsegler** [comment]
- Gefällt mir richtig gut!
- Ich habe auch alles verstanden, obwohl das für mich ja neu ist.
- Alle meine Anpassungen sind nur Vorschläge.
- Habe grundsätzlich alle Bindestriche entfernt, weil das immer so kryptisch aussieht. Also beispielsweise <del>Pull-Request</del> Pull Request
- Screenshots finde ich netter mit Rand (hab das mal fürs ersten Screenshot gemacht) und wenn etwas Leerraum zwischen Schrift und Bild.
- Ich habe bei allen Referenzen auf die Nummerierungen in den Screenshots den Punkt ergänzt, der auf den Screenshots auch zu sehen ist. Alternative könnte man die Punkte in den Screenshots auch wegmachen.
- Die Buttons oder Links habe ich alle so benannt wie sie tatsächlich sind. Wenn dort beispielsweise steht _branch_, dann mache ich kein _Branch_ daraus, sondern übernehme es so wie es im Screenshot steht.
- Bei der Erwähnung des Git Clients könnte man noch einen Link in die Doku setzen, da haben wir doch auch was.

---

## <a id="de"></a>Wie kannst du etwas beitragen?

Am einfachsten ist es, wenn du direkt einen <del>Pull-Request</del> Pull Request einreichst. Falls du nicht <del>weist</del> weißt wie das geht, dann bist du hier genau richtig. Wir erklären dir Schritt für Schritt wie du Änderungen oder neue Features einreichen kannst. Wir prüfen diese <del>Änderung</del> Änderungen dann und lassen sie ggf. in die nächste Version vom GClh II einfließen.

###  <a id="1de"></a>1. Fork: Erstelle eine <del>Serverseitige</del> serverseitige Kopie des Codes in deinem Github Account
Änderungen am Code kannst du nicht direkt bei uns im Repository vornehmen. Du musst dafür eine Kopie des Codes in deinem <del>Githubaccount</del> Github Account erzeugen, einen sogenannten Fork.
Das ist ganz einfach. Dafür loggst du dich bei Github ein und rufst unser Repository über <a href="https://github.com/2Abendsegler/GClh">diesen Link</a> auf.
Auf dieser Seite ist oben <del>Links</del> rechts der *Fork* Button.

![1_fork](https://user-images.githubusercontent.com/22332216/100295030-cd382a80-2f88-11eb-9ac7-f27bc63d5d87.jpg)

Sobald man diesen betätigt hat man eine serverseitige Kopie des Codes angelegt, in dem man nun arbeiten kann.

###  <a id="2de"></a>2. Branch: Erstelle einen lokalen <del>Feature-Branch</del> Feature Branch
Damit deine Änderungen zusammenhängend sind und du ggf. auch an mehreren Sachen gleichzeitig arbeiten kannst, wird pro Feature / Änderung ein sogenannter Branch angelegt. Dies geschieht in deiner lokalen Kopie des Codes, also in deinem Repository. 
Hierfür klickt man auf den <del>*Collector Branch* (1)</del> Branch *collector* (1.), gibt einen neuen Namen für den Feature Branch ein <del>(2)</del> (2.) und klickt anschließend auf <del>*Create Branch* (3)</del> *Create branch* (3.).

![2_branch](https://user-images.githubusercontent.com/22332216/100295588-42f0c600-2f8a-11eb-87bf-0b637b298589.jpg)

###  <a id="3de"></a>3. Entwicklung: Implementierung der <del>Änderung</del> Änderungen
Nun kannst du die Änderungen über ein oder <del>meherer</del> mehrere Commits am Code durchführen.
Entweder du installierst dir einen <del>Git-Client um</del> Git Client, um die <del>Änderung</del> Änderungen auf deinem Computer durchzuführen, oder du führst die <del>Änderung</del> Änderungen direkt <del>im Repository auf</del> im Repository in deinem Github Account auf der Webseite durch.

###  <a id="4de"></a>4. <del>Pull-Request</del> Pull Request: Änderungsantrag einreichen
Sind alle Änderungen <del>gemacht kannst</del> gemacht, kannst du bei uns im Repository einen Änderungsantrag, einen sogenannten <del>Pull-Request</del> Pull Request, einreichen. Wir werden deine Änderungen dann prüfen. Entweder wir übernehmen die <del>Änderung</del>Änderungen in der nächsten Version <del>von GClh II oder</del> vom GClh II, oder melden uns bei dir, falls noch Änderungsbedarf besteht.
_(2Abendsegler: Zusätzliche Leerzeile)_
So reichst du den <del>Pull-Request</del> Pull Request ein.

_(2Abendsegler: Hier nicht 1. und 2. verwenden sondern Punkte, ansonsten kann man das mit den roten 1. und 2. aus dem Screenshot verwechseln.)_

- Dafür loggst du dich wieder bei Github ein und rufst unser Repository über <a href="https://github.com/2Abendsegler/GClh">diesen Link</a> auf.

- Du klickst auf den Reiter <del>*Pull-Requests* (1)</del> *Pull requests* (1.) und dort auf <del>*New Pull Request* (2)</del> *New pull request* (2.).<br>
_(2Abendsegler: Screenshot auch mit einrücken)_
![4_Pull_1](https://user-images.githubusercontent.com/22332216/100295723-9236f680-2f8a-11eb-86de-992e4ab0326a.jpg)

- Hier gibt es nun zwei Sachen zu beachten. Zuerst muss auf den Link <del>*compare acress forks* (1)</del> *compare across forks* (1.) geklickt werden, da sonst nur ein <del>Pull-Request</del> Pull Request innerhalb <del>unserers</del> unseres Repositorys möglich ist. Danach wird als <del>*Base Repository* (2)</del> *base repository* (2.) das Repository von *2Abendsegler/GClh* ausgewählt. Wichtig ist weiterhin den Branch <del>*Collector*</del> *collector* zu wählen. <del>Im *Collector*-Branch</del> In der Branch *collector* sammeln wir alle <del>Änderungen um</del> Änderungen, um sie dann später in einer neuen Version an die User auszuliefern. Als <del>Head-Repository* (3)</del> *head repository* (3.) wählst du nun dein eigenes Repository und <del>die Branch</del> der Branch in der deine Änderungen zu finden sind. Zum Abschluss klickst du auf <del>*Create Pull Request* (4).</del> *Create pull request* (4.).<br>
![4_Pull_2](https://user-images.githubusercontent.com/22332216/100295768-b72b6980-2f8a-11eb-89cb-d215823ec657.jpg)

- Im letzten Schritt kannst du deinem <del>Pull-Request einen Namen (1)</del> Pull Request einen Namen (1.) geben und eine <del>Beschreibung (2)</del> Beschreibung (2.) zur Verfügung stellen. Mit dem Button <del>*Create Pull Request* (3)</del> *Create pull request* (3.) erstellst du den <del>Pull-Request</del> Pull Request und bist fertig.
Die Felder auf der <del>Rechten Seite (4)</del> rechten Seite (4.) musst du nicht ausfüllen.
Bitte erstelle für jedes Feature einen seperaten <del>Pull-Request</del> Pull Request. Das macht mögliche Änderungen einfacher.<br>
![4_Pull_3](https://user-images.githubusercontent.com/22332216/100295809-e641db00-2f8a-11eb-949c-b51357168c9c.jpg)

**Comment by Ruko2010** [comment]
Danke für dein Feedback. ich werde es einbauen.

**Comment by Ruko2010** [comment]
Der erste Teil der Änderungen ist eingepflegt. ich hoffe ich habe alle Stellen erwischt 😃. Die Überarbeitung der Screenshots und die Englische Übersetzung folgen noch. Ich tagge euch dann nochmal wenn ich das fertig habe, damit ihr nochmal drüber schauen könnt.

**Comment by capoaira** [comment]
Mir gefällt die Anleitung auch gut. Damit sollte jeder etwas anfangen können 👍

**Comment by Ruko2010** [comment]
Die Screenshots und Abstände sind nun auch angepasst.
Dann werde ich den Spaß mal noch ins Englische schmeißen.

**Comment by 2Abendsegler** [comment]
Merged
Changelog maintained
Changelog corrected
