### ISSUE TITLE
Show behind the "Add to list" button if cache is available in own bookmarklists does not work.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1500]
**Describe the bug**
1. Show behind the "Add to list" button if cache is available in own bookmarklists does not work. 
2. If GCT installed, the number of bookmarks will be shown behind "Add to GCTour" on searchmap

**To Reproduce 1**
1. Go to Cache Details
2. Look to "Add to list" button. Is always "(0)" for me

**Expected behavior**
Shows number of own bookmarks

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - collector

**Additional context**
Ich habe etwas rumprobiert:
Wenn ich in Zeile 12010
`if ( $(this).find('a[href*="/profile/?guid="]')[0] && $(this).find('a[href*="/profile/?guid="]')[0].innerHTML.match("2Abendsegler") &&`
das `"2Abendsegler"` durch `global_me` ersetzte, funktioniert es bei mir, allerdings werden dann alle Listen doppelt gezählt. Ich denke das liegt daran, dass es Listen in den Cachedetails doppelt gibt, einmal unter "eigene Listen" und einmal unter "Alle listen"

Zu 2.:
Dort sollte `$('.cache-preview-action-menu ul > li:nth-child(1)')[0]` durch `$('.cache-preview-action-menu ul li.add-to-list')[0]` ersetz werden.

**Comment by 2Abendsegler** [comment]
Boah, bin ich bescheuert. 😓
In Zukunft werde ich auch alles gegencheken lassen.

**Comment by capoaira** [comment]
Hihi, kann passieren

**Comment by 2Abendsegler** [comment]
merged
changelog maintained

**Comment by barnoldGEOC** [comment]
so it was not just me
