### ISSUE TITLE
[New log form] Signature does not work.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1502]
**Describe the bug**
Log Signature does not work on the new design if the log is not a draft

**To Reproduce**
1. Go to 'cache details'
2. Click on 'log geocache'
3. Signature is not insert

**Expected behavior**
The Signature should be insert into the log form

**Desktop:**
 - OS: Windows
 - Browser: firefox
 - Version: master and collector

**Additional context**
Der Bug wurde mir von @S-Man42 gemeldet. Ich kann ihn reproduzieren

**Comment by capoaira** [comment]
Ich denke ich habe den Fehler gefunden. @S-Man42 kannst du einmal testen:
[Hier](https://github.com/capoaira/GClh/raw/log/signature/gc_little_helper_II.user.js) geht es zur überarbeiteten Version
[Hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) geht es zurück zur aktuellen Version

**Comment by S-Man42** [comment]
Ja, schaut gut aus :)

**Comment by 2Abendsegler** [comment]
Bei mir schaut es auch prima aus!
Aus altem und neuem Draft heraus mit neuem Log Formular getestet. Und ohne Draft getestet.

---
merged
changelog maintained
