### ISSUE TITLE
[Documentation] How you can install the GClh on Android devices.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1519]
[Documentation] How you can install the GClh on Android devices.

Im [französischen Geocaching Forum](https://france-geocaching.fr/forum/viewtopic.php?f=22&t=5982&p=100012#p99987) wurde die Frage gestellt wie man den GClh auf einem Android System installiert. 

Ich nehme das zum Anlass die Dokumentation dazu in den Installationstipps und in den FAQs zu überarbeiten und allgemeiner zu fassen, so dass nicht nur Firefox sondern auch andere Browser Erwähnung finden.

Außerdem wollte ich im Changelog nochmal darauf verweisen.

Seit Anfang des Jahres 2020 macht die Installation auf dem neuen mobilen Firefox Browser insofern Probleme, dass Tampermonkey noch nicht zu den empfohlenen Erweiterungen gehört und deshalb nur über Umwege als Erweiterung installiert werden kann. Die Userzahlen für die Nutzung vom GClh auf Android Systemen sind um 78% gefallen, was sicherlich auch damit zu tun hat. 

[Hier](https://www.soeren-hentzschel.at/firefox-android/nightly-installation-beliebiger-erweiterungen/) gibt es einen Artikel in deutsch darüber, wie man nicht empfohlene Erweiterungen installieren kann, siehe dazu im Artikel "Erweiterte Unterstützung in Firefox Nightly". Auf diese Info möchte ich auch irgendwo verweisen, im Changelog oder nur in den Foren bei der Ankündigung der einer neuen Version.

**Comment by capoaira** [comment]
Ich habe die Erfahrung gemacht, das viele der (neuen) Features nicht nur nicht funktionieren, sondern die Seiten zerschießen (z.B. BLM)...

**Comment by 2Abendsegler** [comment]
Ja, bei den Bookmarklisten ist es besonders blöd. Das hängt aber damit zusammen, dass teils die mobile Version angezeigt wird. Ich geh dem aus dem Weg indem ich entweder das Smartphone quer halte oder mir die Seite als Desktop-Website anzeigen lasse. In beiden Fällen wird die mobile Version nicht gezogen und es sieht alles wie gewohnt prima aus.

**Comment by capoaira** [comment]
Vielleicht sollten wir manche funktionen an mobiles Layout anpassen. Gerade das Menü sieht Mobile nicht so toll aus und auf den Seite wo wir den Header ersetzen gibt es kein Mobiles Menü

**Comment by 2Abendsegler** [comment]
Die Idee ist schon richtig, nur sagen wir ja eigentlich, dass wir Android nicht supporten. Ich hatte hier immer Bedenken, dass man uns die Bude einrennt, weil vieles auf einem Minigerät eben nicht wirklich gut aussieht. 

Aber was solls, wir können solche Anfragen von Anderen ja trotzdem ablehnen.

Wenn du Interesse an spezifischen Anpassungen fürs Android hast, dann mach halt entsprechende Issues auf.
Schön wäre es halt, wenn man nicht wirklich zweigleisig fahren muss wie es GS ja teilweise macht, also ein Menü für grosse und eins für kleine Bildschirme, oder so. Aber das sehen wir dann ...

**Comment by 2Abendsegler** [comment]
Merged
Changelog maintained
