### ISSUE TITLE
[Owner Dashboard / Statistics] D/T matrix header and coloring broken

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [2Abendsegler/GClh#1522]
**Describe the bug**
Since gc.com invented the D/T medal and the ``Fill your grid again`` button, the DT matrix header does not show the matrix fill count anymore, but the cache found count instead. Header looks like ``... (<FoundCount> complete and (81/81))``.

Moreover the coloring of the lowest numbers in the matrix does not work anymore.

**To Reproduce**
1. open [your statistics page](https://www.geocaching.com/my/statistics.aspx)
2. Scroll down to ``Difficulty and Terrain of Caches I've Found``
3. have a look at the header and the matrix coloring ...

**Desktop:**
 - OS: Windows
 - Browser: Firefox 83.0
 - GClh Version: 0.10.9

**Additional context**
Same behavior using Android 10 with Kiwi Browser Git201105 and GClh 0.10.9.

**Comment by 2Abendsegler** [comment]
Thanks for reporting the bug. 

We have fixed it already with issue #1491.
We are reviewing the changes. If you want you can examine the changes in pull request #1513.

A new version will be available in a few days.  

I will close this issue.

**Comment by MagpieFourtyTwo** [comment]
Great - thx a lot!
