### ISSUE TITLE
[New Map] Show hint automatically does not work always / Refactor show hint automatically

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1531]
**Describe the bug**
If you open a cache description, the hint is displayed, but ff you call another cache via the map, the note is not automatically displayed because the description is displayed directly and so the function is not triggered.

**To Reproduce**
1. Open a Cache
2. Click on "Description & Hint"
3. See automatically shown hint
4. Open an other Cache from map (don't close the description)
5. The Hint is not displayed

**Additional context**
Die Funktion ist momentan sehr komplex, weil Änderungen in der Sidebar vom Mutation Observer nicht bemerkt wurden. Deswegen hatte ich das mit einer Reihe an EventListener gelöst. Zudem habe ich damals noch kein jQuery genutzt.
Mit den neuen Änderungen werden diese Änderungen bemerkt und so kann man einen großen Teil rausschmeißen. Dabei ist mir der Bug durch Zufall aufgefallen, der so auch gleich gelöst ist. ;)

**Comment by 2Abendsegler** [comment]
Merged
Changelog maintained
