### ISSUE TITLE
[New Map] Loading Spinner is visible if "Automatic search for new caches after dragging" is off

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1534]
**Describe the bug**
The Loading Spinner is visible if "Automatic search for new caches after dragging" is off

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/100654197-c07d5300-3349-11eb-94fb-ce6d3a0992a1.png)

**Comment by 2Abendsegler** [comment]
Merged
Changelog maintained
