### ISSUE TITLE
[Hide cache] Build header with navigation menu and linklist.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1542]
There is a new Page to hide a Cache. 
https://www.geocaching.com/play/hide

**Comment by capoaira** [comment]
Es ist keine neue Seite, sondern nur eine überarbeitete Seite. Aber auch der Header wurde durch den neuen ersetzt. Durch unser `mainGCAsyn();` können wir das umgehen.

@2Abendsegler: Wenn man `is_page("hide_cache")` nutzt funktioniert es. Allerdings verweist es auch auf einige andere Seiten, auf denen wir den Header dann unnötiger Weise ersetzten. Dort führt das dann zu Problemen.

Meine Idee war es nun anstatt alle neuen Seiten anzugeben, direkt auf `$('#gc-header')[0]` zu prüfen, denn bei allen neuen Seiten heißt der Header so, bei den alten heißt der Header `#gcNavigation` oder `#ctl00_gcNavigation`
So müsste man dann auch nicht immer wenn GS eine neue Seite raus bringt den Header einfügen. Wäre das ok?

**Comment by 2Abendsegler** [comment]
Ja, hört sich gut an, mach mal.

**Comment by 2Abendsegler** [comment]
Das assign lasse ich drin stehen sonst weiß ich später nicht wer daran gearbeitet hat.

**Comment by 2Abendsegler** [comment]
- [ ] Für neue Hide Seite ein is_page machen. 
(Ich weiß aber selbst noch nicht wie es am besten ist. Vielleicht die alte hide_cache vorher auch umbenennen.)
- [ ] Prüfen Funktionalität von alter hide_cache Seite. Müssen wir was nachziehen?
(Ich denke hier beispielsweise an die Implementierungen zur Taste F2.)
- [ ] Zu langsamer Headeraufbau, `$('#gc-header')[0]` ist noch nicht da.
- [ ] Menüausrichtung und ganz rechts im Header. 
![grafik](https://user-images.githubusercontent.com/22332216/102044402-0cfb7080-3dd7-11eb-8ef6-547fa563bbd0.png)

**Comment by 2Abendsegler** [comment]
merged
