### ISSUE TITLE
[New Map] Automatic search of new caches is available also for bookmarklists maps.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1553]
**Describe the bug**
[New Map] Automatic search of new caches is available also for bookmarklists maps.

Bisher enthielten urls der neuen Karte die Bookmarklisten Kennung, wenn es sich um eine Bookmarkliste handelte, also z.B. BM206W6. Deshalb wurde bei der automatischen Aktualisierung der Karte entsprechend geprüft.
`if (document.location.href.match(/\.com\/play\/map(\/BM|\?bm=)/)) return;`

Seit kurzem ist die Bookmarklisten Kennung jedoch nicht mehr enthalten. Der Link in der Bookmarkliste zur Karte enthält zwar die Bookmarklisten Kennung noch.
https://www.geocaching.com/play/map/BM206W6
Die url wird auf der Karte jedoch ersetzt und dabei fliegt die Bookmarklisten Kennung raus.
https://www.geocaching.com/play/map?lat=50.83649&lng=10.806875&zoom=6&asc=true&sort=distance

**To Reproduce**
1. Go to a bookmarklist, or click [here](https://www.geocaching.com/plan/lists/BM206W6?sort=name&sortOrder=asc&skip=0&take=500)
2. Click on the button to the map 
![grafik](https://user-images.githubusercontent.com/22332216/102068168-6c1fac00-3dfc-11eb-9940-38e76d65ec6c.png)
You can see briefly an url with a bookmarklist id.
3. Move the map and see the automatic search funktionality.

**Comment by 2Abendsegler** [comment]
@Ruko2010, @capoaira:

Ich habe keinen Weg gefunden um auf der Karte festzustellen, ob es sich ursprünglich um einen Aufruf aus einer Bookmarkliste handelte. Ich weiß also nicht wie wir das Problem beheben können.

Könnt ihr bitte mal einen Test machen und mal überlegen welche Lösungsmöglichkeiten es geben könnte?

**Comment by capoaira** [comment]
Ich habe eine Idee, denn die css wird beispielsweise richtig umgesetzt. Man müsste gleich zu Anfang die URL prüfen, denn dort wird noch angegeben, ob es eine BM ist oder nicht. Die Info könnte man in einer globalen variable speichern...

**Comment by 2Abendsegler** [comment]
super!

merged
