### ISSUE TITLE
[Cache listing] Buttons "Create story" and "Helpful" don't work correct.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1565]
**Describe the bug**
[Cache listing] Buttons "Create story" and "Helpful" don't work correct.

**To Reproduce**
1. Go to a cache listing with this buttons or click [here](https://coord.info/GC920A1).
2. Scroll down to the logs.
3. Press button "Create story" or "Helpful" on second log.
4. See error message in the console.
![grafik](https://user-images.githubusercontent.com/22332216/102171736-8490d480-3e97-11eb-9b34-9ee9ed5e52e9.png)

**Comment by capoaira** [comment]
I cannot reproduce the bug...

**Comment by 2Abendsegler** [comment]
Ich kann das auch nicht mehr nachvollziehen, dubios.
Ich schließe das Teil.
