### ISSUE TITLE
[Search Map / Browse Map / Pocket Query] Before saving as PQ from map, determine whether the GClh default settings for new PQs should be set or not.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1574]
**Describe the bug**
Don't set new pocket query parameter if the new pocket query is calling from old map.
Or implement a config parameter to control it for this kind of new pocket queries.

For PQ-Splitter it is not relevant, because links comes from PQ-Splitter include not 
`.../gcquery.aspx?ll=...` 
but 
`.../gcquery.aspx?PQSplit=...`.

Config of the new pocket query parameter:
![grafik](https://user-images.githubusercontent.com/22332216/102511969-b9fd1400-4089-11eb-905e-a8cde1262065.png)

Calling from old map:
![grafik](https://user-images.githubusercontent.com/22332216/102512185-05afbd80-408a-11eb-9406-a9088612f9b0.png)

Coding to handle this:
```
// Pocket query set default value for new one, set warning message.
    if (document.location.href.match(/\.com\/pocket\/gcquery\.aspx/)) {
...
            if (($("p.Success").length <= 0) && (document.location.href.match(/\.com\/pocket\/gcquery\.aspx$/) || document.location.href.match(/\.com\/pocket\/gcquery\.aspx\?ll=/))) {
```

**To Reproduce**
1. Go to [old map](https://www.geocaching.com/map).
2. Click on "Save As Pocket Query" in left side bar at the bottom.
3. See pocket parameter are set.

**Comment by 2Abendsegler** [comment]
@Ruko2010, @capoaira:
Wenn ich von der Karte aus eine Pocket Query generieren lasse, dann möchte ich eigentlich genau das sehen was ich auch auf der Karte gesehen habe. So meine Interpretation.

Man könnte aber auch die Meinung vertreten, dass die Karte ja nur eine grobe Auswahl ist, schließlich kann ich dort einige Parameter wie beispielsweise Difficulty oder Terrain gar nicht einschränken. Dann würde ich vermutlich auch gerne die Parameter für eine neue Pocket Query hier sehen.

Wie seht ihr das? 
Sind beide Fälle relevant und müssen wir deshalb einen neuen Parameter implementieren, der das steuert?

**Comment by capoaira** [comment]
Ich würde alle default Filter setzten, die nicht auf der Karte einstellbar sind. Z.b. automatisch 1000 statt 500...

Statt eines fixen Parameter würde ich einen Button "GClh default Werte einfügen" z.B. im ersten Block machen. Dann könnte man immer entscheiden, was man will, und was nicht.

PS: Cool wäre auch ein Save as PQ Button für die neuen Map.

**Comment by 2Abendsegler** [comment]
Danke für dein Feedback.

> Ich würde alle default Filter setzten, die nicht auf der Karte einstellbar sind. Z.b. automatisch 1000 statt 500...

1000 statt 500 wäre schon ok. Aber beispielsweise die Difficulty und Terrain Parameter, die ja auch nicht in der Karte einstellbar sind, würden schon heftige Unterschiede generieren. Dafür müsste dann wirklich ein Parameter her.

> Statt eines fixen Parameter würde ich einen Button "GClh default Werte einfügen" z.B. im ersten Block machen. Dann könnte man immer entscheiden, was man will, und was nicht.

Ok. Sollte der Button dann nicht direkt oberhalb des "Save As PQ" sein? Auf die Ausgabe in der Karte haben die Parameter ja sowieso keine Auswirkung.

> PS: Cool wäre auch ein Save as PQ Button für die neuen Map.

😄 Ja warum nicht. Ich weiß aber nicht ob man das vernünftig hinbekommen wird. Es sind ja nicht alle Parameter aus der neuen Karte in einer Pocket Query umsetzbar, wie beispielsweise "Geocache name contains" oder "Corrected coordinates".
Außerdem kann man ja eine Bookmark Liste aus der neuen Karte erzeugen. Und daraus kann man wiederrum eine Pocket Query machen. Also lohnt sich der Aufwand vielleicht nicht.

**Comment by Ruko2010** [comment]
Hmm, ich hab hier eigentlich keine Meinung, da ich diese Funktion noch nie genutzt habe. Ich würde aber die PQ so haben wollen, wie es aktuell auf der Karte dargestellt ist, nicht mehr und nicht weniger.

**Comment by 2Abendsegler** [comment]
Ok, danke für dein Feedback.

Ich schlage dann vor, dass wir es so machen wie capoaira es im Kern vorgeschlagen hat. Einen Schalter in der Nähe des Links, mit dem die Default Werte für neue PQs eingeschaltet bzw. ausgeschaltet werden können.

**Comment by 2Abendsegler** [comment]
Auch in Search Map integrieren. 
Vielleicht das Aussehen in der Browse Map so ändern wie es in der Search Map ist, inclusive Hide Header und dem Schalter dafür und einem weiteren Schalter für 'Set defaults'. Mit erklärendem Title versehen.

**Comment by capoaira** [comment]
Ich würde das Layout der alten Karte nicht anpassen, da dort der Save as PQ button eine Funktion von GS ist, Hide Header aber nicht. Wir würden so ein Layout ändern, was es seit Jahren gleich ist.... Auf der neuen Karte haben wir das ja nur aus Platzgründen gemacht.

Ich würde den Schalter für default Werte nicht auf der Karte, sondern auf der PQ Seite machen, oder meintest du das?

**Comment by 2Abendsegler** [comment]
> Ich würde das Layout der alten Karte nicht anpassen, da dort der Save as PQ button eine Funktion von GS ist, Hide Header aber nicht. Wir würden so ein Layout ändern, was es seit Jahren gleich ist.... Auf der neuen Karte haben wir das ja nur aus Platzgründen gemacht.

Du hast Recht.

> Ich würde den Schalter für default Werte nicht auf der Karte, sondern auf der PQ Seite machen

Aber den brauche ich doch auf der Karte, sonst kann ich der PQ ja nicht mitgeben, dass die Defaults gesetzt werden sollen oder eben nicht. 

Für die neue Karte ist das schon so weit fertig und sieht so aus:
![grafik](https://user-images.githubusercontent.com/22332216/120094313-e2506a80-c11f-11eb-841b-53d69301fa03.png)

**Comment by capoaira** [comment]
> Aber den brauche ich doch auf der Karte, sonst kann ich der PQ ja nicht mitgeben, dass die Defaults gesetzt werden sollen oder eben nicht.
> 
> Für die neue Karte ist das schon so weit fertig und sieht so aus:
> ![grafik](https://user-images.githubusercontent.com/22332216/120094313-e2506a80-c11f-11eb-841b-53d69301fa03.png)

Ich dachte an eine checkbox auf der pq Seite, da man dort auch mehr Platz für ne Erklärung hat... aber so wie du es gemacht hast sieht es besser aus und man muss das setzten der Filter nicht an 2. Stelle nochmal einbinden. Ich denke so ists besser 👍🏻

**Comment by 2Abendsegler** [comment]
Merged with #1780

@capoaira 
Danke für vielen unermüdlichen Tests. 😊
