### ISSUE TITLE
[New Map / Pocket query] Save as PQ button on search map.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1578]
>PS: Cool wäre auch ein Save as PQ Button für die neuen Map.

_Originally posted by @capoaira in https://github.com/2Abendsegler/GClh/issues/1574#issuecomment-747641684_

Die Idee hatte ich schon länger, da dies eine Funktion ist die ich auf der search map vermisse.

**Comment by capoaira** [comment]
Es funktionert fast alles (wenn auch nicht 100%ig). Aber leider bekomme ich die Attribute nicht angeklickt. Habt ihr eine Idee wie das gehen könnte. Ich habe es schon mit verschiedenen Methoden ausprobiert...

**Comment by 2Abendsegler** [comment]
`$('button[aria-label="Wheelchair accessible"]').click();`
Damit lässt sich das zweite Attribut "Wheelchair accessible" anklicken. 
(Man muss die Seite neu anwählen, aktualisieren ist scheinbar nicht ausreichend.)

**Comment by 2Abendsegler** [comment]
Ich glaub ich hab nicht richtig gelesen um was es geht ... hahaha.

**Comment by capoaira** [comment]
> Ich glaub ich hab nicht richtig gelesen um was es geht ... hahaha.

Das passiert jedem mal ;D

Ich meinte auf der PQ Seite. `.click()` habe ich ausprobiert, das hat nicht geklappt. Auch andere Versuche das Event (click und onclick) zu triggern hat nicht funktionert.

**Comment by Yannick-XY** [comment]
Wenn ich euch richtig verstehe gehts drum auf der Seite https://www.geocaching.com/pocket/gcquery.aspx einen Klick auf eines der Attribute auszulösen, ums es (ab)wählen zu können... richtig?
https://www.geocaching.com/includes/attributelistcontrol.js da passiert die ganze Magie die die Bildchen tauscht und co, vielleicht kann man die Funktion direkt nutzen?
![image](https://user-images.githubusercontent.com/51820605/105605278-6bcce600-5d96-11eb-9117-e0a5fec577f3.png)

**Comment by 2Abendsegler** [comment]
Hört sich gut an.

**Comment by capoaira** [comment]
Omg, ich habe den Fehler gefunden. Das Event sitzt zwar bei `$('.btn-attribute')`, aber das `evt.target` mit dem das Script von GS arbeitet ist das icon `$('.btn-attribute img')`. Danke für den Tipp, ich hatte schon aufgegeben 🤣
Jetzt funktionert auch endlich das `.click()`

**Comment by 2Abendsegler** [comment]
merged

**Comment by 2Abendsegler** [comment]
@capoaira 
Mir ist hier noch ein Fehler aufgefallen.
Wenn man in My Lists die neue Karte anwählt, dann wird der Button save as Pocket Query auch angezeigt. Wenn man ihn anwählt erfolgt eine Error. 
Kannst du den Button bitte noch für solche Fälle entfernen.

**Comment by capoaira** [comment]
Oh, und ich war so sicher, dass ich das überall entfernt habe... habe einen PR mit dem fix erstellt

**Comment by 2Abendsegler** [comment]
merged
