### ISSUE TITLE
Openroutemaps has been changed and their url

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1585]
The url of openroutemaps has been changed.

Two Bugs:
- [X] The route will not be shown
- [x] Medium of locomotion works not correct

@ColleIsarco please subscribe this Issue so that I can assign you.
I've added a review on your PR #1584

**Comment by capoaira** [comment]
@2Abendsegler: Note for changelog: 
Because of the openroutemap change from `1` to `1a` all users there are use "Bike" have to set "Bike" again. (Otherwise the default value 0 (=car) is set)

@ColleIsarco: It doesn't seem enough to just subscribe to the issue. It seems that you have to add a little comment so that I can assign you.

**Comment by capoaira** [comment]
merged

**Comment by ColleIsarco** [comment]
I will check if it possible to adapt GClh to the new version of Openroute. If yes, I will open a new issue.

**Comment by 2Abendsegler** [comment]
Nur zu Info:

Wir haben im GClh eine Möglichkeit bei einer neuen Version Einstellungen zu migrieren.
Habe noch eine Migration von 1 auf 1a eingebaut. (Kommt aber erst mit PR #1601 in Branch collector.)

```
    function migrationTasks()
        ...
        // Migrate Openroutemaps medium from 1 to 1a (zu v0.10.12).
        if (getValue("migration_task_04", false) != true) {
            if (getValue("settings_show_openrouteservice_medium") == '1') {
                setValue("settings_show_openrouteservice_medium", '1a');
                settings_show_openrouteservice_medium = '1a';
            }
            setValue("migration_task_04", true);
        }
    }
```
