### ISSUE TITLE
[Cache listing] Oneclick watching does not work

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1589]
**Describe the bug**
The oneclick watching does not work due changes of GS

**To Reproduce**
1. Go to cache detail page e.g. https://coord.info/GC163FK
2. Click on 'watch'
3. See error

**Expected behavior**
The cache should be added to the watchlist and the numbers of watchers should be behind "watch"

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/107846329-2aeb4e80-6de3-11eb-9c5e-9f656bcf56f4.png)

**Additional context**
From geoclub: https://geoclub.de/forum/viewtopic.php?p=1319643#p1319643

**Comment by 2Abendsegler** [comment]
@capoaira 
Moin,
ich habe Nachricht erhalten, dass die Anzahl der Watchenden nicht angezeigt wird, wenn man selbst auch dabei ist, dort also das Stop watching steht. Kann du bitte nochmal danach sehen?
![grafik](https://user-images.githubusercontent.com/22332216/110283306-267c1500-7fe0-11eb-9d81-26b51b7d41af.png)
Danke.

**Comment by capoaira** [comment]
Tatsächlich. Das habe ich wohl übersehen. Neuer PR ist raus ;)

**Comment by 2Abendsegler** [comment]
merged
