### ISSUE TITLE
[New/Old Map] Additional data not loaded.

### ISSUE THREAD

**Issue by Yannick-XY** [2Abendsegler/GClh#1591]
Latest logs not shown anymore since some days

**To Reproduce**
- version 0.10.11

1. Go to the old map
2. Click on any cache
3. the latest logs does not load

**Expected behavior**
The latest logs should be displayed with found/dnf/NA/...  -Icons and on hovering the logtext should be shown.

```
var a = $(text).find('.CacheDetailNavigation ul li').first().find('a[href*="/seek/gallery.aspx?guid="]');
                            if (a) {
                                var galleryLink = a[0].href; // <-- there is no href attribute, js crashes.
```

![image](https://user-images.githubusercontent.com/51820605/107876689-be964b00-6ec7-11eb-8dd9-b6b644ca14e7.png)

**Comment by capoaira** [comment]
Vielen Dank für das Melden des Bugs. Die Bugbeschreibung ist gut ausführlich 👍🏻 

Der Bug hängt wohl mit den letzten Änderungen von GS zusammen und ich habe schon eine Idee wo ich ansetzten kann.

**Comment by capoaira** [comment]
So, ich denke ich habe den Fehler behoben.
[Hier](https://github.com/2Abendsegler/GClh/blob/3e6bc712c5fad34a3cc02348465d1f3f99a2fa9a/gc_little_helper_II.user.js?raw=true) kannst du die Änderungen testen.
[Hier](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true) geht es zurück zur aktuellen Version

**Comment by Yannick-XY** [comment]
> So, ich denke ich habe den Fehler behoben.
> [Hier](https://github.com/2Abendsegler/GClh/blob/3e6bc712c5fad34a3cc02348465d1f3f99a2fa9a/gc_little_helper_II.user.js?raw=true) kannst du die Änderungen testen.
> [Hier](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true) geht es zurück zur aktuellen Version
> @Yannick-XY könntest du einmal gucken ob es auch bei dir jetzt wieder klappt?

Lokal verifyed - tut wieder - perfekt danke!
