### ISSUE TITLE
[New Map] VIP, VUP and Mail for owner in cache detail.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1593]
https://geoclub.de/forum/viewtopic.php?p=1319658#p1319658

**Comment by capoaira** [comment]
- [ ] Cache Listing (nicht in den Logs)
- [ ] TB Listing
- [ ] Post, Edit, View Cache und TB Logs
- [ ] Mail schreiben
- [ ] Profil ?
- [ ] Friends

---
- [ ] add vipvup on new map
- [ ] add to "view all logs" (https://www.geocaching.com/seek/cache_logbook.aspx?guid=)
- [ ] remove code for Audit Log (because the site was removed by GS)

---
Seiten ohne Änderung:
- Owner Dashboard
- Öffentliches Profil
- Post Cache Logs neue Seite
- TB Inventar
- Map (For enhanced Popup Informations)
- Nearest Lists mit User
- Friend League, Leaderboard

**Comment by capoaira** [comment]
Die Liste im Comment oben dient auch zum vergleichen, falls die Links noch auf weiteren Seiten geändert werden.

**Comment by 2Abendsegler** [comment]
Könnten wir es nicht überall derart ändern, dass wie beide Möglichkeiten abfragen? 
`.../(p|profile)/...` so in etwa.

**Comment by capoaira** [comment]
Ist eigentlich eine gute Idee. Mache ich morgen... oder übermorgen

**Comment by 2Abendsegler** [comment]
@capoaira 
```
Könnten wir es nicht überall derart ändern, dass wie beide Möglichkeiten abfragen? 
`.../(p|profile)/...` so in etwa. 
```
```
Ist eigentlich eine gute Idee. Mache ich morgen... oder übermorgen
```

Wie weit bist du eigentlich hier? Scheint fast so, dass das Thema hinten runter gefallen ist. 😄

**Comment by capoaira** [comment]
Habe gestern die PR geschickt. #1598

**Comment by 2Abendsegler** [comment]
VIP/VUP/Mail auf der neuen Karte funktioniert nicht korrekt. Ich hab versucht das anzupassen, das klappt aber nicht so schnell wie ich das gerne hätte. 

Die restlichen Änderungen bezüglich Audit Seite und profile|p sind in Ordnung. Die fehlenden profile|p habe ich noch umgesetzt.

Ich habe das Issue umbenannt in "[New Map] Vip/Vup/Mail for owner in cache detail.". Zum Thema kann es also hier weitergehen, irgendwann, ist ja nicht eilig. Man sollte aber auf dem neuen, aktuellen collector aufsetzen.
Zu VIP/VUP/Mail habe ich das folgende Coding entfernt.
```
            // Search Map / New Map:
            // The VIP/VUP for the Search Map is in the Search Map section
            // because a mutation observer is required.
            // ----------

```
```
            function mapVipVup() {
                if ($('.geocache-owner-name')[0]) {
                    if ($('.gclh_vip')[0]) $('.gclh_vip')[0].parentNode.remove();
                    if ($('a[href^="/email/?u="]')[0]) $('a[href^="/email/?u="]')[0].remove();
                    let link = $('.geocache-owner-name a[href^="https://www.geocaching.com/profile/?u="]')[0];
                    if (!link) link = $('.geocache-owner-name a[href^="https://www.geocaching.com/p/?u="]')[0];
                    let user = link.innerHTML;
                    if ($('.header-top-left h1')[0]) var GCTBName = $('.header-top-left h1').html().trim();
                    else var GCTBName = $('.gclh-cache-link').html().replace(/<svg.*<\/svg>/, '').trim();
                    let GCTBCode = $('.cache-metadata-code')[0].innerHTML.trim();
                    global_name = GCTBName;
                    global_code = '('+GCTBCode+')';
                    global_link = '(https://coord.info/'+GCTBCode+')';
                    gclh_build_vipvupmail(link.parentNode, user);
                    if (settings_searchmap_compact_layout && $('.gclhOwner .gclh_vip')[0]) {
                        $('.gclhOwner .gclh_vip')[0].parentNode.addEventListener('click', gclh_add_vip);
                    }
                }
            }
```
`                mapVipVup();`

**Comment by 2Abendsegler** [comment]
![Screen06](https://user-images.githubusercontent.com/22332216/118302010-ff602900-b4e3-11eb-8cdf-7040b460d85d.jpg)

---
merged
