### ISSUE TITLE
[Old Map] Public Transport Lines are not shown.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1594]
**Describe the bug**
The "Public Transport Lines" are not shown

**To Reproduce**
1. Go to 'https://www.geocaching.com/map'
2. Check [ ] Public Transport Lines
3. See error

**Expected behavior**
The should be shown the Transport Lines

**Additional context**
(Geoclub: https://geoclub.de/forum/viewtopic.php?p=1319746#p1319746)
Der Server von http://openptmap.org/ gibt keine Daten mehr. Deswegen wird auch nichts angezeigt.
GS hat angekündigt Stück für Stück alle alten Seiten, also auch die Map abzuschaffen. Lohnt es sich, sich nach einem neuen Dienst umzuschauen, geschweige denn eine neue Implementierung?

**Comment by 2Abendsegler** [comment]
> Lohnt es sich

Ich weiß nicht. 

Ich glaube nicht, dass genau dieser Layer viel verwendet wird.
Bis die alte Karte abgeschafft wird, könnten auch noch Jahre vergehen.
Eigentlich hatten wir geplant die Layer auch auf der neuen Karte anzubieten.

**Comment by Ruko2010** [comment]
Ich bin eher dafür den layer raus zu schmeißen. Wenn es eh keine Daten mehr gibt. Wenn User den nutzen/sehr vermissen, dann werden Sie sich schon melden und dann können wir uns immer noch eine Alternative Suchen und auf der neuen Karte einbauen.

**Comment by capoaira** [comment]
Sehe ich auch so 👍🏻

Habe vergessen zu erwähnen, dass der Bug im geoclub gemeldet wurde: https://geoclub.de/forum/viewtopic.php?p=1319746#p1319746

**Comment by 2Abendsegler** [comment]
"Public Transport Lines" deleted.

**Comment by 2Abendsegler** [comment]
merged
