### ISSUE TITLE
[New Map] align of the sidebar on list view

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1596]
**Describe the bug**
The Sidebar goes over the header

**To Reproduce**
1. Go to 'https://www.geocaching.com/play/map'
2. Open the Sidebar
3. Click on 'My Lists'
4. Choose a list
5. Choose a cache
6. See bug

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/109662922-da5a4c00-7b6b-11eb-9e25-be6a990d45c0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: actual collector 

**Additional context**
https://forums.geocaching.com/GC/index.php?/topic/360753-release-notes-website-premium-member-lists-on-the-search-map-march-1-2021/

**Comment by 2Abendsegler** [comment]
Wird über #1597 erledigt.
Ich schließe das.
