### ISSUE TITLE
[New Map] Integrate new BML feature in compact layout feature.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1597]
Decrease white space on the new Buttons and List
![grafik](https://user-images.githubusercontent.com/50927164/109669473-68d1cc00-7b72-11eb-8d26-f76899a39e16.png)
![grafik](https://user-images.githubusercontent.com/50927164/109669544-7be49c00-7b72-11eb-8cba-f681fd64bf7f.png)

**Additional context**
https://forums.geocaching.com/GC/index.php?/topic/360753-release-notes-website-premium-member-lists-on-the-search-map-march-1-2021/

**Comment by 2Abendsegler** [comment]
Das mache ich bereits mit #1596.

**Comment by 2Abendsegler** [comment]
Auf folgenden Bildschirmen wurden Anpassungen gemacht:
Start:
![grafik](https://user-images.githubusercontent.com/22332216/110219402-3e0fac80-7ebf-11eb-8354-da9d3756d77a.png)

BML:
![grafik](https://user-images.githubusercontent.com/22332216/110219414-5a134e00-7ebf-11eb-8009-80807ad36d7c.png)

BML - Cache Liste
![grafik](https://user-images.githubusercontent.com/22332216/110219428-74e5c280-7ebf-11eb-97ab-6a7f6d4ff6b0.png)

BML - Cache Detail
![grafik](https://user-images.githubusercontent.com/22332216/110219435-829b4800-7ebf-11eb-94a9-b55e48eb78ca.png)

Außerdem musste die Scroll Bar auf allen Bildschirmen angepasst werden, damit sie auf allen Bildschirmen unten am Bildschirm endet. Also das hier in gelb:
![grafik](https://user-images.githubusercontent.com/22332216/110219504-e4f44880-7ebf-11eb-9d29-cde1d00a778e.png)

Außerdem musste auf den Cache Detail Bildschirmen für Caches und für Caches aus BML das Scrollen zum Cache in der Cache Liste nach dem Back Button angepasst werden.

**Comment by 2Abendsegler** [comment]
merged
