### ISSUE TITLE
[Cache listing] Hide upvote feature with logs sort and "Great story", "Helpful" buttons.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1623]
**Is your feature request related to a problem? Please describe.**
The buttons take a lot of space.

**Describe the solution you'd like**
Remove the buttons maybe with an button above the Logs

**Describe alternatives you've considered**
An option in the config

**Comment by Ruko2010** [comment]
Are you sure you want to remove the feature completely? Maybe we can shrink and move them, so they don't take up so much space?
If you want to remove it, you could just hide/remove them. The buttons are situated in a div:
`<div class="upvotes">` you also have to remove the sorting field `<div class="sort-logs">`

**Comment by 2Abendsegler** [comment]
Hier sollten wir noch etwas warten. Es gibt noch einige Anforderungen in den Release Notes.
https://forums.geocaching.com/GC/index.php?/topic/360926-release-notes-website-log-upvotes-march-15-2021/

**Comment by 2Abendsegler** [comment]
merged

**Comment by 2Abendsegler** [comment]
Ich werde doch noch einen Button dazubauen.

**Comment by 2Abendsegler** [comment]
merged
