### ISSUE TITLE
[Cache Listing] Vip Mail Icon double in Logs

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1624]
**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/111468644-14a81980-8726-11eb-8eab-ad1b254e4f3a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox

**Comment by 2Abendsegler** [comment]
Ähh ... in deinem Screenshot sehe ich VIP, VUP, Mail und Message Icons, so wie es sein soll. Und ich sehe auch Online kein Problem.

**Comment by capoaira** [comment]
Oh, wie peinlich.
Ich war an einem anderen PC, der nicht mein config hatte. So sah es für mich doppelt aus, da ich die VUPs normalerweise ausblende… 
Nächstes Mal gucke ich genauer…
