### ISSUE TITLE
[New Map] Hide sidebar by default does not work on list hub

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1627]
**Describe the bug**
If you open the map on the list hub (https://www.geocaching.com/play/map/lists), the sidebar is shown and not hidden.

**To Reproduce**
1. Go to 'https://www.geocaching.com/play/map/lists'
2. See error

**Expected behavior**
The sidebar should be hidden if "Hide sidebar by default" is active.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser: firefox 
 - Version: actual collector

**Comment by 2Abendsegler** [comment]
Hier muss ja noch was nachgearbeitet werden (Review im PR). Habe deshalb auf 'status: in progress' zurückgesetzt.

**Comment by 2Abendsegler** [comment]
merged
