### ISSUE TITLE
[Cache listing] Copy to clipboard menu will not work for own entries.

### ISSUE THREAD

**Issue by Herr-Ma** [2Abendsegler/GClh#1629]
Der Titel sagt schon alles ;-). Alle eigenen Einträge im "Copy to Clipboard"-Menü werden zwar angezeigt, ein Anklicken bleibt aber ohne Funktion (Popup wird nicht geschlossen, konfigurierte Daten werden nicht kopiert). Das Kopieren der vier statischen Menüeinträge funktioniert weiterhin einwandfrei.

Getestet mit GClh 0.10.12 und Firefox 87 (Mac)

**Comment by 2Abendsegler** [comment]
Das hängt damit zusammen dass sich die Links zum Owner geändert haben und hier der tatsächliche Owner, im Gegensatz zum Pseudonym, nicht mehr ermittelt werden konnte. Beispielcache: https://coord.info/GC7N0QH

![Unbenannt](https://user-images.githubusercontent.com/22332216/115806392-fb5e5100-a3e6-11eb-9572-6ac9f19f1029.JPG)

**Comment by 2Abendsegler** [comment]
merged

**Comment by Herr-Ma** [comment]
@2Abendsegler : ich muss es mal wieder los werden...

Vielen Dank für die großartige Arbeit, die insbesondere du hier leistest. Das dieser Bug hier gefixt ist, ist nebensächlich. Dein Einsatz bei der Lösung des Headerproblems (hast du vorletzte Nacht überhaupt geschlafen?) ist nicht mit Gold aufzuwiegen. Daran merkt man, wie sehr dir dieses Projekt am Herzen liegt und es inzwischen komplet zu "deinem Baby" geworden ist (typisches Software-Entwickler-Syndrom ;-).

LG, Marcus alias Herr Ma

**Comment by 2Abendsegler** [comment]
Danke dir Marcus. 😊
LG Frank
