### ISSUE TITLE
[Global] GClh doesn't run because of changing page header.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1630]
**Describe the bug**
GClh doesn't run because of changing <del>the header info about the login user</del> page header.
Class `li-user-info` is not longer available.

**To Reproduce**
1. Go to a geocaching.com page

**Comment by 2Abendsegler** [comment]
Scheinbar werden wieder Änderungen in produktiver Umgebung durchgeführt ohne vorher richtig zu testen, weil die Änderungen nicht konstant sind. Zudem stehen einige Seiten wie die Drafts oder das Dashboard zeitweise gar nicht zur Verfügung. 
Vermutlich wird der Userbereich oben Links im Header dynamisch geladen und steht deshalb nicht immer zu Beginn unserer Verarbeitung zur Verfügung.

**Comment by 2Abendsegler** [comment]
Nicht nur der Userbereich sondern auch die Menüs (Play ...) werden dynamisch geladen. Auf die Schnelle weiß ich nicht wie wir das im GClh abbilden sollen. 

Ich werde morgen den alten GS Header versuchen einzubauen. Den habe ich gesichert, leider aber nur in Englisch. 
Das corecss des alten GS Headers nutzen wir ja bereits.
Erste Versuche sehen vielversprechend aus.

**Comment by capoaira** [comment]
Was hat sich GS nur bei dieser Sch***e gedacht? Tausend Bugs, die man hätte sehen müssen, bevor die an die User gehen.
Ich fürchte wir sollten irgendwann die Header Funktionen an den neunen Header anpassen. Eventuell verwendet GS ja endlich überall den selben header... Hoffen darf man ja ;)

**Comment by 2Abendsegler** [comment]
Tatsächlich ist der Header nun überall identisch. Leider werden die Menülisten aber erst beim Click auf Play... dynamisch geladen. Das dynamische passt jetzt gar nicht so recht. Ich baue gerade den alten Header fix ein, nur damit es schneller geht. Später können wir ja mal sehen.

**Comment by capoaira** [comment]
> Tatsächlich ist der Header nun überall identisch.

Mal sehen wie das bei den Seiten ist, die gar nicht funktionieren...

**Comment by 2Abendsegler** [comment]
> Mal sehen wie das bei den Seiten ist, die gar nicht funktionieren...

😂

Neue Karte und Bookmarklisten funktionierten gestern noch und haben den gleichen Header.

**Comment by capoaira** [comment]
Ah, das ist gut. 👍🏻
Bei GS muss man ja echt schnell sein, um alles zu sehen 😅

**Comment by 2Abendsegler** [comment]
merged

**Comment by capoaira** [comment]
Leider ist das Problem auf dem neuen Ownerdashbord und der Hide Cache page nicht behoben:
![grafik](https://user-images.githubusercontent.com/50927164/115736001-37fc5f00-a38b-11eb-98d9-d3e8bbed812b.png)

**Comment by 2Abendsegler** [comment]
Danke für die Meldung.
Die anderen Seiten sind nun auch mit drin.
merged

**Comment by diundbi** [comment]
Moin Moin,

leider startet GCLH II auf keiner Seite

**Comment by diundbi** [comment]
![GC-Header](https://user-images.githubusercontent.com/59375844/115765241-ce8a4980-a3a6-11eb-8285-42c5cbc72f3a.PNG)

**Comment by capoaira** [comment]
Moin,
bei mir war das leider auch so. Ich musste den GClh einmal entfernen und wieder hinzufügen. Allerdings gaube ich ehr, dass das etwas mit Zwischenspeicher zu tun hat. Wenn du kein backup von deinem GClh Einstellungen hast, würde ich dir empfehlen, den Browser Cache zu löschen, bevor du riskierst, die config datei zu verlieren.
Da der GClh ja nicht läuft kannst du deine Einstellungen nicht so einfach exportieren. Sollte das löschen des Caches nicht funktionieren musst du den Export über Tampermonkey machen. Solltest du dabei Hilfe benötigen, kann ich dir hier gerne helfen.

**Comment by diundbi** [comment]
Vielen Dank für deine schnelle Antwort.

Ich glaube eher nicht, dass das Problem im Browser-Cache liegt, denn weder in Chrome noch in Edge startet das Tool

**Comment by diundbi** [comment]
Update: Auch auf dem Rechner meiner besseren Hälfte startet GCLH nicht

**Comment by capoaira** [comment]
Da ich mit Firefox arbeite habe ich in Chrome noch nicht die neue Version gehabt und konnte bestätigen, dass es nicht funktioniert. Mit dem Löschen des Browser Caches wurde das Problem behoben. 
Dadurch musst du dich natürlich auf allen Webseiten neu einloggen usw.
Wenn du dass nicht willst hilft wohl nur die neu Installation.

**Comment by Etaner7** [comment]
Ich habe dasselbe Problem, habe beim Firefox den Cache gelöscht, aber noch immer startet GCLH nicht.

**Comment by 2Abendsegler** [comment]
@diundbi, @Etaner7 
Wähle mal bitte das Tampermonkey Icon an und dann den Menüeintrag Übersicht. Nun werden alle Scripte angezeigt. 
1. Zeigt der GClh die 0.10.14 an?

Bitte klick dann mal auf den Scriptnamen. Nun bist du im Editor.  
2. In einer der ersten Zeilen steht auch die Version. Ist sie 0.10.14?

Bitte ändere mal die Version im Coding auf 0.10.13. Anschließend Menü Datei / Speichern anwählen.
Installiere die Version 0.10.14 nochmal über folgenden Link: https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true

Beende anschließend den Browser. Alle Tabs müssen geschlossen werden. 
Wähle dann nochmal eine Geocaching Seite an.

@capoaira
Dubios! 
Hast du eine Erklärung dafür? 
Gabs das in der Vergangenheit bei dir auch schon mal?
Hattest du beide Versionen 13 und 14 nacheinander installiert, oder nur noch die 14.

**Comment by 2Abendsegler** [comment]
@capoaira
Hattest du einen Fehler in der Console als er nicht anlief?

**Comment by diundbi** [comment]
@capoaira
Dein workaround hat funktioniert - sowohl bei Edge, als auch bei Chrome. Nun ist der Rechner der besseren Hälfte dran...

Schon einmal ganz herzlichen Dank

**Comment by Etaner7** [comment]
Bei mir funktioniert die Neuinstallation vom Script leider nicht. Habe die alte Version dann komplett gelöscht, aber das Script wird nicht installiert.
Das Skript wurde aktualisiert.[21:21:54] aber Tampermonkey zeigt kein Script.

**Comment by Ruko2010** [comment]
@2Abendsegler Bei mir ist noch Version 10.12 drauf. Es kommt aber keine Updateaufforderung.
Kann es sein, dass Tampermonkey ein Problem hat?
GClh läuft auch nicht, obwohl es als aktiv angezeigt wird. Es gibt auch keinen Fehler in der Console.

**Comment by diundbi** [comment]
Bei dem Rechner meiner Frau war sogar noch V0.10.12 installiert. Habe dann trotzdem das workaround wie beschrieben durchgeführt - und es hat geklappt.

Euer Support ist einmalig. Schönen Abend noch

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Durch die Header Änderungen von GS auf allen Seiten kann der GClh nicht mehr richtig anlaufen. Installiere mal die neue Version.

**Comment by Ruko2010** [comment]
@diundbi Danke für die Rückmeldung.
@2Abendsegler Das Problem wird dann aber sicher bei vielen (allen?) Usern auftreten, dass kein Update erfolgt, oder?

**Comment by Etaner7** [comment]
@2Abendsegler 
Ich schau mir das Morgen nochmals an. 
Vielen lieben Dank inzwischen!

**Comment by Ruko2010** [comment]
> @Ruko2010
> Durch die Header Änderungen von GS auf allen Seiten kann der GClh nicht mehr richtig anlaufen. Installiere mal die neue Version.

Version 10.14 ist nun drauf, Browser neu gestartet. Es läuft immer noch nicht.

**Comment by Ruko2010** [comment]
Update: Es funktioniert weder im Chrome, noch im Firefox. Beide zeigen Version 10.14 an, aber in beiden Browser läuft GClh nicht...

**Comment by 2Abendsegler** [comment]
@Ruko2010
Wie capoaira sagen würde: Browsercache löschen.
Ich habe in allen Foren darauf hingewiesen dass ein Update nicht automatisch kommt. Obwohl es nicht ganz richtig ist, weil ein Update kann auch über Tampermonkey kommen. Aber eben das GClh getriggerte Update erfolgt nicht.

**Comment by Ruko2010** [comment]
ok, nach dem browsercache löschen und erneutem Neustart des Browsers läuft es nun.

**Comment by capoaira** [comment]
@2Abendsegler 
>Dubios!
>Hast du eine Erklärung dafür?
>Gabs das in der Vergangenheit bei dir auch schon mal?
>Hattest du beide Versionen 13 und 14 nacheinander installiert, oder nur noch die 14.

In Firefox nacheinander, aber nur bei der V14 hat es funktioniert. Ich habe nicht nachgeforscht, da ich dachte, das es daran liegt, dass ich mir deinen fix schon mal vorab installiert hatte (aus der PR).

In Chrome habe ich direkt auf v14 installiert.

In der Vergangenheit hatte ich nie Probleme.

**Comment by Ruko2010** [comment]
Ich hab im Chrome nichts weiter gemacht, aber nun kam auch hier die Update-Meldung und das Script läuft nun. Verrückt.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Das kann aber keine GClh Update Meldung gewesen sein. War das Tampermonkey?

**Comment by Ruko2010** [comment]
Das war die Meldung "GClh was updated to 10.14, willst du die Änderungen anschauen."

**Comment by 2Abendsegler** [comment]
> 
> 
> Das war die Meldung "GClh was updated to 10.14, willst du die Änderungen anschauen."

Ja

**Comment by 2Abendsegler** [comment]
Ja. Aber davor muss doch etwas erfolgt sein. Oder hast du automatisches Update bei Tampermonkey eingestellt.

**Comment by Ruko2010** [comment]
Davor habe ich das Script über den Link installiert. 
Mein Dev-Script funktioniert aber immer noch nicht. Und wenn ich nun wieder zurück auf den Standard GClh wechsel, dann klappt es immer noch nicht.
Ich denke es liegt am Header, denn dort entscheiden wir ja, ob der GClh laufen soll oder nicht. Und wenn der nicht lädt, dann lädt auch GClh nicht. Bei mir dauert es manchmal mehrere Sekunden, bis der Header überhaupt erscheint.

**Comment by Ruko2010** [comment]
Jetzt bin ich komplett raus. Es geht nun auch im FF wieder nicht, ob wohl ich da nichts gemacht habe....
Ich versteh es nicht...

**Comment by 2Abendsegler** [comment]
> Ich denke es liegt am Header, denn dort entscheiden wir ja, ob der GClh laufen soll oder nicht. Und wenn der nicht lädt, dann lädt auch GClh nicht. Bei mir dauert es manchmal mehrere Sekunden, bis der Header überhaupt erscheint.

In der neuen Version warten wir aber auf den GS Header, bevor Header relevante GClh Funktionen starten. Die anderen Funktionen dürfen schon früher. 
Mehrere Sekunden: Das ist GS, nicht wir. Asynchron halt.

**Comment by MagpieFourtyTwo** [comment]
Ich habe/hatte GClh auf vier Rechnern und zwei Android Smartphones laufen.
Auf allen sechsen musste ich den Update URL manuell ausführen, damit das Update erfolgte.
Ergebnis: Auf den PCs geht es wieder, auf den Smartphones nicht (egal ob "[X] Desktop Website" oder nicht).
Was kann dafür der Grund sein?

**Comment by gcPhil** [comment]
Moin zusammen,

auch von mir ein kurzes Feedback: auf meinem Windows10-Rechner hat sich GCLH im Firefox mit Tampermonkey automatisch auf 0.1.16 aktualisiert. Wenn ich GC.com besuche wird das Script als aktiv im Tampermonkey angezeigt, es greifen aber leider keinerlei Änderungen durch das Script auf der Seite. Auch nicht nachdem ich den Browsercache für gc.com gelöscht habe.

**Comment by 2Abendsegler** [comment]
@gcPhil 
Danke für das Feedback. Das scheint tatsächlich ein Problem mit dem Zwischenspeicher von Tampermonkey zu sein. 
Den Browsercache für gc.com zu löschen ist hier nicht ausreichend, weil es wohl um den Zwischenspeicher von Tampermonkey geht. 
Hättest du den kompletten Browsercache gelöscht, hätte es vermutlich danach auch funktioniert.

Kannst du bitte deine Versionsnummer von Tampermonkey posten? Danke.

**Comment by 2Abendsegler** [comment]
@MagpieFourtyTwo
> Ergebnis: Auf den PCs geht es wieder, auf den Smartphones nicht (egal ob "[X] Desktop Website" oder nicht).
> Was kann dafür der Grund sein?

- Die Browsertabs müssen alle geschlossen sein. Wenn du den Browser neu startest dürfen also keine Tabs automatisch wieder hergestellt werden.
- Hast du die Smartphones mal runtergefahren und neu gestartet?

**Comment by gcPhil** [comment]
@2Abendsegler
Danke für die Rückmeldung. Meine Tampermonkey-Version ist 4.12.6132
Kann man denn evtl auch den Cache nur für Tampermonkey löschen? 

> @gcPhil
> Danke für das Feedback. Das scheint tatsächlich ein Problem mit dem Zwischenspeicher von Tampermonkey zu sein.
> Den Browsercache für gc.com zu löschen ist hier nicht ausreichend, weil es wohl um den Zwischenspeicher von Tampermonkey geht.
> Hättest du den kompletten Browsercache gelöscht, hätte es vermutlich danach auch funktioniert.
> 
> Kannst du bitte deine Versionsnummer von Tampermonkey posten? Danke.

**Comment by 2Abendsegler** [comment]
@MagpieFourtyTwo
Noch ne Frage: Welchen Browser nutzt du auf den Smartphones?

**Comment by 2Abendsegler** [comment]
@gcPhil

> Kann man denn evtl auch den Cache nur für Tampermonkey löschen?

Gute Frage.
Womöglich hilft es das Add On zu deaktivieren. In diesem Fall müsste der Browser den genutzten Speicher des Add Ons sinnvollerweise freigeben. Das ist aber nur Theorie.

**Comment by 2Abendsegler** [comment]
**Tampermonkey Versionen:**
- 4.11.6114: 2Abendsegler, keine Probleme
- 4.12.6132: gcPhil, vermutlich "Speicherproblem"

**Comment by 2Abendsegler** [comment]
@Ruko2010, @capoaira, @MagpieFourtyTwo 
Könnt ihr bitte eure Tampermonkey Version auf euren Rechnern nachsehen?

**Comment by capoaira** [comment]
V4.12.6132

**Comment by Ruko2010** [comment]
Oh warte, es ging nur einmal kurz nach dem Update. Beim anklicken eines Links gehts dann wieder nicht mehr...

**Comment by Tabaluga1** [comment]
GClh 10.16 läuft nicht mit Chrome Version 90.0.4430.85 (Offizieller Build) (64-Bit) 

10.14 lief gestern Abend

**Comment by Tabaluga1** [comment]
same with Opera Version:75.0.3969.218 and 10.16, with TM v4.11.6120

**Comment by gcPhil** [comment]
**Noch mal Feedback:**
Bei mir lädt GCLH ein paar Logs später nun wieder gar nicht. Ein Löschen des gesamten Browsercaches brachte gerade auch keine Besserung. Ich vermute es liegt nicht am Tampermonkey sondern an GC.com.

**Comment by 2Abendsegler** [comment]
I think ColleIsarco has [here](http://geoclub.de/forum/viewtopic.php?p=1322334#p1322334) the right hint! 
I am working on it!

**Comment by 2Abendsegler** [comment]
@Ruko2010, @capoaira, @Tabaluga1 und andere

Könnt ihr bitte mal testen? 

[Das ist die Vorabversion 0.10.17.](https://github.com/2Abendsegler/GClh/blob/collector/gc_little_helper_II.user.js?raw=true)
[Hiermit kommt ihr wieder zurück zur aktuellen Version 0.10.16, falls nötig.](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true)

**Comment by diundbi** [comment]
Auf den ersten Blick scheint V17 zu funktionieren

**Comment by gcPhil** [comment]
Vorabversion 0.10.17 funktioniert auch bei mir bislang zuverlässig.

**Comment by Tabaluga1** [comment]
10.17 sieht mit Chrome gut aus

**Comment by Etaner7** [comment]
@2Abendsegler: habe mir das heute nochmals angesehen. Ich weiß jetzt, war los war...
Violentmonkey war inaktiv, Tempermonkey, wo GClh gelaufen ist, aktiv. Beim Laden der neuen Version ist es aber ins Violentmonkey geladen worden, warum auch immer. Bisher haben die autom. Updates einwandfrei über Tempermonkey funktioniert. Habe es nicht geschafft, direkt über Tempermonkey das Script zu laden, da habe ich es nicht gefunden. Habe Violentmonkey halt jetzt aktiv geschalten. Vorabversion 0.10.17 läuft jetzt gut. 
Könnte es sein, dass auch Groundspeak wieder was geändert hat? Ich habe heute wieder das alte Message center Symbol...
Vielen Dank für deinen unermüdlichen Einsatz!

**Comment by 2Abendsegler** [comment]
> Könnte es sein, dass auch Groundspeak wieder was geändert hat? Ich habe heute wieder das alte Message center Symbol...
> Vielen Dank für deinen unermüdlichen Einsatz!

Der GClh ersetzt derzeit den kompletten Header durch den alten Header inclusive dem alten Message Center Symbol.

**Comment by MagpieFourtyTwo** [comment]
> [Das ist die Vorabversion 0.10.17.](https://github.com/2Abendsegler/GClh/blob/collector/gc_little_helper_II.user.js?raw=true)

Vorab: Mit 0.10.17 geht es nun auch auf dem Android Smartphone wieder (mit Firefox Nightly und TM 4.12.6132)

Mit 0.10.16 wars so, dass GClh nach Schliessen aller Tabs zwar lief, aber sobald ein Page Rebuild durch z. B. einen Seitenwechsel (z. B. ein Cache Listing aufrufen) oder auch nur ein Refresh der aktuellen Seite erfolgte, war er wieder weg. Ans Laufen hat man ihn dann nur wieder bekommen, wenn man ...
- entweder alle Tabs geschlossen, FF aus dem Speicher geworfen, und neu gestartet hat
- oder TM deaktiviert und wieder aktivert.

In beiden Fällen hat es dann aber auch wieder nur bis zum ersten Reload/Seitenwechsel funktioniert, danach war er wieder weg.

Mit 0.10.17 geht's aber wieder wie geschmiert - jedenfalls noch.  ;)

Besten Dank!

**Comment by 2Abendsegler** [comment]
@MagpieFourtyTwo
Interessant. Danke für das Feedback.

**Comment by 2Abendsegler** [comment]
merged
