### ISSUE TITLE
[Public Profile] Change links for found/hide caches

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1636]
Change from:
`https://www.geocaching.com/play/search?types=2&a=0&sc=False&fb=user`
to:
`https://www.geocaching.com/play/search?types=2&a=0&sc=False&fb=user&sort=FoundDateOfFoundByUser&asc=False`
And From
`https://www.geocaching.com/play/search?types=2&a=0&sc=False&owner[0]=user`
to:
`https://www.geocaching.com/play/search?types=2&a=0&sc=False&owner[0]=user&sort=PlaceDate&asc=False`

Der alte Link hat eine Liste gezeigt, die nach Funddatum sortiert war. Der neue Link bietet diese Funktion nicht. Das holen wir hiermit nach.

**Comment by 2Abendsegler** [comment]
Das wird in den Release Notes massiv bemeckert. Ich glaube das wird GS selbst in den nächsten Tagen nachliefern. Warte mal noch.

**Comment by capoaira** [comment]
Ok, ist vielleicht eine gute Idee.

**Comment by capoaira** [comment]
>Das wird in den Release Notes massiv bemeckert. Ich glaube das wird GS selbst in den nächsten Tagen nachliefern. Warte mal noch.

Jip, nun ist die Funktion von GS eingebaut worden
