### ISSUE TITLE
[Public Profile] Change links to found/hide caches to the old link

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1656]
https://geoclub.de/forum/viewtopic.php?p=1322370#p1322370

Link for found: `https://www.geocaching.com/seek/nearest.aspx?ul=`
Link for Hides: `https://www.geocaching.com/seek/nearest.aspx?u=`

**Comment by 2Abendsegler** [comment]
Hast du hierfür ne Idee/Erklärung? Das liegt nicht an deinem Coding, sondern eher an GS. Da hat sich einfach einer dazwischen gemogelt.

![grafik](https://user-images.githubusercontent.com/22332216/115994784-b39f1b80-a5d8-11eb-89d0-d61810bafcfb.png)

**Comment by 2Abendsegler** [comment]
gemerged

**Ich muss noch Eintrag in Standard Konfiguration vornehmen:** 
settings_profile_old_links false

**Comment by capoaira** [comment]
> 
> 
> Hast du hierfür ne Idee/Erklärung? Das liegt nicht an deinem Coding, sondern eher an GS. Da hat sich einfach einer dazwischen gemogelt.
> 
> ![grafik](https://user-images.githubusercontent.com/22332216/115994784-b39f1b80-a5d8-11eb-89d0-d61810bafcfb.png)

Der Cache ist an der richtigen Stelle, nur das Datum ist falsch. Ich habe aber keine Ahnung wodran das liegt.
