### ISSUE TITLE
[Souvenirs] GS has now an own souvenirs sort feature. Display group of souvenirs do not work.

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#1661]
Groundspeak has updated the Souvenir Page. It is now possible to sort them, like we implemented the feature, so we should build back our implementation.
![image](https://user-images.githubusercontent.com/2239440/116138900-b16eb700-a6d5-11eb-89ae-0773915f8a68.png)

(via https://forums.geocaching.com/GC/index.php?/topic/361703-release-notes-website-and-geocaching%C2%AE-app-souvenir-sorting-april-26-2021/)

**Comment by 2Abendsegler** [comment]
Das ist aber nur auf der Seite `https://www.geocaching.com/my/souvenirs.aspx` implementiert. Im Profile ist das nicht vorhanden.
Außerdem funktionieren unsere Features alle nicht mehr. Vermutlich wurde mal wieder irgendetwas umbenannt.

**Comment by 2Abendsegler** [comment]
[On own souvenirs page:](https://www.geocaching.com/my/souvenirs.aspx) 

![grafik](https://user-images.githubusercontent.com/22332216/116205724-51602b00-a73e-11eb-98b6-23e9a75aeb1f.png)

---
[On public profile souvenirs page:](https://www.geocaching.com/profile/default.aspx?#gclhpb#ctl00_ContentBody_ProfilePanel1_lnkSouvenirs)

![grafik](https://user-images.githubusercontent.com/22332216/116205841-7359ad80-a73e-11eb-989e-79f877d6df4b.png)

**Comment by 2Abendsegler** [comment]
merged
