### ISSUE TITLE
The minimap on the cachepage. 

### ISSUE THREAD

**Issue by reodor09** [2Abendsegler/GClh#1663]
What happened to the lower minimap to show the cache location on the main cachepage? 
It used to show map of my choice, as I have in my Gecaching Map Enhacements. Now it is only a generic map with no details. 
It also showed a red line from original to corrected coordinates, that is also gone. 

Enclosed the "new" version, with corrected coordinates. No lines, no details. 

I am not sure if this is a GClh feature. If so: what is the configuration to get it back?  

![Skjermbilde 2021-04-27 kl  08 28 36](https://user-images.githubusercontent.com/10709042/116195923-1efd0080-a733-11eb-9233-f5e1d426c75b.png)

**Comment by capoaira** [comment]
The map on your image is the map by GS.
The GClh map is on the top, under the toolbar
![grafik](https://user-images.githubusercontent.com/50927164/116197169-ab5bf300-a734-11eb-8066-7c98e3b09af4.png)
The Settings are in the config in the Listing section:
![grafik](https://user-images.githubusercontent.com/50927164/116197286-d7777400-a734-11eb-85bd-a119d0563dfd.png)

**Comment by 2Abendsegler** [comment]
Maybe this is about the script Gecaching Map Enhancements. If I activate the script Gecaching Map Enhancements then a red line from original to corrected coordinates is displayed. If that's what you mean, you have to activate Gecaching Map Enhancements as well. 

![grafik](https://user-images.githubusercontent.com/22332216/116200521-b9ac0e00-a738-11eb-8465-fe3284e461ec.png)

**Comment by capoaira** [comment]
> Maybe this is about the script Gecaching Map Enhancements. If I activate the script Gecaching Map Enhancements then a red line from original to corrected coordinates is displayed. If that's what you mean, you have to activate Gecaching Map Enhancements as well.

It doesn't work for me either. 
Which setting do I have to activate? (I can't find "Geocaching Map Enhancements")

**Comment by 2Abendsegler** [comment]
"Geocaching Map Enhancements" is another script. :)
https://openuserjs.org/install/JRI/Geocaching_Map_Enhancements.user.js

**Comment by reodor09** [comment]
GME is activated. Maybe it has been a change in their script. Thank you

**Comment by 2Abendsegler** [comment]
@reodor09
You can still try to switch off all other scripts and add-ons except GClh and GME. It should actually work then. 

I will close this issue.

**Comment by capoaira** [comment]
> "Geocaching Map Enhancements" is another script. :)
> https://openuserjs.org/install/JRI/Geocaching_Map_Enhancements.user.js

Oh, I don't know this. Thanks!
