### ISSUE TITLE
GC little Helper II

### ISSUE THREAD

**Issue by trinebine** [2Abendsegler/GClh#1667]
Hallo

funktioniert nicht mehr unter Firefox? Interessanterweise aber über Edge?
Viele Grüße trinebine

**Comment by 2Abendsegler** [comment]
Hallo,
was genau funktioniert denn nicht mehr unter Firefox?
Welche Version vom GC little helper II hast du denn?
LG Frank

**Comment by trinebine** [comment]
Hallo Frank

 

Version v0.10.19

 

Bin allerdings grad mal auf die Idee gekommen nochmals neu zu installieren (update einfach anstarten brachte da nichts) und just wondering es geht wieder.

 

Da hätte ich ja schon früher drauf kommen können

 

Manchmal sitzt das Problem nur davor

 

Insofern sorry für die Umstände. Gelernt fürs nächste Mal

 

Danke für die Rückmeldung 

 

Viele Grüße

Sabine 

 

Gesendet: Mittwoch, 28. April 2021 um 12:14 Uhr
Von: "2Abendsegler" ***@***.***>
An: "2Abendsegler/GClh" ***@***.***>
Cc: "trinebine" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [2Abendsegler/GClh] GC little Helper II (#1667)


 

Hallo,
was genau funktioniert denn nicht mehr unter Firefox?
Welche Version vom GC little helper II hast du denn?
LG Frank

**Comment by 2Abendsegler** [comment]
> Manchmal sitzt das Problem nur davor

Ja genau, das kenn ich. 😂
Schön dass es wieder funktioniert.
Ich schließe das Issue dann mal.
LG Frank
