### ISSUE TITLE
[Cache listing] Print page cache listing has coords format error. 

### ISSUE THREAD

**Issue by V60GC** [2Abendsegler/GClh#1670]
Beim Klick auf auf die Print-Links wird die Seite entsprechend erzeugt. Oben steht jedoch in ROT:

GC Little Helper II Error

Improve print page cache listing: otherFormats is not defined

For more information see the console. Create a new issue / bug report at GitHub.

**Comment by 2Abendsegler** [comment]
Danke für die Fehlermeldung.

Das ist immer noch ein Fehler, der in Zusammenhang mit den Header Änderungen von GS entstanden ist.

[Hier gibt es eine Vorabkorrektur.](https://github.com/2Abendsegler/GClh/blob/collector/gc_little_helper_II.user.js?raw=true)
[Hier kannst du wieder zurück, falls notwendig.](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true)

Ich schließe das Issue.
Die Änderungen sind in der nächsten Version enthalten.
