### ISSUE TITLE
[Global] GClh does not always run if finds are null.

### ISSUE THREAD

**Issue by LittleJohn-DD** [2Abendsegler/GClh#1674]
**Describe the bug**
Habe festgestellt, dass nach dem Update von Version 17 auf 19 das Script für Basismitglieder nicht mehr ausgeführt wird.
Eine Erklärung hierfür konnte ich nicht wirklich finden.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: firefox, chrome (Edge)

**Comment by 2Abendsegler** [comment]
Hallo,

ich habe mich gerade mal mit einem Basis User angemeldet. Sieht alles ok aus und der GClh läuft auch. 

Bitte deaktiviere mal alle anderen Scripte und Add ons ausser GClh und Tampermonkey und versuchs dann noch mal.

Wenn er immer noch nicht läuft: Kannst du bitte mal die Version 19 nochmal installieren. [Hier kannst du klicken.](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true)

Wenn er immer noch nicht läuft: Dann schau bitte mal in die Console (Tasten Strg, Shift und K gleichzeitig drücken und dann Reiter Console, dort dann nur die Fehler ausgeben), ob dort ein Fehler ausgegeben wird. Poste mal bitte einen Screenshot mit geöffneter Console von deinem gesamten Browserfenster, vielleicht fällt mir dann noch etwas ein.

LG Frank

**Comment by LittleJohn-DD** [comment]
Hi, 
erstmal für die Annahme meiner Anfrage.
Habe alles bereits im Vorfeld, so wie von dir beschrieben, durchgeführt - leider keine Veränderung.
Wie gesagt, die VErsion 16 läuft (natürlich mit den Versioneinschränkungen); nach dem Update auf 19 wird zear das Script gezogen, allerdings verändert sich nichts; sprich das Script wird nicht 'ausgeführt'.
Der Konsoleneintrag wirft (leider) auch keine Fehler aus.
Bin mit meiner Weisheit am Ende ;-(. 
Wie gesagt 16 funktionert, 19 leider nicht. 
Sämtliche Einstellungen des Browser sind hier indentisch. Melde mich nur ab und mit neuem (BasisMember) an. Erneutes anmelden im gleichen BrowserTab als Premium; alles wie gewohnt, sprich GClh arbeitet.

**Comment by LittleJohn-DD** [comment]
![Image 6](https://user-images.githubusercontent.com/24999469/116531870-eb130e00-a8df-11eb-8465-f6b08c5650b2.png)

**Comment by 2Abendsegler** [comment]
Ich habe die Version 0.10.19 genommen und mal ein paar Ausgeben in die Konsole gemacht.
[Bitte installiere mal diese Version.](https://github.com/2Abendsegler/GClh/blob/a2e26cc456837cf4b0010519a41d05816972eca6/gc_little_helper_II.user.js?raw=true)
Ruf danach wieder dein Dashboard mit dem Basic Member auf und schau mal was in der Konsole ausgegeben wird.

**Comment by 2Abendsegler** [comment]
Ich schon wieder. Schau mal in deinem Screenshot, dort ist der Reiter Fehler deaktiviert. Bitte mal Fehler aktivieren und die Warnungen deaktivieren und dann nochmal schauen was in der Konsole steht.

**Comment by LittleJohn-DD** [comment]
Hast natürlich recht...  falscher Screenshot ;-(

Habe dir jetzt Wrnungen und Logs zusätzlich angefügt damit du siehst, dass etwas passiert ist. Ein Fehler taucht (leider) nicht auf.
Aber sieh slebst ....
![Image 7](https://user-images.githubusercontent.com/24999469/116542287-cbcead80-a8ec-11eb-9b14-0d16373d5c61.png)

**Comment by 2Abendsegler** [comment]
Nächster Versuch.
[Bitte installiere diese Version.](https://github.com/2Abendsegler/GClh/blob/eb83ae02ee07141afcb442029539a242ceb4fe7a/gc_little_helper_II.user.js?raw=true)
Ruf danach wieder dein Dashboard mit dem Basic Member auf und schau mal was in der Konsole ausgegeben wird.

**Comment by LittleJohn-DD** [comment]
Jetzt funktioniert das Script (prima), nun allerdings mit Fehlermeldung.
![Image 8](https://user-images.githubusercontent.com/24999469/116550827-7ea40900-a8f7-11eb-8709-4ada280bf156.png)

**Comment by 2Abendsegler** [comment]
Das ist eine Fehlermeldung von GS, da kommen ständig welche, ist also egal. 
Aber bitte zeig mir die Ausgabe in der Konsole - Log.

**Comment by LittleJohn-DD** [comment]
eine erneuter Aufruf erzeugt nun keine Fehler ... wunderbar.
Läuft erstmal augenscheinlich.

Was hast du genau gemacht/ geändert?
![Image 9](https://user-images.githubusercontent.com/24999469/116551136-e5c1bd80-a8f7-11eb-9373-a97a0e0d4a5f.png)

**Comment by LittleJohn-DD** [comment]
![Image 10](https://user-images.githubusercontent.com/24999469/116551301-16095c00-a8f8-11eb-8162-e91656804bea.png)

**Comment by 2Abendsegler** [comment]
Ich brauche noch die Log Ausgabe. :)

**Comment by LittleJohn-DD** [comment]
wie gerenriere ich die mehrzeige Ausgabe?

**Comment by 2Abendsegler** [comment]
Alles ok. Unsere Meldungen hatten sich nur überschnitten, hab alles was ich brauche.

Es hängt nicht an den Basic Member sondern an 0 Funden. Eigenartig ist nur, dass es bei mir trotzdem funktionierte. 
Ich werde jetzt das Ganze für die nächste Version einbauen. Dann musst du noch mal testen. Ich melde mich noch mal.

**Comment by LittleJohn-DD** [comment]
OK, verstanden. 
Kein Problem; DANKE

**Comment by LittleJohn-DD** [comment]
Habe mir kurzfristig einen Fund generiert und es läuft; deine Annahme also gut und richtig.

Aber was ist denn der Unterschied zwischen den Versionen? Da muss doch der Hase im Pfeffer liegen.
Fällt mir gerade noch ein ...

**Comment by 2Abendsegler** [comment]
Bei der 16 versuchten wir noch die Finds und den Username aus dem Header zu ermitteln, glaube ich. Der Header wird aber von GS asynchron geladen. Deshalb kam es immer wieder vor, dass der Header noch nicht vorhanden war, der GClh die Daten aber schon verwenden wollte.
Du musst übrigens nicht nochmal testen. Das passt auch so.
Die Änderungen werden in der nächsten Version enthalten sein. Du kommst ja bis dahin mit der temporären Version aus.

**Comment by LittleJohn-DD** [comment]
OK, verstanden, danke.
Stehe aber gerne auch Tester zur Verfügung ;-)

**Comment by 2Abendsegler** [comment]
Ok, sicherheitshalber nochmal testen. :)
[Hier die Version aus dem collector. ](https://github.com/2Abendsegler/GClh/blob/collector/gc_little_helper_II.user.js?raw=true)
Hier sind schon andere Dinge enthalten, aber egal.
Sag dann nochmal kurz bescheid, wenn du getestet hast.

**Comment by LittleJohn-DD** [comment]
Sieht gut aus, zumindest das Null-Fund Problem.

Vielleicht ein Schönheitsfehler der mit schon lange aufgefallen ist:
Im Dashboard wird der header nicht wirklich angepasst (zentriert), aber nur hier.
In der Listingdarstellung und auch im owner Dashboad wird es richtig dargestellt - wie gesagt nur ein Schönheitsfehler.

![Image 12](https://user-images.githubusercontent.com/24999469/116556586-e4938f00-a8fd-11eb-8790-3b8abdcfe229.png)
![Image 13](https://user-images.githubusercontent.com/24999469/116556592-e6f5e900-a8fd-11eb-9647-e3aee491ad30.png)

**Comment by 2Abendsegler** [comment]
Schick mir bitte noch deinen GC Usernamen, damit ich dich auf der Thanks Seite eintragen kann.

Ich schätze du hast diesen Parameter aktiviert:
![grafik](https://user-images.githubusercontent.com/22332216/116558151-6c2dcd80-a8ff-11eb-828e-8845336b79da.png)
Eine solche Ausrichtung am Content ist nicht auf allen Seiten möglich, so auch zum Beispiel auf der alten Karte und eben auch auf dem Dashboard. Hinter dem Parameter steht ein Fragezeichen, dort ist das beschrieben.

Siehe insbesondere den dritten Abschnitt.

---
With this option you can arrange the header width on the width of the content of GC pages. This is an easy feature with some restrictions, like for example the available place, especially for horizontal navigation menues.

This feature is available on GC pages in the oldest design like for example cache and TB listings, bookmarks, pocket queries, nearest lists, old dashboards (profiles), statistics, watchlists and drafts, to name just a few.

On map page and on pages in the newer and newest design it is not available, partly because the content on these pages are not yet in an accurate width, like the newer search cache page or the message center page. Also this feature is not fully integrated in the diverse possibilities of the header layout and the navigation menus. But we hope the friends of this specific header design can deal with it.

This option requires "Change header layout".

---

**Comment by LittleJohn-DD** [comment]
Ja, das stimmt - ist schon lange her.

Du brauchst mich nicht auf der Thanks Seite eintragen, ... trotzdem danke für das Angebot. 
Wenn es für euch wichtig ist, dann nimm den "CasRuLu"

**Comment by 2Abendsegler** [comment]
> Du brauchst mich nicht auf der Thanks Seite eintragen, ... trotzdem danke für das Angebot.

Das ist nur als kleine Anerkennung gedacht wenn jemand einen Fehler meldet oder etwas entwickelt. Ich lass dich dann weg.

Ich schliess dann das Issue.

**Comment by LittleJohn-DD** [comment]
OK, ich habe zu danken. !!!
