### ISSUE TITLE
[Global] Remove whitespace from search field in header.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1676]
**Is your feature request related to a problem? Please describe.**
[Global] Remove whitespace from search field in header.

Damit durch cut and paste Operationen keine Blanks vorne oder hinten im Search Feld stehen bleiben.

Improvement von ChristianGK-GC im PR #1675

**Comment by 2Abendsegler** [comment]
@ChristianGK-GC
Magst du mir noch deinen GC Usernamen sagen, dann werde ich dich auch auf der "Thanks" Seite damit eintragen. Wenn du das nicht möchtest dann werde ich deinen GitHub User eintragen, das ist auch ok.

**Comment by ChristianGK-GC** [comment]
@2Abendsegler mein GC-Nick ist ChristianGK.
Danke dir.

**Comment by 2Abendsegler** [comment]
merged
