### ISSUE TITLE
[Cache listing] Change to old search on cache listing page.

### ISSUE THREAD

**Issue by technetium** [2Abendsegler/GClh#1682]
Recently Groundspeak, inc. DBA geocaching has decided to replace the links to the classic search with links to their new and "improved" search. As many others I don't like the view of those result pages.

I've seen there is already an option to replace the links (for owned and found caches) on the profile page to the classic search. I also would like that option on the cache list page for the search to the nearest caches (that I didn't have found / of this type). Actually an option: replace all links to new search with classic search would be preferred.

An other option to randomly query the classic search pages in the background would also be nice. This has the intention to keep requests to the classic search to stay to be a large portion of search requests. So Groundspeak, Inc. DBA geocaching cannot use the excuse the old search is hardly used when they remove this search.

If Groundspeak, Inc. DBA geocaching will remove the classic search (or even before that) an option to restore the layout of the new search to the classic search is welcome.

**Comment by 2Abendsegler** [comment]
Development hint: One of the link will use to determine the real owner of the cache. So we have to change there something also.

**Comment by 2Abendsegler** [comment]
@capoaira 
Ich übernehme den mal, damit der bei der nächsten Version mit dabei ist.

**Comment by 2Abendsegler** [comment]
Info for changelog:

The links to find caches run through the new search. With this option you can use the old search.
![Screen08](https://user-images.githubusercontent.com/22332216/118348601-c52a7200-b54b-11eb-822c-6298a3c70c4f.jpg)

The following links are changed:
![Screen07](https://user-images.githubusercontent.com/22332216/118348598-c22f8180-b54b-11eb-8a2f-383b04b57559.jpg)

Example for using the old search:
![Screen09](https://user-images.githubusercontent.com/22332216/118348604-c8256280-b54b-11eb-9ce4-19022c756613.gif)

**Comment by 2Abendsegler** [comment]
The changes come with the next version.

---
merged

**Comment by technetium** [comment]
Thanks, I've just upgraded to V0.11.1
I can confirm it works.
