### ISSUE TITLE
[Global] Break of the Linklist in the header with horizontal menu.

### ISSUE THREAD

**Issue by Arnos99** [2Abendsegler/GClh#1686]
Obwohl im Header genügend Platz ist, werden Links in einer zweiten Zeile angezeigt.
Siehe Screenshot.
LG Arnos99

![Screenshot_2021-05-02 Dashboard](https://user-images.githubusercontent.com/61402751/116821072-ae157880-ab78-11eb-8e16-9db46e48af32.png)

**Comment by 2Abendsegler** [comment]
Moin,

sieht blöd aus. 😁

Ich habe erfolglos versucht die Situation nachzustellen. Das Vertikale Menü fristet aber auch ein Schattendasein weil niemand von uns dieses Menü nutzt. 

Vorschlag: 
- Ändere deine Homekoordinaten im Config ab, ich möchte die nicht sehen. 
- Vielleicht löschst du auch deine VIPs, wenn du eine Sicherung deiner Einstellungen hast, die gehen mich ja auch nichts an. 
- Dann kannst du mit F10 in den Sync gehen und dort einen Download deiner Einstellungen machen. 
- Schick mir die Datei an meine Mailbox eifra(at)web.de . 

Vermutlich wird das Problem dann auch bei mir sichtbar und ich kann es beheben.

LG Frank

**Comment by Arnos99** [comment]
Moin Frank,
danke für die schnelle Antwort.
Die Mail an Dich ist versandt.
Du schreibst das Vertikale Menü....., aber geht es hier nicht um das Horizontale Menü im Header?
Lg Arne

**Comment by 2Abendsegler** [comment]
> Du schreibst das Vertikale Menü....., aber geht es hier nicht um das Horizontale Menü im Header?

😂 Genau ... es war noch früh.

**Comment by 2Abendsegler** [comment]
Ich hatte angenommen, dass es sich hier um einen Bug handelt, der im Rahmen der Headerumstellung entstanden ist. Im Moment würde ich aber eher sagen, dass der Effekt schon immer so war. 
Frage 1: War das nicht schon immer so?

Nicht alle Seiten haben eine variable Breite, die sich der tatsächlichen Bildschirmbreite anpasst. Beispiel: Cache Listing. Hier wird die im Config hinterlegte Breite (Page width) von 950 px angewendet. Wenn der Bildschirm breiter ist, sieht es so aus, als ob mehr Platz zur Verfügung steht für das Menü. Tatsächlich muss der Header aber auch für die hinterlegte Breite von 950 px funktionieren. 
Wenn du mal in ein Cache Listing gehst und dann das Browserfenster zusammenschiebst, dann wirst du den Effekt sehen den ich meine. 

Frage 2: Wenn du einen breiteren Bildschirm hast, warum erhöhst du dann nicht Page width entsprechend? 
Dadurch ist das Listing nicht so in die Länge gezogen sondern nutzt die Breite des Bildschirms besser aus, und im Menü steht mehr Platz zur Verfügung. Versuchs mal mit 1100 px oder so.

Tatsächlich könnte man das Problem vermutlich auch im Script beheben, das ist aber ein Thema an das ich sehr ungern rangehen möchte.

**Comment by Arnos99** [comment]
Ich hatte im Header immer alle Links in einer Zeile, erst nach dem letzten Update ist es zweizeilig geworden.
Hab an der Config keine Veränderungen vorgenommen.
Wenn ich die 950 px auf zB. 1100 ändere, werden die Listings der Caches so in die Breite gezogen, das man das Hintergrundbild des Listings nicht mehr sieht.
Es muss mit dem letzten Update, irgendeine Änderung im Header stattgefunden haben.
Eine Freundin von mir, hat das gleiche Problem im horizontalem Header.

**Comment by 2Abendsegler** [comment]
Also zwischen Version 0.10.19 und 0.10.20 oder eine Update der letzten 2 bis 3 Wochen.

**Comment by Arnos99** [comment]
Genau, zwischen Version 0.10.19 und 0.10.20.

**Comment by 2Abendsegler** [comment]
Eigentlich ist die Funktionalität eines variabel langen Menüs einem Programmfehler geschuldet. So war das nie beabsichtigt. Da wir aber bestehende Funktionalität nicht mehr wegnehmen, belassen wir es so.

[Hier gibt es eine Vorabkorrektur. ](https://github.com/2Abendsegler/GClh/blob/collector/gc_little_helper_II.user.js?raw=true)

Bitte schließe das Issue wenn der Fehler behoben ist.

LG Frank

---
Das variabel lange Menü wurde durch einen Fehler im Coding der CSS Aufbereitungen ermöglicht. Der Fehler führte dazu, dass nachgelagertes CSS Coding nicht mehr verarbeitet werden konnte. 

Coding zu 0.10.19 und wohl auch schon ne ganze Weile davor: Fehler ist das ; in der zweiten Zeile. Das muss vor die Klammer. "Menü nicht flex" ... wurde deshalb nicht verarbeitet.
```
// Schriftfarbe Search Field.
"#navi_search {color: #4a4a4a};" +
// Menü nicht flex.
".#m {display: unset;}" +
```

Coding zu 0.10.20: Im Zuge der Erweiterung wurde auch der Fehler beseitigt.
```
// Schriftfarbe Search Field.
"#navi_search {color: #4a4a4a;} #navi_search:focus {outline: none;}" +
// Menü nicht flex.
".#m {display: unset;}" +
```

**Comment by Arnos99** [comment]
Vielen Dank für die schnelle Hilfe, jetzt ist alles wieder ok, Fehler wurde behoben.
LG Arne
