### ISSUE TITLE
Message center: "Press enter to send" ignored when GClh is active?

### ISSUE THREAD

**Issue by waldmeisterx** [2Abendsegler/GClh#1690]
**Describe the bug**
When GClh is active, the checkbox "Press enter to send" in the Message Center is ignored or is reset after hitting enter.

**To Reproduce**
1. Go to 'Message Center'
2. Select a Cacher
3. Remove the checkbox "Press enter to send"
4. Enter Text in Textbox
4. Hit Enter or Shift-Enter
5. The text is sent immidiately

**Expected behavior**
If checkbox is removed I would expect to enter line breaks with enter or shift-enter instead of sending immidiately.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2 x64
 - Browser: Brave 1.23.75
 - GC Settings / Preferences / Language = English (!)

If test person is needed, feel free to contact me in GC Message Center ;-)

**Comment by 2Abendsegler** [comment]
Moin,

danke für die Nachricht.

Das ist glücklicherweise kein GClh Problem. Versuch bitte mal ohne GClh. Wenn die Checkbox einmal aktiviert ist, dann läßt sie sich nicht mehr deaktivieren. Das ist ein bekannter Bug der Webseite seit 12. April, siehe [hier](https://forums.geocaching.com/GC/index.php?/topic/361417-message-center-bug/).

LG Frank

**Comment by waldmeisterx** [comment]
Hi Frank,

ok, kein Ding, Danke für das schnelle Feedback.
Dann mache ich hier gleich wieder dicht und werde das mal drüben "beobachten".

LG
Dirk
