### ISSUE TITLE
[Global] Sign out does not always work.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1711]
Details see [geoclub](https://forums.geocaching.com/GC/index.php?/topic/343005-gc-little-helper-ii/&do=findComment&comment=5887800).

**Comment by Ruko2010** [comment]
Ich hab das auch mal versucht, aber nachstellen kann ich es auch nicht.

**Comment by 2Abendsegler** [comment]
Tests waren erfolgreich.
Änderungen wurden gemerged.
