### ISSUE TITLE
listing text "underflows" the right column

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#173]
After today's GClh release I noticed text going under the right column. The screenshot taken at [B-17 going down](https://coord.info/GC1GP8M), page width = 1200 px, FF 51.0.1.

![2017-02-25_gclh_listing_overflow](https://cloud.githubusercontent.com/assets/9153595/23334741/9ffa1bd4-fba5-11e6-9ad5-ed3ad14819ba.png)

**Comment by Chilebeer** [comment]
Same issue here, no matter the selected width the description flows under the right column after last update, Chrome v56.

**Comment by 2Abendsegler** [comment]
Sorry, but you are to late, this issue is already fixed. :)) https://github.com/2Abendsegler/GClh/issues/169
Update comes tomorrow, I hope.

(This bug is not coming with the actual version. It was already there with v0.3.)

**Comment by PontiacCZ** [comment]
You're lightning-fast. :-)

**Comment by Chilebeer** [comment]
Thank You!! 

    On Saturday, February 25, 2017 3:48 PM, PontiacCZ <notifications@github.com> wrote:
 

 You're lightning-fast. :-)—

**Comment by PontiacCZ** [comment]
I confirm that this issue is fixed.
