### ISSUE TITLE
[Listing] Open map links from overview map with left mouse click optional in new browser tab.

### ISSUE THREAD

**Issue by LittleJohn-DD** [2Abendsegler/GClh#1748]
Könntet ihr im listing der neuen 'Funktion' (map_overview_browse_map) in der Kartenübersicht ein target='_blank' spendieren?!?
Aktuell in Zeile 3006 und 3009 bei Version 0.11.2.

**Comment by 2Abendsegler** [comment]
Mit linker Maustaste neuen Browser Tab öffnen, richtig? 
Können wir optional machen. Steuerbar über einen Parameter im Config.

**Comment by LittleJohn-DD** [comment]
Ja, so meinte ich das ... mit der config Steuerung wäre das natürlich optimal.

Gibt es bei euch eine Nomenklatur bzgl. der Titelbeschreibungen?

**Comment by 2Abendsegler** [comment]
Ok, machen wir.

> Gibt es bei euch eine Nomenklatur bzgl. der Titelbeschreibungen?

Nicht wirklich. 😄

- Titel möglichst präzise in aller Kürze benennen. Man soll hier schon möglichst genau wissen worum es geht.
- Wir hatten uns angewöhnt mit den eckigen Klammern den Bereich um den es geht anzugeben, also so was wie [Listing]. Das sticht halt etwas ins Auge und wir versuchen die Issues mit den gleichen Eckigen auch zusammen im Changelog zu beschreiben. Halt so damit man möglichst alles zu einem Thema zusammen hat.
- Und dann halt in Englisch, damit es jeder oder eben auch niemand versteht. 😂 

Das ist aber kein Problem wenn was nicht passt. Das Nötige machen wir dann noch.

Eigentlich sollte auch die Beschreibung im Dokument in Englisch sein, aber wir halten uns auch nicht immer daran. Gerade wenn es schnell gehen muss, schtruddeln wir da auch rum.

**Comment by 2Abendsegler** [comment]
Die Änderungen sind noch nicht gemerged, aber schon verfügbar. Es sind aber auch schon andere Sachen mit dabei.
Wenn du willst ... dann gibt es das [hier](https://github.com/2Abendsegler/GClh/blob/da684fa024881199342bc0339200dc2f1bdc8d2a/gc_little_helper_II.user.js?raw=true).

**Comment by LittleJohn-DD** [comment]
Prima, danke.
Dann werde ich mich das nächste Mal in Englisch versuchen ;.).
Vielleicht noch eine kleine Anregung. Ich würde die icos mit hellem Hintergrund darstellen und dann den mouseover effekt einsetzen, dass passt dann auch besser zu den +/- Schaltern in der Ansicht.

**Comment by 2Abendsegler** [comment]
> Ich würde die icos mit hellem Hintergrund darstellen und dann den mouseover effekt einsetzen, dass passt dann auch besser zu den +/- Schaltern in der Ansicht.

Ich hatte es zu Begin genau so gehabt. Ich habe dann einige Tage damit hantiert und fand dann eigentlich dass zu viel Gedöhns auf der Minikarte ist. Und dann hatte ich mich daran erinnert wie ich es auf der google Karte gemacht habe. Da sind die Links auch transparent. Ich will ja keinen Designpreis gewinnen. 😄

Du kannst doch auch ein wenig programmieren, so weit ich mich erinnere. Das wär doch ne nette kleine Arbeit zum Einstieg, steuerbar über Config Parameter. 😊

**Comment by 2Abendsegler** [comment]
merged

**Comment by LittleJohn-DD** [comment]
Guten Morgen und einen schönen Start in den Tag,

Sorry, konnte gestern nicht mehr antworten.

Ja, dein Gedächtnis ist leider zu gut ;-).
Könntzest du mir ggf. ei e Anleitung an die Hand geben, wie man das auf github macht?

VG
Patrick

**Comment by 2Abendsegler** [comment]
Guten Morgen, dir auch einen schönen Start in den Tag.
 
Kein Problem.
Und ich wollte dich nicht auffordern etwas zu tun was du nicht möchtest. Das soll etwas Spaß machen und kleine Erfolgserlebnisse bescheren. Keine Verpflichtung.
 
Ich bin kein guter Ansprechpartner für die Verfahrensweise, weil bei mir ja alles anders ist wie für alle anderen. Das ist ja mein GitHub Account, da kann ich direkt Änderungen / Entwicklungen vornehmen. 
 
Alle anderen müssen ihre Änderungen auch auf ihrem eigenen GitHub Account durchführen. Das heißt du musst dir zuerst mal die Sourcen von mir holen, das nennt sich forken - das 'r' wird nicht gesprochen. Dann entwickelst du auf diesem Fork in deinem eigenen GitHub Account, oder so. 
 
Das geht so lange bis deine Änderungen fertig sind. Dann schiebst du mir das Ganze wieder per Pull Request zurück auf meinen Account. Ich schaue mir den Pull Request mit deinen Änderungen an und spiele die Sourcen dann in meinen Account ein.
 
Ruko2010 hat eine ziemlich gute Anleitung verfasst, wie dieses Prozedere geht. Wenn du es ein oder zwei Mal gemacht hast, geht das in wenigen Sekunden. Wenn man mal den Überblick gewonnen hat, dann ist es ziemlich einfach.
Hier mal der Link zur Anleitung: 
https://github.com/2Abendsegler/GClh/blob/master/docu/how_to_contribute.md#de
 
Schau es dir mal an wenn du Lust hast. Fragen gerne an mich oder an Ruko2010. Hier auf meinem GitHub gibt es ein Issue "Discussion" (https://github.com/2Abendsegler/GClh/issues/1132), das für ein wenig Abstimmung genutzt werden kann. Dein hiesiges Issue ist auch ok. Wenn mal ein Pull Request da ist, kann man die Kommunikation auch dort machen. Das sieht nicht viel anders aus als ein Issue.
 
Schau es dir mal an wenn du Lust hast dich mit ein paar Zeilen im Coding zu verewigen.
 
Liebe Grüße
Frank

**Comment by LittleJohn-DD** [comment]
Hallo Frank,

das hatte ich auch nicht so aufgefasst.

Bin leider sehr stark eingebunden und kann nicht immer gleich reagieren 🙄. 

Danke für den Link, ich schaue mir das mal an und melde mich.

VG 
Patrick

**Comment by LittleJohn-DD** [comment]
Hallo Frank,

ich habe heute mal probiert und die kltzekleine Änderung gemacht.
Hast du das schon gesehen, bzw. wie bekomme ích mit, dass du das übernommen hast?

VG
Patrick

**Comment by 2Abendsegler** [comment]
Hallo Patrick,

wo hast du denn eine Änderung gemacht? Vermutlich ja nur auf deinem Account.

Es ist so, dass ein paar Leute, mich eingeschlossen, über alles Neue auf meinem GitHub Account (Nachrichten, Issues, Pull Requests (PR), Reviews ...) per Mail informiert werden und dann auch irgendwann reagieren. Auf meinem Account kommen Programme und andere Dateien nur an, wenn du etwas explizit rüberschickst per PR. Oder du kannst Dinge wie Beiträge in Issues oder PRs mit der Hand am langen Arm direkt bei mir im Account erfassen. 

Wenn du etwas per PR rüberschickst, dann sollte das aus deiner Sicht fertig sein und zum Review anstehen. Abstimmungen sollten dann über das zuvor regelmäßig zu öffnende Issue passieren.

Verstehst du? Bei den ganzen Dateien ... musst du tätig werden per PR, sonst bekomme ich davon nichts mit.

Auf der anderen Seite bekommst du in der Regel von allem etwas mit, was mit einem Issue oder einem PR passiert, das du bei mir aufgemacht hast bzw. den du zu mir rübergheschickt hast.

Ich weiß also im Moment von nichts und bin vollkommen unschuldig. 😂   

In der Regel macht es keinen Sinn zu versuchen etwas an einem bereits geschlossenes Issue oder PR zu machen. Das Zeug ist fertig und wird auch in der Regel nicht wieder geöffnet, so wie hier.

Wenn du etwas ändern möchtest, dann solltest du es vorher über ein Issue an uns herantragen, dann besprechen wir es und dann kannst du in der Regel deine Änderungen am Code per PR zu mir rüberschieben.

Also, du hast jetzt schon eine Aufgabe. Das genügt zuerst mal. Kämpf dich dort mal etwas durch. :)
Und dann sehen wir weiter ...

LG Frank

**Comment by LittleJohn-DD** [comment]
Hallo Frank,

kannst du mir bitte mal sagen, wie du das Video gemacht hast, bzw. welches tool du dafür nutzt.

VG
Patrick

**Comment by 2Abendsegler** [comment]
Hey, das ist GifCam. 
https://www.chip.de/downloads/GifCam_79573073.html

**Comment by LittleJohn-DD** [comment]
👌👌👌👌👏👏👏👏 DANKE

**Comment by LittleJohn-DD** [comment]
Hallo Frank, 
leider weiß ich nicht, wie ich dich hier direkt anschreiben kann🙄.
Deshalb auf diesem Umweg ...

Habe mal wieder etwas im Script angepasst (mit dem Desktop Client) - nur Kosmetik, Kleinigkeiten.

Geändert habe ich, dass im unteren Übersichtsfenster eine Möglichkeit besteht in die alte Kartenübersicht zu springen, sowie das man im PersonalCacheNote die Schriftart auf monospace auswählen kann. Sicherlich Geschmackssache, ...

Jetzt zur eigentlichen Frage:
Wie soll/ kann/ darf ich das hochladen? Bin noch nicht so ganz fit mit den Clients, sorry.
Habe einen Fork erstellt (wie beschrieben).

Kannst du bitte nochmal helfen!!!???

Danke
Muss ich das über diesen Weg machen?
![grafik](https://user-images.githubusercontent.com/24999469/127465973-5fe4f493-5ebc-47ea-8a2d-d0ae91541d27.png)

**Comment by 2Abendsegler** [comment]
Moin,

wenn du in GitHub jemanden direkt ansprechen möchtest, dann kannst du das mit `@Username` mache. Für mich also beispielsweise `@2Abendsegler`.

Fragen jeglicher Art kannst du bei den [Diskussionen](https://github.com/2Abendsegler/GClh/discussions) stellen.

Wir benötigen eigentlich ein Issue und einen Pull Request, oder wenigstens einen Pull Request für jede einzelne Anpassung, um im Changelog auf etwas verweisen zu können, wo gegebenenfalls dann noch weitere Details stehen. Außerdem macht das auch deshalb Sinn, weil wir dann kleine Einheiten haben, um im Fehlerfalle die Änderungen schnell überblicken zu können. 

Für deine Anpassungen wäre also folgende Vorgehensweise richtig:
1. Issue für Anpassungen in unterer Übersichtskarte
2. Pull Request für Anpassungen in unterer Übersichtskarte und Verweis auf Issue 
3. Issue für Anpassungen in Personal Cache Note 
4. Pull Request für Anpassungen in Personal Cache Note und Verweis auf Issue

Da du die Anpassungen vermutlich gemeinsam in einer Branche gemacht hast, kannst du nur einen Pull Request für beide Anpassungen erzeugen. Also mach bitte die Punkte 1. und 3. und erzeuge einen gemeinsamen Pull Request für beides. Gib im Pull Request dann bitte die beiden Issues an, also so etwas wie `#1234`, damit wird ein Verweis auf die Issues erzeugt.

Wie du über den Desktop Client vorgehen musst, weiß ich auch nicht. Vielleicht kann @capoaira da Hilfestellung geben (capoaira ist im Moment womöglich nicht verfügbar, deshalb kann das einige Tage dauern).

LG Frank

**Comment by capoaira** [comment]
Moin,
Ja, genau. Dort (lila markiert) machst du den commit. Dann klickst du auf die Schaltfäche wo jetzt "Refresh origin" steht. Beim Namen solltest du irgendwas eindeutiges schreiben.

Mir fällt auf, dass du 4 neue Dokumente hinzufügst, dass ist sicherlich nicht deine Absicht. Gucke mal, das alle deine Änderungen im richtigen Script sind und schmeiße dann die anderen weg ;)

Wenn noch etwas unklar ist, oder du andere Fragen hast, kannst du gerne Fragen. Meine Antworten werden aber erstmal recht kurz ausfallen, da ich unterwegs bin.

**Comment by LittleJohn-DD** [comment]
OK, vieln Dank erstmal.
Soll

> 
> 
> Moin,
> Ja, genau. Dort (lila markiert) machst du den commit. Dann klickst du auf die Schaltfäche wo jetzt "Refresh origin" steht. Beim Namen solltest du irgendwas eindeutiges schreiben.
> 
> Mir fällt auf, dass du 4 neue Dokumente hinzufügst, dass ist sicherlich nicht deine Absicht. Gucke mal, das alle deine Änderungen im richtigen Script sind und schmeiße dann die anderen weg ;)
> 
> Wenn noch etwas unklar ist, oder du andere Fragen hast, kannst du gerne Fragen. Meine Antworten werden aber erstmal recht kurz ausfallen, da ich unterwegs bin.

Danke erstmal für die schnelle Antwort. Das reicht mir erstmal. 
Schiebe das jetzt mal so an und hoffe, dass das dann so passt.

Schönen Urlaub ...

**Comment by LittleJohn-DD** [comment]
Habe gerade wohl Mist geb(r)aut.
Der pull request ist wohl auf closed gesetzt 🙄🥺

**Comment by 2Abendsegler** [comment]
Ist wieder open. 😊

**Comment by LittleJohn-DD** [comment]
DaNke SchOen ;-)

Hoffe, das mit den issues ist auch so in Ordnung...
