### ISSUE TITLE
[Global / Chrome] Script does not start sometimes under Google Chrome.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1760]
[Global / Chrome] Script does not start sometimes under chrome.

Der Fehler mit dem `switch` Code in #1743 ist seit v0.11.2 released, das ist seit 6 Tagen. Scheinbar lief es bisher ok. So weit ich mich erinnere lief es aber nach einer neuen Version immer ein paar Tage ok.

Bei der damaligen Anpassung ließ sich eindeutig feststellen, dass es an diesem Code lag, weil ich mehrfach mit und ohne die Anpassung getestet habe.

Insofern muss es sich um ein weiteres Problem handeln. 
Oder die externe Programmbibliothek `jquery-ui.min.js` ist ebenfalls betroffen weil auch dort der `switch` Befehl verwendet wird.

**Comment by 2Abendsegler** [comment]
Info über Probleme kamen erneut aus dem [Swiss Geocaching Forum](https://www.swissgeocacheforum.ch/forum/topic/12872-gc-little-helper-ii/?do=findComment&comment=77431).

**Comment by 2Abendsegler** [comment]
Könnte gut sein, dass das Problem erst seit dem letzten Update von Windows 10 Pro vorhanden ist.

Aktuelle Systemumgebung:
Chrome: Version 90.0.4430.212 (Official Build) (64-bit)
OS: 
Edition Windows 10 Pro
Version 20H2
Installed on 05.‎04.‎2021
OS build 19042.985
Experience Windows Feature Experience Pack 120.2212.2020.0

**Comment by DieBatzen** [comment]
Probleme mit Chrome habe ich auch schon eine ganze Weile, möglicherweise ist die Ursache die selbe:

- Nach jedem Chrome-Neustart funktioniert kein Skript mehr, obwohl alle im Tampermonkey als aktiv gelistet sind
- Deaktivieren des GCLH und Seite neuladen hilft dahingehend, dass zumindest alle anderen Skripte wieder ausgeführt werden

Zwei Lösungen, die bei mir funktionieren:

1. In den Tampermonkey-Einstellungen ganz nach unten Scrollen und "Neustart": Nachdem die Seite neu geladen ist, funktionieren alle Skripte wieder, inkl. dem GCLH
2. In den Chrome-Einstellungen "Beim Start" die Option "Neuer Tab-Seite öffnen". Damit werden zuletzt geöffnete Seiten nicht mehr automatisch geladen.
 
Bei mir ist die Chrome-Einstellung dauerhaft geändert, damit sind alle Probleme in Chrome verschwunden.

Die Ursache scheint ein Bug im Tampermonkey zu sein:
[https://github.com/Tampermonkey/tampermonkey/issues/1215#issuecomment-819839691](https://github.com/Tampermonkey/tampermonkey/issues/1215#issuecomment-819839691):
wenn ein Skript sowohl eine @require als auch eine @resource Anweisung enthält und gleichzeitig Chrome eine GC-Seite beim Start automatisch lädt, dann geht nichts mehr.

Die gute Nachricht ist, dass der Bug in der Tampermonkey-Beta-Version bereits gefixt ist.
Von daher ist zu überlegen, ob es sich lohnt hier noch weitere Zeit zu investieren.

**Comment by 2Abendsegler** [comment]
@DieBatzen 
Super Info, danke dir.

**Comment by 2Abendsegler** [comment]
Im Swiss Forum ist die Info und ein Link zu hiesiger Nachricht nun auch.

**Comment by 2Abendsegler** [comment]
Only affects the Google Chrome browser: 
The problem should be solved with Tampermonkey version 4.13 for Google Chrome. Please upgrade your Tampermonkey to version 4.13 or higher.
