### ISSUE TITLE
[Owner Dashboard] GClh does not work after changing view

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1761]
**To Reproduce**
1. Go to 'https://www.geocaching.com/play/owner' =>Cachestypes are linked
2. Click on 'Publish hides' (or any other list of own caches)
3. Go Back 
4. See error => Cachetypes aren't linked

**Expected behavior**
The Cachetypes should be allways linked

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/119258491-1e3c7a80-bbca-11eb-9487-26f96ca79cda.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 11.03

**Additional context**
Das Problem hatte ich bei der Entwicklung schonmal, da konnte ich es aber beheben. Es liegt an der asynchronen Verarbeitung von GS. Die Seite wird nicht neu geladen, wenn man Zwischen dem COD und den Listen wechselt. Deswegen wird auch der GClh nur einmal geladen. Ich denke irgendeine Änderung (evt. die, die auch bei GS zu problemen geführt hat) macht nun dem Mutation Observer probleme.

**Comment by 2Abendsegler** [comment]
Es sind nicht nur die Links die fehlen. VIP, VUP, Mail fehlen auch. Und es ist auch einiges verschoben.

**Comment by 2Abendsegler** [comment]
Ich habe erfolglos versucht nach dem Browser Zürck den Mutation Observer zu einer Reaktion zu bewegen.

**Comment by 2Abendsegler** [comment]
Merged with #1782
