### ISSUE TITLE
[Search Map] Space around the header without "Change header layout".

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1762]
**To Reproduce**
1. Go to 'Search Map'
2. See error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/119260196-0668f480-bbd2-11eb-8b05-7efee1afce78.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 11.03

**Comment by 2Abendsegler** [comment]
Danke für die Fehlermeldung.

Das ist die Ausrichtung des Headers nach dem Content. Das ich mich darauf eingelassen habe, fällt mir immer wieder in den Rücken. Bis vor ein paar Tagen funktionierte das zu Recht nicht auf dieser Seite weil ein Content quasi nicht vorhanden war und die maximale Breite der Seite genutzt wurde. Ich weiß es deshalb weil ich mich noch mit jemandem darüber ausgetauscht hatte. Hier muss GS was geändert haben. Was ein Dreck.

**Comment by capoaira** [comment]
Ich habe gearde mal etwas rumpropiert. Das Problem scheint der Hintergrund des `.app-content` zu sein, der vor dem `gclh_nav` ist. Wenn man dem `gclh_nav` ein `position: fixed` und `z-index: 1006` gibt, ist bei mir das Problem gelöst. Mann kann auch bei `.app-content` die Hintergrundfarbe entfernen. Allerdings habe ich beides nicht auf anderen Seiten getestet.

**Comment by 2Abendsegler** [comment]
Deinen Kommentar hier habe ich gesehen.

**Comment by 2Abendsegler** [comment]
Merged with #1769
