### ISSUE TITLE
[Owner Dashboard] Set Link to Profile does not work

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1765]
**To Reproduce**
1. Go to 'https://www.geocaching.com/play/owner/'
2. Try to click on your username (under your profile image)
3. See error

**Expected behavior**
There should be a link to your own public profile

**Additional context**
Der Mutationen Observer feuert nicht mehr so oft wie vorher. Der Bug besteht wahrscheinlich schon länger (evtl. seit dem die neuen Seiten einmal nicht mehr funktionert haben)

**Comment by 2Abendsegler** [comment]
Merged mit  #1766.
