### ISSUE TITLE
[Cache Listing] Upvote buttons and log edit button are not displayed for basic members. 

### ISSUE THREAD

**Issue by LittleJohn-DD** [2Abendsegler/GClh#1792]
Habe wieder eine Diskrepanz zwischen Premium und Basic Member festgestellt.

Als Premium werden die Parameter aus der config Datei richtig umgesetzt, als Baisc Member nicht.
Insbesondere der link zum Bearbeiten eines Logs wird ausgeblendet egal welche Einstellung in der config Datei ausgewählt wurde.

Vielleicht schau ihr euch das mal an.

Windows: 10
Browser: Edge and Firefox

![Image 5](https://user-images.githubusercontent.com/24999469/120454539-42e7dd80-c394-11eb-9876-6f7a14bbcb65.png)

---
![Image 6](https://user-images.githubusercontent.com/24999469/120454541-44190a80-c394-11eb-9b4e-069b40401909.png)

---
![Image 7](https://user-images.githubusercontent.com/24999469/120454544-44b1a100-c394-11eb-925d-97f6b68b4f97.png)

**Comment by 2Abendsegler** [comment]
- [ ] Für die Upvotes, bestehend aus den beiden Buttons und Order by, wird anhand von Order by bestimmt, ob die Upvotes angezeigt werden. Order by steht für die Basismember nicht zur Verfügung. Das wusste ich gar nicht.
Das muss korrigiert werden.
- [ ] Beim Edit Button hat wohl GS das Template und/oder die Variablennamen geändert. Das konnte ich auf die Schnelle nicht finden. Unsere Prüfungen ob ein User mit dem User des Logs übereinstimmt gehen ins Leere.
Das ist auch ein Bug.

**Comment by LittleJohn-DD** [comment]
👍

**Comment by 2Abendsegler** [comment]
@LittleJohn-DD 
Die beiden Dinge sind korrigiert.
Kannst du bitte auch noch testen?
[Hiermit](https://github.com/2Abendsegler/GClh/blob/2800f33beddaa528f2552e26e3b86dfed897246d/gc_little_helper_II.user.js?raw=true) kommst du zu den Änderungen.
[Hiermit](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true) wieder zurück zur aktuellen Version.
Danke.

**Comment by LittleJohn-DD** [comment]
Sieht sehr gut aus, danke für deine Mühen.
Ging ja echt schnell, du weißt wohl aus dem Kopf wo alles steht 😉

Einen schönen Abend

**Comment by 2Abendsegler** [comment]
Dir auch einen schönen Abend. 😊

---
Merged mit #1793
