### ISSUE TITLE
[Search Map] Problems between GClh and Send to c:geo.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1796]
**Describe the bug**
[Search Map] Problems between GClh and Send to c:geo.
If both scripts are running on the search map, the cache details hang and also the map itself, it can no longer be moved. And bowser tab shows no more reaction.
Actual master. 

**To Reproduce**
1. Go to https://www.geocaching.com/play/map/
2. Click on a cache icon on the map
3. The detail screen hanging

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22332216/120902080-9bda9e80-c63e-11eb-906b-08f9b9531fe5.png)

**Additional context**
The following lines in GClh cause problems. But that's not all lines.
```
                    addCopyToClipboardLink(this, null, "GC Code", "margin-right: 3px;");
...
                insertAfter(searchmap_sidebar_enhancements, (document.getElementsByClassName("geocache-owner")[0] || document.getElementsByClassName("gclhOwner")[0]));
```

**Comment by 2Abendsegler** [comment]
@capoaira 
Kannst du dir das vielleicht mal ansehen?
Bitte dann über branch collector-bugs behandeln.

**Comment by capoaira** [comment]
Jip, ich gucke mir das an

**Comment by capoaira** [comment]
Ich glaube ich habe das Problem bei s2cg gefunden. Kannst du mal [https://github.com/capoaira/send2cgeo/raw/new-map/problem-with-gclh/send2cgeo.user.js](https://github.com/capoaira/send2cgeo/raw/new-map/problem-with-gclh/send2cgeo.user.js) testen?
[Hier](https://github.com/cgeo/send2cgeo/raw/release/send2cgeo.user.js) gehts zurück zur release Version von s2cg

**Comment by 2Abendsegler** [comment]
Nee, die Karte bleibt immer noch so stehen wie vorher. :(

**Comment by capoaira** [comment]
Ok, dann werde ich morgen weiter gucken

**Comment by 2Abendsegler** [comment]
Ja, super. Die Anpassungen mit Prüfung auf geänderten GC Code laufen prima.
Danke.

**Comment by 2Abendsegler** [comment]
Falls ich noch auf der s2cg Plattform testen soll, gib Bescheid.

**Comment by capoaira** [comment]
Ich habe bei send to c:geo einen PR aufgemacht und hoffe, dass er dort schnell gemerged wird.

**Comment by 2Abendsegler** [comment]
Das Issue werden wir mit ins Changelog nehmen.
Hab es wieder in den Milestone aufgenommen und auf status on hold gesetzt. Sobald das Teil bei s2cg gemerged ist, kann es hier auf status fixed gesetzt und geschlossen werden.

**Comment by capoaira** [comment]
Ok

**Comment by Lineflyer** [comment]
s2cg Script ist aktualisiert und verfügbar (Version 2021.06.06)

**Comment by capoaira** [comment]
Gerne, war ein gutes Teamwork mit 2Abendsegler um den Fehler zu finden und zu beheben.

merged

**Comment by 2Abendsegler** [comment]
Merged with https://github.com/cgeo/send2cgeo/pull/135
