### ISSUE TITLE
Additional geoservices (OSM, Flopp's Map, GeoHack) from GC Map

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#180]
Added links to
* Openstreetmap
* Flopp's Map
* GeoHack
into GC Map link Google Map button

**Comment by CachingFoX** [comment]
GC Map
![grafik](https://cloud.githubusercontent.com/assets/1838534/23529746/090c9c3a-ff9f-11e6-99d6-d44a34a84e01.png)

Settings
![grafik](https://cloud.githubusercontent.com/assets/1838534/23529650/a37bc86e-ff9e-11e6-8bf6-a37317e227e0.png)

**Comment by 2Abendsegler** [comment]
Das sieht schon mal echt professionell aus auf der Karte!

Bitte spiele Deine beiden Pull requests in die Branch v0.5_cf, damit ich eine einzige Programmbasis habe, um mal vorab drüberzuschauen. Sobald wir etwas in die Branch Collector einspielen, können wir auf Bugs nicht mehr schnell reagieren, deshalb sollten wir dort erst kurz vor der Auslieferung der Version einspielen. Aus v0.5_cf kannst Du einen neuen Pull request erzeugen, sobald Du alles für die Version fertig hast.

Version v0.5 habe ich mal vordatiert auf den 11.03., also in gut einer Woche.

Könntest Du Dir vielleicht mal noch Issue #10 ansehen. Dort geht es auch um die Karten und um Buttons zu Karten wie beispielsweise Flopps Karte. Das Script ist von SiMaKiDD, wir wollten die Funktionalität übernehmen, soweit noch nicht im GClh vorhanden. Im Issue habe ich das Script als zip reingehangen.

**Comment by 2Abendsegler** [comment]
Achja, das Script von SiMaKiDD übernimmt beispielsweise alle Waypoints des Caches in Flopps Karte. Gutes Cachebeispiel dazu ist https://coord.info/GC5W9ZD .

**Comment by 2Abendsegler** [comment]
Ich schon wieder.
Bitte mach als Collaborator eine neue Branch auf, mach einen Blank ins Script oder anderswo und mach einen Pull request. Ich bin mir nicht sicher, ob das Deinem Konto gutgeschrieben wird.

**Comment by CachingFoX** [comment]
Hallo,

Ich habs verk***t. Versehentlich den einen Pull Request in den Collector gemacht. :-(xxx
Ich hoffe ich habe es geschafft den PR rückgängig zu machen.

Danach konnte ich leider keinen PR mehr auf github erstellen, da dieser dann alle Änderungen des Quellbranches beinhaltete. Deshalb habe ich Cherry-Picking über meinen lokalen Workspace gemacht. Ich hoffe das war so richtig vom vorgehen. Aber vielleicht auch unnötig, da ich sowieso alle Änderung übernommen habe. 

Also die Änderungen von Issue #180, #190, #191, #194 sind jetzt in v0.5_cf

**ACHTUNG** Ich habe auch eine Änderung in der gclh_icons.js gemacht.

**Comment by CachingFoX** [comment]
Das Skript SiMaKiDD habe ich mir angesehen. Sieht gut aus. Ich werde es mir die Tage ansehen und schauen, was man in gclh übernehmen kann.

Meine Favorit zum Testen: https://coord.info/GC1FPN1 -- da gibt es Wegpunkte von München bis nach Venedig. :-D
Alternative https://www.geocaching.com/geocache/GCR54G_neunzehn-versteckt?guid=0930b000-a2d3-410a-97e5-158dec03cff7 -- das Listing enthält über 130 Wegpunkte - diese werden dann auch nicht mehr angezeigt.

**Comment by CachingFoX** [comment]
Die Problematik mit dem veränderten Collector Branch habe ich verstanden. 

Aber sollte man, wenn man einen Bugfix für einen Release erstellt nicht einfach einen Branch von diesen Release erzeugen (bei uns Branch master) und in den neuen Branch den Fix machen und anschließend auf 'master' integrieren bzw. dann auch weitere Branches verteilen, damit er nicht verloren geht?

**Comment by 2Abendsegler** [comment]
Moin,

halb so wild, deshalb ist der master nicht der Default. Schön dass es nicht nur immer mir passiert. :))
Das hin- und herschieben des Codings war also nicht notwendig.

So, dafür bist Du jetzt endlich Contributor. 

Ich kann keinen Fehler in Deiner Lösung für die Problematik mit dem veränderten Collector finden. Ich meine es ist noch früh und ich hab noch nicht gefrühstückt ... aber, das scheint ok. Ich glaube so etwas nennt man dann betriebsblind, hihi.

Bitte mach aber noch als Collaborator eine neue Branch auf, mach einen Blank ins Script oder anderswo und mach einen Pull request. Ich möchte noch gerne Wissen, ob Dir das gutgeschrieben wird.
 
Dann erhol Dich mal.
Ich geh jetzt frühstücken.

**Comment by CachingFoX** [comment]
Mahlzeit ;-)

Ich habe eine Testbranch angelegt und eine Änderung gemacht
Issue: https://github.com/2Abendsegler/GClh/issues/195
Branch: https://github.com/2Abendsegler/GClh/tree/test_fuchs_from_collector

Aber etwas Gutes hat das ganze Stress von gestern Nacht. Mein Verständnis für Git ist wieder gewachsen. :-D

**Comment by 2Abendsegler** [comment]
Hallo,

ich habe mit der Testbranch "test_fuchs_from_collector" getestet, ich benötige sie nicht mehr. Ich weiß nicht, ob der zweite Test auch für mich gedacht war, aber egal. Ergebnis hatte ich teils schon geschrieben, nur eben hier noch nicht. Commits und Zeilenänderungen werden Dir nicht immer angerechnet. Beim ersten Test keine Anrechnung. Beim zweiten Test volle Anrechnung. 
Außerdem wurde auch nur ein Commit aus Deinem versehentlichen Einspielen in die Branch collector angerechnet, warum auch immer.

Fazit: Du solltest Deine Entwicklungen und sonstige Änderungen auf Deinem Account machen. Deinen Pull request müssen wir dann auf die Default Branch collector einspielen. Dass ist bisher die einzige verlässliche Methode. 

Wenn Du Deine neuen Erweiterungen noch auf Deinen Account übernehmen kannst, dann mach das bitte, sonst zählen die auch womöglich wieder nicht richtig.

**Comment by CachingFoX** [comment]
Hi,

ich glaube ich habe die Ursache für das Problem gefunden. Ein falsch konfigurierter Client. Dort habe ich als EMail Adresse nur "CachingFoX" und nicht "CachingFoX@xxxxxx.com" eingetragen. Beim zweiten Test habe ich jetzt meine Client entsprechend angepasst.
![fox-vs-fox](https://cloud.githubusercontent.com/assets/1838534/23704334/ab46ee24-0404-11e7-93c1-2bfcff815fa1.PNG)

Ich schau mal ob jetzt meine Erweiterungen auch mir zugezählt werden. 

Gruß

**Comment by 2Abendsegler** [comment]
Ok.
Soll ich Deine Änderungen in Branch v0.5_cf in den collector mergen, sobald ich fertig getestet habe?

**Comment by 2Abendsegler** [comment]
Boah, Du hast ja die München - Venedig Tour selbst gemacht!
Das ist ja wirklich die Härte, der Wahnsinn, Hut ab und ich verneige mich ...

**Comment by 2Abendsegler** [comment]
Ich habe v0.5_cf in den collector gemerged.
Die Commits und die Zeilenänderungen haben nicht bei Dir gezählt, ein K***, tut mir leid!

Deine Anpassungen sind aber super!

Issue kann geschlossen werden.
