### ISSUE TITLE
Replace img links in cache listing to an img link with the larger image if possible

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#181]
http://geoclub.de/forum/viewtopic.php?f=117&t=79518&p=1265640#p1265640

**Comment by 2Abendsegler** [comment]
Hi Marcus, ich kann Dir das Issue ja gar nicht zuordnen, das vergesse ich immer wieder. Ich glaube das geht erst, wenn ein Posting von Dir im Issue ist. Nein, das geht nur, wenn Du das Issue aufgemacht hast.

**Comment by MarcusBi** [comment]
Ich werde es trotzdem umsetzen :-P

**Comment by 2Abendsegler** [comment]
<ul><li>New: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/181">#181</a>] Replace img links in cache listing to an img link with the larger image if possible: <br>
Many thanks to <a href="https://www.geocaching.com/profile/?u=Herr%20Ma">Herr Ma</a> for the development.<br>
screen01 (Config)
<br><br></li>
<li>New: Enlarge VUP list with new features:<br>
Many thanks to <a href="https://www.geocaching.com/profile/?u=Herr%20Ma">Herr Ma</a> for the idea and the development.<br>
screen02 (Config)
<br><br>
Original Log:<br>
screen03
<br><br>
Log, if Cacher is on VUP list:<br>
screen04
<br><br>
Log with new option "Also hide name, avatar and counter from log":<br>
screen05
<br><br>
With the second new option "Hide complete log", the complete log is hidden.
<br></li>
