### ISSUE TITLE
Linklist menu doesn't pull down

### ISSUE THREAD

**Issue by Bohusz** [2Abendsegler/GClh#182]
I've installed Firefox on a new Windows 10 machine after years of using Chrome as my default browser. Then I've installed Tampermonkey and GClh II into it and then synced GClh's configuration. The configuration was saved by GClh (I) running in Chrome on a Windows 7 machine.

Linklist dropdown menu never shows up. Linklist is accessible only in the right column of Geocaching's "my" page.

I can observe also other problems, e.g. cache VIP list (logs) never fills up etc., but let's solve one thing at time.

**Comment by 2Abendsegler** [comment]
Hi,

at first, for Firefox the better choice is [Greasemonkey](https://addons.mozilla.org/de/firefox/addon/greasemonkey/) and not Tampermonkey. I don't know someone which works with Tampermonkey and Firefox. But this should not the reason for all you problems.

Do you know, where you can find the file of the GClh settings? It is called "GC_little_helper_II.db" in folder "gmscript" on Greasemonkey. I'm not sure how it called in Tampermonkey.

If yes, finish Firefox and save this .db file under another name, for example "GC_little_helper_II_save.db". Then start firefox and go to a geocaching.com page. Can you choose the linklist now? Please let me know the result.

If no, please let me know, I will try to explain it. 

Regards, 
Frank

**Comment by PontiacCZ** [comment]
Yep, first install Greasemonkey (and better uninstall Tampermonkey so they do not interfere) and try GClh II again.  Much likely you will have all described issues solved.

**Comment by Bohusz** [comment]
Hi, thanks for your help. **The problem is in using _TamperMonkey_.**

**First** I tried the Frank's recommendations. For your informations, _TamperMonkey for Firefox_ stores all its data in a single file, **storage.js** in **browser-extension-data\firefox**__@tampermonkey.net__ folder in the profile. It's quite a big file, 3.5 MB in my case, 1.5 MB takes the **GClhII** itself. Data of each extension are stored in several nodes named **@_PREFIX_#_GUID_:_SOMETHING_**, where _prefix_ is one of **uid**, **re**, **source**, **meta**, **st** and **ext**; the ":something" part used only for **ext** prefix. _Guid_ for **GClhII** was **cfa5607e-200c-4bec-a43e-43d21a579117**.

**GClhII** config was stored in the **@st#cfa5607e-200c-4bec-a43e-43d21a579117** node as **CONFIG** value. I removed the whole node, disabled all other _TamperMonkey_ scripts as well as _Firefox_ extensions.

After restarting Firefox I lost all the **GClhII** configuration as expected, but the **Linklist** menu kept not to work. Just curious, I tried the VIP feature. It worked now, I could add user and they got extracted and displayed.

**Then** I disabled the _TamperMonkey_, installed _GreaseMonkey_ and **GClhII** into it. Then I restored synced settings from dropbox. Now everytihing seems to work fine, I only lost my previous VIP list, but this I consider to be no problem.

So, thank you both again for your help and attention.

[storage_gclhii-only.js.gz](https://github.com/2Abendsegler/GClh/files/807160/storage_gclhii-only.js.gz) - the mentioned **storage.js** file with all other extensions but **GClhII** data removed.

**Comment by 2Abendsegler** [comment]
Ok, fine.
Thank you for the detailed description.

@PontiacCZ
Very good!
