### ISSUE TITLE
[Cache Listing] Fix "one click Watching" and enable "one click Stop Watching".

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1822]
**Describe the bug**
One-click watching does not work. 

**To Reproduce**
1. Go to a cache listing
2. Click on 'watch'
3. Forwarding to the watch list :(

**Expected behavior**
Step 3 should be only add the Cache to the watch list, without changing the page.

**Additional context**
https://forums.geocaching.com/GC/index.php?/topic/362910-number-of-watchers-disappeared-more-watchlist-bugs/&tab=comments#comment-5895966 - I think we have to wait for GS solve their own problems, then we can fix this bug.
At the moment, it is Possible to remove the Cache from the watch list without a confirmation. Maybe it is possible to use that for a one click unwatch feature

**Comment by 2Abendsegler** [comment]
Merged with 1837 and 1840
