### ISSUE TITLE
Link "View / Edit Log / Images" is missing in own logs

### ISSUE THREAD

**Issue by pgtmania** [2Abendsegler/GClh#1825]
**Describe the bug**
The link "View / Edit Log / Images" is missing in the bottom right corner of my own logs.

**To Reproduce**
1. Go to https://www.geocaching.com/my/geocaches.aspx
2. For one of the logs, click on the cache name
3. Scroll down to the section "xxx Logged Visits"
4. Scroll then down to your log.
5. The link "View / Edit Log / Images" is missing in the bottom right corner of the log.

**Expected behavior**
The link "View / Edit Log / Images" should be visible in the bottom right corner of my own logs.

If I deactivate "GC little helper II" (in Tampermonkey) and reload the page, then the link "View / Edit Log / Images" is displayed.

**Desktop (please complete the following information):**
 - OS: Windows 7 Pro SP1
 - Browser: Firefox Browser Extended Support Release 78.11.0esr (64 bits)
 - Tampermonkey: Tampermonkey® by Jan Biniok v4.13.6136
 - GC little helper II : GC little helper II 0.11.4

**Comment by 2Abendsegler** [comment]
Thank you for reporting the bug and for the detailed description.

This problem should be fixed already. Please try our [advance correction](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) and let us know whether it solves your problem.

A new version will be available in a few days. 

Kind regards,
Frank

**Comment by LittleJohn-DD** [comment]
Hi together,

on my installaton it works fine. Maybe the problem causes as basicmember?!
Greets
Patrick

**Comment by pgtmania** [comment]
Hi 2Abendsegler,

> This problem should be fixed already. Please try our [advance correction](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) and let us know whether it solves your problem.

I try it (= I clicked on the link [advance correction](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) and then click on the reinstall button) and then I reladed the page of the cache and now the link "View / Edit Log / Images" is displayed again in the bottom right corner of my own logs.

Thanks for the fix. ;-)

Regards,

-- 
PgtMania

**Comment by 2Abendsegler** [comment]
Thanks for the feedback.

---
Issue is already solved. Close issue.
