### ISSUE TITLE
[New Map] Undefined Finds in header.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1831]
**Describe the bug**
The find-counter in the header shows "undefined Finds"

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/124112677-d4696e80-da6a-11eb-954b-d6d7e0d25614.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: actual collector

**Comment by 2Abendsegler** [comment]
Auf welcher Seite bekommst du den Fehler?

**Comment by capoaira** [comment]
Auf der neuen Karte.
Habe ein paar Stichproben auf anderen Seiten gemacht, da klappt das.

**Comment by 2Abendsegler** [comment]
Kommt nicht in die Milestones und nicht ins Changelog, da Bug im collector.

**Comment by 2Abendsegler** [comment]
> Kommt nicht in die Milestones und nicht ins Changelog, da Bug im collector.

Blödsinn, den Bug haben wir wohl auch im master.

**Comment by 2Abendsegler** [comment]
@capoaira 
Damit eilt die nächste Version auch etwas. Ich werde am Freitag Abend ab 23:00 Uhr, also morgen, eine neue Version erzeugen.
Sind deine Änderungen zu den Favoritenprozenten im Owner Dashboard dann noch nicht da, dann weiß ich ja was zu tun. Also kein Grund dass du dich beeilen musst.

**Comment by capoaira** [comment]
merged in #1832
