### ISSUE TITLE
[Global] Hide upgrade button in header with new parameter (basic member).

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1835]
**Describe the bug**
For non-premium cachers the header always includes an upgrade button. This Button is hidden by the gclh

**Expected behavior**
The upgrade button shouldn't remove by the gclh

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50927164/124647342-1d1f8e00-de96-11eb-874d-a6bb780122e8.png)

**Additional context**
Ich finde es eigentlich gar nicht so schlimm, denn der Button ist nervig. Aber trodem sollte der nicht ohne zu fragen verschwinden.

**Comment by 2Abendsegler** [comment]
... dann sollten wir auch das hier behandeln auf der alten Karte:
![grafik](https://user-images.githubusercontent.com/22332216/124652920-fc0e6b80-de9c-11eb-8325-51b197bd1b36.png)

**Comment by 2Abendsegler** [comment]
Der Upgrade Button wird nun über einen Parameter gesteuert. Standardmäßig wird nicht ausgeblendet.

Settings -> Global - Header Layout
![Screen08](https://user-images.githubusercontent.com/22332216/141657308-0d0c6077-465b-41b1-a084-e7586cc37bcb.jpg)

(Zur Upgrade Erinnerung auf der alten Karte habe ich nichts gemacht.)

---
Upload js
Upload header.html with upgrade button
Update config_standard.txt with new parameter

---
merged with #1951

**Comment by 2Abendsegler** [comment]
Gerade bemerkte, dass das ja dann auch für Premium Member gilt, weil der Button ja nun immer im Header vorhanden ist, merde.

**Comment by 2Abendsegler** [comment]
merged with #1952
