### ISSUE TITLE
The Tampermonkey link for Safari browser in the installation tips does not work from Safari 12.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1839]
Womöglich funktioniert der Tampermonkey Link für Safari in unserer [Installationsanleitung](https://github.com/2Abendsegler/GClh/blob/master/docu/tips_installation.md#-safari) nicht mehr.

@Ruko2010 
Kannst du das bitte mal testen?

**Comment by Ruko2010** [comment]
Tatsächlich. Der Link scheint zwar noch zu gehen, aber ich glaube der ist nur noch für Safari 6-11. Ab Safari 12 muss man Tampermonkey als Erweiterung über den Appstore **kaufen**: https://www.tampermonkey.net/index.php?browser=safari

Für Safari gibt es wohl keine kostenlose Version mehr.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Danke für die Info, das hatte ich überlesen.

**Comment by 2Abendsegler** [comment]
To do:
Links in der Installationsanleitung einbauen:
[Link for the Tampermonkey app up to Safari 11](https://safari.tampermonkey.net/tampermonkey.safariextz)
[Link for the Tampermonkey app from Safari 12](https://apps.apple.com/app/apple-store/id1482490089?pt=117945903&ct=tm.net&mt=8)

**Comment by Ruko2010** [comment]
Macht es eventuell mehr sinn auf die Übersichtsseite https://www.tampermonkey.net/index.php?browser=safari zu verlinken? Eventuell ändern sich die Links aber die Übersichtsseite wird wohl gleich bleiben

**Comment by 2Abendsegler** [comment]
Ja, könnten wir vielleicht machen. Für die Laien macht das die Sache aber etwas komplizierter. Die müssen sich dann noch mit der Tampermonkey Seite auseinander setzen. Ist ja so schon alles zu kompliziert, auch wenn wir das nicht so sehen.

**Comment by Ruko2010** [comment]
ok, guter Punkt

**Comment by 2Abendsegler** [comment]
Merged with #1841
