### ISSUE TITLE
[Cache Listing] "#GCNote# : User note" in "Copy Data to Clipboard" feature does not work anymore.

### ISSUE THREAD

**Issue by Arnos99** [2Abendsegler/GClh#1843]
With the #GCNote# command, the contents of the Personal Cache Note will no longer be copied.
Looks like Groundspeak has changed something on their side.

**Comment by capoaira** [comment]
Thank you for reporting the bug.
I can confirm the bug and will look for a fix.

**Comment by capoaira** [comment]
I've prepared a bug fix. Can you test it [here](https://github.com/2Abendsegler/GClh/blob/9acb6d3c41413a0ecbc6f9f9054c1491d60a7c94/gc_little_helper_II.user.js?raw=true), please?
[Here](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true) it goes back to the latest release version.

**Comment by Arnos99** [comment]
Thanks for the fast fix,
everything is fine now. :-)

**Comment by capoaira** [comment]
Danke für die schnelle Rückmeldung.

Wir haben uns angewöhnt die Issues erst zu schießen, wenn sie gemerged wurden. Deswegen öffne ich es nochmal.
Wir schießen es dann, sobald die Änderung in der Sammlung für die nächste Version ist.

**Comment by 2Abendsegler** [comment]
Merged with #1845
