### ISSUE TITLE
[Browse Map, Search Map] The display of the Personal Cache Note in the additional cache data is not correct.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1845]
### Describe the bug

[Browse Map, Search Map] The display of the Personal Cache Note in the additional cache data is not correct.
Siehe auch Issue #1843.

![grafik](https://user-images.githubusercontent.com/22332216/125949738-071a1744-a464-4a59-9519-e6638b415615.png)

---
@capoaira
Kannst du dir das vielleicht ansehen, du weißt bestimmt schon worum es geht?

### OS

Windows

### Browser

Firefox

### Version

0.11.5

**Comment by capoaira** [comment]
Jip, ich gucke mir das an.

**Comment by 2Abendsegler** [comment]
@capoaira 
Mist, hab nicht aufgepasst. Du vermutlich auch nicht. Als Bug soll das ja in den bug-collector und nicht in den collector. 
Kannst du bitte die Änderung noch mal für den bug-collector rüberschieben?

**Comment by capoaira** [comment]
Ups, daran habe ich nicht gedacht... klar mach ich.

**Comment by capoaira** [comment]
Hmm, ich muss den fix nochmal vom Bug collector aus machen, da änderungen aus dem collector drin sind. Ich mache das dann später vom PC aus.

**Comment by capoaira** [comment]
merged with #1848
