### ISSUE TITLE
[New Log Form] Templates, Smilies and VUP/VUP/Mail missing, Placeholders and Signature does not work

### ISSUE THREAD

**Issue by gcPhil** [2Abendsegler/GClh#1855]
Gerade ist mir aufgefallen, dass alle in GCLH aktivierten Änderungen auf der Logging-Seite verschwunden sind. GCLH läd zwar noch und z.B. der Seitenheader wird geändert, aber Änderungen wie "Show smilies", "log template", "Auto open trackable inventory" werden nicht alle angezeigt. Vermutlich hat GS wieder ordentlich an der Seite rumgespielt.

**Comment by capoaira** [comment]
Danke für das Melden des Bugs. Auch bei mir fehlt alles.

Comment im GS Forum:
https://forums.geocaching.com/GC/index.php?/topic/343005-gc-little-helper-ii/page/6/&tab=comments#comment-5906343

**Comment by capoaira** [comment]
Es sieht fast so auch, als ob sie mit den Änderungen noch nicht fertig sind:
![grafik](https://user-images.githubusercontent.com/50927164/126626781-de20c46d-8fc2-43e3-8573-fecc83cc1747.png) (Screenshot ohne GCLh)
Zumindest sieht es nicht mehr so schön aus wie vorher.

**Comment by 2Abendsegler** [comment]
> Es sieht fast so auch, als ob sie mit den Änderungen noch nicht fertig sind

Ja, macht Sinn halbfertige Sachen rauszugeben, schließlich testet die Cachergemeinde ja kostenlos. 😂

**Comment by capoaira** [comment]
Ja, und vorallem: warum ändern die überhaupt etwas? Es ist ja nichts neues dazu gekommen :(

**Comment by Tabaluga1** [comment]
looks like the problem appears only whem logging from draft list

![image](https://user-images.githubusercontent.com/40625611/126780831-bf2efdd5-28c7-4373-b91c-13fd001a9966.png)

when logging directly from the listing the Last log and smileys are there 

![image](https://user-images.githubusercontent.com/40625611/126780986-2821e412-418c-41cb-8a9b-b1424c72915e.png)

maybe that helps when analysing the problem

**Comment by Cappa-d** [comment]
Here it doesn't work while logging from a cache listing:

![2021-07-24 (2)](https://user-images.githubusercontent.com/10072462/126872452-1442b8be-adfe-4330-a754-c5e731be2a2e.png)

GClh_ERROR - Signature New Log Page (CACHE) - https://www.geocaching.com/play/geocache/gc30b3x/log: $(...)[0] is undefined
Stacktrace:
replacePlaceholder@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:5654:38
checkLogType@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:5632:39
mainGC@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:5616:25
waitingForUserData@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:2687:13
mainGCWait@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:2698:23
checkBodyContent@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1509:25
start/<@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1516:29
resolveWith@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:874:15720
done@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:874:15606
start@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1500:10
tms_9af99b74_1abb_47fb_90d8_30cded6106a1@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:18591:6
F_a/s</<@eval:4:80
@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1:101
@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1:781
@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:18593:6
@moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC%20little%20helper%20II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:18595:3
F_a/s</<@eval:4:80
t@eval:3:192
E_u/<@eval:4:244
create/<@eval line 2 > Function:67:477
create@eval line 2 > Function:69:193
c@eval line 2 > Function:7:231
F_a/s</<@eval:4:80
i@eval line 2 > Function:5:165
s/<@eval line 2 > Function:5:292
v/<@eval:13:99
v@eval:13:118
GC little helper II.user.js:18461:49
    gclh_error moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:18461
    mainGC moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:5646
    waitingForUserData moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:2687
    mainGCWait moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:2698
    checkBodyContent moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1509
    start moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1516
    resolveWith moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:874
    done moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:874
    start moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1500
    tms_9af99b74_1abb_47fb_90d8_30cded6106a1 moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:18591
    s eval:4
    <anonym> moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1
    <anonym> moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:1
    <anonym> moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:18593
    <anonym> moz-extension://36cdb661-c6bb-4819-b486-050eca51f40a/userscripts/GC little helper II.user.js?id=9af99b74-1abb-47fb-90d8-30cded6106a1:18595
    s eval:4
    t eval:3
    E_u eval:4
    create eval line 2 > Function:67
    create eval line 2 > Function:69
    c eval line 2 > Function:7
    s eval:4
    i eval line 2 > Function:5
    s eval line 2 > Function:5
    v eval:13
    v eval:13

**Comment by 2Abendsegler** [comment]
There is a workaround: You can log using the old log form. On the new log form there is a link at the top right, called "Opt out", that takes you to the old log form.

**Comment by gcPhil** [comment]
@2Abendsegler Your workaround only works for people that have the possibility to opt out. In my profile the option is missing:
![no-opt-out](https://user-images.githubusercontent.com/2893036/127122433-731badef-ba4d-4354-95a6-edb5f2de36e2.png)


> There is a workaround: You can log using the old log form. On the new log form there is a link at the top right, called "Opt out" or "Zurück wechseln", that takes you to the old log form.

**Comment by 2Abendsegler** [comment]
@gcPhil
If you come from a draft, you have to choose the "opt out" on the draft page.

**Comment by gcPhil** [comment]
> @gcPhil
> If you come from a draft, you have to choose the "opt out" on the draft page.

If I choose "opt out" on the draft page ( https://www.geocaching.com/account/drafts ) I see the old layout of the draft page but the logging page stays in the same modern, broken design without any option to opt out.
Can you send me the URL of your working opt-out-link (if it is not personalized)? Maybe it works for me to opt-out if I paste it to the browser.

**Comment by 2Abendsegler** [comment]
@gcPhil 
Moin,
wenn ich über die alte Draft Seite arbeite kommt bei mir immer die alte Log Seite. Ich habe das erfolglos versucht zu ändern. Warum es bei dir scheinbar von der alten Draft Seite zur neuen Log Seite geht kann ich nicht nachvollziehen. 

Der opt out Link auf der neuen Draft Seite sieht wie folgt aus: 
https://www.geocaching.com/account/drafts/home/optout
Ein Link von der alten Draft Seite zur Log Seite sieht etwa wie folgt aus: 
https://www.geocaching.com/seek/log.aspx?PLogGuid=cd02036e-02e0-4beb-bc75-3452b2...

**Comment by capoaira** [comment]
Ich hatte dasselbe Verhalten, wie es bei gcPhil war. Wenn man aber beim GClh den config Parameter `Logging drafts old-fashioned` (In der Kategorie `Logging`) anstellt, ist das Verhalten der Seite wie bei 2Abendsegler. 
Auf die neue Draft Seite hat der Parameter keine Auswirkung.

**Comment by gcPhil** [comment]
Danke @capoaira , (nur) mit dieser etwas versteckten Einstellung erhalte ich neben der alten drafts page auch die alte logging Seite nachdem ich bei den Drafts auf opt-out klicke.

**Comment by 2Abendsegler** [comment]
@capoaira, super! Hatte ich total vergessen. 😄

**Comment by capoaira** [comment]
Macht es schon Sinn sich an dieses Issue zu setzten?
Wir wissen ja nicht, wann es mit der Entwicklung von GS weiter geht. Und ich persönlich finde die Logfunktionen sehr wichtig...

**Comment by 2Abendsegler** [comment]
Das ist ja jetzt schon ne Weile her mit den Änderungen. Ich glaube das macht schon Sinn, dass wir uns dran setzen.
Möchtest du das machen?

**Comment by 2Abendsegler** [comment]
Ok, ich übernehme das.

**Comment by capoaira** [comment]
I prepared a Bugfix. You can install and test it [here](https://github.com/capoaira/GClh/blob/log/template-etc/gc_little_helper_II.user.js?raw=true).
And [here](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true) it goes back to the latest version.

**Comment by gcPhil** [comment]
> I prepared a Bugfix. You can install and test it [here](https://github.com/capoaira/GClh/blob/log/template-etc/gc_little_helper_II.user.js?raw=true).
> And [here](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true) it goes back to the latest version.

Ich konnte die Bugfix-Version gerade testen und es scheint alles wieder wie gedacht zu funktionieren. Vielen Dank!

**Comment by 2Abendsegler** [comment]
@capoaira 
Really great! ❤

---
Merged with #1900
Milestone v0.11.5.3
