### ISSUE TITLE
[Cache Listing / Maps] Elevation data with geonames run into errors.

### ISSUE THREAD

**Issue by Bogmen** [2Abendsegler/GClh#1857]
### Describe the bug

> GC little helper II Error

> addElevationToWaypoints_GeonamesElevation(): json.geonames is undefined

> For more information see the console. Create a new issue / bug report at GitHub.

Neuerdings kommt diese Fehlermeldung ständig, vorher kam diese Meldung beim loggen.
Es gibt keine Emojis beim Loggen.
GC little helper ist auf Deutsch eingestellt, in den Menüs wird allerdings alles auf Englisch angezeigt.
Es wäre gut, wenn das Script wieder fehlerfrei läuft.

### OS

Windows

### Browser

Firefox

### Version

90.0.2 (64-Bit)

**Comment by capoaira** [comment]
Moin, danke für das Melden des Bugs. Das mit dem Loggen ist uns bekannt. Siehe #1855 

Kommt der Error den du beschreibst auch beim Loggen oder beim Cache listing oder auf einer der Karten?

Geonames hat manchmal eine downtime. Kannst du einmal überprüfen ob der Bug sich "von selbst" behoben hat?

**Comment by 2Abendsegler** [comment]
Ergänzend:

Das Script läuft eigentlich nie fehlerfrei. Das hängt damit zusammen, dass der Webseitenbetreiber die geocaching Webseiten ständig anpasst und wir vielfach diese Anpassungen dann im GClh berücksichtigen müssen, bevor wieder alle Features laufen. 

Seitdem vor einigen Wochen die Seitenköpfe mit Menü ... vom Webseitenbetreiber auf allen geocaching Seiten komplett überarbeitet wurden, ersetzen wir diese Seitenköpfe durch einen alten, bisherigen Seitenkopf. Das tun wir immer in Englisch. Die Spracheneinstellung zieht hier nicht. Im Moment haben wir nicht geplant hier etwas zu ändern.

@capoaira 
Zur Geonames Fehlermeldung: Wir haben ja vor einigen Wochen von http auf https umgestellt. Womöglich ist die https Adresse häufiger überlastet oder down. Wir haben mit diesem Fehler hier bereits drei Hinweise darauf erhalten, dass die Höhenermittlung mit Geonames scheinbar schwächelt. Ich konnte das aber nie reproduzieren. 
Vielleicht sollten wir mit beiden Adressen arbeiten, wenn https nicht funktioniert, dann ausweichen auf http. 
Was meinst du?

**Comment by capoaira** [comment]
Jip, könnten wir machen. Auch wenn https ja eigentlich besser ist. 

Off-topic: Ich bin gerade im Urlaub, kann also gerade hier nichts machen.

**Comment by 2Abendsegler** [comment]
@DieBatzen 
Hallo Thomas,

Geonames über https ist gefühlt häufiger nicht erreichbar als zuvor über http. Zumindest gibt es seit der Umstellung gefühlt häufiger Hinweise dazu. Ich habe in den letzten Tagen noch 2 weitere Mails dazu bekommen. 

Spricht etwas dagegen im Fehlerfalle mit https es zusätzlich mit http zu versuchen? 
Ich möchte nicht dass du diese Anpassungen machst. Es geht mir viel mehr um deine Meinung dazu, ob es Sinn macht oder eher nicht.

Danke dir.
LG Frank

**Comment by 2Abendsegler** [comment]
Off-topic: @capoaira: Genieß deinen Urlaub!

**Comment by DieBatzen** [comment]
Hallo Frank,

der Fallback auf http macht auf jeden Fall Sinn.
Die Idee war ja auf das sichere https-Protokoll zu wechseln und dabei die Höhenermittlung in gleicher, zuverlässiger Qualität beizubehalten.

Auch bei mir schlägt die https-Verbindung zu Geonames gelegentlich fehl, kurz darauf funktioniert's dann wieder.
In diesen Fällen einen http-Request hinterher zu schicken dürfte die Höhenermittlung auf jeden Fall robuster machen.

Gruß,
Thomas

**Comment by 2Abendsegler** [comment]
#1876
Go back to http calls.
Merged with #1875.
Milestones 0.11.5.2
