### ISSUE TITLE
[Public Profile] Links "show hides" and "show finds" don't work for user ">Doppelherz<".

### ISSUE THREAD

**Issue by V60GC** [2Abendsegler/GClh#1861]
### Describe the bug

Mit dem User >Doppelherz< klappen die beiden Links nicht. Man landet auf der Advance Search Seite mit dem Hinweis "That username does not exist in the system"

### OS

Windows

### Browser

Firefox

### Version

90.0.2

**Comment by 2Abendsegler** [comment]
Danke für das Melden des Fehlers.

---

Der Link sieht wie folgt aus: `https://www.geocaching.com/seek/nearest.aspx?ul=&gt;Doppelherz&lt;`
Der Link muss wie folgt aussehen: `https://www.geocaching.com/seek/nearest.aspx?u=%253EDoppelherz%253C`

- [ ] Link "show finds" im Profile
- [ ] Link "show hides" im Profile 
- [ ] Icon mit Link "Send a mail to ..." funktioniert auch nicht, wenn der Username verwendet wird. Also beispielsweise im Dashboard bei "ALL MY VIPS".
- [ ] Prüfen ob noch weitere Links zu diesem Usernamen nicht funktionieren.

**Comment by capoaira** [comment]
Ich habe blöderweise Probleme mit meinem Laptop (Ladekabel vergessen)
Also kann ich hieran nicht weiter arbeiten.

Damit sind Punkt 1,2 und 5 behoben: (die Änderung im cod können wir nicht testen, ich bin mir aber sicher, dass die Ergänzung nötig ist.)
![grafik](https://user-images.githubusercontent.com/50927164/129004519-7bdc49e4-f455-42b2-9c83-d22e982214b3.png)

**Comment by 2Abendsegler** [comment]
> Ich habe blöderweise Probleme mit meinem Laptop (Ladekabel vergessen)
> Also kann ich hieran nicht weiter arbeiten.

Gut so! 😄 Genieß deinen Urlaub!

> Damit sind Punkt 1,2 und 5 behoben: (die Änderung im cod können wir nicht testen, ich bin mir aber sicher, dass die Ergänzung nötig ist.)

Ja, sehe ich auch so.
Ich werde deine Änderungen übernehmen und hier weiter machen.

**Comment by 2Abendsegler** [comment]
Merged with #1878
Milestone 0.11.5.2
