### ISSUE TITLE
[Cache Listing] Improve Watch button handling.: Cannot read property 'match' of null

### ISSUE THREAD

**Issue by Sajomagc** [2Abendsegler/GClh#1874]
With Google Chrome 92.0.4515.131 installed on 02.08.2021 the error mentioned above occurs as soon as I am opening a geocache listing.
Is it an GCLH issue or just my problem?
Thanks in advance!

**Comment by capoaira** [comment]
Thanks for reporting the bug.
I cannot reproduce the it. Witch gclh version you use? Do you have a screenshot from the bug?

**Comment by Sajomagc** [comment]
I had this bug since 02.08.2021
Now, after reporting it here, it is no longer visible. 🥴
I'll watch it for a few days and then get back to you.

**Comment by Sajomagc** [comment]
Today the bug appeared again. See attached screenshot.

My GCLH version is 11.6.

Maybe a problem with compatibility to project-gc Add-on?

**Comment by capoaira** [comment]
I'm not sure. I think pgc change nothing at the button. But sometimes bug can be very strange;)
Version 11.6 isn't published. The actual version is 11.5.1

The sceenshot isn't attached.

**Comment by Yannick-XY** [comment]
Got this error too, but can only reproduce it on an own unpublished cache-listing page (maybe because the "watch"-button is missing on this page?)
- Version 11.5.1, 
- other Scripts: Mystery-Wizard, Project-GC, GCTour

**Comment by capoaira** [comment]
Ah, yes, that is a know issue and already fixed: #1856
The fix will be published with Version 0.11.5.2

@Sajomagc can you confirm this?

**Comment by Sajomagc** [comment]
Yes, I can confirm it.
Saw lately that it's an unpublished cache. 
Forgot the screenshot. 🙈

Thanks for fixing it and your time to help.

**Comment by 2Abendsegler** [comment]
@Sajomagc
> My GCLH version is 11.6.

capoaira noticed again that you specified the version as 11.6. You may have also installed the old GC little helper as an add-on. Please have a look in your browser add-on section. The add-on has not been serviced since 2016 and it interferes with the functionality of the GC little helper II. You should remove the add-on.
