### ISSUE TITLE
Logvorlage aus GClh nicht verfügbar 

### ISSUE THREAD

**Issue by LittleJohn-DD** [2Abendsegler/GClh#1883]
### Describe the bug

Ich weiß nict, ob der Fehler schon gemeldet wurde oder in Bearbeitung ist.

Fehler tritt sowohl in Firefox als auch im MS Edge auf.

### OS

Windows

### Browser

Firefox, Edge

### GClh Version

v0.11.5.1

**Comment by capoaira** [comment]
Danke für das Melden des Bugs.
Wir haben bereits ein Issue dazu: https://github.com/2Abendsegler/GClh/issues/1855
