### ISSUE TITLE
[Log Form] Automatic opt out to the old log form.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1884]
### Describe the solution you'd like

[Log Form] Automatic opt out to the old log form.
https://geoclub.de/forum/viewtopic.php?p=1324872#p1324872

**Comment by capoaira** [comment]
Hm, dieses Feature macht in meinen Augen keinen Sinn.
Wenn man bei einem Cache opt out klickt, bleibt man für alle weiteren Logs auf der alten Seite. Es gibt nur eine Ausnahme:
Entwürfe. Bei Entwürfen wird immer die neue Logseite verwendet. Das lässt sich nur von der fieldnotes Seite ändern, nicht von der neuen Drafts Seite. Dafür haben wir aber schon eine Funktion: (settings_fieldnotes_old_fashioned)
![grafik](https://user-images.githubusercontent.com/50927164/132000258-f20c3762-7213-4c3c-af2a-ae7a3bff5ae7.png)

**Comment by capoaira** [comment]
https://geoclub.de/forum/viewtopic.php?p=1326089#p1326089

Merged with #1898
