### ISSUE TITLE
[Maps] Labels (without hovering) on maps

### ISSUE THREAD

**Issue by eddydc** [2Abendsegler/GClh#1885]
### Is your feature request related to a problem? Please describe

I don't know if it's already present, but I didn't find a setting for it.
Now the names of the caches on a map are only shown when one hovers over the caches. This is not possible when one want to have a general overview or print out the map.
The inspiration for this request comes from a GSAK macro where one can get labels on the map without hovering. Why wouldn't you use GSAK instead, you'd say. Well, that isn't that interactive.

### Describe the solution you'd like

Is it possible to have an option that one can also show the labels without hovering? I know things can get cluttered but it's up to the user to zoom in enough. Maybe an extra setting for the zoom level when labels will be shown can fix that too?

**Comment by capoaira** [comment]
Ok, GSAK create its own Map with the gpx data and that make it possible. On the geocaching maps, I find no way to implement this feature because we have to use the data given by the map UI. :(

**Comment by 2Abendsegler** [comment]
Hi Eddy,

there is another script called "Geocaching Map Enhancement" (GME).

This script contains such a feature for the browse map (old map). In addition to the `Search` and `PQ` buttons, a new `GME` button will be established. After a click, additional features are displayed. After clicking on `Show labels` button the cachenames will be displayed even without hovering.

![grafik](https://user-images.githubusercontent.com/22332216/132946721-4012011a-177b-43dd-8762-fd405a4e4eeb.png)

Two things you should know:
1. It should be noted that the corresponding data is stored in the memory of the script-manager, i.e. just as we store the configuration for the GClh, but you can not enter or change this memory. I don't know whether a reorganization will take place here. So it could be that the memory used is getting bigger and bigger. 
2. The data are permanently read and place a load on the Groundspeak servers. That's not the nice way.

As capoaira has already described, we do not yet know how the data will be determined. 🤭

The script has not been maintained for a few years, so we took it up and restored it to such an extent that all features work again. An agreement with the actual owner is still pending. So I don't know whether we will continue to develop the script here in the future. 

You can install it from our support platform with a temporary version name [GME version 0.8.2.1.2As](https://github.com/2Abendsegler/GME/raw/main/Geocaching_Map_Enhancements.user.js).

Maybe you let us know your geocaching name for the GClh thanks page (not for this feature request, but for your last bug report)?

If your feature request is done with GME please close the issue.
 
Cheers Frank

**Comment by eddydc** [comment]
Hi,
This is exactly what I was looking for. Ma,y thanks indeed. 
The layout of the labels could be a bit better, but maybe the owner will be pick it up again. Otherwise an idea to incorporate in GCLH?
My geocaching name is searchjaunt
Cheers,
Eddy

**Comment by 2Abendsegler** [comment]
> Otherwise an idea to incorporate in GCLH?

We will not integrate it into the GClh, but it is quite conceivable that we will maintain and further develop it as a separate script alongside the GClh.

**Comment by eddydc** [comment]
That's an option I surely can live with ;-)

**Comment by 2Abendsegler** [comment]
Realized in GME.
Close
