### ISSUE TITLE
[Search] Button to GClh-Filtersets not visible

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1887]
### Describe the bug

The Button for the Filtersets are not Visible anymore because of changes of the web page.

### Expected behavior

The Button should be visible.

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.5.2

### Additional context

https://forums.geocaching.com/GC/index.php?/topic/365277-release-notes-website-search-filtering-august-26-2021/&tab=comments#comment-5915838
Related: #1886 

@2Abendsegler eventuell könnten wir die Filtersets in das neue Popup integrieren, anstatt ein eigenes dafür zu nutzen. Damit wäre #1504 auch gleich erledigt. Soweit ich das sehen kann, (Habs nur flüchtig verglichen) sind beide Filterpopups nun gleich.

**Comment by 2Abendsegler** [comment]
Merged with #1901
Milestone v0.11.5.3
