### ISSUE TITLE
[Search Map / PQ] Save as PQ doesn't note D/T ratings.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1888]
### Describe the bug

Because auf the UI changes, the url parameter for D/T ratings has changed and does not note for the save as PQ Feature

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.5.2

### Additional context

- [x] Fix TD
- [x] Check all other filters

**Comment by 2Abendsegler** [comment]
merged with #1895
milestones v0.11.5.3
