### ISSUE TITLE
[Browse Map] Enable non GClh layers like GME or GC.

### ISSUE THREAD

**Issue by MuddyPuddles** [2Abendsegler/GClh#1892]
I recently updated GCLH II and now I cannot access my GME map choices. I have set several map preferences in GME as I like to use different maps depending on what info I need etc. Since the GCLH update the grey icon with pages for the maps is overwritten with a map icon that only show me a Go To option for Google maps, Flopps maps, Openstreet maps and geohack. I don't want this, I want my GME options. I've tried changing various map options in GCLH but nothing works, the only way to get my GME map options back is to disable GCLH, which I really don't want to do. 
Please tell me, is there a simple way to get me GME map options back without disabling GCLH?
Thanks in advance

**Comment by 2Abendsegler** [comment]
Hey,

the "Go To ..." map option contains four possible entries. Each of these entries has a parameter that you can turn on or off. The first parameter is "Add link to Google Maps on Browse and Search Map", three more follow in the next lines. If you deactivate all four, the "Go to ..." map option does not appear at all. 

It does not appear possible that these parameters were activated by an update if they were previously deactivated.

There is only the possibility that you used a fairly old version of the GClh II, in which the "Go to" map option did not exist at all. 

Please answer some questions:
1. Previous GClh II version?
2. Current GClh II version?
3. Browser?
4. Operating system?
5. GME version?
6. Have you changed something in GME, or is it the original version?
7. Please post a screenshot of the current map.

Frank

**Comment by MuddyPuddles** [comment]
Hi Frank,

Thanks for the reply. Following your advice I deactivated the four Go To
options and my GME map options are back as they were so problem solved.
Thanks.

I had made no changes at all to either GCLH or GME, nor Tampermonkey etc so
why this should have suddenly changed itself is beyond me. I'm using GClh
II v 0.11.5.2 on Chrome, Windows 10.

Anyway, as I said it's all fixed now. Many thanks

Brad

**Comment by 2Abendsegler** [comment]
Hey Brad,

it sounds like we have made changes which include that the gray button with the layers from geocaching or GME is no longer processed correctly. I didn't find anything in a hurry, but we're still leaving the issue open. When I get back from vacation I'll watch it again.

Can it not be that the button "Go to" was shown to you beforehand and still the gray layers button from GME was available?

Cheers,
Frank 

PS: We have the [GME version 0.8.2.1.2As](https://github.com/2Abendsegler/GME/raw/main/Geocaching_Map_Enhancements.user.js) in which all known errors are corrected ... so if you want, install it.

**Comment by MuddyPuddles** [comment]
Hi Frank,

Actually, I think you're right, the Go To Button was also visible
previously. Before turning the options off earlier to fix the issue, the
GME gray layers button appeared briefly when the maps page opened before
being overwritten with the Go To button. Perhaps it is just positioning
itself over the gray layers button  rather than overwriting it but the
result is the same, the layer button vanishes and is replaced with the Go
To button.

Thanks also for GME v 0.8.2.1.2As. I was using v8.2.1 so this should help.
Thank you.

Enjoy your vacation
Cheers
Brad

**Comment by 2Abendsegler** [comment]
Thanks for your feedback.

**Comment by 2Abendsegler** [comment]
[Browse Map] Enable non GClh layers like GME or GC.

The GC layers work again as desired. The button for the GME Layer is now on the far left. To change that, the whole layer control would have to be rebuilt. The effort is too big for me to do it any other way. If we also edit the GME script in the future, then we should put a label there, that's easier. GCVote, also a layer, moves all buttons, but GCVote no longer works properly anyway. 

That should be enough at the moment.

Merged with #1906
Milestone v0.11.5.3
