### ISSUE TITLE
Signature New Log Page (CACHE): Cannot read property 'children' of undefined

### ISSUE THREAD

**Issue by Robusax** [2Abendsegler/GClh#1896]
### Describe the bug

Wenn ich einen Cache loggen will, wird das Log-Fenster geöffnet und am oberen Rand des Fenster erscheint die im Titel genannte Fehlermeldung in roter Farbe.
Im Log-Fenster wird auch das Template aus GClH nicht aufgelöst. Dort steht also nur 
#Found#. Fund von #Me#
TFTC sagt #Owner#

Das passiert auf Google Chrome und auf Firefox auf meinem Desktop und auf beiden Laptops.

### OS

Windows

### Browser

Firefox, Chrome

### GClh Version

0.11.5.2

**Comment by capoaira** [comment]
Danke für das Melden des Fehlers.
Wir habe bereits ein Issue (#1855) dazu und arbeiten daran.
