### ISSUE TITLE
[Search Map] Hide unsolved Mysterys

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1897]
### Is your feature request related to a problem? Please describe

If I plan a tour, the unsolved mysteries are annoying, but I want to all solved mysteries. 

### Describe the solution you'd like

Include it into the Filtersystem

### Additional context

https://geoclub.de/forum/viewtopic.php?p=1325876&sid=7af8dd0fed1c56402b8367977d11fe4e#p1325876###

**Comment by capoaira** [comment]
Mein kleiner Test hat ergeben, dass wir auf der alten Karte leider keinerlei Einfluss auf einzelne Icons nehmen können, auf der neuen ist dies aber durchaus möglich.
Bei der alten Karte werden Kacheln in derselben Größe wie die Map-Kacheln erzeugt, mit allen Icons, die dort in der Gegend sind. Wir haben so nur Zugriff auf alle Icons einer Kachel, jedoch nicht auf einzelne Icons,
Bei der neuen Karte ist jedes Icon ein eigenes `img` Element, dort sollte ein solcher Filter möglich sein.

**Comment by 2Abendsegler** [comment]
Wenn wir nur einen Cachetyp ausblenden, dann ist das doch auch nur ein Teil der Caches auf einer Kachel. Werden dann ganz neue Kacheln geladen?

**Comment by capoaira** [comment]
Jip, so ist es. Sobald man einen der Filter von GS auslöst werden die Kacheln neu geladen.

**Comment by 2Abendsegler** [comment]
> Jip, so ist es. Sobald man einen der Filter von GS auslöst werden die Kacheln neu geladen.

Wie doof.

**Comment by capoaira** [comment]
Das hier bleibt wohl doch eher ein Wunsch, als ein umsetzbares Issue :(

Ich habe es versucht und bin auf ein paar Probleme gestoßen:
1. Man kann die Mysterys nur ausblenden, wenn sie das große Symbol haben, nicht jedoch bei dem kleinen
2. Die Daten in der Sidebar würde trotzdem auch die Ungelösten zeigen. Wenn man diese rausfiltert, sind nicht mehr auf jeder Seite gleich viele Caches. Das könnte zu optisch unschönen Ergebnissen führen.
