### ISSUE TITLE
Logs werden dreifach angezeigt

### ISSUE THREAD

**Issue by Ingo-Knito** [2Abendsegler/GClh#1899]
### Describe the bug

Es werden alle Logs dreimalig untereinander angezeigt.
Quasi als wären es drei Caches. Bspw. wird "Publish Listing" drei Mal angezeigt.
Wenn GCLH2 deaktiviert wird, ist alles ok.

Ich habe keine Option gefunden, die dieses Verhalten verursacht.
Vielleicht hilft es zu Eingrenzung, dass nur der letzte Bereich per VIP, ... eingefärbt wird.

### To Reproduce

Tritt bei jedem Listing auf

### Expected behavior

Jeder Log sollte nur ein Mal angezeigt werden

### OS

Windows

### Browser

Chrome

### GClh Version

0.11.5.2

**Comment by Ingo-Knito** [comment]
![image](https://user-images.githubusercontent.com/39132657/132293561-0b8bef63-b530-43e0-9fa2-b1dec13af504.png)

**Comment by capoaira** [comment]
Moin, danke für das Melden des Fehlers. 

Ich erinnere mich, dass wir so einen Bug schonmal hatten: #1350, den hat damals @Ruko2010 gefixed.
Ich kann den Fehler wieder mal nicht nachstellen, aber das heißt nichts...

Der im Beispiel gezeigte Cache ist https://coord.info/GC9AZDZ

@Ingo-Knito 
1. Kannst du in der Konsole (Rechts Klick => Untersuchen => Console) gucken, ob dort Fehler angezeigt werden?
2. Läuft der GClh mehrfach (eventuell ist er noch über Greasemonkey oder als zusätzliches Add-on installiert bzw. 2 Mal in Tampermonkey) 
3. Kannst du deine Config Einstellung teilen? (Achte darauf, dass du deine Homekoords entfernst)

**Comment by Ingo-Knito** [comment]
@capoaira: Guter Hinweis mit den anderen Thread: Mit der V10.6 ist das Problem verschwunden. Mit der V11.5.2 werden beim https://coord.info/GC9AZDZ sechs Logs angezeigt.


1. Ja, es sind ein paar Fehler. Eine könnte hier wichtig sein: Uncaught TypeError: Cannot read property 'innerHTML' of null
    at hide_on_load (gc_little_helper.js:1999)
Hier alle:
[GC9ETMZ-1631016560314.log](https://github.com/2Abendsegler/GClh/files/7121369/GC9ETMZ-1631016560314.log)

2. Nein, läuft nur ein Mal über Tampermonkey

3. Kein Problem.
[Config.txt](https://github.com/2Abendsegler/GClh/files/7121424/Config.txt)

**Comment by capoaira** [comment]
Hmm, ich kann es nicht nachstellen, das war beim letzten aber auch so... @2Abendsegler hast du eine Idee?

Eins ist mir in der Logdatei aufgefallen: `VM2221:74 GM_registerMenuCommand is not supported.` Das hat zwar denke ich nichts mit diesem Bug zu tun, müsste aber eigentlich supportet werden. Hast du eine aktuelle Version von Tampermonkey?

**Comment by 2Abendsegler** [comment]
Hier ist der alte GClh wieder mit im Spiel. Bei den Nachrichten in der Konsole wird mehrfach das Script `gc_little_helper.js` benannt. Wäre es unser GClh, dann würde es `gc_little_helper_ii.js` heißen.

@Ingo-Knito 
Schau doch bitte mal im Browser bei den Add ons. Dort sollte der alte GClh noch vorhanden sein. Deaktiviere das Add on oder besser noch lösche es. Dann sollte es wieder funktionieren.

Werden eigentlich auch bei dir zwei Linklists angezeigt?

@capoaira
Vielleicht sollten wir uns nochmal Gedanken machen, ob wir in unserem Script nicht irgendwie erkennen können, dass der alte GClh noch läuft. Womöglich funktioniert das über eine Prüfung auf doppelte Linklists.

**Comment by capoaira** [comment]
Ah, das habe ich übersehen. Dafür habe ich rausgefunden, woher das Ding immer kommt: https://chrome.google.com/webstore/detail/gc-little-helper/aimnideehoepfoiniigacdpefnlngnob

**Comment by capoaira** [comment]
Und hier ist die passende Repo: https://github.com/amshove/GC_little_helper

Trotzdem kann ich den Fehler nicht reproduzieren 😅❓

**Comment by Ingo-Knito** [comment]
@2Abendsegler
Der Blick in die Add ons hat es offenbart: Ja, es war das "GC little helper 11.6" noch aktiv.
Nun ist (wieder) alles i.O.!

Besten Dank für die tolle Unterstützung!
