### ISSUE TITLE
[Cache Listing] Remove One-Click Watching, because it was added by GS

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1902]
Now GS has added the one click watching function, so we can remove our code.

@2Abendsegler are removements for `collector` or `bug-collector`?

**Comment by 2Abendsegler** [comment]
Machs in den Collector.

**Comment by 2Abendsegler** [comment]
Machs bitte in den bug collector.

**Comment by 2Abendsegler** [comment]
Jetzt ist die Verwirrung komplett. Eigentlich war die Mail mit meiner ersten Meinung noch gar nicht raus. Nach dem Löschen hat sie sich aber doch nich rausgemogelt. :) Bug collector ist besser, auch wenn es ihn wohl nicht mehr lange geben wird, weil ich jedes mal Probleme bei einem neuen Release habe.
Jetzt muss ich weiter radeln.

**Comment by capoaira** [comment]
Ok, mache ich.
Schade, dass es Probleme mit dem bug collector gibt...

>  Jetzt muss ich weiter radeln.

Viel Spaß beim Radeln.

**Comment by 2Abendsegler** [comment]
Merged with #1903
Milestone v0.11.5.3
