### ISSUE TITLE
[New Log] Placeholder "Owner" include VIP/VUP/Mail Icons 

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1911]
### Describe the bug

When you log a draft, the signature is only inserted when the log text is changed for the first time. If the VIP / VUP / Mail icons have been added by then, they will also be displayed in the Placholder.
Templates are not affected, only the signature.

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.7

### Additional context

Denselben Fehler hatte ich beim Testen von #1855 und hatte das gefixt. Scheinbar nicht gründlich genug....

**Comment by capoaira** [comment]
@2Abendsegler arbeiten wir noch mit dem bug-collector oder nur noch mit dem collector?

**Comment by 2Abendsegler** [comment]
Entschuldige, ich habe nach der letzten Version nicht richtig aufgeräumt.
Wir arbeiten nicht mehr mit dem bug-collector.

**Comment by 2Abendsegler** [comment]
Merged with #1914
