### ISSUE TITLE
[Cache Listing] Prevent popup when clicking on "Watch" or "Stop Watching".

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1913]
### Describe the solution you'd like

[Cache Listing] Prevent popup when clicking on "Watch" or "Stop Watching".

### Additional context

Ideal wäre ein css beispielsweise auf die class `qtip`, dann würden aber auch andere Popups verhindert wie beispielsweise das Fragezeichen rechts, oben in der Personal Cache Note. 

Wenn man ein css in der Hierarchie rückwärts gewandt angeben könnte wäre das hier sehr hilfreich. Also so etwas wie `.watchlist-message < div < div < div`, wobei das `<` eben in der Hierarchie rückwärts gewandt wäre. Geht so etwas? 

@capoaira Hast du ne Idee?

Popup:
![grafik](https://user-images.githubusercontent.com/22332216/133563798-acba1a55-5915-44b3-8687-0a17cbfba442.png)

**Comment by 2Abendsegler** [comment]
Gemäß folgendem Artikel gibt es solche rückwärtsgewandten CSS-Selektoren nicht.
https://www.mediaevent.de/css/css-selektor-kontextselektor.html unter "CSS Vorgänger-Selektoren" und darunter.

**Comment by capoaira** [comment]
In css gibt es leider kein funktioniert wie parent. Man kann nur das nächste oder innere Elemente ansprechen.

In diesem Fall müsste es, wenn GS sauber gearbeitet hat, aber über die id #qtip-content gehen. Eine id sollte nicht mehrmals verwendet werden.
Oder wir machen das mit js
$('.watchlist-massage').parent('#qtip-content').css('display', 'none');

**Comment by 2Abendsegler** [comment]
> In diesem Fall müsste es, wenn GS sauber gearbeitet hat, aber über die id #qtip-content gehen. Eine id sollte nicht mehrmals verwendet werden.

Der erste Block ist vom Fragezeichen über der Personal Cache Note. Der zweite ist vom Watchclick.

![grafik](https://user-images.githubusercontent.com/22332216/133568322-17382467-7b27-4535-8aee-908a53326a60.png)
Soviel dazu.

> Oder wir machen das mit js
> $('.watchlist-massage').parent('#qtip-content').css('display', 'none');

Dafür müsste das Element aber schon vorhanden sein. Das ist aber nicht der Fall. Der ganze Block wird bei jedem erneuten Klick neu aufgebaut und durchnummeriert und dann entfernt, wenn man an eine andere Stelle klickt und das Popup verschwindet. Ich werde das aber mal über ein eigenes Klick Event versuchen. Ich weiß nicht ob ich damit schnell genug bin, oder ob das Popup dann noch kurz aufflackert.

Danke schon mal.

Falls dir noch etwas einfällt ... 😊

**Comment by capoaira** [comment]
Mir fällt gerade tatsächlich noch etwas ein. Vielleicht kann man mit dem `:not()`-Selektor arbeiten.

**Comment by capoaira** [comment]
> Mir fällt gerade tatsächlich noch etwas ein. Vielleicht kann man mit dem `:not()`-Selektor arbeiten.

Das funktioniert leider nicht :(
Ich hatte den `:not()`-Selektor leider falsch in Erinnerung...

**Comment by 2Abendsegler** [comment]
Hm, dann bin ich aber doch auch schon zu weit unten in der Hierarchie, oder? Ich muss ja den kompletten qtip ausblenden.

Dein not bringt mich noch auf eine andere Idee. Vielleicht blende ich alle aus und den einen für die Personal Cache Note explizit nicht. Dann muss ich nur noch schauen ob es noch andere gibt.

**Comment by 2Abendsegler** [comment]
![Screen02](https://user-images.githubusercontent.com/22332216/133649252-a4a4d63a-36e7-475a-b2ef-e0253eaf8b92.jpg)

![Screen03](https://user-images.githubusercontent.com/22332216/133649254-7e07198f-30fd-47fd-9224-79e63d915db2.jpg)
If you want to use this feature, you have to activate it.

**Comment by 2Abendsegler** [comment]
Merged with #1916
