### ISSUE TITLE
[Old log form] Automatic opt out to the old log form with a draft run into error on old log form.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1917]
### Describe the bug

[Old log form] Automatic opt out to the old log form with a draft run into error on old log form.

The error is not shown because of missing try, catch.

Line with error is `$('#uxNewLoggingBannerLink')[0].href += '?gclhNewLog=true';`

### To Reproduce

1. Go to old drafts
2. Choose "compose log"
3. See error in console

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.7

**Comment by capoaira** [comment]
Oh, das habe ich wohl verbockt...

**Comment by 2Abendsegler** [comment]
Merged with #1918
