### ISSUE TITLE
[Pocket Query] Some default values are not set if the PQ is created from map. Keep "Set default" parameter in mind.

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#1920]
### Describe the bug

Wenn über "Save As Pocket Query" ein neuer Pocket Query angelegt wird, dann werden nicht mehr alle Einstellungen entsprechend der Config gesetzt.

Zumindest die drei Einstellungen werden ignoriert.
- Set difficulity  
- Set terrain 
- Enable option "Include pocket query name in download file name"

### To Reproduce

siehe oben

### Expected behavior

siehe oben

### OS

Windows

### Browser

Firefox

### GClh Version

 v0.11.7

**Comment by capoaira** [comment]
> Kann man eigentlich irgendwo den Schalter von „Set defaults“ auf True/Haken/ON setzen oder muss man das immer neu setzen?

Nein, aber das lässt sich sicher in der nächsten Version umsetzen.

**Comment by capoaira** [comment]
ToDo:
- [ ] Fix Bug
- [ ] Save if the gclh default values should set

**Comment by 2Abendsegler** [comment]
@capoaira 

1. Fix PQ from Browse Map:
Soll eine PQ aus der Browse Map angelegt werden, werden die Defaults "I haven't found" und "I don't own" explizit nicht gesetzt. Wir haben sie explizit für diesen Fall ausgenommen. 
`  if (!document.location.href.match(/aspx\?ll=/)) { // Not for Save as PQ from Browse Map.  `
Dafür gab es wohl einen Grund (ich schätze das habe ich gemacht), ich kenne ihn aber nicht mehr. Fällt dir dazu etwas ein?

**Comment by capoaira** [comment]
> Dafür gab es wohl einen Grund (ich schätze das habe ich gemacht), ich kenne ihn aber nicht mehr. Fällt dir dazu etwas ein?

Hm, ne fällt mir auch nicht mehr ein.

**Comment by 2Abendsegler** [comment]
- [ ] Fix: Set defaults "I haven't found" and "I don't own" in Browse Map. 
- [ ] Fix: Set defaults "I haven't found" and "I don't own" and "Is Enabled" in Search Map. 
- [ ] New: Keep "Set defaults" parameter for save as pocket query in Browse Map in mind. 
- [ ] New: Keep "Set defaults" parameter for save as pocket query in Search Map in mind. 

---
merged with #1975
