### ISSUE TITLE
[Search Map] The GClh default filters setting change map zoom.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1921]
### Describe the bug

If the GClh set default values, the map zoom is changes also. This should not happen.

### OS

Windows

### Browser

Firefox

### GClh Version

collector

**Comment by 2Abendsegler** [comment]
Jedes Mal wenn GS wieder irgendwo bastelt ist es danach komplizierter als zuvor. Wer hat das nochmal geschrieben ... 
Wieder mal echter Scheiß.

Die beschriebene Problematik ist quasi ein Feature von GS. Wenn der Filter angewählt und applyed wird, wird soweit raus gezoomt bis die maximale Anzahl von Caches gemäß Map Settings und Filters dargestellt werden können. Das kann man quasi nur dadurch umgehen, indem man bei der Lokation beispielsweise die Homekoordinaten eingibt. Die kann man aber nicht einfach eingeben, sondern muss sie anschließend auch noch aus den möglichen Eingaben auswählen.

---
- [ ] Fix [Search Map] The GClh default filters setting change map zoom.
- [ ] New [Search Map] Don't display the filters screen during the GClh default filters setting are running.

**Comment by 2Abendsegler** [comment]
merged with #1921
