### ISSUE TITLE
[Search Map] Button "Browse geocaches" remains, even if it is relocated to the other buttons.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1927]
### Describe the bug

[Search Map] Button "Browse geocaches" remains, even if it is relocated to the other buttons.

Parameter [Relocate the buttons "Search" and "Browse geocaches" to the other buttons](https://www.geocaching.com/my/#GClhShowConfig#a#settings_relocate_other_map_buttons) is activated.

![grafik](https://user-images.githubusercontent.com/22332216/138542457-14f9708d-1887-4652-9ed1-44fcb941a481.png)

### To Reproduce

1. Activate config parameter [Relocate the buttons "Search" and "Browse geocaches" to the other buttons](https://www.geocaching.com/my/#GClhShowConfig#a#settings_relocate_other_map_buttons).
2. https://www.geocaching.com/map/
3. See button "Browse geocaches" and Icon.

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.7

**Comment by capoaira** [comment]
merged with #1941
