### ISSUE TITLE
[Search Map] The first line of buttons in sidebar is again bigger then necessary in compact layout.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1929]
### Describe the bug

[Search Map] The first line of buttons in sidebar is again bigger then necessary in compact layout.

![grafik](https://user-images.githubusercontent.com/22332216/138542870-5248ca8a-e904-4b2f-92a4-b8c0e84fe38b.png)

### To Reproduce

1. https://www.geocaching.com/play/map/
2. Look to the first line of buttons in sidebar

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.7

**Comment by capoaira** [comment]
merged with #1942
