### ISSUE TITLE
[Search Map] Header has white space border if "Change header layout" is disabled.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1936]
### Describe the bug

![grafik](https://user-images.githubusercontent.com/50927164/139302192-4d381911-2348-4d85-a81d-886014303a68.png)

### OS

Windows

### Browser

Firefox

### GClh Version

actual collector

**Comment by 2Abendsegler** [comment]
@capoaira 
Ich kann das Problem gerade nicht nachstellen. Kannst du bitte mal schauen ob das Problem noch besteht?

**Comment by capoaira** [comment]
Jip, besteht noch. Ich habe "Change Header Layout" nicht an. Wenn ich das anstelle, passt die Größe...

**Comment by 2Abendsegler** [comment]
Hm, ich bekomme das Problem nicht nachgestellt. Ich schätze da gibt es noch eine andere Besonderheit. Vielleicht hat es damit zu tun, dass du nicht mehr ausreichend oft cachen gehst. 😄
Vielleicht kannst du dir das irgendwann mal ansehen, wenn du mal Zeit und Lust hast.

**Comment by capoaira** [comment]
> Vielleicht hat es damit zu tun, dass du nicht mehr ausreichend oft cachen gehst. 😄

Daran wird es liegen. 🤣

>  Vielleicht kannst du dir das irgendwann mal ansehen, wenn du mal Zeit und Lust hast.

Jip, mache ich. Wobei mir im Moment zugegebenermaßen etwas die Motivation fehlt. Sowohl zum Cachen (außer FTF ;)) als auch hier etwas zu machen. Aber das ändert sich sicher wieder, sobald ich mich an den Uni-Alltag gewöhnt habe. ;)

**Comment by 2Abendsegler** [comment]
merged with #1944

**Comment by 2Abendsegler** [comment]
Ja ok, hatte es nicht geöffnet. 🤭

**Comment by 2Abendsegler** [comment]
Zurückgesetzt mit #1955.
@capoaira Bitte beachte, dass sich main.css geändert hat.

**Comment by 2Abendsegler** [comment]
Merged with #1963
