### ISSUE TITLE
GC Map link is not shown everytime on openstreetmap.org

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#194]
In some cases the GCMap link button is not always shown on openstreetmap.org - especially in case of automatic redirect from www.openstreetmaps.org to www.openstreetmap.org/#map=...

**Comment by 2Abendsegler** [comment]
Womöglich betrifft das nur folgende Seiten: www.openstreetmap.org/?#map=...
Das "?" muß noch behandelt werden.
Außerdem hatte ich auch mal sowas: www.openstreetmap.org/history#map=...
Ich habe das mal entsprechend im v0.5_cf angepaßt und mit $$FE001 gekennzeichnet. 
Anschließend war der Button immer da. 

Old: 
`if ( document.location.href.match(/^(http|https):\/\/www\.openstreetmap\.org\/#map=/ ) && ...`
New:
`if ( document.location.href.match(/^(http|https):\/\/www\.openstreetmap\.org\/(.*)#map=/ ) && ...`

Kann es das gewesen sein?

**Comment by 2Abendsegler** [comment]
Die Änderung ist im Collector.
Meines Erachtens kann Issue geschlossen werden.

**Comment by CachingFoX** [comment]
Done
