### ISSUE TITLE
Collaborator Test

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#195]

**Comment by 2Abendsegler** [comment]
Die Änderung wird Dir nicht gutgeschrieben, wie ich befürchtet habe. Die Commits zählen bei mir.
Ein Elend, was funktioniert hier eigentlich mal ohne wenn und aber. 
Ich schick Dir das jetzt auch noch über eine PN des geoclubs, weil GitHub mir sagt, dass Deine Mail Adresse nicht mehr richtig hinterlegt ist.

**Comment by 2Abendsegler** [comment]
Ach ja, der Fuchs hat nun ausgesprungen, :)
Habe die Änderung wieder zurückgedreht.
