### ISSUE TITLE
[Log forms] Show number and percentage of favorites and number of watcher.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#1965]
### Describe the solution you'd like

Show number and percentage of favorites in both log forms, to have a better idea, of whether or not you should put a favorite.

New log form:
![Unbenannt1](https://user-images.githubusercontent.com/22332216/145602813-8b17f90d-fcce-4900-8ecd-a8be454f99ee.JPG)

Old log form:
![Unbenannt2](https://user-images.githubusercontent.com/22332216/145604443-47a9f804-c419-4812-809a-1608cc8cc3f8.JPG)

**Comment by capoaira** [comment]
Die Idee gefällt mir. Ich kann mir aber vorstellen, dass es bei der neuen Logseite zu Verwirrung führen könnte, da beim hovern die eigene Anzahl, der zur Verfügung stehenden Favs angezeigt wird.

**Comment by capoaira** [comment]
Vielleicht sollten wir die Info lieber unter/neben den Cachenamen schreiben.

**Comment by 2Abendsegler** [comment]
Guter Punkt. 
Dann sollten wir vielleicht die Zahlen, so wie beim alten Log Formular vorgesehen, hinter den VIP ... Icons oder so einbauen und zusätzlich auch eine Info beim Hovern angeben. Vielleicht dann auch ein gefülltes Herz verwenden, auch im alten Log Formular.
Was meinst du?

**Comment by capoaira** [comment]
Jip, finde ich gut. 👍🏻

**Comment by 2Abendsegler** [comment]
Old log form:
![Screen08](https://user-images.githubusercontent.com/22332216/147250424-ea7d52f5-1a51-43a8-869f-9eb4304bec6f.jpg)

---
New log from:
![Screen09](https://user-images.githubusercontent.com/22332216/147250465-ecfd5f66-0038-41a6-ad4e-450af046153f.jpg)

---
Settings -> Logging:
![Screen10](https://user-images.githubusercontent.com/22332216/147250476-33cec0bd-c1c4-44ea-9d25-272daf56b5f5.jpg)

---
Merged with #1998

---
To do: Maintain standard parameter file: settings_show_add_cache_info_in_log_page
