### ISSUE TITLE
"Go to logs" link malfunction

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#1981]
### Describe the bug

The "Go to logs" link in the right column of a cache listing no longer works.

Gclh II version: 0.11.8.1
Browser: Firefox 95.0.1 x64

![image](https://user-images.githubusercontent.com/9153595/146682554-8eefb36f-5a8a-400a-a1ef-999bb1a9c450.png)

### To Reproduce

1. Open for instance https://coord.info/GC9D9NT
2. Click on the "Go to Logs" link
3. Nothing happens

### Expected behavior

The link should take us down to the logs section of the page.

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.8.1

**Comment by 2Abendsegler** [comment]
Thanks for reporting the bug.

We have fixed it already with issue #1966.

A new version will be available in a few days. 

You can install an [advance correction](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js), if you want. However, other adjustments are already included there.

I will close this issue.

**Comment by 2Abendsegler** [comment]
Close because of duplicated issue.
