### ISSUE TITLE
Overview map in listing: zoom in/out loses cache marker

### ISSUE THREAD

**Issue by DieBatzen** [2Abendsegler/GClh#2]
Hello 2Abendsegler ,

there's a minor issue if you also have the script "Geocaching Map Enhancements" (http://geo.inge.org.uk/gme.htm) installed.

If you zoom in/out the overview map in a cache listing, the cache marker gets replaced by a default marker and the static image shows an error message:
![grafik](https://cloud.githubusercontent.com/assets/16579282/21720295/8d1d5aa8-d422-11e6-8eff-3843deab9d78.png)

The reason is that GME changes the cache image link and therefore the proper marker creation fails.
But there seems to be an easy fix:
in function `buildMapValues`, change lines 2289 and 2290 from
```
if ( $("img:first", "a[href='/about/cache_types.aspx']")[0] ) {
            var src_arr = $("img:first", "a[href='/about/cache_types.aspx']").attr("src").split("/");
```
to
```
if ( $(".cacheImage").find("img").attr("src") ) {
            var src_arr = $(".cacheImage").find("img").attr("src").split("/");
```

Keep up the great work!

Regards,
Thomas

**Comment by 2Abendsegler** [comment]
Danke für die klasse Beschreibung und das fertige Coding. :)
Kommt mit der nächsten Version.
Issue lass ich offen, ich hab das Script nicht am Laufen und kann nicht abschließend testen.
LG Frank
