### ISSUE TITLE
[Public Profile] Change links to found/hide caches to the old link no longer works

### ISSUE THREAD

**Issue by joemadder** [2Abendsegler/GClh#2012]
### Describe the bug

Change links to found/hide caches to the old link no longer works

### OS

Linux

### Browser

Chrome

### GClh Version

0.11.9

**Comment by 2Abendsegler** [comment]
Yes, you are right.

---
Betrifft alle Links im Cache Tab. Class `span-9` gibt es nicht mehr.
Parameter: settings_profile_old_links

**Comment by 2Abendsegler** [comment]
Thanks for reporting the bug.

We have fixed it already with issue #2013.

You can install an [advance correction](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js), if you want. However, other adjustments are already included there.

I will close this issue.

Nice weekend
Frank

---
Merged with #2013
