### ISSUE TITLE
[Pocket Query] Revise the look of the buttons.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2028]
### Describe the solution you'd like

[Pocket Query] Revise the look of the buttons.

**Comment by 2Abendsegler** [comment]
Add to Queue Button does not run because the type is no longer "submit" but "button". This change in this issue was wrong.

**Comment by 2Abendsegler** [comment]
Bug fixing merged with #2048

**Comment by 2Abendsegler** [comment]
Delete Button does not run in both tabs.
Was mach ich nur für einen Scheiß.

**Comment by capoaira** [comment]
merged with #2072
