### ISSUE TITLE
[Header] Submenu is displayed on wrong position on wide screens

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2035]
### Describe the bug
![grafik](https://user-images.githubusercontent.com/50927164/152202102-42eda83a-66a6-403b-a085-483f2f52de0a.png)

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.11 (and earlier)

**Comment by 2Abendsegler** [comment]
Merged with #2038

**Comment by 2Abendsegler** [comment]
Kleine Anpassung für Browse Map.

**Comment by 2Abendsegler** [comment]
Merged with #2043
