### ISSUE TITLE
[Cache Listing / Browse Map / Search Map] Log type counters are no longer displayed correct.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2044]
### Describe the bug

[Cache Listing / Browse Map / Search Map] Log totals are no longer displayed correct.

Das HTML Coding zu den Log Totals wurde auf der Cache Listing Webseite geändert.  
- [x] 1. Im Cache Listing werden die Log Totals im Kopf unterhalb der Favoritenbox kurz falsch dargestellt und verschwinden dann.
![grafik](https://user-images.githubusercontent.com/22332216/152443848-0feec42b-44c6-4187-b5fe-e81a8084a716.png)
Zu änderndes Coding beginnt bei:
`// Show log totals symbols at the top of cache listing.`

- [x] 2. Im Cache Listing werden die Standard Log Totals oberhalb der Logs ausgeblendet und werden nicht neu aufgebaut.
![grafik](https://user-images.githubusercontent.com/22332216/152444108-d71d4b54-f03c-4eef-b294-8622036911f9.png)
Zu änderndes Coding beginnt bei:
`var legend = document.getElementById("ctl00_ContentBody_lblFindCounts").childNodes[0];`

- [x] 3. Die Log Totals im Popup der Browse Map werden nicht mehr korrekt dargestellt.
![grafik](https://user-images.githubusercontent.com/22332216/152444971-dfb067c2-ec86-4e0d-8d4b-d3944a61ccea.png)

- [x] 4. Die Log Totals im Cache Details Screen der Search Map werden nicht mehr korrekt dargestellt.
![grafik](https://user-images.githubusercontent.com/22332216/152445056-83233b93-09fd-4c59-8776-332beafb1916.png)

### To Reproduce

Für 1. und 2.: Aufruf eines Cache Listings.

Für 3.: Browse Map und dann klick auf Cache Icon.

Für 4.: Search Map und dann klick auf Cache Icon.

### OS

Windows

### Browser

Firefox

### GClh Version

actual collector

**Comment by capoaira** [comment]
Ich habe das Issue mal gepinnt, um es für alle präsenter zu machen. ;)

**Comment by capoaira** [comment]
Moin, wie viel anpassungen hast du hier schon gemacht? Ich hätte in den nächten Tagen evt. die Zeit wieder etwas zu machen.

**Comment by 2Abendsegler** [comment]
Nur das was bereits im PR vorhanden ist und was im Issue abgehakt ist. Den PR kannst du mergen.

**Comment by 2Abendsegler** [comment]
Merged with #2046

---
Du hast richtig viel weggeschafft, echt super, danke!
Spricht etwas dagegen wenn ich heute Abend eine neue Version fertig mache?

**Comment by capoaira** [comment]
> Spricht etwas dagegen wenn ich heute Abend eine neue Version fertig mache?

Ich denke nicht :)
