### ISSUE TITLE
Log type counters no longer displayed

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [2Abendsegler/GClh#2049]
### Describe the bug

At least over here the log type counters (x Found it, y Write Note, 1 Publish Listing) which are usually displayed above the ``View all logs (zz)`` link, are no longer displayed. After loading a listing I can see them for the fraction of a second below the favorites counter and on reload even at their "normal" place, but then they disappear. Pressing the ``Show log counter`` button does nothing.

BTW: ``settings_show_log_counter_but`` and ``settings_show_log_counter`` are usually set to true, but even changing them (or just the second) to false does not change a thing.

Moreover, the code for this stuff is there:
```
            <div class="InformationWidget Clear">
                <h2 class="h3">
                    37 Logged Visits
                </h2>
                <span id="ctl00_ContentBody_lblFindCounts"><ul class="LogTotals" aria-labelledby="LoggedVisits"><li><img src="/images/logtypes/2.png" alt="Found it" title="Found it" /> 34</li><li><img src="/images/logtypes/4.png" alt="Write note" title="Write note" /> 2</li><li><img src="/images/logtypes/24.png" alt="Publish Listing" title="Publish Listing" /> 1</li></ul></span>
                <div class="Callout">
                    <p class="HalfLeft">
                        <a id="ctl00_ContentBody_uxLogbookLink" href="../seek/geocache_logs.aspx?guid=3dc04f84-b0be-4a5d-8526-565b5229b8da">View all logs (37)</a>
                    </p>
                    <p class="NoBottomSpacing AlignRight">
                        <span class="Warning">**Warning!</span> <a href="/about/glossary.aspx#spoiler" title="Spoilers">Spoilers</a> may be included in the descriptions or links.
                    </p>
                </div>
            </div>
```

Ah, even the ``View all logs (37)`` link text is incomplete, I just see ``all logs (37)``:
![No Log Counters anymore](https://user-images.githubusercontent.com/9889015/152704486-71539016-3a78-4766-91dc-d6372dd964d1.jpg)

### To Reproduce

Open any listing and look for the log type counters ...

### Expected behavior

Log type counters should be there or at least appear after pressing the corr. button.

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.12

**Comment by 2Abendsegler** [comment]
Moin,
thanks for reporting the bug.
We have already an issue for this bug: #2044
I improved the heading in it.

**Comment by MagpieFourtyTwo** [comment]
Ah - ok - thx!
