### ISSUE TITLE
Popup cache details in map too big

### ISSUE THREAD

**Issue by eddydc** [2Abendsegler/GClh#2050]
### Describe the bug

For some the cache details popup in the maps is much bigger than it used to be. It occurs that the number of logs per log type is causing this by showing them below instead of next to each other 
![2022-02-08_8-01-41](https://user-images.githubusercontent.com/25877499/152935695-d6c86536-651c-4f20-9bd3-c7786e7fa6f7.png)
The map doesn't move either when the popup doesn't fit on the screen due to the bigger popup
Van this be fixed in order to have smaller popup pls?
 

### To Reproduce

Go to maps and click on cache in order to have a popup

### OS

Windows

### Browser

Firefox

### GClh Version

0.11.12

**Comment by 2Abendsegler** [comment]
Moin,
thanks for reporting the bug.
We have already an issue for this bug: #2044

**Comment by eddydc** [comment]
Ok, I was looking at previous reports, but for some reason didn't see the link. Sorry for that. 
This issue can be closed then.

**Comment by 2Abendsegler** [comment]
No problem.

For the bug in the Browse Map you can install this [advance correction](https://github.com/2Abendsegler/GClh/blob/067d976af0138905317d25a5b7200b081e028e66/gc_little_helper_II.user.js?raw=true), if you want. However, other adjustments are already included there.
