### ISSUE TITLE
[Config] Typo in settings

### ISSUE THREAD

**Issue by eddydc** [2Abendsegler/GClh#2054]
### Describe the bug

Hidding should be hiding
![2022-02-11_7-45-41](https://user-images.githubusercontent.com/25877499/153548089-67ca6ae4-fad2-4f05-ba80-97ba66040f1c.png)

### To Reproduce

Go to the settings of GClh

### OS

Windows

### Browser

Firefox

### GClh Version

v0.11.12

**Comment by 2Abendsegler** [comment]
Thanks for reporting the bug.
We will correct it in the next version. 

---
Can you please tell us your geocaching name, so we can mention you on the GClh thank you page?

**Comment by 2Abendsegler** [comment]
Merged with #2066
