### ISSUE TITLE
[Pocket Query] "Delete Selected" ohne Wirkung bei "Your Pocket Queries"

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#2056]
### Describe the bug

Bei "Your Pocket Queries" ist der Button "Delete Selected" ohne Wirkung für die Selektierten. Es kommt zwar noch die Rückfrage, ob man wirklich löschen will, aber dann passiert nichts mehr.

![image](https://user-images.githubusercontent.com/7745027/153896191-76c70974-e27e-423f-91b4-6a87f6348df3.png)

### To Reproduce

1. Zu "Your Pocket Queries" navigieren
2. Pocket Queries selektieren
3. Button "Delete Selected", egal ob bei "active pocket Queries" oder "pocket Queries ready for Download" anklicken
4. Frage "Are you sure you want to delete 1 PQ(s)?" mit "OK" geantwortet
5. dann passiert nichts mehr, refresh bringt auch nichts

Das Problem hatte ich bei Firefox, Chrome und Edge.

Damit ich die Queries löschen kann habe ich Tampermonkey mal deaktiviert. Ohne den GClh hat es dann geklappt.

### OS

Windows

### Browser

Chrome

### GClh Version

v0.11.12

**Comment by capoaira** [comment]
Bug is fixed in #2028
