### ISSUE TITLE
[Log Form] Submit with F2

### ISSUE THREAD

**Issue by king-ton** [2Abendsegler/GClh#2057]
### Describe the solution you'd like

Submit the new Log Form by pressing F2 key.

### Additional context

The old draft logging page is not more available. I use this function für every log submit and it is very helpful. You have not to scroll to the bottom. Because of this feature I always used the old logging page.

I know you removed this feature because it was instable. Is there any possibility to integrate it again?
For example first as an experimental feature?

Thanks!

**Comment by 2Abendsegler** [comment]
Moin,

wir hatten das schon mal versucht, haben es aber wieder ausgebaut, weil wir es nicht stabil hinbekommen haben. Siehe [Kommentar Issue #1046](https://github.com/2Abendsegler/GClh/issues/1046#issuecomment-522235653). 

Wir können dein Issue aber mal offen lassen. Sobald die neue Draft Seite von GS fertiggestellt ist, werden wir uns den Ablauf von den neuen Drafts über die neue Log Seite sicherlich noch mal genauer ansehen. Vielleicht haben wir dann auch hierzu noch neue Ideen.

**Comment by king-ton** [comment]
Danke dir für die schnelle Antwort!
Ja das hatte ich gelesen. Will GS hier aktuell noch etwas an den Drafts machen? Letzte Info, die ich gelesen habe, ist die hier: https://forums.geocaching.com/GC/index.php?/topic/370029-release-notes-website-upcoming-retirement-of-the-old-drafts-pages-february-1-2022/

**Comment by 2Abendsegler** [comment]
Ja, ich verstehe es so, dass sie noch etwas an den Drafts machen wollen. Sie haben mal alle Wünsche aufgenommen und wollen sich das mal ansehen. Die [Liste von Bl4ckH4wkGER](https://forums.geocaching.com/GC/index.php?/topic/370029-release-notes-website-upcoming-retirement-of-the-old-drafts-pages-february-1-2022/&do=findComment&comment=5967862) sieht auch vielversprechend aus. Sicherlich werden nicht alle Wünsche berücksichtigt, ein paar aber vielleicht schon.

**Comment by king-ton** [comment]
@2Abendsegler ich mal mal was gebaut. Schaue es dir einfach mal an. Bei mir behebt es 2 Probleme, die ich im PR beschrieben habe.

**Comment by 2Abendsegler** [comment]
@king-ton 
Moin,
wir haben im Redesign des neuen Log Formulars (Issue #2424) eine F2 Verarbeitung eingebaut. In der nächsten Version in ein paar Tagen ist dieses Feature enthalten. 
Ich schließe dein Issue schon mal.
