### ISSUE TITLE
[Cache Listing] "Show log counter" button doesn't work anymore

### ISSUE THREAD

**Issue by Chrono81** [2Abendsegler/GClh#2060]
### Describe the bug

In the description page, a click on the "Show log counter" button doesn't work anymore. 
unlike usual no counter is displayed on the first line of each log 

### To Reproduce

1. Go to the description page of a geocache.
2. Click on the Show log counter button
3. Normally the log counter should be displayed on the first line of each log but it doesn't.

### OS

Windows

### Browser

Firefox

### GClh Version

v0.11.12

**Comment by capoaira** [comment]
Thank you for reporting the bug.
We will fix it asap.

Maybe Related to #2044

**Comment by capoaira** [comment]
This Bug will be fixed with Issue #2044 in PR #2046 
I close this Issue to clean up the Issue Tracker
