### ISSUE TITLE
[New Log Form] Favorite percentages are displayed incorrectly.

### ISSUE THREAD

**Issue by arduhe** [2Abendsegler/GClh#2061]
### Describe the bug

Im Dialog für das Loggen eines Fundes wird die Zahl der bisher vergebenen Favos falsch angezeigt (Faktor 10 zu hoch)

![grafik](https://user-images.githubusercontent.com/65784966/155891379-631a2949-7a54-4903-89a0-36e86eefd946.png)

Im Vergleich dazu die Anzeige aus dem zugehörigen Listing
![grafik](https://user-images.githubusercontent.com/65784966/155891437-55ed2890-08d9-498c-ba64-6bd086e45845.png)

Da scheint sich ein Rechenefehlerteufelchen eingeschlichen zu haben ;-) 

### OS

Linux

### Browser

Firefox

### GClh Version

0.11.12

**Comment by arduhe** [comment]
Wie ich gerade gesehen habe, tritt das Phänomen nicht immer auf 😲

Bei dieser Dose sind die Angaben korrekt. Beim Loggen

![grafik](https://user-images.githubusercontent.com/65784966/155892282-cb86a441-292d-41df-995b-e661914f7b55.png)

zum Vergleich im Listing

![grafik](https://user-images.githubusercontent.com/65784966/155892310-4c2ada4e-ec44-4976-ab23-a8255bb43dbc.png)

**Comment by 2Abendsegler** [comment]
Moin,

danke für die Meldung des Bugs. 

Ich kann das Problem nachvollziehen. Scheinbar werden die Prozentzahlen in bestimmten Fällen nicht mehr richtig dargestellt. Die `0` bei den `30` sind nämlich die Prozente und sollten als ` 0%` dargestellt werden. Vermutlich ist die `0` lediglich ein Platzhalter der nicht mehr versorgt wird. 
Wir berechnen die Prozente nicht, sondern übernehmen sie quasi aus dem Cache Listing. 

Wir werden das untersuchen und für die nächste Version berichtigen.

LG
Frank

**Comment by 2Abendsegler** [comment]
Das Beispiel von oben:
https://www.geocaching.com/play/geocache/gc93kt0/log

Das Problem scheint nur dann aufzutreten, wenn die Anzahl der Favoriten größer 0 ist, die Favoritenprozente aber 0 sind. https://www.geocaching.com/play/geocache/gc5fv6b/log
https://www.geocaching.com/play/geocache/gc6d5hg/log

Überall sonst scheint es ok.

**Comment by 2Abendsegler** [comment]
@capoaira 
Super, danke für den Fix.

---
Merged with #2067
