### ISSUE TITLE
Remove the popup for external links

### ISSUE THREAD

**Issue by technetium** [2Abendsegler/GClh#2077]
### Is your feature request related to a problem? Please describe

I'm always frustrated when the popup appears when I click on an external link. Especially because it disables the [CTRL]-click feature to open the link in a new tab. 

### Describe the solution you'd like

Add the following code:
````
document.querySelectorAll("#ctl00_ContentBody_LongDescription a").forEach(a => a.addEventListener("click", () => event.stopImmediatePropagation(), true))
````

### Additional context

No need to do something fancy for user defined events on href's since Groundspeak, inc. DBA geocaching.com has disabled them for user content.

**Comment by capoaira** [comment]
Thanks for your input. We are working on it and will be adding this feature in the next release

We have already an Issue for this #2053, so I close this one.
