### ISSUE TITLE
[Drafts] Improve drafts page

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2079]
### Describe the solution you'd like

![grafik](https://user-images.githubusercontent.com/22332216/157557613-583f9dbe-96b4-4061-934f-2160c9fc3c84.png)

**Comment by MagpieFourtyTwo** [comment]
-T-H-A-N-K-S- A LOT!!!!!einself  ;))))
Die alte Logseite ... danke!!  :)
