### ISSUE TITLE
[Search Map / Browse Map] Show Weekday of an Event

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2091]
### Describe the solution you'd like

Show the Time and Weekday next to the date

**Comment by capoaira** [comment]
Notice: `$.get()` does not give `head` information, so the meta tag with a uniform date format is missing :(

**Comment by 2Abendsegler** [comment]
Innerhalb von body stehen aber auch noch andere Informationen. Wenn du in einem Event stehst dann such mal nach eventCacheData. Das müsste doch auch funktionieren fürs Datum.

```
//<![CDATA[
var isLoggedIn = true;
var eventCacheData = {
start: new Date(2022, 05-1, 07, 10, 30)
, end: new Date(2022, 05-1, 07, 11, 00)
```

**Comment by capoaira** [comment]
Ah, cool. Dann probiere ich das später mal.

**Comment by ChristianGK-GC** [comment]
Hallo capoaira,

das ist doch schon teilweise umgesetzt.
![grafik](https://user-images.githubusercontent.com/24353480/175761477-ef2f3689-9212-4ae0-8725-5a18835fe7a9.png)
Es fehlt doch hier nur noch die Uhrzeit oder?

Gruß
Christian

**Comment by capoaira** [comment]
Moin Christian,

Das feature soll auf die beiden Karten. Auf der Search Map z.B. hier:
![grafik](https://user-images.githubusercontent.com/50927164/175764344-40bb636e-4ed4-4714-95c5-6f65cedc9b9b.png)

Hintergrund ist, dass ich zu faul bin, immer das Listing eines Events zu öffnen, wenn ich z.B. eine Cachetour plane. 😅

**Comment by ChristianGK-GC** [comment]
Moin capoaira,

Hast du es dir so vorgestellt?
![grafik](https://user-images.githubusercontent.com/24353480/189514278-eb87e43b-fa57-4e98-b02f-fc5b7624c0ea.png)

In der anderen Map werden mir die ganzen Informationen gar nicht angezeigt.


`if (settings_show_eventday && (text.match(/eventCacheData/) != null)) {
	var matchDate = text.match(/(<meta name="description" content=").*([0-9]{2})\/([0-9]{2})\/([0-9]{4}).*?(\/>)/);
	if (matchDate != null) {
		var date = new Date(matchDate[4], matchDate[2], matchDate[3]);
			if (date != "Invalid Date") {
				var weekdays = new Array(7);
				weekdays[0] = "Sunday"; weekdays[1] = "Monday"; weekdays[2] = "Tuesday"; weekdays[3] = "Wednesday"; weekdays[4] = "Thursday"; weekdays[5] = "Friday"; weekdays[6] = "Saturday";
				var weekday = weekdays[date.getDay()];
				console.log('Day: ' + weekday);
				document.getElementById('gmCacheInfo').children[0].children[0].children[3].children[1].append(' ('+weekday+')');
			}
	}
}`

**Comment by capoaira** [comment]
Ja, so habe ich mir das vorgestellt. 👍🏻

>In der anderen Map werden mir die ganzen Informationen gar nicht angezeigt.

Da die Requests mehr oder weniger gleich aufgebaut sind, solltest du die Infos auf beiden Karten gleichermaßen bekommen.

**Comment by ChristianGK-GC** [comment]
Auf der Karte:
https://www.geocaching.com/play/map?lat=48.0785&lng=11.6122&zoom=14&asc=true&sort=distance&st=N+48%C2%B0+6.349%27+E+11%C2%B0+33.180%27&ot=coords
Sieht das bei mir so aus.
Die ganzen Infos fehlen....
![grafik](https://user-images.githubusercontent.com/24353480/189550317-6e55934a-7b23-4b34-bfa1-6eb79fc499f4.png)

**Comment by ChristianGK-GC** [comment]
> Das feature soll auf die beiden Karten. Auf der Search Map z.B. hier: ![grafik](https://user-images.githubusercontent.com/50927164/175764344-40bb636e-4ed4-4714-95c5-6f65cedc9b9b.png)

Das alles fehlt bei mir... Seltsam.

**Comment by capoaira** [comment]
Den Fehler habe ich lange nicht mehr gesehen, und ich bin mir nicht mehr sicher woran es lag. Ich tippe jetzt einfach mal auf config Einstellungen, die trotz unserer vielen Tests nicht zusammen passen. 
Den PC habe ich aber gerade heruntergefahren, also kann ich erst morgen auf Fehlersuche gehen 😉

**Comment by ChristianGK-GC** [comment]
Achja und auf beiden Karten Seiten [play/map](https://www.geocaching.com/play/map) & [map](https://www.geocaching.com/map/) hab ich den Fehler, sobald ich einen Cache anklicke.
![grafik](https://user-images.githubusercontent.com/24353480/189550535-5434ac9c-ade6-4591-b03e-6e083512413f.png)

**Comment by capoaira** [comment]
> Achja und auf beiden Karten Seiten [play/map](https://www.geocaching.com/play/map) & [map](https://www.geocaching.com/map/) hab ich den Fehler, sobald ich einen Cache anklicke. ![grafik](https://user-images.githubusercontent.com/24353480/189550535-5434ac9c-ade6-4591-b03e-6e083512413f.png)
> 
> Die VIP Funktion ist bei mir nicht aktiv.

Das ist ein guter Ansatzpunkt. Den werde ich mir angucken

**Comment by ChristianGK-GC** [comment]
@capoaira 
test mal bitte
[https://github.com/2Abendsegler/GClh/pull/2186/](https://github.com/2Abendsegler/GClh/pull/2186/)

**Comment by 2Abendsegler** [comment]
@capoaira @ChristianGK-GC
Ähh ... habt ihr jetzt beide das Gleiche entwickelt? 🤭 Was machen wir denn jetzt? 🙄
#2185 #2186

**Comment by capoaira** [comment]
> @capoaira @ChristianGK-GC Ähh ... habt ihr jetzt beide das Gleiche entwickelt? 🤭 Was machen wir denn jetzt? 🙄 #2185 #2186

Jip, sieht so aus 😅
Ich teste das von Christian mal und mache dann eine Version aus beiden. Bei #2186 fehlt in jeden Fall der Buffer, wenn ich das richtig sehe...

**Comment by ChristianGK-GC** [comment]
> Ja, so habe ich mir das vorgestellt. 👍🏻
> 
> > In der anderen Map werden mir die ganzen Informationen gar nicht angezeigt.
> 
> Da die Requests mehr oder weniger gleich aufgebaut sind, solltest du die Infos auf beiden Karten gleichermaßen bekommen.


Nachdem ich es erst mal für die alte Karte gemacht hab, wollte ich es auch noch in die neue Karte einbauen.

**Comment by 2Abendsegler** [comment]
@capoaira 
> Ich teste das von Christian mal und mache dann eine Version aus beiden.

Ok, check das kurz, ob dort etwas enthalten ist was bei deiner Version fehlt. Falls nicht, sollten wir jetzt einfach deine Version nehmen, die ich mir gestern auch schon kurz angesehen hatte.

**Comment by ChristianGK-GC** [comment]
Ich bin nur über den VIP Bug gestolpert und hätte dazu gleich nen issue aufmachen sollen

**Comment by capoaira** [comment]
> @capoaira
> 
> > Ich teste das von Christian mal und mache dann eine Version aus beiden.
> 
> Ok, check das kurz, ob dort etwas enthalten ist was bei deiner Version fehlt. Falls nicht, sollten wir jetzt einfach deine Version nehmen, die ich mir gestern auch schon kurz angesehen hatte.

Christians Version denkt an den config Parameter, den habe ich vergessen. Und seine match Funktion ist schöner 😅



> Ich bin nur über den VIP Bug gestolpert und hätte dazu gleich nen issue aufmachen sollen

Alles gut, als ich mir gestern den VIP Bug angeschaut habe, konnte ich mich nicht aufhalten weiter zu programmieren. Eigentlich hattest du das ja schon angefangen... Sorry

**Comment by ChristianGK-GC** [comment]
Kein Stress. Kein Problem.
Egal welche Version verwendet wird.

**Comment by capoaira** [comment]
Könnt ihr #2185 einmal testen?
Mir ist noch aufgefallen, dass auf der alten Karte beachtet werden muss, wenn mehrere Caches übereinander liegen.

@2Abendsegler Gibt es eine Möglichkeit einen Config Parameter 2 verschiedenen Sektionen zuzuordnen?

**Comment by 2Abendsegler** [comment]
> Gibt es eine Möglichkeit einen Config Parameter 2 verschiedenen Sektionen zuzuordnen?

Der Parameter settings_hide_upvotes wird beispielsweise in den Bereichen "Logs" und "Logs Header" verwendet. Für mehrere Versionen eines Parameters wird er ab der zweiten Version hinten mit X0 bis X9 erweitert. Damit bei einer Aktion wie beispielsweise einem Click bei allen Versionen eines Parameters die Aktion erfolgt, muss der eigentliche Parameter mit Function setEvForDouPara aufgerufen werden.
Suche mal nach settings_hide_upvotes, dann wirst du settings_hide_upvotes und settings_hide_upvotesX0 und den Aufruf der Function setEvForDouPara("settings_hide_upvotes", "click") finden.

**Comment by 2Abendsegler** [comment]
Ich habe mir den #2185 angesehen. Mir sind zwei Punkte aufgefallen.

---
1. In beiden Karten werden die Wochentage falsch ausgewiesen. Im Listing ist es korrekt. Hier ein Beispiel mit Listing und Browse Map mit unterschiedlichen Wochentagen für GC8MAC4.
![In karte falsch und anders als im Listing](https://user-images.githubusercontent.com/22332216/190232997-296b15a7-1404-4fac-b395-33630a4aaf57.JPG)

---
2. In der Browse Map wird die Zeile in Englisch zumindest bei Wednesday umgebrochen, das ist etwas unschön. 
![Zeilenumbruch1](https://user-images.githubusercontent.com/22332216/190233636-807770ba-1e74-483b-91ec-e7653b367b6d.JPG)
Wenn die Sprache auf Deutsch eingestellt ist, dann wird die Zeile bereits bei kleineren Wochentagen umgebrochen.  
![Zeilenumbruch2](https://user-images.githubusercontent.com/22332216/190233955-171574ef-1841-435a-8e0a-b255ff5eb165.JPG)
Könnten wir vielleicht die Abkürzungen für die Wochentage verwenden? Oder könnten wir nicht zumindest im Englischen etwas anpassen, damit die Zeilen mit langen Wochentagen (womöglich ist es nur Wednesday) nicht mehr umgebrochen werden?

**Comment by 2Abendsegler** [comment]
> Zu 2. Wie wäre es mit folgenden Abkürzungen: `let weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];`

👍

**Comment by 2Abendsegler** [comment]
> Zu. 1. Gut aufgepasst. Das habe ich wohl nicht ... Fix ist committet

Passt jetzt 👍

**Comment by 2Abendsegler** [comment]
Ich noch mal. Vielleicht sollten wir es im Listing nicht mit Abkürzungen machen. Irgend jemand wird sicherlich diese Reduzierung nicht gut finden. In beiden Karten sind Abkürzungen aber ok, oder auch nur in der Browse Map, mir egal.

Kommst du klar mit der Mehrfachnennung eines Config Parameters?

**Comment by capoaira** [comment]
> Kommst du klar mit der Mehrfachnennung eines Config Parameters?

Jip, deine Erklärung war sehr gut 👍🏻

Habe auch die Abkürzungen für die Browsemap hinzugefügt

**Comment by ChristianGK-GC** [comment]
> Zu. 1. Gut aufgepasst. Das habe ich wohl nicht ... Fix ist committet
> 
> Zu 2. Wie wäre es mit folgenden Abkürzungen: `let weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];`

Hallo ihr beiden.
Ich bin zZ auf Dienstreise, daher nur bedingt verfügbar.
Ich finde die kurze Version auch super.

**Comment by capoaira** [comment]
>Baust du das ein @capoaira ?

Jip, ist alles so weit eingebaut

**Comment by 2Abendsegler** [comment]
@capoaira @ChristianGK-GC 
Sieht super aus, vielen Dank an euch beide!

---
Merged with #2185
