### ISSUE TITLE
[Cache Listing / Search Map / Browse Map] getElevations(Geonames-Elevation): GM_xmlhttpRequest() reported error.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2107]
### Describe the bug

![grafik](https://user-images.githubusercontent.com/50927164/166098442-2326d3ab-984b-42bf-ac21-182f559b5e32.png)
Since a few days, we get no information from the geonames elevation service

### OS

Windows

### Browser

Firefox

### GClh Version

current collector

**Comment by 2Abendsegler** [comment]
Tritt der Fehler bei dir auf?
Meines Wissens geben wir auf der Console noch weitere Details zum Error aus. Hast du diese Information?

**Comment by 2Abendsegler** [comment]
Das ist dubios, bei mir läuft alles fehlerfrei und ich hab in den letzten Tagen wirklich viele Listings angesehen weil schon der nächste Urlaub ansteht. 

Hast du vielleicht Open-Elevation als Secondary Elevation benannt. Dann könnte die angezeigte von dort stammen. Wenn du mit der Maus drüberfährst, müsste angezeigt werden, von wo es stammt.   

---
Off-topic: 
Bevor ich nächste Woche in den Urlaub aufbreche, wollte ich noch eine Version fertig machen. Vielleicht am Freitag Abend. Alle was bis dahin fertig ist, werde ich noch versuchen vorher zu testen.

**Comment by 2Abendsegler** [comment]
... was mir gerade noch einfällt. Kannst du mal deine IP Adresse ändern, vielleicht ist die aus irgendwelchen Gründen bei geonames gesperrt.

**Comment by capoaira** [comment]
>Hast du vielleicht Open-Elevation als Secondary Elevation benannt. Dann könnte die angezeigte von dort stammen. Wenn du mit der Maus drüberfährst, müsste angezeigt werden, von wo es stammt.

Jip, stammt von Open-Elevation, das mit dem Hover wusste ich noch nicht

>... was mir gerade noch einfällt. Kannst du mal deine IP Adresse ändern, vielleicht ist die aus irgendwelchen Gründen bei geonames gesperrt.

Wie kann ich meine IP-Adresse ändern? (eigentlich müsste meine dynamisch sein und sich somit immer wieder ändern)

>Off-topic:
>Bevor ich nächste Woche in den Urlaub aufbreche, wollte ich noch eine Version fertig machen. Vielleicht am Freitag Abend. Alle was bis dahin fertig ist, werde ich noch versuchen vorher zu testen

Das ist ja fast schon Urlaubsstress 😅 Ich wünsche dir viel Spaß und Erholung :)

Eine neue Version wäre gut.

In die nächste Version sollten auf jeden Fall noch
- https://github.com/2Abendsegler/GClh/issues/2089#issuecomment-1084547211
- #2114 
- evt #2117 
Ob ich die Filtersets rechtzeitig fertig kriege, weiß ich nicht. Und zum Testen ist das ja auch großer Aufwand

**Comment by 2Abendsegler** [comment]
... ach ja. Die Kleinigkeiten beim #2108 könntest du vielleicht auch noch versuchen fertig zu machen. 😬

**Comment by 2Abendsegler** [comment]
Auch [hier](https://www.geoclub.de/forum/t/gc-little-helper-ii-v0-11.81650/post-1336082) gibt es dieses Problem.

**Comment by 2Abendsegler** [comment]
Ich arbeite seit einigen Tagen von einem anderen Ort und erhalte nun auch regelmäßig, aber nicht immer einen Fehler. Wenn ich nach dem Fehler sofort über den Browser aktualisiere, gab es bisher noch nie einen weiteren Fehler.

![grafik](https://user-images.githubusercontent.com/22332216/173668603-c5b1f8a0-adc1-4b2e-aef0-eeaefe2a32b2.png)

**Comment by capoaira** [comment]
Kann es sein, dass gm_xmlhttp Requests nicht in der console unter xhr nicht angezeigt werden? Ich wollte mir mal nur die Details zur Request ansehen, die werden jedoch gar nicht angezeigt.

Nutzen wir die Möglichkeit, mehrere Locations gleichzeitig abzufragen, irgendwo? Ich mit dem Thema nicht ganz so vertraut, auf die Höhendaten achte ich eigentlich nie wirklich.

**Comment by capoaira** [comment]
>Nutzen wir die Möglichkeit, mehrere Locations gleichzeitig abzufragen, irgendwo? Ich mit dem Thema nicht ganz so vertraut, auf die Höhendaten achte ich eigentlich nie wirklich.

nvm, bei den WPs nutzen wir das in jedem Fall... ich war wohl blind

**Comment by capoaira** [comment]
Ich wollte mal versuchen, die Daten über eine `fetch()` Methode zu bekommen, leider werden die Anfragen blockiert, da wir von https nach http einen Request senden. Ich weiß, es gab einen Grund, dass wir `secure.geonames.org` nicht (mehr) nutzen, aber ich weiß nicht mehr welchen... erinnerst du dich?
#1770 beschreibt das Problem. 
Ich hatte "Nur-HTTPS-Modus in allen Fenstern aktivieren" eine Zeit lang aktiviert, als dann der Fehler auftrat. Irgendwann hatte ich es deaktiviert, weil ich bei einem Projekt mit einem Kumpel dasselbe Problem hatte. Vermutlich hat sich das Ganze deshalb bei mir "von alleine" gelöst.

Allerdings passt diese Beobachtung nicht zu deiner. An sich sollte der Bug immer, oder nie auftreten...

Welchen Browser nutzt du? Ich habe es immer mit Firefox versucht.

**Comment by 2Abendsegler** [comment]
> Kann es sein, dass gm_xmlhttp Requests nicht in der console unter xhr nicht angezeigt werden?

Ja, ich glaube das ist so.

> Ich weiß, es gab einen Grund, dass wir `secure.geonames.org` nicht (mehr) nutzen, aber ich weiß nicht mehr welchen... erinnerst du dich?

Die kostenlose https Seite ist auf 1000 Zugriffe pro Stunde limitiert.
#1876
{"status":{"message":"the hourly limit of 1000 credits for gclh has been exceeded. Please throttle your requests or use the commercial service.","value":19}}

> Ich hatte "Nur-HTTPS-Modus in allen Fenstern aktivieren" eine Zeit lang aktiviert, als dann der Fehler auftrat. Irgendwann hatte ich es deaktiviert, weil ich bei einem Projekt mit einem Kumpel dasselbe Problem hatte. Vermutlich hat sich das Ganze deshalb bei mir "von alleine" gelöst.
> 
> Allerdings passt diese Beobachtung nicht zu deiner. An sich sollte der Bug immer, oder nie auftreten...
> 
> Welchen Browser nutzt du? Ich habe es immer mit Firefox versucht.

Ich habe `Nur-HTTPS-Modus nicht aktivieren`, daran kann es bei mir also nicht liegen. Ich nutze den aktuellen Firefox.

---
Ich habe gerade nochmal ein paar Tests gemacht.
- 7 Listings aufgerufen, davon sind bei dreien die entsprechende Fehlermeldung aufgetaucht. Dann habe ich alle Listings einzeln über den Browser aktualisiert, alles ohne Fehlermeldung.
- Noch mal 5 Listings aufgerufen, ein Fehler, Aktualisierung ohne Fehler.
- Ich habe nochmal 20 Listings gleichzeitig aufgerufen. Ohne Fehler. 
- Gerade kann ich keine Fehler mehr produzieren.

Vielleicht sollten wir uns einfach mal bei den Verantwortlichen für geonames melden. Womöglich freut man sich ja sogar über unsere Meldung, schließlich endet der Request ja auch nicht mit einem echten Fehler, es wird ja gar kein Fehlertext übergeben, so wie beispielsweise an anderer Stelle.

**Comment by capoaira** [comment]
Ok, das mit dem Limit ist schonmal echt blöde.

> Vielleicht sollten wir uns einfach mal bei den Verantwortlichen für geonames melden. Womöglich freut man sich ja sogar über unsere Meldung, schließlich endet der Request ja auch nicht mit einem echten Fehler, es wird ja gar kein Fehlertext übergeben, so wie beispielsweise an anderer Stelle.

Ja, gute Idee, wobei es gut wäre, wenn wir uns vorher selbst ein Bild davon machen können, denn das Verhalten spricht eher für einen Fehler auf client Seite.
Mal sehen, ob uns https://stackoverflow.com/questions/72630163/where-i-can-find-gm-xmlhttprequest-xhr-console-logs weiter bringt...

**Comment by capoaira** [comment]
Ich kann das Problem nicht mehr nachstellen, und Papa Delta scheint nicht wirklich an einer Mithilfe beim Lösen des Problems interessiert zu sein...
aber:

>Mal sehen, ob uns https://stackoverflow.com/questions/72630163/where-i-can-find-gm-xmlhttprequest-xhr-console-logs weiter bringt...

Hier gab es nun eine Antwort, dort sollten wir, wenn der Fehler erneut auftritt, die Logs sehen können. So können wir dann hoffentlich feststellen, woran es liegt.

**Comment by 2Abendsegler** [comment]
> Papa Delta scheint nicht wirklich an einer Mithilfe beim Lösen des Problems interessiert zu sein

Das und andere Dinge sind der Grund, warum ich auf Anfragen von ihm nicht mehr reagiere.

Die Antwort zu xhr werde ich mir noch ansehen, damit ich weiß was ich tun kann, wenn bei mir der Fehler wieder auftaucht. Seit dem ich wieder zu Hause bin ist der Fehler aber nicht mehr aufgetreten.

**Comment by 2Abendsegler** [comment]
Ich hatte am frühen Abend wieder einen Error. In der "Extension Toolbox" kann man die xhr Logs sehen, aber natürlich nur ab dem Zeitpunkt, ab dem die Toolbox aktiviert ist. Einen weiteren Error gabs bisher aber nicht. 

Meine Vorgehensweise:

1. Einschalten der "Extension Toolbox" (Details siehe [hier](https://extensionworkshop.com/documentation/develop/debugging/#developer-tools-toolbox)):
- Open new Tab.
- enter about:debugging in the URL bar.
- in the left-hand menu, click This Firefox.
- click Inspect next to the extension Tampermonkey. Neues Popup wird geöffnet. 

2. Im neuen Popup dann gegebenenfalls noch den Reiter xhr aktivieren. 

3. Dann nochmal versuchen den Fehler zu wiederholen.

**Comment by 2Abendsegler** [comment]
@capoaira 
Alle paar Monate bekomme ich einen solchen Fehler, er hat sich aber nie wiederholen lassen so dass keine Auswertungen möglich sind. Ich möchte die Fehlermeldungen von geonames grundsätzlich so umstellen, dass keine Meldung mehr im Header der Webseite angezeigt wird. Anstatt dessen wird nur noch ein Fehler in der Konsole ausgegeben mit allen Details. Die Elevation Anzeige beispielsweise im Listing erfolgt dann mit `???` und im title mit `Fail to load elevation data`, so wie das auch bisher schon bei allen anderen Fehler aus dem Bereich Elevation gemacht wird. Das Issue möchte ich anschließend schließen weil wir ja hier nicht weiterkommen. 

Bist du damit einverstanden oder hast du andere Vorschläge?

**Comment by capoaira** [comment]
Ja, das hört sich sinnvoll an 👍🏻
