### ISSUE TITLE
[Header] Horizontal Linklist with more than one line does not work.

### ISSUE THREAD

**Issue by TiBaWe** [2Abendsegler/GClh#2110]
### Describe the bug

Die Horizontale Linkliste im Header wird in nur einer Zeile angezeigt, ganz egal, ob in den Einstellungen 1, 2, oder 3 Zeilen dafür eingestellt ist.

![Bild_2022-04-30_184848335](https://user-images.githubusercontent.com/104689878/166114776-f1ef9bf3-bc81-48f0-8651-010b8c56761f.png)

### To Reproduce

1. Config aufrufen
2. "Change header layout" und "Show Linklist on top" aktivieren
3. "Show Linklist in horizontal direction" aktivern
4. "Number of lines for all links" zu 2 oder 3 ändern
5. Die Linklist mit einigen Links füllen/ Größe ändern/ Abstand ändern
6. Config speichern

### Expected behavior

Die Linklist im Header sollte auf 2, bzw. 3 Zeilen verteilt werden (je nach Einstellung)

### OS

Windows

### Browser

Opera

### GClh Version

0.11.15

**Comment by capoaira** [comment]
Danke für das Melden des Bugs und die ausführliche Beschreibung. So konnte ich den Bug sehr schnell reproduzieren. Klasse!

Mit diesen Optionen kann man auch nichts mehr aus dem Dropdown auswählen, da es verschwindet, sobald man den Button verlässt.

@2Abendsegler hier werde ich mich nicht ran setzten, da ich mich in dem Teil des Scripts so gar nicht auskenne 😅 und es viele Abhängigkeiten gibt, die ich nicht kenne. Du kannst dich nun auf eine schöne Aufgabe nach deinem Urlaub freuen 😉😝

**Comment by TiBaWe** [comment]
Auch mit der Vorabkorrektur wird mir die Linkliste nach wie vor nur in einer Zeile angezeigt, Egal, ob 1, 2 oder 3 Zeilen in den Einstellungen gewählt ist.

Was mir eben auch noch aufgefallen ist:
Ich habe die neue Version einfach "als Update" installiert, als ohne die Vorversion vorher zu löschen. Nachdem ich die Einstellungen geändert und abgespeichert hatte, hat sich das ganze Script aus Tampermonkey gelöscht/ in den Papierkorb verschoben.
Erst nach endgültigem Löschen und Neuinstallation hat die Vorabkorrektur sich nicht mehr selbst gelöscht.

Aber das ursprüngliche Problem mit der Zeilenanzahl ist immer noch nicht behoben.

**Comment by 2Abendsegler** [comment]
Hallo,

du hast recht, es funktionierte noch nicht für alle Geocaching Seiten. Bei den neueren Seiten aus den letzten Jahren war dieses Feature überhaupt nicht vorgesehen. Das bedeutet, dass dieses Feature überhaupt nicht mehr genutzt wurde.

Nunja, es sollte nun für alle Geocaching Seiten funktionieren.
[Hier](https://github.com/2Abendsegler/GClh/blob/8606b9963b39e3370b71b79547c0e8eca7a57261/gc_little_helper_II.user.js?raw=true) gibt es eine Vorabkorrektur. Kannst du bitte noch mal testen?
[Hier](https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true) kommst du wieder zurück zur aktuellen Version.

---

> Ich habe die neue Version einfach "als Update" installiert, als ohne die Vorversion vorher zu löschen. Nachdem ich die Einstellungen geändert und abgespeichert hatte, hat sich das ganze Script aus Tampermonkey gelöscht/ in den Papierkorb verschoben.
> Erst nach endgültigem Löschen und Neuinstallation hat die Vorabkorrektur sich nicht mehr selbst gelöscht.

Ich habe mir auch mal wieder Opera aufgespielt und den Link für die Vorabversion angewählt. Bei mir funktioniert das Updaten ohne Probleme. Nach dem Update solltest du alle Tabs des Browsers und den Browser schließen und neu starten.

Opera gehört nicht zu den verbreiteten Browsern, deshalb kann es durchaus sein, dass Interaktionen zwischen Opera und dem Scriptmanager Tampermonkey nicht so gut getestet sind wie bei den Browsern Firefox oder Chrome. Bei dem beschriebenen Problem handelt es sich vermutlich um ein Problem zwischen Tampermonkey und Opera.

Wenn das Problem weiterhin besteht, solltest du überlegen, ob du nicht besser auf einen verbreiteteren Browser umsteigst. 

LG

**Comment by TiBaWe** [comment]
Servus,
mit der neuen Version funktioniert der Header jetzt richtig. Diesmal hat auch die Instllation problemlos funktioniert.

Was mir noch aufgefallen ist, was aber auch nicht weiter schlimm ist:
Im einzeiligen Modus werden die Links, die nicht in den Header passen nach rechts weitergeschoben.
![image](https://user-images.githubusercontent.com/104689878/166458277-c979417e-490a-432f-9fc6-cd1682a61b17.png)

Im zweizeiligen Modus hingegen wandern die überschüssigen Links in eine 3. Zeile.
![image](https://user-images.githubusercontent.com/104689878/166457835-b7f3a9f3-ccab-4bad-bb9d-ccb8b4e9bf14.png)

Ich weiß nicht, ob das so vorgesehen ist, weiter schlimm ist es jedenfalls nicht.

LG
Tilman

**Comment by 2Abendsegler** [comment]
Schön dass es jetzt klappt.

Das Weiterschieben bzw. in eine neue Zeile umbrechen ist quasi so beabsichtigt. Damit kann man sehen dass der Platz nicht mehr ausreicht und man die Namen der Links kürzen muss bzw. noch eine Zeile dazunehmen muss.

**Comment by 2Abendsegler** [comment]
Merged with #2116
