### ISSUE TITLE
[Header / Suchmaske] Suchmaske teilweise zu schmal

### ISSUE THREAD

**Issue by TiBaWe** [2Abendsegler/GClh#2111]
### Describe the bug

Beim Vergrößern des Link-Abstandes schrumpft ab einem gewissen, scheinbar willkürlichen, Punkt die Breite der Suchmaske.

![Bild_2022-04-30_185913010](https://user-images.githubusercontent.com/104689878/166115110-a503d971-d138-4bb2-9204-8ae3aa62939e.png)

![Bild_2022-04-30_185823367](https://user-images.githubusercontent.com/104689878/166115084-3d007a99-d68f-45e1-8677-4f5c6b751d42.png)

![Bild_2022-04-30_185729833](https://user-images.githubusercontent.com/104689878/166115052-ff2881ff-8f7a-41b7-8bf5-46b2550987b2.png)

### To Reproduce

1. Config aufrufen
2. "Change header layout" und "Show Linklist on top" aktivieren
3. "Show Linklist in horizontal direction" aktivern
4. "Show searchfield" aktivieren
5. "Distance between the links" vergrößern
6. Config speichern

### Expected behavior

Die Suchmaske sollte ihre Breite behalten, bzw. erst beim erreichen der Logos auf der rechten Seite schmaler werden.

![Bild_2022-04-30_185552276](https://user-images.githubusercontent.com/104689878/166115001-938c8758-025a-4e6c-9819-c81d37e082f0.png)

### OS

Windows

### Browser

Opera

### GClh Version

0.11.15

### Additional context

Eventuell könnte man der Suchmaske auch eine Einstellung verpassen, mit der man die Breite manuell festlegen kann.

**Comment by capoaira** [comment]
I think when #2110 is fixed, this will be also fixed

**Comment by 2Abendsegler** [comment]
Ich glaube der Effekt hängt damit zusammen, dass du einen ziemlich großen Bildschirm hast und der Parameter "Page width" nicht ausreichend groß ist. Dadurch steht im Menübereich weniger Platz zur Verfügung als es aussieht. Wenn zu wenig Platz zur Verfügung steht, wird die Breite des Eingabefeldes automatisch reduziert. 

Versuche mal den Parameter "[Page width](https://www.geocaching.com/my/#GClhShowConfig#a#settings_new_width)" zu erhöhen.

**Comment by TiBaWe** [comment]
Dankeschön, das hat es tatsächlich behoben :)
