### ISSUE TITLE
[Drafts] Edit and re-save drafts

### ISSUE THREAD

**Issue by TiBaWe** [2Abendsegler/GClh#2113]
### Is your feature request related to a problem? Please describe

Manchmal schreibe ich meine Logs am PC, kann diese aber - aus welchem Grund auch immer - nicht fertig stellen, weil zeitlich etwas dazwischen kommt. Um diese dann später weiterschreiben zu können müsste ich mir den Logtext in ein Textdokument copy-pasten und lokal abspeichern. 

### Describe the solution you'd like

Ich würde im auf der Log-Seite einen Button wünschen, um den Log als Entwurf/ Field Note abzuspeichern, ähnlich wie es schon lange in der Geocaching App oder in Alternativen wie c:geo funktioniert.

Auch bereits bestehende, aus den Apps hochgeladene Entwürfen würde ich gerne nach Bearbeitung am PC erneut abspeichern können, also wieder als Entwurf, nicht als gesendeten Log.

### Additional context

Da die Field Note Funktion ja bereits vorhanden ist und auch das hochladen von Field Notes aus Third Party Apps funktioniert (siehe c:geo)
![download](https://user-images.githubusercontent.com/104689878/166116909-3699d9cf-f078-421e-a7d8-76e31fd0be11.png)
stelle ich mir - als Laie - eine Implementierung dieses Vorschlags als relativ einfach vor. Im Grunde genommen sollte das ja nichts anderes sein, als den zu speichernden Log herunterzuladen, auf geocaching.com zu löschen und als Field Note wieder hochzuladen (vgl. c:geo).

**Comment by capoaira** [comment]
Duplicate of #1473

Moin,
den Wunsch habe ich schön häufiger gehört und wünsche mir das auch manchmal. 
Technisch ist das aber für uns sehr schwer umsetzbar. c:geo hat als Android App andere Möglichkeiten als wir und auch die können keine Drafts von geocaching.com ändern.

Für diese Funktion sind folgende Schritte notwendig:
1. Abspeichern des Logtextes
2. Eine Textdatei im richtigen Format erstellen, ohne sie auf dem Rechner des Users zu speichern
3. Drafts löschen
4. Besagte Textdatei hochladen

Dabei tauchen einige Probleme auf. Zum Beispiel das Erstellen der Datei, aber auch das Hochladen oder Löschen ist aufgrund des asynchronen Aufbaus der Geocaching-Seite sehr aufwändig. Sicherlich kann man sich etwas aus dem Quellcode von c:geo bedienen, aber deren Quellcode ist sehr mächtig und somit schwer zu durchsuchen, wenn man mit diesem nicht vertraut ist.
Zudem ist JavaScript (was wir nutzen müssen) beschränkter als Java (was c:geo nutzt)

Um sich diesem Issue zu widmen brauchen wir viel Zeit und momentan hat die keiner von den Entwicklern hier.

Ich schließe das Issue, da wir bereits eines dazu haben
