### ISSUE TITLE
[Config] Color Picker popup behind config

### ISSUE THREAD

**Issue by TiBaWe** [2Abendsegler/GClh#2114]
### Describe the bug

Das Color Selecion Popup Tool liegt hinter dem Einstellungsfenster, sodass man es nur teilweise benutzen kann.

![image](https://user-images.githubusercontent.com/104689878/166172744-4b49b9b3-bb34-423f-a502-4f65774711da.png)

Vergrößert man den Seitenzoom, während der Color Picker offen ist, verschiebt dieser sich nach rechts.

![image](https://user-images.githubusercontent.com/104689878/166172891-d8293a0b-9775-444e-841c-6bf7b560b458.png)

### To Reproduce

1. Einstellungen öffnen
2. Color Hex Code anklicken (z.B. in Global/List Layout)
--> Popup unter Einstellungsfenster

3. Bei geöffnetem Popup Seitenzoom vergrößern
--> Popup wandert nach rechts, sodass man es benutzen kann

4. Popup schließen und wieder öffnen
--> wieder unter Einstellungsfenster

### Expected behavior

Popup öffnet sich über dem Einstellungsfenster, sodass man es benutzen kann.

### OS

Windows

### Browser

Opera

### GClh Version

0.11.15

**Comment by capoaira** [comment]
Danke für das Melden des Bugs.
Ich kann ihn auch in Firefox nachstellen.

Der fix kommt in der nächsten Version

**Comment by 2Abendsegler** [comment]
Merged with #2118
