### ISSUE TITLE
[Drafts] "Automatic go back to Drafts after sending to log" doesn't work from old logging page

### ISSUE THREAD

**Issue by TiBaWe** [2Abendsegler/GClh#2117]
### Describe the bug

Ich lande nach dem Absenden des Entwurfs auf der normalen Seite, auf der man den eben verfassten Log erneut sieht, unabhängig davon ob die Funktion "Automatic go back to Drafts after sending to log" aktiviert ist oder nicht.

### To Reproduce

1. "Automatic go back to Drafts after sending to log" aktivieren
2. Irgendeinen Draft (bearbeiten)/ absenden

### Expected behavior

Automatische Weiterleitung auf die Draft-Übersichtsseite

### OS

Windows

### Browser

Opera

### GClh Version

0.11.15

**Comment by capoaira** [comment]
I can reproduce the bug if I use the old logging page for the Drafts.

I'll take a look in it.

**Comment by capoaira** [comment]
Warum schreibe ich eigentlich Englisch? Naja...

Die alte Logseite wird vom Coding gar nicht beachtet.

Note für mich:
Link nach dem Loggen: https://www.geocaching.com/seek/log.aspx?PLogGuid=

**Comment by 2Abendsegler** [comment]
Hm ..., wir wollten mit diesem Feature verhindern, dass man nach dem Loggen von Drafts im Listing stehen bleibt. Das passiert, wenn man über das neue Log Formular geht. Dieses Feature wurde im Geocaching Forum immer wieder verlangt.  Geht man über das alte Log Formular sieht man nach dem Loggen das Log, so wie man es gesendet hat. Hier handelt es sich also nicht um einen Bug. Letzteres anzupassen hatten wir nie beabsichtigt.

Man kann ein solches Feature vielleicht trotzdem noch einbauen. Ich bezweifle aber, dass es viel verwendet wird. So lange es die alte Log Prozedur gab, wurde es ja auch nie angefordert, und es macht ja auch Sinn, dass man das Log nochmal sieht. Man störte sich zuletzt nur daran, dass man im Listing landete.

Falls wir das Feature nicht umsetzen, sollten wir etwas im Config dazu erwähnen.

**Comment by 2Abendsegler** [comment]
> Den Log noch einmal nach dem Loggen zu sehen, fände ich beim neuen Loggen eigentlich auch gut.

Ja, würde ich auch sinnvoll finden.

**Comment by capoaira** [comment]
Da es keine weitere Antwort gab würde ich vorschlagen, dass wir eine Bemerkung im config schreiben, damit es nicht zu weiteren Irritationen kommt und dann das Issue Schließen.

**Comment by 2Abendsegler** [comment]
Merged with #2139

Bezeichnung des Parameters ergänzt.
Old: `Automatic go back to Drafts after sending to log`
New: `Automatic go back to Drafts after sending to log with new log form`
