### ISSUE TITLE
Track Overlay in Map

### ISSUE THREAD

**Issue by Herr-Ma** [2Abendsegler/GClh#2125]
### Is your feature request related to a problem? Please describe

II often go by bike and make tracks for myself. Now it would be nice if I could only load the caches onto the device that are really related to the track. A tour over 1000km is coming up soon. I don't want to create PQs over huge areas, but only have what's really interesting with me.

### Describe the solution you'd like

If you could load a GPX track as an overlay in the BrowseMap, you could easily collect the corresponding caches together with gctour.

**Comment by capoaira** [comment]
Hm, that sounds not easy to implement.
I haven't the time for that, and I'm thinking 2Abensegler also not.

It also sounds like much work to add all caches from an 1000 km tour to one List.

I always used the https://www.geocaching.com/my/userroutes.aspx page to upload parts of my tours and create a PQs from the route. There you can select a radius for the tour, and you'll get up to 2000 Caches per route (1000 per side). I think that much faster than adding Caches on a track manually to GCT.

**Comment by Herr-Ma** [comment]
The Groundspeak tool for creating a PQ along a route is rubbish in my opinion. It happens again and again that caches are simply not present in the PQ, even though they are within the radius.

With the UserScript GeocachingMapEnhancement it is possible to create a track online on the map. In theory it shouldn't make a difference whether this track is now created online point by point or if the points are all loaded from one file. But of course I could be wrong ;-)

**Comment by Herr-Ma** [comment]
Ok, you can close this issue ;-)  I took a closer look at the source code of the GeocachingMapEnhancement user script and found that this script does exactly what I want. If the script is activated, then you can drag'n drop a track onto the map.

Sorry for the circumstances and the request 😇.
![grafik](https://user-images.githubusercontent.com/23725271/168999093-e54c7cc2-1738-4da1-9454-b3a424c60afe.png)
