### ISSUE TITLE
[Browse Map] Empty header due to a bug on the website.

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#2134]
### Describe the bug

In der Kopfzeile der Karte (https://www.geocaching.com/map/#?ll=51.57013,7.46062&z=14) werden keine Shortcuts mehr angezeigt. Die Kopfzeile ist leer.
![image](https://user-images.githubusercontent.com/7745027/172546292-2bff428b-a781-44d4-a8d4-940b915a48b6.png)

Aus der Suchseite (https://www.geocaching.com/play/search) werden die Shortcuts hingegeben weiterhin angezeigt.
![image](https://user-images.githubusercontent.com/7745027/172546072-4b03425f-4f7c-426a-b47a-aa524578f1d7.png)

### OS

Windows

### Browser

Firefox, Chrome

### GClh Version

v0.11.16

**Comment by capoaira** [comment]
Danke für das Melden den Bugs. 
Der steht wohl im Zusammenhang mit https://forums.geocaching.com/GC/index.php?/topic/378861-weird-mapmenu-bar-behaviour/

Wir werden uns der Sache annehmen, sobald wir Zeit dazu finden.

**Comment by 2Abendsegler** [comment]
Ich vermute mal, dass der Header auch mit dem GClh wieder angezeigt wird, sobald es auf der Webseite wieder funktioniert. Und Groundspeak hat sich ja auch bereits dazu kommittet etwas tun zu müssen.

**Comment by Donnerknispel** [comment]
Wie konnte ich nur annehmen, dass es ein Bug des GClh ist ;-)

**Comment by cghove** [comment]
@[2Abendsegler](https://github.com/2Abendsegler) Adding :
```
if (is_page("map"))   {
         console.log("hijack menu");
    $("#gc-header-root").remove();
    $( "body" ).prepend('<div id="gc-header-root" style="background-color: #02874D; min-height: 80px;"><header id="gc-header" class="css-az98zw">');
}
```
To line 81 will fix the groundspeak bug, while using GCLH2

**Comment by Donnerknispel** [comment]
Inserting the few lines worx right away.

**Comment by cghove** [comment]
Yeah... if only I could get it to work on my own script... 😂

**Comment by 2Abendsegler** [comment]
Unfortunately, Groundspeak just doesn't get going.

The idea seems good. I'll look at it a little later. We will probably put it in a different place and change something so that it only runs when the header is not yet built.

@cghove Thanks
@Donnerknispel Thanks for testing

**Comment by 2Abendsegler** [comment]
Merged with #2153
Comes with the next version in some minutes.

**Comment by capoaira** [comment]
The Bug is finally fixed by GS https://forums.geocaching.com/GC/index.php?/topic/378861-weird-mapmenu-bar-behaviour/#comment-6021114

Vielleicht hat unser Update GS unter Druck gesetzt, auch mal eine Lösung zu finden 😅

**Comment by 2Abendsegler** [comment]
Ja genau. 😂
