### ISSUE TITLE
[The Great Jerky Hunt by Jack Link's] Integration of the page.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2146]
### Describe the bug

Die neue Seite https://www.geocaching.com/live/promos/jacklinks wird im GClh nicht verarbeitet, weil die Userdaten nicht gefunden werden. Die Userdaten sind mal wieder auf eine neue Art auf der Seite hinterlegt.

### To Reproduce

1. Go to [Dashboard](https://www.geocaching.com/account/dashboard)
2. Click to "The Great Jerky Hunt by Jack Link's"

oder
1. Go direct to [The Great Jerky Hunt by Jack Link's](https://www.geocaching.com/live/promos/jacklinks)

### OS

Windows

### Browser

Firefox

### GClh Version

actual collector

**Comment by capoaira** [comment]
Merged with #2147
