### ISSUE TITLE
[Draft] Drafts loading is slow.

### ISSUE THREAD

**Issue by gpsschneider** [2Abendsegler/GClh#2173]
### Describe the bug

Hi,
I'm using 
- Google Chrome Version 104.0.5112.81 (Offizieller Build) (64-Bit)
- Tampermonkey 4.16.1
- GC little helper II | 0.11.19

On https://www.geocaching.com/account/drafts# (14 drafts) the script slows down the page loading up to about 10 seconds. With more drafts the loading time increases. 

Disabling GCLH II or excluding drafts page fixes the issue.

Thanks for your help
Thomas

### To Reproduce

Reload drafts

### Expected behavior

Tried to reload the Drafts with / without GCLH II. If enabled, page loading is very slow.

### OS

Windows

### Browser

Chrome

### GClh Version

0.11.19

### Additional context

![image](https://user-images.githubusercontent.com/111235822/184542180-bab7ec08-55d4-4828-bd58-20297357873a.png)

**Comment by 2Abendsegler** [comment]
Hi,

I can't reproduce the problem at the moment.

I'm on vacation and have only limited internet access. I don't have any drafts right now either. But some should come in the next few days, then I'll take a closer look at it again.

Can you please call up the settings for the GClh in the Draft area and attach a screenshot of your settings here? The following link will take you to the right place:
https://www.geocaching.com/my/#GClhShowConfig#a#gclh_config_draft

Can you please select the following cache listings and see how long it takes for the VIPs to load in the VIP list? The VIP list is located in the listing on the right below the navigation area and the map. The first listing should go very quickly. The second listing can take a while because there are many logs here. But it should be there in 2 to 3 seconds. Can you please tell me the times for the loadings?
https://coord.info/GC9GTT7
https://coord.info/GC3PZF2

We have another issue with similar problems (#2172).

Frank

**Comment by gpsschneider** [comment]
Hi,
here the requested config
![image](https://user-images.githubusercontent.com/111235822/184545555-e80d0515-079d-401a-aeb1-62f7c20197cc.png)

First listing takes about 3-4 seconds to load
Second listing takes about 8 seconds.

If I can do anything more, just tell me.

Regards 
Tom

**Comment by 2Abendsegler** [comment]
Hallo Tom,

danke für die Tests.

Die Ladezeiten sind etwas hoch. Könnte aber auch an deiner Internet Verbindung oder an der Erreichbarkeit von geocaching.com liegen. 

Ich habe mal mit deinen Einstellungen mit einem einzigen Draft getestet, das scheint bei mir ok. Ich werde mir in den nächsten Tagen, sobald sich die Möglichkeit bietet, die Drafts Seite näher ansehen.

Wenn dir noch etwas Ungewöhnliches auffällt, auch auf anderen geocaching Seiten, dann lass uns das bitte wissen.

LG
Frank

---
@capoaira
Moin, hast du vielleicht Zeit dir das mal anzusehen?

**Comment by capoaira** [comment]
Moin,
ich bin gerade auch im Urlaub, und habe deswegen nur kurz getestet. Meine 8 Drafts laden normal schnell und auch die VIP-List lädt nicht länger als üblich, wobei ich beim 2. ein kurzes Stoppen beobachten kann (lodingspinner bleib kurz stehen) bevor die Liste sichtbar wird.
@gpsschneider nutzt du eventuell noch andere Skripte oder AddOns (z.B. Ad-Blocker wie UBlock)? Wir hatten schon Probleme, bei denen 2 Scripte sich gegenseitig behindert haben. Stellt man eines der beiden aus, funktioniert das jeweils andere wieder.
Die üblichen verdächtigen geocaching scripte (GCTour, PGC, send2cgeo, mystery wizard, Geocaching Map Enhancements (2AS), GC Ad-Blocker) habe ich bei mir getestet. Mit denen scheinen wir kein Problem zu haben.

**Comment by gpsschneider** [comment]
Hi,
ich hab mal alle Erweiterungen deaktiviert. Hat keinen Einfluss. 
Im Tampermonkey habe ich nur GCLH - sobald das aus ist, ist die Seite schnell.
VG
Tom

**Comment by capoaira** [comment]
Schade, dann gehen auch mir die Ideen aus :(

**Comment by gpsschneider** [comment]
Ich versuch heute mal noch ein bisschen zu forschen. Mal sehen, ob ich was finde. 
Anbei mal ein gif, das das Verhalten zeigt
![gclh](https://user-images.githubusercontent.com/111235822/184589325-6a74497a-4de9-42ba-af50-6dba08498ee9.gif)
.

**Comment by 2Abendsegler** [comment]
Das Laden hängt ja richtig, und das auch ganz ohne Drafts. 
Ich habe jetzt auch noch einmal mit einigen Drafts getestet, kann die Probleme aber immer noch nicht nachvollziehen.

Bei deinem gif fallen mir einige Dinge auf:
1. Dein Geocaching Name und der Zähler deiner Funde fehlen im Header. Wie kommt es dazu?
2. Das Add On CacheVote läuft noch. Hast du dieses Add On auch mal abgeschaltet und dann nur mit dem GClh getestet?
3. Es sieht so aus, als ob rechts auf der Seite keine Werbung eingeblendet wird. Hast du noch einen Werbeblocker laufen?

Kannst du bitte noch in die Konsole schauen, ob dort noch andere Meldungen ausgewiesen werden.

**Comment by gpsschneider** [comment]
Moin,
das ist nur ein Ausschnitt, damit das Ding nicht zu groß wird. 
Die AddOns hatte ich vorher schon mal komplett aus, da hat sich das Verhalten nicht geändert. Auch den Werbeblocker hatte ich schon mal ausgemacht, auch keine Änderung. 
Als Idee: Verwendet ihr den Nutzernamen im Script? Es gab bei einem anderen Tool schon mal Probleme mit unserem Namen, da wir ein "&" im Namen haben - ist heute nicht mehr zugelassen bei GC, damals war es das noch und wir genießen Bestandsschutz...

**Comment by capoaira** [comment]
Eigentlich sollte der Nutzername keinen Unterschied machen, aber wir werden uns das angucken, denn das ist auf jeden Fall ein Unterschied der immer mal wieder zu Problemen geführt hat.
Ich weiß nur gerade nicht, wie wir das testen könnten...

**Comment by gpsschneider** [comment]
Vielleicht hilft das? Hab heute mal versucht rauszufinden, wo die Zeit hingeht. uBlock ist aus.
![image](https://user-images.githubusercontent.com/111235822/184851080-7af7269e-4800-4f6a-95be-ecb68c61107b.png)

**Comment by capoaira** [comment]
Ich habe das Script mal so umgeschrieben, dass der Nutzername durch einen einfachen String ersetzt wird. Kannst du das einmal ausprobieren, um einen solchen Fehler auszuschießen?
https://github.com/capoaira/GClh/blob/slow-darfts/gc_little_helper_II.user.js?raw=true
Danach kannst du hier wieder zu aktuellen GClh:
https://github.com/2Abendsegler/GClh/blob/master/gc_little_helper_II.user.js?raw=true

**Comment by gpsschneider** [comment]
Hilft leider nicht. Hab auch alle anderen AddOns für den Test nochmal ausgemacht. 
Geht hier nen private Chat?

**Comment by capoaira** [comment]
Ok, schade.

> Achtung, eins kann ich nicht ausmachen "Microsoft S/MIME 20.21.531.1" (company policy)

Kannst du mal gucken, ob du das in Firefox oder einem anderen Browser ausschalten kannst?

Erreichen kannst du uns immer über unser GC Profil oder per Mail (hast du ja schon gefunden :))

**Comment by 2Abendsegler** [comment]
Hallo Thomas,

kannst du bitte mal die folgenden älteren Versionen aufspielen, um zu prüfen an welcher Version es liegt bzw. ob es überhaupt an einer der letzten Änderungen liegt. 
[v0.11.18](https://github.com/2Abendsegler/GClh/raw/cedd5f538ad30641564d9159123e10b4ba69fa42/gc_little_helper_II.user.js)
[v0.11.17](https://github.com/2Abendsegler/GClh/raw/bf80e644222cb8b2a0361a9c82c91ea36e80b0b2/gc_little_helper_II.user.js)
[v0.11.16](https://github.com/2Abendsegler/GClh/raw/0d95fd24e93b9733cf9d1905c28b7557fac6d8bf/gc_little_helper_II.user.js)

[Hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) kommst du wieder zurück zur aktuellen Version. 

LG
Frank

**Comment by gpsschneider** [comment]
Soll das so sein, dass nach einer Neuinstallation immer noch 0.11.19 als Version da steht? Bin da gerade unsicher, ob das richtig installiert wird...

**Comment by 2Abendsegler** [comment]
Moin Tom,

ja, das sollte so sein. Sorry, das wollte ich gestern noch beschreiben, hatte es dann aber doch vergessen. 

Tampermonkey listet beim Update alle Änderungen ab. Wenn du sicher gehen möchtest, dass ein Update erfolgt ist, dann kannst du das Update ein weiteres Mal anwählen. Listet Tampermonkey das komplette Script ab und keine Änderungen, dann ist das Update bereits erfolgt. Ich glaube der Button zum Update heißt dann auch anders.

LG 
Frank

PS: Wie kam ich eigentlich auf Thomas? 🤭 Irgendwie hat mich die Paddeltour übers Veerse Meer gestern doch mehr geschlaucht als gedacht. 😂

**Comment by gpsschneider** [comment]
N‘Abend :)

dann scheint das Installieren der älteren Skripte nicht zu funktionieren.
Da steht im Tampermonkey immer 0.11.19. Egal, was ich tue.

Hab das vorhandene Skript im Tampermonkey gelöscht, GC neu geladen, dort
war es weg, dann auf die Links geklickt, dann hat es installiert und im
Tanpermonkey stand wieder 0.11.19.
Ich hätte erwartet, dass dann 0.11.16 da steht.

Bin übrigens grad am Versuchen, mal ne alte Tampermonkey-Version zu
installieren. Vielleicht liegt es ja daran.

VG
Tom
PS: Keine Ahnung, wie Du auf Thomas kommst. 🤷‍♂️
Passt ja, deswegen hab ich mich da eher weniger gewundert.
Weiß ja nicht, was ihr beim Paddeln so trinkt äh macht… 🙄😃



2Abendsegler ***@***.***> schrieb am Mi. 17. Aug. 2022 um
21:41:

**Comment by capoaira** [comment]
Die Links von 2Abendsegler funktionieren bei mir.
Versuche aber sonst mal folgende, bei denen wird auch die Versionsnummer downgradet und Tampermonkey sollte statt `update` oder `Neu instalieren`, `downgrade` als Button zeigen.
[Version 0.11.18](https://github.com/2Abendsegler/GClh/blob/1c94620cf9045bec834f1a761f27e7c7b4c95c84/gc_little_helper_II.user.js?raw=true)
[Version 0.11.17](https://github.com/2Abendsegler/GClh/blob/15543a1462225f392e4e8e5ff2293291b6925da9/gc_little_helper_II.user.js?raw=true)
[Version 0.11.16](https://github.com/2Abendsegler/GClh/blob/b78a635070001d57ebd86f56040804789fc82936/gc_little_helper_II.user.js?raw=true)
Irgendwann wird das Script dann meckern und ein automatisches Update durchführen wollen. Davon nicht beirren lassen ;)

**Comment by gpsschneider** [comment]
Moin,
sorry, ich hatte die letzten Tage viel zu tun und bin nicht zum Testen
gekommen.
Ich schau mal, dass ich euch heute ne Rückmeldung gebe.
Viele Grüße
Tom

capoaira ***@***.***> schrieb am Do. 18. Aug. 2022 um 15:07:

**Comment by gpsschneider** [comment]
Interessant. Im Inkognitomodus läuft das Skript schnell. Dort ist die
SMIME-Extension nicht aktiv.
Vermutlich macht das Ding doch Probleme... :(

Am Do., 25. Aug. 2022 um 19:45 Uhr schrieb Gps Schneider <
***@***.***>:

**Comment by lukeIam** [comment]
hallo zusammen - ich habe das Problem zwar nicht, aber vielleicht bringt mein Hinweis auch euch was:

Ich hatte ähnliche Probleme auf der Karten-Seite (ohne aktivierten GCLH2) während der Entwicklung GCComment 2 (auch ohne geladene Haderleiste).
Und ich hatte das Gefühl es war häufiger und schlimmer wenn ich die Chrome Debug Console offen hatte.

Ich bin dem etwas nachgegangen und bin auch auf die "getTagCookieCategories()" gestoßen und die kommt aus uc.js von cookiebot.

Ich habe jetzt in meinem AdBlocker `https://consent.cookiebot.com/uc.js` auf die Blacklist gesetzt und zumindest gefühlt ist es jetzt viel besser.

Grüße

**Comment by gpsschneider** [comment]
Krass :o :o :o 

Genau das war es!!! Seite läuft wieder super schnell.
 
Das kann gerne als Lösung übernommen werden: 
Folgende Regel in (bei mir uBlock Origin) übernehmen: "[www.geocaching.com](http://www.geocaching.com/) [cookiebot.com](http://cookiebot.com/) * block"
Das sieht dann so aus:

![image](https://user-images.githubusercontent.com/111235822/188083815-a10d22ca-9926-4d69-b0e4-ed07c769b1cc.png)


Vielen Dank nochmal! 
Setzt ihr den Status des Issues?

**Comment by capoaira** [comment]
Freut mich, dass es jetzt klappt 👍🏻👍🏻👍🏻
Vielen Dank @lukeIam und vielen Dank @gpsschneider für die vielen Test 👍🏻

Das blocken vom Cookiebot sollte aber nicht die finale Lösung sein, wir werden weiter gucken, ob wir das selbst umgehen können.☺

**Comment by capoaira** [comment]
Das ganze sieht etwas komplexer aus. Wenn das Ganze in Microsoft 365 inkludiert ist, kann ich das bei Gelegenheit testen. Im Moment fehlt mir aber die Zeit und Motivation

**Comment by 2Abendsegler** [comment]
Danke für die Info.
So wie ich meine gelesen zu haben sollte das mit dem Paket Microsoft 365 funktionieren. Die Erweiterung muss man dann wohl noch installieren und vermutlich noch einiges Einrichten.

**Comment by gpsschneider** [comment]
N'Abend,

so, ich habe nochmal intensiv getestet. In allen Versionen ist das Laden
der Drafts langsam. :(
Egal, ob mit oder ohne UBlock oder andere Extensions.
Ich vermute mal, das liegt am Tampermonkey oder am Browser. Ansonsten
hättet ihr das bestimmt schon von anderen auch gehört. Leider habe ich es
noch nicht geschafft, Tampermonkey mal downzugraden. In der neuen
Beta-Version tritt das auch so auf.

Von daher würde ich erstmal mit nem anderen Browser weitermachen, da mir so
langsam die Ideen ausgehen und ich euch auch nicht zu viel Zeit damit
klauen will. Die SMIME-Extension bekomme ich leider nicht weg.

Vielen Dank auf jeden Fall für eure Hilfe!!! Wenn Tampermonkey mal wieder
ein Update hat, werde ich mal wieder testen - vielleicht geht es ja dann.

Viele Grüße

Tom

Am Di., 23. Aug. 2022 um 07:22 Uhr schrieb Gps Schneider <
***@***.***>:

**Comment by gpsschneider** [comment]
Krass :o :o :o

Genau das war es!!! Vielen Dank!
Das kann gerne als Lösung übernommen werden:

Einfach folgende Regel in (bei mir uBlock Origin) übernehmen: "
www.geocaching.com cookiebot.com * block"
Das sieht dann so aus:
[image: image.png]

Vielen Dank nochmal!
Setzt ihr den Status des Issues?

Am So., 28. Aug. 2022 um 13:15 Uhr schrieb lukeIam ***@***.***

**Comment by capoaira** [comment]
Oh, das hatte ich komplett vergessen :(

Tatsächlich nutze ich seit etwas über einem Jahr auch hauptsächlich Linux und da laufen Microsoft Apps ja garnicht...

Ich denke auch, der Workaround ist gut, wir können das Issue schließen.
