### ISSUE TITLE
[PQ-Splitter] "Create PQ(s)" button on Project-GC's PQ Splitter page does not work

### ISSUE THREAD

**Issue by UJstr** [2Abendsegler/GClh#2177]
### Describe the bug

PQ-Teiler ausgeführt, es werden 10 PQ's angezeigt. Klickt man auf den Button "Create PQ(s)" öffnen sich keine Fenster, es werden im Hintergrund auch keine PQ erzeugt. 

Auf der GC-Seite und in Project-GC bin ich jeweils angemeldet.

### To Reproduce

1. Project-GC.com
2. authenticate
3. https://project-gc.com/Tools/PQSplit
4. Set filter 
5. Result:

```

# | Startdatum | Enddatum | Tage | Caches
-- | -- | -- | -- | --
März/09/2002 | August/24/2011 | 3456 | 990
August/25/2011 | Mai/04/2013 | 619 | 990
Mai/05/2013 | Januar/06/2015 | 612 | 989
Januar/07/2015 | Juni/24/2016 | 535 | 989
Juni/25/2016 | Februar/03/2018 | 589 | 988
Februar/04/2018 | Oktober/12/2019 | 616 | 989
Oktober/13/2019 | Oktober/22/2020 | 376 | 989
Oktober/23/2020 | Mai/30/2021 | 220 | 988
Mai/31/2021 | Juni/26/2022 | 392 | 989
Juni/27/2022 |   |   | 218

```

Press Button Create PQ(s)

### Expected behavior

10 Fenster sollten sich öffnen und PQ's unter https://www.geocaching.com/pocket/ erzeugen.

### OS

MacOS

### Browser

Chrome

### GClh Version

aktuell

### Additional context

Funktioniert ebenfalls nicht unter der Kombination Mint Linux 20.2 / Firefox

**Comment by 2Abendsegler** [comment]
Eigentlich sollten sich kleine Browser Tabs öffnen. Am wahrscheinlichsten ist es, dass der Popup Blocker deines Browsers das Öffnen der Popups verhindert. Ich weiß aber gerade gar nicht wie man das prüfen kann. Weiß das jemand?
Funktionierte es denn schon mal oder ist das der erste Versuch?
LG

**Comment by UJstr** [comment]
Nein, das war es nicht. In den Browsereinstellungen hatte project-gc die Erlaubnis popups zu öffnen und JavaScript ist für alle Seiten aktiviert. Ich habe es auch einmal generell eingeschaltet und den Chrome neu gestartet.  Keine Veränderung.

Im Juni hat es noch funktioniert (MacOS/Chrome) seit dem gab es nur kleinere Software-Updates.

**Comment by 2Abendsegler** [comment]
Kannst du bitte mal in der Konsole nachsehen ob dort irgendwelche Fehler (rot) stehen. Gleichzeitig die Tasten Ctrl, Shift und c drücken. Vielleicht muss noch der Reiter Console angewählt werden. Wenn Fehler vorhanden, dann am besten einen Screenshot hier reinhängen.

**Comment by UJstr** [comment]
`userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:2417 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at HTMLInputElement.<anonymous> (userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:2417:48)
    at Function.each (userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:882:12795)
    at init.each (userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:882:9370)
    at getSelection (userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:2415:96)
    at HTMLTableRowElement.<anonymous> (userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:2363:27)
    at Function.each (userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:882:12795)
    at init.each (userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:882:9370)
    at HTMLButtonElement.prepareCreatePQ (userscript.html?name=GC%2520little%2520helper%2520II.user.js&id=50ea816b-9664-4528-bfda-05266985a593:2354:37)
<img width="1171" alt="Bildschirmfoto 2022-08-28 um 18 10 52" src="https://user-images.githubusercontent.com/110341718/187084001-1e0f4aa1-d756-42a2-b656-c735dd70880a.png">
`

**Comment by UJstr** [comment]
<img width="1402" alt="Bildschirmfoto 2022-08-28 um 18 19 25" src="https://user-images.githubusercontent.com/110341718/187084114-3119f1ed-cf44-420a-a3a9-0626ce4140e8.png">

**Comment by 2Abendsegler** [comment]
Moin,

auf der Project-GC Seite wurden anpassen vorgenommen, die dazu führten, dass das Auslesen der Filter nicht mehr funktionierte. Wenn du möchtest kannst du vorab testen, ob alles wieder funktioniert.
[Hier](https://github.com/2Abendsegler/GClh/raw/b64aa2481cf62573c3bb789558990e3c2b78de59/gc_little_helper_II.user.js) gibt es eine Vorabkorrektur.
[Hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) kommst du wieder zurück zur aktuellen Version. 

LG Frank

PS: Sorry, hat etwas gedauert. War in letzter Zeit ziemlich mit Cachen ausgelastet. 😬

**Comment by UJstr** [comment]
Hi Frank,

alles gut, Cachen hat Vorrang!  Ich bin ja froh, dass es ein so tolles Tool gibt. 

Der Teiler funktioniert. Mir ist nur  aufgefallen, dass die Einstellungen 

![PastedGraphic-1](https://user-images.githubusercontent.com/110341718/190255220-99e0cf6d-4510-47c5-918e-9a7b2c2c3fe6.png)

nicht übernommen werden. Ändere ich die Daten im Nachgang, stimmt es mit dem PQ-Splitter wieder überein.

ich hatte auch die gefundenen Caches in der PQ. Da ich den Teiler bisher nicht in der HomeZone genutzt hatte, ist mir das nicht aufgefallen, ob das ein Fehler ist oder ein Änderungswunsch wäre:

![PastedGraphic-2](https://user-images.githubusercontent.com/110341718/190255814-06976388-a0a7-4f6a-9a2c-17654b19f540.png)


VG

Udo

**Comment by 2Abendsegler** [comment]
Hallo Udo,

danke für deine Rückmeldung.

Die Default Values für neue PQs sollten aus meiner Sicht nicht gesetzt werden, weil sie die Ergebnisse des PQ-Splitters ja nochmal abändern würden, was zu anderen Ergebnissen führen könnte. Wir wollen doch gerade nur die Einstellungen aus dem PQ-Splitter übernehmen. 

Mir leuchtet es gerade nicht ein, warum eine Anpassung der Daten im Nachgang dazu führen könnte, dass die Daten dann mit dem PQ-Splitter übereinstimmen. Ich glaube das ist in deinem Fall nur Zufall. Die angegebene Anzahl von Caches aus dem PQ-Splitter muss nicht immer genau mit der Anzahl der Caches aus der PQ übereinstimmen, weil die Daten mit denen Project-GC arbeitet ein paar Tage veraltet sein können. Kannst du das vielleicht nochmal überprüfen und testen?

Zu deinem zweiten Punkt bezüglich der gefundenen Caches in der PQ. Auch hier sollten wir nur diejenigen Einstellungen übernehmen, die im PQ-Splitter getroffen wurden. Wenn du die gefundenen Caches nicht in der PQ haben möchtest, dann kannst du das im PQ-Splitter einstellen mit dem Filter "Hide Found" oder "Verbergen Gefundene" (oder so ähnlich). Kennst du den Filter?

LG Frank

**Comment by UJstr** [comment]
Genau die Filter hatte ich im PQ Splitter ja vorab eingestellt:

![Bildschirmfoto 2022-09-15 um 06 58 17](https://user-images.githubusercontent.com/110341718/190318298-dc4e083f-d18a-4e0f-97f9-78ba140901fd.png)

und die wurden nicht in die PQ übernommen. Ich war mir nur nicht sicher, ob das noch nie so gewesen ist, oder jetzt erst auftritt. dass müsstet Ihr wissen. 

Koordinate und Land werden richtig übernommen:
![Bildschirmfoto 2022-09-15 um 07 00 52](https://user-images.githubusercontent.com/110341718/190318640-8cd701d5-08a9-40bb-917e-bad4ba253289.png)

Die Daten hatte ich händische eingegeben und (zufällig!) zum Zeitpunkt die gleiche Anzahl an Caches, wie im Teiler vorgeschlagen.

VG

Udo

**Comment by 2Abendsegler** [comment]
Ok, danke für den Hinweis. Das muss ich mir noch anschauen. Womöglich gibt es hier ein weiteres Problem, denn eigentlich sollten diese Werte aus dem PQ-Splitter übernommen werden.

**Comment by 2Abendsegler** [comment]
Moin Udo,

durch meine letzten Änderungen sind ein paar Parameter nicht mehr gesetzt worden. Unter anderem der hidefound Parameter, sorry. Das habe ich nun korrigiert und alle Parameter getestet. Wenn du möchtest kannst du auch noch mal testen, bevor wir das in die nächste Version schieben.
[Hier](https://github.com/2Abendsegler/GClh/raw/1b89237ef1930298c82896ecb52c9711e85cc515/gc_little_helper_II.user.js) kannst du testen.
[Hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) kommst du wieder zurück zur aktuellen Version, falls nötig. 

LG Frank

**Comment by UJstr** [comment]
Sieht gut aus, die Daten werden in die PQ übernommen. Du brauchst Dich nicht für diese tolle Arbeit zu entschuldigen! Sobald irgend etwas an einer der Website geändert wird, muss man ja leider alles wieder überprüfen werden. Logisch, dass man das nicht alles immer testen kann. 

Für die Feature-List wäre jetzt noch cool, wenn die Einstellungen aus den Parameter übernommen würden, die nicht auf Project-GC hinterlegt werden können. Also z.B.:

![Bildschirmfoto 2022-09-28 um 22 43 40](https://user-images.githubusercontent.com/110341718/192884990-83b57366-a0eb-4695-bc75-e66bd1ef7d9e.png)

VG

Udo

**Comment by 2Abendsegler** [comment]
Danke für die Rückmeldung.
Magst du vielleicht für die zusätzliche Anforderung ein neues Issue aufmachen?
Magst du uns deinen Cachernamen nennen, damit wir den auf der Thanks Seite eintragen können?

---
Merged with #2187

**Comment by UJstr** [comment]
Hi Frank ,

Gerne.


Happy Hunting

Udo von
Die C-SAU Bande
