### ISSUE TITLE
[VIP / Vup] gclh_build_vipvupmail run into issues if settings_show_vip_list is off

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2183]
>Auf der Karte:
https://www.geocaching.com/play/map?lat=48.0785&lng=11.6122&zoom=14&asc=true&sort=distance&st=N+48%C2%B0+6.349%27+E+11%C2%B0+33.180%27&ot=coords
Sieht das bei mir so aus.
Die ganzen Infos fehlen....
![grafik](https://user-images.githubusercontent.com/24353480/189550317-6e55934a-7b23-4b34-bfa1-6eb79fc499f4.png)
>
>> ![grafik](https://user-images.githubusercontent.com/50927164/175764344-40bb636e-4ed4-4714-95c5-6f65cedc9b9b.png)
>
>Das alles fehlt bei mir... Seltsam.

_Originally posted by @ChristianGK-GC in https://github.com/2Abendsegler/GClh/issues/2091#issuecomment-1243049950_

**Comment by capoaira** [comment]
Achja und auf beiden Karten Seiten [play/map](https://www.geocaching.com/play/map) & [map](https://www.geocaching.com/map/) hab ich den Fehler, sobald ich einen Cache anklicke.
![grafik](https://user-images.githubusercontent.com/24353480/189550535-5434ac9c-ade6-4591-b03e-6e083512413f.png)

Die VIP Funktion ist bei mir nicht aktiv.

_Originally posted by @ChristianGK-GC in https://github.com/2Abendsegler/GClh/issues/2091#issuecomment-1243051205_

**Comment by ChristianGK-GC** [comment]
Teilweise gut. ;-)
[https://www.geocaching.com/map/](https://www.geocaching.com/map/)
![grafik](https://user-images.githubusercontent.com/24353480/189650135-77fecf53-5413-4d70-8a15-c76f1a5c2b8b.png)

[https://www.geocaching.com/play/map](https://www.geocaching.com/play/map)
![grafik](https://user-images.githubusercontent.com/24353480/189650336-5413cd3e-4a14-49b1-ba88-e2f8e91d52a5.png)

**Comment by capoaira** [comment]
Ok, das Problem ist größer als ich dachte und betrifft den gesamten VipVup block... muss an vielen stellen gefixed werden :(

**Comment by capoaira** [comment]
@2Abendsegler kannst du dir den Bug mal angucken, ob ich irgendetwas übersehe? Ich glaube, du bist mit den VIP Funktionen vertrauter als ich.

**Comment by capoaira** [comment]
merged with #2197
