### ISSUE TITLE
[Cache Listing / Search Map / Browse Map / Cache Log] Favorite score missing

### ISSUE THREAD

**Issue by DieBatzen** [2Abendsegler/GClh#2191]
### Describe the bug

GS removed the old method to retrieve the favorite score:
`'/datastore/favorites.svc/score?u='+userToken`

Therefore favorite scores are missing in
- cache listings
- search map
- browse map
- old/new log methods

### To Reproduce

1. Go e.g. to cache listing
2. Favorite score is missing besides the favorite points

### OS

Windows

### Browser

Firefox, Chrome

### GClh Version

0.11.19

### Additional context

Favorite score can be retrieved via web API:
`'/api/proxy/web/v1/geocache/'+gccode+'/favoritepoints/score'`

**Comment by capoaira** [comment]
Gut aufgepasst👍🏻. Danke 😊
