### ISSUE TITLE
[New Log Form] Missing favorite point marker.

### ISSUE THREAD

**Issue by diundbi** [2Abendsegler/GClh#2193]
### Describe the bug

When opening the log-page the heart for favorite points appears as usual. While loading gclh the heart disappeares and there is no chance to give a favorite point for this logentry anymore.

### OS

Windows

### Browser

Edge

### GClh Version

v0.11.19

**Comment by capoaira** [comment]
Can you describe the Issue more in detail? I think you mean the new Log Page, but to me, everything looks normal on that page.
Please add a screenshot of the Issue and take a look into the console (ctrl+shift+C and then console). That information will help us to understand and fix the bug.

**Comment by diundbi** [comment]
<img width="521" alt="Fav missing" src="https://user-images.githubusercontent.com/59375844/192384401-5a2d17d0-0a5a-478e-b62c-ee19f6bb52a0.PNG">

**Comment by diundbi** [comment]
In the circle there should be a "heart" icon

**Comment by diundbi** [comment]
secureclick-media-maynemyltf.netdna-ssl.com/Extensions/rjs/c2.js:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
log:1 
        
       Mixed Content: The page at 'https://www.geocaching.com/play/geocache/gc80dga/log' was loaded over HTTPS, but requested an insecure element 'http://img.geocaching.com/cache/7b3b511e-9b9b-48ed-8477-c9bc1f90a7a6.jpg?rnd=0.7266896'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
log:1 
        
       Mixed Content: The page at 'https://www.geocaching.com/play/geocache/gc80dga/log' was loaded over HTTPS, but requested an insecure element 'http://img.geocaching.com/cache/7b3b511e-9b9b-48ed-8477-c9bc1f90a7a6.jpg?rnd=0.7266896'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
/datastore/favorites.svc/score?u=4OB3GFHLRR3CHNTWDVM2KYZOWHY7KZ5USHJGRP67H3KHXL6XJFAOQFTRLGTRFIDBYCXIXFGBBJIZ7FLVNQKAESNZISCJONYE6HTWBY5NDV5MGZ4ILYZ4SDBBDTFXBRPDE2UMQBCDB7UMR7A6VZHSKKXKO2XDHCHSJT2DB44XD5RMWAHI7OXABB6W26ZXNOH2ZNAUZQRBFVLGSO7DVAYH7U4KFHVMYMJ3LB6P5KIUCH4V7PU4IJJDEFRP3RMYMENWXKIWAJCC6OCIXZTBWVBRCV3UE3ACJSIR4HGGUGTBNOHQVOR32PXR2ULEMSEZM4EY22CWJDYWEZL7YYM25SJXUWFJFTW4V32DVGGTNRA:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by capoaira** [comment]
> <img alt="Fav missing" width="521" src="https://user-images.githubusercontent.com/59375844/192384401-5a2d17d0-0a5a-478e-b62c-ee19f6bb52a0.PNG">

Hm, komisch, bei mir funktioniert es wie gewohnt:
![grafik](https://user-images.githubusercontent.com/50927164/192384787-b5adba4f-af70-45a4-bdbb-54e5506d1fcd.png)

Mir fallen 2 dinge auf:
1. Unter Loglength sind 2 Symbole, wo kommen die her? Hast du noch andere Add-ons aktiviert?
2. Auch dass `!` neben dem "Problem melden" fehlt.




> secureclick-media-maynemyltf.netdna-ssl.com/Extensions/rjs/c2.js:1
> 
> ```
>    Failed to load resource: net::ERR_NAME_NOT_RESOLVED
> ```
> 
> log:1
> 
> ```
>    Mixed Content: The page at 'https://www.geocaching.com/play/geocache/gc80dga/log' was loaded over HTTPS, but requested an insecure element 'http://img.geocaching.com/cache/7b3b511e-9b9b-48ed-8477-c9bc1f90a7a6.jpg?rnd=0.7266896'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
> ```
> 
> log:1
> 
> ```
>    Mixed Content: The page at 'https://www.geocaching.com/play/geocache/gc80dga/log' was loaded over HTTPS, but requested an insecure element 'http://img.geocaching.com/cache/7b3b511e-9b9b-48ed-8477-c9bc1f90a7a6.jpg?rnd=0.7266896'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
> ```
> 
> /datastore/favorites.svc/score?u=4OB3GFHLRR3CHNTWDVM2KYZOWHY7KZ5USHJGRP67H3KHXL6XJFAOQFTRLGTRFIDBYCXIXFGBBJIZ7FLVNQKAESNZISCJONYE6HTWBY5NDV5MGZ4ILYZ4SDBBDTFXBRPDE2UMQBCDB7UMR7A6VZHSKKXKO2XDHCHSJT2DB44XD5RMWAHI7OXABB6W26ZXNOH2ZNAUZQRBFVLGSO7DVAYH7U4KFHVMYMJ3LB6P5KIUCH4V7PU4IJJDEFRP3RMYMENWXKIWAJCC6OCIXZTBWVBRCV3UE3ACJSIR4HGGUGTBNOHQVOR32PXR2ULEMSEZM4EY22CWJDYWEZL7YYM25SJXUWFJFTW4V32DVGGTNRA:1
> 
> ```
>    Failed to load resource: the server responded with a status of 404 (Not Found)
> ```

Ok, da steht nichts, was den Fehler verursacht. Die letzte ist zwar vom GClh, aber zeigt einen anderen Bug (#2191)

**Comment by 2Abendsegler** [comment]
Moin,
danke für die zusätzlichen Informationen.
In deinem Screenshot sind zwei uns unbekannte Icons zu sehen. Kann es sein, dass du noch andere Scripte oder Add Ons am Laufen hast? Bitte gegebenenfalls mal deaktivieren und nochmal testen ob das Problem immer noch besteht.

**Comment by diundbi** [comment]
Ich habe noch "Geocaching Utils" installiert. Ich vermute, die Symbole stammen von dort. Das Problem mit dem fehlenden Herz ist mir nach der Installation von Version v0.11.18 aufgefallen.

**Comment by diundbi** [comment]
Weiterhin ist noch der !Mystery Wizard" installiert. Habe beide Extensions deaktiviert, die Cacheseite refreshed - hat kein anderes Ergebnis gebracht

**Comment by diundbi** [comment]
Mit dem "Chrome"-Browser habe ich den selben Effekt

**Comment by capoaira** [comment]
Bei mir ändert Geocaching Utils auch nichts:
![grafik](https://user-images.githubusercontent.com/50927164/192388418-125b5949-c450-4f3f-9265-9fb9a2ac3b51.png)

Hast du noch andere Erweiterungen? 

Wenn ich mir deine Konsolen Logs ansehe, sehe ich, dass das alte Multi-Symbol geladen wird, das dürfte aber weder von der Seite selbst, noch von einem der hier erwähnten Erweiterungen sein...

**Comment by 2Abendsegler** [comment]
@capoaira 
> Ok, da steht nichts, was den Fehler verursacht. Die letzte ist zwar vom GClh, aber zeigt einen anderen Bug (#2191)

Dann sollte der Fehler doch auch bei mir angezeigt werden wenn ich mit der master Version arbeite. Das ist aber nicht der Fall.

**Comment by diundbi** [comment]
Wenn ich die Logseite zwei - drei Mal aktualisiere, ist der Marker tatsächlich da

**Comment by capoaira** [comment]
> @capoaira
> 
> > Ok, da steht nichts, was den Fehler verursacht. Die letzte ist zwar vom GClh, aber zeigt einen anderen Bug (#2191)
> 
> Dann sollte der Fehler doch auch bei mir angezeigt werden wenn ich mit der master Version arbeite. Das ist aber nicht der Fall.

Jip, das sollte der Fall sein. Bei FF wird mir die Meldung aber auch normal nicht angezeigt. Nur wenn ich XHR Meldungen dazu nehme.

**Comment by capoaira** [comment]
> Wenn ich die Logseite zwei - drei Mal aktualisiere, ist der Marker tatsächlich da

Hm, dann fehlen mir gerade die Ideen...

**Comment by diundbi** [comment]
Wenn ich weiss, dass es mit der Aktualisierung funktioniert, kann ich damit leben, auch wenn es natürlich nicht sehr komfortabel ist. Vielleicht fällt euch ja noch etwas ein. Auf jeden Fall schon einmal herzlichen Dank.

**Comment by 2Abendsegler** [comment]
> Wenn ich die Logseite zwei - drei Mal aktualisiere, ist der Marker tatsächlich da

Wenn du Geocaching Utils und Mystery Wizard deaktiviert hast oder wenn die noch aktiv sind?

**Comment by diundbi** [comment]
Geocaching Utils habe ich derzeit noch deaktiviert. Der Mystery Wizard ist aktiv.

**Comment by capoaira** [comment]
>Geocaching Utils habe ich derzeit noch deaktiviert

Dann liegt es vielleicht daran. Wenn ich die nächsten Tage etwas Zeit habe, werde ich mir den Utils Code mal ansehen und gucken, wo die beiden Scripte sich ins Gehege kommen könnten.

Auf den Mystery-Wizard müssen wir hier nicht achten, der ist auf den Log-Seiten nicht aktiv.

**Comment by diundbi** [comment]
Vielen Dank

capoaira ***@***.***> schrieb am Di., 27. Sept. 2022, 00:35:

**Comment by ztNFny** [comment]
Same issue here, happens "randomly", haven't found a pattern yet. Could even be an issue of the size itself - i never opened the log form without gclh 😉

**Comment by 2Abendsegler** [comment]
@ztNFny 
Ist die Sprache bei Geocaching deutsch wenn der Fehler auftritt?

**Comment by ztNFny** [comment]
No, always english

**Comment by 2Abendsegler** [comment]
Ich kann den Fehler manchmal nachstellen, aber nur wenn ich bei Geocaching deutsch als Sprache eingestellt habe. Die beiden Icons (Herz und Ausrufezeichen) sind in diesen Fällen einfach nicht vorhanden.

Normal, mit svg:
![Unbenannt2](https://user-images.githubusercontent.com/22332216/212876084-96c25aa8-7ce5-4c7c-86af-b0534741faac.JPG)

Fehlerhaft, ohne svg:
![Unbenannt](https://user-images.githubusercontent.com/22332216/212876182-0b84e5e1-c006-4ccc-912d-4018ac5b8fe4.JPG)

**Comment by ztNFny** [comment]
![image](https://user-images.githubusercontent.com/1258173/212876840-95d91bb4-d7f1-4c6d-9b59-5e92af953638.png)
height and width is 0

**Comment by ztNFny** [comment]
Yes, the SVG child of button is missing

**Comment by 2Abendsegler** [comment]
Das Problem entsteht durch den alten Header, den wir auf allen Seiten aufbauen.
Sobald der alte Header über `changeHeaderLayout()` aufgebaut wird, verschwinden die Icons. Wenn man mit dem Aufruf der Funktion ein paar Sekunden wartet, sieht man die Icons und nach den Sekunden verschwinden sie wieder. 
![GIF 17 01 2023 12-38-51](https://user-images.githubusercontent.com/22332216/212889888-0f2581b1-858e-40f8-b139-53e636b754a1.gif)
Voll dubios. Für heute habe ich genug.
