### ISSUE TITLE
[Browse Map] Improve clickability on list names of add to list popup.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2194]
### Is your feature request related to a problem? Please describe

Short list names are not clickable behind of the list name. 
![Zwischenablage01](https://user-images.githubusercontent.com/22332216/192650172-e1168900-c8e5-4177-a681-7899b0ce87bf.jpg)

Long list names are not clickable from about halfway.
![Zwischenablage02](https://user-images.githubusercontent.com/22332216/192650289-4cbcce16-2794-48a9-bae1-981770f0b033.jpg)

### Describe the solution you'd like

Make the entire row clickable.

**Comment by capoaira** [comment]
Merged with #2195
