### ISSUE TITLE
[PQ-Splitter] Additional settings on Project-GC's PQ Splitter page.

### ISSUE THREAD

**Issue by UJstr** [2Abendsegler/GClh#2196]
### Is your feature request related to a problem? Please describe

Wenn man auf der website [https://project-gc.com/Tools/PQSplit](https://project-gc.com/Tools/PQSplit) kann man verschiedene Parameter eingeben, die beim Aufteilen übernommen werden, z.B.:  Gefunden, eigene, Cachetyp, Größe, Schwierigkeit oder Gelände.

Die Seite bietet leider keine Möglichkeit die Parameter 

- nicht auf meiner Ignore Liste 
- ist aktiv
- Pocket Query-Namen im Dateinamen verwenden

zu setzen.

siehe:
![Bildschirmfoto 2022-09-28 um 23 22 27](https://user-images.githubusercontent.com/110341718/192891324-ad5b3006-3fb2-45b7-84e0-c56cf089f9bb.png)

### Describe the solution you'd like

Diese Parameter sind in den Einstellungen als mögliche Defaultwerte für Pocket Queries hinterlegbar:

![Bildschirmfoto 2022-09-28 um 23 14 23](https://user-images.githubusercontent.com/110341718/192890866-39df3673-6dc6-44be-8c25-4dabc5d18e63.png)

Es wäre ein schönes Feature, wenn die fehlenden Parameter beim Erzeugen durch den PQ-Teiler direkt ergänzt werden, so dass ein manuelles Nachbearbeiten reduziert wird.

### Additional context

If you go to the website [https://project-gc.com/Tools/PQSplit](https://project-gc.com/Tools/PQSplit) you can enter various parameters that will be applied when splitting, e.g.: Found , owned, cache type, size, difficulty or terrain.

Unfortunately, the page does not offer the possibility to change the parameters

- not on my ignore list
- is active
- Use Pocket Query name in filename

to choose.

please refer:
![Screenshot 2022-09-28 at 23 22 27](https://user-images.githubusercontent.com/110341718/192891324-ad5b3006-3fb2-45b7-84e0-c56cf089f9bb.png)

These parameters are already sotred in the settings as possible default values for new pocket queries:

![Screenshot 2022-09-28 at 23 14 23](https://user-images.githubusercontent.com/110341718/192890866-39df3673-6dc6-44be-8c25-4dabc5d18e63.png)

It would be a nice feature if the missing parameters were added directly when the PQ is created by PQSplit, so that manual post-processing is reduced.

**Comment by 2Abendsegler** [comment]
Moin,

wir werden die drei zusätzlichen Parameter direkt bei der Konfiguration auf der PQ Splitter Seite vorsehen. Wir haben dort ja bereits einige Parameter. 
![Unbenannt](https://user-images.githubusercontent.com/22332216/192908204-c67074ef-2551-405f-91e7-42ddec46c457.JPG)

Der GClh behält sich die Einstellungen auf der PQ Splitter Seite, so dass sie nicht immer wieder erneut eingegeben werden müssen.

Ich will das nicht mit den Default Settings für neue PQs verknüpfen, weil es nicht jedem klar sein wird, wie es zu diesen Einstellungen kommt. Wir haben eine solche Verknüpfung bereits an anderen Stellen gemacht und obwohl wir dort die Default Einstellungen erwähnt haben, kommt es immer wieder zu Rückfragen. 

Ich weiß noch nicht ob wir den Einbau zur nächsten Version schaffen, die vielleicht am Wochenende kommen wird.

LG Frank

**Comment by UJstr** [comment]
Eilt nicht... 

Ich freue mich über jede Weiterentwicklung.

**Comment by capoaira** [comment]
merged with #2207

**Comment by UJstr** [comment]
Das sieht hervorragend aus. Ich hatte nur zunächst die Checkbox "Include pocket query name in download file name" übersehen...

VG
Udo
