### ISSUE TITLE
[Cache Listing] Add logs by Lackeys to VIP-List.

### ISSUE THREAD

**Issue by jakedot** [2Abendsegler/GClh#2203]
### Is your feature request related to a problem? Please describe

Events are routinely archived 30 days after the event date by the Lackey account Geocaching HQ Admin. Normal logs by Reviewer accounts are shown in the VIP-List (e.g. Publish, Unarchive, Retract, Archive, Disable) but at least not for this account. 

If I remember correctly, e.g. Will Attend logs by Reviewers and Lackeys are shown in the VIP-List for events.

### Describe the solution you'd like

Reviewer-type Logs by Lackeys should be shown in the VIP list.

### Additional context

Example: [CCE Listing GC8K0TE](https://coord.info/GC8K0TE)

![image](https://user-images.githubusercontent.com/12250212/193617035-294f5d32-355d-48da-9522-9dbb42afab4b.png)

![image](https://user-images.githubusercontent.com/12250212/193617104-f6416c9a-7acd-40b9-8105-84205896cc04.png)

**Comment by 2Abendsegler** [comment]
Hi jakedot,
we will implement this feature.
Regards Frank

---
Es sollte ausreichen wenn in den "log_infos..." der GroupTitle "Lackey" so wie der GroupTitle "Reviewer" mit "membership_level" "Reviewer" versehen wird. Das muss für jede VIP Liste gemacht werden.

**Comment by 2Abendsegler** [comment]
Hi,

we have implement the feature. Can you maybe test?

[Here is an temporary feature version.](https://github.com/2Abendsegler/GClh/raw/20495155f39f8e1c703bcbb9ce5810ba68c7c423/gc_little_helper_II.user.js)
[Here you come back to the current version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) in case the feature version causes problems.

Cheers Frank

**Comment by jakedot** [comment]
Great thanks! Will test it in the evening.

**Comment by jakedot** [comment]
![image](https://user-images.githubusercontent.com/12250212/193881692-3e2f77c5-3144-4fd3-b9c7-d3fd717c4449.png)

LGTM!

thanks a lot for the quick support and Servus from Linz!

**Comment by 2Abendsegler** [comment]
@jakedot 
Moin,

capoaira hat [bemerkt](https://github.com/2Abendsegler/GClh/pull/2204#issuecomment-1266911306), dass die Lackeys eigentlich Spieler Accounts sind und nur in Ausnahmefällen Reviewer Tätigkeiten wahrnehmen. 

Deshalb haben wir noch mal nachgebessert und integrieren die Lackeys nicht als Reviewer, sondern ermöglichen es über einen neuen Config Parameter die Lackeys in der VIP Liste anzuzeigen. 

[Hier](https://github.com/2Abendsegler/GClh/raw/6db555776eb94668ec5966d1487f75fc5b4bc1a5/gc_little_helper_II.user.js) kannst du das Feature vorab installieren.
[Hier](https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_lackey_as_vip) kannst du den neuen neuen Config Parameter aktivieren.

Ich schließe das Issue.
LG
Frank

---
merged with #2204
