### ISSUE TITLE
[Friends List] Error on page if "Show summary for new finds/hides in friends list" is deactivated.

### ISSUE THREAD

**Issue by ChristianGK-GC** [2Abendsegler/GClh#2205]
### Describe the bug

https://www.geocaching.com/my/myfriends.aspx

Improve friends list: document.getElementsByClassName(...)[0] is undefined

`spanTclass` does not exists

`
document.getElementsByClassName('spanTclass')[0].appendChild(button);
`

### To Reproduce

Open [https://www.geocaching.com/my/myfriends.aspx](https://www.geocaching.com/my/myfriends.aspx)

### OS

Windows, Linux

### Browser

Firefox

### GClh Version

0.11.20

**Comment by ChristianGK-GC** [comment]
Keine Ahnung wo der Button war.

**Comment by ChristianGK-GC** [comment]
Wie wäre es dann gleich noch mit einem schöneren Button?
![grafik](https://user-images.githubusercontent.com/24353480/194044477-d341f8cc-d42a-4b1a-9a29-9c4ac4b583f6.png)

**Comment by 2Abendsegler** [comment]
Der Fehler taucht nur auf wenn [Show summary for new finds/hides in friends list](https://www.geocaching.com/my/#GClhShowConfig#a#settings_friendlist_summary) deaktiviert ist.

[Ursprünglich sah das mal so aus.](https://github.com/2Abendsegler/GClh/blob/collector/images/v0.4_Screen17.jpg)
Damals hatten wir den Reset Button neben den anderen plaziert. Das sah etwas aufgeräumter aus, als es jetzt der Fall ist. Das gilt besonders, wenn wir den Reset Button nun als echten Button darstellen. 

Wir benötigen den Button auch für den Fall, dass "Show summary for new finds/hides in friends list" deaktiviert ist, deshalb ist er an der jetzigen Stelle nicht gut aufgehoben.

Ich finde den neuen Platz neben dem "Sort by" nicht schlecht. Vielleicht sollten wir versuchen die css von GS zu verwenden, damit unser Button auch nach irgendwelchen Änderungen von GS noch so aussieht wie der GS Button.

@capoaira 
@Herr-Ma (Chief of this page 😂)
Was meint ihr?

**Comment by Herr-Ma** [comment]
Den Button neben dem "Sort by" finde ich optisch ok, thematisch allerdings irgendwie komisch. 

Wenn keine Zusammenfassung angezeigt werden soll, könnten wir das nicht genauso handhaben, wie für den Fall, dass keine Daten für eine Zusammenfassung vorhanden sind? Das sieht im Moment wie folgt aus:

![grafik](https://user-images.githubusercontent.com/23725271/194089571-f63e650a-0774-4726-8ef8-140f041f139e.png)

VG,
Marcus alias Herr Ma  
Chief of this page (muhahahahrrrrrr)

**Comment by ChristianGK-GC** [comment]
> Den Button neben dem "Sort by" finde ich optisch ok, thematisch allerdings irgendwie komisch.
> 
> Wenn keine Zusammenfassung angezeigt werden soll, könnten wir das nicht genauso handhaben, wie für den Fall, dass keine Daten für eine Zusammenfassung vorhanden sind? Das sieht im Moment wie folgt aus:
> 
> ![grafik](https://user-images.githubusercontent.com/23725271/194089571-f63e650a-0774-4726-8ef8-140f041f139e.png)
> 
> VG, Marcus alias Herr Ma Chief of this page (muhahahahrrrrrr)

Finde die Variante super so.
Thematisch war Stimme ich euch zu.

**Comment by 2Abendsegler** [comment]
Moin Marcus, 

der Reset Counter Button dient aber nicht nur zum Zurücksetzen der Zusammenfassung, sondern auch zum Zurücksetzen der Counter bei den einzelnen Freunden, dort stehen die Counter ja auch. Insofern finde ich den Platz oberhalb der Liste der Freunde, neben dem "Sort by", eigentlich thematisch gar nicht unpassend.

Diejenigen, die eine Zusammenfassung deaktiviert hatten, wollten womöglich auch diese eine Zeile nicht sehen, die wir ihnen aber jetzt, im Gegensatz zu bisher, aufs Auge drücken. Vor dem letzten Bug vor einigen Wochen wurde in solchen Fällen nur der Reset Counter Button weiter oben angezeigt. Änderungen an bestehenden Dingen mag nicht immer jeder. 🙄

LG
Frank

**Comment by capoaira** [comment]
>Wie war das vor der letzten Änderung? Gab es den Hinweistext, wann der letzte Reset erfolgt ist, bei deaktivierter Zusammenfassung gar nicht?

Ich glaube den gab es da nicht, dieser Fehler müsste also durch die letzte Umpositionierung entstanden sein.
Trotzdem wäre ich für diese Lösung:

> ![grafik](https://user-images.githubusercontent.com/23725271/194089571-f63e650a-0774-4726-8ef8-140f041f139e.png)

Den Hinweistext anzuzeigen macht mit und ohne Zusammenfassung Sinn, allerdings nutzte ich auch nur die Version mit und bin somit daran gewöhnt 😅

Neben dem "Sort By" macht der Button IMO nur wirklich Sinn, wenn man die Zusammenfassung ausgeschaltet hat, da er ja dann mittig im Feature, aber nicht im Zusammenhang damit stehen würde - ist aber wohl Geschmackssache, den Button von Christian finde definitiv schön :)

> > Änderungen an bestehenden Dingen mag nicht immer jeder.
> 
> Da muss ich dir wohl zustimmen. Allerdings betrifft das natürlich auch diejenigen, die den Button bisher "in der Nähe" der Zusammenfassung angezeigt bekommen haben und ihn dann jetzt innerhalb von ein paar Wochen an einer dritten Stelle vorfinden würden ;-)

... während es für diejenigen, die von diesem Bug betroffen sind, die erste Änderung wäre. Die Umpositionierung war nötig, da der Button in einem Zeilenumbruch gelandet ist. Wir könnten aber natürlich auch versuchen, den Text Input kleiner zu machen und den Button wieder an die alte Stelle schieben - ich frage mich, warum mir das nicht schon beim ersten Bug eingefallen ist 😕

... so oder so, irgendjemand muss sich (erneut) umgewöhnen :(

**Comment by 2Abendsegler** [comment]
> Wir könnten aber natürlich auch versuchen, den Text Input kleiner zu machen und den Button wieder an die alte Stelle schieben

> Wenn es möglich ist, das Input-Feld ein wenig kleiner zu machen, den "Send Invitation"-Button daran anzupassen und den "Reset Counter" Button wieder dahinter darzustellen, wäre das meiner Meinung nach - vom optischen und Gewohnten her - die beste Lösung.

Ja, das hört sich gut an. 

Bei dem letzten Bug wurden einige Änderungen gemacht (#2160). Womöglich ist es einfacher auf die vorangegangene Version zurück zu gehen. Dort dann `ctl00_ContentBody_btnAddFriend`  durch `invitation-button-root` ersetzen. Dann muss nur der Button wieder nach oben geschoben werden und vielleicht noch farblich angepasst werden.

@ChristianGK-GC 
Möchtest du das machen?

**Comment by ChristianGK-GC** [comment]
Meist du das in etwa so:
![grafik](https://user-images.githubusercontent.com/24353480/194415996-159f0e81-7570-4a6a-a683-4a485bc4eef9.png)
Bin gerade von der Dienstreise gekommen und nicht mehr so ganz fit/aufnahmefähig.

**Comment by 2Abendsegler** [comment]
Ja genau. 😊

**Comment by ChristianGK-GC** [comment]
Bitte testen.

**Comment by 2Abendsegler** [comment]
Merged with #2206
