### ISSUE TITLE
[New Log Form] Automatic view posted log after logging.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2208]
### Describe the solution you'd like

After sending a new log using the new log form, the listing will appear. 
If it was a draft related log, you can enable an option to automatic go back to the drafts page or you can enable an option to automatic go to view log page.
If it was a non draft related log, you can enable an option to automatic go to view log page.

![Screen02](https://user-images.githubusercontent.com/22332216/194187078-ae021629-75e7-4f41-8a43-afe5459948f4.jpg)

#2089

**Comment by capoaira** [comment]
merged with #2209
