### ISSUE TITLE
[Drafts] "Count cache and log types" does not work correctly after uploading or deleting drafts.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2215]
### Describe the bug

1. <del>The counted cache types are no longer displayed after clicking to the button "Count cache and log types". The counted log types are displayed.
![Unbenannt](https://user-images.githubusercontent.com/22332216/194530733-efa3eca4-2882-40b8-b575-61ff5703d03f.JPG)</del>

2. If drafts have just been uploaded, processing hangs.
![Unbenannt](https://user-images.githubusercontent.com/22332216/194532163-fad2008b-8a62-4858-9d21-aff502e84679.JPG)

### Expected behavior

[So sollte es aussehen.](https://github.com/2Abendsegler/GClh/blob/master/docu/changelog.md#v01116)

### OS

Windows

### Browser

Firefox

### GClh Version

actual collector

**Comment by capoaira** [comment]
Zu 1. Das ist so, wie es sein soll. Es werden nur die Cachetypen angezeigt, die man gefunden hat. Das funktioniert bei mir noch:
![grafik](https://user-images.githubusercontent.com/50927164/194535381-b35cae80-ba67-4d0d-b6bc-24235e9102e1.png)
Da bei dir keine Funde sind, werden auch keine Cachetypen angezeigt
An 2. arbeite ich :)

**Comment by 2Abendsegler** [comment]
Super! Schön dass du das Thema übernommen hast auch wenn es mit der Motivation ja gerade nicht so gut bestellt ist. 👍 Mit dem Observer Gedöhns hätte ich mich sicherlich schwer getan. 🙄

---
Merged with #2218
