### ISSUE TITLE
Draft type counter not working

### ISSUE THREAD

**Issue by RubyShoos** [2Abendsegler/GClh#2222]
The completely excellent counter you created to count cache types (Trad, Multi, etc.) and log types (Found It, DNF, etc.) in the logging queue (Drafts) does not seem to be working, 

:-(

I'm missing it, as I have a rather unruly backlog at the moment.

**Comment by RubyShoos** [comment]
Sorry - Should have said

I'm using Firefox 105.0.3 (64-bit)

It just gets to the bottom of the queue and then just hangs with this message
![2022-10-08 19_11_11-Drafts — Mozilla Firefox](https://user-images.githubusercontent.com/101502393/194721662-d5a06a19-5c62-4cda-8eeb-096f572aa77f.png)

**Comment by capoaira** [comment]
Thanks for reporting the bug.

Do you try to count after upload / deleting drafts? We are aware of this issue and fixed it in #2215 
Please try the temporary fix until our next version is released: https://github.com/capoaira/GClh/blob/211fb1ec195fa40572d4c3751d6a1bbc19bfad49/gc_little_helper_II.user.js?raw=true
Does it fix the problem?

**Comment by RubyShoos** [comment]
Thank you for getting back so super fast. All of you over at GClh HQ are amazing.

The fix has work and my handle on the disaster that is my logging queue is resolved!

Thank you. And if it can handle this, it is up to whatever anyone throws at it (although I did recently meet someone at an even who had not logged since 2018 and had over 10,000 in his queue!!)
![2022-10-08 19_23_53-Drafts — Mozilla Firefox](https://user-images.githubusercontent.com/101502393/194722138-1ae9b060-9b31-4a7d-8beb-2af38bce24c2.png)
