### ISSUE TITLE
[New Dashboard] Show log text in Markdown as it is in cache listing.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2223]
### Is your feature request related to a problem? Please describe

![Screen07](https://user-images.githubusercontent.com/22332216/194740328-1a1e11a6-3ee3-406f-a29f-63bc9a6268bc.jpg)

### Describe the solution you'd like

[New Dashboard] Show log text in Markdown as it is in cache listing.

**Comment by 2Abendsegler** [comment]
![Screen08](https://user-images.githubusercontent.com/22332216/194740400-96318a9b-72f3-45b3-869d-387372137fe1.jpg)

Config
![Screen09](https://user-images.githubusercontent.com/22332216/194740402-9d8ea8e2-2dc5-4583-8a38-d6ea349a6c42.jpg)

**Comment by capoaira** [comment]
merged with #2224
