### ISSUE TITLE
[Drafts] drafts_go_automatic_back geht nicht vom alten LogForm

### ISSUE THREAD

**Issue by ChristianGK-GC** [2Abendsegler/GClh#2225]
### Describe the bug

In der Version:
https://github.com/2Abendsegler/GClh/blob/collector/gc_little_helper_II.user.js
durch den merge: https://github.com/2Abendsegler/GClh/commit/307041b7a403851e4adcf2dd55590a283be88fbf
geht das `settings_drafts_go_automatic_back` nicht mehr, wenn man mit dem alten Logform (https://www.geocaching.com/seek/log.aspx?PLogGuid= ) geloggt hat.

### GClh Version

collector

**Comment by 2Abendsegler** [comment]
Moin,
für das alte Log Formular haben wir dieses Feature nicht entwickelt.
[Hier](https://github.com/2Abendsegler/GClh/issues/2117#issuecomment-1117571412) gibt es etwas Hintergrund dazu.

**Comment by ChristianGK-GC** [comment]
Im Aktuellen master geht es aber auch mit dem alten LogForm.
Das hab ich damals eingebaut.

**Comment by 2Abendsegler** [comment]
> Im Aktuellen master geht es aber auch mit dem alten LogForm.
> Das hab ich damals eingebaut.

😂 Wo du es sagst. 
Gut aufgepasst. Das hatte ich gar nicht auf dem Schirm.
Ich schau es mir an. Das dürfte ich wohl verbockt haben.

**Comment by ChristianGK-GC** [comment]
Drum hab ich ja auch extra den merge rausgesucht. 😂

**Comment by 2Abendsegler** [comment]
@ChristianGK-GC 
Moin,

ich habe meine Erweiterungen nochmal überarbeitet.
Ich habe @capoaira schon um einen Review für den entsprechenden Pull Request #2226 gebeten.
Wenn du möchtest kannst du aber auch noch mal testen, insbesondere das was du erwartest.
Danke!

**Comment by ChristianGK-GC** [comment]
Moin moin,
ich hab's gleich mal getestet, passt nun aus meiner Sicht.
Gruß
Christian

**Comment by capoaira** [comment]
merged with #2226
