### ISSUE TITLE
[PQ Splitter] Does not close the windows by itself

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2233]
### Discussed in https://github.com/2Abendsegler/GClh/discussions/2230

<div type='discussions-op-text'>

<sup>Originally posted by **capoaira** October 12, 2022</sup>
Moin,
ich nutzte den PQ Splitter eigentlich nicht, aber mir ist aber eben beim Testen aufgefallen, dass nur 5 PQ auf einmal erzeugt werden können und sich die Fenster nicht automatisch schließen. Damit es weitergeht, musste ich die Fenster manuell schließen, daher meine Frage: Gibt es dafür einen Grund, etwas was ich übersehen habe, im Browser einstellen muss, oder ist es ein Bug?</div>

**Comment by capoaira** [comment]
Tested Browser: Firefox, Chrome (both latest versions)
OS: Windows 11

**Comment by 2Abendsegler** [comment]
Ich habe das jetzt auch noch mit Chrome getestet. Auch dort werden bei mir die Fenster automatisch geschlossen. Ich arbeite aber auch unter Windows 10.

Also alles ok bei folgender Systemkonfiguration:
Browser: Firefox, Chrome (both latest versions)
OS: Windows 10 Home

**Comment by 2Abendsegler** [comment]
@capoaira 
Moin,
kannst du vielleicht bei Gelegenheit mal prüfen, ob sich das Problem noch mal nachstellen lässt?

**Comment by capoaira** [comment]
Jip, ist bei mir noch wie beschrieben, 5 Fenster gehen auf, aber schließen sich nicht wieder.
Landest du nach dem Erstellen einer PQ auch auf einer Error 500 Seite? Vielleicht werden die Fenster deshalb nicht geschlossen...

**Comment by 2Abendsegler** [comment]
Danke für dein Feedback. 
Bei mir wird keine Error 500 Seite erzeugt. Es erscheint nun einleuchtend, dass das Fenster nicht geschlossen wird. Wir warten sicherlich darauf, dass die Meldung auf der Seite erscheint, dass die PQ erzeugt wurde, bevor wir das Fenster schließen.
Wird die PQ denn überhaupt erzeugt?
Kannst du mal versuchen eine ähnliche PQ manuell zu erzeugen? Kommt dann auch die Error 500 Seite?

**Comment by 2Abendsegler** [comment]
Es gibt auch mindestens zwei Fehlermeldungen im Forum wo es auch darum geht dass bei der Erzeugung einer PQ dieser Fehler erzeugt wird.
https://forums.geocaching.com/GC/index.php?/topic/387656-when-i-attempt-to-create-a-pocket-query-i-get-a-500-error/#comment-6061990
Der folgende Beitrag ist sogar von dir.
https://forums.geocaching.com/GC/index.php?/topic/389265-error-500-travel-bug-pages/&do=findComment&comment=6073701

**Comment by 2Abendsegler** [comment]
Ich wollte auch zuerst auf einen Fix verzichten, letztlich werden sich Betroffene aber in den meisten Fällen gar nicht melden und den GClh beschuldigen, wir ja auch zuerst, und auf GS warten bringt hier wohl nichts. Wenn wir die Seite identifizieren können, könnte ich das als zusätzliches Kriterium zum Schließen des Fensters einbauen. 

Kann man die Seite an der url erkennen oder an etwas anderem?

Was mir gerade noch einfällt. Theoretisch könnte es auch schon auf der ersten Seite zu einem solchen Error kommen, oder? In dem Fall würden wir das dann bereits als Kriterium zum Schließen nehmen. Das wäre natürlich blöd. Und richtig viel Aufwand reinstecken um sich die Abfolge der Seiten zu merken, will ich eigentlich nicht. 
Weiß jetzt nicht so recht.

**Comment by capoaira** [comment]
Der Error 500 wurde vor ein paar Wochen von GS gefixt und der PQ-Splitter läuft wieder durch.
