### ISSUE TITLE
[PQ-Splitter] Add information on how to change pop-up blocker settings on Project-GC's PQ splitter page.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2234]
### Describe the solution you'd like

Add information on how to change pop-up blocker settings on Project-GC's PQ splitter page.

For browser Firefox: https://support.mozilla.org/kb/pop-blocker-settings-exceptions-troubleshooting
For browser Chrome: https://support.google.com/chrome/answer/95472

**Comment by 2Abendsegler** [comment]
![grafik](https://user-images.githubusercontent.com/22332216/195582371-45d9bd24-42c1-496e-afa6-9fb2933c1bd5.png)

**Comment by capoaira** [comment]
merged with #2235
