### ISSUE TITLE
Mails/message form in new window

### ISSUE THREAD

**Issue by MarcusBi** [2Abendsegler/GClh#224]
Add an option to **Mail / Message form** block in configuration:

[ ] open mail/message form in new window

If checked, the mail/message form will open in a new window.

**Comment by MarcusBi** [comment]
Ich kann nach wie vor hier leider weder Label setzen, noch Zuweisungen tätigen... :(

> Bitte mir zuweisen

**Comment by 2Abendsegler** [comment]
Ich weiß nicht, ob wir das so sicherstellen können. Was ist denn, wenn jemand beispielsweise einen Link zum Mailen aus der Linklist anwählt, oder wenn irgendwo ein Standardlink zum Mailen angewählt wird. 

Vielleicht wäre es besser auf die Icons zu setzen, also "Show mail link beside usernames" und "Show message link beside usernames", um dort dann einen Parameter dazuzuhängen.

**Comment by 2Abendsegler** [comment]
... Womöglich ist das nicht mal eben schnell gemacht.

**Comment by MarcusBi** [comment]
Und wenn wir einfach dazu schreiben, dass diese Feature nur für einen Klick auf die Mail / Message-Icons gilt (falls aktiviert)?

**Comment by 2Abendsegler** [comment]
Dann mach mal. Obs geht müssen wir am Ende sehen.

**Comment by MarcusBi** [comment]
Completed!
![geocaching _ your profile - mozilla firefox 2017-03-15 16 46 58](https://cloud.githubusercontent.com/assets/23725271/24031890/65fedcae-0ae5-11e7-8eb2-29f5f920e8db.jpg)

**Comment by 2Abendsegler** [comment]
Moin,
ich habe gerade den Endtest gemacht. Funktional war alles Top!
Bei den Bezeichnungen der Parameter habe ich noch kleine Änderungen vorgenommen, insbesondere anstatt "new window" heißt es jetzt "new tab". 
Wenn Du nochmal schauen möchtest, das aktuelle Script steht in der Branch collector.

**Comment by MarcusBi** [comment]
N’Abend,

passt alles…bis auf zwei Fehler die ich schon eingebaut habe: im Hilfetext muss es in beiden Fällen natürlich heißen „…will open in a new tab“ (anstatt "an new tab“).

LG,
   Marcus aka Herr Ma
