### ISSUE TITLE
[Public Profile] Replace privacy text links by Icon link

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2240]
### Is your feature request related to a problem? Please describe

The links are way too present on the geocache view. I often click on them instead of the view all link

### Describe the solution you'd like

Hide the Links or make them smaller (maybe only the Icon as link)

### Additional context

The setting has to be set on `false` by default

**Comment by 2Abendsegler** [comment]
> Hide the Links or make them smaller (maybe only the Icon as link)

Both ok. If smaller then only the icon as link, yes. Please decide.

> The setting has to be set on `false` by default

👍

**Comment by capoaira** [comment]
Smaller icon is maybe more consistent to the other buttons

**Comment by 2Abendsegler** [comment]
Merged with #2262.

**Comment by 2Abendsegler** [comment]
@capoaira 
Da ist uns aber was durch die Lappen gegangen. 😅
Wenn ich ein fremdes Profil anwähle dann gibt es einen Error.
Kannst du bitte noch mal danach sehen.

**Comment by 2Abendsegler** [comment]
Merged with #2262 and #2270.

**Comment by DieBatzen** [comment]
Wenn der About-Teil des Public Profile (https://www.geocaching.com/account/settings/profile#ProfileFormRowBiography) leer ist, gibt es noch einen Fehler, da dann kein Privacy-Hinweis vorhanden ist.
Das gilt im eigenen und auch in anderen Profilen.

**Comment by capoaira** [comment]
Danke für den Hinweis. Fix kommt sofort....
