### ISSUE TITLE
[View/Edit Log] Scripts sometimes add strange things in logs.

### ISSUE THREAD

**Issue by anvanlaer** [2Abendsegler/GClh#2244]
### Describe the bug

I noticed this before, but today decided to do some small investigations.  In one of my friends logs i noticed this: 
![image](https://user-images.githubusercontent.com/4437672/201538304-6eca7766-616d-47b3-889d-f1a1dd5b04a6.png)
When i load the log into another browser, or chrome without the script loaded.  It displays like this
![image](https://user-images.githubusercontent.com/4437672/201538494-58d43fdf-7c28-46a2-bf27-e6d21485fd6d.png)
Is this a bug? How can i solve this?

### OS

Windows

### Browser

Chrome

### GClh Version

0.12

**Comment by 2Abendsegler** [comment]
Hi,
does the wrong display come with the Firefox browser?
Can you please give us a link so we can check it.
Thanks

**Comment by anvanlaer** [comment]
This is a log for the example https://www.geocaching.com/seek/log.aspx?LUID=0dbd2386-90ef-4d1f-bc77-88e160fae7b1

**Comment by 2Abendsegler** [comment]
I can still understand that in the cache listing, because we prepare the log text there ourselves. Here in the log view, however, we shouldn't do anything with the log text, dubious.

Thanks for reporting the bug.

**Comment by 2Abendsegler** [comment]
The correction comes with the new version in some days. 

---
Merged with #2251
