### ISSUE TITLE
[Cache Listing] After pressing the reset button, dynamic reloading of logs no longer works.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2252]
### Describe the bug

[Cache Listing] After pressing the reset button, dynamic reloading of logs no longer works.

`4. (1.1) Dass nach dem Drücken des Reset-Buttons das dynamische Nachladen nicht mehr funktioniert ist ein Bug.`
See also item 4. of https://github.com/2Abendsegler/GClh/discussions/2246#discussioncomment-4220548

### OS

Windows

### Browser

Firefox

### GClh Version

0.12

**Comment by DieBatzen** [comment]
Das könnte ich übernehmen, sehe aber gerade, dass der Staus bereits auf `in progress` sitzt.
Soll ich oder hast du den Fix bereits in Arbeit?

**Comment by 2Abendsegler** [comment]
Ja, du kannst das gerne übernehmen, ich bin tatsächlich noch nicht dazu gekommen. Ich habe dir das Issue zugeordnet.

**Comment by 2Abendsegler** [comment]
Merged with #2257
