### ISSUE TITLE
[Cache Listing] Possible unneeded (and dangerous) call to append upvotes to logs

### ISSUE THREAD

**Issue by DieBatzen** [2Abendsegler/GClh#2258]
### Describe the bug

In function `gclh_load_dataHelper` there's a possible unneeded (and dangerous) call to `unsafeWindow.appendUpvotesToLogs`:
> line 8281:
    if (isUpvoteActive) {
       unsafeWindow.appendUpvotesToLogs(log_ids);
       updateUpvoteEvents(logs);
   }

Is this call really required?
The upvote info is already fetched by `getUpvoteData()` and stored in logs before:
> line 8264:
    // Add Great story / helpful data to logs. Give starting index to the function, so it knows what index has to be updated.
   if (isUpvoteActive) getUpvoteData(all_ids,((z-1)*100));

An additional call itself wouldn't hurt, but for calls with more than approx. 160 log IDs the Groundspeak server throws an error:
> 404 (Not Found)

### To Reproduce

1. Go to GCLH settings, sections `Logs`, parameter `Show at least x logs`
2. Set the value to 200 in order to show the first 200 logs in every cache listing
3. Open a cache listing with approx. 200 logs (e.g. https://coord.info/GC8XWTC)
4. Open console and observe a 404 error from call `https://www.geocaching.com/api/proxy/web/v1/Geocaches/logs/upvote`

If you reduce the value to something < 150 all is good.
This seems to be an undocumented restriction in the GS WebAPI.

### Expected behavior

Call to `https://www.geocaching.com/api/proxy/web/v1/Geocaches/logs/upvote` shouldn't result in an error.

### OS

Windows

### Browser

Chrome

### GClh Version

0.12.1

### Additional context

There are two possible solutions:

1. If this call isn't necessary, delete it
2. Otherwise split the call to `https://www.geocaching.com/api/proxy/web/v1/Geocaches/logs/upvote` in chunks of 100 log IDs:
> let floor = Math.floor(log_ids.length/100),
	rest = log_ids.length % 100;
for (let i=0; i<floor; i++) {
	unsafeWindow.appendUpvotesToLogs(log_ids.slice(i*100, (i+1)*100));
}
unsafeWindow.appendUpvotesToLogs(log_ids.slice(runs*100, rest));

Exactly the same is by the way also valid in function `gclh_dynamic_load`, line 7777 (same call sequence).

**Comment by 2Abendsegler** [comment]
@DieBatzen 

Super gefunden! Vielen Dank.
Und du hast völlig recht, die Upvotes werden bereits an anderer Stelle geladen. Das zusätzliche Laden wurde wohl nur eingebaut, weil die Upvotes zum Zeitpunkt der Anzeige der Logs noch nicht immer vorhanden sind. Gleiches gilt auch für die dynamische Anzeige der Logs beim Scrollen, wenn man nur schnell genug nach unten scrollt. 

Es werden zuerst alle Logs geladen. Anschließend werden alle Upvotes geladen und gleichzeitig werden bereits die Logs zur Anzeige gebracht. Das macht auch Sinn, damit wir möglichst schnell die eigenen Logs angezeigt bekommen. 

Lösung:
Das "dubiose" Coding fliegt raus und wir prüfen nach dem Laden der einzelnen Upvotes ob das entsprechende Log bereits angezeigt wird und ändern die Anzeige gegebenenfalls ab. 

Eine Rohfassung funktioniert. Ich will die Tests aber lieber in ausgeschlafenem Zustand durchführen.

Ich hoffe ich komme morgen dazu einen PR zu erzeugen. Wäre super, wenn du das dann auch noch zusätzlich testen könntest. 😊

**Comment by DieBatzen** [comment]
Klar, mache ich gerne.

**Comment by 2Abendsegler** [comment]
Merged with #2263.
