### ISSUE TITLE
[Browse Map] Sorting of map layers doesn't work in Chrome

### ISSUE THREAD

**Issue by DieBatzen** [2Abendsegler/GClh#2259]
### Describe the bug

If you enable GCLH setting [Sort map layers in map](https://www.geocaching.com/my/#GClhShowConfig#a#settings_sort_map_layers) then the map layers are still in default order in Chrome.

In Firefox the sorting works.

### To Reproduce

1. Enable GCLH setting `Map - Sort map layers in map`
2. Open Browse map in Chrome and observe that the map layers are still in default order

### OS

Windows

### Browser

Chrome

### GClh Version

0.12.1

**Comment by 2Abendsegler** [comment]
Merged with #2260
