### ISSUE TITLE
[Search Map] Show found caches at corrected coordinates

### ISSUE THREAD

**Issue by DieBatzen** [2Abendsegler/GClh#2274]
### Is your feature request related to a problem? Please describe

Found caches that do have corrected coordinates are always displayed at their original position.

It would be nice to have a possibility to display them at their corrected coordinates (as they already do as long as they're unfound).

### Describe the solution you'd like

An optional button to switch cache display between original and corrected coordinates.

**Comment by 2Abendsegler** [comment]
Super! 😄

---
Merged with #2275.
