### ISSUE TITLE
Auto set for checkboxes on geocache edit

### ISSUE THREAD

**Issue by king-ton** [2Abendsegler/GClh#230]
For owner of geocaches (like me) it would be a good feature that the checkboxes on geocache edit page will automatically be set. I implemented it for my own in the old script and it saves a lot of time ( and some annoy ;) ).

**Comment by 2Abendsegler** [comment]
Hallo,

kannst Du bitte mal einen oder mehrere Screenshots hier reinhängen und kennzeichnen was wir automatisch setzen sollen.

Können wir womöglich etwas aus Deinem fork des GClh Originals und Deinen Änderungen übernehmen? 
Oder möchtest Du es vielleicht sogar selbst hier einbauen? 

LG Frank

**Comment by king-ton** [comment]
Hi Frank,

wenn ich morgen Abend dazu komme, baue ich meinen Code mal einen und pushe es in eine neue branch.

Beste Grüße
Toni

**Comment by 2Abendsegler** [comment]
Ok, lass Dir ruhig etwas Zeit, wir planen die nächste Version erst für Ende nächster Woche.

**Comment by 2Abendsegler** [comment]
Hallo Toni,

ich habe mir etwas schwer getan bei der Bezeichnung und Beschreibung des Parameters. Kannst Du hier gerade noch mal drüberschauen? Ist das ok oder soll ich noch etwas anpassen.

![settings_hide_cache_approvals01](https://cloud.githubusercontent.com/assets/22332216/24069834/ec851d48-0bb1-11e7-93a9-d6ce86a857a3.jpg)

![settings_hide_cache_approvals02](https://cloud.githubusercontent.com/assets/22332216/24069835/f4aa0646-0bb1-11e7-9bcc-59eac38ee471.jpg)

LG Frank

**Comment by 2Abendsegler** [comment]
Ich habe es im Config nochmal geändert. Mein Englisch ist echt super :))

![settings_hide_cache_approvals03](https://cloud.githubusercontent.com/assets/22332216/24071037/5ebd73c6-0bc9-11e7-9024-098580108274.jpg)

**Comment by PontiacCZ** [comment]
Good idea!
