### ISSUE TITLE
Fixed "Submit changes"-button on geocache edit page

### ISSUE THREAD

**Issue by king-ton** [2Abendsegler/GClh#231]
If an owner edit his geocache he always has to scroll down to submit his changes. It would be a nice feature if the button is fixed on the screen like the top scroll button on cache pages.

Thanks that you continue the project!

**Comment by 2Abendsegler** [comment]
Hallo,

meine erste Idee wäre etwas anders. Wir haben bereits Funktionalität am laufen, wo wir den Submit beispielsweise des Logs per F2 Taste ermöglichen. Die Tastenbezeichnung wird dann auch um F2 erweitert. Der vorhandene Parameter im Config heißt "Submit log, Pocket Query or Bookmark on F2". Schau mal im Log nach dem Button. Diesen Button kannst Du dann von überall auf der Seite mit F2 auslösen.

Wäre das eine Alternative?

LG Frank

**Comment by king-ton** [comment]
Ich denke die Idee ist sogar noch besser! Da hängt nicht dieser Button sinnlos herum ^^
Allerdings macht die Funktionalität mit F2 nur Sinn, wenn die beiden Haken direkt über dem Submit-Button gesetzt sind ( s. Ticket #230 ). Sonst würde es jedes Mal zu einem Fehler kommen.

Beste Grüße
Toni

**Comment by 2Abendsegler** [comment]
Ok, das schauen wir uns an.

**Comment by 2Abendsegler** [comment]
**Infosammlung:**

Editing Geocache:
- URL: https://www.geocaching.com/hide/report.aspx?guid=...
- Checkbox: Yes. I have read and understand the guidelines for listing a cache.: id="ctl00_ContentBody_chkUnderstand" (siehe #230)
- Checkbox: Yes. I have read and agree to the terms of use agreement: id="ctl00_ContentBody_chkDisclaimer" (siehe #230)
- "Submit Button": id="ctl00_ContentBody_btnSubmit"

Editing attributes: Vermutlich wäre hier ein F2 auch hilfreich.
- URL: https://www.geocaching.com/hide/attributes.aspx?WptID=...
- "Update Attributes": id="ctl00_ContentBody_Attributes_btnUpdate"

Add a New Waypoint: Vermutlich wäre hier ein F2 auch hilfreich.
- URL: https://www.geocaching.com/hide/wptlist.aspx?DS=1&RefWptID=...
- "Create Waypoint": id="ctl00_ContentBody_WaypointEdit_uxSubmitIt"

**Comment by 2Abendsegler** [comment]
<ul><li>New: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/231">#231</a>] Enable save with F2 key in hide cache process. This include the complete hide cache process with all of the buttons "Continue", "Save and Preview" and "Submit changes" of the create and the change functionality.<br>  
<br></li></ul>
