### ISSUE TITLE
[Certitude] Copy to clipboard feature not longer available and stay anonymous does not work if signed in by certitudes.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2315]
### Describe the bug

[Certitudes] Copy to clipboard feature not longer available and stay anonymous does not work if signed in by certitudes.

Certitudes Seite wurde komplett überarbeitet.

### OS

Windows

### Browser

Firefox

### GClh Version

actual master

**Comment by ChristianGK-GC** [comment]
Ich bin schon dran.

**Comment by 2Abendsegler** [comment]
Ich habe die Entwicklung bereits fertig gestellt. Ich habe den Status in progress schon vor gut 3 Tagen gesetzt.

Da die raw.githubusercontent.com Links nur noch mit bis zu 24 Stunden zeitverzögert ankommen, werde ich die Anpassungen erst zusammen mit anderen hochladen. Die müssen aber zuerst noch fertig gestellt werden.

**Comment by 2Abendsegler** [comment]
Ich habe eine [temporäre Branch](https://github.com/2Abendsegler/GClh/tree/Certitude) für dich erzeugt, für den Fall dass du drüber schauen möchtest. Dort sind aber auch schon andere Anpassungen enthalten. Die Branch wird nicht gemerged, Anpassungen daran machen also keinen Sinn.

**Comment by ChristianGK-GC** [comment]
Danke dir für alles. Ich schaue es mir heute Abend an.

**Comment by ChristianGK-GC** [comment]
Habs gestern ganz vergessen zu schreiben.
Sieht gut aus! Top.

**Comment by 2Abendsegler** [comment]
Merged with #2342
