### ISSUE TITLE
[New Dashboard] If there are more than ten unpublished hides, the display no longer works correctly.

### ISSUE THREAD

**Issue by ChristianGK-GC** [2Abendsegler/GClh#2354]
### Describe the bug

Ich denke das verhalten liegt kommt nur vor, wenn es mehr als 10 Unpublished Hides sind.
Ich kann leider nichts archivieren um es zu testen.
Die markierten sind doppelt.
In der Console habe ich keine Fehler.
![grafik](https://user-images.githubusercontent.com/24353480/219334506-ad32e5fb-451b-4847-b32d-eeee908ee43a.png)
![grafik](https://user-images.githubusercontent.com/24353480/219341929-8a89cb7f-cd00-45f8-a436-40b6564508e8.png)

### OS

Windows

### Browser

Firefox

### GClh Version

0.14.2

**Comment by ChristianGK-GC** [comment]
Ich habe den Wert nun auf 20 gesetzt. Dann kommt es zu dem Fehler im Dashboard nicht mehr.
Geht man wieder zurück auf die 10, so ist der Fehler wieder da.
![grafik](https://user-images.githubusercontent.com/24353480/219343350-44cc8766-f9fd-4255-a81f-e766a0bb442f.png)

**Comment by 2Abendsegler** [comment]
Danke fürs Melden des Fehlers!

Die Ermittlung der unveröffentlichten Caches und Events läuft nun nicht mehr über die Webseite https://www.geocaching.com/play/owner/unpublished sondern wird über die API durchgeführt. Das ist schneller und funktioniert nun mit bis zu 100 Caches und mit bis zu 100 Events. Wer mehr auf einen Schlag aufmachen will, ist selbst Schuld. Hier wollte ich keine weitere Arbeit rein stecken.

Das Ganze ist nun auch viel schneller.

Kannst du bitte mal drüber schauen. Nur kurz, ob dir irgendetwas auffällt, was noch nicht so super ist. Ich habe bereits ausführlich getestet. Danke.

**Comment by 2Abendsegler** [comment]
... Hier gibt es das Coding #2357.

**Comment by ChristianGK-GC** [comment]
Top! 100 sollten ja wohl auch dick reichen.

**Comment by 2Abendsegler** [comment]
Danke fürs drüber schauen!

---
Merged with #2357
