### ISSUE TITLE
[Event Listing] Show event time in 24 hours format.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2358]
### Describe the solution you'd like

Show event time in 24 hours format.

Event time in 12 hours format:
![Screen01](https://user-images.githubusercontent.com/22332216/219718205-786db32e-c5da-4fc7-b1a4-bcfeff6a7ff9.jpg)

Event time in 24 hours format:
![Screen02](https://user-images.githubusercontent.com/22332216/219718225-961146ce-8f0a-4cf4-8fec-678c0d6ff714.jpg)

Settings: Listing - Listing Header:
![Screen03](https://user-images.githubusercontent.com/22332216/219718012-cc6c6fe6-112e-489f-bf4b-6d675b3cfc80.jpg)
https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_eventtime_with_24_hours

The start time and end time of an event are generated on the website using the language in which you are signed in. In English, the preferred language when using the GClh, but also in some other languages, the start time and end time of an event is shown in 12 hour format with AM and PM. If you want to change it to a 24 hour format, you can activate this parameter.

**Comment by capoaira** [comment]
merged with #2359
