### ISSUE TITLE
[Cache Listing] Build dropdown list with possible layers for "Google Maps" in right navigation area.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2365]
### Describe the solution you'd like

Build possible layers for "Google Maps" pop up in listing with the layers Google Maps, Google Maps Satellite and others.
See also discussion #2363.

**Comment by 2Abendsegler** [comment]
I tried to build the Google Maps pop up for the listing. Unfortunately, there doesn't seem to be a way to add additional waypoints, like it is for example for the Flopp's Map links. You therefore only have the listing coordinates on which the map is then centered.

Or we make driving directions with intermediate points like we do it on the other pop ups in the listing with routing functionality for example with the openrouteservice.

**Comment by olilesp** [comment]
I think it's better to have  the listing coordinates (maybe the corrected ones when there's a mystery cache) on the map rather than driving directions with intermediate points.

**Comment by 2Abendsegler** [comment]
> I think it's better to have the listing coordinates (maybe the corrected ones when there's a mystery cache) on the map rather than driving directions with intermediate points.

That's exactly what you already have below with the link "Show area on Google Maps" above the minimap. And with GME you can display all waypoints in the Browse Map and then select the Google Maps layer there. Actually, that should be enough, additional adjustments are not necessary in my opinion.

**Comment by 2Abendsegler** [comment]
We will not implement this feature. 
Close issue.
