### ISSUE TITLE
[FriendList] Problems with counter and sorting

### ISSUE THREAD

**Issue by Herr-Ma** [2Abendsegler/GClh#2374]
### Describe the bug

At the moment the Friends page looks a bit disastrous:
- something must be completely mixed up in the summary
- sorting friends doesn't work anymore

But since the mapping doesn't work without the gcLittelHelper, Groundspeak seems to have screwed something up again. We should wait until the sorting works again and then check whether the numbers are still wrong.

Checked with and without active gcLittleHelper on
Firefox 110.0 
Edge 110.0.1587.50 

### OS

Windows, MacOS

### Browser

Firefox, Edge

### GClh Version

0.14.2, 0.14.3

**Comment by 2Abendsegler** [comment]
Moin,
ich hatte das Issue gestern auch schon im GS Forum gesehen.
https://forums.geocaching.com/GC/index.php?/topic/387973-friends-list-issue
Ja, warten wir zuerst mal auf die Lösung von denen.

**Comment by Herr-Ma** [comment]
Was du alles auf dem Schirm hast 😉 👍🏻

**Comment by capoaira** [comment]
Habe gerade noch einen kleinen "Bug" im Geoclub aufgeschnappt, der wohl auch mit diesem Issue zusammenhängt. Wir müssen her nichts tun, aber vielleicht gut zu wissen, falls andere die Fragen haben, oder den Fehler melden:
https://www.geoclub.de/forum/t/freundesliste-auf-gc-com-fundzahlen-seit-letztem-reset-fraglich.82427/
Die Labs werden jetzt zu den Funden gezählt, das heißt, dass der Counter einmalig ein falsches + anzeigt, da die Labs dazugerechnet werden.

**Comment by Herr-Ma** [comment]
Das macht Sinn! Ich vermute mal, wenn GS ihre Seite repariert haben und die Sortierung wieder funktioniert, ist hier nichts weiter zu tun (außer einmalig "Reset Counter" zu drücken, damit die Zähler wieder auf Stand sind).

**Comment by Herr-Ma** [comment]
Sortierung funktioniert wieder, Zähler auch - ich schließe daher.

Sorry für die Verwirrung ;-)

**Comment by 2Abendsegler** [comment]
Alles gut, das Issue gab es zu recht. Danke fürs Beobachten und fürs Schließen. Solche Issues sind mir die Liebsten. 😉
