### ISSUE TITLE
[Global] Failed to execute 'atob' on 'Window': The string to be decoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2375]
### Describe the bug

GClh no longer starts. 
Error message in the console.
![Unbenannt](https://user-images.githubusercontent.com/22332216/221432313-d72c981d-1e6b-48a3-88f4-334c529d3c01.JPG)

According to user he just changed templates for logs. After that it didn't work anymore.
Details im geoclub: https://www.geoclub.de/forum/t/gc-little-helper-ii-ab-v0-11.81650/post-1350595

### OS

MacOS

### Browser

Chrome

### GClh Version

0.14.3

**Comment by 2Abendsegler** [comment]
@capoaira 
Danke, dass du dir das Teil geschnappt hast!

**Comment by capoaira** [comment]
Gerne :)

Ich hatte bei einem Uni-Projekt schon Probleme mit dem Zeichensatz, da konnte mir ChatGPT helfen. Hier hoffentlich auch 😅

**Comment by 2Abendsegler** [comment]
Fall du noch einen Versuch machst, könntest du die Version hoch zählen, also so was wie 0.14.3.1 , damit wir sicher sind, dass mit der richtigen Version getestet wurde.

**Comment by 2Abendsegler** [comment]
Kannst du bitte die Änderung noch als PR rüber schieben. Ich mache dann eine neue Version fertig.
Danke für die Behebung des Problems, super gemacht! Hätte ich vermutlich nicht beheben können.

**Comment by capoaira** [comment]
Ich bin mir noch nicht sicher, ob das das Problem wirklich behebt. Da ich einen `try-catch` Block hinzugefügt habe, kann es auch sein, dass Zyklotrop nur gesehen hat, dass das Script wieder läuft, ohne die Funktion zu testen. Ich würde daher noch auf eine Antwort warten.
Da UFT-8 bei den meisten Standard ist, ist dieser Bugfix auch nicht so dringend.

**Comment by 2Abendsegler** [comment]
Wenn ich ehrlich bin, verstehe ich das Problem nicht. Wenn ein Listing aufgerufen wird, wird das beanstandete Coding doch gar nicht ausgeführt. Wieso kommt es dann zu dem Fehler in der Konsole?
Ich bin mir nicht sicher, ob wir nochmal eine Antwort bekommen werden.

**Comment by 2Abendsegler** [comment]
@capoaira
Ich nochmal, sorry. 

Ich habe Bedenken, dass der GClh den Tampermonkey Speicher kaput macht und das Script dann nicht mehr richtig anläuft, so dass wir über Änderungen am Script nichts mehr bewirken können. Wenn das so ist, und eine Lösung darauf hinaus läuft, dass die Anwender den Tampermonkey Speicher löschen müssen, dann wären auch die wenigen Anwender, die kein UTF-8 verwenden, zu viel. Zyklotrop hat wohl den Tampermonkey Speicher vom GClh gelöscht. Das ist ungünstig, wir wissen jetzt nicht, warum das Script bei ihm wieder läuft, wegen deinen Änderungen oder wegen dem gekillten Speicher.

Ich verstehe das Problem nicht, wie ich gestern schon geschrieben habe. Die Fehlermeldung in der Konsole kam auch im Listing, obwohl das Coding im Listing überhaupt nicht angesprungen wird, weil es dort kein bannerartiges Teil gibt. Das war im Geoclub noch bevor du dich eingeschaltet hast. Ob bei den späteren Tests von Zyklotrop noch ein Listing verwendet wurde, kann ich nicht beurteilen.

Wenn die Möglichkeit besteht, dass ich mit meinen Bedenken richtig liege, dann sollten wir so schnell wie möglich eine neue Version raus hauen. Nicht unbedingt mit einer Lösung. Wir können das Feature auch deaktivieren, so dass kein weiterer Schaden entstehen kann. Anschließend könnten wir in Ruhe überlegen, was wir machen.

Wie schätzt du meine Bedenken ein?

**Comment by capoaira** [comment]
Ich denke nicht, dass es am Speicher liegt. Die Exception müsste eigentlich schon fliegen, bevor es in den Speicher geschrieben wird. 

Aber wir haben ja eine Antwort erhalten und die Konsole ist leer. Leider ist das ein Screenshot der Cacheseite und nicht des Dashboards.

Ich mache den PR, dann einfach hoffen, dass das Problem wirklich behoben ist.

**Comment by 2Abendsegler** [comment]
> Leider ist das ein Screenshot der Cacheseite und nicht des Dashboards.

Was wäre beim Dashboard besser?

**Comment by 2Abendsegler** [comment]
Merged with #2376

**Comment by capoaira** [comment]
> > Leider ist das ein Screenshot der Cacheseite und nicht des Dashboards.
> 
> Was wäre beim Dashboard besser?

Wie du schon geschrieben hast, ist kein blauer Banner im Cachelisting. Aber da er den Fehler auch im Cachelisting hatte, ist es wohl egal.
