### ISSUE TITLE
Friends page: "Last check" stuck

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#238]
Hello,
I have noticed that the "Last check" information on "Your friends" page always calculates the time difference from 1. 1. 1970 1:00:00. So probably an issue with saving the timestamp of the last made check.

**Comment by 2Abendsegler** [comment]
Hi,

can you please post a screenshot of your friends page, so I can see the time output and your first friends?

I think you could know the firefox console? Please press shift, Strg and Q on your friends page. The console open. Please choose Console and below JS and Logbook. Please post a screenshot, if something is displayed there.
![konsole](https://cloud.githubusercontent.com/assets/22332216/24075716/d644447c-0c20-11e7-99c4-3cda8e03ccd5.jpg)

**Comment by PontiacCZ** [comment]
OK, here's the screenshot 2-in-1. :) 

BTW SHIFT+CTRL+Q kept opening new tab with Youtube (for whatever reason), so I checked Google and SHIFT+CTRL+K opened the console for me.

![obrazek](https://cloud.githubusercontent.com/assets/9153595/24075884/4e55a84a-0c24-11e7-8429-b86fa7343609.png)

**Comment by 2Abendsegler** [comment]
Perhaps firefox in Czech have other key combinations, I don't know.

I see you have a VIP, but could it be, that you have deleted all your VIPs recently? 

Please press the "Reset counter" button. This should save the last checked data manually. Perhaps you have to do a page refresh. In another case it has helped. You are not the first one with this problem. But we do not know the exact reason.

If it couldn't help, please deactivate all other scripts, go to friends page and call the console again. I need only the console data now, if there are data.

**Comment by PontiacCZ** [comment]
> "...could it be, that you have deleted all your VIPs recently?"

No, I have not. 
On my home PC I disabled the original GClh, installed Gclh II and set it up from scratch (about month ago I guess).
On my work PC I used the export/import function to transfer the settings to Gclh II.

On both PCs Gclh II calculates the last check from 1. 1. 1970 1:00:00.



> Please press the "Reset counter" button. This should save the last checked data manually. Perhaps you have to do a page refresh.

OK, just tried it. The last check timestamp changed to 19. 3. 2017 12:27:34 and has kept on this value since (during all following page loads). Conclusion: the last check timestamp seems to only get set after manually clicking the "Reset counter" button.

**Comment by MarcusBi** [comment]
Have you set the config switch "Reset difference counter on friendlist automatically"?

**Comment by PontiacCZ** [comment]
Yes, it came set (checked) as a default and I have not changed it on either PC.

![obrazek](https://cloud.githubusercontent.com/assets/9153595/24093028/258f72f4-0d52-11e7-91d6-83d8cb43a9c7.png)

Right now I am experimenting with my work PC, there is 1. 1. 1970 1:00:00 as the last check as well. I clicked "Reset counter" and now the timestamp keeps on 20. 3. 2017 9:47:55 no matter how frequently I refresh the Friends page.

Gclh II 0.5.

**Comment by 2Abendsegler** [comment]
Hi,

MarcusBi has fixed the problem. 

We are expected to bring a new version next weekend, where the bug is corrected. But here is too an advance correction, you can use directly: 
https://raw.githubusercontent.com/2Abendsegler/GClh/master/temp/gc_little_helper_II.user.js

Best regards
Frank

**Comment by PontiacCZ** [comment]
I have installed the update from your link and tried to visit the Friends page a few times, I even restarted the browser. But the last check date stays at 20. 3. 2017 9:47:55 which got set using "Reset counter" yesterday.

**Comment by MarcusBi** [comment]
Thats correct! The last reset was yesterday and you will see the difference from the showing date until now.

The automatically reset funtion resets the counter only once a day (the first time you visit the friends page).
"...the difference counter at friendlist will automatically reset if you have seen the difference and if the day changed."

![grafik](https://cloud.githubusercontent.com/assets/23725271/24135652/58afdcdc-0e0b-11e7-8f87-7644e6597857.png)

The showing date/time is the time of the last reset which will be set on
- the time of the first call of the friends page (when automatically reset ist checked in config)
- manually reset with the "reset counter" button

Cheers, Marcus

**Comment by PontiacCZ** [comment]
Ahaaa, I overlooked this slight "wording" change. It works perfectly then. :) I apologize for this confusion and thank you for the fix. I consider this ticket solved so I am closing it.
