### ISSUE TITLE
[Log Forms] Show further cache infos cache type, difficulty and terrain in log forms.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2399]
### Discussed in https://github.com/2Abendsegler/GClh/discussions/2389

<div type='discussions-op-text'>

<sup>Originally posted by **ChristianGK-GC** April 13, 2023</sup>
Ich habe seit einiger Zeit bei mir eine kleine Erweiterung laufen. 
Vielleicht passt die auch in den GClh.
Ich habe immer vermisst, dass man sieht um was für einen Cache es sich handelt und welche Wertung der Cache hat.
Basierend auf den Infos packe ich unterschiedliche TBs zum Log dazu oder nicht.

![grafik](https://user-images.githubusercontent.com/24353480/231716364-5f71a9ee-7c0b-4293-abec-35d6a05eb5ce.png)

https://github.com/2Abendsegler/GClh/compare/collector...ChristianGK-GC:GClh:collector
</div>

**Comment by ChristianGK-GC** [comment]
Ich habe den PR macht.
https://github.com/2Abendsegler/GClh/pull/2405

**Comment by 2Abendsegler** [comment]
Super!

---
Merged with #2405 und #2406.

---
Ich habe noch ein paar Dinge geändert, insbesondere was die Aufbereitung betrifft, auch zu älteren Dingen. Und ich habe die title zu D, T und dem Cache Namen noch eingebaut. Und die Ausgabelänge des Cache Namens im neuen Log Formular habe ich variabel gemacht. Ich hoffe das passt alles. Eigentlich wollte ich das noch an dich zum Testen geben, dann hätte ich dieses Wochenende aber keine neue Version mehr raushauen können. Also, Mut zur Lücke. 😂
