### ISSUE TITLE
[Cache Listing] Open-Elevation macht Probleme hinter Proxy

### ISSUE THREAD

**Issue by ChristianGK-GC** [2Abendsegler/GClh#2409]
### Describe the bug

Ich bekomme seit Freitag immer mal wieder Fehlermeldungen bei der Elevation.
Der Fehler tritt aber nur auf, wenn ich hinter einem Proxy bin.

Object { readyState: 4, responseHeaders: "", finalUrl: "https://api.open-elevation.com/api/v1/lookup?locations=49.1778,10.84877|49.1778,10.84877", status: 0, statusText: "", responseXML: undefined, responseText: "", response: undefined, context: {…}, DONE: 4, … }
GC little helper II.user.js:5241:37

GClh_LOG - https://www.geocaching.com/geocache/GC7NGA6: 
addElevationToWaypoints_GeonamesElevation():

- Error:
```
<html><head><title>504 Gateway Timeout</title></head>
<body><h1>Gateway Timeout</h1>
<p>Server error - server 188.40.33.19 is unreachable at this moment.<br><br>Please retry the request or contact your administrator.<br></p>
</body></html>

```
- url: http://api.geonames.org/astergdemJSON?lats=49.1778,49.1778&lngs=10.84877,10.84877&username=gclh GC little helper II.user.js:20166:49

### OS

Windows

### Browser

Firefox

### GClh Version

0.14.6

**Comment by ChristianGK-GC** [comment]
Problem scheint behoben zu sein. Hatte heute kein Problem mehr.

**Comment by 2Abendsegler** [comment]
@ChristianGK-GC
Moin,
ist das Problem noch mal aufgetaucht. Falls nicht, könnten wir das Issue eigentlich schließen, oder?

**Comment by ChristianGK-GC** [comment]
Jo kann zu gemacht werden.
