### ISSUE TITLE
[Log Forms] Markdown smilies have been changed.

### ISSUE THREAD

**Issue by Mitchsa** [2Abendsegler/GClh#2411]
### Describe the bug

Bei den GC Logs werden die Smilies nicht mehr richtig dargestellt ???

### OS

Windows

### Browser

Firefox

### GClh Version

0.14.6

**Comment by capoaira** [comment]
Moin, danke für das Melden des Bugs. Leider können wir mit einer Meldung wie dieser nichts anfangen. Bitte sage uns um welche Seite es sich handelt. Es gibt viele wo Logs angezeigt werden. Auch ein Screenshot wäre hilfreich.

**Comment by Mitchsa** [comment]
Moin, hier ein Ausschnitt von geocaching.com - alte Logseite.
habe alle Smilies in Reihenfolge ins Log eingefügt - beim Preview das Ergebnis.
Hat da GS was am Aussehen geändert, oder?

![GCLH1](https://user-images.githubusercontent.com/27776456/236983939-03986c11-1ffa-4afb-9b12-19ab849291d2.JPG)

Hier noch die "neue" Logseite. Gleiches Ergebnis

![GCLH2](https://user-images.githubusercontent.com/27776456/236984509-4327845e-902e-45a2-aa2f-f5ed82712ee8.JPG)

So erscheinen die dann auch in den Logs :(

**Comment by 2Abendsegler** [comment]
Merged with #2422 and #2425
