### ISSUE TITLE
[Cache Listing] VIP-List "Not Found" does not work on Webcam Caches

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2412]
### Describe the bug

The List shows all VIPs how hasn't found the Cache. In case of a Webcam Cache, it shows all VIPs. So maybe we just check for "Found it"?

### OS

Windows

### Browser

Firefox

### GClh Version

current version

**Comment by 2Abendsegler** [comment]
Habe das Icon 11 für Webcam Caches als Found integriert. Das war bisher nicht vorgesehen. Dubios dass es jetzt erst aufgefallen ist. Habs getestet für normale VIP List und für die lange VIP List. Sollte also alles passen. 

---
Merged with #2415
