### ISSUE TITLE
[TB Listing] Button to copy TB Code in trackable listing to clipboard

### ISSUE THREAD

**Issue by mibe** [2Abendsegler/GClh#2413]
### Describe the solution you'd like

I'd like to have a function to copy the TB code on the TB page to clipboard, just like on the cache listing, cache log or TB log page. Basically the same as #695 just for TB's.

**Comment by 2Abendsegler** [comment]
A button to copy the TB code on the TB listing to clipboard should be possible. 
I don't have much time at the moment, it will probably take a while.

**Comment by capoaira** [comment]
merged with #2427

**Comment by mibe** [comment]
Funzt, Danke!
