### ISSUE TITLE
[Cache Listing] VIPs are not displayed

### ISSUE THREAD

**Issue by Fassenachterin** [2Abendsegler/GClh#2417]
### Describe the bug

Habe in meiner Freundesliste https://www.geocaching.com/my/myfriends.aspx verschiedene Cacher als VIP angeklickt.
Beim Mega in Köln "GIFF 2023 - Janz jroß Kinema Directors Cut" https://coord.info/GCA7RDH haben sich lt. Logbuch und Auswahl "Logeinträge deiner Freunde" drei Freunde angemeldet, von denen ich einen zuvor als VIP markiert habe.
Im Listing wird mir in der rechten Spalte zwar die VIP-Liste angezeigt, aber sie ist leer. Dort müsste der eine Nick, den ich als VIP markiert habe, angezeigt werden.
Auch wird mir bei den Logs von Caches bzw. Will Attend-Logs im Listing neben dem Namen kein VIP-Icon angezeigt. Darüber konnte ich in einer früheren Version Cacher zu meiner VIP-Liste hinzufügen.
In meinem Dashboard https://www.geocaching.com/account/dashboard werden mir meine VIPs angezeigt, aber nicht im Listing.
Was ist die Lösung? Userfehler oder Programmfehler?

### Expected behavior

Im Listing sollte bei den Logs neben dem Namen das VIP-Icon angezeigt werden.
Im Listing sollte in der rechten Spalte bei der VIP-Liste die Namen der VIPs angezeigt werden.

### OS

Windows

### Browser

Firefox

### GClh Version

0.14.6

**Comment by 2Abendsegler** [comment]
Hi,

danke für die Nachricht.
Ich kann das Problem im Moment noch nicht nachstellen. Eigentlich sollte die VIP-List zumindest auch den Owner und die Reviewer anzeigen, es sei denn du hast das ausgeschaltet. 

Welchen Browser nutzt du?

Lass uns mal ein paar Dinge ausprobieren, vielleicht können wir damit das Problem finden:
1. Kannst du bitte mal alle anderen Scripte und Add-ons ausschalten und dann nochmal testen?

2. Zeig uns bitte mal deine Einstellungen unter "Listing - VIP-Lists". Also in etwa so
![Unbenannt2](https://github.com/2Abendsegler/GClh/assets/22332216/f8f59bc8-ecaf-4ddb-9520-c74339b68923)

  
3. Zeig uns bitte mal die VIP-Lists im Listing. Also in etwa so
![Unbenannt](https://github.com/2Abendsegler/GClh/assets/22332216/e4c710df-927c-45cd-b387-50086a8e8717)

  
4. Kannst du bitte mal die Konsole aufrufen, gleichzeitig die Tasten Strg, shift und K drücken. Dort dann den Tab Konsole wählen. Also in etwa so
![Unbenannt3](https://github.com/2Abendsegler/GClh/assets/22332216/be9b2671-63d6-4d17-8a70-50c76011b1e1)
Interessant wären hier vor allem Fehler in rot, falls welche da sind.

LG
Frank

**Comment by 2Abendsegler** [comment]
...
5. Bitte auch mal die [Cookies](https://www.geocaching.com/account/settings/cookies) überprüfen. Hast du dort alle akzeptiert. Also in etwa so
![Unbenannt4](https://github.com/2Abendsegler/GClh/assets/22332216/82d62ce8-6adf-4519-8991-7b6d1dac9761)
Fast du nicht alle akzeptiert hast, dann ändere das bitte mal ab.

**Comment by Fassenachterin** [comment]
Hallo Frank,

 

nun komme ich endlich mal dazu, zu antworten, nachdem die Mail im Spam gefunden wurde, hier die relevanten Screenshots:

 



 

 



 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 





 

Ich hoffe, du weißt einen Rat.

Was mir auch auffiel:

Lade ich PQ hoch, werden auch die geladen von Caches, die ich längst geloggt habe, nicht nur die, die noch zu loggen sind.

 

Viele Grüße

Tanja (Fassenachterin)

 

 

 

Von: 2Abendsegler ***@***.***> 
Gesendet: Samstag, 19. August 2023 22:40
An: 2Abendsegler/GClh ***@***.***>
Cc: Fassenachterin ***@***.***>; Author ***@***.***>
Betreff: Re: [2Abendsegler/GClh] VIP werden nicht angezeigt (Issue #2417)

 

Hi,

danke für die Nachricht.
Ich kann das Problem im Moment noch nicht nachstellen. Eigentlich sollte die VIP-List zumindest auch den Owner und die Reviewer anzeigen, es sei denn du hast das ausgeschaltet.

Welchen Browser nutzt du?

Lass uns mal ein paar Dinge ausprobieren, vielleicht können wir damit das Problem finden:

1.	Kannst du bitte mal alle anderen Scripte und Add-ons ausschalten und dann nochmal testen?
2.	Zeig uns bitte mal deine Einstellungen unter "Listing - VIP-Lists". Also in etwa so
 <https://user-images.githubusercontent.com/22332216/261819261-f8f59bc8-ecaf-4ddb-9520-c74339b68923.JPG> 
3.	Zeig uns bitte mal die VIP-Lists im Listing. Also in etwa so
 <https://user-images.githubusercontent.com/22332216/261819248-e4c710df-927c-45cd-b387-50086a8e8717.jpg> 
4.	Kannst du bitte mal die Konsole aufrufen, gleichzeitig die Tasten Strg, shift und K drücken. Dort dann den Tab Konsole wählen. Also in etwa so
 <https://user-images.githubusercontent.com/22332216/261819433-be9b2671-63d6-4d17-8a70-50c76011b1e1.JPG> 
Interessant wären hier vor allem Fehler in rot, falls welche da sind.

LG
Frank

**Comment by 2Abendsegler** [comment]
Hallo Tanja,

irgendwie haben es deine Screenshots nicht bis hier her geschafft. Kannst du bitte die Screenshots nochmal hier bei GitHub direkt rein hängen? 

Zu deiner anderen Frage: 
Du meintest Drafts/Entwürfe, richtig? Es gibt seit einiger Zeit einen Bug beim Hochladen von Drafts. Eine Lösung scheint es noch nicht zu geben. Vielleicht schaust du dir den Beitrag im Forum mal genauer an, ich bin nur kurz drüber geflogen. https://forums.geocaching.com/GC/index.php?/topic/391803-recent-change-on-how-drafts-are-handled

LG

**Comment by 2Abendsegler** [comment]
Moin Tanja,
kannst du bitte noch die verloren gegangenen Screenshots nachliefern? Am Besten hängst du sie direkt in GitHub rein.
Danke und LG

**Comment by 2Abendsegler** [comment]
Tanja hatte am 02.10.2023 übers GC Nachrichten Center um Rat gefragt wie sie die Screenshots liefern kann.

Meine Antwort:

> Oct 2, 2023 11:00 PM
> Moin Tanja,
> 
> du kannst mir die Screenshots auch übers Nachrichten Center zukommen lassen. Ich hänge sie dann in GitHub.
> 
> Oder du kannst in dein Issue auf GitHub gehen, dort dann nach unten Scrollen und ganz unten deine neue Nachricht schreiben. Wenn du auf "Attach files ..." unterhalb der neuen Nachricht klickst, wird der Windows Explorer geöffnet und du kannst einen Screenshot auswählen.
> 
> Hier der Link zu deinem Issue auf GitHub, ich hoffe der Link wird nicht verstümmelt von GS:
> https://github.com/2Abendsegler/GClh/issues/2417
> 
> LG Frank

**Comment by 2Abendsegler** [comment]
@Fassenachterin 
Hallo Tanja,

ich bin im GClh gerade beim Aufräumen. 

Bei deinem Issue [VIPs are not displayed](https://github.com/2Abendsegler/GClh/issues/2417) fehlen uns die Screenshots, ohne die wir das Problem nicht analysieren und bearbeiten können. Vermutlich ist das Problem nicht mehr aufgetaucht. Ich werde das Issue schließen. 

Falls das Problem nochmal auftritt, kannst du die Screenshots gerne über das Geocaching Nachrichten Center zu mir schicken. Ich werde dann das Issue wieder öffnen und die Screenshots dort reinhängen.

LG
Frank

**Comment by Fassenachterin** [comment]
Hier nun endlich die nötigen Screenshots.
![einstellung_VIP-List](https://github.com/2Abendsegler/GClh/assets/142675292/59ff9c73-027c-4488-93ce-af0c544a78d3)
![rechte Spalte Listing](https://github.com/2Abendsegler/GClh/assets/142675292/97bbc702-7f09-4f14-9bd9-a686f4bd7f4b)
![fehler](https://github.com/2Abendsegler/GClh/assets/142675292/d4342ef7-5ca1-4551-972a-8ac4c22e9603)
![cookies](https://github.com/2Abendsegler/GClh/assets/142675292/7cb81e24-cd7b-4a0d-8731-be4ccf8230a5)
Es gibt eine Fehlermeldung (s. Screenshot). 
Bei den Cookies hatte ich auch vorher alle erlaubt, hab das heute nur nochmal aktualisiert, um zu kucken, ob es dann funktioniert:
Außer dem Reviewer müssten bei dem Beispielcache viele meiner VIPs auftauchen, da einige den schon geloggt haben (Beispielcache war "AB - Die Post ist da - Am Lindensee" https://coord.info/GCAEG3V).
Vielleicht hat jemand Lust und Zeit, sich mit dem Problem zu befassen? Würde mich sehr freuen.

**Comment by 2Abendsegler** [comment]
@Fassenachterin 
Danke für die Infos.

**Comment by 2Abendsegler** [comment]
Per GC Nachrichten Center gesendet:

> 29.12.2023 8:40 PM
> Hallo Tanja,
> 
> danke für die Infos.
> 
> Deine Screenshots sind unauffällig. Es scheint soweit also alles ok zu sein. Ich habe deine VIP Einstellungen gerade auch mal bei mir eingestellt, kann aber das Problem nicht nachstellen.
> 
> Etwas dubios erscheint es mir, dass beide VIP Boxen leer sind. Falls etwas schief läuft, sollte zumindest die Eieruhr bei der VIP-List verbleiben und eigentlich sollten bei VIP-List "not found" sofort immer alle VIPs aufgelistet werden.
> 
> Ich habe im Moment keinen Ansatz für eine Analyse des Problems. Theoretisch könnte noch eine andere Einstellung im GClh außerhalb der VIPs hier mit reinspielen, oder es könnte ein bestimmter VIP sein, der die Probleme verursacht.
> 
> Ich würde das Problem gerne mit deinen GClh Einstellungen analysieren. Kannst du mir bitte deine GClh Einstellungen als .txt Datei über das GC Nachrichten Center (falls das dort mit einer .txt Datei geht) oder über meine Mail Adresse (_entfernt_) zur Verfügung stellen? Vorher kannst du vielleicht die Home Koordinaten direkt im GClh Config etwas abändern, sofern die tatsächlich auf dein zu Hause zeigen. Die VIPs musst du aber alle drin lassen. Ich versichere dir, dass ich nur selbst mit den Daten arbeite und sie nach dem Lösen des Issues wieder alle von meinem Rechner entferne.
> 
> Zur Erzeugung der .txt Datei mit den GClh Einstellungen kannst du den GClh Sync mit der Funktionstaste F10 aufrufen, dort "Manual" anklicken, dann "Export" anklicken und dann "Download" anklicken. Anschließend kannst du eine .txt Datei speichern.
> 
> Liebe Grüße
> Frank

**Comment by 2Abendsegler** [comment]
@Fassenachterin
Super, danke für die Config Datei.
Ich kann das Problem damit nachvollziehen. Wir werden das Problem also beheben können. Vielleicht nicht mehr dieses Jahr, aber am Anfang des neuen.
Einen guten Rutsch.

**Comment by 2Abendsegler** [comment]
@Fassenachterin
Ich noch mal. Es handelt sich gar nicht um einen Fehler, sondern um eine Einstellung. Das war echt nachlässig von mir, daran nicht zu denken. 

Du hast den Parameter `Load logs with GClh II` deaktiviert. Wenn man das tut bekommt man eine Warnmeldung, dass zahlreiche Features wie beispielsweise die VIPs nicht mehr funktionieren.
![Unbenannt](https://github.com/2Abendsegler/GClh/assets/22332216/4f667499-4870-49ca-adcd-b839c7ea6c39)

Wenn du den Parameter wieder aktivierst, dann sollten die VIPs und auch andere Dinge wieder funktionieren. 
[Hier gelangst du zum Parameter.](https://www.geocaching.com/my/#GClhShowConfig#a#settings_load_logs_with_gclh)

Bitte probier es mal aus und gib bitte Rückmeldung.

Liebe Grüße
Frank

**Comment by Fassenachterin** [comment]
@2Abendsegler 
SENSATIONELL und 1000 Dank für die mega-schnelle Hilfe. Genau das war's. Ich hatte beim Einrichten am anderen Laptop ein paar Features angeklickt, und da mir das Feature  Load logs with GClh II nichts sagte (und ihr ehrlich gesagt die Infos hinter dem ? hier nicht las, bei vielen anderen aber schon), habe ich das nicht angeklickt oder sogar aus mir nicht mehr nachvollziehbaren Gründen deaktiviert.
Jetzt ist es angehakt, und schwupp, werden die VIPs angezeigt. Klasse!

Nochmals dicken Dank für die tolle Hilfe und vor allem auch mit Direktlink, damit ich gleich sehe, wo ich klicken muss ( [Hier gelangst du zum Parameter.](https://www.geocaching.com/my/#GClhShowConfig#a#settings_load_logs_with_gclh) ) Dass sowas überhaupt möglich ist, super.
Jetzt kann ich meine Touren mit meinen Cacherfreunden wieder ganz easy planen plus bei geplanten Caches auch sehen, wer ihn schon gemacht hat, z. B. auch im Hinblick auf mögliche Telefonjoker. Ich freu mich! 👍 🫶

**Comment by 2Abendsegler** [comment]
@Fassenachterin 
Sehr schön, dass wieder alles klappt bei dir.
Ich schließe das Issue dann mal.

**Comment by capoaira** [comment]
Vielleicht sollten wir zusätzlich zu dem Hinweis die Parameter im Config deaktivieren, die ohne die Option nicht funktionieren.

**Comment by 2Abendsegler** [comment]
> Vielleicht sollten wir zusätzlich zu dem Hinweis die Parameter im Config deaktivieren, die ohne die Option nicht funktionieren.

Ich wollte vor Jahren hier schon mal was machen, und dann war es mir zu viel Aufwand und es ergaben sich zu viele Probleme. 

Wenn wir abhängige Parameter deaktivieren, würde ein User diese abhängigen Parameter kaum alle wieder finden, um sie wieder manuell zu aktivieren, wenn er es sich anders überlegt und den Parameter `Load logs with GClh II` wieder aktiviert. Wir müssten uns also die Parameter merken, die wir dann wieder automatisch aktivieren. Außerdem entstehen dadurch Probleme, dass wir einen Parameter wie die VIPs nicht ausschalten können, weil die VIPs ja durchaus im Dashboard noch korrekt angezeigt werden und die Cacher auch an anderen Stellen als VIP markiert werden können. 

Wir könnten die VIP Listen im Cache Listing entfernen, indem wir den Parameter `Load logs with GClh II` rechtzeitig abfragen. Das würde aber an der eigentlichen Problematik, dass die VIPs trotz aktiviertem Parameter im Listing nicht angezeigt werden, auch nichts ändern. 

Vielleicht könnten wir den Hinweis als Popup noch aussagekräftiger und heftiger formulieren. Oder wir könnten in allen abhängigen Parametern im Hilfstext die Abhängigkeit zum Parameter `Load logs with GClh II` benennen.  

Eigentlich will ich da aber gar nicht dran gehen, wir haben schon zu wenig Zeit für wichtigere Dinge.
