### ISSUE TITLE
[Cache Listing] GC Code is not copyable when PGC script is running

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2420]
Without PGC:
![grafik](https://github.com/2Abendsegler/GClh/assets/50927164/058e8983-1d76-44a5-be0a-aeae74707098)

With PGC:
![grafik](https://github.com/2Abendsegler/GClh/assets/50927164/c818cc89-f49c-402c-abd3-2b9265d7c3d2)

**Comment by 2Abendsegler** [comment]
@capoaira 
Die Anpassungen am GS Code durch das pgc Script führen dazu, dass wir den Copy Button nicht wieder an der richtigen Stelle aufbauen können, ohne dass wir an diesen Anpassungen Änderungen vornehmen. Das möchte ich aber nicht im GClh Script tun. Das sollte direkt im pgc Script erfolgen. Ich möchte das aber nicht selbst dort implementieren. Hast du vielleicht Lust das dort zu implementieren?

Im Moment sieht es wie folgt aus:
![Unbenannt 1](https://github.com/2Abendsegler/GClh/assets/22332216/a81529a2-6c88-4496-a86c-dfc3896b5253)

Mit PR #2426 sieht es so aus:
![Unbenannt 2](https://github.com/2Abendsegler/GClh/assets/22332216/8669ecf4-413f-4f2e-8dda-6c82f72541b2)

Mit folgender Anpassung am pgc Script:
Alt:
```
            html('<div style="margin-right: 15px; margin-bottom: 10px;"><p id="ctl00_ContentBody_CoordInfoLinkControl1_uxCoordInfoCode" style="font-size: 125%; margin-bottom: 0">' + gccode + '</p>' +
                '<input size="25" type="text" value="https://coord.info/' + encodeURIComponent(gccode) + '" onclick="this.setSelectionRange(0, this.value.length);"></div>');
```
Neu:
```
            html('<div style="margin-right: 15px; margin-bottom: 10px;"><p style="font-size: 125%; margin-bottom: 0"><span id="ctl00_ContentBody_CoordInfoLinkControl1_uxCoordInfoCode">' + gccode + '</span></p>' +
                '<input size="25" type="text" value="https://coord.info/' + encodeURIComponent(gccode) + '" onclick="this.setSelectionRange(0, this.value.length);"></div>');
```
... sieht es so aus:
![Unbenannt 3](https://github.com/2Abendsegler/GClh/assets/22332216/c1e8bf5a-77d3-4b17-803f-ec8505e64707)

**Comment by capoaira** [comment]
Ja, kann ich machen

**Comment by capoaira** [comment]
merged with #2426 and https://github.com/magma1447/greasemonkey-geocaching-projectgc/pull/154
