### ISSUE TITLE
[Maps] Add link to Komoot on Browse and Search Map.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2433]
### Describe the solution you'd like

In the "Got to ..." icon an additional link are placed on the Browse Map and on the Search Map page to link to the same area in Komoot.

![Screen02](https://github.com/2Abendsegler/GClh/assets/22332216/0e783208-92d7-4c4a-9983-621d2e785bb8)

![Screen03](https://github.com/2Abendsegler/GClh/assets/22332216/ad94c458-5667-49bc-9826-a643a9cb26a0)

[Edit]
![Screen04](https://github.com/2Abendsegler/GClh/assets/22332216/16ede486-0d72-4c6e-93f4-954ea2536f90)

**Comment by capoaira** [comment]
merged with #2434
