### ISSUE TITLE
[Friends List, Public Profile, Cache Listing, Cache owner dashboard] Nearest list links no longer work.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2446]
### Describe the bug

Scheinbar wurden bis auf die PQ als "nearest list" Links abgestellt. Womöglich ist die Zeit gekommen, dass alle alten Verarbeitungen abgestellt werden. Sehr schade.

Teils können wir die Parameter im GClh Config ändern (das sind die Links weiter unten), um unsere eingebauten Links zu entfernen. Teils haben wir aber dafür keine Parameter vorgesehen. 
(Die Links müssen nacheinander abgearbeitet und gespeichert werden, nicht alle Links gleichzeitig aufrufen und speichern, weil dann die Parameter immer wieder überschrieben werden.)

Es betrifft nach derzeitigem Stand folgende Bereiche:

1. Friends List: 
[Show summary for new finds/hides in friends list? ](https://www.geocaching.com/my/#GClhShowConfig#a#settings_friendlist_summary)
2. Public Profile: 
[Geocaches: Use old links to finds and hides caches?](https://www.geocaching.com/my/#GClhShowConfig#a#settings_profile_old_links) und
Links für die Finds und Hides: Dafür haben wir keinen Parameter vorgesehen, schlampig. Hier gibt es aber auch keine Links im Standard.
3. Cache Listing: 
[Links to Find Caches: Use old links to find caches](https://www.geocaching.com/my/#GClhShowConfig#a#settings_listing_old_links)
4. Cache owner dashboard: 
Total hides Links. Dafür haben wir keinen Parameter vorgesehen, schlampig.

### Expected behavior

https://www.geoclub.de/forum/t/gc-little-helper-ii-ab-v0-11.81650/post-1370327

### OS

Windows

### Browser

Firefox

### GClh Version

0.14.6

**Comment by capoaira** [comment]
> Scheinbar wurden bis auf die PQ als "nearest list" Links abgestellt. Womöglich ist die Zeit gekommen, dass alle alten Verarbeitungen abgestellt werden. Sehr schade.

Das ist echt schade :-(



> Total hides Links. Dafür haben wir keinen Parameter vorgesehen, schlampig.

Ein Parameter ist hier nicht nötig, da das Layout nicht geändert wird. So wie auch die Verlinkung der Owner auf der Search Map

**Comment by capoaira** [comment]
Glücklicherweise war es wohl ein Bug und keine freiwillige Abschaltung. 

https://forums.geocaching.com/GC/index.php?/topic/394944-error-500-on-seek-sites/#comment-6107376
