### ISSUE TITLE
[Log Form] Signature disappears on changing the logtype

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2455]
### Describe the bug

When you change the logtype, the signature will be removed. We need an automatic, that keeps the log text also after a change of logtype.

Sorry, I didn't see that during the Review :(

### OS

Windows

### Browser

Firefox

### GClh Version

current collector

**Comment by 2Abendsegler** [comment]
Das ist das Phänomen wie im #1688. Die eingefügte Signatur ist noch nicht im Textfeld angekommen. Sobald man eine Eingabe im Textfeld macht, ist sie im Textfeld bekannt. Das gilt nicht nur für die Signatur, sondern auch für alle Templates. Hatte ich [dort](https://github.com/2Abendsegler/GClh/pull/2451#issuecomment-1816392928) auch bereits erwähnt.

Und ich habe keine Lösung dafür.

**Comment by 2Abendsegler** [comment]
Die Signaturen und Log templates verschwinden nicht nur wenn ein Log type ausgewählt wird, sondern auch bei anderen Aktionen auf der Seite. Bis gestern verschwanden die Dinge bei der Auswahl eines Log dates noch nicht, heute verschwinden sie auch damit. Bis vor ein paar Tagen war alles im Bereich Trackable Inventory auch nicht betroffen, heute ist alles dort davon betroffen. Da scheint noch Bewegung drin.

Im Moment verschwinden unsere Eingaben mindestens bei folgenden Aktionen:
- Log type ändern
- Log date ändern
- Foto hochladen über select photos 
- Foto hochladen über Drop files
- Log preview ein-, ausklappen
- Favorite setzen, entfernen
- Trackable inventory ein-, ausklappen 
- Klick auf Clear all, Visit all, Drop all 
  (Witzigerweise im Replicate TB-Header to bottom nicht, obwohl damit ein click dorthin erfolgt.) 
- Klick auf No action, Visit, Drop 
  (Witzigerweise bei den Autovisit Buttons nicht, obwohl damit ein click dorthin erfolgt.) 

Eigentlich ist mir die Zeit zu schade um all diesen Dingen nachzugehen. Vielleicht reicht ja der Workaround mit dem Hinweis an den Nutzer, dass anschließend eine manuelle Eingabe erfolgen muss.

**Comment by capoaira** [comment]
Das ist ja echt blöd.
Moderne Frameworks wie React, Vue, o.ä. speichern sich alle Werte intern und bauen die Seite bei jeder Änderung im DOM neu. *Eigentlich* sollten nur die Elemente neu gebaut werden, in denen Änderungen stattfinden. GS scheint aber nur eine Variable (object) zu haben, in der alle Daten gespeichert werden. Wenn diese geändert wird, werden alle Felder neu gebaut, in der das Object genutzt wird.
Leider habe keine Möglichkeit gefunden darauf zuzugreifen. Ich würde trotzdem gerne vor der nächsten Version noch eine Kleinigkeit versuchen, die das Ganze nicht unbedingt stabil, aber zumindest stabiler machen könnte.

**Comment by 2Abendsegler** [comment]
Da haben wir aber Glück, ich wollte gerade die neue Version in den master mergen. 🤭
Gib bitte Bescheid, wenn du mit deinen Versuchen, Anpassungen durch bist.

**Comment by capoaira** [comment]
Super 👍, ich kann aber leider nichts versprechen...

**Comment by capoaira** [comment]
Sorry für den komischen Log. Ich bin versehentlich auf Strg+s gekommen. Das sendet den Log automatisch ab.🙃
Ich mache aber tatsächlich Fortschritte mithilfe eines Mutations Observers  (Templates sollten funktionieren), kann sich nur noch um Stunden handeln bis auch die Signatur läuft.... 😅
