### ISSUE TITLE
[Changelog, Config] The changelog links no longer work properly.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2468]
### Describe the bug

The changelog links no longer work properly. readme no longer exists.
`https://github.com/2Abendsegler/GClh/blob/master/docu/changelog.md#readme`
Maybe we can create our own anchor in the changelog.

### OS

Windows

### Browser

Firefox

### GClh Version

0.15

**Comment by capoaira** [comment]
Bei mir sieht es normal aus. Evtl. könnten wir aber darüber nachdenken, den Changelog ins Wiki zu übertragen. Dort kann man das ganze besser Gliedern.

**Comment by 2Abendsegler** [comment]
Die Seite wird schon noch angezeigt, es wird nur nicht mehr etwas runter gescrollt. Das ist es was nicht mehr funktioniert. Es gibt den `readme` Anker nicht mehr.
Hab schon einen Anker `readme` eingebaut. Wir müssen deshalb ansonsten auch nichts ändern. 

> Evtl. könnten wir aber darüber nachdenken, den Changelog ins Wiki zu übertragen.

Ich weiß nicht genau was das Wiki kann, aber eine solche Übertragung würde vermutlich keinen oder nur geringen Mehrwert generieren. Dann vielleicht lieber an neuen Features arbeiten, nicht im Log Formular, sondern irgendwo wo es netter ist. 😂

**Comment by capoaira** [comment]
Ah ok. Hatte mich schon gewundert 😅

Dem Wiki kann man Seiten hinzufügen, die man auch anordnen kann. Die Seiten werden wie jetzt auch schon in Markdown geschrieben.
