### ISSUE TITLE
[GitHub] Bug filling out new issues.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2469]
### Describe the bug

Bug filling out new issues if you click to a field.
![Unbenannt](https://github.com/2Abendsegler/GClh/assets/22332216/5f3898a9-6595-4e89-9e8b-96ce38eda51e)

### OS

Windows

### Browser

Firefox

### GClh Version

0.15

**Comment by capoaira** [comment]
Ich denke, dass das hier ein Fehler von Github ist, den wir selbst nicht beheben können

**Comment by 2Abendsegler** [comment]
Fehlermeldung vom 27.11.2023:
https://github.com/orgs/community/discussions/63402#discussioncomment-7681231

Ich habe temporär die `placeholder:` für `type: textarea` mit einer Leerzeile versehen, so wie auch in der Fehlermeldung beschrieben.

**Comment by 2Abendsegler** [comment]
Weitere Meldung:
https://github.com/orgs/community/discussions/76763

**Comment by 2Abendsegler** [comment]
Das Problem scheint gelöst. Allerdings werden mehrzeilige Texte wie bei `To Reproduce` nach einem Klick ins Feld nicht mehr umgebrochen. Ich werde noch einige Tage warten und dann die temporären Änderungen wieder zurück nehmen.

**Comment by 2Abendsegler** [comment]
Bug filling out new issues is solved. Undo temporary changes.
