### ISSUE TITLE
[Log Form] On the edit log page, GClh is not running, but the GClh header is available on the page.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2472]
### Describe the bug

On the edit log page, GClh is not running, but the GClh header is available on the page. 

Ausgangspunkt ist die View Log Seite. Wenn man dort den Edit Button wählt, kommt man ins Log Formular. Obwohl der GClh hier gar nicht anspringt, ist der Header des GClh noch vorhanden. Das sieht so aus als würde eine neue url gesetzt, ohne dass es zu einem neuen Seitenaufbau kommt. 

Wenn man die Edit Seite aktualisiert, startet der GClh.

### To Reproduce

1. Baue ein console.log im maingc ein.
2. Gehe zur einer Log Anzeige, beispielsweise übers Dashboard und dort dann Log anzeigen wählen.
3. Wähle den Edit Button.
4. Siehe den GClh Header aber keine Ausgabe in der Konsole.

### OS

Windows

### Browser

Firefox

### GClh Version

0.15

**Comment by capoaira** [comment]
Wenn ich die Seite neu lade, wird der GClh geladen.

Ich gehe davon aus, dass GS `navigate` von React nutzt. Die Seite wird nicht neu geladen, nur der Inhalt wird ausgetauscht. Unser Script merkt das natürlich nicht.
