### ISSUE TITLE
[Log Form] Signature is insert into edit form

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2475]
### Describe the bug

Signature is insert into edit form

### To Reproduce

1. Click on "Edit Log"
2. Reload the page

The Log must be a log without the signature.

### Expected behavior

The Signature should not be insert into Logs, if we are on edit.

### OS

Linux

### Browser

Firefox

### GClh Version

0.15

**Comment by 2Abendsegler** [comment]
@capoaira 
Mir ist gerade aufgefallen, dass deine Anpassung in #2476 nur für Caches wirksam ist. Sorry, das ist mir heute mittag nicht aufgefallen. Für TBs wird immer noch eine Signatur erzeugt. Einen Fehler kann ich aber nicht finden.
Kannst du bitte noch mal danach sehen.

**Comment by 2Abendsegler** [comment]
@capoaira 
... Es scheint mit den `?:` bei `const isEdit` zusammen zu hängen.

**Comment by capoaira** [comment]
> @capoaira ... Es scheint mit den `?:` bei `const isEdit` zusammen zu hängen.

Ne, das `?:` macht nur, dass Gruppen nicht als solche erkannt werden. Ob das da steht oder nicht, ist hier tatsächlich egal. Das müsste mit der Verknüpfung der Bedingungen zu tun haben. Der PR folgt gleich.
