### ISSUE TITLE
[Global] GC little helper does not work anymore (behind a DNS server).

### ISSUE THREAD

**Issue by flat2let** [2Abendsegler/GClh#2505]
### Describe the bug

Following Error Message appeared on on site
GC Little Helper Error
Remove GC Menüs: Syntax Error, unrecognized expression: u1 (Menu|menu) li a. dropdown

GC little helper is not shown on any geocaching.com page anymore.

### OS

Windows

### Browser

Firefox

### GClh Version

0.15.1

**Comment by 2Abendsegler** [comment]
I am also unable to reproduce it (Windows 10, Firefox 120.0.1).
And at the moment I don't understand how a syntax error can occur.

@flat2let
Can you please call up the console (F12 and then select Console) and provide us with a screenshot of the red stuff here?

Can you please re-select the installation of the GClh [here](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) and then select the “Install new” button (or something similar).

**Comment by flat2let** [comment]
![screenshot](https://github.com/2Abendsegler/GClh/assets/85786015/2f0de65f-08d3-46e9-86c1-f37e6d743529)
the error started with the update of gc little helper as you can see

**Comment by flat2let** [comment]
![screenshot_2](https://github.com/2Abendsegler/GClh/assets/85786015/bf2fce04-8a53-4bc8-ab71-941314d13b15)
I hope that's waht ou were looking for?

**Comment by 2Abendsegler** [comment]
Sorry, du musst noch den Button "Fehler (3)" anwählen und dann sind die roten Dinge wichtig. "Warnungen" kannst du abwählen, die sind im Moment nicht wichtig.

**Comment by 2Abendsegler** [comment]
... Vielleicht sind die Warnungen doch nicht so unwichtig.
Kann es sein, dass du die Cookies beim Anmeldeprozess auf der Geocaching Seite nicht alle angewählt hast? Dann mach das mal. Du kannst das bei den [Settings](https://www.geocaching.com/account/settings/cookies) ändern. Da gibt es so was wie "Einwilligung ändern" oder so ähnlich.

**Comment by flat2let** [comment]
![Uploading screenshot_5.JPG…]()

**Comment by flat2let** [comment]
Die Idee mit den Cookies hatte ich jetzt auch schon und hab neu gestartet und alle Cookies akzeptiert, das hat leider auch nichts geändert :-(
Danke dass Du Dir so viel Mühe für mich gibst

**Comment by flat2let** [comment]
![screenshot_4](https://github.com/2Abendsegler/GClh/assets/85786015/632e78c7-2e89-4d48-a305-e0ab123598c3)
![screenshot_5](https://github.com/2Abendsegler/GClh/assets/85786015/4c4ae29f-62a2-4a10-ad40-633d98def46b)

**Comment by flat2let** [comment]
hatte vorher schon alles ausgeschaltet, habe jetzt noch zusätzlich alle add ons deaktiviert, hilft leider auch nicht. Es ist so frustrierend

**Comment by flat2let** [comment]
![screenshot_6](https://github.com/2Abendsegler/GClh/assets/85786015/795d52d4-4559-49ce-966e-0fa60fa9a1a6)
das läuft jetzt in einer Endlosschleife

**Comment by flat2let** [comment]
![screenshot_8](https://github.com/2Abendsegler/GClh/assets/85786015/c9811b3b-f07f-4ec2-9eeb-e6d65f3d6c9f)
das ist jetzt ganz oben

**Comment by flat2let** [comment]
![screenshot_9](https://github.com/2Abendsegler/GClh/assets/85786015/d020ae41-ecc9-4b3b-afc6-8a9fcb829efc)

**Comment by 2Abendsegler** [comment]
> leider nichts

Das ist eine gute Nachricht. Nun wissen wir mit Bestimmtheit, dass diese Bibliotheken bei dir blockiert werden. 
Du hast einige Add-Ons am Laufen. Ich kenne nur "ABP". Das ist ein Blocker, der theoretisch dafür verantwortlich sein könnte.
Schalte bitte nochmal alle Add-Ons aus, auch Tampermonkey, einfach alle. Dann bitte nochmal anwählen
`https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js`

**Comment by flat2let** [comment]
wir haben es jetzt noch mal mit meinem Partner gestestet und die Seite ging bei ihm auch nicht auf. Obwohl er nichts bei uns geändert hatte hat er nun festgestellt dass der adblocker des DNS servers es geblockt hat. Abgeschaltet, und nun geht es

**Comment by flat2let** [comment]
danke Dir so so sehr, dass Du Dir die Zeit genommen hast mir zu helfen. Das ist unglaublich. Ich bin echt sprachlos und jetzt natürlich so so happy, dass alles geht. Danke danke danke.

**Comment by flat2let** [comment]
Das tool ist so toll, ich wüsste gar nicht mehr was ich ohne GC little helper machen würde. Es ist wunderbar, dass es Leute wie Dich gibt
Lieben Gruß Kathrin/flat2let.de

**Comment by 2Abendsegler** [comment]
Cool, dass es wieder funktioniert! 
So langsam gingen mir auch die Ideen aus. 🤭
Dann werde ich mich jetzt mal wieder den Outdoor Planungen für Sonntag widmen.
LG
Frank

**Comment by flat2let** [comment]
Sorry dass ich Dich von Deinen Sachen abgehalten hab' und viel Spaß und Erfolg

**Comment by 2Abendsegler** [comment]
> Sorry dass ich Dich von Deinen Sachen abgehalten hab' und viel Spaß und Erfolg

Hey, kein Problem, das war kein Vorwurf. 😊
Aber schön, dass du dich noch mal gemeldet hast. 😀
Noch ein schönes Wochenende. Ich glaube in Frankfurt soll morgen das Wetter auch ganz nett werden, wenn sich der Hochnebel verzieht.
LG 
Frank

**Comment by flat2let** [comment]
Ich hatte das auch absolut nicht als Vorwurf verstanden, aber es tut mir trotzdem leid, dass ich Dich so lange beschäftigt habe. Und es ist absolut nicht selbstverständlich, dass Du das tust. Geocaching wird es wohl morgen eher nicht werden, eher Weihnachtsmarkt und Glühwein :-)

**Comment by 2Abendsegler** [comment]
Weihnachtsmarkt und Glühwein sind natürlich auch cool. 
Mal sehen ob wir auch etwas davon finden. 😊
Und ... nette Anfrage ...

Habt ihr eigentlich eine Idee wie die Bibliotheken auf den Adblocker eures DNS servers gekommen sind. Ich frag mich nur, ob es sein kann, dass davon auch noch andere Nutzer betroffen sind.

**Comment by flat2let** [comment]
Hast Du die Message von meinem Mann im geocaching.com message center bekommen? Er hat Dir wegen des DNS Servers geschrieben. Ich hoffe das hilft Dir weiter.

**Comment by 2Abendsegler** [comment]
Ja, hab ich bekommen, danke, konnte mir die Details aber noch gar nicht genau ansehen, deshalb fehlt auch meine Rückmeldung. Ich werde mir das heute Abend mal genauer ansehen und versuchen zu beurteilen wie hoch die Wahrscheinlichkeit ist, dass auch noch andere Nutzer von diesem Problem betroffen sind. Habe auch dein Issue wieder geöffnet, damit man das hier auf GitHub besser sieht, falls jemand ein ähnliches Problem hat.
Jetzt gehen wir aber zuerst mal etwas nach draußen in die Kälte. 🥶 😂
