### ISSUE TITLE
[Global] Execution of GClh ends with a syntax error due to blocking of the requested JQuery libraries.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2508]
### Is your feature request related to a problem? Please describe

Hintergrund ist Issue #2505.

Im Moment entsteht dabei irgendwann während der Ausführung des GClh ein Syntax Error, ausgelöst durch das Blockieren der angeforderten JQuery Bibliotheken. Im aktuellen Beispiel durch den Werbeblocker Pi-Hole, der auf einem DNS Server läuft.

Das aktuelle Problem stellte sich wie folgt da: (Auszug aus der Beschreibung der betroffenen User.)
> ... The problem turned out to be my ad-blocker, Pi-Hole. (https://pi-hole.net/) Once I added ajax.googleapis.com to the "whitelist" everything worked fine.
> The list of blocked domains comes from https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts. I searched through the list but didn't find the above mentioned ajax URL. There were other googleapis.com domains, but not the ajax one. The list is mainted by someone else, whenever I do a routine update of the raspberry pi, the Pi-Hole app is updated, including the most recent Adlist, but I have no idea what is modified between list versions. ...

Ist der Parameter [Show an alert if an internal error occurs](https://www.geocaching.com/my/#GClhShowConfig#a#settings_gclherror_alert) aktiviert, wird im Header der Seite eine Fehlernachricht ausgegeben. Im aktuellen Fall war es `Remove GC Menüs: Syntax Error, unrecognized expression: u1 (Menu|menu) li a. dropdown`. Der genaue Inhalt der Nachricht, mal abgesehen von `Syntax Error`, und die Abbruchstelle im Script, hängen meines Erachtens davon ab, wann die Rückmeldung erfolgt, dass die Bibliotheken nicht geladen werden konnten. Denn erst dann scheint der Befehlssatz der Bibliotheken nicht mehr vorhanden zu sein. Zuvor stehen die Bibliotheken womöglich noch über den Scriptmanager zur Verfügung. Ich habe im Moment keine andere Erklärung für die Abbruchstelle.
![a1](https://github.com/2Abendsegler/GClh/assets/22332216/42c04517-31b7-4b4a-a0ee-fd07395621f6)

Nachdem die Fehlermeldung ausgegeben wurde, wird das Fehlerhandling meines Erachtens abgebrochen, vermutlich weil dort ebenfalls Befehle aus den Bibliotheken verwendet werden. Es kommt also vermutlich nicht zur Ausgabe der Fehlermeldung in der Konsole. Zumindest scheint im aktuellen Fall keine entsprechende Fehlermeldung in der Konsole gewesen zu sein. Das ist im Moment meine Einschätzung, ohne dass ich es im Coding verifiziert hätte.

Das die angeforderten Bibliotheken nicht geladen werden konnten, wird in der Konsole mit einer Warnung protokolliert.
![a2](https://github.com/2Abendsegler/GClh/assets/22332216/0a6d1b3b-f01f-4089-bd6e-94522bbf86b3)

### Describe the solution you'd like

Der Fehler sollte besser abgefangen werden. Idealerweise sollten wir erkennen, dass es sich um einen Syntax Error handelt und dass die Befehlssätze der Bibliotheken nicht vorhanden sind. 

Wir könnten dann ein Popup ausgeben, ähnlich wie nach einer Installation der Hinweis auf das Changelog, hier nur eben dann mit einem Hinweis zum Fehler und den FAQ, wo das Problem ausführlich beschrieben ist. Per ok Button im Popup sollte man direkt zu den FAQ gelangen. Die Beschreibung in den FAQ sollte es den User idealerweise in die Lage versetzen, das Problem zu beheben. 

Außerdem sollte der Fehler ordnungsgemäß in der Konsole protokolliert werden.

**Comment by 2Abendsegler** [comment]
Eigentlich geht es mir hauptsächlich darum, das Problem auszuweisen, als etwas was nicht vom GClh verursacht wird. Einen Syntax Fehler sollten wir im Fehlerhandling erkennen können und dass JQuery nicht mehr verfügbar ist auch. Wenn wir es dann noch schaffen den User direkt zu informieren, dann ist aus meiner Sicht alles gut. 

Wenn jemand meint Anfragen an Google Server unterbinden zu müssen, ist das ok, wir zeigen die Auswirkungen. Wenn bei jemandem unwissentlich, wie in unserem Beispiel, Anfragen an Google Server unterbunden wurden, dann zeigen wir, wie er das Beheben kann. Das wäre optimal. Damit sind wir auch außen vor.

Ich wollte mal testweise versuchen die Bibliotheken auf GitHub zu speichern um sie dann umzubenennen und damit das Laden über Tampermonkey zu verhindern in der Hoffnung, dass ich das Problem damit nachstellen kann. Wenn du aber in der Lage bist das Problem in echt nachzustellen, wäre das natürlich viel besser. Wenn du also irgendwann Zeit und Lust hast ... .

**Comment by capoaira** [comment]
Pi-Hole läuft jetzt bei mir und blockiert fleißig Tracker und Werbung. Der GClh läuft bei mir trotzdem wunderbar.

**Comment by 2Abendsegler** [comment]
Ja, super.

Du musst Tampermonkey auch dazu bringen die Bibliotheken neu zu laden. Hast du das gemacht? Das kannst du beispielsweise machen, indem du dem GClh in Tampermonkey eine andere Version gibst.

**Comment by capoaira** [comment]
> Ja, super.
> 
> Du musst Tampermonkey auch dazu bringen die Bibliotheken neu zu laden. Hast du das gemacht? Das kannst du beispielsweise machen, indem du dem GClh in Tampermonkey eine andere Version gibst.

Jup, klappt auch damit.

**Comment by 2Abendsegler** [comment]
@capoaira 
Moin,
wollen wir das hier schließen? 
Es hat bei deinen Tests ja alles funktioniert und du hattest ja sowieso ursprünglich schon geschrieben,
> Da dies vermutlich nur wenige betrifft, sollten wir nicht zu viel Zeit investieren, diese Problematik zu lösen.

**Comment by capoaira** [comment]
Jup, können wir gerne machen. Falls wir die Fehlermeldung erneut bekommen, wissen wir ja, wo das Problem liegt. 

PS.: Die beiden PRs gucke ich mir an, sobald ich wieder gesund bin.

**Comment by 2Abendsegler** [comment]
Ich hoffe es ist nichts schlimmes. Gute Besserung.
