### ISSUE TITLE
 [Log Form] "Copy Log" Button in new design

### ISSUE THREAD

**Issue by ChristianGK-GC** [2Abendsegler/GClh#2510]
### Is your feature request related to a problem? Please describe

Man könnte den copy Button gut im neuen Design integrieren.

### Describe the solution you'd like

![grafik](https://github.com/2Abendsegler/GClh/assets/24353480/4a622584-8b80-4af1-b0e0-5a9ab5b3a478)

**Comment by 2Abendsegler** [comment]
Hm ... ich finde es eigentlich gut, dass das "Copy to clipboard" Feature auf allen Seiten durchgängig identisch aussieht.
