### ISSUE TITLE
option to disable "Special days" (nicolaus) found smileys

### ISSUE THREAD

**Issue by ztNFny** [2Abendsegler/GClh#2511]
### Describe the solution you'd like

During some special days log summary smileys are displayed with decorations. There should be an option to disable that.
![image](https://github.com/2Abendsegler/GClh/assets/1258173/86f779fa-ff00-4619-8bc2-8ad35c087c00)

**Comment by capoaira** [comment]
@2Abendsegler ist das gerade aktiv? Bei mir wird das gar nicht angezeigt...

**Comment by 2Abendsegler** [comment]
@capoaira das war am 05. und 06.12 aktiv und wird vom 24. bis 26.12 aktiv. Ich sehe hier gar keinen Handlungsbedarf.

**Comment by capoaira** [comment]
Ok, danke. Ich dachte, dass das in den letzten Jahren immer den ganzen Dezember an war.

Maybe @ztNFny can explain why there should be an option to disable the christmas-smileys

**Comment by ztNFny** [comment]
imho it's distracting. Usually it's possible to tell with a quick glance whether all is good (only yellow found smileys) - but with those red and differently sized icons that is lost.

**Comment by 2Abendsegler** [comment]
> Ok, danke. Ich dachte, dass das in den letzten Jahren immer den ganzen Dezember an war.

Letztes Jahr war es glaube ich gar nicht an. Die Jahre davor war es auch mal zusätzlich an den Adventswochenenden an, meine ich. Und eigentlich finde ich, so darf es auch bleiben, ohne dass wir noch etwas zusätzliches zum Abschalten einbauen. 😉

**Comment by 2Abendsegler** [comment]
This feature is not planned.
