### ISSUE TITLE
Driving Directions for every waypoint

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#252]
Offer for every waypoint in the waypoint list in a cache listing a link to driving direction of Google Maps. Start point: home location.
Show link as an icon like in the top of the listing 
![grafik](https://cloud.githubusercontent.com/assets/1838534/24217491/4ad2dc0a-0f40-11e7-82b1-45e69ff6f1da.png)
Show the link in the 8th column of the waypoint list table

Settings
- enable/disable feature
- option: link only for Parking Area waypoints

**Comment by CachingFoX** [comment]
![grafik](https://cloud.githubusercontent.com/assets/1838534/24222021/f3466cc0-0f50-11e7-8c89-a02d9591da17.png)

**Settings > Listing**
![grafik](https://cloud.githubusercontent.com/assets/1838534/24222123/4eda77c0-0f51-11e7-8d16-2147469a5c66.png)

**Comment by CachingFoX** [comment]
CachingFoX/GClh/dev_cf_drivingdirections

**Comment by 2Abendsegler** [comment]
Eingespielt und getested.
