### ISSUE TITLE
Link to Waypoint List and Logs section in a cache listing

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#253]
As a geocacher I want to come directly to the waypoint list or log section in a cache listing without scrolling at the end of the (long) listing.

Added two links in the cache detail navigation panel on the right side in the top of the listing:
- Go to Waypoint List
- Go To Logs

**Comment by CachingFoX** [comment]
![grafik](https://cloud.githubusercontent.com/assets/1838534/24218638/4560a5dc-0f44-11e7-9551-f2a368d6c7d9.png) 
![grafik](https://cloud.githubusercontent.com/assets/1838534/24218676/6bb56cc2-0f44-11e7-98b5-521fb719f8fd.png)

**Comment by CachingFoX** [comment]
CachingFoX/GClh/dev_cf_shortcut

**Comment by CachingFoX** [comment]
Test cases
- Check this feature with cache listings without additional waypoints

**Comment by 2Abendsegler** [comment]
Hi,
im Rahmen der Issues #254 und #268 war ein neues Icon für das Filtern von VIP Logs notwendig.

Das sieht dann bei der VIP-list wie folgt aus:
![v0 7_screen02](https://cloud.githubusercontent.com/assets/22332216/24680311/b3c83d7c-1990-11e7-8e10-87ec4249b12c.jpg)

Und über den Logs so:
![vip logs 2](https://cloud.githubusercontent.com/assets/22332216/24680398/16d7d8b4-1991-11e7-9d70-684669c05c69.jpg)

Vielleicht kannst Du das Icon ohne VIP Schriftzug für Dein "Go to logs" nutzen, damit wir einheitliche Icons für gleiche Dinge verwenden.
![logs](https://cloud.githubusercontent.com/assets/22332216/24680410/1c33667a-1991-11e7-98cb-a6dc2a7890fa.jpg)

Das Icon ist im gclh_icons in branch collector unter dem Namen global_logs_icon bereits vorhanden.

LG

**Comment by 2Abendsegler** [comment]
Eingespielt und getested.
