### ISSUE TITLE
Filter VIP logs in cache listing (images on Logbook page)

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#254]
I do not visit a cache logbook page often and I guess only minority of cachers have noticed it but it is there. And **it is** useful sometimes like in the case of world's most visited cache [Prague bridges 1 - Karluv most](https://coord.info/GC189E5). This cache has over 28 000 finds so even loading the page with generating VIP list takes nearly a minute. I have all my friends in VIP list so I can read their stories. So far so good.

But what if I'd like to see their attached images? I can click the smiley in VIP list which would take me to their log. But GClh has hard time with caches like this. I chose a friend who found it in November 2016 (only 4 months ago!) and I quickly get **Warning: unresponsive script**.

So the only suitable way is to go to this cache's [logbook](https://www.geocaching.com/seek/cache_logbook.aspx?guid=d719b55f-1b6c-4e3b-bdbf-d6fc2b7de5e9) and choose _Your Friends' Logs_ tab. But the images here display very small, even smaller than they would display on a cache page without GClh involved.

![obrazek](https://cloud.githubusercontent.com/assets/9153595/24237285/f69f0ac6-0fa5-11e7-8875-d5960a90fb7b.png)

So the question is: is it possible to use the rules already set up in GClh II config for Logbook page as well? Especially **Show thumbnails of images**  and **Max size of big image**.

**Comment by 2Abendsegler** [comment]
I have never seen so much finds. Czech Republic seems to be the new star on caching countrys. In the GClh installation statistics, Czech Republic has the second place after germany. :)

I understand the problem, but perhaps the logbook page is not the right way. You have already written, only minority of cachers have noticed this logbook page. And you can only work with your friends on this page. Perhaps it would be better to operate with the VIPs and not with the friends, because you have the VIPs under control but not realy the friends. For example, I have blocked friend requests.

I would prefer a handling on the listing page. The hard work (the loading) of GClh is already done. If you could choose a button like "Show VIPs" over the logs, and if it would be very fast, it seems to be a good way. You can simulate the speed with the field "Search in logtext". Enter for example "hugo" in the field. The logs are available directly.

So my proposal is a new button "Show VIPs" over the logs on listing pages.
What do you mean?

**Comment by PontiacCZ** [comment]
Well, yes, why not, I can see from the issues list that you have a lot of work and I am not willing to give you more. :) A button for filtering the logs for VIPs would be sufficient and elegant, I think. It would actually use the already developed search functionality so I agree.

**Comment by 2Abendsegler** [comment]
We will deliver new version 0.6 on friday evening. It seems to be too narrow to integrate it in this version, so we have to wait of version 0.7. This only for your information.

**Comment by PontiacCZ** [comment]
Yeah, it's OK. No rush needed. :)

**Comment by PontiacCZ** [comment]
You are probably going to add a new filter "VIPs" next to existing ones (Found it, Write notes, Publish etc.) am I right? So when in this work maybe it would be useful to add another button which would restore the original order of logs.

I mean - for instance I filter NM logs. Then I would like to read again all latest logs just like when I originally loaded the page. Currently I do this by refreshing the page (F5). Or is there another way to achive this?

**Comment by 2Abendsegler** [comment]
> You are probably going to add a new filter "VIPs" next to existing ones (Found it, Write notes, Publish etc.) am I right?

Something like this, yes. I'm not sure how we implement it.

> I filter NM logs. Then I would like to read again all latest logs just like when I originally loaded the page. Currently I do this by refreshing the page (F5). Or is there another way to achive this?

With choosing the filter functionality, you are leaving the dynamic log load by scrolling. You can not go back to this after leave in the current program structure. And there seems to be no easy possibility to implement it. And the dynamic log load is a critical functionality, which nobody understand complete. Neither do I. :) We should leave this part as it is.
If the number of logs are not too much, 100 or 200 are already ok, you can use "Show all logs", you know this. It is faster than a refresh page if there are not too much logs.

**Comment by PontiacCZ** [comment]
Oh, I see. I have noticed that logs are loaded dynamically. OK, I agree, ignore my previous suggestion, that was just an idea. :) Will use "show all logs" for caches that don't have tons of logs. ;)

**Comment by 2Abendsegler** [comment]
<ul>
<li>
New: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/254">#254</a>] Filter VIP logs in cache listing:<br>
<img src="../blob/collector/images/v0.7_Screen01.jpg" alt="v0.7_Screen01.jpg"><br>
<br></li>
</ul>

(Only if you want to play with it in front of delivery, you can load it [here](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) as beta version. You can always go back with the official link for [the actual version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).)

**Comment by PontiacCZ** [comment]
Just tried the beta and it works great. Will close this ticket after v0.7 release so people know that this has been worked on.

**Comment by 2Abendsegler** [comment]
I have changed the icon, so we can use the same icon above beside the VIP-list. 
<ul>
<li>
New: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/254">#254</a>] Filter VIP logs in cache listing:<br>
<img src="../blob/collector/images/v0.7_Screen01.jpg" alt="v0.7_Screen01.jpg"><br>
<br></li>
</ul>

**Comment by PontiacCZ** [comment]
I have just run into the cache [Energeticka8](https://coord.info/GC32WHP) which the VIP filter has issues with.

There is only the cache owner in the VIP list and his four logs - Disable, OM and 2 x WM. But the VIP filter shows none of these four.

**Comment by 2Abendsegler** [comment]
Is the owner a VIP?

**Comment by PontiacCZ** [comment]
Well - yes, actually he is since I have checked the **Show owner in VIP list** option and the description says: _"If you enable this option the owner is VIP for the cache..."_

But I know what you mean - he is not in my VIP list.

**Comment by 2Abendsegler** [comment]
Ah, I understand. The old description is not realy right. The owner is not a VIP in this case, he is only a part of the VIP-list for the cache, so you can see, what happened with the cache. The owner is too not marked as a green VIP in the VIP-list and too not in the logs. 
I will change this description.

If you have only the owner in the VIP-list and he is not marked as a green VIP, the filtered VIP logs should be empty.

**Comment by PontiacCZ** [comment]
I understand....  Hhmm, I'm thinking and you're starting to get goose bumps, right? :-D  But I'm gonna say it:

Would it be hard to consider the CO of a particular cache a **real** VIP? So we do not only see his logs in VIP list, but in VIP filter as well? The behavior would be consistent then. One expects the VIP filter to output the same logs he  is seeing in VIP list.

Well, just sayin.... forget it if it is too complicated.

**Comment by 2Abendsegler** [comment]
Your english seems to be very good, as far as I can assess. Sometimes I am not sure, if I understand all of you, because my english is really bad.  

It is not so hard and I have no goose bumps, because I am my own boss. Everything, concerning the GClh, goes over my table. If I get bored with a task, I say, that I do not want to do it. That is really not bad. :)

It seems to be not complicated.

I am not sure, if one expects that. I have not missed something, as we used the VIP icon above the logs to filter the VIP logs. I think you have not missed something too. The starting point was to filter VIP logs that one can have pleasure by reading the logs and showing the pictures of the own VIPs. 
I don't know.  I will sleep about it.

**Comment by 2Abendsegler** [comment]
It is implemented. You were not alone with your meaning, but me. :)

<ul>
<li>
New: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/254">#254</a>] Filter VIP logs in cache listing:<br>
<img src="../blob/collector/images/v0.7_Screen01.jpg" alt="v0.7_Screen01.jpg"><br>
<br></li>
</ul>

(Only if you want to play with it in front of delivery, you can load it [here](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) as beta version. You can always go back with the official link for [the actual version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).)

**Comment by PontiacCZ** [comment]
Thank you so much, I've just checked the beta and it works as expected. :)
