### ISSUE TITLE
[Search Map] GClh slow down the map

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2540]
### Describe the bug

With the GClh that map is very laggy on dragging. If the GClh is not running, the map can be dragged smoothly.
Here is a screenshot of my CPU with the GClh:
![grafik](https://github.com/2Abendsegler/GClh/assets/50927164/be8be561-8dae-4d37-ab7e-ab1f6cd189af)
Here without:
![grafik](https://github.com/2Abendsegler/GClh/assets/50927164/5269f31a-48c8-491a-8d7a-599e2cc60010)

### Expected behavior

The GClh shouldn't slow down the Map

### OS

Linux

### Browser

Firefox

### GClh Version

.

**Comment by 2Abendsegler** [comment]
@capoaira 
Ich kann das im Moment nicht nachstellen.

Wir haben mit v0.15 zuletzt etwas direkt an der Search Map gemacht. Das war der Komoot Button und css Änderungen im Kopf der Sidebar, Buttons wieder richtig ausgerichtet. Seitdem nichts mehr.

Ist das Verschieben immer langsam und hakelig, oder lässt das nach gut 30 Sekunden nach? 
Hast du mal alle anderen Scripte und Add Ons deaktiviert, nicht das wir von etwas anderem behindert werden?

**Comment by capoaira** [comment]
Moin,
tut mir leid, das hier hatte ich total vergessen.
Ich habe heute mal etwas getestet und tatsächlich ist es die Kombination von Firefox (Version 121.0.1 (64-Bit)) auf Linux (Mint LTS Cinnamon). Auf Windows sowie auf Linux unter Chrome läuft es flüssig.

Leider ist das auch nicht das einzige Problem, was ich mit Firefox auf meiner Linux Distro habe. Werde wohl oder übel auf Chrome wechseln. 

Ich schließe das Issue mal, da hier der Aufwand nicht im Verhältnis zum Nutzen steht. Wenn ich Firefox weiter nutze, ruckelt es halt ein bisschen.
