### ISSUE TITLE
[Log Form] Log template "Last Cache-Log" inserts old Log instead of last one

### ISSUE THREAD

**Issue by gcPhil** [2Abendsegler/GClh#2542]
### Describe the bug

I am logging caches and try to insert my Last-Cache-Log with the Log template function.
But it inserts the text of an old DNF log (that I wrote in the first days of November) instead of my last logs that I made before some minutes.
Saving the last log text does not seem to work for me since one of the last updates

### OS

Windows

### Browser

Firefox

### GClh Version

0.15.3

**Comment by 2Abendsegler** [comment]
Danke für das Melden des Bugs.

Ich kann das Problem im Moment nicht nachstellen. 

Zum Speichern des "Last Logs" bauen wir beim "Post" Button ein Klick Event ein, das bewirkt, dass beim Klick auf den Button auch der Loginhalt in einem GClh Parameter gespeichert wird. Es scheint mehrere mögliche Fehlerquellen zu geben. 
1. Das Klick Event wird nicht aufgebaut, weil der GClh vorher abgebrochen wird. Dazu sollte es entweder vom GClh oder von der Webseite selbst eine Fehlermeldung in der Konsole geben. 
2. Das Klick Event wird durch Seitenänderungen von GS zerstört. Im Bereich des Buttons kommen solche Effekte immer mal wieder zu Beginn der Aufbaus der Webseite vor. Deshalb bauen wir das Klick Event 10 Sekunden lang immer wieder auf, wenn es zerstört wurde. Theoretisch könnte es auch nach dieser Zeit zu Seitenänderungen kommen, wir haben solche aber bisher noch nicht beobachten können.
3. Die Ausführung des "Post" Buttons erfolgt so schnell, dass das Klick Event nicht mehr ausgeführt wird. Bei einer super schnellen Internetverbindung wäre das denkbar. Ich halte es aber für nicht besonders wahrscheinlich.

@gcPhil
Zu 1. Zuerst könntest du mal in ein Log Formular gehen und dann bitte die Konsole mit der Funktionstaste F12 aufrufen. Du musst im Log Formular nichts eingeben. Wähle dort bitte mal den Reiter "Konsole" aus und aktiviere eine Zeile tiefer rechts das Feld "Fehler". Falls in der Liste etwas in rot dargestellt wird, bitte mal entsprechendes per Screenshot hier einstellen. Die Liste kann über mehrere Seiten gehen.
Falls nichts in rot dargestellt wird, die Webseite mit Funktionstaste F5 aktualisieren und anschließend die Liste wieder prüfen und rotes gegebenenfalls hier einstellen. Letzteres drei, vier mal wiederholen solange noch nichts rotes vorhanden ist.

Zu 2. Anschließend können wir eine Testversion zur Verfügung stellen, mit der wir prüfen können, ob das Klick Event aufgebaut wurde. Dazu aber erst später ... oder morgen.

**Comment by gcPhil** [comment]
@2Abendsegler Vielen Dank für die schnelle und ausführliche Antwort!

- Beim weiter loggen heute ist mir aufgefallen das die "Last Logs" nun doch manchmal korrekt gespeichert sind und manchmal nicht. Durch deine Erklärung zum Vorgehen des Scripts habe ich mir einen unfachmännischen Erklärungsansatz zusammen gereimt: Ich logge die Funde über die "Drafts"-Seite. Dort ist der Post-Button seit neuestem inaktiv ausgegraut bis man eine erste Eingabe im Textfeld gemacht hat (oder den Last Log um mindestens ein Zeichen verändert hat).
Falls Euer Parameter nur in den aktiven Button eingefügt werden kann (bzw beim späteren aktiv-schalten zerstört wird), hätte man nur 10 Sekunden Zeit mit den Textänderungen zu beginnen, was das "manchmal funktionierts, manchmal nicht" erklärten könnte.

- Unabhängig davon sende ich anbei einen Screenshot den ich gerade von der Konsole auf der Log-Seite erstellt habe.

![screenshot](https://github.com/2Abendsegler/GClh/assets/2893036/879522da-c02b-4fc4-a8a8-f405dd1926b1)

**Comment by 2Abendsegler** [comment]
Die Daten im Screenshot sind unauffällig. Da das Speichern der Last Logs aber manchmal auch funktioniert, könnte es sich hier aber auch genau um einen solchen funktionierenden Fall handeln. Hier müsste man sich die Konsole häufiger ansehen und beobachten, bei welchem Inhalt das Speichern funktioniert und ob es überhaupt einen anderen Inhalt in der Konsole gibt. Aber stellen wir das mal zurück.

Ich kann nur dann bei einem Draft einen grauen Post Button erzeugen, wenn kein Text mitgegeben wird. Sind deine Drafts ohne Text? 

Das Klick Event wird auch bei grauem Button aufgebaut. Wechselt der Button die Farbe verschwindet das Klick Event manchmal, aber nicht immer. 

Ich überlege gerade, ob viel dagegen spricht, den Aufbau des Klick Events zeitlich nicht zu begrenzen. Womöglich wäre das eine einfache Lösung des Problems. Für die Prüfung, ob die letzte Eingabe vom GClh stammt, sollte das dann identisch erfolgen. @capoaira Bist du online? Was meinst du?

**Comment by capoaira** [comment]
Den Aufbau zeitlich nicht zu begrenzen fühlt sich sehr unsauber an. Ich denke aber auch, dass das die einfachste Lösung wäre.
Da wir scheinbar mehrfach die Events, wie auch andere Dinge initialisieren müssen, würde eigentlich ein MutationObserver Sinn machen, oder? Ein entsprechender Umbau wäre aber vermutlich unnötig Zeitaufwendig.
Wir könnten einen MutationObserver aber auch nur für die beiden Problem-Funktionen nutzen, dann würde sich der Aufwand (hoffentlich) in Grenzen halten.
 
Ich bin aktuell nicht in Bremen und kann daher nichts für den GClh machen. Zudem werde ich, wenn ich zurück bin, weiterhin sehr von der Uni eingebunden sein. Zeit zum Testen werde ich finden, zum entwickeln aber leider nicht :-(

**Comment by 2Abendsegler** [comment]
@gcPhil
Bevor wir größere Umstellungen machen, habe ich eine kleine Anpassung gemacht, weil das Speichern des Last Logs leicht anders realisiert ist als zwei vergleichbare Themen (Warning last changes by GClh, F2). Vielleicht kannst du deine nächsten Logs mit der kleinen Anpassungen erledigen. Bitte prüfe nach jedem Log, ob das letzte Log gespeichert wurde.

[Hier geht es zu der kleinen Anpassungen.](https://github.com/2Abendsegler/GClh/raw/09d6360f31b1d5022b9e2db7a427dc6a6dc993e9/gc_little_helper_II.user.js)
[Hier geht es wieder zurück zum Original.](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js)

**Comment by 2Abendsegler** [comment]
@gcPhil
Ich noch mal.
Bitte wenn möglich 10 Sekunden warten, bevor du im Log Formular etwas eingibst.

**Comment by gcPhil** [comment]
@2Abendsegler
Ich habe die Version mit Anpassungen installiert (zumindest nehme ich das an: Nach klick auf den Link zur Version habe ich auf "neu installieren" geklickt und das Tab hat sich daraufhin immer ohne Bestätigung geschlossen).

Leider war das ganze auch ohne großen Erfolg: Vier von vier Log-Texte wurden nicht gespeichert, auch mit 10 Sekunden Wartezeit vor der Eingabe.

Ach ja, genau meine Drafts enthalten keinen Text, es sind reine "schnelle offline logs" ohne Notiz, die ich aus c:geo hochlade.

**Comment by 2Abendsegler** [comment]
@gcPhil 
Danke für die Tests.
Um zu überprüfen, ob du die kleinen Anpassungen wirklich installiert hast, kannst du ein Log Formular aufrufen und dann in der Konsole schauen ob "GClh save last log: Build Event" ausgegeben wird.

**Comment by gcPhil** [comment]
@2Abendsegler 
Ja, "GClh save last log: Build Event" wird ausgegeben.

**Comment by gcPhil** [comment]
Kurze Rückmeldung: Ich bin wieder mal am Loggen, mittlerweile läuft dabei GClh v0.15.4.
Immer noch wird der Log-Text mal gespeichert, mal nicht. Um genau zu sein hat es gerade 4x am Stück funktioniert, danach 4x am Stück nicht. Gefühlt habe ich dabei nichts anders gemacht. Auch ob Text-Notizen in den Draft-Logs gespeichert sind oder nicht scheint dabei keine Rolle zu spielen. Außerdem konnte ich das Problem in der Zwischenzeit auch sporadisch bei anderen Cachern auf anderen Rechnern sehen.

**Comment by 2Abendsegler** [comment]
@gcPhil
Moin,

sorry, dass wir uns so lange nicht mehr um das Problem gekümmert haben.
Ich gehe mal davon aus, dass das Problem leider noch existiert.

Mit der nächsten Version des GClh in Kürze haben wir das Click Event für das Speichern des letzten Log Textes komplett so umgestellt, wie wir es bei unseren anderen Click Events auch realisiert haben. Wenn das nun nicht funktioniert, würde das nahelegen, dass auch unsere anderen Click Events nicht immer funktionieren.

Kannst du das Thema bitte nach der Installation der nächsten Version beobachten und hier noch mal Feedback geben. Danke.
Das Issue bleibt noch offen.

LG Frank

**Comment by 2Abendsegler** [comment]
@gcPhil
Moin,

konntest du das Verhalten beim Loggen bezüglich des "Last Cache-Log" Templates nochmal beobachten?

LG Frank

**Comment by gcPhil** [comment]
Moin Frank,
sorry für die späte Antwort. Ich habe ehrlich gesagt einige Zeit nicht mehr im Browser geloggt, aber ich werde das ganze kommene Woche noch mal testen.

**Comment by gcPhil** [comment]
**Sooo, ich habe heute eine ganze Weile mit V. 0.16.2 geloggt und konnte den Fehler nicht mehr feststellen.**
Vielen Dank noch mal für die ganze Arbeit die du in die Behebung gesteckt hast!

**Comment by 2Abendsegler** [comment]
Vielen Dank für das Feedback. Ich werde dann das Issue schließen.

Wenn ich ehrlich bin, bin ich mir nicht sicher, dass das Problem tatsächlich behoben ist. Bitte melde dich unbedingt noch mal, falls das Problem wieder auftaucht. Es gibt noch andere Möglichkeiten, wie wir es realisieren können.
