### ISSUE TITLE
[Cache Listing] Show bigger avatar image in cache listing log.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#2559]
### Describe the solution you'd like

[Comment of @f-o in issue 349](https://github.com/2Abendsegler/GClh/issues/349#issuecomment-1956990062):
> I really love this feature, but it's always when I'm 100 logs deep in the page, that I find an avatar I'd want to have expanded, prompting me to scroll back to the top, click the button, and find my way to the log again.
> 
> Is there a way we could have this enabled by default, for all logs, and have it automatically fetch new bigger versions as logs are being returned on the page? @2Abendsegler

**Comment by 2Abendsegler** [comment]
@f-o
Hi,

I understand the problem. I feel the same way sometimes.

However, I would no longer implement the existing feature in this way today because it puts too much strain on the GS servers if hundreds of large images of the avatars are retrieved. In my opinion, an expansion so that all large images of the avatars are always loaded is no longer conceivable also.

What we could perhaps do is a new feature that allows you to load the large image of the avatar in a log by clicking on the avatar. At the moment the profile of the user is linked by clicking on the avatar. Because the name of the user is also linked to the profile of the user we could give the click on the avatar a new meaning.

Would that help?

**Comment by f-o** [comment]
> @f-o Hi,
> 
> I understand the problem. I feel the same way sometimes.
> 
> However, I would no longer implement the existing feature in this way today because it puts too much strain on the GS servers if hundreds of large images of the avatars are retrieved. In my opinion, an expansion so that all large images of the avatars are always loaded is no longer conceivable also.

Thank you for taking in this suggestion!

I fully understand where you're coming from.
It is also very rarely that I actually need the avatar in full size, but when I do I do.

Instead of fetching all the images, regardless of whether they are needed or not, would it be possible to add an event listener on avatar hover, and only then fetch the image in question at that time?
I haven't gone through all of your code, so feel free to correct me if I'm wrong, but doing it this way would mean that you would only get the resources that are needed, when they are needed, and not everything on the page.

If you're using some framework to show the floating images, and they may need an image to load, you could render the page with a small dummy image, from some open cdn, and replace the source whenever the avatar has successfully been fetched.

I think this would be the best solution to this problem, while keeping overall requests down.

**Comment by 2Abendsegler** [comment]
I cannot replace the current feature with the button above the logs with a worse feature (because it involves waiting time) without good reason.

Your actual request could possibly also be triggered by moving the mouse over the avatar instead of clicking. We still have to check that.

**Comment by f-o** [comment]
> Your actual request could possibly also be triggered by moving the mouse over the avatar instead of clicking. We still have to check that.

Yes, that's exactly what I meant.

When the mouse is hovered over the avatar, we fetch the image (and only that one image) from the GS server, and shows it in the little overlay box.
This would work very well, and only cost 1 request when needed.

**Comment by f-o** [comment]
I fear you may have misunderstood my initial reply, hence the "cannot replace with a worse feature".

To better explain what I meant, I've gone ahead and created my own little userscript, which does exactly like we talked about, and is very gentle with the AWS resources.

This is nothing more than a hacky workaround though, developed to be used alongside of your little helper, and I'm pretty sure this is the exact same thing you had implemented with your button initially, just wrapped in an event listener instead.
There are some bugs in this, which I'm not going to be addressing, as it's just made to solve my problem here and now. Hopefully it can be useful for your proper tool.

```js
// ==UserScript==
// @name         GC Image Hover UserScript
// @namespace    http://gc.soon.to
// @version      0.1
// @description  Enlarge user avatars in logs on Geocaching.com
// @author       Fox
// @match        https://www.geocaching.com/geocache/*
// @grant        none
// ==/UserScript==

(function () {
    'use strict';

    // Add CSS to the page
    // Create a style element
    var style = document.createElement('style');
    style.type = 'text/css';
    style.innerHTML = `
        a.gclh_thumb:hover {
            white-space: unset;
            position: relative;
        }
        a.gclh_thumb {
            overflow: visible !important;
            display: unset !important;
            max-width: none !important;
        }
        a.gclh_thumb span {
            white-space: unset !important;
            visibility: hidden;
            position: absolute;
            top: -310px;
            left: 0px;
            padding: 2px;
            text-decoration: none;
            text-align: left;
            vertical-align: top;
        }
        a.gclh_thumb:hover span {
            visibility: visible;
            z-index: 100;
            border: 1px solid #8c9e65;
            background-color: #dfe1d2;
            text-decoration: none !important;
        }
        a.gclh_thumb img {
            height: 48px;
        }
        .gclh_max {
            height: unset !important;
            vertical-align: unset !important;
            margin-right: 0 !important;
            max-height: 600px;
            max-width: 600px;
        }
    `;
    // Append the style element to the head of the document
    document.head.appendChild(style);

    // Extract the GUID from the image URL
    function extractGuidAndExtensionFromImageUrl(imageUrl) {
        // Split the URL by "/"
        let parts = imageUrl.split('/');
        // The GUID is the second to last part of the URL
        let guidAndExtension = {
            guid: parts[parts.length - 1].split('.')[0],
            extension: parts[parts.length - 1].split('.')[1]
        };
        return guidAndExtension;
    }

    // Use event delegation to handle "mouseover" for dynamically loaded images
    document.addEventListener('mouseover', function (event) {
        let target = event.target;
        if (target.matches('.logOwnerAvatar a img')) {
            // Check if the sibling span exists
            let siblingSpan = target.parentNode.querySelector('span');
            // Check if the sibling exists, and that the parent is not a span element
            if (!siblingSpan && target.parentNode.tagName !== 'SPAN') {
                // Add proper GClt class to the parent
                target.parentNode.className += ' gclh_thumb';
                // Create the new span
                let newSpan = document.createElement('span');
                // Get the image source
                let imgSrc = target.getAttribute('src');
                // Extract the GUID from the image URL
                let imageData = extractGuidAndExtensionFromImageUrl(imgSrc);
                // Create the new image
                let newImg = document.createElement('img');
                newImg.className = 'gclh_max';

                newImg.src = 'https://s3.amazonaws.com/gs-geo-images/' + imageData['guid'] + '.' + imageData['extension']; // Placeholder for the new img src
                newSpan.appendChild(newImg);
                target.parentNode.insertBefore(newSpan, target.nextSibling);
            }
        }
    });
})();
```

**Comment by 2Abendsegler** [comment]
@f-o
Hi,

we have implement the feature. If you want, you can test it in advance.

[Here is an temporary feature version.](https://github.com/2Abendsegler/GClh/raw/48b098e5ba6a31cc77a6ab11f1d9af85155ea252/gc_little_helper_II.user.js) (Other changes are already included there.)
[Here you come back to the current version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) in case the feature version causes problems.

Cheers Frank

**Comment by f-o** [comment]
Very well done.

And thank you for understanding what I initially meant. I feel like there was a bit of a language barrier, which caused some misunderstandings, but I'm glad we got there in the end.

Vielen Dank!
