### ISSUE TITLE
[Log Form] Enlarge width of form

### ISSUE THREAD

**Issue by ColleIsarco** [2Abendsegler/GClh#2565]
### Is your feature request related to a problem? Please describe

A log view and the formualr for editing a log is small compared to the available width of my browser window. I would like to have as wide as possible to fit the window-width of the browser.
I think that a similar featue already exists for other pages shown on Groundspeak.

### Describe the solution you'd like

I have opened a pull-request for the same. It set the width to 90percent of the width of the browser

**Comment by 2Abendsegler** [comment]
Global:
![Screen03](https://github.com/2Abendsegler/GClh/assets/22332216/7ce68efc-88c7-457f-a16d-5b43b31e7ac4)
Log:
![Screen01](https://github.com/2Abendsegler/GClh/assets/22332216/ebe66be5-52ae-44c8-b4b0-38ff85ab9fc9)


Before / Larger page width:
![Screen05](https://github.com/2Abendsegler/GClh/assets/22332216/251263a7-94b0-4556-9fbe-2ad3100503f3) ![Screen04](https://github.com/2Abendsegler/GClh/assets/22332216/2b5fcb8d-69de-44ac-91af-9b45a6f56924)
