### ISSUE TITLE
[Cache Listing / Search Map / Browse Map] addElevationToWaypoints_GeonamesElevation(): json.geonames is undefined

### ISSUE THREAD

**Issue by Fassenachterin** [2Abendsegler/GClh#2567]
### Describe the bug

![Screenshot 2024-03-13 at 13-43-20 Geocaching Geocaching Maps](https://github.com/2Abendsegler/GClh/assets/142675292/9bd76b69-9e45-42a3-a0d1-7a98ca7d0ab7)
Fehlermeldung seit 12.03.2024 beim Aufruf von geocaching.com mit aktiviertem GClh

### OS

Windows

### Browser

Firefox

### GClh Version

0.15.5

**Comment by 2Abendsegler** [comment]
Danke für die Fehlermeldung.

Ich bin schon dran, hatte den Fehler auch gestern schon bemerkt, nur ist er dann irgendwann wieder verschwunden. Heute ist er nun wieder gegen 12:30 aufgetaucht.

**Comment by 2Abendsegler** [comment]
Off-Topic:
Welches Script ist da noch im Header sichtbar?

**Comment by 2Abendsegler** [comment]
Es scheint so, dass die API von geonames die Verarbeitung von mehr als einem Wegpunkt nicht immer erlaubt. Womöglich ist die Anzahl solcher Aufrufe limitiert worden.
Beispielsweise führen folgende Aufrufe zeitweise zum Fehler:
`http://api.geonames.org/astergdemJSON?lats=49.6978,49.69598&lngs=8.6529,8.64937&username=gclh `  
`http://api.geonames.org/astergdemJSON?lats=49.6978&lngs=8.6529&username=gclh`
Folgender Aufruf funktioniert dagegen immer:
`http://api.geonames.org/astergdemJSON?lat=49.6978&lng=8.6529&username=gclh`
Wie wir das genau beheben sollen, weiß ich nicht.

In einem ersten Schritt werde ich die Fehlermeldungen durch geonames nicht mehr im Header des Seitenkopfes ausgeben. Das war sowieso geplant, weil es einfach zu häufig zu Problemen kommt, die nicht in unserem Verantwortungsbereich liegen. Bei den Features zur DropBox hatten wir das vor langer Zeit auch aus gleichem Grund umgestellt.

Anschließend können wir uns überlegen, wie wir hiermit und mit #2107 weiter verfahren wollen.

**Comment by 2Abendsegler** [comment]
Das Problem taucht seit mindestens 3 Tagen nicht mehr auf. Ich habe über die Tage hinweg fast stundenweise geprüft. Zuvor war es so, dass der Fehler gegen Mittag bis etwa gegen 17 Uhr immer reproduziert werden konnte. Ich dachte ja eigentlich dass es sich um eine Limitierung der Anzahl der Mehrfachaufrufe handelt, war ja auch vielleicht so. Auf jeden Fall lässt sich das Problem im Moment nicht mehr nachstellen. 
Ich schließe das Issue.
