### ISSUE TITLE
The GC-little helper gave under Edge the "already open error"

### ISSUE THREAD

**Issue by NordicRoller23** [2Abendsegler/GClh#2573]
### Describe the bug

The GC-little helper gave under Edge the "already open error"
Version GC little Helper II   Version   0.15.5
running with Tampermonkey only.

Thanks a lot for help.

### OS

Windows

### Browser

Edge

### GClh Version

0.15.5

**Comment by 2Abendsegler** [comment]
Hi,
thank you for your report.

I just tried this on Edge. Unfortunately I can't reproduce this error.

Can you please briefly answer the following questions:
1. Have you been using the GClh for a long time or is this your first time using it?
2. Since when does the error occur?
3. Which script manager and with version do you use?
4. Can you please give us a screenshot with this error? Please take a screenshot of the entire browser window with address bar and icons.

**Comment by Eiich** [comment]
Hi 2Abendsegler,

Thanks alot for the quick answer.

I used the foloeing tools before and now again with Win10 and Firefox:
Also with different monkeys but with the working result. 
Corrected Coords - version     0.8
GC Tour 4.29
Littel Helper II 0,15,5

With the PC change to Win11 The GC-tour and Corrected Cords are working well with Edge.
With the Firefox I get also problems with the corrected cords, that is the reason I change to Edge.
With Edge the Little Heleper don´t show my me frineds.
The double opening I found and fixed now.
I had 3 Monkeys running and dont realized that not shown Tampermonky with Version  5.0.6192 that was hidden
But the further etst shows now that no Monkey is able to list the frieds with found or not found.
Can you help me here as well ?.
Please find attached a big JPG-file with all 3 different Monkonkeys and all with no friends.

Thanks for help, I like the function of the little helper and will not stop using it with Win11.
![Little-Helper - Over view](https://github.com/2Abendsegler/GClh/assets/83064015/2cbc84bd-c65a-4f20-bdec-9caa7547bf46)

**Comment by 2Abendsegler** [comment]
Die Freunde werden nicht automatisch bei den VIP Listen angezeigt. Du kannst einen Geocacher als VIP kennzeichnen indem du auf das VIP Icon klickst. Das VIP Icon findest du im Anschluss an den Namen des Geocachers, beispielsweise in den Logs, beim Owner im Cache Listing oder auch auf der Freunde Seite. Wenn du alle Freunde als VIP kennzeichnen möchtest, dann geht das am einfachsten, wenn du auf die Freunde Seite gehst und dort alle Freunde mit je einem Klick auf das VIP Icon dafür vorsiehst. 

War das deine Frage und ist die Frage damit geklärt?

**Comment by Eiich** [comment]
Hallo 2Abendsegler,
Danke für die Erleuterung des VIP, dies ist bei einigen aktiviert wird aber leider unter Win11 in Edge bei keinem Monkey angezeigt.
Ich hoffe Du hast noch eine Idee und die Möglichkeit dies zu testen.

Vielen Dank für die Unterstützung.

**Comment by Eiich** [comment]
Hallo und Entwarnung,
warum auch immer mußte ich auf dem Win11-PC die Freunde neu aktivieren.
Damit funktionierte es auf Anhieb. 
DANKE - DANKE - DANKE   :-)

**Comment by 2Abendsegler** [comment]
Danke für das Sponsoring. 😀

Hattest du die Einstellungen vom GClh per Dropbox oder so automatisch übernommen?

**Comment by Eiich** [comment]
Sorry, das weis ich leider nicht, ich habe die Scripte zum Teil manuell in den Code hineinkopiert.
Die Appdatas habe ich von Firefox nicht kopiert da er auf dem Win10 PC komische sache macht.

**Comment by 2Abendsegler** [comment]
Alles klar, dann weiterhin viel Spaß.
Ich schließe das Issue dann jetzt.
