### ISSUE TITLE
[Cache Listing] "Show on ..." and "own copy entries" remain inactive, logs are not loaded.

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [2Abendsegler/GClh#2574]
### Describe the bug

Aktuell werden die "own copy data entries"- und die "Show on ..."-Links (oben rechts unter [Log geocache]) nicht mehr geladen (bleiben grau).
Allerdings lassen sich (zumindest bei mir) auch keine Personal Notes mehr speichern ("Something went wrong. Please refresh the page and try again.") - und das sogar unabhängig davon, ob TM aktiv ist oder nicht.
Da scheint also mal wieder irgendwas im Umbruch zu sein ...

### OS

Windows

### Browser

Firefox

### GClh Version

0.15.6

**Comment by 2Abendsegler** [comment]
Moin,

du hast völlig recht. Dazu gibt es seit gestern Abend auch einen [Bug Report im GS Forum](https://forums.geocaching.com/GC/index.php?/topic/398164-missing-logs-other-elements-from-cache-pages).

Die GClh Features werden deshalb nicht aktiviert, weil die Logs häufig nicht mehr geladen werden. Das ist ein zu erwartendes Verhalten. Insofern ist das im Moment noch kein Fehler bei uns. Werden die Logs dann doch gelegentlich geladen, dann funktionieren unsere Features auch wieder.

**Comment by MagpieFourtyTwo** [comment]
Dass die Hyperlinks oben rechts ohne Logs gar nicht erst aktiviert werden, hätte ich jetzt so nicht erwartet, weil da ja keine (offensichtliche) Abhängigkeit besteht. Aber an irgendwas muss man den Start des Scripts natürlich festmachen. Von daher zumindest nun nachvollziehbar.

Also bleibt für den Moment erstmal nur abwarten. Naja, die Vollprofis von Groundspeak werden das sicherlich hinbekommen. Irgendwann. Ist ja jetzt Wochenende, da können sie morgen beim Frühstück ihre Kinder fragen, wie man das wieder repariert bekommt.

Interessant finde ich die Beobachtung, dass die "Neuerungen" wohl zu einem Grossteil aus "tons of scripts with ad related stuff" bestehen sollen. Was insbesondere für paying members eigentlich ein Unding wäre, mich persönlich vor dem Hintergrund des American way of business aber auch nicht wirklich überraschen würde. Ist aber erstmal nur Information aus zweiter Hand, das schaue ich mir heute abend dann noch mal genauer an. Dankenswerterweise entwickelt Groundspeak ja anscheinend nicht in einem extra Testsystem, sondern lässt uns User direkt Einblick nehmen in die abgefahrene Gedankenwelt ihrer Entwickler. Da kann man als Europäer, die mit parallelen Testaufbauten immer viel Zeit verschwenden, noch einiges lernen.

Besten Dank jedenfalls für die Aufklärung (und natürlich für GClh überhaupt) und noch viel Kraft und Energie für die augenscheinlich anstehende Überarbeitung!

**Comment by 2Abendsegler** [comment]
Es gibt tatsächlich unterschiedliche Abhängigkeiten für die Hyperlinks oben rechts, die wir beachten müssen. Bei den Kartenlinks müssen wir beispielsweise auf die Koordinaten warten, die im Moment ähnlich wie bei den Logs, nicht an der zu erwartenden Stelle abgelegt werden, auch wenn sie am Bildschirm dargestellt werden. So bleibt auch beispielsweise der Copy Button vor den Koordinaten inaktiv und die Höhenermittlung dahinter startet erst gar nicht.

> Dankenswerterweise entwickelt Groundspeak ja anscheinend nicht in einem extra Testsystem, sondern lässt uns User direkt Einblick nehmen in die abgefahrene Gedankenwelt ihrer Entwickler. Da kann man als Europäer, die mit parallelen Testaufbauten immer viel Zeit verschwenden, noch einiges lernen.

Ja genau. Leider scheint das so zu sein.

**Comment by MagpieFourtyTwo** [comment]
Sieht für den Moment gut aus. Und das noch vor dem Familienfrühstück. ;)
