### ISSUE TITLE
Fehlender Wert des Log-Datums in Warnmeldung

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#2615]
### Describe the bug

In einer Warnmeldung wird nicht das Datum eines Logs eingefügt. "You have already logged a "Found it" for this cache on {{dateString, sting}}. Please continue with a different log type or delete this draft"
![TAdtkGlGTJ](https://github.com/2Abendsegler/GClh/assets/7745027/58c3b0b0-0d09-4b29-ab41-5c3e83f6f2d6)

### To Reproduce

1 Drafts hochgeladen
2. Auf das "Stift" Icon geklickt um den Log-Erstellen-Dialog zu öffnen
3. In dem Log-Erstellen-Dialog wird die Warnmeldung mit dem Fehler im Text angezeigt
![yuw7HnNOMB](https://github.com/2Abendsegler/GClh/assets/7745027/61d329b0-2083-479a-b0f4-40c336239963)

### OS

Windows

### Browser

Chrome

### GClh Version

 v0.15.9

**Comment by 2Abendsegler** [comment]
Ich gehe davon aus, dass die eigentliche Fehlermeldung berechtigt ist und es nur um das fehlende Log-Datum in der Fehlermeldung geht. 

Das ist keine Meldung die wir mit dem GClh beeinflussen. Bitte versuch es mal ohne den GClh, der Fehler sollte dann auch erfolgen. Ich habe gerade gesehen, dass der Fehler auch bereits [im Forum gemeldet](https://forums.geocaching.com/GC/index.php?/topic/401246-bug-drafts-page-date-not-displayedresolved/#comment-6148115) wurde.

**Comment by Donnerknispel** [comment]
Ich kann bestätigen, dass das nicht an GClh liegt.
Ich habe Tampermonkey mal ausgeschalten und der Fehler kommt trotzdem. 
Danke für die schnelle Rückmeldung.
Soll ich das Ticket schließen oder willst du das machen?

**Comment by 2Abendsegler** [comment]
> Ich kann bestätigen, dass das nicht an GClh liegt.

Alles klar. Ich schließe das Issue.
