### ISSUE TITLE
Beim "upload drafts", also der Datei geocache_visits.txt, werden bereits hochgeladene Caches erneut hochgeladen

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#2616]
### Describe the bug

Beim "upload drafts" lade ich die Datei geocache_visits.txt vom Oregon 700 hoch. Dabei werden bereits hochgeladene Caches erneut hochgeladen, d.h. es werden immer alle Caches noch einmal hochgeladen.
Das Datum der geocache_visits.txt wird dabei geändert. Ich benutze Windows 11.
Ich muss aktuell immer die geocache_visits.txt nach dem Hochladen löschen.

Ich habe die beiden Einstellungen aktiviert:
Enable draft download feature?
Change log dates of the drafts in download file?

### To Reproduce

1. Menüeintrag "Draft Upload" anklicken
2. Darin "Upload drafts" aufrufen
3. Datei "geocache_visits.txt" im Datei-Explorer auswählen

### Expected behavior

Es sollten nur die Caches hochgeladen werden die seit dem letzten Hochladen dazugekommen sind

### OS

Windows

### Browser

Chrome

### GClh Version

v0.15.9

**Comment by 2Abendsegler** [comment]
Ja, das ist ziemlich nervig. Das ist aber kein Fehler vom GClh und wir können es auch nicht beeinflussen. Der Fehler besteht schon länger und wurde auch bereits [im Forum diskutiert](https://forums.geocaching.com/GC/index.php?/topic/391803-recent-change-on-how-drafts-are-handled/#comments). Leider kümmert sich niemand bei GS um das Problem.

**Comment by Donnerknispel** [comment]
Och nöö. Das Problem geht mir auch schon länger auf den Geist. Ich frage mich langsam, warum ich an Groundspeak Geld zahle.

**Comment by 2Abendsegler** [comment]
> Ich frage mich langsam, warum ich an Groundspeak Geld zahle.

Frag ich mich auch manchmal.
