### ISSUE TITLE
[Mail and Message Form] Placeholder for GC-Code without brackets

### ISSUE THREAD

**Issue by UlliH1** [2Abendsegler/GClh#2617]
### Is your feature request related to a problem? Please describe

Um den GC-Code automatisch in eine Message einzufügen, sieht GCLH nur vor:
"#GCTBCode# : GC or TB code in brackets".
Ich halte es für sinnvoller, den OHNE Klammern einzufügen, also z.B. nur "GCAA04Y".
Begründung:
1.  das Message-Center verlinkt den Code mit dem Cache nur, wenn vor und nach dem Code ein Leerzeichen steht. Die beiden Leerzeichen können natürlich in der Form vom User entsprechend gesetzt werden. Durch die feste Klammerung kann dies aber nicht erreicht werden.
2. dies ist die generischere Lösung. Wenn gewünscht, können ja vom User unmittelbar anschließende Klammern in der Form hinzugefügt werden.

### Describe the solution you'd like

Zwecks Rückwärts-Kompatibilität wäre dazu vielleicht die Einführung eines neuen Platzhalters, z.B: "#GCTBCodeNoBrackets# zu erwägen.
Für meine Bedürfnisse wäre es aber auch vollkommen ausreichend, im GCLH-Skript einfach nur die Klammern in "#GCTBCode# zu entfernen.

**Comment by 2Abendsegler** [comment]
Danke für deine Nachricht. 

Der Platzhalter `#GCTBCode# : GC or TB code in brackets` war nie als Link gedacht. Dass mittlerweile alle möglichen Links immer mal wieder verstümmelt werden und aus keinen Links versucht wird Links zu machen und das etwas unzulänglich, ist leider wahr. Leider scheint das auch bei Mails und Messages unterschiedlich zu sein. 
Scheinbar wird auch immer mal wieder an dieser Stelle gebastelt.

Unter bestimmten Bedingungen, die ich aber nicht genau kenne, funktionieren die GClh Links mit Platzhalter `#GCTBLink# : GC or TB link in brackets` noch. Das Ergebnis sieht dann so aus:
![Unbenannt](https://github.com/2Abendsegler/GClh/assets/22332216/3b74b79b-4065-4edb-b222-3300e65b5dd0)
Daraus ist auch der GC Code ersichtlich und es ist ein Link.

Reicht das nicht vielleicht aus?

**Comment by 2Abendsegler** [comment]
> Es wundert mich sowieso, dass #GCTBCode# als die unflexiblere Lösung implementiert ist: man kann ja jederzeit die Klammern in der Form hinzufügen, aber eben nicht umgekehrt.

Ich glaube das waren damals historische Gründe. Diese Platzhalter gabs schon vor unserer Zeit.

> Ich würde die kurze Version "nur GC-Code" in meinen Messages bevorzugen, wenn sie denn verlinkt würde.

Wir werden das vorsehen. Unklar ist aber derzeit, wann wieder jemand von uns Zeit findet das umzusetzen.

> [edit] natürlich ist es absolut in meiner Verantwortung, dass das von Groundspeak im Message-Center auch tatsächlich als Link behandelt wird.

Ja, war schon klar. Aber danke, dass du es noch erwähnt hast.

**Comment by ChristianGK-GC** [comment]
Ich finde die Idee auch gut.
Vielleicht finde ich eine "Minute" für einen MR.

**Comment by 2Abendsegler** [comment]
Der neue Platzhalter `#GCTBCodeNoBrackets#` wurde eingebaut mit Issue #2622.

Ich werde das Issue schließen.

**Comment by UlliH1** [comment]
Vielen Dank für die sehr zeitnahe Implementierung. Ich nutze dies schon vom ersten Tag an. Klappt prima!
