### ISSUE TITLE
[Cache Listing] Select log types in listing not working for some types.

### ISSUE THREAD

**Issue by barnoldbert** [2Abendsegler/GClh#2620]
### Describe the bug

if I select a specific logtype GClh does not always select the corresponding logs.
it works fine for found-it, did-not-find-it, write-note and vip-logs
but no longer for other log types

### To Reproduce

go to the the lines immediately above the logs
click one of the logtypes.
click the found-it icon ad only the found logs are displayed
but after clicking on the temporarily-disable icon no logs are shown, although they exist.

### Expected behavior

selection should result in displaying all the logs with the type that has been clicked on.

### OS

Windows

### Browser

Firefox, Chrome

### GClh Version

0.15.9

**Comment by 2Abendsegler** [comment]
You're right.
Thanks for reporting the bug.

**Comment by 2Abendsegler** [comment]
We have fixed it already with issue #2621.

A new version will be available in a few days. 

You can install this [advance correction](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js), if you want. However, other adjustments are already included there.

Can you please tell us your geocaching name, so we can mention you on the GClh thank you page?

**Comment by barnoldbert** [comment]
my geocaching name is barnold (without capital!)

**Comment by capoaira** [comment]
I just recognize, that the filter for NMs still not work.

**Comment by 2Abendsegler** [comment]
@capoaira 
Thanks, please check the new PR.
