### ISSUE TITLE
[Cache Listing] `$('#srOnlyCacheNote').html()` is `null`

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2639]
### Describe the bug

From https://www.geoclub.de/forum/t/gc-little-helper-ii-ab-v0-11.81650/post-1391117

### OS

Other

### Browser

Other

### GClh Version

0.16.0

### Additional context

OS and Browser are unknown.

**Comment by 2Abendsegler** [comment]
Ich habe das schon korrigiert, siehe weiteres Issue
