### ISSUE TITLE
[Cache Listing] Two new helpful buttons for waypoints

### ISSUE THREAD

**Issue by dcjkfgdjhd** [2Abendsegler/GClh#2644]
### Is your feature request related to a problem? Please describe

It would be very helpful, if every waypoint in the waypoint list had...

1. a "copy coordinates to clipboard" button
2. a "use these coordinates as corrected main coordinates for the cache" button

### Describe the solution you'd like

See above.

**Comment by 2Abendsegler** [comment]
Hi,
can you please explain in which cases you want to use a waypoint as corrected main coordinates for a cache?

**Comment by dcjkfgdjhd** [comment]
Two examples:

1. When you started a multicache and did not complete it on the first try. You can then choose the next uncompleted stage as the next uncorrected coordinates, for the next time.
2. For "map art" caches that use fake coordinates to draw images on the cache map, where you have to search for the "Final" waypoint and copy these coordinates into the corrected coordinates.

**Comment by 2Abendsegler** [comment]
> 2\. For "map art" caches that use fake coordinates to draw images on the cache map, where you have to search for the "Final" waypoint and copy these coordinates into the corrected coordinates.

I know some map arts, but I have never seen such a system of caches where the caches already contain a waypoint that represents the final destination. Do you have an example please?

**Comment by dcjkfgdjhd** [comment]
All the caches belonging to this annoying series for example: https://coord.info/GCA8NDB

**Comment by 2Abendsegler** [comment]
The second button is quite special and, in my opinion, will not be used by many users. I don't know if we should implement this feature.

**Comment by dcjkfgdjhd** [comment]
Of course, it was only a suggestion.
