### ISSUE TITLE
[Cache Listing] Add "Show on Locus Maps"

### ISSUE THREAD

**Issue by UlliH1** [2Abendsegler/GClh#2657]
### Describe the solution you'd like

Sorry, noch ein Pull request, der (hoffe ich mal) mehr User betrifft, und damit relevanter ist:
Analog zu "Show on Flopp's Map => Openstreetmap" sollte ein Tag "Locus Maps" hinzugefügt werden, der den Cache (möglichst auch mit allen seinen Wegpunkten) in Locus Maps anzeigt.
Am PC wird der zwar wahrscheinlich ziemlich irrelevant sein, aber auf dem Handy fände ich dies sehr praktisch.
Tatsächlich würde dies ja auch meinen Use-Case meines vorherigen [Pull requests](https://github.com/2Abendsegler/GClh/issues/2656) lösen.
Entsprechende Schnittstellen dazu müsste es in  Locus Maps geben, z.B. erstellt [Coordinate Joker](https://play.google.com/store/apps/details?id=com.github.siggel.coordinatejoker) (mehrere) Wegpunkte in Locus Maps. Coordinate Joker ist übrigens auch auf Github gehostet, s. [hier](https://github.com/siggel/coordinatejoker).

**Comment by 2Abendsegler** [comment]
Locus Maps ist eine App für Android. Um Daten zwischen dem GClh und Locus Maps auszutauschen, müssten wir Entwicklungen für Android Geräte durchführen und diese Funktionalität sogar für nicht Android Geräte abklemmen. 

Wir unterstützen zur Zeit keine Android Geräte, auch wenn das Script mit nur wenigen Einschränkungen auch unter Android funktionsfähig ist. Details dazu gibt es [hier](https://github.com/2Abendsegler/GClh/blob/collector/docu/tips_installation.md#android_de). 

Bitte gib kurz Bescheid, ob ich die Anforderung richtig verstanden habe.

> Sorry, noch ein Pull request, der (hoffe ich mal) mehr User betrifft, und damit relevanter ist

Kein Problem, dafür gibt es diese Umgebung. 😉

**Comment by UlliH1** [comment]
Ja, du hast das richtig verstanden. Schade! Aber, trotzdem, danke!
