### ISSUE TITLE
[Cache Listing] Funktionsprobleme unter Chrome

### ISSUE THREAD

**Issue by diundbi** [2Abendsegler/GClh#2660]
### Describe the bug

Seit einigen Tagen habe ich folgende Probleme mit der Webseite geocaching.com:
1. in der Map-Ansicht können keine Caches mehr angeklickt werden
2. in der Detailansicht zu einem Cache fehlt der Button "korrigiere Koordinaten" rechts neben den Ausgangskoordinaten. Beim Laden der Seite wird der Bleistift kurz dargestellt, verschwindet aber sofort wieder.
3. ebenso in der Detailansicht werden die Logeinträge nicht mehr dargestellt.

Diese Probleme ergeben sich sowohl bei der Nutzung von Edge, als auch bei Chrome, auf allen Rechnern (drei Notebooks, alle mit Windows 11).

Somit ist ein Arbeiten derzeit nur am Smartphone (Android) möglich.

Sind euch diese Probleme bekannt und wenn, ja, gibt es einen Workaround?

Viele Grüße
Dieter

### OS

Windows

### Browser

Chrome, Edge

### GClh Version

0.16.2

**Comment by 2Abendsegler** [comment]
Hallo Dieter,

die Probleme sind uns bisher nicht in Zusammenhang mit dem GClh bekannt.
 
Ich habe gerade mal versucht die drei Probleme unter Chrome nachzuvollziehen. Ich konnte zwar deine Probleme nicht nachvollziehen, allerdings hatte ich mit zahlreichen anderen Problemen zu kämpfen. Ich habe dann alle Browser Daten gelöscht und dann funktionierte alles wieder, völlig dubios. In Firefox gab es keine Probleme. Edge habe ich nicht getestet.

zu 1. Handelt es sich hier um die alte Karte? Falls ja: Hier gibt es immer mal wieder Probleme, derart, dass die Cache Icons nicht angewählt werden können. Im Original Forum gibt es dazu Meldungen. Wenn man raus oder rein zoomt funktioniert es aber in der Regel bei irgendwelchen Zooms. Das ist ein Problem unabhängig von Browsern und unabhängig vom GClh.

zu 3. Auch dieser Problem wurde im Original Forum bereits angesprochen. Ich glaube das Problem ist ebenfalls unabhängig von Browsern und auch unabhängig vom GClh.

Gegebenenfalls kann ich versuchen die Links im Original Forum zu finden. Bitte gib Bescheid, falls das hilfreich erscheint.

Versuch mal folgendes um das Problem zu beseitigen bzw. zu verifizieren ob es mit dem GClh zu tun hat:
1. Bitte lösche mal den Chrome Browser Speicher auf einem deiner Rechner und versuche es dann erneut.
2. Bitte schalte mal Tampermonkey ab und versuche es dann erneut. Bestehen die Probleme auch ohne GClh?
3. Bitte prüfe mal bei deinen Cookie Settings (https://www.geocaching.com/account/settings/cookies) ob du alle Cookies akzeptiert hast. Nach der Anwahl des Links "Einwilligung ändern" wählen.
4. Kannst du vielleicht mal mit Firefox testen, falls du ihn auf einem Rechner hast?

LG Frank

**Comment by diundbi** [comment]
Moin Frank,

vielen Dank für deine schnelle Antwort. Ich werde in den nächsten Tagen
einmal deine Tipps ausprobieren (bin derzeit unterwegs) und melde mich dann
wieder.

Liebe Grüße
Dieter

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Do., 10. Okt. 2024 um 23:07 Uhr schrieb 2Abendsegler <
***@***.***>:

**Comment by 2Abendsegler** [comment]
Es gibt weitere Erkenntnisse zu den fehlenden Logs, also Punkt 3 im ersten Beitrag. Ich habe eine weitere Fehlermeldung per Nachricht erhalten:

---
... es gibt tatsächlich einen Fehler, der mit hoher Wahrscheinlichkeit vom GClh stammt:
`Uncaught TypeError unsafeWindow.$(...).tmpl is not a function`
![90e0b591-59f7-4d3d-b3b7-cbb7f9093ff5](https://github.com/user-attachments/assets/ec4ead1d-087f-4f94-9ac1-9351dd5b7a55)

Scheinbar bricht der GClh beim Erzeugen der Logs ab. Wie es dazu kommt, kann ich im Moment nicht ausmachen, weil wir zuvor eigentlich alles notwendige geprüft haben sollten. Genau genommen verstehe ich aber gerade das Coding überhaupt nicht. 😂

Vielleicht aus Zeile 8826: 
`unsafeWindow.$("#tmpl_CacheLogRow_gclh").tmpl(initialLogs.data[i]).appendTo(newBody);`

Vermutlich funktioniert auch einiges andere beim GClh nicht, denn deine veraltete GME Version verabschiedet sich auch. Sie ist darauf angewiesen, dass der GClh den Header neu aufbaut.

(6a. GME v0.8.2 ist veraltet und enthält zahlreiche Fehler. Es gibt eine überarbeitete Version: GME v0.8.2.2As.8, dort sind alle derzeit bekannten Fehler beseitigt. Info dazu: https://github.com/2Abendsegler/GME#geocaching-map-enhancements-gme--1 . Diese überarbeitete Version wird als neues Script installiert, alle anderen Versionen von GME müssen deaktiviert sein, sonst funktionierts nicht. Falls du also möchtest installiere v0.8.2.2As.8 mit folgendem Link https://github.com/2Abendsegler/GME/blob/collector/Geocaching_Map_Enhancements.user.js .)

7a. Wenn der Fehler auftritt, wird dann im Header der Seite das Menü Linklist angezeigt?

8a. Kann es sein, dass die Cacheseite mehr als 10 Sekunden benötigt, bis sie geladen ist? Gut einschätzen lässt sich das mit dem "Aktuelle Seite neu laden" Icon neben der Adresszeile im Browser. Ist das Icon da, ist die Seite fertig geladen.

9a. Bitte aktualisiere Tampermonkey und teste dann noch mal.

Ich werde die Erkenntnisse mit in das bestehende Ticket 2660 ( https://github.com/2Abendsegler/GClh/issues/2660 ) aufnehmen,
dort ist unter Punkt 3. das gleiche Problem benannt.

Ich weiß leider nicht, wann jemand dazu kommt, sich des Problems anzunehmen und ob wir überhaupt eine Lösung finden, solange wir die Sache nicht selbst nachstellen können.

LG
Frank
 
---
Zuvor bereits angesprochene Punkte:

1a. Vielleicht kannst du noch prüfen, dass nur der GClh läuft und sonst keine Scripte und auch keine Add-ons, außer Tampermonkey? Manchmal kommen sich Erweiterungen einfach gegenseitig in die Quere, das wollen wir gerade mal ausschließen.
Andere Erweiterungen scheinen keinen Einfluss zu haben. Wenn alle abgeschaltet sind, treten die Fehler auch auf wie unter Punkt 2a beschrieben.

2a. Tritt der Fehler immer auf oder nur manchmal? Wähle bitte mal verschiedene Caches an.
Der Fehler tritt nicht immer auf auf.

3a. Wenn der Fehler wieder aufgetreten ist, dann drück mal die Funktionstaste 12. Wähle dort dann mal den Reiter Console. Mach das Fenster groß und mach für die ganze Liste der Meldungen ein oder mehrere Screenshots und schick mir die bitte zu. Vielleicht fällt mir dann noch was ein.
(Siehe Screenshot oben)

4a. Welche Tampermonkey Version hast du?
Tampermonkey v5.1.1

5a. Ist dein Gerät ein Laptop oder ist das ein größerer Bildschirm oder ein Smartphone?
Desktop HP Z600

**Comment by 2Abendsegler** [comment]
zu 7a. Der Menupünkt "Linklist" ist immer da.

zu 8a. Die Liste benötigt zischen 3 - 4 Sekunden bis sie vollständig geladen ist.

**Comment by 2Abendsegler** [comment]
zu 9a. Neueste Tampermonkey Version hat bezüglich der manchmal fehlenden Logs keine Änderung gebracht.

**Comment by 2Abendsegler** [comment]
Der Aufbau der VIP/VUP Liste funktioniert auch nicht, vermutlich weil die Logs schon gar nicht gelesen werden.

**Comment by 2Abendsegler** [comment]
Es gibt weitere Erkenntnisse zu den fehlenden Logs, also Punkt 3 im ersten Beitrag. 
Ich hatte dazu am 21.10.2024 eine weitere Fehlermeldung per Nachricht erhalten und hatte sie damals hier integriert. 

Ich habe mittlerweile weiterführende Informationen dazu erhalten: 
Die fehlenden Logs wurden beim GClh im Zusammenhang mit der Erweiterung "GeocachingUtils" (https://chromewebstore.google.com/detail/geocachingutils/aiddapoflafkbecobkoiakgagaijacaa?pli=1) verursacht. Schaltet man die Erweiterung ab, werden die Logs vom GClh korrekt angezeigt. Außerdem konnten auch die Koordinaten im Cache nicht geändert werden. Scheinbar kommen sich die Erweiterung und der GHlh hier ins Gehege.

@diundbi
Hallo Dieter,
hast du vielleicht auch die Erweiterung "GeocachingUtils" am laufen?
Bitte gib mal Bescheid.
LG
Frank

**Comment by 2Abendsegler** [comment]
@diundbi
Hallo Dieter,

ich noch mal.

Habe gerade noch eine weitere Rückmeldung erhalten:
Laut Rückmeldung waren genau deine Probleme, also die Punkte 1 bis 3 aus dem ersten Beitrag, auch vorhanden. Auch dass in der Map-Ansicht keine Caches mehr angeklickt werden können.

LG
Frank

**Comment by diundbi** [comment]
Moin Frank,

habe GeocachingUtils deaktiviert und die Seite(n) neu geladen. Im ersten
Versuch sind in der Kartenansicht die Caches anklickbar und die Logs werden
dargestellt. Was lange währt...Vielen Dank für die Unterstützung.

Liebe Grüße
Dieter

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Am Di., 19. Nov. 2024 um 18:08 Uhr schrieb 2Abendsegler <
***@***.***>:

**Comment by 2Abendsegler** [comment]
Dann schließe ich mal das Issue.
