### ISSUE TITLE
[Cache Detail] Add event start and end time back to description 

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#2664]
### Is your feature request related to a problem? Please describe

GS recently removed the event start and end time from the cache description. And put it to the tiny meta data info at the top.
Many people don't like that new position 

### Describe the solution you'd like

We can add two solutions (both from the GS Release Thread)
1. Add the date and time back to description 
2. Make the date and time Infos at the to bold

### Additional context

https://forums.geocaching.com/GC/index.php?/topic/410241-release-notes-website-and-geocaching%C2%AE-app-event-start-and-end-times-october-17-2024/#comment-6179885

**Comment by 2Abendsegler** [comment]
Moin.
I haven't followed the thread. On which geocaching site was the information removed from the cache description? Are we talking about the cache listing or another site?

**Comment by capoaira** [comment]
Yes, it was at the top of the description. Now it is very tiny at the top of the page (in the meta data where also Owner Name, T/D rating, etc is)

**Comment by 2Abendsegler** [comment]
All right, thanks.
At first I thought it would be somewhere on a search page, where you might have to read a lot of caches to expand the description.
