### ISSUE TITLE
VIP list: quick link to VIP logs

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#268]
Now that we have this new VIP filter (well, not yet, but planned for 0.7 :) ) an idea just came to my mind about minor improvement of VIP list  - a link pointing down to filtered VIP logs.

I often open caches and when I see VIPs I like to read their stories. Some of my friends usually attach interesting images so I often go down and search for their logs to enjoy the photos. Now we have the new VIP filter but still one has to scroll down which might be annoying as some listings are long and then click the VIP icon.

So my idea is this:

![obrazek](https://cloud.githubusercontent.com/assets/9153595/24497644/68fb2cda-153c-11e7-8920-070e549aa0a1.png)

It would do two things:
1) navigate down to logs area
2) invoke the VIP filter

It sure can have much smaller form, like some mini-icon or something.

**Comment by 2Abendsegler** [comment]
Good idea.

**Comment by 2Abendsegler** [comment]
<ul>
<li>
New: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/268">#268</a>] VIP list: quick link to VIP logs:<br>
Navigate down to logs area and invoke the VIP filter.<br>
<img src="../blob/collector/images/v0.7_Screen02.jpg" alt="v0.7_Screen02.jpg"><br>
<br></li>
</ul>

(Only if you want to play with it in front of delivery, you can load it [here](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) as beta version. You can always go back with the official link for [the actual version](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).)

**Comment by PontiacCZ** [comment]
I am giving the beta a shot right now but something's not right - VIP list keeps "loading cache logs" and never ends.

The official version works OK.

**Comment by 2Abendsegler** [comment]
You are right, sorry. A file was missing. The "bug" is fixed. 

(Only for understanding: If we have new icons, we have to distribute the file with the icons to the whole environment, not only to the beta enviroment (branch collector), because the main script require the file during installation always at master enviroment. I forget it half the time.)

**Comment by PontiacCZ** [comment]
As Forrest Gump says: "It happens." :) 

Checked the beta again now and yes, it works! Thank you  very much for this improvement. Nice icon by the way. :)
