### ISSUE TITLE
Build Flopp's Map link too in navi area top right. Provide config parameter for new links in navi area.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#294]
https://geoclub.de/forum/viewtopic.php?f=117&t=79633#p1267984
4 Beiträge.

**Comment by 2Abendsegler** [comment]
Issue #308

**Comment by CachingFoX** [comment]
There are two possible positions in the navi bar
![grafik](https://cloud.githubusercontent.com/assets/1838534/25277240/21fed9b2-269e-11e7-9eda-8bbda730e57e.png)
In a own section
![grafik](https://cloud.githubusercontent.com/assets/1838534/25277212/0ab0f736-269e-11e7-8e20-23483753ac24.png)

**Comment by 2Abendsegler** [comment]
Die standard Sektion reicht aus meiner Sicht völlig aus.
