### ISSUE TITLE
No link to Flopp's Map if there no additional waypoints 

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#297]
Effected Version: 0.7

**Comment by GFEMajor** [comment]
Das Problem besteht leider weiterhin. Ist ein Lösung geplant, bzw. warum wurde das Ticket zu gemacht?

**Comment by 2Abendsegler** [comment]
Hi, 
du hast recht.
Die Tickets wurden alle ausgelagert, weil wir im Moment nicht weiter daran arbeiten und abwarten bis GS seine Anpassungen fertiggestellt hat. Sofern wir dann die Arbeit wieder aufnehmen, werden alle Tickets mit Label "storage" wieder aktiviert und bearbeitet.
LG

**Comment by GFEMajor** [comment]
Ah ok, das wusste ich nicht! Super 👍

**Comment by 2Abendsegler** [comment]
Ich habs jetzt mir zugeordnet, dann meint mal wieder jeder ich hätte was gearbeitet, hihi.
Issue reopen.

Vermutlich läßt sich das unten ja nicht einbauen, weil ja keine Waypoints vorhanden sind, bzw. es macht da unten dann nicht so viel Sinn. Vielleicht kannst du einen Link unterhalb von "Go to logs" einbauen. Das war ja sowieso auch gewünscht #294. Wenn dann keine Waypoints vorhanden sind, dann steht der Link eben nur oben.
![grafik](https://user-images.githubusercontent.com/22332216/31102017-83ebb010-a7d0-11e7-961b-f7e22d94de11.png)

**Comment by GFEMajor** [comment]
Ich habe das Problem gefunden. Leider will das Script die Kartenlinks hinter die Tabelle für Additional Waypoints hängen, wenn es aber keine Waypoints gibt, kann man auch nichts dahinter hängen 😃.
Ich werd es fixen und die Links trotzdem noch zusätzlich wie von dir vorgeschlagen in die Seitenleiste einfügen.
Eine Frage dazu @2Abendsegler . Soll dort auch das Dropdown mit Kartenauswahl rein, oder lieber nur ein normaler Link mit einer Standardkarte?

**Comment by GFEMajor** [comment]
#308 schau ich mir dann auch gleich an.

**Comment by 2Abendsegler** [comment]
- Damit der Link oben einzeilig bleibt, wäre mein Vorschlag fürn Linktext "Show Flopp's Map with …" oder "Show on Flopp's Map …".
- Den Link oben würde ich ansonsten genauso aufbauen wie unten, also mit Dropdown.
- Beim Link unten würde ich vermutlich den Linktext identisch machen, weils ja das Gleiche ist.  
- Ich würde auch den Link unten nur dann anzeigen, wenn es an der Stelle tatsächlich weitere WPs gibt, also so wie es heute schon ist. Der Abschnitt läuft ja unter der Überschrift "Additional Waypoints". Wenn der Abschnitt nicht vorhanden ist, würde ich also auch keinen Link an dieser Stelle vorsehen. Ansonsten müßten wir ja auch die Überschrift selbst aufbauen. 
- Zu #308: Hier gings ja primär um den "fetten" grünen Button, der hier an dieser Stelle unpassend wirkte. Wenn der Link zu Flopp's Map oben per Parameter ein- bzw. ausgeblendet werden kann, dann sollte das aber auch für den Link unten gelten, sehe ich genauso. Können wir ja hier abhandeln, ich mach den #308 nicht mehr auf.

LG du Arbeitstier :)

(Das at funktioniert und ist in der Mail ersichtlich unter CC. Ich bekomme aber trotzdem nur eine Mail, weil ich ja wie du auch alles bekomme. Das scheint gut gelöst von GitHub.)

**Comment by GFEMajor** [comment]
Zu #308 ging es mir mehr um die Möglichkeit, das über die Konfig auszublenden. Meine Frage dazu: Lässt du in solchen Fällen die ganze Funktion weg (über ein if, dass nur einsteigt wenn die Anzeige erlaubt ist), oder machst du da einfach ein "display: none" drauf?

**Comment by 2Abendsegler** [comment]
Üblicherweise über if, auch um die Zeit für den Aufbau zu sparen. Wobei das bei den Links hier ja nicht viel sein kann.

**Comment by GFEMajor** [comment]
Naja, es müssen ja alle Koordinaten von allen Waypoints ausgelesen und umgewandelt werden 😉. Aber ok, dann mache ich es über ein "if" und einen konfig value
