### ISSUE TITLE
Helper function: gclh_DateFormat

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#304]
A common function returns the current date format selected in Preferences (https://www.geocaching.com/account/settings/preferences) as a string like yyyy-mm-dd. The format strings are defined by Groundspeak

Every page contains a short script snippet includes a JavaScript object, which contains the date format. (Name of the object???).  The function should be able extract this information.

The function should be able to persist the current date format in the settings/variable for a faster access, to avoid the parsing process every time. There still exists a settings parameter with the name **settings_date_format** which can be used; but the problem is to trigger the initial update.

If settings_date_format is undefined or contains an empty string, the page will be parsed for the JavaScript object and afterwards the persistence will be updated.

An optional boolean parameter forces an update (parse page) and refresh the persistent of the date format.

If the user changes the format in the Preferences section the settings have to be updates. => new issue

**Comment by 2Abendsegler** [comment]
Moin,
will GS hier etwas umstellen? Woher kommt gegebenenfalls die Info?
LG

**Comment by CachingFoX** [comment]
Nein aktuell hat Groundspeak nichts geändert. Die Änderungen liegen schon einige Zeit zurück. Der Issue hat zwei Hintergründe:
1.  In den Settings kann man unabhängig von den Website Preferences ein Datumsformat einstellen. Wird benötigt um bei Events den Wochentag anzuzeigen. Beide Einstellungen sind nicht synchronisiert. 

2. GS sendet bei jedem Seitenaufruf (egal welche Seite) das eingestellte Datumsformat mit.

Idee ist, dass der Benutzer nicht mehr das richtige Format einstellen muss, sondern dass es automatisch ermittelt wird.

**Comment by 2Abendsegler** [comment]
Ok, verstehe, danke für die Info.
