### ISSUE TITLE
Update date format in settings_date_format automatically

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#306]
If the user changes the date format in the Preferences section the persistence (**settings_date_format**) will be automatically updated.

The default value of settings_date_format should be a empty string.

**Comment by 2Abendsegler** [comment]
Tasks:
- Update date format in settings_date_format automatically
- Remove dropdown box for date format in Settings
- Helper function: gclh_parseDate
- Helper function: gclh_DateFormat

**Comment by 2Abendsegler** [comment]
Die 2017er Issues, die nie bearbeitet wurden, entlassen wir in die Freiheit.
