### ISSUE TITLE
Rework TODOs of v0.7

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#309]
:)

**Comment by CachingFoX** [comment]
I found 9 TODO in the code (in my local code of v0.7 + unpublished changes):
	Line 3433:                     // TODO: check if home_coords defined
	Line 3442: // TODO: settings
	Line 3627:     // TODO: Find a better name and use getListingCoordinates.
	Line 3676:             addWP.push(waypoint); // TODO: added only if listing coordinates available
	Line 3780:         // TODO: problems if the zoom level to big
	Line 3781:         // TODO: danksagugng
	Line 3984:                         // TODO: according to Google this exception occurs if the text field is not visible,
	Line 4036:                         // TODO: according to Google this exception occurs if the text field is not visible,
	Line 7844:         // values = uniq(values); // TODO: median-B

**Comment by CachingFoX** [comment]
Remove two TODos
Line 3780: // TODO: problems if the zoom level to big --- already done in the changelog :-)
Line 3781: // TODO: danksagugng  --- already fixed see nearby l. 3797 (var maxZoom)

remain 7 TODOs

**Comment by CachingFoX** [comment]
TODOs from 
Line 3984 and Line 4036 not from me :-)

remain 5 TODOs

**Comment by CachingFoX** [comment]
Line 3676: // TODO: added only if listing coordinates available -- solved

**Comment by CachingFoX** [comment]
Line 3627:     // TODO: Find a better name and use getListingCoordinates. -- solved

**Comment by 2Abendsegler** [comment]
Die 2017er Issues, die nie bearbeitet wurden, entlassen wir in die Freiheit.
