### ISSUE TITLE
When using "Log your visit (inline)" and clicking "All visited" for the trackables list opens an empty new tab

### ISSUE THREAD

**Issue by MaggieLplus** [2Abendsegler/GClh#31]
-configuration of GClH II to show the list of TBs  
-click "Log your visit (inline)" from a cache page
-click "All Visited" below the list of Trackables
-new empty tab opens
-same happens for "All Dropped Off" and "Clear"
-functionality nevertheless works as expected

**Comment by 2Abendsegler** [comment]
Hi,
the theme is one of three I have not tested. So it was realy probably that there is at least one bug.
Nice that we have one. Do you have some trackables? Can I grab one or better two trackables of you, so I can test it. :) That was the reason it was not tested in the past.
Perhaps you can give me two tracking codes. Then I can grab the two trackables and I can test it. Is this possible?
Regards Frank

**Comment by 2Abendsegler** [comment]
There will be set a target to all the links of the inline frame from GClh. For the three buttons (AllDroppedOff AllVisited AllClear) this makes no sense. It could be, that this functionality runs never before.     

Change and test is successfully done local. 
After transports to branch test and master, issue can be closed.

**Comment by MaggieLplus** [comment]
Just tried with the last old GClH where it also showed this behaviour.

I'm not sure whether this was the same in the past as I used AutoVisit.

**Comment by 2Abendsegler** [comment]
Hi MaggieLplus,
you can grab the trackables back, thanks. If you delete your logs afterwards, it looks like never happend.
I will delete my logs too after your grabbing.
Best regards, Frank

**Comment by 2Abendsegler** [comment]
Thanks for your feedback. There is the same procedure in all three buttons. So the three buttons run never before tidy. Only a little bit funny, that nobody notified it in the past. Probably the reason was a missing support system like this here, or a missing support team. So what. :)

I have deleted my logs too in the trackables. Now it should be tidy again for the owner.

Nice working day. :)
