### ISSUE TITLE
Display images in image galleries with maximum possible size (like in logs) 

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#312]
I believe that in the past when I clicked an image in an image gallery (be it user image gallery or a cache one) it displayed in the maximum possible size (depending on the browser window size and the original image dimensions) just like when you click an image attached to a log. This no longer works.

Example:
- open my cache [Velka Jivina](https://coord.info/GC6JT70) 
- scroll down to the log with date 2016-07-30 and click the thumbnail, the image fills up the entire browser window, see the following screenshot:

![obrazek](https://cloud.githubusercontent.com/assets/9153595/25129345/ed9efde4-243d-11e7-99ea-dcd8018c0652.png)

- now go to the cache gallery and click the same image thumbnail. You will only get this size:

![obrazek](https://cloud.githubusercontent.com/assets/9153595/25129368/078f64d2-243e-11e7-90f6-6169e815cf8c.png)

I expect the image to be of the same size in both cases.

GC Little Helper II v0.7.1

**Comment by 2Abendsegler** [comment]
I can retrace your example. 
We build the images in the logs by click, called fancybox. In every gallery, we do not build this fancybox, but GS. If you let run the listing without GClh the image is so small like in the gallery.

Perhaps you have a new bigger monitor running. Because GS images have a maximum size, the effect with a bigger monitor is now that the picture seems now small.

I think your monitor is too big, please go to the loft and take your old and smaller monitor. :)

We will try to build our own fancyboxes in all galleries.
At the moment I have however still no idea how that goes. :)

**Comment by PontiacCZ** [comment]
I see, fancybox, yeah, already heard of that thing. :) I am sorry, I'm somehow confused, I would swear I used to get full-window images in galleries. That must have been just in my head. And no, my monitors at work and at home have not changed  for a few years. :-) 

OK, so maybe one day. Nevermind, I prefer reading logs and watching the attached images there. :) 

Thank you for your reply.

**Comment by 2Abendsegler** [comment]
Hi again,

clicked images in user, cache and TB image galleries have now a maximum size.

Best regards,
Frank
PS: Do you want to reveal your first name? :)

![cache_gallery_image_max](https://cloud.githubusercontent.com/assets/22332216/25467216/23a30446-2b0d-11e7-9672-a4e254567fd5.jpg)

**Comment by 2Abendsegler** [comment]
<ul><li>
New: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/312">#312</a>] Display images in user, cache and TB image galleries with maximum possible size.<br>
<br>
</li></ul>

**Comment by PontiacCZ** [comment]
Another great job, thank you!

PS: no problem. :-)

Have a nice day
Pavel ;-)

**Comment by PontiacCZ** [comment]
Verified this one as well. Thank you, it is a great experience to use gc.com with GClh II. Many people who are not aware of GClh II are missing so much. :-)

**Comment by 2Abendsegler** [comment]
Hi Pavel,
I saw, that you have contributions for javascript on your GitHub account. 
Can you perhaps develop in javascript? How much? Or are that others things?
Have a nice day!
Frank

**Comment by PontiacCZ** [comment]
Well, unfortunately not much. That was just a trivial commit to the old GClh - I found the non-working link and adapted it to the working form. No JS knowledge actually needed for that.
