### ISSUE TITLE
GClh Search 2.0

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#314]
A new powerful single universal search field for
- Location (suggestion)
- GC Codes (suggestion)
- Radius search around a GCCode (suggestion)
- Radius search around coordinates 
- Show map on coordinates
- User accounts (suggestion)
- public and private code for trackables

**Comment by 2Abendsegler** [comment]
Eigentlich dachte ich, dass wir es die nächsten Monate etwas gemächlicher angehen lassen wollten.
Und nun haben wir mehr Issues als je zuvor.
Ich kann mich im Moment nur schwer für Neues begeistern, insbesondere wenn es nicht mal von den Usern kommt. Ich habe mit den Anforderungen der User eigentlich schon weit mehr als genug zu tun. Vielleicht müssen wir nicht wirklich alles entwickeln was uns gerade so einfällt und wir sollten auch bedenken, dass jede Entwicklung auch Nacharbeiten mit sich bringen kann. Vielleicht könnten wir etwas auf die Bremse drücken und mal wieder mehr cachen gehen. :)

**Comment by 2Abendsegler** [comment]
Hi Du,

ich wollte Dich wirklich nicht vergrämen mit meinem Kommentar. Falls es aber geschehen ist, möchte ich mich dafür entschuldigen. Magst Du nicht wieder was tun, beispielsweise an den Bugs oder an den Änderungswünschen von Simakid oder SammysHP oder so? :)

Ich habe gesehen, dass Du Dich als Reviewer vorgeschlagen hast, wie Du das auch immer geschafft hast. :)
Ich verwende für meine Coding Tests ziemlich viel Zeit und prüfe alles doppelt und dreifach. Damit ist es zwar nicht ausgeschlossen, dass ich einen Bug produziere, aber es ist doch einigermaßen sichergestellt. Zumindest so viel, dass es eigentlich keinen Sinn macht, dass Du hier auch noch Zeit reinsteckst. Das sollte zumindest die Regel sein. Ich war ziemlich lange Reviewer für alle möglichen Kollegen, die teilweise gar nicht testen konnten oder wollten. 
Aber ich nehme das trotzdem als Vorschlag an und werde Dich in Anspruch nehmen sobald das mal Sinn macht. Ich habe vermutlich auch schon ein Thema.

Ich hatte den collector abgemurkst mit der v0.7.2 oder war es v0.7.1, weiß nicht mehr. Hat alles ziemlich krumm gestanden, weil ich am collector vorbei diese Versionen transportiert habe. Ich weiß noch nicht mal was ich genau falsch gemacht habe, aber ich mußte alle geänderten Dateien nochmal manuell in den collector bringen. Ich bin mir noch nicht sicher, ob er sauber ist. 
Bitte merge nichts vom collector zu Dir. Mach Dein Coding fertig und dann werde ich sehen ob alles funktioniert oder ob ich beim collector wieder nachbessern muß. Wenn die 0.8 raus ist, dann müssen wir den collector neu aufbauen aus dem master.

Für v0.8 gibt es aber noch keinen Termin, wir lassen uns dieses Mal so viel Zeit wie wir brauchen oder haben wollen. :)
 
LG Frank

**Comment by 2Abendsegler** [comment]
Die 2017er Issues, die nie bearbeitet wurden, entlassen wir in die Freiheit.
