### ISSUE TITLE
Colors for logs in cache listing not proper by using the script of project gc at once

### ISSUE THREAD

**Issue by JuicyFruit6** [2Abendsegler/GClh#316]
If you've choosen colors for "you" and for "VIP's", and you are also a VIP (it's because of finding your own logs faster), the color for VIP is overwriting the green color for "you".

**Comment by JuicyFruit6** [comment]
So it should be possible to choose priority for colors

**Comment by 2Abendsegler** [comment]
The standard log colors are:
![standard_log_colors](https://cloud.githubusercontent.com/assets/22332216/25189359/3391ef14-2529-11e7-9608-2aa8a4f0cfdf.jpg)
If you have nothing changed, "you" are green and the "VIPs" are yellow.

So, if you are a VIP and you choose for example the new button "VIP logs", then you are green and all other VIPs are yellow. 

And now, please explane me once again why it should be possible to choose the priority of the colors. What is wrong with the colors.

**Comment by JuicyFruit6** [comment]
Ich habe alle Haken gesetzt. Wenn ich über F5 die Seite mit meinem Log neu lade, sehe ich kurz meinen Log in grün. Wird aber sofort wieder mit gelb überschrieben. Ich bin ja auch VIP :)
Wenn ich die Optionen so mache wie auf deinem Bild, und mich aus der VIP Liste entferne, wird mein Log kurz grün, dann weiß angezeigt. Mit VIP grün ->gelb. Habe FF 52.0.2

**Comment by JuicyFruit6** [comment]
Da scheint ein weiterer Programmteil das ganze zu überschreiben ?

**Comment by 2Abendsegler** [comment]
Das scheint ein Fehler. Womöglich hast Du Sonderzeichen in Deinem Geocaching Namen. Wie lautet er denn?
Kannst Du bitte mal einen Screen hier posten, auf dem die falschen Farben zu sehen sind.

**Comment by JuicyFruit6** [comment]
Das mit dem Sonderzeichen ist wohl so :)
Habe ☺ (Alt 1)
![unbenannt](https://cloud.githubusercontent.com/assets/27776456/25242629/9a5444fa-25fa-11e7-93a8-2e42ce577703.JPG)

**Comment by 2Abendsegler** [comment]
Ok, danke. 
Ich gehe davon aus, dass beim Aufbau der VIP Farbe in einer weiteren Programmschleife (gut erkannt), dein Username nicht als solcher erkannt wird. Das liegt mit sehr hoher Wahrscheinlichkeit an den Sonderzeichen ☺ (Alt 1) und & im Username.
Ich muß mal sehen ob wir das mit Version 0.8 oder schon vorher mit einer Vorabkorrektur korrigieren können.

**Comment by 2Abendsegler** [comment]
User:
☺Mitchsa & firefly70
https://www.geocaching.com/profile/default.aspx?guid=7df3b38e-884c-4ec9-a943-eeac5dc424aa

**Comment by 2Abendsegler** [comment]
Hi,

ich habe mir das gerade mal angesehen und kann eigentlich keinen Fehler finden. Es sollte eigentlich bereits funktionieren. Wenn ich mir einen Deiner Caches aufrufe und Dich als VIP kennzeichne, dann werden Deine Logs auch als Owner in grau gekennzeichnet und nicht als VIP in gelb. Und User und Owner werden eigentlich gleich behandelt. Weiß gerade nicht so recht weiter. :)

Kannst Du bitte mal in irgend einem Cache Listing mit der Maus oben rechts auf Deinen Usernamen gehen und dort mal die Rechte Maustaste drücken und "Element untersuchen" auswählen. Es sollte dann die Konsole angezeigt werden mit einer blau unterlegten Zeile. Bitte mal einen Screenshot davon.
(Das ist die Funktionsweise unter Firefox. Wenn Du einen anderen Browser verwendest, dann gib bescheid.)

**Comment by JuicyFruit6** [comment]
![grafik](https://cloud.githubusercontent.com/assets/27776456/25259581/46e45d08-2647-11e7-8983-207e883f0217.png)

**Comment by JuicyFruit6** [comment]
Hier mal noch ein paar Bilder vom direkten "Übergang"

![grun](https://cloud.githubusercontent.com/assets/27776456/25260090/24dd39e8-264a-11e7-8ccf-e19c834471a5.jpg)
![grau](https://cloud.githubusercontent.com/assets/27776456/25260093/26d7de88-264a-11e7-8427-e1b6077aef81.jpg)
![gelb](https://cloud.githubusercontent.com/assets/27776456/25260096/298976a0-264a-11e7-80a6-a022d3bb8657.jpg)

**Comment by 2Abendsegler** [comment]
Hi,

ich kann den Fehler nicht reproduzieren, tut mir leid.

Noch ein paar Fragen, deren Antworten mir vielleicht neue Ideen bringen:
1. Hast Du andere Scripte am Laufen? Dann bitte deaktivieren.
2. Welche Firefox Version läuft bei Dir?
3. War der Fehler schon immer da?
4. Tritt der Fehler bei mehreren Cache Listings auf?
5. Kannst Du mal nur die Farben im Config zum Cache Listing aktivieren, die beiden anderen deaktivieren?

**Comment by JuicyFruit6** [comment]
Soory, dass ich mich erst so spät melde. 
1. Liegt am Project GC scipt.
2. FF 52.0.2
3. kA
4. bei allen, bei unseren Eigenen (Events) wir die Farbe Owner angezeigt
5. Habe mal alle Farben zum Cache Listing deaktiviert, Außer "for you". Dann werden mit aktivierten Project GC unsere Logs weiß angezeigt.

Das Problem liegt also nur an der Farbe für YOU??
Ich versuche mal einwenig mit Project GC zu spielen. Vielleicht finde ich was?

**Comment by JuicyFruit6** [comment]
Finde dort keine Einstellung die etwas in der Richtung bewirkt

**Comment by 2Abendsegler** [comment]
Ich werde mir dann mal wieder Project GC aufspielen und schauen, was die am Log verändern, dass wir es nicht mehr als "you" identifizieren können.

**Comment by 2Abendsegler** [comment]
Hi,

das Problem mit Project GC haben wir von unserer Seite aus behoben. 
Eine Korrektur kommt erst mit Version 0.8, was noch einige Zeit dauern kann.
Du kannst aber die Vorabkorrektur einspielen: 
https://raw.githubusercontent.com/2Abendsegler/GClh/collector/temp/gc_little_helper_II.user.js

Liebe Grüße
Frank

**Comment by JuicyFruit6** [comment]
Danke, funzt :)
VG, Michael
