### ISSUE TITLE
Cache title of an active cache shown striked

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#32]
Activate option "Strike through title of archived/disabled caches"

The cache title of an active cache shown stirked, see here  this https://www.geocaching.com/geocache/GC22ENV_tanzparadies-lp

last five logs: found, nm, 3x found

**Comment by CachingFoX** [comment]
Reason found:
The owner use a element with the class "OldWarning" in the short description. This is the trigger for archived/disabled caches.

**Comment by CachingFoX** [comment]
Improvement
looking for ul .OldWarning > li >
* This cache has been archived / temporary disabled

**Comment by 2Abendsegler** [comment]
Cache title of an active cache shown striked.
Tested:
archiviert: https://coord.info/GC2FMEK
deaktiviert: https://coord.info/GC444MB
Tanzparadies (LP): https://coord.info/GC22ENV
