### ISSUE TITLE
Without home coordinates driving direction link in Additional Waypoints doesn't work proper

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#322]
Is a TODO from issue #309

**Comment by CachingFoX** [comment]
Link will not available if there no coordinates for home location

**Comment by GFEMajor** [comment]
Ist der Fehler noch aktuell bzw. was genau soll getan werden?

**Comment by 2Abendsegler** [comment]
Ich vermute mal, dass der Link nur dann funktioniert, wenn die Homekoordinaten bereits im Config gespeichert sind. Das kann man nur testen wenn man die .db Datei löscht. Bei der nächsten Anwahl einer GC Seite wird dann die Standardkonfiguration in der .db Datei erzeugt in der keine Homekoordinaten enthalten sind. 

Es gibt noch andere Fälle bei denen das so ist. Beispiel die Nearest List. Hier wird dann ein anderer Link gesetzt, der eine UserInfo bringt, ob der GClh die Homekoordinaten automatisch ermitteln soll.

Also:
- .db Datei killen, vorher sichern.
- link anwählen. Wenns nicht funktioniert dann wissen wir was Sache ist. dann weiter wie folgt ...

1. Als nearest list Link wird in der Linklist ein spezieller Link aufgebaut der in der URL hinten folgendes enthält: #gclhpb#errhomecoord . Siehe Line 139. Die driving direction links müssen auch dieses Anhängsel bekommen.
2. Dieser Link bleibt bestehen, sofern keine Homekoordinaten im GClh gespeichert sind und wird bei Anwahl in der nächsten Script Verarbeitung ganz oben im GClh abgefangen. Siehe Line 689. Dort erhält der User eine Info, dass es so nicht funktioniert und ob der GClh die Homekoordinaten automatisch ermitteln. Wenn ja springt er zu den Homekoordinaten und speichert sie.
3. Sind die Homekoordinaten im GClh gespeichert, wird der Link in einen echten Link umgewandelt. Siehe Line 7627 (stimmt vermutlich nicht ganz genau, weil ich noch etwas geändert habe.) 

Die driving direction links müssen also so aufgebaut werden wie in 1. und am besten eine ID erhalten damit sie bei 3. identifiziert werden können. 
Bei 2. muß vermutlich gar nichts gemacht werden. Das müßte gleich funktionieren.
Bei 3. müßte der der Link in einen echten Umgewandelt werden.

Eigentlich ist das nicht kompliziert wenn man es mal verstanden hat. Ich hoffe ich hab das einigermaßen erklärt.

**Comment by GFEMajor** [comment]
ich hab die .db verschoben und dann versucht den Link aufzurufen. Es wird 0,0 als Homekoords übertragen. Das Problem besteht also weiterhin. Zur Beseitigung muss ich mich glaube ich erstmal in die Thematik einarbeiten 😉. Aber so grob verstehe ich, was gemacht werden muss. Nur wie genau muss ich mal schauen, da die Links ja extern an Google gehen und nicht intern bei GC bleiben. Da schau ich mal, ob das Probleme macht. Ansonsten würde ich es eventuell anders lösen. (Symbol deaktivieren und einen Hint + Link zu den Homekoords speichern anzeigen oder etwas ähnliches)

**Comment by 2Abendsegler** [comment]
Ich nehm dir das weg. Du sollst nicht auf dem Sofa rumlungern, sondern deine Vorbereitungen ... fertigmachen. :)

**Comment by 2Abendsegler** [comment]
Ich habe es fürs Listing in ähnlicher Art realisiert wie die nearest lists, weil es am wenigsten Aufwand war.
Die Waypointliste beim hide funktioniert aber nach wie vor nicht ohne die Homekoordinaten. Hier würde ich aber sagen sch... drauf, das ist sowieso recht unwahrscheinlich.

**Comment by GFEMajor** [comment]
In meinem Folk hatte ich das heute eingebaut, aber wenn du es nun gemacht hast ist das auch ok 😉.
Was meinst du mit "Die Waypointliste beim hide funktioniert aber nach wie vor nicht ohne die Homekoordinaten."?

**Comment by 2Abendsegler** [comment]
Doof, doppelt machen ist doof, sorry.
Wenn du das Listing für einen neuen Cache bearbeitest, dann kannst du eine Liste der Wegpunkte aufrufen. Dort wird auch der driving direction link für jeden Wegpunkt aufgebaut. Falls die HomeCoords nicht bekannt sind, funktioniert das eben nicht.

**Comment by GFEMajor** [comment]
Achso, ok.
Um doppelarbeit vorzubeugen, schau am Besten einfach in meinen Folk rein, wenn ich ein Ticket zugewiesen habe. Dann siehst du ja ob ich was gemacht habe oder nicht. meine Commit Nachrichten sind eigentlich immer recht aussagekräftig 😉
