### ISSUE TITLE
Clairify why home location doesn't stored in settings

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#323]
The home location is store in *home_lat* and *home_lon* instead of settings object.

Why use saveHomeCoords not toDec to decode geocoordinates?

**Comment by 2Abendsegler** [comment]
Ich weiß es nicht, aber ich vermute, dass diese Variablen ursprünglich nicht über den Config änderbar sein sollten und deshalb nicht mit settings beginnen. 

saveHomeCoords verwenden doch toDec: 
var latlng = toDec(match[1]);

Wieso erscheint Dir hier eine Klärung notwendig?
