### ISSUE TITLE
Link "Go to Waypoint list" not avaiable for unpublished caches

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#324]
https://www.geocaching.com/geocache/*

**Comment by 2Abendsegler** [comment]
Das ist kein Bug, das soll so sein. Hier macht der GClh gar nichts.

**Comment by CachingFoX** [comment]
see also #325 

Function is_page/is_link("cache_listing") doesn't return true for listing with a submit button (=unpublished cache)
