### ISSUE TITLE
Duplicate in "new finds by" (0.7.1)

### ISSUE THREAD

**Issue by gcnumero** [2Abendsegler/GClh#327]
Hi there,

I have one VIP nickname for which I always get 2 times his nickname listed with his corresponding number of new finds number after the text "new finds by".

Example 👍 
![image](https://cloud.githubusercontent.com/assets/27970365/25351312/94fc8518-2928-11e7-8b22-b7970c0064c6.png)

Can this be fixed please ?

Thank you
Jan

**Comment by 2Abendsegler** [comment]
Hi Jan,

I can not replicate your case and I have not found a bug by a short analyse.  
Can you please try to answer my questions?

1. Please deactivate all other scripts and go again to your friends page. Is the bug always available?
 
2. How often is the nickname listed below in section "Your Friends List" on your friends page? 

3. You have written that you "always" get 2 times his nickname. Do I understand it right, that you have meanwhile reset the counter and you get his nickname 2 times again after the nickname has done new finds?

4. Is only this nickname shown 2 times?

5. Have you activated the parameter "Show summary only for friends in VIP list" in Config?

Thanks
Frank

**Comment by gcnumero** [comment]
Hi Frank,

Thank you for your questions.

I investigated through your questions and noticed the following : the specific nickname for which the duplicates were generated existed twice in the friends list for some reason (so a groundspeak issue I assume).  Removing that friend made both entries to disappear in the friends list.

I assume everything will be OK now as indeed I had the issue only with this particular friend.

Sorry to have wasted your time on this.  The issue seems to have been at groundspeak level.

Thank you for your help and keep up the good work with this nice script !

Best regards,
Jan

**Comment by 2Abendsegler** [comment]
Yes, it could be a groundspeak issue.

Have you done a new friend request? If the friend is available again and the friends page is checked, a little notice would be great.

You can leave the issue open for so long.

Thanks and best regards,
Frank

**Comment by gcnumero** [comment]
Hi Frank,
I entered a new friends request.  I hope I get an answer because it was somebody I met only once 4 years ago ;-)
Will let you know.

Thank you
Jan

**Comment by 2Abendsegler** [comment]
Hi Jan,
I think you get no answer of this person. Can you then close the issue?
Thanks
Frank

**Comment by gcnumero** [comment]
Couldn't reproduce. Can indeed be closed.
