### ISSUE TITLE
Profile information width changes when GClH II is enabled

### ISSUE THREAD

**Issue by MaggieLplus** [2Abendsegler/GClh#33]
I'm using banners in my public profile (via the "Bio" entry).
Normally I get three banners in a row.
Using the old GClH this worked fine.
Since GClH 2As there are only two displayed per row.

See as example my [public profile](https://www.geocaching.com/profile/?u=MaggieL%2B)

**Comment by 2Abendsegler** [comment]
Hi,
once again. :)
If I look to your profile, I see 4 Banners in one line. I could send you a picture, but it is not necessary, because you can see it too 3, 4 or other. It should depents on the customised "Page-Width" in your GClh Config. Please go to the GClh Config (push Button F4 or go about you profile). Change the page-width a little bit more, perhaps 950 px should show you 3 Banners.
Please try it and come back if you have further questions.
Oh my terrible english, sorry.
Regards Frank

**Comment by MaggieLplus** [comment]
Hallo Frank,

 

Du kannst gerne in Deutsch schreiben...


 

Vielen Dank, das wars. 970 statt 950 und ich sehe wie vorher drei Spalten.

Ist das neu mit GClH 2As bzw. II?

 

Ein riesen Dankeschöm an Euch für die Übernahme von GClH und die schnelle Antwort!

Schöne Grüße,

Robert.


Gesendet: Dienstag, 10. Januar 2017 um 13:51 Uhr
Von: 2Abendsegler <notifications@github.com>
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: MaggieLplus <robert.laufer@gmx.de>, Author <author@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Profile information width changes when GClH II is enabled (#33)


Hi,
once again. :)
If I look to your profile, I see 4 Banners in one line. I could send you a picture, but it is not necessary, because you can see it too 3, 4 or other. It should depents on the customised "Page-Width" in your GClh Config. Please go to the GClh Config (push Button F4 or go about you profile). Change the page-width a little bit more, perhaps 950 px should show you 3 Banners.
Please try it and come back if you have further questions.
Oh my terrible english, sorry.
Regards Frank

**Comment by 2Abendsegler** [comment]
Hallo Robert,

schön dass das nun klappt. Aber eigentlich ist das nicht der richtige Weg. Du solltest die Breite Deines Fensterinhaltes nicht an den Bannern ausrichten. Du solltest die Breite des Fensterinhaltes so auswählen, dass Du möglichst gut damit "arbeiten" kannst. Bei mir bedeutet das maximale page width von 1200 Pixel, damit auf meinem kompletten Bildschirm Informationen stehen.

Neu ist, dass wir versuchen, möglichst viel der zur Verfügung gestellten Breite auch zu nutzen, Wenn Du also eine Breite über 950 wählst, dann wir auch der Contenbereich, also der Bereich wo die Daten stehen, also beispielweise das Cache Listing verbreitert, Das Listing wird deshalb dann etwas kürzer. 
Beim Alten war eine feste Breite vorgegeben. Nur der Header mit Menü ... war variabel.   
 
Bitte sei Dir darüber im Klaren, dass jeder der sich Dein Profil ansieht andere Einstellungen hat. Ich habe zuvor  4 Banner in einer Reihe gesehen. Du mit den 950 nur 2. Deshalb sollte man das im Profile variabel gestalten. Also beispielsweise nur 2 von den großen Bannern zusammen in eine Zeile und die dann beispielsweise zentrieren. Du kannst natürlich auch die Banner in Höhe und Breite nacharbeiten, so wie das viele machen, damit alle Banner möglichst gleich groß sind, und dann hängen sie vier nebeneinander.  

Wenn Du möchtest kannst Du ja folgendes mal versuchen. 2 Banner in einer Reihe zentriert und nochmal eine zweite Reihe. 
<center>
<p>
Hier dein 1. Banner
Hier dein 2. Banner
</p>
<p>
Hier dein 3. Banner
Hier dein 4. Banner
</p>
</center>

Liebe Grüße
Frank

**Comment by 2Abendsegler** [comment]
Ich weiß nicht ob Du die Aufbereitungszeichen sehen kannst, weil die ja hier bereits umgesetzt werden. :) Hier also noch ein Bild.

![so solls aussehen](https://cloud.githubusercontent.com/assets/22332216/21809664/02562042-d749-11e6-8301-6d65dcb68e5b.jpg)

Wenn alles soweit in Ordnung ist, dann kannst Du das Issue mit dem Button Close schließen.
