### ISSUE TITLE
Abspeichern von benutzerdefinierten Suchen

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#34]
Unter https://www.geocaching.com/play/search können benutzerdefinierte Suchen erstellt werden. Die Suchparamter sind in der URL kodiert.

Idee:
Der User kann solche Suchen (Suchparameter nicht die Ergebnisse) abspeichern und dann immer wieder aufrufen.

Anforderungen

1. "Speichern"-Button, um eine Suche abzuspeichern 
Vorschlag: In der Ergebnisliste Neben der Schaltfläche "My List"
2. Beim Speichern muss ein Namen vergeben werden
3. Suchen können aufgerufen werden 
Wo? Über das SeitenmenÜ?
4. Verwalten der benutzerdefinierten Suchen (löschen, bearbeiten) 
Vorschlag: In den GClh Settings

**Comment by 2Abendsegler** [comment]
Schöne Idee, ja wirklich, hätte ich auch schon gebrauchen können!

1. und 2. super.
3. und 4. das könnte man auch an der gleichen Stelle machen, also dort wo man die Liste eingegeben hat. So etwas wie eine Auswahlliste. Im Seitenmenü könnte man vielleicht einen Link zu allen Suchen ermöglichen, also eigentlich hierher. Einzelne Suchen in der Linklist, hmm, man hat ja nicht nur 2, dann würde man sich die Linklist zudonnern und wo soll man sie hinhängen, untendran ... Eigentlich sind das genaugenommen gar keine Settings oder Customizing, sondern Anwenderdaten. GClh Config scheint mir deshalb nicht ganz richtig. Zumindest habe ich das in meiner SAP Laufbahn zu behandelt. Warum nicht alles an eine Stelle ... ? Ähnlich wie die Bookmarklisten ganz rechts. Da kommt ein Popup und alles was notwendig ist, amche da drin. Bei den Popup der Bookmarks ist das hglaube ich auch so. Cache rein, Cache raus, Namen vergeben, hier halt für die Bookmarkliste. Im Grunde genommen sind die Anforderungen doch ziemlich ähnlich.

Auf jedenfall eine super Idee.   

Ich habe meine eigenen Ideen bisher nicht als Wunsch gesehen. Ist eine Wunsch nicht etwas aus der Community?

**Comment by 2Abendsegler** [comment]
2. und 4. "My List" gibt es ja noch nicht, wenn die Suche noch nicht ausgeführt ist, also paßt mein Vorschlag ja nicht ganz. Was hälst Du denn von neben der Schaltfläche "Add Filters bzw "Change Filters"?

**Comment by CachingFoX** [comment]
issue #35: rename c.settings_search_list to settings_search_data 			d56086d

**Comment by CachingFoX** [comment]
![Uploading Capture-0.PNG…]()

**Comment by CachingFoX** [comment]
Hier ein paar Screenshots 

![capture-0](https://cloud.githubusercontent.com/assets/1838534/23181208/65d02dba-f874-11e6-9805-32d7e92324e5.jpg)
![capture-1](https://cloud.githubusercontent.com/assets/1838534/23181213/6e2b0e26-f874-11e6-9e06-5260e7e7ef02.PNG)
![capture-2](https://cloud.githubusercontent.com/assets/1838534/23181223/754a7ce6-f874-11e6-8b32-62088edb1f2a.PNG)
![capture-3](https://cloud.githubusercontent.com/assets/1838534/23181228/7ad8a890-f874-11e6-8bb0-c1ecc3b392eb.PNG)
![grafik](https://cloud.githubusercontent.com/assets/1838534/23181279/aff33892-f874-11e6-89ce-b9bceeeba56b.png)
