### ISSUE TITLE
Show bigger avatar images in cache listing logs while hovering with the mouse

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#349]

**Comment by 2Abendsegler** [comment]
<ul>
<li>
New: Show bigger avatar images in cache listing logs while hovering with the mouse: [Issue <a href="https://github.com/2Abendsegler/GClh/issues/349">#349</a>]<br>
After pressing the button "Show bigger avatars" in cache listing above the logs, a big avatar image is shown, if one hover with the mouse over an avatar image.<br>

![v0 8_screen41](https://cloud.githubusercontent.com/assets/22332216/25774355/7768a9fa-328d-11e7-8549-4e2a7dab0192.jpg)

The thumbnail parameter has to be activated.
Settings -> Listing:<br> 

![v0 8_screen40](https://cloud.githubusercontent.com/assets/22332216/25774357/7b345782-328d-11e7-8ef7-d65b481c9091.jpg)

<br>
<br>
</li>
</ul>

**Comment by f-o** [comment]
I really love this feature, but it's always when I'm 100 logs deep in the page, that I find an avatar I'd want to have expanded, prompting me to scroll back to the top, click the button, and find my way to the log again.

Is there a way we could have this enabled by default, for all logs, and have it automatically fetch new bigger versions as logs are being returned on the page? @2Abendsegler
