### ISSUE TITLE
New Dashboard is broken by GCLH

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#365]
![dashboard](https://cloud.githubusercontent.com/assets/2239440/26141226/0e61b414-3adb-11e7-8d43-68622cfe7ed4.png)

**Comment by GFEMajor** [comment]
nevermind, this is only if you limit the pagewidth to 950px :), sorry

**Comment by 2Abendsegler** [comment]
Hi,
wir lassen das Issue trotzdem mal offen, auch wenns nur bei 950px Probleme bereitet.
Ich schau mir das gerne an.
LG Frank

**Comment by 2Abendsegler** [comment]
Da wir nicht wissen, was Groundspeak noch alles bringt, werden wir versuchen, alle neuen Seiten außen vor zu lassen und nicht durch den GClh zu bearbeiten. Das gilt zumindest so lange, bis wir die Seite durchgetestet haben.

Insofern war es doch gut, darauf hinzuweisen, danke.
Ich werde das Issue nun wieder schließen.

Liebe Grüße
Frank
