### ISSUE TITLE
disable GClh on the new dashboard

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#369]
Just a thought, Frank: is is possible to detect the new dashboard and do not run the enhancing javascript on it? One has to switch GClh off when exploring it. When on, it screws up the page.

![obrazek](https://cloud.githubusercontent.com/assets/9153595/26191461/387ba880-3bae-11e7-9509-7c6645bd0e84.png)

Pavel

**Comment by 2Abendsegler** [comment]
Hi Pavel,
at the weekend we rollout v0.8. 
In that version, we have try to let the new sites out of GClh. This will not help on every new page but on the new dashboard.
Cheers Frank

**Comment by PontiacCZ** [comment]
Good to hear that. Thank you! :-)
