### ISSUE TITLE
With new GC look the public profile bio page last column is cut

### ISSUE THREAD

**Issue by MaggieLplus** [2Abendsegler/GClh#377]
page: [profile](https://www.geocaching.com/p/default.aspx?tab=profile#profilepanel)

- using GClh the page width is set to more than the GC default
- with old GC look the bio on public profile page is displaying 4 banner columns
- with new GC look profile->about is cutting the fourth column

**Comment by 2Abendsegler** [comment]
Hi,

ich kenne das Problem, es läßt sich aber nicht ohne weiteres abstellen.

Eigentlich soll der GClh auf den Seiten im neuen Design gar nichts tun. Das ist auch der Fall mit einer Ausnahme und das ist der "About" Tab. Hier, wie auch beim alten Design als "Profile Information", wird ein besonderer Bereich aufgerufen, in dem nicht der komplette Befehlssatz von HTML ... gilt, eine sogenannte Sandbox. Deshalb muß die Verarbeitung in zwei Schritten stattfinden, einmal das Drumherum und einmal die Sandbox. Das bedeutet auch, dass der GClh zwei mal aufgerufen wird. Dummerweise prozessiert GS die Sandbox als erstes und der GClh kann zuerst mal nicht wissen, was als nächstes kommt, das Drumherum des Profiles im neuen Design oder entsprechend im alten Design.

Der GClh protokolliert die Aufrufe auch in der Konsole. Bei mir sieht das dann etwa so aus:
"GClh: 1495793245223 | https://www.geocaching.com/profile/profilecontent.html"
"GClh: 1495793245766 | https://www.geocaching.com/p/default.aspx?tab=profile#profilepanel"
GClh: Unknown page, do nothing 

543 Millisekunden vor der Profileseite wird die Sandbox aufgerufen (profilecontent). Erst wenn die Profileseite im neuen Design aufgerufen wird, stellt der GClh fest, dass es sich um eine unbekannte Seite handelt, die dann nicht verändert wird. Die Sandbox ist dann schon längst geändert.

Ich kann das also nicht abstellen. Es sei denn der GClh würde die Seiten im neuen Design ebenfalls verarbeiten. Das macht er aber nicht und im Moment ist das auch nicht geplant.

Ich kann hier also nichts tun, tut mir leid.

LG Frank

**Comment by MaggieLplus** [comment]
Hallo Frank,

spannend wird das Ganze dann, wenn GC nur noch das neue Design unterstützt. Früher oder später wird das wohl kommen.

Danke für die aufschlussreiche Erklärung und Deine Bemühungen für GClh,
Robert

**Comment by 2Abendsegler** [comment]
Hallo Robert,

ja, Du hast recht. 

Es stellt sich grundsätzlich die Frage, ob die Funktionen des GClh auf Seiten im neuen Design portiert werden. Wenn GS das Cache Listing anpaßt, dann betrifft das schätzungsweise 40-50% des GClh. 
Im Moment habe ich eigentlich nicht vor, dermaßen umfangreiche Arbeiten am GClh durchzuführen, trotz der entsprechenden Konsequenzen. 

Aber wir sehen mal was kommt.

LG Frank
PS: Bitte schließe das Issue wenn möglich. Falls irgendwann portiert wird, gehört dein Punkt sowieso dazu und ansonsten wird er sowieso nicht umgesetzt.

**Comment by 2Abendsegler** [comment]
Solution of @Jipem:
https://github.com/2Abendsegler/GClh/issues/393#issuecomment-322423779
