### ISSUE TITLE
Profil > About > Empty

### ISSUE THREAD

**Issue by Jipem** [2Abendsegler/GClh#393]
Hello,

With the new profile pages (https://www.geocaching.com/p/default.aspx or https://www.geocaching.com/p/default.aspx?guid=6eff0265-cf3f-4802- Aa2f-9e88a47b5446), GClh blocks the contents of the "About" tabs. They are systematically empty. While disabling this script, the content appears.

Thanks,

_###
Windows 10
Google Chrome Version 60.0.3112.90 (Build officiel) (64 bits)
Tampermonkey 4.3.6_

**Comment by 2Abendsegler** [comment]
Hi,
I know this problem but I can not eliminate this stuff.
Please look to this comment:
https://github.com/2Abendsegler/GClh/issues/377#issuecomment-304248489
If you can not understand it, it is in german :) , please come back.
Frank

**Comment by Jipem** [comment]
I added in the settings of GClh, section "user exclusions": https://www.geocaching.com/profile/profilecontent.html
What makes that apparently page works.

**Comment by 2Abendsegler** [comment]
Realy not bad! :)
It is nice if the questioner himself solve the problem.
If the issue is solved, you can close it.
Thanks for the solution.

**Comment by Jipem** [comment]
@2Abendsegler : 
In the next version, can you add
// @exclude          https://www.geocaching.com/profile/profilecontent.html
So that this is the default configuration, and that it works for all users? :-)

**Comment by 2Abendsegler** [comment]
Ok yes, you are right again, I will add it.

I had doubt, because we can not evaluate or change the content in this area. But in the moment we do realy nothing in this area.

Thanks 
Frank

**Comment by Jipem** [comment]
Thank you Franck, I close the ticket !
