### ISSUE TITLE
[FF] #me# in templates does not work & changing templaes does not work

### ISSUE THREAD

**Issue by Cappa-d** [2Abendsegler/GClh#399]
Habe seit heute ein Problem:

Ich habe mehrere Templates für Logeinträge definiert. Bisher ohne Probleme. Seit heute ist es auf mehreren Rechnern so, dass ich die Templates nicht mehr wechseln kann und in dem Standardtext der Parameter 

> #me#

 nicht mehr funktioniert. Es ist zwar scheinbar noch was da, aber wird nicht mehr übernommen als Text.

**Comment by 2Abendsegler** [comment]
Ja, das sind die Header Anpassungen die GS aktuell macht. Der User oben rechts wird nun anders klassifiziert und GClh kann ihn nicht mehr finden. Ich arbeite an einer Lösung. Das wird aber sicherlich noch etwas dauern, weil es nicht nur das ist.

**Comment by Cappa-d** [comment]
Ok danke für die Info! Ich war schon verwirrt weil gestern noch alles ging.
Falls Du weitere Details brauchst für Tests oder so -- bitte melden

**Comment by 2Abendsegler** [comment]
done
Comes with v.0.8.5 in an hour.

**Comment by 2Abendsegler** [comment]
Ich mach dann mal zu

**Comment by Cappa-d** [comment]
Ups! Danke, ja funktioniert alles wieder. Total untergegangen
