### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#4]
Test Comment

**Comment by CachingFoX** [comment]
Oh es funktioniert :-)

**Comment by 2Abendsegler** [comment]
Sehr schön. :-)
Wie man an den bunten Dingen sieht, baue ich etwas an den Labels rum, um die Wunschliste und die Issues hier zu integrieren. Das wird das Handling dann einfacher machen. Und ich werde dann alles hier übernehmen. Das ist sicherlich in deinem Sinne. :-)
