### ISSUE TITLE
VIP List doesn't work

### ISSUE THREAD

**Issue by winkamol** [2Abendsegler/GClh#403]
Implemented the VIPs many times and somehow the VIPs go missing. What can I do? It's enerving.

**Comment by 2Abendsegler** [comment]
Hi,

ich kann dein Problem nicht nachvollziehen. Bei mir funktioniert es wie gewünscht. 

Ist es ein neues Problem seit wenigen Tagen, oder ist das schon länger so?
Auf welcher Seite klickst du auf den VIP Button, in einem Listing?

Versuche mal folgende Einstellungen für die VIPs in der Kategorie "Listing":
![vips](https://user-images.githubusercontent.com/22332216/30033760-868d6852-919d-11e7-97ec-b7fbaf2948ad.jpg)

LG Frank

**Comment by winkamol** [comment]
Hallo Frank,

Ich nutze GCLH 2 seit heute morgen, da ich bisher die alte Version 1 hatte. Ich bin leider sehr unzufrieden damit. Die Einstellungen sind übrigens so wie auf deinem Bild unten. Was mich wundert ist, dass wenn ich das Skript deaktiviere die VIP Liste problemlos funktioniert.

Das nervigste ist das Dropbox Pop-up Fenster, das sich jedes Mal öffnet, sobald ich eine GC Seite lade.

Was kann ich tun? 

Gruß Patrick

**Comment by 2Abendsegler** [comment]
Das hört sich so an, dass du beide Scripte, den GClh und den GClh II parallel benutzt, das geht natürlich nicht. Bitte deaktiviere mal den GClh und schau dann mal obs mit den VIPs nicht doch funktioniert.

Nochmal zur Dropbox: Du solltest mal die automatische Connection zur Dropbox ausschalten. Findest du unter "GClh Config / Sync" Punkt "Auto apply DB Sync".

Hast du die alten Einstellungen des GClh auch im GClh 2 verwendet, oder hast du neu angefangen?

**Comment by 2Abendsegler** [comment]
Kleine Ergänzung: 
Was mir gerade noch einfällt. Das Problem mit der Dropbox kann auch mit dem Parallelbetrieb zusammenhängen.

**Comment by winkamol** [comment]
Ich habe selbstverständlich den alten deaktiviert und nicht beide gleichzeitig am laufen gehabt.
Die Dropbox Synchronisation habe ich deaktiviert, das klappt jetzt. Vielen Dank schon mal. Es scheint aber auch gespeicherte Einstellungen nicht zu übernehmen. Ich habe meine Home Koordinaten eingegeben und jetzt ist es wieder zurück gesetzt.
Außerdem fehlen sämtliche VIPS. Gibt es eine Möglichkeit diese einfach einzubinden? Ich habe sie extra noch in einer Textdatei gespeichert.

Gruß Patrick

**Comment by winkamol** [comment]
Wie gesagt es wurde nicht parallel verwendet.

**Comment by 2Abendsegler** [comment]
Ich gehe mal davon aus, dass die VIPs nun per Button gespeichert werden können.

Es gibt keine Möglichkeit VIPs über eine externe Datei aufzubauen. Man hat lediglich die Möglichkeit die alte Datei mit den Einstellungen vom GClh auch für den GClh II zu verwenden, was ich aber mittlerweile nicht mehr empfehle, weil die alte Datei noch anders aufgebaut war und es damit immer wieder Probleme gab.

Du kannst mit dem Link aus der Linklist "Find Player" direkt auf einen User zugreifen, und dort dann den VIP Button wählen. Das scheint mir der schnellste Weg.

Eigentlich sollten die Homekoordinaten automatisch übernommen werden, das scheint aber wegen einer Änderung von GS nicht mehr zu funktionieren. Das muß ich mir für die nächste Version noch ansehen. Ich bin in Urlaub und mein Equipment reicht hier nicht aus, um das genau zu prüfen.

Wenn du die Homekoordinaten manuell eingibst, dann muß das vermutlich ohne Hochkomma geschehen, schätze ich mal. Versuchs mal.

**Comment by winkamol** [comment]
Alles klar, vielen Dank für die Hilfe aus dem Urlaub! Ich habe jetzt die Namen manuell durchgeklickt in der Hoffnung, dass er es diesmal speichert.

Dann wünsche ich noch einen erholsamen Urlaub!

Gruß Patrick

**Comment by 2Abendsegler** [comment]
Wenn das Ticket soweit erledigt ist, dann bitte schließen.
LG Frank
