### ISSUE TITLE
Dropbox opens a new window every time I open a new page

### ISSUE THREAD

**Issue by winkamol** [2Abendsegler/GClh#404]

**Comment by 2Abendsegler** [comment]
Hi,

ja, hier hast du wohl recht. 

Eigentlich sollte Dropbox irgendwann im September gar nicht mehr funktionieren mit dem Coding im GClh. Vielleicht ist das gerade schon der Fall. Wir beabsichtigen im Moment keine Umstellung auf die neue Verfahrensweise bei Dropbox. Das heißt, die Connection zu Dropbox wird nicht wieder implementiert, sorry. 

In sofern mußt du dich bis auf weiteres von Dropbox verabschieden, zumindest was den GClh angeht.
Bitte schließe das Ticket. 

LG Frank

**Comment by 2Abendsegler** [comment]
#403

**Comment by 2Abendsegler** [comment]
Wenn das Ticket soweit erledigt ist, dann bitte schließen.
LG Frank
