### ISSUE TITLE
Linklist is behind Menue in Map Mode

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#405]
The Linklist Popup is under the left Menue if you are in the GC Map Mode (https://www.geocaching.com/map/). I have added a Screenshot.
<img width="344" alt="menue" src="https://user-images.githubusercontent.com/2239440/30097362-977977e6-92dd-11e7-9c0c-425bc0ffa6c0.png">

**Comment by 2Abendsegler** [comment]
Hi,

yes you are right, thanks.
Please hide the map sidebar as workaround to use the linklist.

Best regards Frank

PS: I'm on holiday until middle of october. Perhaps I only have time after that. :)

**Comment by GFEMajor** [comment]
Ok, than have a nice vacation 😉.
The Problem is located in the function 
`buildCoreCss()`
the z-index of the menue is 100, the z-index of the map sidebar is 999, so just add a "0" in line 1414:
`css += "ul.Menu {margin-left:210px; position:relative; z-index:100}";` 
to
`       css += "ul.Menu {margin-left:210px; position:relative; z-index:1000}";`
would probably fix this.

**Comment by 2Abendsegler** [comment]
This makes sense. 
You can fork the program, fix it, test it and create a pull request if you want. 
And I can transport the changes with a new version.
Only if you want. :)
