### ISSUE TITLE
BRouter-Link

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#425]
#424

**Comment by 2Abendsegler** [comment]
- Neue Config Parameter für Links zu Flopp's Map und BRouter in die Restore Liste ...data/config_standard.txt aufgenommen, damit beim Restore die Standardwerte gesetzt werden.
- Die rechte Maustaste wird bei Flopps Map und Brouter nicht unterstützt. Ich habe die quasi abgeklemmt, so wie es im Coding beim Flopps Link unten bereits war.
- Flopps Map layer Warnung bei BRouter entfernt. Ist wohl vom Kopieren noch dort stehen geblieben. 
- Wird der BRouter Link direkt angewählt, also ohne Auswahl der Karte, kann BRouter das nicht verarbeiten im Gegensatz zu Flopps Map wo dann eine Standard Karte gesetzt wird. Hab Standard Karte gesetzt.
- Hab in der rechten Navigation "Calculate routing on BRouter" in "Calc. routing on BRouter" umbenannt damit nicht umgebrochen wird. Ist das dann noch verständlich?
- Mindest Breite der Dropdown Listen von 160 auf 170 erhöht, dann wird nicht umgebrochen.
- Im Config habe ich die beiden neuen Parameter farblich unterlegt, weil sie neu sind.
- Im Config habe ich für show_help show_help3 aufgebaut, damit der Text darin komplett lesbar ist.

Das waren aber alles nur Kleinigkeiten.
Pull Request erfolgt im Anschluß, dann kannst du Dir das nochmal ansehen. 
Falls aus deiner Sicht alles in Ordnung ist, Close Issue.

**Comment by 2Abendsegler** [comment]
Änderungen stehen im Collector.
Bitte schau sie dir an.

**Comment by GFEMajor** [comment]
> Die rechte Maustaste wird bei Flopps Map und Brouter nicht unterstützt. Ich habe die quasi abgeklemmt, so wie es im Coding beim Flopps Link unten bereits war.

Was genau meinst du damit?

> Flopps Map layer Warnung bei BRouter entfernt. Ist wohl vom Kopieren noch dort stehen geblieben.

hubs 😃, es war spät gestern als ich das gemacht hab 😉
 
Zum Linknamen, vielleicht reicht auch einfach "Show Route on BRrouter"?

Schön das du dir alles nochmal angeschaut hast. Es ist halt doch besser, wenn 2 Leute drüber schauen 😉. Deine Änderungen sehen gut und sinnvoll aus.

**Comment by 2Abendsegler** [comment]
Rechte Maustaste und Open in new Tab. Wenn du jetzt die rechte Maustaste drückst, dann gibt es Open in new Tab gar nicht. Oder hat der Mac vielleicht keine rechte Maustaste ... :)))
 
Hab "Show Route on BRrouter" und unten "Show Route on BRrouter with ..." verwendet.

**Comment by GFEMajor** [comment]
Höre ich da einen leisen Spot aus deinem Text raus 😉. Da bashed wohl jemand gern gegen Mac 😉. Und nein, bei mir gibt es keine rechte Maustaste 😜. Aber ja, der "Open in new Tab" Link im Kontextmenü ist bei mir trotzdem auch weg. Hatte ich gar nicht bemerkt vorhin beim Testen.
Namen für die Links finde ich OK.

**Comment by radlerandi** [comment]
wow das ging ja schneller als gedacht. Habe die neue Version auch erfolgreich bei mir ausprobieren können.
Jetzt überlege ich, wie man es am besten anstellt, dass man die Route rückwärts berechnen lässt. Vermutlich einfach die for-schleife ändern. 
Und ob das ein Feature wäre, dass ich hier beisteuern könnte/sollte, wobei ich es selbst wohl nur 1x brauche - für die Deutschland-Tour Ost-West https://coord.info/GC6128Z, welche man auch West-Ost fahren kann - was ich machen will ;-)

**Comment by 2Abendsegler** [comment]
Wir könnten ein rückwärts Icon hintendran hängen und dort die umgekehrte Sortierung verwenden. 
Beispiel ![index](https://user-images.githubusercontent.com/22332216/31513324-4e852f08-af8e-11e7-92a6-c530064c9f6c.png)
@radlerandi Wie oft benötigt man das denn?
@GFEMajor Was meinst du denn?

**Comment by radlerandi** [comment]
äußerst selten. ;-) die allermeisten Multis haben ja nur eine Richtung und nur eine Dose, und ob ich eine Kreistour rückwärts mache oder nicht, spielt ja auch keine Rolle.
Wollte mir nur die eine Strecke rückwärts machen, und noch die Koords von einem anderen Multi mit in die URL reinpacken konnte, für die die Richtung auch "falsch rum" war. Kann man ja erstmal weg lassen, und wenn sich später zeigt, dass es noch eine nützliche Idee wäre immer noch einbauen

**Comment by 2Abendsegler** [comment]
Ok, dann lassen wir das zuerst mal weg.
Dann dürfte das jetzt alles sein zum Thema BRouter. 
Ich schließ das Teil mal.

**Comment by GFEMajor** [comment]
Bin auch dafür das Rückwertsfeature weg zu lassen. Ich glaube nicht, dass es benötigt wird. Wie @radlerandi schon schreibt, die meisten Cacheowner denken sich ja etwas bei der Reihenfolge der Waypoints. Wenn du es brauchst, kannst du es ja auch einfach in deinen Folk einbauen 😉
