### ISSUE TITLE
VIP Liste: Klick auf den Namen generiert falschen Link bei Sonderzeichen im Namen

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#426]
Wenn man in der VIP Liste einen Namen anklickt, dann kann der Benutzer von Geocaching nicht gefunden werden. Ich denke es liegt an den Sonderzeichen im Namen.

Beispiel: für Geocacher "RasendeZwerge 1+2+3" wird folgender Link generiert: https://www.geocaching.com/p/default.aspx?u=RasendeZwerge%201%2B2%2B3

Ich glaube es liegt nicht an allen Sonderzeichen, sondern eventuell an dem "Plus" (+) im Namen. Denn bei Geocacher "Stefan28 & Co." funktioniert der Link.

Ich denke aber, dass es an Groundspeak liegt, dass Sie den Link nicht verarbeiten können. Aber eventuell kann man die Sonderzeichen anders generieren.

**Comment by 2Abendsegler** [comment]
Kommt immer mal wieder vor. Und du hast wohl recht mit dem + und der Verarbeitung des Links. 
Das kann ich machen in einigen Tagen.

**Comment by GFEMajor** [comment]
Ich habe mir die Sache mal angeschaut. Ich denke nicht, dass es eine Lösung dafür gibt, denn selbst Groundspeak bekommt es nicht richtig hin 😉. Schau mal auf das Listing von https://coord.info/GC7CR0T . Der Cache ist von den Rasenden Zwergen. Wenn du jetzt auf den Link Suche nach ... 
... anderen Geocaches, die vom selben Owner versteckt oder gefunden wurden klickst (egal welchen), kommt man zur Suchen Seite. Und als Fehlermeldung steht "That username does not exist in the system". Es scheint also ein Bug im System selbst zu sein. Kann man das eventuell irgendwo reporten? Hat Geocaching ein Bugtracker?

**Comment by GFEMajor** [comment]
Da ich keinen Issue Tracker gefunden habe, habe ich mal einen Post im Forum gemacht:
https://forums.geocaching.com/GC/index.php?/topic/346244-bug-link-to-profile-page-and-nearest-list-are-not-working-when-user-has-in-his-name/

Ich hoffe die können den Bug nachvollziehen und fixen 😃

**Comment by 2Abendsegler** [comment]
Ich weiß auch keinen anderen Platz für den Issue Tracker. Das scheint mir so richtig wie dus gemacht hast.

Der generierte Link in der VIP Liste für die RasendeZwerge 1+2+3 funktioniert bei mir. Ich hab noch nichts daran geändert. 
https://www.geocaching.com/profile/?u=RasendeZwerge%201%2B2%2B3
Kannst du nochmal bei dir schauen. Mit welchem Browser und unter welchem System arbeitest du.

Der Link Suche nach ... anderen Geocaches von den Rasenden Zwergen funktioniert aber auch bei mir nicht. Das ist ja aber definitiv GS Baustelle.

**Comment by 2Abendsegler** [comment]
Die GUID zu nehmen wäre aus heutiger Sicht wohl richtig. Damals gabs die aber noch gar nicht. ;)
Das jetzt umzustellen ist vermutlich ein riesiger Akt, weil auch die bestehenden VIP Lists bei den Usern umgesetzt werden müssen. Und das eigentlich nur für einen kleinen Mehrwert. Ich würde lieber die Finger davon lassen. :D

**Comment by 2Abendsegler** [comment]
Dein Browser und dein System. FF und Mac?

**Comment by 2Abendsegler** [comment]
Hab jetzt erst dein System ... gesehen, sorry.

Ich schätze mal das ist ein Apple spezifisches Verhalten. Mit Win 8.1 gehts auch mit Chrome und Opera. Safari haben wir sowieso nicht freigegeben. Hier funktionieren scheinbar zumindest die VIP Listen nicht immer.
Schaff dir doch mal nen anständigen Rechner an, jaaahahaha.
 
Ich weiß jetzt nicht was wir hier machen sollen. Hast du noch ne Idee.

**Comment by GFEMajor** [comment]
Ich denke nicht, dass es ein Problem vom GClh ist. Ich habe den Link ganz normal im Browser getestet, ohne das Script aktiv zu haben. In meiner VM (Windows 7 Prof.) geht der Link aber auch nicht! Sehr merkwürdig, dass es bei dir geht.
GC ändert ja den Link (redirect). kannst du mal deinen Finalen Link posten? Ich würde den gern mal sehen. Bei mir kommt am Ende das raus:
https://www.geocaching.com/p/default.aspx?u=RasendeZwerge%201%2B2%2B3

**Comment by 2Abendsegler** [comment]
Wenn ich die url kopiere sieht es so aus:
https://www.geocaching.com/profile/?u=RasendeZwerge%201%2B2%2B3
Angezeigt wird sie aber so:
`https://www.geocaching.com/profile/?u=RasendeZwerge 1%2B2%2B3`

**Comment by GFEMajor** [comment]
ja, weil "%20" für Leerzeichen steht und das wird dann wieder zu einem Leerzeichen. Wie gesagt, dass Problem liegt bei Groundspeak selbst, da die Leerzeichen im Namen durch "+" ersetzen. Das funktioniert dann aber nicht, wenn es noch selbst ein "+" im Namen gibt.

**Comment by 2Abendsegler** [comment]
Ich verstehe.
Dass du das Userscript im Bug Report erwähnt hast macht eine Lösung durch GS nicht wahrscheinlicher ;)
Hast du eine Idee wie wir das regeln können?

**Comment by GFEMajor** [comment]
Ich dachte ich mach einfach bissel Werbung für uns 😋.
Eine Lösung hab ich leider nicht. Ich habe es nicht hinbekommen (auch nicht manuell) einen Link zu generieren, der auf die Profilepage von RasendeZwerge kommt. Wie die Antworten im Thread beweisen scheint das Problem aber bekannt zu sein. Die Frage wäre, ob man sich aus dem Username des Benutzers irgendwie die GUID erzeugen kann. Aber da man den Benutzernamen ja ändern kann, sehe ich das eher nicht als möglich an. Ich denke die GUID wird bei Anmeldung vergeben.

Was man machen könnte wäre beim hinzufügen eines VIPs nicht nur seinen Namen, sondern auch seine GUID zu speichern. Das ist an sich kein Problem, denn der Link zum Userprofile über dem Button enthält diese direkt. 
Dann wäre das Problem komplett weg. Das heißt aber auch, man muss in eine der neuen Versionen einen Konverter einbauen, der für die "alten" VIPs die GUIDs abruft und das Array umwandelt. Das sollte an sich kein Problem sein, nur muss man alle Stellen anpassen, die VIPs betreffen. Den Umfang kannst du sicher besser abschätzen als ich.

**Comment by 2Abendsegler** [comment]
Die GUID wird bei Anmeldung vergeben, yep.

Im Rahmen des Einbaus der VUPs ist die komplette Funktionalität etwas vereinfacht worden. Das sollte damit alles in einem Packen zusammen stehen - ab 5410, die Einfärbung der Logs steht wohl an anderer Stelle. Ich hatte mir damals allerdings gesagt, dass ich nie wieder dort Hand anlegen werde, solange alles funktioniert, und das tut es eigentlich. ;) 
Außerdem bin ich mir nicht sicher, ob überall eine guid zur Verfügung steht, wo wir heute unsere VIP bzw. VUP Buttons aufbauen.

Lediglich der Aufruf von User Profilen aus VIPs bzw. VUPs mit plus im Namen aus Apple Rechnern heraus funktioniert nicht, vermutlich für alle Browser. Die eigentliche VIP und VUP Funktionalität tut es aber nach wie vor auch dort. Ist doch richtig oder?

In sofern würde ich hier lieber kein Faß aufmachen. 
Wenn du dich diesem Thema widmen möchtest, kannst du das aber trotzdem tun. :)

**Comment by 2Abendsegler** [comment]
Werbung ist gut. Schätz mal wieviel User wir haben, schätzen nicht nachsehen.

**Comment by GFEMajor** [comment]
Ich wüsste nichtmal wo man das nachschauen kann 😃. Aber keine Ahnung, 100?

ok, ich sehe das Argument. Wenn wir irgendwann mal ein anderes Problem mit den VIPs haben, dann können wir das ja mit anfassen. Insofern würde ich das Ticket zu machen und auf rejected setzen.

**Comment by 2Abendsegler** [comment]
Im Coding sind drei Counter zu den Installationen eingebaut. Und [hier](https://github.com/2Abendsegler/GClh/blob/master/docu/counter.md) gibt es dazu ein paar Daten, immer gemessen nach zwei Wochen, sofern ich daran gedacht habe. Wir starteten unter 600 und sind nun bei etwa 1300.

**Comment by GFEMajor** [comment]
Cool 😃. Doch sehr viel mehr als ich dachte 😃
