### ISSUE TITLE
Automatically save HomeCoords does not work 

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#438]
Für Bug #322 habe ich mal meine Home Coords gelöscht. Wenn ich jetzt auf den Link "nearest List" klicke kommt das Popup, dass keine Home Coords gespeichert sind, und nach einem klick auf Ok werde ich zur Einstellungs-Seite geleitet, aber meine Homecoords werden nicht gespeichert. Die Funktion wirft einen Fehler.
Es sieht aus, als ob das Fenster mit den Homecoods (Input und google Karte) asynchron geladen werden und zur Zeit, wenn die Funktion ausgeführt wird noch nicht geladen sind.

**Comment by GFEMajor** [comment]
@2Abendsegler kannst du den Bug bestätigen?

**Comment by 2Abendsegler** [comment]
Ja, ich habs auch zweimal hinbekommen. Immer dann wenn ich die Seite mit den Homekoordinaten vorher noch nicht angewählt hatte, werden die Koordinaten nicht übernommen. Du könntest also gut recht haben.

Ich werde mir das ansehen. Du hast im Moment besseres zu tun. :)

**Comment by 2Abendsegler** [comment]
Fix steht im collector zur Verfügung.
