### ISSUE TITLE
Authentificate with Dropbox does not work

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [2Abendsegler/GClh#439]
May be it's an individual problem, but Authentication of Dropbox does not work for me.

Opened GC little helper Sync II (v0.8.8), expanded "DropBox", clicked [authenticate], entered my credentials on dropbox.com, (even confirmed the dropbox mail (new device connected)), but there is still the [authenticate] button below "DropBox".

On second try Firefox just fetches the token from https://www.dropbox.com and reopens GC little helper Sync II, then "Working" appears for about half a second but at the end ... the [authenticate] button is there again.

Restarted Firefox several times, same procedure, but no changes.

Any suggestions?

Cheers, Mag'

**Comment by 2Abendsegler** [comment]
(Nebenbei, hat mit dem vermeintlichen Problem nichts zu tun:
Der Restore des Token funktioniert nicht mehr, weil nun die Version auf dem master steht, beim beta Test aber nur aufm collector, selbst verscheißert. Hat mit dem vermeintlichen Problem nichts zu tun, man kann nur eben nicht mal alles zurücksetzen.
Fixed mit v0.8.9.)

**Comment by 2Abendsegler** [comment]
Hi,
bitte ruf mal den Sync auf, wähle Manual und dann export. Scroll mal ganz nach unten. Steht dort "settings_DB_auth_token" und steht dort etwas kryptisches dahinter?

**Comment by 2Abendsegler** [comment]
Ach, und noch etwas. Wenn du https://www.dropbox.com anwählst, bist du dann in deinem Account angelogged?

**Comment by GFEMajor** [comment]
@MagpieFourtyTwo Vielleicht kannst du auch mal Screenshots von den einzelnen Schritten machen? Dann können wir es vielleicht nachstellen.

**Comment by MagpieFourtyTwo** [comment]
Hallo zusammen,

zunächst mal danke für eure Reaktionen!  Schön zu sehen, dass man mit seinen Problemen nicht alleine steht.  :)

Aaalso ... anscheinend handelt es sich um ein lokales Problem meines Büro-Rechners, mglw. des Netzwerkes, denn von daheim hat's gestern abend dann wunderbar geklappt. Was mich zugegebenermassen etwas überrascht hat, denn die beiden Firefoxes sind weitestgehend identisch konfiguriert und haben vor allem auch die gleichen AddOns und Scripte. Und wurden bislang auch über die Dropbox synchronisiert (und das sollte auch weiterhin so sein, denn das sind die zwei wichtigsten).

Screenshots gehen leider nicht, dabei kriege ich (zumindest hier im Büro) einen Fehler: "Something went really wrong, and we can't Process that file. Try again" - für jpg eher ungewöhnlich.  Das passiert unabhängiog davon, ob ich's per Dateiauswahl oder Drag'n Drop mache.  Seltsam.

Abgesehen davon würden sie aber wohl eh nicht sonderlich viel bringen, denn da wäre nicht mehr drauf, als der normale Synch-Settings-Dialog und die DropBox Anmeldemaske, die eh jeder beide kennt. Ablauf noch mal: ich klicke halt auf [authenticate], FF wechselt zu dropbox.com, wo ich die Credentials eingebe, und dann geht's (in einem neuen Tab!) zurück zum Synch-Settings-Dialog, der zuhause dann glaub [Upload] und [Download] anzeigt (und es auch tut, wie eine kurze Kontrolle der DropBox-Files ergeben hat), aber im Büro kommen halt nicht diese zwei Buttons sondern wieder [authenticate].

Zu den weiteren Fragen:
- DropBox-Anmeldung: Wenn ich danach auf dropbox.com gehe, brauche ich mich nicht noch mal anzumelden, bin dann gleich drin, das Anmelden scheint also zu tun.
- Token im manuellen Export der Einstellungen: Ja, das scheint vorhanden zu sein, letzte Zeile ist "settings_DB_auth_token": "Ew-kIxh...L", danach ein CR/LF und geschweifte Klammer zu.

Könnte es sein, dass die Authentifizierung mittels dieses Tokens dann über einen anderen Port als 80 bzw. 443 geht? Dann könnte evtl. ein Firewall- oder Routing-Problem sein ...

Cheers, Mag'

**Comment by MagpieFourtyTwo** [comment]
Gerade nachgesehen: In den Firewall Protokollen hab ich kein entsprechendes DENY gefunden ...

**Comment by GFEMajor** [comment]
> Ablauf noch mal: ich klicke halt auf [authenticate], FF wechselt zu dropbox.com, wo ich die Credentials eingebe, und dann geht's (in einem neuen Tab!) zurück zum Synch-Settings-Dialog,

Kannst du mal bitte schauen, wie du URL aussieht, wenn du wieder auf die GC Seite zurück kommst? Sieht die URl so aus?:

https://www.geocaching.com/my/default.aspx#access_token=XXXXXX
&token_type=bearer
&uid=XXXXX
&account_id=XXXXXX

Eventuell liegt es auch daran, dass ein neuer Tab geöffnet wird. Bei mir geht das alles in der gleichen Seite.

**Comment by MagpieFourtyTwo** [comment]
Der URL sieht genau aus wie erwartet:
https://www.geocaching.com/my/default.aspx#access_token=Ew-k...5r0U&token_type=bearer&uid=1...4&account_id=dbid%3AAA...pM

**Comment by MagpieFourtyTwo** [comment]
Hab jetzt mal alle Fenster geschlossen und den URL mit Token in einem ganz neuen Fenster direkt aufgerufen - keine Änderung, es wird immer noch [authenticate] angezeigt.

**Comment by GFEMajor** [comment]
Und du bist sicher, dass du die neuste Version des Scriptes installiert hast?
![image](https://user-images.githubusercontent.com/2239440/32099695-8d6c13ec-bb11-11e7-85c3-7c0a7789b725.png)

**Comment by MagpieFourtyTwo** [comment]
Zu den sich bei jedem Klick auf [authenticate] neu öffnenden Tabs:
Das liegt am AddOn TabMix Plus - hab jetzt mal meine darin normalerweise gesetzte Option "Force to open in new tabs: [X] Links to other sites" deaktiviert. Es wird nun zwar kein neues Tab geöffnet, alles spielt sich im ursprünglichen ab, aber das Verhalten bleibt gleich. Hätte mich auch gewundert, denn daheim ist das auch so eingestellt und da hat die Authentification ja geklappt.

Nichtsdestotrotz habe ich auch das GM-Script "GC-Vote" mal deaktiviert ("GC Tour" ist auch installiert, aber eh deaktiviert) und noch mal probiert - ebenfalls keine Änderung. :/

Ja, Version ist die v0.8.8.

Cheers, Mag' - ratlos

**Comment by MagpieFourtyTwo** [comment]
Kann man das Ding irgendwie debuggen?
Bzw. an welchen Stellen würde man sinnvollerweise Debug-Output einbauen?
Programmierkenntnisse sind vorhanden ... ;)

**Comment by GFEMajor** [comment]
Also erster Ansatzpunkt wäre die Funktion, die den Dropbox_Auth_Token ausliest zu testen.
Da gibt es einen Kommentar im Code:
`// Save dropbox auth token if one is passed (from Dropbox))` (Bei mir in Zeile 11012)

Dort könntest du schauen, ob er in die if-Verzweigung rein geht und den Wert "settings_DB_auth_token" setzt.

Am besten mal sowas wie
`alert(getValue('settings_DB_auth_token'));`

Wenn Dort dein Token drin steht (der der auch in der URL übergeben wird) dann sollte das schonmal passen.

**Comment by MagpieFourtyTwo** [comment]
Ok, mach ich ... gegen etwas später, jetzt erst mal Besprechung ... ;)

**Comment by 2Abendsegler** [comment]
So wie es sich für mich darstellt, wird der Token im GClh gespeichert und die URL mit dem Token wird wohl auch korrekt aufgebaut. Insofern würde ich annehmen, dass bis dahin aus Sicht des GClhs alles korrekt abläuft. Ich würde dort beginnen zu debuggen, wo der GClh nach der Anfrage an DropBox meint, der Zugang wurde nicht gewährt. @GFEMajor du weißt sicherlich wo das ist. 

Ich würde aber vielleicht vorab alles auf Anfang zurückdrehen, den Token löschen und das DropBox Prozedere einfach mal neu machen. Leider geht das in der v0.8.8 nicht weil ich was übersehen hatte. Das ist aber in der zukünftigen Version korrigiert, die vorab [hier](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) installiert werden kann. Es verbleibt dabei bei v0.8.8. 

Nach der Installation dann den GClh Config aufrufen, oben rechts "Reset" anwählen, "Reset dynamic and unused data" markieren und "reset" button wählen. Dabei sollte auch der Token gelöscht werden - gelöschtes wird abgelistet. Dann am Besten die GC Seite in neuem Fenster neu anwählen und DropBox Prozedere im Sync starten ...

**Comment by MagpieFourtyTwo** [comment]
Ok, done.  Mit folgendem Code ...

```
    // Created the Dropbox Client with the given auth token from config.
    function gclh_sync_DB_CheckAndCreateClient() {
        var deferred = $.Deferred();
        token = getValue('settings_DB_auth_token');

        if (token) {
            // Try to create an instance and test it with the current token
            dropbox_client = new Dropbox({ accessToken: token });
alert('token: ' + getValue('settings_DB_auth_token'));                          // DEBUG
            dropbox_client.usersGetCurrentAccount()
                .then(function(response) {
alert('usersGetCurrentAccount.then: ' + getValue('settings_DB_auth_token'));    // DEBUG
                    deferred.resolve();
                })
                .catch(function(error) {
alert('usersGetCurrentAccount.catch: ' + getValue('settings_DB_auth_token'));   // DEBUG
                    deferred.reject();
                });

        }else{
            // No token was givven, user has to (re)auth GClh for dropbox
alert('no token given: ' + getValue('settings_DB_auth_token'));                 // DEBUG
            dropbox_client = null;
            deferred.reject();
        }

```

... bekomme ich folgende zwei Alert Messages:
- "token: XXXXX"
- "usersGetCurrentAccount.catch: XXXXX"

... wobei das XXXXX mit sowohl dem Token in der manuell exportierten config übereinstimmt, als auch mit dem in dem URL, mit dem gc.com von der dropbox aus wieder aufgerufen wird. Grundsätzlich scheint das also erst mal gut zu gehen. Nur scheint er mit der dropbox-Antwort wohl nicht zufrieden zu sein.

Kriegt man das "function(error)" noch weiter aufgedröselt? Kann grad keine Doku wälzen ...

Cheers, Mag'

**Comment by MagpieFourtyTwo** [comment]
Das übrigens mit der 0.8.8b-Version, also auch vorher mal ein Reset der dynamic and unused data gemacht - ohne Änderung der Situation.

**Comment by GFEMajor** [comment]
ok, dann liegt der Fehler wohl beim aufbau der Dropbox verbindung, da bei dir der "catch(error)" Zweig aufgerufen wird. Ändere deinen Code mal bitte folgendermaßen und schaue, was in der Fehlermeldung ausgegeben wird:

`function gclh_sync_DB_CheckAndCreateClient() {
        var deferred = $.Deferred();
        token = getValue('settings_DB_auth_token');

        if (token) {
            // Try to create an instance and test it with the current token
            dropbox_client = new Dropbox({ accessToken: token });

            dropbox_client.usersGetCurrentAccount()
                .then(function(response) {
                    deferred.resolve();
                })
                .catch(function(error) {
                    alert(error);
                    deferred.reject();
                });

        }else{
            // No token was givven, user has to (re)auth GClh for dropbox
            dropbox_client = null;
            deferred.reject();
        }

        return deferred.promise();
    }`

**Comment by MagpieFourtyTwo** [comment]
Hallo GFEMajor,

wieder am Platze gleich mal ausprobiert:
Beim Aufruf von https://geocaching.com/my/default.aspx kommt lediglich ein Alert mit "[object Object]", sonst nix.
Nach [OK] klicke ich auf "GClh_Sync_II" (auf der obigen Seite) und es kommt wieder "[object Object]".
Gehe ich dann auf [authenticate], erscheint in der Adressliste der DropBox-URL in folgender Form:
https://www.dropbox.com/oauth2/authorize?response_type=token&client_id=XXXXX&redirect_uri=https://www.geocaching.com/my/default.aspx
und auf Dropbox.com wieder der Alert "[object Object]".  Danach gebe ich die DropBox-Anmeldedaten ein und
Firefox geht mit folgendem URL zurück nach geocaching.com:
https://www.geocaching.com/my/default.aspx#access_token=XXXXX&token_type=bearer&uid=127502984&account_id=dbid%XXXXX
wo dann GClh Sync II mit dem kreiselnden "Working" erscheint, im Vordergrund wiederum "[object Object]".
Klicke ich im Alert auf [Ok] kommt er noch ein zweites Mal und gestätige ioch auch den mit [Ok], kommt wieder das [authenticate].

Cheers, Mag'

**Comment by GFEMajor** [comment]
Ach Mist, es geht ja im Alert leider nicht Objekte auszugeben.

Tausche mal bitte das Commando
`alert(error);`
gegen 
`console.error('gclh_sync_DB_CheckAndCreateClient: Error while creating Dropbox Client:');
  console.error(error);`

Btw: In der nächsten Version wird das dann auch im "normalen" Code mit drin sein, so dass wir da Logausgaben haben.

Wenn du von Dropbox zurück bist, mache mal einen Rechtsklick auf die Seite und wähle "Element untersuchen".
Im neuen Fenster schau mal ganz oben, da sollte irgendwo "Konsole" stehen und dort sollte eine Fehlermeldung ausgegeben werden.

**Comment by GFEMajor** [comment]
Die Error Ausgabe ist jetzt auch im Collector, wenn du lieber die Version installieren willst und nicht dein Script von Hand ändern möchtest:
https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js

**Comment by MagpieFourtyTwo** [comment]
Loading failed for the <script> with source “https://www.googletagmanager.com/gtm.js?id=GTM-N3KS8V2”.  default.aspx:1
Loading failed for the <script> with source “https://www.googletagservices.com/tag/js/gpt.js”.  default.aspx:1
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.  default.aspx:1
Loading failed for the <script> with source “https://secure.quantserve.com/quant.js”.  default.aspx:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery.min.js:3:3869
gclh_sync_DB_CheckAndCreateClient: Error while creating Dropbox Client:  gc_little_helper_II.user.js:11037:21
	gclh_sync_DB_CheckAndCreateClient/< file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/gc_little_helper_II.user.js:11037:21
	D file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2481
	F file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2595
	S file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2384
	T file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:1966
	l file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:653
Object { status: undefined, error: "Error: Request has been terminated …", response: undefined }  gc_little_helper_II.user.js:11037:111
	gclh_sync_DB_CheckAndCreateClient/< file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/gc_little_helper_II.user.js:11037:111
	D file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2481
	F file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2595
	S file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2384
	T file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:1966
	l file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:653
gclh_sync_DB_CheckAndCreateClient: Error while creating Dropbox Client:  gc_little_helper_II.user.js:11037:21
	gclh_sync_DB_CheckAndCreateClient/< file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/gc_little_helper_II.user.js:11037:21
	D file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2481
	F file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2595
	S file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2384
	T file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:1966
	l file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:653
Object { status: undefined, error: "Error: Request has been terminated …", response: undefined }  gc_little_helper_II.user.js:11037:111
	gclh_sync_DB_CheckAndCreateClient/< file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/gc_little_helper_II.user.js:11037:111
	D file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2481
	F file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2595
	S file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2384
	T file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:1966
	l file:///D:/Programme/Internet/Firefox/Magpie/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:653
Autosync: Hash function was not successful:  gc_little_helper_II.user.js:11302:13
Dropbox client is not initiated.  gc_little_helper_II.user.js:11303:13
gclh_sync_DBHash: Error while getting hash for config file:  gc_little_helper_II.user.js:11169:13
Object { status: undefined, error: "Error: Request has been terminated …", response: undefined }  gc_little_helper_II.user.js:11170:13
AI: TelemetrySampledAndNotSent message:"Telemetry is sampled and not sent to the AI service." props:"{SampleRate:1}"  Logging.ts:201:20

**Comment by MagpieFourtyTwo** [comment]
Die "Loading failed for the <script> with source “https://www.google..." etc. kommen daher, dass ich die Google Analytics Geschichten per NoScript geblockt habe. An der Config dafür kann's aber nicht liegen, denn die ist im Büro und daheim identisch. Und daheim tut's ja. Zudem hatte ich NoScript im Büro auch schon deaktiviert, ohne Änderung.

**Comment by GFEMajor** [comment]
Also was ich als "wichtig" sehe ist folgende Fehlermeldung:

"error: "Error: Request has been terminated …""

Steht bei den 3 Punkten vielleicht noch etwas? Kann man das noch "aufklappen"?
Das sieht für mich aus, als ob Dropbox (oder dein Arbeitsnetzwerk) die Verbindung zu Dropbox nicht zu lässt.

**Comment by MagpieFourtyTwo** [comment]
Das "Aufgeklappte" steht oben schon mit drin, gleich nach der "Object { status:" Zeile.
Hier noch mal das von der Meldung mit dem "terminated":
```
Object { status: undefined, error: "Error: Request has been terminated …", response: undefined }  gc_little_helper_II.user.js:11037:111
	gclh_sync_DB_CheckAndCreateClient/< file:///D:/Programme/Internet/Firefox/Dirk/gm_scripts/GC_little_helper_II/gc_little_helper_II.user.js:11037:111
	D file:///D:/Programme/Internet/Firefox/Dirk/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2481
	F file:///D:/Programme/Internet/Firefox/Dirk/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2595
	S file:///D:/Programme/Internet/Firefox/Dirk/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:2384
	T file:///D:/Programme/Internet/Firefox/Dirk/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:1966
	l file:///D:/Programme/Internet/Firefox/Dirk/gm_scripts/GC_little_helper_II/Dropbox-sdk.min.js:8:653
```

**Comment by GFEMajor** [comment]
Ich hab mal die Dropbox API angeschaut. Da steht der Fehler noch etwas ausführlicher drin:

> Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

Das heißt, er kann Dropbox nicht erreichen. Da es nur auf Arbeit bei dir nicht geht, würde ich sagen, dass die Verbindung, die der DropboxClient aufbauen will von deinem Rechner oder deinem Arbeitsnetzwerk geblockt wird.

Mein Lösungsansatz wäre (falls das bei dir auf Arbeit geht). Installiere dir mal Chrome und füge GClh dort ein (wie das geht steht hier: https://github.com/2Abendsegler/GClh/blob/master/docu/tips_installation.md#readme). Wenn es dort klappt, dann ist es irgendeine Extension oder ein AdBlocken oder sowas, der die Verbindung verhindert. Wenn es dort auch nicht klappt, dann liegt es wirklich an der Firewall deines Rechners oder der Firma.

Sollte das der Fall sein, bleibt dir noch die Möglichkeit die Einstellungen einmalig Manuell zu exportieren / importieren. Das ist dann zwar nicht so komfortabel, aber du musst wenigstens nicht alle Einstellungen noch einmal machen.

**Comment by MagpieFourtyTwo** [comment]
So, ich hab's ... *uff*

Allerdings hab ich nur eine Massnahme, die zum Erfolg geführt hat, aber die Gründe sind mir völlig unklar.
Was ich getan habe:

- gestern noch Firefox von Grease- auf Tapermonkey umgebaut (der bei mir übrigens deutlich performanter läuft als GM), was aber (erwartungsgemäss) keine Änderung bzgl des aktuellen Problems brachte.
- heute Chrome installiert (mit *sehr* schlechtem Gefühl im Bauch, denn Spyware mag ich nicht sonderlich)
- darin GClh II unter TM installiert und die Config vom Firefox TM herübergeholt
- GClh Sync aufgerufen ... tat sofort, ohne weitere Authentifizierung, das Token war also ok
- Chrome gleich wieder deinstalliert und alles gelöscht. ;)

Danach war klar, dass es nicht am Netzwerk, sondern an irgend einer Firefox Einstellung liegen muss.
Also nach und nach alle AddOns de- und wieder aktiviert, bis NoScript als "Verursacher" entlarvt war:
Ohne NoScript tat's, mit aber nicht.  Also geblockte Sites kontrolliert (was de facto nur Tracking Sites waren, die zudem exakt wie daheim konfiguriert sind) ... und nun kommt das, was ich nicht verstehe: Gehakt hat es wegen Scripts von [quantserve.com ](https://www.theguardian.com/technology/2012/apr/23/quantcast-tracking-trackers-cookies-web-monitoring) - und der Witz an der Sache: Einmal per "Temporarily Allow" zugelassen, in GClh Sync die DropBox-Authentifizierung durchgeführt, danach Quantserve wieder "Untrusted" gemacht ... und nun geht es trotz geblocktem quantserve.com ... selbst wenn ich das Token resette und ganz neu mache ... kann mir das jemand erklären?  Also, gleich zwei Sachen: 1. Was hat Quantserve mit der DropBox-Kommunikation zu tun und 2. warum geht's, wenn man's einmal kurz erlaubt und dann gleich wieder sperrt ...?

Für Leute, die nur kurz drüberfliegen und nur den Fix wollen, hier noch mal in Stichpunkten:

- in NoScript quantserv.com per "Temporary Allow" zulassen
- in GClh Sync II [authenticate] durchführen (danach sollten Upload und Download angezeigt werden)
- in NoScript quantserv.com wieder als "Untrusted" markieren

Cheers, Mag' - aka Kannitverstan.

**Comment by MagpieFourtyTwo** [comment]
Übrigens (offtopic) bin ich bei der Umarbeitung darüber gestolpert, dass der Link für die [Migrationshilfe ](https://github.com/2Abendsegler/GClh/blob/v0.8.9/docu/tips_migration.md#6), der im Kapitel "Firefox" auf der [Installationsseite](https://github.com/2Abendsegler/GClh/blob/master/docu/tips_installation.md#readme) drauf ist, ins Leere zeigt.

**Comment by GFEMajor** [comment]
> Gehakt hat es wegen Scripts von quantserve.com - und der Witz an der Sache: Einmal per "Temporarily Allow" zugelassen, in GClh Sync die DropBox-Authentifizierung durchgeführt, danach Quantserve wieder "Untrusted" gemacht ... und nun geht es trotz geblocktem quantserve.com ... selbst wenn ich das Token resette und ganz neu mache ... kann mir das jemand erklären? Also, gleich zwei Sachen: 1. Was hat Quantserve mit der DropBox-Kommunikation zu tun und 2. warum geht's, wenn man's einmal kurz erlaubt und dann gleich wieder sperrt ...?

Ich bin ganz ehrlich, ich habe keine Ahnung was quantserve damit zu tun hat. Wir bauen das nicht ein. Eventuell nutzt es Dropbox um die API aufrufe zu tracken. Warum es aber funktioniert, wenn du es ab und wieder an schaltest, verstehe ich genauso wenig wie du.
Aber schön, dass du eine Lösung gefunden hast. Dann kann die Issue ja jetzt geschlossen werden 😃.

**Comment by MagpieFourtyTwo** [comment]
Jau, sehe ich ebenso.

Und besten Dank noch mal für den Support!

**Comment by 2Abendsegler** [comment]
(Offtopic: Danke für den Hinweis, Link ist korrigiert.)
