### ISSUE TITLE
DropBox Authentificate does not work (DropBox Error 400)

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#447]
Error (400)
It seems the app you were using submitted a bad request. If you would like to report this error to the app's developer, include the information below.
More details for developers
Invalid redirect_uri: "https://www.geocaching.com/my/": It must exactly match one of the redirect URIs you've pre-configured for your app (including the path).

**Comment by 2Abendsegler** [comment]
Moin,
 
1. Habe ich das richtig verstanden, dass die gc Seite von der der Aufruf zu DropBox durchgeführt wird, auch die return URL von DropBox ist, die wiederum in DropBox definiert sein muß? 

2. Das scheint nur für die Autorisierung zu gelten und nicht für save und load, oder?

3. Man kann quasi von fast allen Seiten die Sync Funktionalität aufrufen mit Taste F10. Also beispielsweise https://www.geocaching.com/pocket/default.aspx (Pocketquery Übersicht) und dort dann F10. Insofern kämen fast alle gc Seiten in Frage.  

4. Wenn ich mich richtig erinnere, wurde die alte DropBox Authentifizierung über einen neuen Bildschirm behandelt. Wenn dort etwas schief gegangen ist, dann ist man in diesem neuen Bildschirm immer auf dem Profil gelandet. Vielleicht war der aktuelle Fehler damals schon der Grund, warum die Verarbeitung in einem eigenen Bildschirm abgelaufen ist. So quasi damit man immer die gleiche URL hat. Kann das sein?  

5. Bist du nicht schon weg?

LG

**Comment by GFEMajor** [comment]
1. Ja, das klingt so, als ob du es verstanden hast 😃.
2. Ja, nur für Auth
3. Ohh, das ist natürlich schlecht 😃.
4. Dazu kann ich nichts sagen
5. Nein 😃. Dann mache ich das anders und setze explizit die return URL bei uns im Script. Bis jetzt wird einfach die aktuelle Seite gesetzt. ich kümmere mich drum.

**Comment by 2Abendsegler** [comment]
DropBox hat keine prio ... :)
Machs nur wenn du noch ausreichend Zeit hast.

**Comment by GFEMajor** [comment]
Ist schon gefixt 😉.
