### ISSUE TITLE
Added Error Output to Dropbox Client Creation

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#450]
#449

**Comment by GFEMajor** [comment]
@2Abendsegler sollen wir für sowas immer eine Issue aufmachen? Oder ist das nur für das Changelog? Ich hoffe es war ok, dass ich das gleich in den Collector gemerged habe.

**Comment by 2Abendsegler** [comment]
Es muß eine einfache Möglichkeit geben, alle Änderungen zu überblicken und zu prüfen, ob alle Änderungen in der zukünftigen Version enthalten sind. Im Moment mache ich das über die zuletzt geänderten Issues, die immer einen Verweis auf einen Milestone haben müssen. Das geht RuckZuck. 
Also ja, ohne Issue kein Merge.

Merge war ok.

**Comment by GFEMajor** [comment]
ok, ich werde es demnächst beherzigen :)
