### ISSUE TITLE
Make Tampermonkey possible in Firefox

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#451]

**Comment by PontiacCZ** [comment]
Hi Frank,
if I understood the latest changelog correctly (Google translate ;) ) then Tampermonkey is not only going to be "possible" in Firefox but mandatory.

What is the reason behind the retreat from good-old Greasemonkey? Has Tampermonkey become a better script manager lately? Just curious. :)

**Comment by GFEMajor** [comment]
Hi @PontiacCZ 
yes, this change will be mandatory for all users of firefox Version 57 and higher.
With version 57, firefox is changing its core and thus will not be supporting extensions with the "old core". Until now, there are no affords from Greasemonkey to rewrite their code for the new firefox core, so if you update to FF57, Greasemonkey will simply stop working. You can check this in the Add-Ons Tab on Firefox. There should be something like "old extension type" behind Greasemonkey.
Luckily Tampermonkey is compatible with the new Firefox core, so we can all switch to it and enjoy GClh like before 😉

**Comment by GFEMajor** [comment]
You can read more about it here: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

**Comment by PontiacCZ** [comment]
Thanks for explanation, I am already reading it. You're right, Greasemonkey shows up with a note "LEGACY" in the extensions list. So do all other extensions except one! I wonder how many of them will make it to the new format of 57... :-o
