### ISSUE TITLE
Relate web page has disappeared

### ISSUE THREAD

**Issue by khaderaque** [2Abendsegler/GClh#471]
The box that usually displays between the name of the cache and the cache coordinates has disappeared in recent updates.
The box title is "Please note". 
I also noticed that:
- the "Log your visit inline " link appears two times sequentially. If i disable the script, there is only one link.
- the VIP list only has the owner. If i disable the script, other users appear.
I hope this helps and it's not an issue on my side.
Regards

**Comment by 2Abendsegler** [comment]
Could it be that the GClh runs two times? Perhaps one time with script manager Greasemonkey and one time with Tampermonkey? Two "Log your visit inline" links and the VIP behavior are clues.
The GClh is allowed to run only once.

**Comment by khaderaque** [comment]
Thank you. That was the problem. I had the chrome extension running and also the script in Greasemonkey. I had the extension enabled some time ago when the script had some problems due to Groundspeak changes.
All is fine now. Awesome work. 
Regards
