### ISSUE TITLE
This app is unable to link additional users because it has been frozen pending review.

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#475]
I am running FF 57 with GClh II on Tampermonkey now, I chose to set up the GClh from scratch but I had it within minutes. All looks good so far.

I was curious about how Dropbox sync would work out so I clicked on **GClh Sync II**:

![image](https://user-images.githubusercontent.com/9153595/32881010-fb5a64fa-caaf-11e7-87c9-e98651598444.png)

I continued with "Authenticate" and received following error report from Dropbox.com:

![image](https://user-images.githubusercontent.com/9153595/32881055-2eaefb68-cab0-11e7-8921-9f04a73a9e96.png)

I don't understand a single word - what linking? Which users? What review???  :-) What am I supposed to do?

I am attaching screenshot of my GClh Config / Sync section:

![image](https://user-images.githubusercontent.com/9153595/32881384-6196e184-cab1-11e7-8ce3-f023c92f8671.png)

**Comment by 2Abendsegler** [comment]
The GClh has an own Dropbox account with an app. The task of this app is only to connect/link the GClh script to your (user) Dropbox. It seems now, that we have to apply for a production status approval, because a number of users has been reached. But this seems to be not easy because Dropbox want to have a possibility to test the app and some other things ... :) what a rubbish.

More Infos:
https://www.dropbox.com/developers/reference/developer-guide#production-approval

Dropbox rubbish!

I will talk with GFEMajor, our Dropbox specialist.
This will take some time.

**Comment by PontiacCZ** [comment]
Oh, it's getting kind of clear now. :) Well, you might as well consider dropping the Dropbox support. This functionality is not essential for GClh, I guess. The manual export/import works and that is important.

**Comment by GFEMajor** [comment]
Sorry @PontiacCZ for the delay, but I'm still on vacation in Australia with little Internet Access around here :). I've applied our App for Production Mode and hope it will be reviewed soon.
@2Abendsegler I will write you an email with more detailed informations

**Comment by GFEMajor** [comment]
The App is now in production status (yeah). @PontiacCZ can you please test if you can authenticate now?

**Comment by PontiacCZ** [comment]
Yup, I confirm the authentication worked and I managed to save the settings to my Dropbox as well. It is now **Dropbox\Apps\GC Little Helper\GCLittleHelperSettings.json**. 

I only noticed that the previous directory was named "GCLittleHelper" (no spaces) but that does not matter, I'll delete it later.

**Comment by 2Abendsegler** [comment]
> I only noticed that the previous directory was named "GCLittleHelper" (no spaces) ...

I'm guilty. :)

**Comment by GFEMajor** [comment]
Glad to hear that it's working again. Happy Syncing 😃
