### ISSUE TITLE
Trackable Karte vergrößern

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#492]
https://stackoverflow.com/questions/24412325/resizing-a-leaflet-map-on-container-resize
könnte helfen

**Comment by 2Abendsegler** [comment]
Das hatte ich mir auch schon angesehen und mal versucht. Das Resizing ging zwar, die anderen Kartenfunktionalitäten funktionierten aber danach nicht mehr.

**Comment by GFEMajor** [comment]
Was genau meinst du mit "anderen Kartenfunktionalitäten"?

**Comment by 2Abendsegler** [comment]
Mit Plus Minus Zoomen und ich glaube auch die Karte mit gehaltener Maus verschieben ging nicht mehr.

Am 30. November 2017 15:25:21 MEZ, schrieb GFEMajor <notifications@github.com>:
Was genau meinst du mit "anderen Kartenfunktionalitäten"?

**Comment by GFEMajor** [comment]
ok, ich prüfe 😃

**Comment by 2Abendsegler** [comment]
... was mir gerade noch einfällt.
Ich hatte die Vorstellung die Behandlung des DOMMouseScroll Events nicht selbst zu entwickeln, sondern Leaflet die Arbeit machen zu lassen. Ich weiß aber nicht, wie ich ein Event an die Leaflet Funktionalität binden kann. Die verwendete Leaflet Funktionalität ist zwar Teil der GS Quelldateien, trotzdem weiß ich nicht wie ich das machen könnte.

**Comment by GFEMajor** [comment]
Für mich: Das könnte beim Zoom helfen: https://gis.stackexchange.com/questions/111887/leaflet-mouse-wheel-zoom-only-after-click-on-map

**Comment by GFEMajor** [comment]
Ich habe beides gelöst (siehe Email). Meinst du es reichen 500px höhe für die Map, oder lieber Variabel über die Konfig machen?

**Comment by 2Abendsegler** [comment]
Sehr schön, gefällt mir. Lassen wir so. :)
