### ISSUE TITLE
Tampermonkey warning due to not using @connect

### ISSUE THREAD

**Issue by Bananeweizen** [2Abendsegler/GClh#495]
Tampermonkey is warning me about the script trying to request data from Google Maps Elevation and Github. It suggests to add "[@connect](http://tampermonkey.net/documentation.php#_connect) domain" to avoid the warning.

Please add
@connect maps.googleapis.com
@connect raw.githubusercontent.com

**Comment by 2Abendsegler** [comment]
Vielen Dank für den Hinweis. Ich kannte das noch nicht. Für die nächste Version, die allerdings noch etwas Zeit in Anspruch nehmen wird, werden wir das einbauen.
