### ISSUE TITLE
A weird icon in the "Latest logs" icon row

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#496]
Not sure what it might mean.

https://coord.info/GC1HY7N

![image](https://user-images.githubusercontent.com/9153595/33517593-526c6cdc-d787-11e7-9fd1-dac43c70dbff.png)

A Christmas joke? ;-)

**Comment by 2Abendsegler** [comment]
Only in the Latest logs? Something is wrong. It's the weekend of the first advent, there should be further Christmas hats in the VIP-lists, sometimes. But you have a nice one, it's a kissing female Christmas hat. :D

**Comment by PontiacCZ** [comment]
OH! I've just checked out the VIP list and there are much more of these! :-D They're cute. :-) 

OK, thank you for an amusement and since I no longer consider this an issue - I am closing it. :)
