### ISSUE TITLE
Bookmark Liste: Markiere Caches mit korigierten Koordinaten

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#504]
Es wäre cool wenn man auf der Seite der Bookmarklisten (in der Liste selbst) sehen würde, welche der Caches schon korigierte Koordinaten haben.
Das würde mir vor allem beim Lösen von Cacherunden mit vielen Mysteries / Matrixrunden helfen. So sieht man auf einen Blick welche Caches aus der Liste man schon gelöst hat.
@2Abendsegler was hälst du davon?
Ich stelle mir das so vor, dass pro Cache die Daten irgendwie nachgeladen werden, da diese info ja sicher nicht auf dieser Seite verfügbar ist. Oder meinst du das werden zu viele Requests?

**Comment by GFEMajor** [comment]
Also Speichern im GC Speicher sehe ich nicht als Option. Da sind mir persönlich zu viele Unsicherheiten drin. Ich löse auch gern mal am iPad etwas oder trage im Handy Koords ein, da gibts ja dann kein GClh. Weiterhin könnte es ja sein, dass sich die Koords ändern. Dann bekommt es das Script ohne Abfrage auch nicht mit und dann sind die Daten inkonsistent.
Aber es nicht immer zu machen, sondern nur auf Anfrage (Button) finde ich gut. Jetzt muss ich nur noch schauen wo ich die Info her bekomme 😃. Die Api von GC können wir nicht nutzen, oder?

**Comment by 2Abendsegler** [comment]
Theoretisch können wir die Api nutzen, dazu ist aber dann eine Authorisierung des Users notwendig. Und darauf wollte ich eigentlich verzichten, auch deshalb, weil ich etwas in Erklärungsnot käme, warum wir das benötigen. 
Vermutlich müssten wir uns dann auch noch von GS zertifizieren lassen oder so. Es soll ja vermutlich nicht jeder auf die Api Zugriff bekommen.

Als url beim Lesen kannst du das nehmen was du im Online auch nehmen würdest, also beispielsweise einen Link zum Cache, der ja in der BM Liste vorhanden ist. 

So, ich geh jetzt schlafen. :)

**Comment by GFEMajor** [comment]
Ok, das mit der API verstehe ich. Das wäre doof, das stimmt. Vor allem, da man sich dann ja aller 30 Tage neu Authentifizieren müsste.
Die URL zum Cache ist ja kein Problem. den GC Code +  coord.info geht ja schnell ;). Muss nur mal schauen wie ich dann die Information dort abrufen kann.
Schlaf gut 😃

**Comment by GFEMajor** [comment]
So ein Mist. Die Information mit den Korrigierten Koordinaten steht nicht schon beim laden auf der Seite, sondern wird dynamisch durch ein javascript-objekt nachgeladen 😔. Kennst du eine andere Stelle wo diese Information zu finden sein könnte?

**Comment by GFEMajor** [comment]
Nevermind. Ich hab gesehen, dass die das Objekt unten auf der Seite selbst aufbauen. Klappt also schonmal das auszulesen. Jetzt nur noch in "ordentlichen" Code gießen 😃

**Comment by GFEMajor** [comment]
So, der erste Entwurf ist fertig und funktioniert auch 😃. Ich habe es so gebaut, dass es in beiden Versionen (large und compact) funktioniert. Ich hab einen PL erzeugt, aber noch nicht gemerged. Schaus dir am besten mal an.

**Comment by GFEMajor** [comment]
Fertisch
