### ISSUE TITLE
small code to the left menu gc.com ;)

### ISSUE THREAD

**Issue by DrakMrak** [2Abendsegler/GClh#523]
nothing important just I using it for quick access to map and search (it may be useful).
I use in one of my script... (And it's not important, I'm learning the java script on it)

`//Prepare menu
//-----------------------------------------------------------
var nav = document.querySelector('.sidebar-links');
var ul = nav.querySelector('ul');
//-----------------------------------------------------------
//add MAP button
var newli = document.createElement('li');
newli.classList.add ("action-link");
newli.innerHTML = '<a href="https://www.geocaching.com/map/" target="_blank"><svg  class="icon" height="36" width="36"><use xlink:href="/account/app/ui-icons/sprites/global.svg#icon-map-no-border"></use></svg>Map</a>';
//add element to right place
//-----------------------------------------------------------
ul.insertBefore(newli,ul.childNodes[0]);  //MAP
//-----------------------------------------------------------
//add Search button
var newlii = document.createElement('li');
newlii.classList.add ("action-link");
newlii.innerHTML = '<a href="https://www.geocaching.com/play/search" target="_blank"><svg  class="icon icon-svg-fill charcoal" height="36" width="36" style="margin-left:3px; margin-right:19px; margin-top:5px; margin-bottom:5px; width:26px !important;height:auto !important;"><use xlink:href="/account/app/ui-icons/sprites/global.svg#icon-spyglass-svg-fill"></use></svg>Search</a>';
//add element to right place
//-----------------------------------------------------------
ul.insertBefore(newlii,ul.childNodes[0]);  //SEARCH
//-----------------------------------------------------------`

Have a nice day ;)

**Comment by GFEMajor** [comment]
Hi @DrakMrak. As a workaround. You have the Linklist in the left menu. So you could simply add the map/search to the Linklist 😉. Maybe this is enough?

**Comment by DrakMrak** [comment]
probably yes :) I wrote that it is not important... :)
these are the two most used things...  that's why I use it

You're doing a wonderful job I'm just learning ;)

**Comment by 2Abendsegler** [comment]
Of course, both links are available on some other ways, in the Linklist above, in the Linklist and the Default Links in the left sidebar and of course in GC menu Play. But I mean this new way is not bad, it has something nice. And with settings in config everyone can take it or throw it away. 

@DrakMrak 
Perhaps you can fork the GClh and build your code in GClh. Line number should be about 3898, under this ...
`// Improve dashboard.`
`if (is_page("dashboard")) {`
`try {`
Then you can make a pull request so we can apply your changes.

GFEMajor or I will do the rest with the settings in section "Public Profile / Dashboard" Config and perhaps other necessary things. Perhaps we split this section meaningful, somehow everything came in here, I don't know, we will see.

**Comment by DrakMrak** [comment]
Thanks, I will look at it :) ... I try fork GClh and make changes...

**Comment by GFEMajor** [comment]
If You need any help let us know

Gesendet mit der GMX iPhone App

Am 19.12.17 um 22:46 schrieb DrakMrak

**Comment by 2Abendsegler** [comment]
Moin,
is just merged and I am working on the settings.

**Comment by GFEMajor** [comment]
Sorry, I send the last message via Email and the other conversations had not been loaded. So it was a bit delayed 😉.

**Comment by GFEMajor** [comment]
Btw: I like the Idea of the Links and the implementation looks great 😃

**Comment by DrakMrak** [comment]
Thanks... ;)

**Comment by 2Abendsegler** [comment]
The settings are done too.

[Here](https://github.com/2Abendsegler/GClh/commit/3388f8ec8a4de30fac63f53d8f3c861dd59c31f7) you can see what lines are changed. Of course I have not all your lines changed, this is GitHub. I have only changed your lines with .innerHTML. And I have added a line for green icons by hovering and some lines for the settings. The xxxx marked line are not relevant. 

You can install it from branch collector [here](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js). You have to set the "no update" flag in Tampermonkey if you rest by this version. In other cases you get all our changes to branch collector as update. :) 
You come back to the original [here](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).

**Comment by 2Abendsegler** [comment]
... you have to set a parameter in Config to open the link in a new tab, section Public Profile / Dashboard.

**Comment by 2Abendsegler** [comment]
... me again. :D  
You can change the update flag in Tampermonkey for every script. If you are in the script take the tab settings or something like that. There you can find the update flag.

**Comment by DrakMrak** [comment]
Thanks for info about GitHub :)  I Slowly exercisers interact with it... In my work I use SVN system and Git is a little bit different. But I managed it well I hope :) and I see all the changes in my fork...

**Comment by DrakMrak** [comment]
:) I add small css improovment into new dashboard.
Slightly narrower some elements ...

**Comment by 2Abendsegler** [comment]
I close the issue because the changes are done bei pull request #524.
