### ISSUE TITLE
images on the new dasboard open too small

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#530]
If I click an image attached to a log on the new dashboard it opens up in the Groundspeak default size. Is it possible to display it as large as on the cache page?

![image](https://user-images.githubusercontent.com/9153595/34299142-a8cf72fa-e721-11e7-8904-ba42118fbe7a.png)

**Comment by 2Abendsegler** [comment]
Hi, I have no example in my dashboard. Is it possible that I log a write note with an image in one of your caches, perhaps Poznej sve Kostelany https://coord.info/GC28A9D? I will delete it later.

**Comment by PontiacCZ** [comment]
Sure, go ahead.

**Comment by 2Abendsegler** [comment]
I do not know at the moment how we could do that. And I have no further idea in the moment. The note is deleted.

If GFEMajor has a little bit time, maybe he can look at this. But only in the new year.

**Comment by GFEMajor** [comment]
I'll look into this on the weekend

**Comment by GFEMajor** [comment]
this picture on the dashboard is not the original one. if you look at the url/filename (my testimage):
original:
`https://img.geocaching.com/cache/log/aa2940b6-a69d-4a7a-8d2a-6f0bcf169e13.jpg`
file on dashboard:
`https://s3.amazonaws.com/gs-geo-images/aa2940b6-a69d-4a7a-8d2a-6f0bcf169e13_l.jpg`
you see there is an "_l" on the filename (for large image 😉).

On the amazon server, there are both versions of this picture. If we just change the filename of the image to 
`https://s3.amazonaws.com/gs-geo-images/aa2940b6-a69d-4a7a-8d2a-6f0bcf169e13.jpg` (without the "_l" at the End) it may be possible to show the large picture.

@2Abendsegler should we build this in or should we make it with an option (of cause only if I can make it work 😃 in the first place)

**Comment by 2Abendsegler** [comment]
We have a parameter in the cache listing. You can expand the description and place the parameter once again in section dashboard. 
- settings_link_big_listing - Replace image links in cache listing to bigger image

Or you make a new one.
Your decision :)

**Comment by GFEMajor** [comment]
hmmm.....i can't find the javascript that opens the modal with the image....this image is reloaded from amazon, but I can't find the function the does this 😔. @2Abendsegler can you help me?

**Comment by 2Abendsegler** [comment]
I did not find anything either, and you should slowly know that I have no idea ..., hahaha.

**Comment by 2Abendsegler** [comment]
@GFEMajor 
Ich hab folgendes Script gefunden. Damit wird das große Bild aufgebaut. url ist in meinem Fall

**Comment by 2Abendsegler** [comment]
@GFEMajor
Ich hab folgendes Script gefunden. Damit wird das große Bild aufgebaut. url ist in meinem Fall ein img.geocaching url mit /large/. Wenn wir das /large entfernen können dann ist das der gewünschte Effekt. Ich weiß aber nicht wie das hier funktioniert.

```
<script type="text/x-handlebars-template" id="ActivityCarouselItemTpl">
    <div class="inner-slide">
        <div class="img-wrapper">
            <img src="{{url}}"/>
        </div>
    </div>
</script>
```

Ich war böse und hab ganz viel mit "Der verlorene Schatz der Mary Hyde - Aufgabe 1" rumgespielt. :D Im Moment steht noch ein Log dort, eben das mit einem Bild. Das müßtest du ja auch auf deinem dashboard bekommen wegen friends.

Wenn du Zeit hast dann schau bitte nochmal rein, ob du damit etwas anfangen kannst, danke.

**Comment by GFEMajor** [comment]
Jup, ich schau im laufe der Woche mal rein...

**Comment by GFEMajor** [comment]
Ich find leider nichts. Das Bild wird wohl irgendwo Serverseitig verkleinert.

**Comment by GFEMajor** [comment]
@PontiacCZ Sorry, but I can't find anything. The picture is rendered on the server side, but I can't find a place to hook in...

**Comment by 2Abendsegler** [comment]
Kannst du nichts mit dem Script anfangen das ich rausgesucht hatte?
Dort wird die url gesetzt. Ich kann die url ersetzen und dann kommt etwas anderes. Das Problem ist hier, dass man den Platzhalter hier an dieser Stelle noch anpassen müßte.

**Comment by GFEMajor** [comment]
Das ist doch gar kein Script oder? Ist das nicht nur ein Platzhalter? Bei mir ist das Bild am Ende nicht in diesem Snippet, sondern an einer anderen Stelle.

**Comment by 2Abendsegler** [comment]
Du weißt doch bescheid mit der Ahnung die ich hab :)
Aber tausche mal {{url}} durch https://raw.githubusercontent.com/2Abendsegler/GClh/master/images/nicolaus_head_08.png, dann siehst du den Effekt. 
Ich würde also jetzt hingehen und {{url}} durch {{url}}.replace('/large/','/') ersetzen, aber das funktioniert nicht. Aber du verstehst was ich wollte. :)

**Comment by GFEMajor** [comment]
Leider ist das nicht so einfach wie du dir das vorstellst 😃. GS nutzt irgend eine Bibo, die aus diesem Snippet den Modal generiert. 
`s = e.compile("<a href='{{url}}' target='_blank'>{{text}}<\/a>");`
Wenn du nun das {{url}} einfach ersetzt und du hast mehr als ein Bild auf der Seite, dann sollte immer das gleiche Bild kommen. Das ding ist wie gesagt nur das "Template" wie der Modale Dialog aussehen soll. Und wenn das zum Ersetzen nicht mehr da ist ({{url}}), dann nimmt er einfach das vom Template.

Man müsste also irgendwie die Funktion `e.compile` ersetzen und hier schauen, dass nicht das kleine sondern das Originalbild genutzt wird.
ich schau mal ob ich die noch irgendwo finde, aber ich würde fast vermuten, dass das über einen JSON Request gemacht wird, wie so vieles auf der neuen Seite.

**Comment by 2Abendsegler** [comment]
Ok, danke, war nur ne Idee. Vielleicht ist auch mal gut. 
Du hast genug Arbeit reingesteckt, ich wäre ja schon gar nicht so weit gekommen. Ich hätte vielleicht noch versucht die Erzeugung durch GS zu unterbinden und das Bild selbst zu erzeugen. Der Link ist ja bereits nach dem Klick aufs Icon bekannt, nur das /large müßte aus dem Link entfernt werden. Das mit /large ist nämlich das runtergeregelte mit so etwa 640 pixel, das ohne ist das Original. 
Laß mal gut sein. Wir können das Issue ja vielleicht noch offen lassen, vielleicht hat später jemand noch ne gute Idee. Gut Ding braucht halt manchmal Weile. :)

@PontiacCZ 
Sorry for the german, it was here only faster and better to understand for me.

**Comment by PontiacCZ** [comment]
No problem. :) 

I have pushed your conversation thru Google Translate but still I am not sure whether I got you right. If you believe someone might come with an idea in the future, leave it open, otherwise feel free to close it. 

Anyway, thank you SO MUCH, guys, for your work, GClh II is an incredible piece of work and I am delighted to use it every day.

**Comment by GFEMajor** [comment]
@PontiacCZ I had another look at this, and I think there is no way of editing this image. Geocaching is using some kind of Javascript (JS) Framework to generate the large image carousel which is a JS class of itself. It is really hard to follow this minified JS and from my opinion impossible to edit this file.
Sorry, but we should close this and put it on storage. Maybe we can do something in the future, if Groundspeak is changing it's way of generating this images/image-viewers.

**Comment by PontiacCZ** [comment]
OK, no problem. We'll see in the future. :) 
Thank you for your time, I very much appreciate it. Closing this issue now.

**Comment by 2Abendsegler** [comment]
After 8 years and with the new dashboard release from April 16, 2026, we might have a way to display the images larger. We still need to investigate this further. However, initial tests look promising.

**Comment by 2Abendsegler** [comment]
The feature comes with the next version.

---
Will be implemented with #3122.

---
With this option, the dialog containing the log images are displayed larger and the log images can be loaded in full resolution. Using this option also simplifies closing such a dialog by clicking outside the dialog.

To ensure that the images are fully visible on the screen, the max width and height should be adjusted to the screen size. For example, a max width of 640 pixel and a max height of 450 pixel might be a good choice for a small laptop with a screen resolution of approximately 1280 x 620 pixel.

If the max width is greater than 640 pixel, images will be processed in full resolution. The loading of such images results in higher data transfer and can incur high costs if your internet plan is based on data volume. Therefore, this option is not recommended for such plans. The loading of such images takes also longer, so it may take some time for the image to appear on the screen. Therefore, this option is not recommended for slow internet connections.

```
settings_view_larger_log_images_db
settings_view_larger_log_images_max_width_db
settings_view_larger_log_images_max_height_db
```
<img width="551" height="26" alt="Image" src="https://github.com/user-attachments/assets/70e27389-6b51-4def-b729-cebffb2faf6b" />
(Screen06.jpg)
