### ISSUE TITLE
#Owner# placeholder does not work with new layout

### ISSUE THREAD

**Issue by Cappa-d** [2Abendsegler/GClh#533]
Hi!

Just realized that there was a change in the placeholders for templates. I changed my templates and I am using #Owner# and it works just fine in the old layout. However with the new layout this placeholder remains while loging a cache and is not replaced by the Owner name.

Is it just me or really a bug?

Merry Christmas to all :)

**Comment by 2Abendsegler** [comment]
Moin,
es liegt nicht an dir und es ist auch kein Bug. Im neuen Formular steht gegebenenfalls nicht der Owner sondern das Pseudonym aus dem Cache Listing. Deshalb wollten wir das nicht als Owner verwenden.
Schau mal bitte im geoclub beim Thread zum GClh Version 0.9, dort ist beschrieben was wir wie umstellen werden zur nächsten Version. Vermutlich hat sich damit das Ticket auch erledigt.
Frohe Weihnachten

**Comment by 2Abendsegler** [comment]
Das wird bereits im Isuue #526 behandelt und kommt zu v0.9.1.
Ich schließe dieses Issue weil quasi doppelt.
