### ISSUE TITLE
Vorschau des Logs beim Schreiben

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#545]
Im alten Design sah man eine Vorschau des Logs den man gerade schreibt. Das wäre auch in der neuen Ansicht, gerade wegen dem Markup cool, damit man gleich sieht wie der finale Log aussieht.

**Comment by 2Abendsegler** [comment]
http://geoclub.de/forum/viewtopic.php?f=117&t=80208&p=1278957#p1278944

**Comment by GFEMajor** [comment]
Es stößt also auf anklang 😃. Ich werd mich dran setzen. Soll es auch einen Konfig Value dafür geben, so dass man das ein-/ausschalten kann? Oder soll ich das Feld im Log einfach versteckbar machen (eventuell so wie die Tackables)?

**Comment by 2Abendsegler** [comment]
Im Log einfach versteckbar wäre irgendwie cooler. Config geht aber auch.

**Comment by GFEMajor** [comment]
Ich hätte es jetzt so gebaut:
![image](https://user-images.githubusercontent.com/2239440/34461637-8ea6fe60-ee2f-11e7-8b15-d070daa77c9e.png)

**Comment by 2Abendsegler** [comment]
Sieht gut aus.
Ich hätte es auf den ersten Blick mehr zusammengeschoben Logvorschau und Trackables Kasten. Eigentlich sind die aber alle so weit auseinander auch oben. Also ok.

**Comment by GFEMajor** [comment]
Das können wir ja später noch machen. Ich bau erstmal die Funktionalität 😉. Mal schauen ob das gut klappt mit dem Markup

**Comment by GFEMajor** [comment]
@2Abendsegler gibt es einen Grund warum unsere jQuery Lib noch auf Version 1.6.4 ist? Wollen wir die mal auf eine höhere Version heben? Ich wollte nämlich gerade eine Funktion nutzen, die erst in 1.7 eingeführt wurde 😃

**Comment by 2Abendsegler** [comment]
Kompatibilität. 
Niemand garantiert, dass in einer höheren Version alles noch völlig identisch funktioniert. Wenn wir hier etwas umstellen, dass müßte man eigentlich einen Kompletttest machen. Wie wichtig ist das?

**Comment by GFEMajor** [comment]
Nicht all zu wichtig 😃. Ich wollte nur mal nachfragen, da Version 1.6.4 vom September 2011 ist, also doch schon etwas veraltet.
Klar wird nicht alles auf anhieb gehen, aber ich denke irgendwann sollten wir mal ein Update einplanen. Es sind ja immerhin 6 Jahre Entwicklung weiter gegangen 😉.

**Comment by GFEMajor** [comment]
So, erste implementierung ist fertig. ich mach einen PR und dann kannst du es dir ja mal anschauen.
<img width="684" alt="log preview" src="https://user-images.githubusercontent.com/2239440/34467310-1df95fa4-eeee-11e7-9cb8-f9ff4b17042a.png">

**Comment by GFEMajor** [comment]
Ich habe vorher ein Rebase meines Folks gemacht. Schau mal bitte ob das jetzt mit dem Merge klappt, oder ob ich wirklich einen komplett neuen Folk erstellen muss.

**Comment by 2Abendsegler** [comment]
Rebase ist schon mal aussreichend.

**Comment by GFEMajor** [comment]
Also ich komm an den unformatierten Text.
Ja ich sehe was du meinst...so ein Mist, ich dacht ich kann mir das parsen sparen. Aber ich schau mal wie GS es bei der alten Logpage implementiert hat. Eventuell kann ich das klauen 😃

**Comment by GFEMajor** [comment]
@2Abendsegler Eine Frage...kann ich auf alle Javascript Libraries zugreifen, die GS eingebunden hat? Oder muss ich die irgendwie nochmal einbinden bzw. sichtbar machen im Script
Speziell geht es mir um die hier:
`<script src="../scripts/MarkdownDeepLib.min.js" type="text/javascript"></script>`

**Comment by 2Abendsegler** [comment]
Du weißt doch dass ich keine Ahnung habe ... :)

**Comment by GFEMajor** [comment]
😂😂😂

Ich will es eigentlich ungern über @require machen, da es dann die ganze Zeit mit geladen wird. Aber vielleicht pack ich das Script einfach mit in meine Verzweigung rein, mal schauen. Es sieht auf jeden Fall schon besser aus als vorher, aber fertig ist noch nix 😉 

Gesendet mit der GMX iPhone App

Am 03.01.18 um 18:20 schrieb 2Abendsegler

**Comment by GFEMajor** [comment]
So, das sollte schonmal besser aussehen. Ich habe die ganzen Sachen bei der alten Groundspeak Seite geklaut 😁.
Jetzt schau ich mal, ob ich das @require noch raus bekommen, damit das Zeug nur geladen wird, wenn es auch gebraucht wird.
![log-preview](https://user-images.githubusercontent.com/2239440/34644505-416a7d62-f338-11e7-8821-810a39700194.png)

**Comment by GFEMajor** [comment]
So, eine neue Version ist im PR. Kannst du sie dir mal anschauen @2Abendsegler? Ich habe das @require leider nicht weg bekommen. Wenn ich versuche die Scripte so einzubinden:
`var scriptElement = document.createElement( "script" );
    scriptElement.type = "text/javascript";
    scriptElement.src = "/scripts/MarkdownDeepLib.min.js";
    document.body.appendChild( scriptElement );`
Dann bekomme ich den Fehler, dass "jQuery" nicht geladen ist, so als ob die jQuery Lib noch nicht fertig geladen ist, bzw. das Script nicht drauf zugreifen kann.
Nachteil der jetzigen Lösung ist, dass sowohl der SmileyConverter als auch die Markdown Lib immer geladen werden, egal auf welcher Seite man ist.

**Comment by 2Abendsegler** [comment]
Super!

Ich bekomm das auch nicht ohne require hin. Dann halt mit.

**Comment by GFEMajor** [comment]
Was ich noch machen könnte wäre die Smiley convert funktion direkt in den Quelltext einbinden, aber dann haben wir das Problem, wenn mal welche hinzu kommen, dann müssen wir die manuell nach pflegen. So wären sie immer mit dabei, solange GS die Datei nicht löscht (darum auch das Backup im neuen Backupordner 😉)

**Comment by 2Abendsegler** [comment]
Vielleicht fällt irgendjemandem später noch was ein. Ich würde es so lassen.
Backupordner hatte ich schon gesehen, du denkst halt mit. :)

Ich hab noch zwei Kleinigkeiten geändert, hatte ich vergessen. Ist noch nicht im Collector. Logvorschau in Englisch und bei leerem Log die Info dass man was eingeben soll entfernt. Die kam bei mir sowieso nicht.

**Comment by GFEMajor** [comment]
Die Info, dass man was eingeben soll ist noch aus der ersten Version drin. Leider ist die Doku der von GS verwendeten Bibo recht dürftig. Eventuell gibt es da auch so einen Placeholder Text, aber ich habs nicht gefunden. Is ja an sich auch nicht sooo wichtig.

**Comment by 2Abendsegler** [comment]
Ich finds ohne sowieso besser. :)
