### ISSUE TITLE
New Config capitel structure

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#547]

**Comment by 2Abendsegler** [comment]
@GFEMajor 
Vielleicht kannst du dir irgendwann mal die neue Kapitel Struktur des GClh Config anschauen. Hab den Bereich "Profile / Dashboard", wo ja alles mögliche drinstand, auseinanderdividiert und neue Kapitel gemacht. Falls du Änderungsvorschläge hast, laß hören. :)

**Comment by GFEMajor** [comment]
Ich habe es mir angeschaut. Es sieht alles schlüssig aus. Mir sind nur ein paar kleinere Sachen aufgefallen, vor allem Inputfelder sind manchmal zu klein (siehe Screenshot). Eventuell kann man die noch etwas vergrößern.
<img width="570" alt="gc_gallery" src="https://user-images.githubusercontent.com/2239440/34461474-63004234-ee2b-11e7-8758-24ce0d9b83bc.png">
<img width="598" alt="gc_home" src="https://user-images.githubusercontent.com/2239440/34461475-631fed82-ee2b-11e7-8e39-3285c586b11a.png">

**Comment by 2Abendsegler** [comment]
Ok, ich geh nochmal drüber mit Chrome, das passiert immer nur dort. :)

**Comment by 2Abendsegler** [comment]
@GFEMajor 
Als ich in Chrome nachgesehen habe, fiel mir ein, dass ich das schon gemacht hatte. Dein Phänomen scheint also nicht alleine an Chrome zu liegen sondern vielleicht auch am Mac. Ich habe die drei benannten Felder und das Color Feld und die Ähnlichen Felder etwas auf gut Glück vergrößert. Bitte schau mal nach ob es nun in Ordnung ist.

**Comment by 2Abendsegler** [comment]
@GFEMajor 
Sorry ich muß das zuerst noch rüberschieben.

**Comment by 2Abendsegler** [comment]
@GFEMajor
Steht jetzt aufm Collector.

**Comment by GFEMajor** [comment]
Also die Sachen die du geändert hast sehen jetzt gut aus. Ich hab nochmal einen kompletten Screenshot gemacht. Es sind leider noch ein paar Felder die noch fehlen 😃. Ich hoffe ich habe nichts übersehen.
![screencapture-geocaching-account-dashboard-1514966798123](https://user-images.githubusercontent.com/2239440/34512966-f21b709c-f065-11e7-8656-6beea8105f35.png)

**Comment by 2Abendsegler** [comment]
@GFEMajor 
Hab zwei Felder verlängert. Die Color Felder nicht, das sieht langsam ziemlich doof aus.
Bitte ruf mal den Config auf, save und ruf ihn erneut auf. Schau mal ob der # immer noch in Felder steht.

**Comment by GFEMajor** [comment]
Ich brauchte nicht mal neu speichern. Die # waren schon beim ersten Aufruf der Config weg. Speichern klappt auch.
Ich denke das ist damit erledigt.

**Comment by 2Abendsegler** [comment]
Ok super, dann mach ich das Teil zu.
