### ISSUE TITLE
Bug at autovisit of trackables by logging with the new GUI

### ISSUE THREAD

**Issue by sunnygeocaching** [2Abendsegler/GClh#549]
I logged my uploaded fieldnotes and used the new GUI for logging.
I used autovisit for my trackables, everything was correctly show at the logging page, but after storing my logs no trackable had a new log for the visited cache.

Using Windows 7 and Google Chrome Version 63.0.3239.84

**Comment by 2Abendsegler** [comment]
Hi,
I need some more information.
1. Please let me know your geocaching name.
2. Please let me know a link to one log or a link to one cache which went wrong.
3. Do you perhaps know, if you booked with the F2 key or if you booked with the mouse to the Post button? This is especially important for us.
4. Have you perhaps seen, that the icons are marked with Visit and Autovisit like this here
![autovisit](https://user-images.githubusercontent.com/22332216/34488941-b33f1f94-efda-11e7-9de8-b6ce333fbba6.JPG)

Cheers

**Comment by sunnygeocaching** [comment]
1. Please let me know your geocaching name. -> Sunnysky.ger
   2. Please let me know a link to one log or a link to one cache which
   went wrong. -> all caches i logged at 31.12. and 01.01.
   3. Do you perhaps know, if you booked with the F2 key or if you booked
   with the mouse to the Post button? This is especially important for us. ->
   post Button
   4. Have you perhaps seen, that the icons are marked with Visit and
   Autovisit like this here

i checked it just again:

logging with looking4cache app as Fieldnotes:


[image: Inline-Bild 1]


Logging the cache


[image: Inline-Bild 2]



using post button


No visited trackables are shown in the list of trackable logs


[image: Inline-Bild 3]



[image: Inline-Bild 4]



I hope i coud help you with this bug.

Please let me know when you have finished analysing the bug, so i can
delete todays test log again

Greetings

Sunnysky alias Angi




2018-01-02 16:39 GMT+01:00 2Abendsegler <notifications@github.com>:

**Comment by GFEMajor** [comment]
Hi @sunnygeocaching can you please come to the github page (https://github.com/2Abendsegler/GClh/issues/549#issuecomment-354986118) and reupload your pictures? We can't see them.
Thanks

**Comment by sunnygeocaching** [comment]
sorry for that, i just used snagit tool, i' ll upload all pictures at once

2018-01-03 13:06 GMT+01:00 GFEMajor <notifications@github.com>:

**Comment by 2Abendsegler** [comment]
@sunnygeocaching
Du kannst deine Testlogs wieder löschen.
Noch eine Frage. Kommt der Inhalt deines Logtextes komplett aus dem Draft oder hast du im Logtext nochmal etwas eingegeben oder geändert?

@GFEMajor 
Für mich sieht das so aus, als würde GS die Änderung des Visit Buttons nicht bemerken. Ein ähnliches Phänomen haben wir bei Post F2, dort wird manchmal lediglich der Draft Text gebucht. Änderungen am Drafttext verschwinden. Ich hab F2 bereits im Collector entfernt, weil ich hier zu keiner Lösung gekommen bin, manchmal ging es und manchmal nicht.
Kannst du bitte mal schauen, ob du hier etwas findest, ansonsten fliegt diese Funktionalität nämlich auch wieder raus.

**Comment by sunnygeocaching** [comment]
@2Abendsegler 
Im Testlog war der Text komplett im Draft, gestern habe ich beim Loggen den Text  angepasst und auch mal mit Copy&Paste eingefügt. Kein einziger Log hatte einen Visit.

**Comment by sunnygeocaching** [comment]
..... und noch nen Bug bei Groundpeak gefunden 😂😂😂. Der found Zähler auf der Übersichtsseite wird nicht zurückgesetzt

**Comment by 2Abendsegler** [comment]
Was meinst du damit? Hast du einen Screenshot?

**Comment by sunnygeocaching** [comment]
Der hatte in der alten Übersichtsseite die Fundzahl auf 7798 korrigiert und auf der neuen stand sie noch auf 7799. Jetzt nach 15 Minuten ist sie auch in der neuen Übersicht korrigiert. 
Hat scheinbar nur etwas länger gedauert

**Comment by 2Abendsegler** [comment]
Ok, danke, verstehe.

Ist also kein neuer Bug bei uns. :)

**Comment by GFEMajor** [comment]
Ich schau mir das ganze mal an wenn ich Zeit finde am Wochenende. Ich hab selbst L4C und kann das Szenario also nachstellen mit der Fieldnote, ich muss nur mal einen Freund fragen, ob ich seinen Cache als Testobjekt benutzen kann, da man seine eigenen Caches ja nicht loggen kann 😃

**Comment by sunnygeocaching** [comment]
@GFEMajor 
Du kannst auch meinen nehmen

**Comment by GFEMajor** [comment]
Ok dann nehm ich den. Mein Cacher Name ist Ruko2010, nur damit du Bescheid weist 😉

**Comment by GFEMajor** [comment]
Also es liegt schonmal nicht an den Fieldnotes. Ich habe gerade einen "normalen" Log gemacht und alle meine Bugs standen auf Auto Visit. Keiner der Bugs wurde geloggt.
@2Abendsegler kannst du mir mal die Codezeile sagen, wo die Bugs auf Auto Visit gesetzt werden, dann schau ich mal ob ich was finde.

**Comment by 2Abendsegler** [comment]
Autovisit heißt nur dass die TBs auf Visit gesetzt werden wenn es ein Found log oder ähnliches ist. Ansonsten wird sowieso nichts gemacht. Wichtig ist also dass der TB automatisch auf Visit gesetzt wurde. Das ist in den Beispielen von sunnygeocaching auch der Fall gewesen. Und trotzdem wurde der Visit nicht geloggt.

function setAuto macht das.
...
`                    if (autos[1].checked == true) {`
`                        if (type == 2 || type == 10 || type == 11) actions[1].checked = "true";`
`                        else actions[0].checked = "true";`
`                    } else {`
`                        if (allTbs != true && (type == 2 || type == 10 || type == 11)) actions[0].checked = "true";`
`                    }`

Aber wie gesagt, das scheint nicht das Problem, weil die Visits ja richtig gesetzt wurden, GS merkt es aber nicht.

**Comment by GFEMajor** [comment]
ok, danke. Ich schau mal ob eventuell noch irgendein Event ausgelöst werden muss wenn der Log für den TB ausgelöst werden soll.

**Comment by 2Abendsegler** [comment]
Ich schau mir das gerade nochmal an.

**Comment by 2Abendsegler** [comment]
@sunnygeocaching 
Ich sehe im Moment keine Möglichkeit wie wir per Script den GS Routinen mitteilen können, dass die Buttons gesetzt sind. Sofern GFEMajor auch durch ist, werden wir das Issue schließen und die Funktionalität mit der nächsten Version auf der neuen Logseite nicht mehr anbieten. 
Die Autovisit Funktionalität ist weiterhin über die alte Logseite nutzbar.
Sorry.

@GFEMajor  
Ich kann keinen Weg finden. Hab den Programmteil rausgeschmissen und den Parameter in den Bereich old log page only verschoben. Wenn du auch durch bist, dann schließ das Issue bitte. Schau dir bitte mal noch die Labels an, ob das so Sinn macht. Was besseres fällt mir nicht ein.

**Comment by GFEMajor** [comment]
Ich hab es noch nicht geschafft mir das weiter anzuschauen. Ich versuche es diese Woche / Wochenende nochmal. Solange bitte noch offen lassen.

**Comment by 2Abendsegler** [comment]
Hey, kein Problem. Es soll noch Menschen geben die verbringen ihre Zeit mit arbeiten. :) 
Pass auf, im Collector ist die Funktionalität schon weg.

**Comment by GFEMajor** [comment]
Danke für den Hinweis...dann erzeuge ich mir einfach eine Branch bevor ich deinen Collector merge...

**Comment by GFEMajor** [comment]
@2Abendsegler Ich hab mir die Sache nochmal angeschaut. Also es werden wirklich ein paar Events getriggert wenn man den Button drückt. Darum hab ich mir gedacht, warum nicht einfach auch den "Button drücken" wenn man den Status des Auto Visit ändert. Das funktioniert auch halbwegs, aber leider noch nicht perfekt.
Ich habe deinen Code
`actions[0].checked = "true";`
geändert in
`$('input[name=actions-'+tbN+']').eq(0).trigger("click");`. Wenn man das an den drei Stellen ändert, wo du "nur" den Input änderst, dann klappt es, wenn der TB auf Autovisit stand, dann wird er geloggt.

Problem aktuell: Wenn man einen Bug neu auf "AutoVisit" stellt, dann wird er beim ersten mal nicht geloggt, sondern erst beim zweiten mal. Warum hab ich nicht herausfinden können.

@sunnygeocaching Sorry für die sehr vielen Testlogs 😃

**Comment by GFEMajor** [comment]
Was ich auch nicht ganz verstehe, warum wird die Funktion `setAuto` 2 mal aufgerufen wenn man den Auto Visit Button drückt??

**Comment by 2Abendsegler** [comment]
Moin,

wenn ich mich richtig erinnere hab ichs hinbekommen, dass nach einem click auf den Autovisit Button eine korrekte Verbuchung stattfand. Ich hatte mit dem change Event auf den li Tags rumgespielt. Also bei einem Click in den Bereich eines TBs funktionierte es.
Das problematische ist jedoch das Setzen des Log Typs und daraufhin das automatische Setzen der Visits weil Autovisit on. Das funktionierte nicht.

Warum die fkt doppelt aufgerufen wird vermag ich jetzt nicht zu sagen. Vermutlich stört es aber zumindest nicht. Vermutlich ist es nur der Vereinfachung des codings geschuldet.

Ich war jetzt schon drei Mal dran und hab genauso oft das Handtuch geschmissen. Ich will im Moment nicht mehr drangehen. Wenn du meinst du bekämst es vielleicht hin, dann können wir es ja auch noch zurückstellen und für die nächste Version nochmal schauen. Vielleicht habe ich dann auch wieder Lust. 

Oder wir schmeißen es raus. Ich hab kein Problem damit, auch deshalb nicht weil es auf der alten Seite ja funktioniert.

Was meinst du?



Am 15. Januar 2018 22:41:51 MEZ, schrieb GFEMajor <notifications@github.com>:
@2Abendsegler Ich hab mir die Sache nochmal angeschaut. Also es werden
wirklich ein paar Events getriggert wenn man den Button drückt. Darum
hab ich mir gedacht, warum nicht einfach auch den "Button drücken" wenn
man den Status des Auto Visit ändert. Das funktioniert auch halbwegs,
aber leider noch nicht perfekt.
Ich habe deinen Code
`actions[0].checked = "true";`
geändert in
`$('input[name=actions-'+tbN+']').eq(0).trigger("click");`. Wenn man das
an den drei Stellen ändert, wo du "nur" den Input änderst, dann klappt
es, wenn der TB auf Autovisit stand, dann wird er geloggt.

Problem aktuell: Wenn man einen Bug neu auf "AutoVisit" stellt, dann
wird er beim ersten mal nicht geloggt, sondern erst beim zweiten mal.
Warum hab ich nicht herausfinden können.

@sunnygeocaching Sorry für die sehr vielen Testlogs 😃

**Comment by sunnygeocaching** [comment]
@2Abendsegler Ich habe nur einen Bug gemeldet und nicht die Erwartung dass er sofort gelöst wird, habe auch kein Problem wenn die Funktion in der neuen GUI rausfliegt. Lieber keine Funktion als eine verbuggte Funktion.
@GFEMajor habe kein Problem mit den Testlogs, dafür wird er viel zu selten geloggt, kannst ihn gerne weiter nutzen.

Danke an alle und Respekt wie schnell und intensiv ihr Euch kümmert. Sagt Bescheid, wenn ich etwas für Euch testen kann/soll.

**Comment by GFEMajor** [comment]
Also ich bin auch nicht weiter gekommen. Ich würde die Funktionalität raus schmeißen. Eventuell versucht sich jemand anders nochmal dran.
