### ISSUE TITLE
Großer Abmelden Button

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#552]
Ist das Absicht?
<img width="343" alt="abmelden" src="https://user-images.githubusercontent.com/2239440/34554414-14145804-f12d-11e7-93f1-4447d8ea2000.png">

**Comment by 2Abendsegler** [comment]
Bei mir ist er zumindest auf den begutachteten Seiten gleichgroß aber auch dunkel. Das ist schon ne ganze Weile so und scheint mit Änderungen am Header durch GS zusammenzuhängen. Hab mich darum nicht gekümmert. Eigentlich sollte dieses Menü auch die Farbe gar nicht annehmen, war aber irgendwann dann mal so.
Wenn du magst kannst du es ruhig ändern so wie du es bevorzugst.

**Comment by GFEMajor** [comment]
Ok, ich werd dieses Menü von den CSS Änderungen ausschließen.

**Comment by 2Abendsegler** [comment]
Bist du hier schon dran, oder kann ich das noch übernehmen?

**Comment by 2Abendsegler** [comment]
Ich hatte nichts zu tun und hab das komplette rechte Menü von den CSS Änderungen ausgeschlossen.
Ich hoffe ich bekomme jetzt keine Prügel.

**Comment by GFEMajor** [comment]
Alles gut. Ich kann erst heute Abend was machen, du hast also nichts doppelt gemacht 😉
