### ISSUE TITLE
Link von Google Karte zu Geocaching funktioniert in Chrome nicht

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#553]
@2Abendsegler kannst du das bestätigen? Wenn es nicht an mir liegt, würde ich mir das anschauen.

**Comment by 2Abendsegler** [comment]
Bei Firefox das Gleiche.
Das ist mein Fehler.
Ich korrigiere das fix.

**Comment by GFEMajor** [comment]
Im Firefox ging es bei mir. Aber das kann daran liegen, dass im Firefox bei mir die Stable Version aus dem Master läuft und in Chrome die aktuelle Development Version

**Comment by 2Abendsegler** [comment]
Das kommt davon wenn man globale Änderungen macht. http://www.geocaching.com entfernt.
Ich habe alles durchgecheckt, wo ähnliches gemacht wird. Funtioniert alles, hab sogar noch weiter gekürzt.

Nun gut, böser Frank :)

**Comment by GFEMajor** [comment]
War auch nur Zufall, dass ich es bemerkt habe. Ich nutze den link wirklich NIE 😃. Aber heute hab ich  ihn dann doch mal geklickt 😉.
Aber gut, dass es noch vor dem Release aufgefallen ist...

**Comment by 2Abendsegler** [comment]
Ja genau, da ist mir mal ne Blamage erspart geblieben, gut gemacht, auch wenns nur zufällig war. :)
