### ISSUE TITLE
More cache information on map for cache popups.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#554]
http://www.geocaching.cz/topic/31295-gc-little-helper-ii/page-4#entry552274

---
When we are encouraged to submit ideas: Basic information appears on the map by clicking on the icon of a cache. Would any more information be added? For example - the latest 5 logs (same as at the beginning of the listing), the total number of finds,or % FP.

---
These are all good ideas, but I'm afraid we can not realize a lot of that. The script runs in a way like you work on the geocaching pages. If it needs some information of a cache, it have to read the complete cache listing. This means that the script has to read for example 200 cache listings because on the map are 200 caches. You know the time for one cache with a lot of logs if you go to such a cache listing. The time is too long. The other way to read the cache listing if the user click to the cache is also too long. Nobody want to wait 2 or 4 seconds in such an online application or perhaps 10 seconds for very big listings.   

The latest logs are certainly not possible, you would be faster if you press the link to the cache because you see somthing before the cache is completly loaded.
The total number of FPs and perhaps the percentage could be possible, because this information are also in pocket queries.

I will open an issue on our issue system and we will look what we can do. Perhaps I can found someone who wants to develop it, because I probably will not have enough time left.

I take with me:
- Latest logs (like in cache listing)
- Total founds of the cache
- Percentage FPs of the cache

All with own Config parameter.

Something else?
- Country

**Comment by GFEMajor** [comment]
Ich denke ein Nachladen jeglicher Informationen macht höchstens Sinn, wenn jemand auf das Popup geklickt hat. Das im Hintergrund vorher für alle Caches auf der Karte zu machen macht keinen Sinn.
Dann könnte man einen Loading Spinner einbauen (damit der User sieht, da kommt gleich noch was) und dann die Sachen asychron nachladen und danach anzeigen. Welche Infos hier Sinnvoll sind muss noch geklärt werden

**Comment by DrakMrak** [comment]
There could be a **country** there too: it is often a problem at the border where the cache lies... one click and I see where is and I must open cache.

**Comment by Ruko2010** [comment]
@2Abendsegler @DrakMrak this is my first implementation. Any thoughts on that?
The informations are loaded asynchronous when the popup is opened from the original cache page. A loading gif shows, that informations are being reloaded.

![image](https://user-images.githubusercontent.com/2239440/36811578-919aa720-1cce-11e8-9817-4e93dbebec09.png)

**Comment by 2Abendsegler** [comment]
That looks really good, great. :)

**Comment by DrakMrak** [comment]
Wau look nice

**Comment by Ruko2010** [comment]
Any more Ideas what we can place there?

![image](https://user-images.githubusercontent.com/2239440/36813242-34462f9e-1cd4-11e8-8340-7ecfb0e603a9.png)
![image](https://user-images.githubusercontent.com/2239440/36813261-4a316a26-1cd4-11e8-8289-3595c1c146d5.png)

**Comment by DrakMrak** [comment]
if it was possible... info about GC/TB in cache

**Comment by Ruko2010** [comment]
Fav-Points are already present in the original Popup ;). I will see what I can do about the TBs

**Comment by DrakMrak** [comment]
Fav points oh sorry...  I'm blind ;)

**Comment by Ruko2010** [comment]
> and last five logs

I'll look into this

**Comment by DrakMrak** [comment]
ok thanks :)

**Comment by 2Abendsegler** [comment]
Maybe not the last five logs but the set number of logs, or an own setting.
Maybe VIP and VUP icons.

And the solutions for the mysteries I have to look for myself. :) Somehow it's no fun to solve the mysteries themselves if they are traded in several places. :(

**Comment by Ruko2010** [comment]
This Popup is really annoying me. One click of the map on a cache icons mutates the DOM for the popup serveral times. Still trying to find a solution to let the code only run once.
Also if you look at caches that are tight together on the map and can go through them by hitting the next/prev button, the popup is not loaded again but killing everything I put in there...
Current Status:
![image](https://user-images.githubusercontent.com/2239440/36965027-ab766b2e-2058-11e8-8d62-040273aa2938.png)

![image](https://user-images.githubusercontent.com/2239440/36964812-1a89483e-2058-11e8-8438-76e0d9269f65.png)

Just for everyone watching this :). I'm still on it.

**Comment by Ruko2010** [comment]
I have overcome all the problems with the map popup. I changed the way I watch this popup, so my function is only called once.
Also, if there are two or more caches near each other (so you have the Prev/Next Button available) the information for all caches is loaded (asynchronous).
![image](https://user-images.githubusercontent.com/2239440/37246831-1bf91660-24b1-11e8-8508-67e4071fd838.png)
Now that are all this problems solved, I start with the last 5 (or other number) of logs. But this should be easy ( at least I hope) because the last 25 logs are on the inital page in a (JSON?) String

**Comment by Ruko2010** [comment]
Ok, so it was not that easy to parse that (fuc....) variable, but I made it. Just to let you see the current progress. I have to made some changes to the styling, but not yet, it's to late now 😃
![image](https://user-images.githubusercontent.com/2239440/37248211-0cf7eb9e-24cc-11e8-92c9-94acea187afc.png)

**Comment by 2Abendsegler** [comment]
Sounds good and looks good!

**Comment by DrakMrak** [comment]
Great work...
It look very good... I'm looking forward to trying it :)

**Comment by Ruko2010** [comment]
Ok, so this is the finished work (Please let it load, file is 10MB 😉). Hope you like it. If you think it is ok, I'll built in a config parameter to turn it off and one to configure the count of latest logs shown.
![kapture 2018-03-11 at 20 13 40](https://user-images.githubusercontent.com/2239440/37257389-c91b92de-2568-11e8-9918-bcba5cb6b6a2.gif)

**Comment by 2Abendsegler** [comment]
Das sieht echt super aus! Wenn das alles so funktioniert wie du es zeigst, klasse.
Ich hab nur ne Winzigkeit. Geht man mit der Maus über ein Latest Logs Icon, klappt das Log auf, aber nicht direkt unter dem Icon. Wenn du also die Maus weiter runter in Log bewegst, weißt du nicht mehr von welchem Icon das Log stammt. Im Listing fängt das Log deshalb unter dem jeweiligen Icon an.


Zu VIP VUP:
Ich sehe es im Moment wie folgt mit zwei Aufgaben.

Ab Zeile 3760
(is_page("cache_listing")    ||      // Cache Listing (nicht in den Logs) 
1. Hier muß die Map Seite erlaubt werden.

Ab Zeile 4336
// Public Profile:
Werden für das Public Profile die Daten beschafft und die VIP, VUP Icons aufgebaut durch Aufruf der Funktion gclh_build_vipvup. 
2. Das scheint am Besten geeignet als Vorlage für die aktuellen Interessen. Du mußt es wohl in eine Funktion packen.

Ab Zeile 3876 
// Build VIP, VUP Icons:
function gclh_build_vipvup
Hier werden die Icons aufgebaut.

**Comment by Ruko2010** [comment]
@2Abendsegler Thanks for the help. I'll look into this function.

**Comment by Ruko2010** [comment]
The VIP/VUP thing was easier than I thought 😃. I also moved the log box under the coresponding icon:
![image](https://user-images.githubusercontent.com/2239440/37272129-fd55ee88-25d5-11e8-97d5-f60d9378ce09.png)

**Comment by Ruko2010** [comment]
If no further changes should be made, I'll make the config parameter and test the feature in different browsers and consider it as finished

**Comment by DrakMrak** [comment]
I tested it in last version Firefox and EDGE and it seems to work well...
Thanks for great improvements to the map :)

**Comment by Ruko2010** [comment]
Thanks. I still need to add the config values, but this should be the easy task right now 😉

**Comment by Ruko2010** [comment]
The one thing I'm not happy about is, that the popup gets larger after the data is loaded, so everything slips to the top.
But I have no smart solution for this. of cause I could reserver the space (3 lines) that is reloaded, but I can not be sure, that there are "only 3 lines" reloaded. So in some cases (when the user wants many latest logs displayed, or there are many different logtypes, there could be 4 lines. If some of you has a smart solution, just let me know it 😉.

**Comment by Ruko2010** [comment]
Ok, as I was writing I thought that the reserving space idea would be a good aproch. I think in 95% of all cases there will be only 3 Lines of space used for the additional data, so this is a good solution to reserve this space.
In the other 5% the popup will slide up. Looks now like this:
![kapture 2018-03-14 at 8 27 16](https://user-images.githubusercontent.com/2239440/37388717-dc6e75f4-2761-11e8-9505-bae400a233fd.gif)

**Comment by DrakMrak** [comment]
In Czech I have always 4 rows - long names for district and long name for country :) and Trackable is on the fourth line always...

'Kraj Vysocina, Czech Republic' - long

I thinking... that it could help convert some text to images (for shortening)
Text: Trackables: to symbol for TB
Text: Favorites percent: to symbol heart and '%'

take it as a suggestion for solution ;)

**Comment by Ruko2010** [comment]
Good Idea, I'll do this. I also have a lot more to style :):
![image](https://user-images.githubusercontent.com/2239440/37389409-88484e0c-2764-11e8-9271-84e13e79010a.png)

**Comment by Ruko2010** [comment]
I think it looks good 😃(ignore the lates logs, I have to fix this)
![image](https://user-images.githubusercontent.com/2239440/37390199-6d95af52-2767-11e8-8424-e1cdd6fd1648.png)

**Comment by DrakMrak** [comment]
great :)

**Comment by Ruko2010** [comment]
i think I'm ready now. Made the config values and enhanced the styles. I'll transport it into the collector. It will be available in the next version.
![image](https://user-images.githubusercontent.com/2239440/37467310-296bb304-2860-11e8-93b2-0a3ad58f6f54.png)
![image](https://user-images.githubusercontent.com/2239440/37467329-347ad8b0-2860-11e8-9bb5-55427a53d48b.png)
