### ISSUE TITLE
Go live

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#564]
Ich habe aus meinen Unterlagen alle wichtigen Punkte zusammengestellt um eine neue Version auszuliefern.

A. Go live Dokument:
https://github.com/2Abendsegler/GClh/blob/collector/docu/go_live.md

Wenn du etwas Zeit hast, könntest du sie dir mal ansehen und versuchen die einzelnen Punkte durchzuspielen. Es ist schon fast alles gemacht, aber darum geht es ja nicht. Wichtig ist, dass du die Punkte verstehst und umsetzen kannst. Das Dokument ist ein Arbeitsdokument. Schreib deine Ergänzungen rein. Das Dokument dient in erster Linie dir.

Wenn etwas unklar ist oder du Fragen hast, dann können wir das hier machen.

**Comment by 2Abendsegler** [comment]
Die Counter kannst du alle ruhig zurücksetzen, das macht nichts. Wenn wir live gehen, machen wir das nochmal.

**Comment by GFEMajor** [comment]
Ok, ich schau es durch. Eventuell drehen wir dann für die 0.9.2 den Spieß rum und ich mache alles und du schaust drüber. Dann haben wir gleich einen Test ob ich auch alles verstanden habe. Wird aber sicher erst Ende der Woche wenn das OK ist.

**Comment by 2Abendsegler** [comment]
Ok, vielleicht ist die nächste Version auch etwas kleiner und übersichtlicher. Hier hatte sich jetzt doch wieder viel angesammelt. 
Kein Stress. Es ist nun soweit alles fertig. Mir ist es gleich wann wirs an die User geben. Auch nächste Woche ist ok.

**Comment by GFEMajor** [comment]
ok. Spätestens Montag Abend hab ich viel Zeit, da sind Frau und Kind aus dem Haus 😉

**Comment by 2Abendsegler** [comment]
Noch ein paar weiter Punkte bezüglich des go_live Dokuments und wie man sich das Leben nicht unnütz schwer macht. Und eine Durchnummerierung aller wichtigen Punkte.

2. Das go live Dokument soll ja nur die weitere Funktionsfähigkeit einer neuen Version sicherstellen. Dafür ist es aber beispielsweise nicht notwendig in den ganzen Foren präsent zu sein und eine Counterauswertung ist auch nicht notwendig. 
Wenn du nun für die nahe Zukunft das Project am Leben erhalten möchtest, dann kannst du natürlich noch ganz andere Dinge etablieren und du kannst auch das was für die Funktionsfähigkeit nicht notwendig ist einfach weglassen. Das bleibt dir völlig freigestellt. Insbesondere ist eine Präsenz in den Foren nicht notwendig, den Update bekommt man ja auch so. 

3. Ich würde es schön finden, wenn du dann auch über die Entwicklungen von Dritten drüberschaust und gegebenenfalls auch korrigierend eingreifst und vielleicht auch zumindest vor einer Auslieferung die Dinge von Dritten mittestest. 
Wenn du etwas garnicht oder nicht so wie an dich herangetragen mergen möchtest, dann ist das dein gutes Recht. Wenn jemand etwas implementiert haben möchte, ist es deine Entscheidung ob du es umsetzen möchtest oder nicht. Da kann dann auch ruhig jemand rumlamentieren. Es ist deine Entscheidung. Du bist der Herr und Meister. :)
Das gilt auch gegebenenfalls für andere Collaboratoren. Es gibt dich und CachingFoX, den ich ebenfalls bestehen lasse.

4. Du kannst dich gerne auch im Kopf des Scriptes oder auch sonstwo verewigen, so wie ich das ja auch gemacht habe. 
@name und @namespace dürfen vermutlich nicht verändert werden, weil sie einen benannten Datenbereich darstellen in dem sichergestellt ist, dass der GClh nur einmal installiert werden kann. Bei Änderungen würde beim Update ein weiterer GClh installiert werden, was dann nicht mehr funktioniert. Das war zumindest in Greasemonkey stand der Technik, vermutlich auch in Tampermonkey. Es besteht ja aber auch kein Grund dort etwas zu ändern, das sind nur Namen. 

5. Damit Änderungen den Entwicklern zugerechnet werden, muß der Merge des Pull Requests direkt in die Hauptbranch, den Collector erfolgen. Eine Zwischenstufe, wie ich das ursprünglich vorgesehen hatte, funktioniert nicht. Nachbesserungen können direkt im Pull Request erfolgen, oder wie ich es bevorzuge, nach dem Merge über eine ganz normale Anpassung.
Ich bin bei Nachbesserungen nach meine Vorlieben vorgegangen, wie du auch bemerkt hast. Das kannst du ebenfalls tun, wenn das jemand nicht möchte ... Da kann dann auch ruhig jemand rumlamentieren ...

6. Insbesondere die Themen
° VIP Icons und Listen,
° Mail und Message Icons und Unterstützung und
° Log-Template und Overwrite Log-Template
sollte man wenn möglich meiden, weil die Themen wirklich schwer zu überblicken sind und schon etwas anfällig sind bezüglich ungeahnter Folgen. :)

7. Die Position der Programmteile sollte wenn möglich nicht mehr verändert werden, weil hier teils Abhängigkeiten bestehen, die auf den ersten Blick manchmal nicht zu erkennen sind. Obwohl ich alles überarbeitet habe und ich quasi alles kenne sind mir auch zwei Positionsänderungen zu v0.9 ins Kreuz gefallen. 

8. Wenn du weiter auch etwas für die User tun möchtest, dann schadet es nicht zumindest im geoclub gelegentlich reinzuschauen. 
Ich hatte meine Forenpräsenz davon abhängig gemacht, wieviele User aus den entsprechenden Ländern kommen. Entsprechend bin ich in Deutschland und Schweiz/Österreich vertreten. In Österreich gabs nichts Richtiges, es sind aber viele scheinbar im geoclub oder im Schweizer Forum. 
Im Forum der Tschechischen Republik ([Thread zum GClh](http://www.geocaching.cz/topic/31295-gc-little-helper-ii/page-4#entry552360)) hatte ich auch mal korrigierend eingegriffen. Das ist aber schwierig, weil alles nur auf Tschechisch ist. Hier habe ich aber keine Updatemeldungen eingestellt.
Hier mal die aktuelle Länderverteilung für v0.9 als Anhaltpunkt: 
http://s04.flagcounter.com/countries/mHeY/

**Comment by GFEMajor** [comment]
Ich beziehe mich mal auf die Punkte um GoLive Dokument:

1. Da brauch ich noch eine kleine Erklärung. Wir setzten ja immer als Milestone die nächste Version (jetzt gerade 0.9.1). Meinst du damit einfach, dass alle Issues geschlossen sind, oder muss ich mit dem Milestone in Git noch etwas machen?
2. Klar
3. Klar soweit. Kleine Frage noch zu den Bilder. Du machst einfach Screenshots, lädst sie dann in den Image ordner und verlinkst sie dann in dem Dokument, richtig?
4. Das sollte doch schon raus bevor es in den Collector geht 😉
5. 
Weist du was für eine Funktion diese $$XXX Sachen haben? Ist das etwas spezielles von Tampermonkey? Oder sind das nur Kommentare "von uns" damit wir wissen, wo wir etwas ändern müssen vor einer neuen Version?

$$000: klar
$$001: Kannst du mir das nochmal genauer erklären? Ich verstehe schon, dass das für die Hervorhebung der neuen Funktionen ist, aber was genau muss ich ändern, wenn es eine neue Version gibt? Was genau meinst du mit "nach unten reichen und letzte nach oben?"
$$002: machst du das bei jeder Version (0.9.0 => 0.9.1), oder nur bei den "großen" (0.8 => 0.9)? Für den Reset brauch ich noch die Zugangsdaten, am besten die schickst du mir noch per Email
"Zählt Installation je Adresse nur einmal innerhalb von 8 Stunden:" => what 😃? warum soll man die abwechselnd verwenden? Das hab ich noch nicht verstanden.
$$003: Kann ja an sich auch drin bleiben, denn es kommt ja nur bei den Usern die noch kein FF+TM nutzen. Also sollte es die "normalen" User auch nicht betreffen. Und so wissen die Leute wenigstens warum das Script eventuell nicht mehr funktioniert.
$$004: klar
$$005: Warum werden Parameter da raus genommen? Kannst du das näher erläutern?

6. Wie geht das 😃?
7. klar
8. Ich werde mich anmelden und die Sachen posten. Dann wissen die Leute, dass es etwas neues gibt.

**Comment by 2Abendsegler** [comment]
zu 1. Ich gehe einfach die Issues nochmal durch, die den Milestone haben. Du mußt nichts mehr mit dem Milestone machen. Das Einfachste ist es, wenn man die Issues schließt, wenn sie erledigt sind, dann muß man nur im Milestone nachsehen, ob alle Issues auf close stehen. So wirst du es vermutlich auch machen. Ich hatte die Issues von Usern immer noch offen gelassen und es den Usern überlassen sie zu schließen.

zu 3. Ja

zu 4. Stimmt, sind sie aber in der Regel nicht, weil ich ständig in den Collector transportiere, auch deshalb weil ich die PR von anderen zeitnah bearbeiten möchte und immer mit einem aktuellen Stand arbeiten möchte. Tausch mal 4. und 5. dann paßt es besser, so ist es auch bei mir.

zu 5. :)
Mit $$ und einer fortlaufenden Nummer wurden im SAP Änderungen dokumentiert. Ich habe das hier genauso für mich verwendet. Dann geh ich einmal drüber mit $$ und hab alles erwischt. Nur Kommentare von uns.

zu $$001:                            
```
                                  v0.8   v0.9 v0.10
newParameterOn1 = d.replace("#", "0.6"); 0.3  1.0
newParameterOn2 = d.replace("#", "1.0"); 0.6  0.3
newParameterOn3 = d.replace("#", "0.3"); 1.0  0.6

newParameterLL1 = s.replace("#", "0.6"); 0.3  1.0
newParameterLL2 = s.replace("#", "1.0"); 0.6  0.3
newParameterLL3 = s.replace("#", "0.3"); 1.0  0.6
```
Ich schiebe die Opacity immer um eins runter, dadurch wird die Farbe für eine bestimmte Version im Laufe der Zeit immer weiter runterreguliert, schwächer.

Beispiel:
- Zu v0.8 ist Parameter settings_esc_close_gclh_config neu. Das Coding wird gekennzeichnet mit newParameterOn2, weil opacity 1.0 beträgt, ganz kräftig.
```
html += newParameterOn2;
html += checkboxy('settings_esc_close_gclh_config', 'Close GClh Config on ESC') ...
html += newParameterVersionSetzen(0.8) + newParameterOff;
```
- Zu v0.9 ist Parameter settings_show_pseudo_as_owner neu. Das Coding wird gekennzeichnet mit newParameterOn3, weil opacity 1.0 beträgt, ganz kräftig.
```
html += newParameterOn3;
html += checkboxy('settings_show_pseudo_as_owner', 'Take also owner...
html += newParameterVersionSetzen(0.9) + newParameterOff;
```
- Zu v0.9 ist Parameter settings_esc_close_gclh_config aus v0.8 auf opacity 0.6 zurückgestuft worden, newParameterOn2 wurde nämlich von 1.0 auf 0.6 reduziert. 
- Haben Parameter eine opacity 0.3 fallen sie bei der nächsten Version raus. Das heißt im Coding werden die beiden relevanten Zeilen entfernt. Das sollte man als erstes machen.
```
html += newParameterOn2;
html += newParameterVersionSetzen(0.8) + newParameterOff;
```

zu $$002:
- Ich hatte das zu jeder Auslieferung gemacht, um zu sehen wie es sich entwickelt. Also einfach immer. Das bleibt aber dir überlassen. Bei Stichtag zwei Wochen wollte ich den Stand immer hier eintragen https://github.com/2Abendsegler/GClh/blob/master/docu/counter.md
Meistens habe ich es jedoch vergessen.
- Zugangsdaten stehen in Klammern im Dokument.
- "Zählt Installation je Adresse nur einmal innerhalb von 8 Stunden:" 
Eindeutige Adresse in einem Netzwerk, auch wenn immer wieder die gleiche IP Adresse rausgegeben wird. Es wird tatsächlich je Gerät gezählt.
Mehrfachinstallationen auf einer Adresse werden nur einfach gezählt innerhalb von 8 Stunden. Damit fallen die Tests von manchen Personen unter den Tisch. Bei andhoppe gibts den Parameter, der zeitunabhängig nur einmalig die eindeutige Adresse zählt. Das ist der wichtigste Parameter, wenn es darum geht wieviele Geräte sind mit dem Script bestückt.
Die Flagcounter werden beim Reset nicht korrekt zurückgesetzt. Es wird nur der Zähler auf 0 gesetzt, aber nicht die gesammelten Adressen. Würde man den Flagcounter nicht austauschen würde eine neue Installation mit v0.9.1 nicht mitzählen, wenn für das gleiche Gerät in den letzten 8 Stunden eine Installation zu v0.9 erfolgt ist. Ich habe zwei Flagcounter im Wechsel verwendet, was ausreichend ist, wenn die zwei Versionen mindestens 8 Stunden auseinanderliegen.
  
zu $$003:
Ja. Nur irgendwann gibt es diese Fälle nicht mehr. Und ich bin immer darauf bedacht Coding zu reduzieren. :)

zu $$005:
Es geht hier um permanente Arbeitsdaten wie beispielsweise die show/hide Parameter im dashboard, im Gegensatz zu temporären Arbeitsdaten wie beispielsweise Autovisits für die TBs. Permanente Arbeitsdaten sollen bei einem "Reset dynamic and unused data" nicht entfernt werden. Beispielsweise ist im Moment eine Ausnahme mit /^(show_box)/ vorhanden. Sie verhindert dass Config Parameter, die mit show_box beginnen, entfernt werden. Würde man nun beispielsweise einen neuen show/hide Parameter einbauen unter dem Namen showhide_fuppes, müßte eine neue Ausnahme /^(showhide_)/ oder so eingebaut werden.

zu 6.
![unbenannt](https://user-images.githubusercontent.com/22332216/34960374-d6161f76-fa3a-11e7-8269-7fc9ce698f86.JPG)


zu 8.
Das ist schön. :) Das werde ich dann auch bei meinem letzten Postings bekanntmachen.

**Comment by 2Abendsegler** [comment]
Ich würde gerne die Punkte hier im Issue von nummerisch auf alpha umstellen, damit es eindeutig ist.
Kann ich das noch tun?

**Comment by GFEMajor** [comment]
kannst du gern tun

**Comment by 2Abendsegler** [comment]
Der neue erstmalig verwendete Worldflag Counter zählt etwa 30% mehr als die Andy Hopes, die sich aber immer etwa mit des Easy Countern gedeckt haben, zumindest in Userzählung. Und die Flag Counter lagen immer so zwischen 5 und 10 % unter den Andy Hopes. Das heißt aus meiner Sicht decken sich die alten Counter in etwa. 
Ehrlich gesagt kommt mir das spanisch vor, 30% mehr. Der Counter ist also aus meiner Sicht mal mit Vorsicht zu genießen.

**Comment by GFEMajor** [comment]
So, die Issues sind ja alle zu, haben wir für die 0.9.2 noch was zu tun 😃?

**Comment by 2Abendsegler** [comment]
Aus meiner Sicht nicht. 
Wir könnten warten bis die zwei Wochen um sind, um mal wieder einen aktuellen Userstand zu bekommen, weil ich doch immer nach zwei Wochen gemessen hatte. Andererseits wäre er aber sowieso nicht aktuell weil wir Winter haben und einfach sowieso nicht alle Cacher auf den Seiten rumspringen. 
Vielleicht ist es ja ganz nett wenn deine erste Version nicht riesen groß ist. 
Gib bescheid wenn du noch Fragen hast und wenn ich nochmal drüberschauen soll. :)

**Comment by GFEMajor** [comment]
Ich wollte auch keine neue Version raus bringen 😉. ich meinte nur, dass es für die 0.9.2 zur Zeit nichts zu tun gibt und auch keine Issues mehr offen sind.
Hast du noch etwas, das erledigt werden muss?

**Comment by GFEMajor** [comment]
Vielleicht muss ich mir doch mal #554 anschauen 😃

**Comment by 2Abendsegler** [comment]
Ja, gute Idee. Ich hab sonst nichts mehr.

**Comment by GFEMajor** [comment]
So, ich schreibe mal hier weiter, das passt besser als in der anderen Issue 😃. Ich denke ich wäre jetzt soweit.
Ich würde jetzt den offenen PR vom collector in den Master schieben, und dann die Forumsbeiträge erstellen, oder habe ich etwas vergessen?
Schaust du nochmal drüber?

**Comment by 2Abendsegler** [comment]
Ok mach ich. Ich melde mich wenn ich fertig bin.

**Comment by 2Abendsegler** [comment]
- Version erhöhen im Code.
- Den www.worldflagcounter.com solltest du austauschen. Den kann man nicht zurücksetzen.
Ansonsten alles ok.

**Comment by GFEMajor** [comment]
Zur Version: Mist 😃, hab ich total übersehen.
Zum Worldcounter: Hattest du nicht gesagt ich soll den weg lassen? Aber ok, dann mach ich einen neuen. Speicherst du dir die "alten" irgendwo?

**Comment by 2Abendsegler** [comment]
Zum Worldcounter: Der hat insgesamt zu hohe Werte, hat sich aber im Laufe der Zeit beruhigt. Der ist schon sinnvoll wegen den Browsern und den Betriebssystemen, die man dort gut erkennen kann.
Ich speicher mir nur die Ergebnisse nach zwei Wochen im Dokument counter.md oder so. Hatte ich aber schon wieder vergessen. Mich hat immer nur interessiert wie es sich von Version zu Version verändert, ansonsten sind mir die Counter egal.

**Comment by GFEMajor** [comment]
Der PR in den Master ist geupdated. Nun sollte es passen 😃

**Comment by 2Abendsegler** [comment]
Das mit Ruko2010 im Config sieht aber schlecht aus. Schnellschüsse sind immer Scheiße. ;)

**Comment by GFEMajor** [comment]
Ach Mist, du hast völlig recht 😔.

**Comment by 2Abendsegler** [comment]
Kannst aber Torsten entfernen und nur Amshove stehen lassen, dann paßt es wieder.

**Comment by GFEMajor** [comment]
T. Amshove passt auch (zumindest bei mir, bei dir auch?)

**Comment by 2Abendsegler** [comment]
Bei mir unter FF nicht, hatte ich schon versucht. Mach die blanks hinter den Kommas noch weg, und schreib T.Amshove ohne blank, dann geht es auch bei mir. :)

**Comment by 2Abendsegler** [comment]
Und dann geht es auch unter Chrome.

**Comment by GFEMajor** [comment]
So, dann sollte es jetzt aber passen, oder?

**Comment by 2Abendsegler** [comment]
Passt :)

**Comment by GFEMajor** [comment]
Gut. Ich mach den PR morgen Früh fertig. Dann kann ich auch die Forumsbeiträge fertig machen...

**Comment by GFEMajor** [comment]
Neue Version ist raus. Mal schauen ob ich bei der nächsten alles alleine schaffe 😃

**Comment by 2Abendsegler** [comment]
Das wirst du schon schaffen. Ich bin dann aber sicherlich auch noch verfügbar. :)

**Comment by GFEMajor** [comment]
Das hoffe ich 😃.

**Comment by 2Abendsegler** [comment]
Vielleicht könntest du zukünftig im Changelog meine Änderungen, entgegen dem was wir vereinbart hatten, doch mir zuordnen, das finde ich netter und spornt mich auch etwas an noch was zu machen. :D Und du könntest dich auch eintragen, beispielsweise unten beim Datum.

Und vielleicht könntest du die wichtigsten Sachen im Changelog nach oben schieben. Es springen derzeit weit mehr als die Hälfte der User nach einem Update ins Changelog, am Anfang hat das fast keiner gemacht. Ansonsten schläft das womöglich wieder ein und man bekommt wieder das Gefühl umsonst zu arbeiten. ;)
Nur ein Vorschlag.

**Comment by Ruko2010** [comment]
Ich wollte dich sowieso noch fragen, wie du die Sachen sortiert hast.
Also eher Features nach oben, Fixes nach unten!?
Ja ich füg deinen Namen noch hinzu, kein Problem 😉. Mein Name muss nicht unbedingt rein. Er steht ja schon an ein paar Stellen.

**Comment by 2Abendsegler** [comment]
Genau: Features nach oben, Fixes nach unten. Und innerhalb die wichtigen nach oben. Und wenn man Bilder hat, scheint mir das immer besser als nur Text.

Schreib deinen Namen ruhig auch rein. Wenn du mal in Urlaub bist und jemand anders ne Version macht ...
Ehre wem Ehre gebührt.
