### ISSUE TITLE
Runnable under browser Safari

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#582]
Laut einer Rückmeldung von vor einigen Wochen läuft der GClh auch unter Safari.
Beim Worldflagcounter werden mittlerweile auch 7 Installationen unter Safari auflistet. 

@GFEMajor 
Ich würde das gerne in die Doku mit aufnehmen in readme und tips_installation und bei der nächsten Version auch im Changelog. Das bedeutet dann aber, dass wir gegebenenfalls auch nach Fehlermeldungen unter Safari schauen müßten.
Was meinst du, sollen wir den Safari mit auflisten?

**Comment by GFEMajor** [comment]
Ich würde mir die Sachen erstmal gern im Safari installieren und schauen ob die grobe Funktionalität auch geht.
Wenn ja können wir ja Safari als "Beta" mit aufnehmen

**Comment by 2Abendsegler** [comment]
Ok.
Wenn du magst kann ich die Doku später anpassen. Gib bescheid.

Aber was ist denn Beta. :) 
Das hab ich noch nie verstanden. Wenn ich was an den Kunden gebe dann hab ichs auch getestet, dann soll es auch funktionieren, da brauch ich auch kein Beta. Beta ist doch nur für die Looser, die sich bei Fehlern rausreden wollen, hihi.

**Comment by GFEMajor** [comment]
😃 Die Einstellung gefällt mir. Aber ich hätte es so gedacht, dass ich mir die groben Funktionen anschaue. Aber alles werde ich nicht testen (können). Damit würde ich es für Safari "as it is" also als Beta raus geben...Die User können ja gern Fehler berichten, und ich werd mich auch drum kümmern, aber ich würde nicht versichern wollen, dass alles unter Safari geht 😉, darum Beta

**Comment by 2Abendsegler** [comment]
Schon ok. :)

**Comment by GFEMajor** [comment]
- Dropbox Sync funktioniert nicht

(ich werd das Komment hier aktualisieren wenn ich weitere Fehler finde)

**Comment by 2Abendsegler** [comment]
Die Safari Logos hatte ich schon mal rausgesucht. Stehen jetzt bei den Images.
safari_logo.png
safari_logo_small.png

**Comment by GFEMajor** [comment]
Danke. Ich werde heute noch ein paar Tests im Safari machen und dann die Docu anpassen.

**Comment by 2Abendsegler** [comment]
Das war aber keine Aufforderung von mir. Eigentlich eilt es nicht. Bis zur nächsten Version gehen ja noch einige Tage ins Land. Ich wollte nur mal die Logos wegschieben die ich lokal auf dem Rechner hatte. Schönes WE.

**Comment by GFEMajor** [comment]
Ich weis 😃. Ich arbeite auch gerade noch an der anderen Issue die ich aufgemacht habe. Dann mach ich erst den Safari test 😉

**Comment by GFEMajor** [comment]
Dropbox geht doch. Lag wahrscheinlich daran, dass ich mit dem falschen Account eingeloggt war...ich werde die Unterstützung frei geben. ich habe nichts gefunden, was nicht geht.

**Comment by 2Abendsegler** [comment]
In README.md wird durch das Browser Icon ein Zeilenumbruch durchgeführt. Scheinbar ist beim Mac alles mehr zusammengeschoben. Schau mal ob du das selbst in irgendeinem Browser erkennen kannst. Ansonsten ist das doof, weil es dann ungewollt für >75% der User Zeilenumbrüche gibt und du kannst sie nicht sehen.

**Comment by Ruko2010** [comment]
Du hast völlig recht. so sieht es im Windows aus:
![image](https://user-images.githubusercontent.com/2239440/36410875-67e6fc74-1613-11e8-8a48-7a0848f9da98.png)
und so bei mir:
![image](https://user-images.githubusercontent.com/2239440/36410886-7458b06a-1613-11e8-8f01-e62d7ee6d818.png)

Das ist ja total doof, dass die Browser das so unterschiedlich darstellen. Ich schau mal ob ich das Fixen kann.

**Comment by Ruko2010** [comment]
@2Abendsegler ich habe es mal etwas umgebaut. In der Readme sind ja mehr Leerzeichen als Caches die ich gefunden habe...^^.
Ich habe es jetzt erstmal so gemacht:
https://github.com/Ruko2010/GClh/blob/collector/README.md

ich bin damit aber noch nicht zu frieden. Ich werde das Layout denke ich nochmal umarbeiten und die Logos der Browser woanders hin schieben, so dass man nichts mehr "rechts am Rand" positionieren muss. Das ist glaube ich die sauberste Lösung.

**Comment by 2Abendsegler** [comment]
Das fixen ist ja nicht das Problem, sondern wie du es zukünftig sehen kannst. Wie kommst du zu dem Windows Screen?

**Comment by Ruko2010** [comment]
Ich hab eine Virtuelle Maschine mit Windows 7 hier auf dem Mac. Die brauch ich für GSAK 😉

**Comment by Ruko2010** [comment]
Ja das mit der Englischen Version wollte ich auch nachholen 😃.
Leider kann man auf der Readme Seite von Github nur Bilder nach rechts schieben. Alle anderen "style" Tags werden entfernt, so dass man keine ganzen Blöcke verschieben kann.
Ich schau mal, dass ich das gesamte Design der Readme neu mache und dann gleich noch die Englische Version dazu. Ich werd es dir dann zur Prüfung geben wenn du willst 😉. ich mach aber dafür mal ein neues Ticket auf. Das gehört ja nicht mehr hier rein: https://github.com/2Abendsegler/GClh/issues/599

Dann kann diese Issue auch wieder zu 😃

**Comment by 2Abendsegler** [comment]
Prüfen muss nicht sein. 

Im Grunde kannst du ja machen was du möchtest. Ich versuche nur bei dem einen oder anderen behilflich zu sein, sofern sich bereits das eine oder das andere als gut oder schlecht rausgestellt hat. ;)
