### ISSUE TITLE
[Edge] After Tampermonkey update to 4.5.5648 GClh is not running anymore

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#583]
http://geoclub.de/forum/viewtopic.php?p=1280081#p1280038

von Peter_Keller » Di 6. Feb 2018, 09:37

Hallo,

seid dem Tampermonkey für Edge Update auf 4.5.5648 funktioniert GCLH nicht mehr. Es verhält sich so als wäre es überhaupt nicht da. Oben rechts im Icon wird aber eine rote 1 angezeigt. Ich habe auch nur dies eine Script aktiviert.

---
von 2Abendsegler » Di 6. Feb 2018, 22:23

Lösche bitte mal den temporären Speicher von Edge cookies ... und versuchs nochmal.
Deinstalliere Tampermonkey und damit auch den GClh und installiere sie erneut. Bei Firefox gabs das auch schon dass nichts mehr ging und nach einer Neuinstallation plötzlich wieder alles ok war. Die GClh Einstellungen vorher sichern.

Wenn das nicht hilft:
Kannst du bitte mal die Konsole aufrufen? Edge hat bestimmt auch so etwas. Bei Firefox und Chrome geht es mit den Tasten Strg Shift k gleichzeitig drücken.
"Syntax error ... JSHINT output und die Folgezeilen mit require" interessieren dabei nicht.
Wenn noch etwas anderes dort steht, dann poste das doch bitte mal hier. Bitte vorher auch den ganzen Fehler aufklappen, da gibts ganz links bei jedem Fehler einen Pfeil oder einen Button.

LG Frank

---
von Peter_Keller » Mi 7. Feb 2018, 17:55

2Abendsegler

So ich habe Tempermonkey und GCLH neu installiert und keine Veränderung.

Hier sind die Meldungen aus der Konsole:
```
HTML1300: Navigation wurde ausgeführt.
default.aspx
DOM7011: Der Code auf dieser Seite hat die Zwischenspeicherung für das Vor- und Zurücknavigieren deaktiviert. Weitere Informationen dazu finden Sie unter: http://go.microsoft.com/fwlink/?LinkID=291337
dashboard
Aktuelles Fenster: www.geocaching.com/account/dashboard
HTML1500: Die Markierung kann nicht selbstschließend sein. Verwenden Sie eine explizite schließende Markierung.
dashboard (375,21)
ERROR: Execution of script 'GC little helper II' failed! Unable to get property 'substring' of undefined or null reference
Function code (125) (2,389)
TypeError: Unable to get property 'substring' of undefined or null reference
   at quitOnAdFrames (Function code:957:5)
   at start (Function code:932:5)
   at tms_08192034_550e_4bb1_8bef_d496240d63c1 (Function code:11682:1)
   at Anonymous function (Unknown script code:2:116)
   at Anonymous function (Function code:2:1)
   at Anonymous function (Function code:1:58)
   at Function code (Function code:1:5)
   at Anonymous function (Unknown script code:2:116)
   at D.E_c (Unknown script code:2:433)
   at pa (Function code:59:179)
Function code (125) (2,476)
AI: TelemetrySampledAndNotSent message:"Telemetry is sampled and not sent to the AI service." props:"{SampleRate:1}"
Logging.ts (199,36)
```

**Comment by 2Abendsegler** [comment]
@GFEMajor 
Das läuft nur unter Windows 10, hab ich aber nicht. Kannst du dir das bitte mal ansehen?

**Comment by 2Abendsegler** [comment]
@GFEMajor
Was mir gerade noch einfällt. DrakMrak arbeitet so weit ich weiß sogar mit Edge. Vielleicht kannst du ihn auch anfunken, wenn es bei dir nicht klappt.

**Comment by GFEMajor** [comment]
Ich hab leider auch kein Windows 10, ich bin doch die Mac-Fraktion 😃.

@DrakMrak one of our Edge users is having trouble with the newest tampermonkey version and GClh. Have you updated your tampermonkey version yet? If yes, do you have any problems?

**Comment by GFEMajor** [comment]
Maybe we continue in english, so @DrakMrak can follow up 😃.

I think the problem is here:
`ERROR: Execution of script 'GC little helper II' failed! Unable to get property 'substring' of undefined or null reference
Function code (125) (2,389)
TypeError: Unable to get property 'substring' of undefined or null reference`

there are only 11 places where the "substring" function is called in the script, so it should be one of this positions causing the problem...

**Comment by DrakMrak** [comment]
I am looking at it

**Comment by DrakMrak** [comment]
It also does not work so I'm looking at where the problem is ...

**Comment by GFEMajor** [comment]
Great. Thank you.

**Comment by DrakMrak** [comment]
element: windows.name --> retuened 'undefined' = null
I think some problem in TamperMonkey or EDGE

```
var quitOnAdFrames = function(c) {
    var quitOnAdFramesDeref = new jQuery.Deferred();
    console.log('---------');
    console.log(window.name);
    console.log('---------');
    if (window.name.substring(0, 18) !== 'google_ads_iframe_') quitOnAdFramesDeref.resolve();
    else quitOnAdFramesDeref.reject();
    return quitOnAdFramesDeref.promise();
};
```
**returned:**
 ---------
 undefined
 ---------

**Comment by DrakMrak** [comment]
this will help - if I understand the function properly
```
var quitOnAdFrames = function(c) {
    var quitOnAdFramesDeref = new jQuery.Deferred();
    try {
        if (window.name.substring(0, 18) !== 'google_ads_iframe_') quitOnAdFramesDeref.resolve();
        else quitOnAdFramesDeref.reject();
    }
    catch(err)
    {
        quitOnAdFramesDeref.resolve();
    }
    return quitOnAdFramesDeref.promise();
};
```

**Comment by DrakMrak** [comment]
in EDGE is windows.name ---> Undefined
in FireFox is windows.name  ---> empty string

**Comment by GFEMajor** [comment]
Thanks @DrakMrak. I looked over your code. Instead of using a catch statement for this purpose, wouldn't it be better to test the windows.name variable? I think this is a more clean and understandable code (untested, because I don't have EDGE, but runs in FF):

`var quitOnAdFrames = function(c) {
    var quitOnAdFramesDeref = new jQuery.Deferred();
    if(window.name){
        if (window.name.substring(0, 18) !== 'google_ads_iframe_') quitOnAdFramesDeref.resolve();
        else quitOnAdFramesDeref.reject();
    }else{
        quitOnAdFramesDeref.reject();
    }
    return quitOnAdFramesDeref.promise();
};`

**Comment by DrakMrak** [comment]
OK no problem but you have error in else part must be...

```

var quitOnAdFrames = function(c) {
    var quitOnAdFramesDeref = new jQuery.Deferred();
    if(window.name) {        
        if (window.name.substring(0, 18) !== 'google_ads_iframe_') quitOnAdFramesDeref.resolve();
        else quitOnAdFramesDeref.reject();
    }
    else {
        quitOnAdFramesDeref.resolve();
    }
    return quitOnAdFramesDeref.promise();
};
```

**Comment by DrakMrak** [comment]
this working well

**Comment by DrakMrak** [comment]
good, please cancel my pull request and I do it again better ;)

**Comment by GFEMajor** [comment]
You can just push more commits. They will be added to your PR

**Comment by DrakMrak** [comment]
ok

**Comment by 2Abendsegler** [comment]
Great guys!
I still looked at Chrome and Opera. They are fine.

@GFEMajor 
Mac? :) right :)
Do not wait for my merge, it's your play. ;)

**Comment by GFEMajor** [comment]
@2Abendsegler I would like to test it in Chrome / FF tonight before merging it. I know I have to do such things now 😉

**Comment by GFEMajor** [comment]
Ich wollte gerade nen neuen Flag Counter erstellen. Was für Einstellungen nimmt man da? Die Standartsachen?
![image](https://user-images.githubusercontent.com/2239440/35995173-df604436-0d12-11e8-8a59-b8e118cdac94.png)

**Comment by GFEMajor** [comment]
zu Nr.6 Backup vom Collector erzeugen. Speicherst du dir die Lokal, oder packst du die in einen Ordner in Git (ich seh nämlich keinen 😃)

**Comment by 2Abendsegler** [comment]
Du hast 2 Flagcounter die du abwechselnd verwenden kannst. Einen neuen brauchst du eigentlich nicht.
Die Einstellungen sind egal, weil wir das Icon ja nicht anzeigen.

Ja, lokal.
