### ISSUE TITLE
Marker in Titelleiste anzeigen wenn man noch Entwürfe hat

### ISSUE THREAD

**Issue by GFEMajor** [2Abendsegler/GClh#589]
Eventuell so etwas wie der kleine gelbe Kreis, den man sieht wenn man eine neue Nachricht hat.
@2Abendsegler was hälst du davon?

**Comment by GFEMajor** [comment]
@2Abendsegler Das wäre meine Vorstellung. Was sagst du dazu? Mit einem Klick auf die Zahl kommt man dann direkt zu den Entwüfen.
Der Code zum Abruf ist schon fertig. Ich muss nur noch einen Schalter in die Konfig einbauen 😃
![image](https://user-images.githubusercontent.com/2239440/36050365-9341cde8-0de6-11e8-9438-a3714e6c223c.png)
![image](https://user-images.githubusercontent.com/2239440/36050397-b13bb0de-0de6-11e8-8d0f-ebc8c5d814a5.png)
![image](https://user-images.githubusercontent.com/2239440/36050406-bd2b1f92-0de6-11e8-8020-c28ad253e0a2.png)

**Comment by 2Abendsegler** [comment]
Ja, sieht schon mal gut aus. :)

**Comment by GFEMajor** [comment]
Schön, dass du als Zweitmeinung es auch gut findest 😉. Ich bin immer etwas unsicher wenn es um "Desingsachen" geht.
Ist es eigentlich ok, wenn ich dich sowas noch frage, oder hast du dafür keine Zeit mehr?

**Comment by 2Abendsegler** [comment]
Ist ok. :)
Es ist immer schön wenn man neben seiner eigenen noch ne Meinung hat. Ich kenn das auch.
