### ISSUE TITLE
images in filtered out logs load as a new page (on a specific cache page)

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#591]
Hello Frank,
I've come across an odd issue.

Steps to reproduce:

1) for the purpose of resolving this issue assign me to your VIPs - [Pontiac_CZ](https://www.geocaching.com/profile/?guid=40df1622-4af7-4a44-882e-540d104eea38)
2) open this cache page: https://www.geocaching.com/geocache/GC1PXDD_vk-137-tvrz-kasarov
3) filter out VIP logs 
![image](https://user-images.githubusercontent.com/9153595/36306284-60ad7ad6-1317-11e8-9534-d47458b1b6f5.png)
4) during the filter action the Javascript that takes care of displaying bigger versions of the attached images gets somehow corrupted or what.
5) go down to find my log and click on either image
6) the image opens up as a new page and not as an overlay window as usual. Consequence of this is that when you click "Back" in your browser it does not take you back to your log as it loads all logs again.
7) in case you do not use the filter and scroll down to my log manually, images open correctly as expected.

Weird thing is it does not happen on other cache pages that I have tried. There's something wrong with this one...?

This is what I mean by an image opened on a new page:

![image](https://user-images.githubusercontent.com/9153595/36306733-6839de82-1319-11e8-8df3-0ccc42cb51cd.png)

**Comment by GFEMajor** [comment]
Hello @PontiacCZ I can reproduce this issue. I will have a look at it.

**Comment by 2Abendsegler** [comment]
@GFEMajor Hey, the effect seems to occur only if it is the last log.

**Comment by GFEMajor** [comment]
Hey Pontiac. I think I found the error. Are you able to make changes to the script yourself? If so, please locate this lines around line 4698 in the current master version 0.9.2.:
`if (logs[i] && (logs[i].LogType == log_type || (log_type == "VIP" && (in_array(logs[i].UserName, global_vips) || logs[i].UserName == vip_owner)))) {
                                var newBody = unsafeWindow.$(document.createElement("TBODY"));
                                unsafeWindow.$("#tmpl_CacheLogRow_gclh").tmpl(logs[i]).appendTo(newBody);
                                injectPageScript("$('a.tb_images').fancybox({'type': 'image', 'titlePosition': 'inside'});");
                                unsafeWindow.$(document.getElementById("cache_logs_table2") || document.getElementById("cache_logs_table")).append(newBody.children());
                            }`

If you just exchange the two last lines, it should work:
`if (logs[i] && (logs[i].LogType == log_type || (log_type == "VIP" && (in_array(logs[i].UserName, global_vips) || logs[i].UserName == vip_owner)))) {
                                var newBody = unsafeWindow.$(document.createElement("TBODY"));
                                unsafeWindow.$("#tmpl_CacheLogRow_gclh").tmpl(logs[i]).appendTo(newBody);
                                unsafeWindow.$(document.getElementById("cache_logs_table2") || document.getElementById("cache_logs_table")).append(newBody.children());
                                injectPageScript("$('a.tb_images').fancybox({'type': 'image', 'titlePosition': 'inside'});");
                            }`

Can you confirm, that this fixes the problem?

**Comment by PontiacCZ** [comment]
Yep, that helps. I exchanged the two last lines and it works now. Thank you, GFEMajor! :-)

Not sure if I am supposed to close this issue since the fix is not officially out yet. So feel free to close it at will. :)

**Comment by GFEMajor** [comment]
If the problem is solved, you can always close an issue 😉. I will role out the fix in the next version. Thanks for reporting.
