### ISSUE TITLE
If user not logged in and visiting a cache page directly, he has no chance to sign in

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#594]
![image](https://user-images.githubusercontent.com/2239440/36368624-73022522-1558-11e8-9a18-22dfaa8e3c5d.png)

**Comment by Ruko2010** [comment]
Menue is hidden, so user can't log in to see the cache page

**Comment by 2Abendsegler** [comment]
Das passiert nur bei PMO Caches. Hängt damit zusammen, dass der GClh auch ausgeführt wird selbst wenn kein User angeloggt ist. Das fand ich immer schon blöd, eigentlich sollte der GClh dann gar nicht laufen. Dann wurde aber der Facebook Login angezeigt.

Ich hab eine einfache Lösung. Soll ich die mal in den Collector stellen?

Off-Topic: Falls du keine Werbung auf den GC Seiten haben möchtest. Da gibt es ein winziges Script. :)
https://github.com/2Abendsegler/GC_ad_blocker

**Comment by Ruko2010** [comment]
Ja du kannst die Lösung gern in den Collector stellen. Ich hab mir schon gedacht, dass es nur bei PMO ist, wollte mir es aber noch genauer anschauen.
Werbung: Die lass ich lieber, immerhin finanziert das Geocaching mit. Und wenn es hilft die Premiumkosten etwas weiter unten zu halten, lass ich die gern anzeigen 😉.

**Comment by 2Abendsegler** [comment]
Hab das "Hide Facebook" weiter nach oben geschoben und steig dann anschließend aus dem maingc aus. Das ist das Einzige was auch ohne User laufen sollte.

Off-Topic: Ich glaube das finanziert nur dann, wenn man draufklickt.

**Comment by 2Abendsegler** [comment]
<li>
Fix: If user not logged in and visiting a cache page directly, he has no chance to sign in: [Issue <a href="https://github.com/2Abendsegler/GClh/pull/594">#594</a>]<br>
<br>
</li>

**Comment by Ruko2010** [comment]
Danke für den Fix...
> Off-Topic: Ich glaube das finanziert nur dann, wenn man draufklickt.
Ich glaube nicht. zumindest ist es bei Google Anzeigen so, dass man schon bezahlt wenn das nur angezeigt wird. Aber du hast recht, es gibt Netzwerke wo man erst was bekommt, wenn man drauf klickt. Aber so es drum. wenn die Werbung nicht überhand nimmt, dann stört sie mich auch nicht.

**Comment by 2Abendsegler** [comment]
Die Änderungen zu diesem Issue sind auf dem Collector verschwunden. Ich schätze mal, das hängt mit deinen letzten Merges zusammen. Ich weiß nicht ob auch andere Dinge verschwunden sind. Kannst du bitte mal prüfen?

Ich stelle einen PR zur Verfügung mit dem die Änderungen zu diesem Issue und dem #601 wieder eingebaut werden können. Bitte spiel du den PR ein.

**Comment by Ruko2010** [comment]
hast du in der richtigen Branch geschaut? Also wenn ich den aktuellen Stand des collectors anschaue, dann ist dein Commit mit dem Facebook schon (noch?) drin!
Hast du vielleicht in meinem Collector geschaut? Da sind deine Änderungen nicht drin, und das hat seine Richtigkeit.

**Comment by Ruko2010** [comment]
![image](https://user-images.githubusercontent.com/2239440/36728701-f62e896c-1bc1-11e8-9d8e-2ca972a72f9b.png)
@2Abendsegler

**Comment by 2Abendsegler** [comment]
Jetzt holen wir mal tief Luft und machen alles nochmal. :)
Das ist der Collector bei mir:
![1](https://user-images.githubusercontent.com/22332216/36733281-6c37906e-1bd0-11e8-8733-0d3a033a7998.JPG)


Und das ist der neue PR bei dem es mir aufgefallen ist:
![2](https://user-images.githubusercontent.com/22332216/36733301-7adc655e-1bd0-11e8-955e-6fe9065e2aeb.JPG)

Schau mal bitte nochmal. :)

**Comment by Ruko2010** [comment]
Schau mal bitte in zeile 510 des aktuellen collectors. Da ist diese Facebookfunktion bei mir schon drin (in deinem Repo, im aktuellen Collector (siehe URL im Browser)). Aber das ist natürlich die Stelle von `var mainGMaps = function() {`. Deine Facebook funktion ist bei `var mainGC = function() {` drin. Muss die in beide rein?

![image](https://user-images.githubusercontent.com/2239440/36733492-18f9c902-1bd1-11e8-995d-7ee96625f33e.png)

**Comment by Ruko2010** [comment]
Dein Commit vor 8 Tagen, hatte es an die Stelle `var mainGMaps = function() {` eingefügt. Und das ist wie gesagt auch noch drin.

**Comment by 2Abendsegler** [comment]
Das ist ja völlig falsch, was ein Dreck, mein Fehler. Ich erinnere mich, dass ich beim letzten PR schon die gleichen Probleme hatte. Sorry.
Ich korrigier das jetzt.

**Comment by Ruko2010** [comment]
Gut das wir drüber geredet haben 😃.
