### ISSUE TITLE
Renew your subscription is hidden

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#595]
Bug or feature? I have to check this.

![image](https://user-images.githubusercontent.com/2239440/36368702-d09b4498-1558-11e8-847c-c49bb5196d8c.png)

**Comment by 2Abendsegler** [comment]
Der Button fiel dem benötigten Platz insbesondere für das horizontale Menü zum Opfer. Es wäre sicherlich eine komplexe Aufgabe, den Button wieder anzuzeigen, weil die Berechnung des zur Verfügung stehenden Platzes für die Menüs im Header ebenfalls ohne den Button erfolgt. 
 
Zeile so um die 790:
```
            // Member Upgrade Button entfernen.
            $('.li-upgrade').remove();
            if ($('.li-membership')[0]) $('.li-membership')[0].remove();
```

**Comment by Ruko2010** [comment]
hmm...und wenn man aus dem Button einen kleineren Button macht sowas wie das hier:
![image](https://user-images.githubusercontent.com/2239440/36395184-2b5ec18e-15b8-11e8-87f9-2ea1274dbe5a.png)

**Comment by 2Abendsegler** [comment]
Die Berechnungen fürs Vertikale Menü lassen meines Wissens nicht mehr als 20 Pixel frei bis der Message Button kommt. Wenn man die Berechnungen ändert kann man nochmal einige Pixel rausholen für die derzeitige Standardkonfiguration mit Logo anzeigen und in Deutsch. Viel ist es aber nicht. 
Egal wie klein der neue Button wird, beim horizontalen Menü gibt es wahrscheinlich Post von Usern die dieses Menü nutzen. :)  Als GS irgendwann Anfang letzten Jahres den User-Message Bereich oben überarbeitet hat, gabs auch Post, obwohl dadurch nur wenige Pixel verloren gingen.  

Mich hat das nie gestört, dass das Teil weg ist, und Klagen gabs auch nicht. :)
Wieso willst du es überhaupt haben?

**Comment by 2Abendsegler** [comment]
Ach ja, und bei der Karte ist gar kein Platz wenn GC Tour im Einsatz ist, weil dort noch ein Button hinzukommt.

**Comment by Ruko2010** [comment]
hmm....ok, dann lassen wir das sein...
