### ISSUE TITLE
Problem with #Found# placeholder on the new logging page

### ISSUE THREAD

**Issue by gboye** [2Abendsegler/GClh#596]
On FF 58.0.2, with TamperMonkey 4.6.5703, we do not get the right number (a very low number like 4 or 5) in place of the #Found# placeholder.

**Comment by Ruko2010** [comment]
Hi @gboye. Have you testet it on the old page?

**Comment by Ruko2010** [comment]
Is the problem only in FF? have you testet it with another browser?

**Comment by gboye** [comment]
It's working perfectly well on the old page. I did not test it on any other browser.

**Comment by gboye** [comment]
The difference seems to come from the presentation of the number of caches found in the old version "3,695" and the new "3 695" (actually "3&#160;695") which might mess up the regex.

**Comment by Ruko2010** [comment]
or maybe your country uses another "number format" with the space in it. Are you able to edit the script code in tampermonkey? If yes, can you try this please:

Go to Line 7010 (Current version v0.9.2) and change the following line:
`function get_my_finds() {
        var finds = "";
        if ($('.cache-count').text()) finds = parseInt($('.cache-count').text().match(/[0-9,\.]+/)[0].replace(/[,\.]/,""));
        return finds;
    }`
Please add in the replace statement after the "." a space (" "). The function should read
`function get_my_finds() {
        var finds = "";
        if ($('.cache-count').text()) finds = parseInt($('.cache-count').text().match(/[0-9,\.]+/)[0].replace(/[,\. ]/,""));
        return finds;
    }`
after the modification.

**Comment by Ruko2010** [comment]
Ignore my last comment. It is not working. I try to modify the statement to get it work :). Hang on

**Comment by Ruko2010** [comment]
ok, I think I have it. try to replace the line
`if ($('.cache-count').text()) finds = parseInt($('.cache-count').text().match(/[0-9,\.]+/)[0].replace(/[,\.]/,""));`
with
`if ($('.cache-count').text()) finds = parseInt($('.cache-count').text().match(/[0-9,\. ]+/)[0].replace(/[,\. ]/,""));`
(add a space " " in both regexes after the dot "."
This should fix the problem when the cache number is displayed with a space in it

**Comment by Ruko2010** [comment]
Sorry for all the comments, but now I could really reproduce your problem. I switched my language on geocaching.com to france and had the same problem.
This code solves the problem:

`if ($('.cache-count').text()) finds = parseInt($('.cache-count').text().replace(/\s/g,'').match(/[0-9,\.]+/)[0].replace(/[,\.]/,""));`

it removes the whitespace before parsing the number.

**Comment by gboye** [comment]
Thx a lot.

**Comment by Ruko2010** [comment]
I'll roll out this fix with the new version. I'm closing this issue now. If you encounter anything else, just let me know.
