### ISSUE TITLE
Update Readme Layout, Add English Version

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#599]

**Comment by Ruko2010** [comment]
@2Abendsegler Ich habe mal die erste Version der englischen Readme hochgeladen. Auch wenn deine Englischkenntnisse auch nicht perfekt sind, vielleicht kannst du mal drüber lesen 😃. Steht bis jetzt nur bei mir im Folk:
https://github.com/Ruko2010/GClh/blob/collector/README.md

**Comment by 2Abendsegler** [comment]
Ja super! Bitte jetzt noch in Tschechisch und Französisch. 

 

Hab nur Kleinigkeiten:

 

1. Ich würde Safari hinter Chrom hängen, von den Userzahlen wird es vermutlich auch darauf hinauslaufen. Logos und im Text.

 


2. Gleiche Abschnitte in de und en

 

... werden.

 

Das Tool ist in englisch. Es ist kostenlos und ohne Werbung.

 

3. Die Installationshilfe sollte meines Erachtens ganz weit nach oben. Und vielleicht auch als Link Text Installationshilfe oder so wie bisher, damit es richtig ins Auge sticht. Ich finde nichts schlimmer wenn ich sowieso schon gereitzt bin weil die Installation nicht klappt und dann muß ich auch noch Doku lesen bis ich endlich einen Link zur Abhilfe finde. ;)

 

4. Ich würde den englischen Text vor den deutschen legen. Wenn ein englischer da war hab ich das an anderer Stelle auch so gemacht.

 

Ansonsten klasse.
LG Frank

 

Gesendet: Donnerstag, 22. Februar 2018 um 14:18 Uhr
Von: Ruko2010 <notifications@github.com>
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: 2Abendsegler <eifra@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Update Readme Layout, Add English Version (#599)


@2Abendsegler Ich habe mal die erste Version der englischen Readme hochgeladen. Auch wenn deine Englischkenntnisse auch nicht perfekt sind, vielleicht kannst du mal drüber lesen 😃. Steht bis jetzt nur bei mir im Folk:
https://github.com/Ruko2010/GClh/blob/collector/README.md

**Comment by Ruko2010** [comment]
So @2Abendsegler , ich denke ich habe alle Änderungsvorschläge von dir eingebaut.

**Comment by 2Abendsegler** [comment]
Bin nochmal drüber, sieht super aus!

Für die Sprungmarken innerhalb eines Dokumentes hat sich meines Erachtens bewährt die Sprache mit aufzunehmen. Das gilt zumindest für einheitliche Marken wie halt beim Namen des Scriptes. Das nur so, ist ja trotzdem so alles richtig. ;) 

Bei den Installationstips, ich hab nur gerade die Links angewählt, habe ich de noch als erstes stehen. Safari steht noch unten und bei Safari steht noch Edge im Text. Ist mir nur gerade aufgefallen, ich weiß das ist noch nicht fertig.

**Comment by Ruko2010** [comment]
> Für die Sprungmarken innerhalb eines Dokumentes hat sich meines Erachtens bewährt die Sprache mit aufzunehmen. Das gilt zumindest für einheitliche Marken wie halt beim Namen des Scriptes. Das nur so, ist ja trotzdem so alles richtig. ;)

Hä 😃? Das versteh ich nicht, die Sprungmarken sind doch sprachabhängig, oder reden wir über zwei verschiedene Sachen? Außerdem werden doch alle Sprungmarken in der Readme von GitHub generiert. Nur die für die Sprachwahl (Flagge oben) hab ich manuell eingefügt.

> Bei den Installationstips, ich hab nur gerade die Links angewählt, habe ich de noch als erstes stehen. Safari steht noch unten und bei Safari steht noch Edge im Text. Ist mir nur gerade aufgefallen, ich weiß das ist noch nicht fertig.

Da bin ich noch nicht drüber gegangen. Das passe ich noch an. Auch die Links würde ich da noch sprachabhängig machen, so dass die Englischen direkt in die Englischen Tips springen und die Deutschen halt ins Deutsche 😉

**Comment by 2Abendsegler** [comment]
Mit den Sprungmarken ist alles ok. :)
Für den Namen des Scriptes hat GitHub die Sprungmarke in der Anzeige automatisch durchnummeriert. Ich dachte du hättest das gemacht, alles cool, hihi.

**Comment by Ruko2010** [comment]
So, nun sollte alles passen. Ich hoffe ich habe nichts übersehen. @2Abendsegler schaust du nochmal drüber?

**Comment by 2Abendsegler** [comment]
Hab mir readme und Installationstips angesehen. Sieht alles prima aus.

Nur eine Kleinigkeit die du womöglich mit dem Mac wieder nicht sehen kannst. Das Safari Icon ist nicht ausgerichtet in den Installationstips.

**Comment by Ruko2010** [comment]
Doch das sehe ich auch, aber bei mir waren die alle nicht "ausgerichtet" 😃. Ich habs mal umgedreht und die Icons nach vorn genommen.
https://github.com/Ruko2010/GClh/blob/collector/docu/tips_installation.md

**Comment by 2Abendsegler** [comment]
Ja super, paßt. :)
