### ISSUE TITLE
On new dashboard search button is moved due to changes made by GS

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#607]
![searchbutton verschoben](https://user-images.githubusercontent.com/22332216/36783055-31dbb728-1c7b-11e8-885b-8ce3940092c4.png)

@Ruko2010 
Können wir das noch in der v0.9.3 reparieren? Die Änderungen sind quasi schon gemacht. Ich würde nochmal das Script anpassen und das Changelog noch ergänzen und beides auf den Collector mergen. Und du kannst die Änderungen dann noch in deinen PR aufnehmen.  
Ist das ok?

**Comment by 2Abendsegler** [comment]
<li>
Fix: On new dashboard search button is moved due to changes made by GS: [Issue <a href="https://github.com/2Abendsegler/GClh/pull/607">#607</a>]<br>
Thanks to <a href="https://www.geocaching.com/profile/?u=2Abendsegler">2Abendsegler</a> for the Fix.<br>
</li>

**Comment by Ruko2010** [comment]
Klar. Schmeiß rein 😉

**Comment by Ruko2010** [comment]
Schieb es einfach in den Collector, dann sollte es ja automatisch noch im PR zum Master auftauchen. Ich prüfe das heute Abend dann nochmal bevor ich den Release Live stelle.

**Comment by 2Abendsegler** [comment]
Ja genau, die Änderungen sind schon in deinem PR mit drin.
