### ISSUE TITLE
Draft count is also displayed at project GC button

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#611]
If project GC script is running too, draft count is also displayed at project GC button.

![unbenannt](https://user-images.githubusercontent.com/22332216/36831206-fcd4e5c0-1d26-11e8-91e0-021a64d44a37.JPG)

Usermail:
--

Guten Morgen,

Mit dem Update auf Version 0.9.3 habt ihr diese feine Funktion mit dem Draft eingebaut. Ich nutze das Script Project-GC, wenn dieses mit installiert ist wird auch bei diesem eine "Draft Zahl" angezeigt. Wäre es möglich das ihr nur für das Nikename Icon die Anzeige schaltet?

Besser sichtbar auf dem Bild.

Danke und Grüße

**Comment by 2Abendsegler** [comment]
```
1127 old  $('.user-avatar').prepend('<span class="draft-indicator"><a href="/my/fieldnotes.aspx" title="Go to Drafts">' + draft_count + '</a></span>');
1127 new  $('.li-user-info .user-avatar').prepend('<span class="draft-indicator"><a href="/my/fieldnotes.aspx" title="Go to Drafts">' + draft_count + '</a></span>');
```

**Comment by 2Abendsegler** [comment]
Antwort an User:
--
Moin,
 
[Issue 611](https://github.com/2Abendsegler/GClh/issues/611).
 
Zur nächsten Version ist der Fehler berichtigt. Wenn du in der Lage bist selbst am Script Hand anzulegen, dann korrigiere bitte Zeile 1127 wie folgt:

```
1127 old  $('.user-avatar').prepend('<span class="draft-indicator"><a href="/my/fieldnotes.aspx" title="Go to Drafts">' + draft_count + '</a></span>');

1127 new  $('.li-user-info .user-avatar').prepend('<span class="draft-indicator"><a href="/my/fieldnotes.aspx" title="Go to Drafts">' + draft_count + '</a></span>');
```
LG Frank

**Comment by 2Abendsegler** [comment]
Usermail
--
Super, Vielen Dank

Grüße und Weiter so...ihr macht eine Klasse Arbeit

**Comment by Ruko2010** [comment]
@2Abendsegler Ich hab mich gerade gefragt, warum du den Text deiner Issue so komisch schreibst, bis ich gesehen habe, dass es eine Usermail war.
Wie kam die Mail zu dir? Warum legt der User keine Issue dafür an?

**Comment by Ruko2010** [comment]
Achja, Danke für den Fix. wenn du die Sachen fixed, kannst du gern auch gleich das Changelog mit anpassen wenn du willst.
ps.: was macht das Script ProjectGC eigentlich bzw kannst du mir einen Link schicken? Dann schau ich selbst...

**Comment by 2Abendsegler** [comment]
Manch einer möchte lieber per Mail kommunizieren und möchte sich nicht bei GitHub anmelden.

Das ist kein Einzelfall, tatsächlich kommen die meisten Anfragen oder Bugs über Mail. Es hilft auch nicht es anzusprechen, bis zum nächsten Mal haben sie es wieder vergessen.

**Comment by Ruko2010** [comment]
ok, das verstehe ich. Aber wo haben die deine EMailadresse her? Wäre ja günstiger wenn solche Sachen zu mir kommen, oder?

**Comment by 2Abendsegler** [comment]
Ich hab keine Ahnung, vermutlich über den GC User oder übers Forum.

Du mußt etwas Geduld haben, die werden auch zu dir kommen. ;)

**Comment by 2Abendsegler** [comment]
Project GC

https://github.com/magma1447/greasemonkey-geocaching-projectgc/raw/master/greasemonkey-geocaching-projectgc.user.js

 

Ich nutze das um mir bei den Gallery Bildern automatisch die EXIF Koordinaten anzeigen zu lassen. Das Script kann aber noch mehr. Das Script hinterlegt sich im Header, dort kannst du nachsehen was es alles macht.

 

Gesendet: Donnerstag, 01. März 2018 um 09:18 Uhr
Von: Ruko2010 <notifications@github.com>
An: 2Abendsegler/GClh <GClh@noreply.github.com>
Cc: 2Abendsegler <eifra@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [2Abendsegler/GClh] Draft count is also displayed at project GC button (#611)


Achja, Danke für den Fix. wenn du die Sachen fixed, kannst du gern auch gleich das Changelog mit anpassen wenn du willst.
ps.: was macht das Script ProjectGC eigentlich bzw kannst du mir einen Link schicken? Dann schau ich selbst...

**Comment by Ruko2010** [comment]
Danke für den Link. Ich schau mir das mal an.
Da du im anderen Issue über die Mysteries gesprochen hast. Ich kann dir noch den Mystery Wizard empfehlen. Der deckt auch so einige Kleinigkeiten im Listing auf 😉:
https://www.saarfuchs.com/?s=mystery+wizard

Vielleicht sollte ich das bei den nächsten Release Notes und den Forumbeiträgen noch mit einfügen, dass Sie mich gern kontaktieren können oder hier eine Issue aufmachen.

**Comment by 2Abendsegler** [comment]
Den Mystery Wizard will ich nicht, weil man das Script nicht lesen kann. ;)
Trotzdem danke.

Du kannst es gerne reinschreiben, es wird aber bei diesen Kollegen nichts bringen. Die haben jetzt ihren Ansprechpartner, tut mir leid, hihi. 

Ich habs am Anfang doch auch erklärt mit den issues, die wollen sich aber nicht auch dort noch anloggen.

Jetzt bleib mal cool, leg die Füsse hoch und lass die Zeit es regeln. ;)
Das wird schon.

**Comment by Ruko2010** [comment]
ok 😃
