### ISSUE TITLE
Link "Show on Flopp´s Map"

### ISSUE THREAD

**Issue by Mitchsa** [2Abendsegler/GClh#614]
The link "Show on Flopp´s Map" leads to https://flopp.net/.
But this page does not work properly.
The adress https://flopp-caching.de/ works fine.

**Comment by Ruko2010** [comment]
Thanks @JuicyFruit6 for reporting. I'll look into this.
Just for me: I thought https://flopp.net/ and https://flopp-caching.de/ are equivalent?! Can you tell me what the difference is?

**Comment by JuicyFruit6** [comment]
It seems the server at https://flopp.net/ isn't working anymore?
Via trial you get this message "An internal server error occurred. Please try again later."
 
I`m using old Firfox ESR. I've tested Edge in the moment. There everything is OK?

**Comment by Ruko2010** [comment]
Are you using tampermonkey or greasemonkey in your Firefox?
For me https://flopp.net/ is working fine in FF, Chrome and Safari

**Comment by JuicyFruit6** [comment]
Greasemonkey, but it doesn't matter, because the direkt link to  https://flopp.net/ isn't working, too!?

**Comment by JuicyFruit6** [comment]
It seems the problem is the old version of firefox ESR 52.6.0?

**Comment by JuicyFruit6** [comment]
I will do so, thx :)

**Comment by Ruko2010** [comment]
no problem. If your problem is solved, can you please update the ticket here? I'm interrested in the solution 😉.

**Comment by 2Abendsegler** [comment]
Ähnliches Problem aus geoclub verlinkt.
https://geoclub.de/forum/viewtopic.php?f=117&t=80306#p1280464

**Comment by JuicyFruit6** [comment]
Wenn ich die Links im Quelltext mit flopps-caching.de ersetze, geht alles.
Es scheint ein Problem mit der alten Firefox Version und dem Server von Flopps zu sein?
Anfrage bei Flopps ist gestellt.

**Comment by Ruko2010** [comment]
Ach schön, es geht auf Deutsch weiter 😃. Ich kann den link ja gern in der nächsten Version umstellen, das ist für mich kein Problem, aber ich wüsste schon gern wo der Fehler liegt 😉. Ich denke, dass beide Seiten die gleiche Codebasis haben und auch auf dem gleichen Server laufen.

**Comment by JuicyFruit6** [comment]
Problem weiter eingekreist :)  Siehe https://github.com/flopp/FloppsMap/issues/84
**Es betrifft ALLe flopp Adressen!!!**

**Comment by JuicyFruit6** [comment]
Flopps scheint eine Lösung parat zu haben :)
Liegt wohl am Cookiehandling. Er wird versuchen das Problem mit HTML5-LocalStorage in den Griff zu bekommen.

Werde hier nun closen.

**Comment by JuicyFruit6** [comment]
Hier ist jedenfalls alles Bestens. Danke für eure Arbeit :)

**Comment by JuicyFruit6** [comment]
Dieses Problem wurde von Flopps gelöst. 
Alle die dieses Problem haben müssen aber einmal den Cookie von  https://flopp.net/ löschen.
Danach funktionierts wieder reibungslos.

**Comment by Ruko2010** [comment]
Vielen Dank für den Hinweis, somit könnne wir auch den anderen Usern helfen. Ich mach die issue hier zu.
