### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#616]
@2Abendsegler was hälst du davon, wenn wir (mit wir meine ich natürlich mich 😃) den GClh übersetzen und in mehr als einer Sprache anbieten? Meinst du das bringt einen Mehrwert, oder nur mehr Aufwand 😃? Ideen zur Umsetzung hätte ich und es wäre initial sicher ein riesiges Projekt, aber so wie ich es sehe auf jeden Fall machbar.
Die Frage ist, ob sich der Aufwand gegenüber dem Nutzen lohnt. Was meinst du dazu. Eventuell finden wir auch jemand, der die Übersetzung für andere Sprachen (Polnisch / Tschechisch) übernimmt.

**Comment by 2Abendsegler** [comment]
Moin.
Vermutlich würden die Userzahlen leicht steigen, weil es sicherlich einige gibt, die sich vor Englisch ins Höschen machen. :) Meines Erachtens wird das aber überschaubar bleiben. 
Wir hatten das Thema schon mal und ich hatte damals alle Informationen in einem eigenen Thread (Translation) zusammengetragen. Schau mal im geoclub bei den Scripten. Dort ist auch beschrieben wie die Übersetzungen gemacht werden könnten. Wir halsen uns damit aber bei jeder kleinen Erweiterung Probleme auf, denn jedes noch so kleine Teil muss dann auch wieder übersetzt werden. ;)
Ich würde den Aufwand nicht treiben. Ich würde lieber cachen gehen oder andere Erweiterungen bauen.

**Comment by Ruko2010** [comment]
Das klingt vernünftig. Dann lassen wir das.

**Comment by Cappa-d** [comment]
Wenn ich es richtig verstanden habe, dann setzt c:geo hier auf den Ansatz der cloud... Wäre das im Fall eines Falles nicht eine Variante? Wenn die Texte in einer Sprachdatei sind und ihr mit den Variablen arbeitet bzw. dann ein Übersetzungsfile habt, dass nur bei Vollständigkeit einer Sprache gepflegt wird?

Nur eine Idee, aber ich kann Franks Ansatz natürlich auch verstehen ;)

**Comment by 2Abendsegler** [comment]
Die Ideen im benannten [Thread](http://geoclub.de/forum/viewtopic.php?f=117&t=79390) stammen hauptsächlich von SammysHP und den Erfahrungen mit c:geo. Die Übersetzungen würden sicherlich in einer Cloud (Crowdin) passieren. 
Das Problem ist meines Erachtens aber tatsächlich das kontinuierliche Arbeiten am Script. Dort würde zusätzlicher Mehraufwand entstehen, bei jeder kleinen Erweiterung.

**Comment by Cappa-d** [comment]
Ja, bei der Schlagzahl in der Ihr Veränderungen bringt, gebe ich Dir Recht ;)

**Comment by Ruko2010** [comment]
Also meine Idee wäre folgende gewesen (so mache ich das in anderen Projekten 😉):

1. Statt einer "normalen" Textausgabe wird jeder Text im Englischen über eine Funktion ausgegeben.
Also statt `var text = "I'm a testtext";` dann sowas wie `var text = __("I'm a testtext")`
2. Es gibt pro Sprache eine CSV Datei, in der jeweils die Übersetzung steht. Das heißt für deutsch wäre es:
`"I'm a testtext","Ich bin ein testtext"`
3. Es wird ein helper script entworfen, dass über den gclh "drüber läuft" und alle texte automatisch extrahiert und in die englische CSV-Datei schreibt.

um flexibler zu sein, kann man die Ausgabe auch noch erweitern, so dass solche Sachen denkbar sind:
`var text = __("I'm a testtext. The result is %s items", 5)`, wobei das `%s` automatisch mit der 5 ersetzt wird. Dann ist man flexibler was die Strings angeht.

**Comment by Ruko2010** [comment]
Wie gesagt, dass "große" Problem sehe ich im initialen aufwand. Man muss die 12000 Zeilen durch gehen und alles einmal auf die neue Ausgabefunktion umstellen. Für spätere Entwicklungen muss man sich nur merken, dass Ausgaben immer über die Übersetzungsfunktion gemacht werden müssen
