### ISSUE TITLE
Entwickeln mit Tampermonkey

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#619]
Eine Beschreibung wie man Tampermonkey für GClh so konfigurieren kann, dass man das Userskript in einer lokalen Kopie im Dateisystem bearbeiten kann.

**Comment by Ruko2010** [comment]
Ich habe mir den ersten Draft durchgelesen. Genauso mache ich es auch 😃. Das funktioniert übrigens ähnlich (bzw. fast genau so) auch in Chrome.

**Comment by 2Abendsegler** [comment]
Off-Topic:
Da ist ja jemand auferstanden. :) Moin CachingFoX, nice to see you.
