### ISSUE TITLE
Modifizieren der Einträge auf der neuen Entwurfsseite

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#620]
Modifizieren der Einträge auf der neuen Entwurfsseite
- Cache-Icon verlinkt auf das Cachelisting
- Cache-Icon bekommt ein Icon, dass den Logtyp anzeigt
- Cache-Title verlinkt nicht mehr auf die Log-Seite, sondern auf das Listing. Die Logseite kann über die dritte Zeile aufgerufen werden
- Die Modifikation der Items kann über die Konfiguration deaktiviert werden

Anpassung der Verlinkung und Ergänzung des Logtyps als Icon
![v0 9 4_screen4a](https://user-images.githubusercontent.com/1838534/37571070-2cfe9582-2af8-11e8-9653-684ea377da83.png)
![v0 9 4_screen4b](https://user-images.githubusercontent.com/1838534/37571077-3a374d98-2af8-11e8-918a-893501db2cf8.png)
In den Einstellungen
![v0 9 4_screen4c](https://user-images.githubusercontent.com/1838534/37571078-3cd7161e-2af8-11e8-9c3c-273f68970ea5.png)

**Comment by Ruko2010** [comment]
Die Idee an sich finde ich gut, aber ich würde nicht die Hauptfunktion des Titellinks ändern. Was ich damit meine, der Click auf den Cachenamen sollte weiterhin zum Logeintrag führen. Eventuell kann man einen weiteren Button oder Link einfügen der zum listing führt. 
Die Sache mit dem Logtyp als Icon finde ich toll 😃

**Comment by CachingFoX** [comment]
Danke für das schnelle Feedback. Die Veränderung des Links vom Titel habe ich auch zweischneidig gesehen. Evtl. wäre ein Icon rechts neben der Mülltonne besser. Ich werde mal eine Anpassung versuchen.

Die Anpassung der Items ist relativ einfach, weil man nur das Handlebar Template dafür modifizieren muss. Allerdings ist man in der Funktionalität etwas eingeschränkt, da nur wenig Funktionen für das Handlebar Framework implementiert sind und der Zugriff auf das Framework nicht so ohne weiteres aus dem Userskript möglich ist.

**Comment by Ruko2010** [comment]
Eventuell so? (bitte entschuldige die sehr schlechte Qualität 😉)
![37571077-3a374d98-2af8-11e8-918a-893501db2cf8](https://user-images.githubusercontent.com/2239440/37582193-0f739e14-2b4c-11e8-9328-4acb8417a437.png)

**Comment by CachingFoX** [comment]
Habe nun ein weiteren Action-Button auf der rechten Seite hinzugefügt. Dieser öffnet das Listing in einen extra Tab. Über das Icon bin ich nicht ganz glücklich, habe aber aktuell kein besseres gefunden. 
![bildschirmfoto am 2018-03-19 um 08 15 03](https://user-images.githubusercontent.com/1838534/37582541-cb95038e-2b4d-11e8-933a-e92e97051426.png)

**Comment by CachingFoX** [comment]
Hallo Ruko2010, 
dar warst du schnell. Siehe mein Entwurf. Ich finde aber das Icon bei dir besser. Ist das Icon bei GC verfügbar?

**Comment by Ruko2010** [comment]
Nein das Icon kommt aus der Schriftart Font-Awesome und sollte nur als Beispiel dienen: https://fontawesome.com/icons?d=gallery

Ich weis nicht wie es mit der Lizenz aussieht, aber vielleicht kannst du es auch einfach kopieren und einzeln einfügen (als Data-Blob).

Ansonsten vielleicht einfach mal die Sprites von GC durchgehen und schauen ob da was brauchbares dabei ist:
https://www.geocaching.com/account/app/ui-icons/sprites/global.svg
Eventuell das hier: icon-signout-svg-fill und dann gespiegelt an der Y-Achse
![image](https://user-images.githubusercontent.com/2239440/37588552-d220d376-2b62-11e8-96e8-47d21e1c6f97.png)

**Comment by CachingFoX** [comment]
Bei externe svg z.B. von Fontawesome (Symbole sind auch als einzelne svg verfügbar) müsste die Lizenzfrage geklärt werden und außerdem wird das Laden von externe Resourcen blockiert.

Daher habe ich einmal geschaut, ob man ein Pfeilsymbol über Unicode bekommt. Einen Pfeil aus einem Kästchen gibt es nicht, allerdings ein Pfeil nachschräg oben:
![bildschirmfoto am 2018-03-20 um 19 13 27](https://user-images.githubusercontent.com/1838534/37674366-07a261fc-2c73-11e8-94f4-950d6b8206db.png)

So habe nun noch etwas geschaut. Also bei den GC Sprites habe ich nichts direkt passendes finden können. Eben nur caret nach rechts (siehe Bild oben) und den More-Button (drei Punkte in einem Kreis) was ja nicht wirklich stimmt.

Alternativ habe ich andere GC Symbole verwendet und diese etwas gedreht:
![bildschirmfoto am 2018-03-20 um 19 29 36](https://user-images.githubusercontent.com/1838534/37675312-43c9157a-2c75-11e8-8958-92bece70b4b9.png)
Von links nach rechts: Pfeil, Pfeil im Kreis, Map, Map Simple.

Wobei mir die Map Simple ab besten gefällt.

Was meint ihr?

**Comment by Ruko2010** [comment]
Hmm, ich finde das Kartensymbol nicht passend. Da denke ich, ich komm zur Karte und nicht zum Listing.
Ich würde den Pfeil mit dem Kreis nehmen.

**Comment by Ruko2010** [comment]
Off Topic: Bei Gelegenheit musst du mir mal sagen woher du weist, wie du das Template bearbeitet hast, bzw. woher du weist was du ändern kannst, damit es immer noch funktioniert 😃.

**Comment by CachingFoX** [comment]
Die finale Lösung:
![Uploading Bildschirmfoto am 2018-03-23 um 23.50.39.png…]()

**Comment by CachingFoX** [comment]
Die Entwickler von GS haben das Framework [](https://handlebarsjs.com/) eingebaut. Leider habe ich es nicht geschafft, mich an das Framework direkt zuhängen. So ist eine Erweiterung um eigene Funktionen nicht möglich. 

In der Webseite werden in einer <script>-Sektion das HTML Template definiert und dieses kann man austauschen, wenn man die Seite modifizieren möchte.
