### ISSUE TITLE
Open Elevation als alternative zu Google Elevation

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#621]
@CachingFoX Ich habe deine Arbeit mal in mein Repo übernommen und angeschaut. 
Warum rufst du die Funktion über setTimeout auf? 
Zeile 2197: 
`setTimeout(function() {
                    GM_xmlhttpRequest({
                        method: 'GET',
                        url: elevationServices[serviceIndex]['url'] + locations,
                        onload: elevationServices[serviceIndex]['function'],
                        onerror: function() {gclh_log("Elevation: ERROR: request elevation for waypoints failed!");}
                    });
                }, wait);`

Noch was anderes:
https://www.geocaching.com/geocache/GC1KEZX_jenaer-muschelkalk-i#
Die beiden APIs liefern ziemlich unterschiedliche Werte (341m zu 306m). Was ist denn nun besser 😃?

**Comment by CachingFoX** [comment]
Aus welchen Branch hast du den die Änderung übernommen? Ich checke alle Änderungen in fox-dev-0.9.4 ein.

Der Aufruf mit setTimeout war schon enthalten. Ich denke damit wollte man die mehrfachen Aufrufe hintereinander mit zeitlichen Abstand versehen.

Ich habe auch noch einmal das Händling umgebaut und den Code vereinfach und klarer strukturiert.

Das liegt an der Interpolation der Daten. Dazu gab es schon einmal in der Grünen Hölle einen langen Diskussionsthread.

**Comment by CachingFoX** [comment]
Der AXAJ-Aufruf mit `setTimeout` wurde entfernt, da nun bei  Probleme beim ersten Höhnedatendienst auf den zweiten Dienst umgeschwenkt wird. Hintergrund ist, dass Google Elevation nur eine gewisse Anzahl von Abfragen pro Zeit und Region erlaubt (Fehlermeldung: OVER_QUERY_LIMIT). Dadurch kam es häufiger dazu, dass keine Höhendaten mehr angezeigt wurden.

**Comment by CachingFoX** [comment]
*Achtung* Es wurden Anpassungen in gclh_defi.js gemacht. Evtl ist eine Anpassung im Stub/Wrapper notwendig.
```
// @require          https://raw.githubusercontent.com/2Abendsegler/GClh/master/data/gclh_defi.js
```
zu
```
// @require          file:///C:/projects/gclh/GClh/data/gclh_defi.js
```

**Comment by CachingFoX** [comment]
Weitere Anpassung:
* Einbinden des Services Open-Elevation
* Festlegen der Reihenfolge der Elevation Services
* Verbesserung der UX: 
** Anzeige einer Ladeanimation während der Abfrage
** Bei Problemen wird '???' angezeigt
** Mittels Tooltip kann festgestellt werden, welcher Service die Daten geliefert hat

**Comment by CachingFoX** [comment]
Informationen zu den Antwort-Status von Google Elevation: [](https://developers.google.com/maps/documentation/geocoding/intro#StatusCodes)
