### ISSUE TITLE
Sort souvenirs after acquired date

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#624]
Sort souvenirs on private and public souvenirs page after acquired date (ascend, descend).

**Comment by Ruko2010** [comment]
Ein ganz dickes +1 von mir für die Idee 😃. Ich hasse die aktuelle Souvenir Seite! Warum sortieren die das das Namen? Das macht für mich überhaupt keinen Sinn 😉.
@CachingFoX hattest du meinen review deines PR gesehen?

**Comment by CachingFoX** [comment]
Ist schon quasi implementiert :-D

@Ruko: Ja und nein - PR wahrgenommen, aber noch nicht begutachtet

**Comment by Ruko2010** [comment]
Sehr schön...

btw: mit "@ruko" hast du gerade jemand anders kontaktiert 😉. Du musst drauf achten immer den ganzen namen hinter das @ zu schreiben 😉

**Comment by Ruko2010** [comment]
Also ein Großteil meiner Souvenire sind die der Länder. Wenn man die Gruppiert reicht das vielleicht schon um ein wenig Übersicht hinein zu bringen...

**Comment by Ruko2010** [comment]
Vielleicht kannst du dir hier auch was abschauen:

https://project-gc.com/Tools/SouvenirList

**Comment by CachingFoX** [comment]
Die Einbindung in die Settings wird aufwändiger als die Implementierung des Features :-1: Vorerst werde ich die einfache Sotierung nach Datum implementieren. Eine Gruppierung folgt evtl. später und dann mit extra Ticket.

**Comment by Ruko2010** [comment]
Das klingt vernünftig. Machst du die Sortierung dynamisch über einen Button in der Souvenirliste, oder rein über die Konfig? Wenn du erstes machen würdest, dann brauch mal an sich ja keine Konfiguration.
Dann könntest du beim Laden der Seite die Original-Sortierung anzeigen und dann bei klick auf Button "nach Datum sortieren" erst die Sortierung ausführen.

**Comment by CachingFoX** [comment]
Some additional information

Dashboard > Souvenirs
https://www.geocaching.com/my/souvenirs.aspx

Public Profile 
*New style* https://www.geocaching.com/p/default.aspx?u=CachingFoX&tab=souvenirs#profilepanel
*Old style* https://www.geocaching.com/profile/?u=Waldkauz1977 > Souvenirs

Container
// private/dashboard: divContentMain
// public profile new ctl00_ContentBody_ProfilePanel1_pnlSouvenirs
// public profile old ???

**Comment by CachingFoX** [comment]
# Known problems
* Sorting order of souvenirs acquired on the same day is not stable. 
Reproducible: 

1. Click on Newest
2. Click on A-Z
3. Click on Newest

**Comment by Ruko2010** [comment]
Könnte man das Problem nicht umgehen, indem man einfach eine Funktion sort(A,B, Algorithm) macht und wenn der erste Vergleich das gleiche Ergebniss liefert (zum Beispiel acquired ist gleich), dann wird einfach der nächste Algorithmus auch noch angewendet. Dann wäre die Sortierung stabil.

**Comment by Ruko2010** [comment]
Sozusagen eine Fall-Back-Strategie:

Ist der original-Algortihmus Sort_By_Date:ASC dann wird als Fall-Back Sort_By_Name:ASC genommen.
Ist der original-Algortihmus Sort_By_Date:DESC dann wird als Fall-Back Sort_By_Name:DESC genommen.
usw.

**Comment by Ruko2010** [comment]
@CachingFoX wenn ich nach Datum sortieren will, bekomme ich folgende Fehlermeldung und alle Souvenire sind weg:
![image](https://user-images.githubusercontent.com/2239440/39230190-d7900366-4865-11e8-93b7-ea8af4a116b1.png)
Die markierte Stelle im Code ist:
`function getSouvenirAcquiredDate( souvenirDiv ) { return $(souvenirDiv).text().match( /20[0-9][0-9]-[01][0-9]-[0123][0-9]/g )[0]; }`

**Comment by Ruko2010** [comment]
Ok, Problem erkannt. Man kann in den Preferences von Geocaching.com ein DateFormat angeben. Die Auswahl ist leider ziemlich umfangreich 😔.
![image](https://user-images.githubusercontent.com/2239440/39326758-4dcc5350-4996-11e8-8f51-08620e0b5d27.png)

Man kann also nicht wirklich das Matching aus deiner Funktion nutzen um das Datum zu extrahieren. 
@CachingFoX ich habe leider keine gute Idee wie man das Fehlersicher machen könnte ohne das verwendete Date-Format zu kennen.

**Comment by Ruko2010** [comment]
Ich hab mir die Sachen mit dem Regex nochmal angeschaut. Leider kann man meinen Vorschlag nicht umsetzen, da `$(souvenirDiv).text()` den gesamten Text liefert, und nicht nur den Text unter dem Link. Also lassen wir das so wie es ist.

Die Stabilisierung der Sortierung hab ich aber noch eingebaut.
