### ISSUE TITLE
Erweitertes Map Popup funktioniert nicht

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#633]
**Describe the bug**
https://geoclub.de/forum/viewtopic.php?f=117&t=80208&start=50#p1282812

**To Reproduce**
1. Go to maps
2. Click on a Cache
3. See error

**Expected behavior**
Map Popup with more informations will be displayed.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser FF
 - Version 59.0.3

**Additional context**
Ein anderer User mit Vivaldi und Win10 beschreibt auch, dass es bei ihm nicht geht.
@2Abendsegler kannst du mal schauen ob es bei dir klappt? Du hast doch auch Win10, richtig?

**Comment by 2Abendsegler** [comment]
Habs mitbekommen und wollte heute morgen sowieso mal kurz checken, hab aber win 8.1, aber trotzdem.

**Comment by Ruko2010** [comment]
Dankö :).
Also wenn ich die Fehlermeldung `GClh_ERROR - enhance cache popup - https://www.geocaching.com/map/: Argument 1 of MutationObserver.observe is not an object.` richtig interpretiere, dann kann es sein, dass das Map Popup noch nicht verfügbar (im DOM) ist und man deswegen dem Observer (Zeile 6167 im aktuellen Master `observer.observe(target, config);`) das taget (Zeile 6008 `var target = document.querySelector('.leaflet-popup-pane');`) nicht übergeben kann.
Wenn das wirklich der Fall ist muss ich mir irgendwas einfallen lassen. Aber es wäre schön, wenn man das Problem wenigstens nachstellen könnte 😃. Nur ein reproduzierbarer Bug ist ein guter Bug 😉

**Comment by 2Abendsegler** [comment]
Bei win 8.1 läufts auch fehlerfrei.
Ich hab spätestens am Wochenende ein win 10 System und werde dann nochmal danach sehen.
Jetzt bin ich im Urlaub vermutlich bis Samstag.
Vielleicht kannst du aber trotzdem v0.9.5 raushauen mit dem reparierten save Problem im Config, weil das irgendwie doof ist und auch alle betrifft.
Bis dann.

**Comment by Ruko2010** [comment]
Neue Version ist draußen. Sorry für den Fehler. Ich hatte nur die Funktion an sich getestet, aber nicht das einstellen in der Config.

**Comment by 2Abendsegler** [comment]
Hey, kein Problem, dat passiert halt mal.
Ja Forums Beiträge wären schon ok.

**Comment by 2Abendsegler** [comment]
Alles geklärt. Lag an "The Cachetur Assistant".
https://geoclub.de/forum/viewtopic.php?f=117&t=80208&p=1282894#p1282890

**Comment by Ruko2010** [comment]
@2abendsegler danke fürs closen, aber du brauchst es nicht vom Milestone entfernen. Is ja sozusagen erledigt und damit legitim drin zu bleiben, auch wenn es keine Änderung bei uns gab.
