### ISSUE TITLE
Save in Config does not work.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#634]
id settings_primary_elevation_service nicht vorhanden.
Das war nicht getestet. :(

**Comment by 2Abendsegler** [comment]
Das sollten wir aus meiner Sicht schnell bereinigen, weil man keine Einstellungen mehr sichern kann.

**Comment by Ruko2010** [comment]
Es ist live im Master. Soll ich dafür auch die Forumsbeiträge machen?
