### ISSUE TITLE
Popup message on all geocaching webpages

### ISSUE THREAD

**Issue by kyrsa33** [2Abendsegler/GClh#637]
**Describe the bug**
Since I installed the latest version 0.9.5, every time I open a geocaching webpage I get the following popup:
The script "GC Little Helper II" is already running.
Please make sure that it runs only once.

**To Reproduce**
1. On Windows 10, Firefox 59.0.3 (64-bit), install GC Little Helper II version 0.9.5. Note: in my case, I was upgrading from version 0.9.4.
2. Open any (and every) webpage from the https://www.geocaching.com website or https://www.google.ca
4. See error popup message described above.

**Expected behavior**
There should be no error popup when navigating on webpages of the two websites mentioned in step 2.

**Screenshots**
![gclittlehelperpopuperror](https://user-images.githubusercontent.com/38994179/39657605-770064e0-4fd7-11e8-903e-35a7ada3a62b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 59.0.3 (64-bit)
 - Version GC Little Helper II version 0.9.5

**Additional context**
The upgrade from 0.9.4 to 0.9.5 was a little strange. I hit the Save button in Tampermonkey and noticed the issue ever since.

**Comment by Ruko2010** [comment]
Hi @kyrsa33 . Can you have a look at tampermonkey and see, if the script is installed twice?
Or maybe you have installed greasemonkey in Addition to tampermonkey with the script running?
Maybe you backup you config and try to reinstall the script.
Usually, if the error pops up, the script is really running two or more times

**Comment by 2Abendsegler** [comment]
@Ruko2010
Das sind jetzt einige User die das Problem haben. Mir ist total unklar wieso das Problem scheinbar erst in den letzten beiden Versionen auftritt. Hast du ne Idee? Das scheint ja für die User auch ein Problem zu sein das sie häufig auch nicht selbst lösen können. Wenn wir keine Meldung ausgeben aber nur die Verarbeitung des ersten GClh zulassen läuft womöglich ein GClh mit einer alten Version, nur weil es das Script ist welches als erstes startet. Mir fällt nichts ein wie man das anders regeln kann.

**Comment by Ruko2010** [comment]
Eventuell sollten wir die Fehlermeldung anpassen und dort erwähnen, was die Leute selbst checken können (Greasemonkey, 2 Fache Installation)

**Comment by 2Abendsegler** [comment]
Ja und vielleicht auch mit Link zu einer kleinen Doku im Dokument Installationstips oder in einem eigenen Dokument.

**Comment by 2Abendsegler** [comment]
... also wie beispielsweise die Meldung nach der Installation mit Link ins Changelog.

Kannst du das übernehmen?

**Comment by kyrsa33** [comment]
I confirm that GreaseMonkey was the cause of my problem. I was using it many months ago before we were all forced to switch to TamperMonkey. Somehow, it re-enabled itself and GC Little Helper II is currently at version 0.9.5 in GreaseMonkey as well. Disabling GreaseMonkey fixes the issue.

What is the recommendation? Should I:
- Disable GreaseMonkey, or
- Uninstall GreaseMonkey, or
- Disable GC Little Helper II from GreaseMonkey, or
- Uninstall GC Little Helper from GreaseMonkey, or
- Uninstall GC Litttle Helper from TamperMonkey and use GreaseMonkey again from now on?

**Comment by Ruko2010** [comment]
@2Abendsegler yes, i‘ll do it. 
@kyrsa33 you have 2 options, since GClh is not compatible with greasemonkey any more. Uninstall the script from greasemonkey and use tampermonkey OR uninstall greasemonkey completely and use tampermonkey 😃.

**Comment by kyrsa33** [comment]
I have uninstalled the script from Greasemonkey. No more popup even when Greasemonkey is turned on.
Thank you for all the help.

**Comment by Ruko2010** [comment]
@kyrsa33 no Problem. We are currently designing an FAQ section, where this problems are described. Hope this will help other people with such problems.
