### ISSUE TITLE
Runnable under browser Internet Explorer

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#642]
**Describe the solution you'd like**
Internet Explorer testen und in Dokumente integrieren.

Es sind 28 Installationen (eigentlich dividiert durch 3 oder 4) vorhanden unter Internet Explorer. 
(Entgegen meinen Erwartungen kommt Safari nicht voran und Edge macht gar keiner mehr. Dokumente könnte man auch umsortieren nach der Häufigkeit.)

Statistik vom 05.05.2018:
```
1. 	Firefox			3546
2. 	Chrome 			1172
3. 	Opera Next / Opera	84
4. 	Vivaldi			31
5. 	IE			28
6.	Safari			20
7.	Edge			0
```

**Comment by Ruko2010** [comment]
Ich kann den IE leider nicht so richtig testen, da ich nur eine VM mit Win7 habe. ich weis nicht wie sich das auswirkt. Ich könnte es mal generell versuchen, aber eine "Laufgarantie" wie für FF oder Chrome würde ich (vor allem angesichts der Userzahlen) erstmal nicht geben.
Die Dokumente würde ich nicht nach den Userzahlen sortieren, sonst sind wir ja ständig am Umsortieren 😉. Es reicht wenn alle drin sind.
@2Abendsegler was denkst du?

**Comment by 2Abendsegler** [comment]
Ja du hast recht, das reicht auch. ;)
Ich wollte das auch irgendwann mal machen. Das kann nur etwas dauern. Ich assign das mal.

**Comment by 2Abendsegler** [comment]
Das scheint nicht so einfach wie gedacht, weil es kein Tampermonkey für den Internet Explorer gibt. Es gibt einige Beschreibungen wie man Userscripts unter IE ermöglichen kann, denen will ich aber nicht nachgehen.
Hier eine: https://kaiserkiwi.de/2014/07/userscripts-im-internet-explorer-installieren/

Ich rejecte und schließe das Issue.
