### ISSUE TITLE
Copyright in GClh Config is too long, it is partly demolished

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#643]
**Describe the bug**
Die Copyright Ausgabe im GClh Config ist zu lang und wird teils umgebrochen und demoliert. Es scheint auch mit der Ausgabebreite des Screens zusammenzuhängen. Spielt aber keine Rolle. Wir sollten das anders machen, ein weiterer User würde ja sowieso nicht mehr reinpassen.

**Expected behavior**
Vielleicht könnte man alle paar Sekunden den nächsten User einblenden nachdem man den vorangegangenen User ausgeblendet hat. Dann kann man auch wieder die vollen Daten auch mit Angabe der Jahre verwenden.
Oder man könnte auch ein Laufband machen.

**Desktop (please complete the following information):**
 - Win 10 Enterprise
 - FF 59.0.3
 - GClh v0.9.5

**Comment by Ruko2010** [comment]
Ich würde die Ausgabe einfach komplett anders machen und unter (oder über?) die Button schieben. Dann kann man die volle Breite der Config-Seite nutzen und hat auch kein Problem wenn noch jemand hinzu kommt.

**Comment by 2Abendsegler** [comment]
Ja, lass es uns so machen. Unter den Buttons ist vielleicht netter. Assign es wenn du anfängst, ansonsten werd ich mirs diese Woche vielleicht auch noch schnappen, wenns zeitlich noch paßt.

**Comment by 2Abendsegler** [comment]
![grafik](https://user-images.githubusercontent.com/22332216/39755404-fcc30c18-52c5-11e8-8ae1-662f247656d1.png)

**Comment by Ruko2010** [comment]
Sieht gut aus. Willst du vielleicht das Enddatum bei unseren beiden Namen noch dynamisch nach dem aktuellen Jahr machen? Sonst müssten wir das einmal im Jahr anpassen 😉.

`var ende = (new Date()).getFullYear();`

**Comment by 2Abendsegler** [comment]
Wer weiß schon was im nächsten Jahr ist, hahaha. Gut dass du gleich das Coding mitgeliefert hast, ich hätte es nämlich nicht parrat gehabt. ;)

Ist eingebaut und getestet.

Im Scriptkopf müssen wir es aber trotzdem im nächsten Jahr anpassen.

**Comment by Ruko2010** [comment]
Wir machen einfach eine Issue auf mit Due-Date 01.01.2019 😂
