### ISSUE TITLE
Push the map further down when the map popup is displayed

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#646]
**Is your feature request related to a problem? Please describe.**
Map popup ist nicht komplett sichtbar wenn das Icon zu weit oben angewählt wird weil die Karte nicht weit genug nach unten verschoben wird.

![grafik](https://user-images.githubusercontent.com/22332216/39691719-bf72b7ba-51de-11e8-8352-08bc422d353b.png)

**Describe the solution you'd like**
Karte weiter nach unten schieben, wenn das map popup angezeigt wird.

**Comment by Ruko2010** [comment]
Das hab ich auch schon gemerkt. ich wollte mal schauen, ob ich direkt das Template, dass GC für die Karte benutzt ändern kann, so wie CachingFox das mit der DraftPage gemacht hat. Aber das dauert wohl etwas länger 😃

**Comment by Ruko2010** [comment]
Ich habe es nun wie CachingFox gemacht und direkt das Template auf der Seite angepasst. Damit schiebt sich das Popup auch halbwegs in den richtigen Abstand. Leider bekomme ich es nicht komplett nach oben, aber das ist in der "normalen" Version (ohne GClh) auch so.
![kapture 2018-06-12 at 20 44 22](https://user-images.githubusercontent.com/2239440/41310384-a5ceda9a-6e81-11e8-8a5f-ef63ca11b1cb.gif)

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Kannst du dir das vielleicht nochmal ansehen.

- [ ] 1. Ich hatte mir dass nochmal angesehen um zu schauen wie du es gemacht hast. Ich habs aber nicht verstanden. Kannst du mir vielleicht kurz sagen welches Coding dafür verantwortlich ist, dass die Karte nach unten wandert?
- [ ] 2. Es ist etwas suboptimal, dass wir das komplette Template in unserem Coding ersetzen. Tun wir doch, oder? Änderungen oder Erweiterungen von GS werden nun nicht mehr berücksichtigt. Könnte man nicht vielleicht unsere Teile ins GS Template einbauen?
- [X] 3. Es gab immer einen kleinen Ruck nach oben weil die Mindesthöhe des Popups mittlerweile nicht mehr ausreichte. Vermutlich wegen unseren Ergänzungen. Irgendwann war das zumindest mal nicht so. Das hab ich geändert. 
`ALT: var css = "div.popup_additional_info {min-height:68px;}"`
`NEU: var css = "div.popup_additional_info {min-height:70px;}"`
- [X] 4. Ich hab das Verschieben des Popups oben und rechts und links angepaßt, so dass es nun soweit verschoben wird dass alles sichtbar ist. Das funktioniert auch soweit. Nur wenn sich die Höhe des Popups ändert, weil der Ownername umgebrochen wird rutscht es nicht weit genug nach unten. 
`NEU: css += ".leaflet-popup-content-wrapper, .leaflet-popup-close-button {margin: 16px 3px 0px 13px;}"`
Womöglich würde diese Änderung auch genügen und 2. wäre gar nicht mehr nötig, kann ich aber nicht wirklich beurteilen, weil ich ja das Coding zu 1. bzw. 2. nicht verstehe. ;) 
Oben und links:
![grafik](https://user-images.githubusercontent.com/22332216/41339565-743e2390-6ef5-11e8-806f-e524fb20b925.png)
Oben und rechts:
![grafik](https://user-images.githubusercontent.com/22332216/41339632-9b04826c-6ef5-11e8-89d9-65884f2799cb.png)

**Comment by 2Abendsegler** [comment]
@Ruko2010 

- [ ] 5. Mist. Mir ist gerade aufgefalen dass wir auch die Änderungen von anderen Scripten im Popup Template nicht mehr haben, zumindest teilweise. Send2cgeo ist noch dabei, ist ja auch ganz klein das Script, das war also schneller als wir. GC Tour ist aber nicht mehr mit dabei. Wir sollten also dringend über 2. nachdenken.

**Comment by 2Abendsegler** [comment]
@Ruko2010

- [ ] 6. Prüfen, ob durch einen Umbruch der Zeile mit den Links (Add to list, send to GPS ...) das Popup weiter nach unten geschoben werden muss. Wir wissen wann GC Tour geladen wird wegen Config Parameter. Und GC Tour sorgt auf jedenfall für einen Umbruch. Send2cgeo alleine sorgt nicht für einen Umbruch. Eigentlich müßte man die tatsächliche Höhe des Popups auch abfragen können und dann entsprechend nach unten schieben, oder? Damit wäre dann auch die nicht ausreichende Verschiebung beim Owner Zeilenumbruch beseitigt. 

Irgendwie doch ziemlich aufwendig.

**Comment by Ruko2010** [comment]
Hier die Antworten auf deine Fragen:
1. Ich habe nichts geändert, was die Karte nach unten schiebt, das man GC selbst. Ich habe lediglich das Template für das Popup angepasst, so dass der Platz für unseren Code schon vorher reserviert wird, und dadurch die Karte weiter nach unten rutscht.
2. Ja das sehe ich auch so. ich schau mal ob ich es ändern kann, aber ich denke das wird schon klappen. dann schiebe ich einfach nur unseren Code "dazu" und tausche nicht mehr das komplette Template aus.
3. ok, bei mir war alles mit 68px Ruckelfrei, aber das kann wieder mal an Mac/Windows FF/Chrome usw. liegen.
4. Ich hoffe die Änderung gibt bei kleinen Bildschirmen keine Probleme?
5. Das sollte sich mit den Änderungen aus 2 erledigen. Ich schreib dir wenn ich es umgebaut habe
6. Ich glaube so einfach ist es nicht. Die Höhe des Popups wird zur Anzeigezeit berechnet (wenn ich es richtig sehe). Ich weis nicht, ob zu diesem Zeitpunkt GCTour und Send2cgeo schon geladen sind. Wenn nicht, dann bringt es auch nichts zu bestimmen, ob es einen Umbruch gab oder nicht. Das solltest du prüfen, wenn die Sachen wieder drin sind. Aber an sich können wir daran glaube ich nichts ändern, außer wir spüren die Funktion auf, die direkt die Karte verschiebt und passen da etwas an.

**Comment by Ruko2010** [comment]
Ich habe Punkt 2 erledigt. Kannst du bitte mal testen ob die anderen (früherer) Fehler bei dir noch auftreten (zum Beispiel, die Doppelanzeige) und bitte auch testen, ob nun die anderen Scripte ihre Arbeit noch tun. Den Code findest du hier:
https://github.com/Ruko2010/GClh/blob/feature/map_popup_modifikation/gc_little_helper_II.user.js oder hier https://github.com/Ruko2010/GClh/commit/6358794cc9279db93902ee0db90955bf03f5090b je nachdem was dir lieber ist 😉

**Comment by 2Abendsegler** [comment]
Hab das Script aus dem ersten Link installiert. Der zusätzlich Teil wird bei mir jetzt gar nicht mehr angezeigt.

**Comment by Ruko2010** [comment]
Das ist aber merkwürdig... Ich habe es gerade nochmal funktioniert, und es klappt ohne Probleme. Gibt es denn eine Fehlermeldung in der Console oder so?

**Comment by 2Abendsegler** [comment]
Ich habs nochmal installiert aber der zusätzliche Teil des Popups wird nicht angezeigt. Das Template wird meines Erachtens so nicht geändert. Fehlermeldung gibt es keine und es läuft nur der GClh.
Ich würde ja ins Detail gehen aber ich hab grad gar keine Zeit. Bin schon auf dem Sprung Richtung Urlaub.

**Comment by 2Abendsegler** [comment]
Off Topic: Mir ist gerade aufgefallen dass die Hidden Creatures in 5 Tagen starten. Auf der Seite funktionierte ja das Menü nicht. Falls du in den nächsten Tagen etwas Zeit hast wäre eine neue Version sicherlich nicht schlecht.

**Comment by 2Abendsegler** [comment]
Ja.

Bei den Creatures ist das Notwendige gemacht. Die Twitter Links könnte man noch ausblenden wenn der entsprechende Schalter gesetzt ist, das muß aber nicht sein.

**Comment by Ruko2010** [comment]
Ich schaffe heute das Rollout leider nicht mehr, aber Morgen Abend habe ich Zeit, da mache ich es dann in ruhe.

**Comment by Ruko2010** [comment]
@2Abendsegler um zum Ursprünglichen Problem zurück zu kommen 😃. Bei mir funktioniert die Sache mit dem Anpassen des Templates. Es rutscht auch nichts mehr hoch und das Popup ist voll sichtbar.
Welche weiteren Userscripte nutzt du denn? Eventuell bastelt ja auch eins davon am Popup rum und deswegen ist die Änderung bei dir nicht sichtbar.
Ich würde mir deine anderen Scripte gern installieren um das mal zu testen.

**Comment by 2Abendsegler** [comment]
Wenn ich ehrlich bin weiß ich gerade den Stand nicht.  Sind deine Änderungen mit dem append ans Template schon in 0.9.7?

Ich hatte das Popup gestern kurz getestet. Außer dass der Link zu GC Tour nicht mehr vorhanden ist scheint ja alles in Ordnung. Bzw. Vielleicht gibt es noch Probleme wenn die Linkzeile umbricht.

Die Scripte sind GC Tour (siehe geoclub Greasemonkey Scripte) und send to cgeo (hast du bestimmt selbst).

Der Link zu Send to cgeo ist in der Linkzeile enthalten, nur der zu GC Tour nicht.

LG

**Comment by Ruko2010** [comment]
Ich hab mal Send2cgeo und GC Tour installiert. Beide Scripte werden bei mir auch angezeigt. Aber das Popup rutscht nicht weit genug nach unten wenn beide aktiv sind, da umgebrochen wird.
![image](https://user-images.githubusercontent.com/2239440/41956856-5eb1ce0a-79e5-11e8-9d1d-02c1d0d6fdd3.png)

Man könnte nun der Zeile mit den Links eine feste (minimal) Höhe geben, aber dann sieht das ganze komisch und aufgebläht auf, wenn man diese ganzen "anderen" Scripte nicht installiert hat.

Man müsste mal schauen ob man das Event, dass die Map verschiebt nochmal feuern kann nachdem alles geladen ist.

**Comment by Ruko2010** [comment]
Die Schwierigkeit daran ist nur, das Event/die Funktion zu finden 😉

**Comment by Ruko2010** [comment]
Meine Änderungen mit dem Append sind noch nicht im Collector, sondern bis jetzt nur in meinem Repo in dieser Branch: https://github.com/Ruko2010/GClh/tree/feature/map_popup_modifikation wenn du dir das Script installierst (https://github.com/Ruko2010/GClh/blob/feature/map_popup_modifikation/gc_little_helper_II.user.js) Dann sollte dort das Template nur noch erweitert und nicht mehr ausgetauscht werden (Zeile 6107)

**Comment by Ruko2010** [comment]
Was mir gerade noch auffällt. Es klappt nur beim ersten mal nicht! Beim zweiten Klick auf einen Cache schiebt er die Karte richtig hin. Wahrscheinlich tauscht er das Template nur gegen die neuen Informationen aus, weshalb dann die Größe der Linkleiste schon fest steht und alles klappt.
![kapture 2018-06-27 at 9 09 59](https://user-images.githubusercontent.com/2239440/41958312-f2c31b72-79e9-11e8-8da6-9dc85c9e97bf.gif)

**Comment by 2Abendsegler** [comment]
Wir wissen ob GC Tour läuft anhand eines Config Parameters. Die schnelle und zuerst auch mal ausreichende Lösung, wie ich meine, wäre diesen Parameter abzufragen. Ich schätze es wird auch dann umgebrochen wenn GC Tour läuft und send to cgeo nicht.

Am 27. Juni 2018 08:55:12 MESZ schrieb Ruko2010 <notifications@github.com>:
Ich hab mal Send2cgeo und GC Tour installiert. Beide Scripte werden bei
mir auch angezeigt. Aber das Popup rutscht nicht weit genug nach unten
wenn beide aktiv sind, da umgebrochen wird.
![image](https://user-images.githubusercontent.com/2239440/41956856-5eb1ce0a-79e5-11e8-9d1d-02c1d0d6fdd3.png)

Man könnte nun der Zeile mit den Links eine feste (minimal) Höhe geben,
aber dann sieht das ganze komisch und aufgebläht auf, wenn man diese
ganzen "anderen" Scripte nicht installiert hat.

Man müsste mal schauen ob man das Event, dass die Map verschiebt nochmal
feuern kann nachdem alles geladen ist.

**Comment by Ruko2010** [comment]
Ist dieser Parameter "settings_gc_tour_is_working"? Der sieht aber für mich eher so aus, als ob den der User selbst setzen muss?

**Comment by 2Abendsegler** [comment]
Ja und ja. :)

**Comment by 2Abendsegler** [comment]
Wenn es nur beim ersten Mal nicht klappt sollten wir vielleicht gar nichts machen und anstatt dessen Cachen gehen. ;)

**Comment by Ruko2010** [comment]
😂 das klingt gut. Soll ich meine Änderung mal in den Collector pushen und dann testest du, ob es jetzt bei dir klappt? Oder kannst du es aus meinem Repo installieren?

Ich glaube ein Bug ist noch drin bei der neuen Variante, den muss ich noch Fixen. wenn mehrere Caches "übereinander" liegen, dann kommt die Map Erweiterung mehrfach.

**Comment by 2Abendsegler** [comment]
Wenn du den Bug gefixt hast dann gib einen Link, das reicht.

 

Das kann halt nur etwas dauern weil ich ja Urlaub mache. :)

**Comment by Ruko2010** [comment]
Ok, dann mach ruhig deinen Urlaub. Ich transportiere es in den Collector wenn es geht, dann kannst du es dort testen...

**Comment by 2Abendsegler** [comment]
Mit GC Tour Version 4.8 wurde das Problem mit dem fehlenden Link von Seiten GC Tour berichtigt. 
https://geoclub.de/forum/viewtopic.php?f=117&t=78798&p=1284124#p1284121
Das nur zur Info.

Wenn du den Bug gefixt hast, gib bescheid.
