### ISSUE TITLE
Change souvenirs sort buttons

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#649]
**Describe the solution you'd like**
Die Souvenir Buttons haben bei standard 900 Pixel nicht ausreichend Platz und brechen um. 
![grafik](https://user-images.githubusercontent.com/22332216/39698766-7d5c3be0-51f6-11e8-8d06-5e1368df4eb3.png)
Beim Drüberfahren zeigen sich diese Buttons auch nicht verändert. 

Warum verwenden wir keine Standard Buttons wie wir sie an anderen Stellen auch verwenden?
![grafik](https://user-images.githubusercontent.com/22332216/39698734-55974e60-51f6-11e8-8a16-c8447b9266a0.png)

Ich würde das gerne ändern. Meinungen?

**Comment by Ruko2010** [comment]
Ich bin dafür.

**Comment by 2Abendsegler** [comment]
Wie wollen wir es machen?
1. so
![grafik](https://user-images.githubusercontent.com/22332216/39717180-c165c7e8-5232-11e8-96ad-88532b41f932.png)
2. oder so
![grafik](https://user-images.githubusercontent.com/22332216/39717257-f4f34c66-5232-11e8-8244-b2b4cd928797.png)

Ich bin ja fast immer fürs Geraffte. ;) Also für 2.

**Comment by Ruko2010** [comment]
Ich finde Version 1 sieht besser aus.

**Comment by 2Abendsegler** [comment]
Dann mach ich 1, das wäre ja wohl auch die Wahl von CachingsFoX.

**Comment by 2Abendsegler** [comment]
![grafik](https://user-images.githubusercontent.com/22332216/39753077-df235544-52bd-11e8-92f9-53a529d23f9a.png)

![grafik](https://user-images.githubusercontent.com/22332216/39753134-02d83bbc-52be-11e8-9346-8c35fc0e0555.png)

**Comment by Ruko2010** [comment]
Diese Lösung über die Button finde ich persönlich schöner, da jetzt die Buttons erst disabled sind, bis das Datumsformat bekannt ist. Vorher waren die Buttons nicht da und wurden erst angezeigt, wenn der Request durch war. Macht finde ich mehr sinn 👍.
