### ISSUE TITLE
Reorganization buttons in bookmark lists so it runs to with 900 pixel

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#650]
**Describe the solution you'd like**
Die Buttons auf der Bookmark List Seite sind zu breit für standard 900 Pixel.

![grafik](https://user-images.githubusercontent.com/22332216/39698902-0ea59984-51f7-11e8-8af5-af9226cf373c.png)

Vielleicht könnten wir die Bezeichnung der Buttons etwas schmaler gestalten. :)

Download as kml => Download kml
Mark Caches with Corr. Coords => Mark Corr. Coords

Meinungen?

**Comment by Ruko2010** [comment]
wie wäre es die Button ganz woanders hin zu schieben? in eine neue Ebene zum Beispiel. Bei mir sieht das eh alles etwas "kreuz und quer" aus. Da ändern auch geänderte Namen nichts dran glaube ich:
![image](https://user-images.githubusercontent.com/2239440/39702295-97c3fe38-5204-11e8-9920-19c9b53a01b9.png)

**Comment by 2Abendsegler** [comment]
- Ich erinnere mich dass es bei mir anfänglich auch so verschoben war. Dann sollte man hier nochmal drangehen. Ist das bei dir grundsätzlich so oder nur bei Safari?
Das ist ja das compact layout. Hier gings ja gerade darum möglichst alles zusammenzuraffen. Eine extra Zeile wäre jetzt nicht im Sinne des Erfinders.

- Wollte den Download Link links neben GC setzen und hab dann mal im Standard geschaut wie lange der Name der BML werden kann, hahaha.
![grafik](https://user-images.githubusercontent.com/22332216/39702927-ae76e92c-5206-11e8-830e-a009fe7f4784.png)

- Wir könnten den Download Link ganz nach unten schieben hinter Create PQ, das geht dann auch für 900 Pixel und dein Button bleibt dann auch so erhalten. ;) Also etwa so: 
![grafik](https://user-images.githubusercontent.com/22332216/39703254-cfd1a836-5207-11e8-887d-6fb398a23d33.png)
Ok?

**Comment by 2Abendsegler** [comment]
... und den Download LINK machen wir dann auch als Button, so wie Download to .LOC

**Comment by Ruko2010** [comment]
Ich bin für die variante „download as kml“ nach unten und als Button zu machen

**Comment by Ruko2010** [comment]
ich bin für neben den Copy button, dann ist das alles einheitlich auf einer Ebene

**Comment by 2Abendsegler** [comment]
Ich habs getestet im Compact Layout und ohne, mit und ohne GC Tour, per Aufruf aus neuer BML und aus alter BML, nach Edit der BML, nach Edit BML entry, nach Delete BML entry und nach Add BML entry.

![grafik](https://user-images.githubusercontent.com/22332216/39752987-879a931e-52bd-11e8-9512-375ecbfa35d9.png)
