### ISSUE TITLE
Premium Only-Info im MapPopup anzeigen

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#651]
**Is your feature request related to a problem? Please describe.**
Erweiterung des Map Popups um Anzeige, ob es ein Premium Only Cache ist oder nicht

**Comment by 2Abendsegler** [comment]
http://geoclub.de/forum/viewtopic.php?p=1282935#p1282935
Hab mir gerade mal die Grafik ausm geoclub geschnappt. 

Ich finde man sollte das "Place: In" weglassen, weil ja nicht die gesamte Zeile was mit dem "Place" zu tun hat. Und das "In" ist doch auch nicht notwendig. Es ist doch klar was gemeint ist, finde ich jedenfalls. 

![grafik](https://user-images.githubusercontent.com/22332216/39760542-d7d04758-52d5-11e8-8069-0fd3a4f87a34.png)

Ansonsten, ich hab noch gar nichts erwähnt, finde ich die Erweiterung wirklich klasse. Das Laden geht auch viel schneller als ich angenommen hatte. Und ich hätte das jedenfalls nicht so toll, wenn überhaupt, hinbekommen. Echt super! :)

**Comment by Ruko2010** [comment]
Gute Idee. Ich machs weg.
Wegen dem Icon für Premium. Is das GC related? weist du was? oder muss ich mir selbst eins basteln?

**Comment by 2Abendsegler** [comment]
Ich kenn das Icon von den PQs. Das steht dann zusätzlich in der Spalte der TBs, wenn es ein Premium ist.

**Comment by SDBH-R** [comment]
Ich habe jetzt euer Projekt auch hier bei GitHub gefunden ;-)
Das Icon ist GC-spezifisch. Ich habe da mal einen (relativen) Link aus der Liste meiner [meiner gefundenen Caches](https://www.geocaching.com/seek/nearest.aspx?ul=SDBH-R) rausgeholt: /images/icons/16/premium_only.png
Vielleicht hilft das weiter.

**Comment by Ruko2010** [comment]
@SDBH-R Ja das ist super, damit kann ich Arbeiten. Danke.

**Comment by Ruko2010** [comment]
@2Abendsegler Das "place" kann ich weglassen, aber das "in" kommt leider von der original GC Seite. Problem ist wie immer, dass es nicht in allen Sprachen "In" heißt, sondern auch mal "a" usw. Ich mach das Place also weg, aber das andere lass ich stehen.
