### ISSUE TITLE
Additional linebreaks in cache listing due to changes made by GS 

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#652]
**Describe the bug**
Berechnung von "span-9" ist falsch, dadurch rutsch der Ort für den Cache nach unten (siehe Screenshot)

**To Reproduce**
Einfach ein Cachelisting aufrufen

**Expected behavior**
Ort für den Cache rutscht nicht nach unten

**Screenshots**
![image](https://user-images.githubusercontent.com/2239440/39926107-71df4362-552e-11e8-90d2-fcc0c4254671.png)

**Comment by Ruko2010** [comment]
Kann den Fehler jemand bestätigen, oder ist das bei mir ein Lokales Problem?

**Comment by 2Abendsegler** [comment]
Nach der Anpassung. Wie bei dir mit 1000 Pixel:

![grafik](https://user-images.githubusercontent.com/22332216/39948330-cacb4772-5575-11e8-8e63-4f9f099e6479.png)

**Comment by 2Abendsegler** [comment]
Im Inventory wird auch umgebrochen.

![unbenannt](https://user-images.githubusercontent.com/22332216/39948584-f22dc67c-5576-11e8-937a-c3777a068ab8.JPG)

**Comment by 2Abendsegler** [comment]
Nach der Anpassung:

![grafik](https://user-images.githubusercontent.com/22332216/39948613-1a604340-5577-11e8-8e12-bc9bdf0149bb.png)

Weitere Probleme hab ich jetzt nicht ausmachen können.
Ich schiebe es in den PR.
