### ISSUE TITLE
No button for "Find Caches Along a Route" in compact layout of pocket query lists due to changes made by GS

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#654]
**Describe the bug**
No button for "Find Caches Along a Route" in compact layout of pocket query lists due to changes made by GS.

**To Reproduce**
1. https://www.geocaching.com/pocket/default.aspx

**Expected behavior**
Button

**Screenshots**
![unbenannt](https://user-images.githubusercontent.com/22332216/39951404-e6b92f12-5589-11e8-809b-228e6aa6f9a3.JPG)

**Desktop (please complete the following information):**
 - Win 8.1
 - FF 59.0.2 (64-bit)
 - GClh v0.9.5

**Comment by 2Abendsegler** [comment]
Nach der Anpassung:

![grafik](https://user-images.githubusercontent.com/22332216/39951445-41a3317a-558a-11e8-99b1-c267b0901fe2.png)

**Comment by 2Abendsegler** [comment]
Kann ich nicht nachvollziehen, hab im Chrome nachgesehen, der Button wird bei mir auch dort angezeigt.

Bist du auch im PQ Compact Layout, denn es wird nur dort der Button gesetzt.
![unbenannt](https://user-images.githubusercontent.com/22332216/39987478-34d3c900-5765-11e8-89f5-6c10c0de450b.JPG)

**compact layout in list of pocket queries:**
![grafik](https://user-images.githubusercontent.com/22332216/39987577-765349e6-5765-11e8-89be-3628292cd9b9.png)

**No compact layout in list of pocket queries:**
![grafik](https://user-images.githubusercontent.com/22332216/39987610-8e170e46-5765-11e8-98d5-c63bc39737fe.png)

**Comment by Ruko2010** [comment]
Nein ich hab das Compact Layout nicht an, aber warum gibt es den Button nur im Compact Layout? Der würde doch in beiden Layouts Sinn machen, oder spricht etwas dagegen?

**Comment by 2Abendsegler** [comment]
Erledigt, kommt mit dem nächsten PR bzw. mit der Version.

**Comment by Ruko2010** [comment]
👍
