### ISSUE TITLE
Wrong owner identification on new log page if draft log was empty

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#655]
**Describe the bug**
Beim einfügen eines Templates in einen Draft wird der Tag #owner# mit vip symbol versehen.

**To Reproduce**
Heute habe ich die Entwürfe Funktion mal genutzt, dabei ist mir ein Fehler Aufgefallen. Die automatische Signatur hängt sich nur an wenn in dem Entwurf auch Text steht. Wenn nicht hängt sie sich beim einfügen eines Textes han, aber so:
`Danke an sternchen.07<a href="javascript:void(0);" name="sternchen.07"><img class="gclh_vip" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAKCAYAAAC9vt6cAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sHDhEzBX83tZcAAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAsElEQVQoz6WSsQ2DUAxEz4gdfkdBQQUlDAU9E0ALHQWLsMAfA8o/BNVLkYCS0ETkGstn6+kk2yShPxRLEtxjmJmio8nzXN57SZL3XkVRnEtHNTNlWaZ5nj9AAHRdR9M0ANR1Td/38Iz2UZdlIUmS0zsB67rinGPfd5xzbNt2AUgiTVOmaboCAMqypG1bqqo6ve8E77oAhmEgiiLGcbwHCCEQxzEhhJ8B9hrcPqP9+0gPbh/tf/c8szwAAAAASUVORK5CYII=" title="Add sternchen.07 to VIP-List" border="0"></a> für meinen 3206. [:)]!
Grüße aus Bremen - dem kleinsten aber feinsten Bundesland [;)]`

**Expected behavior**
Kein einfügen des VIP Symbols im Draft

**Screenshots**
![image](https://user-images.githubusercontent.com/2239440/39956006-88ed0918-55d8-11e8-927e-4ef4f79fdd68.png)

**Additional context**
Bericht aus dem Geoclub Forum: https://geoclub.de/forum/viewtopic.php?p=1282987&sid=76a956d6aebdea3cb605f8f60c9c2d02#p1282987

**Comment by 2Abendsegler** [comment]
Der Owner über dem Logtext wurde falsch ausgelesen. Es wurde erwartet, dass die VIP ... Buttons noch nicht vorhanden sind. Getestet mit und ohne Draft Text. Wenn Text leer wird nach wie vor keine Signatur eingestellt, erst wenn man etwas einträgt. Das habe ich so gelassen.
(Läßt sich am einfachsten testen, wenn Draft Text leer ist und man dann auf der neuen Log Page eine Eingabe im Textfeld tätigt. Dadurch springt dann die fehlerhafte Verarbeitung an, hier halt verspätet, weil der Text zuvor leer war.)
