### ISSUE TITLE
Update Overview/Screenshots

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#661]
Ich glaube es ist mal wieder Zeit komplett über diese Seite zu gehen.
Einiges sieht ja jetzt anders aus, und einige Funktionen sind hinzu gekommen.

Es geht um diese Seite: https://github.com/2Abendsegler/GClh/blob/collector/docu/overview_screenshots.md

**Comment by 2Abendsegler** [comment]
Ich habe mal die Teile überarbeitet. Aug bewegte Bilder habe ich verzichtet. Die Änderungen durch den GClh sind nur markiert.
@Ruko2010, @capoaira: Können wir das so lassen?

**Comment by 2Abendsegler** [comment]
Hier noch der Link:
https://github.com/2Abendsegler/GClh/blob/update-overview/docu/overview_screenshots.md

**Comment by Ruko2010** [comment]
Mensch, dass war sicher eine riesige Arbeit, so oft wie meine Uhr eine neue Email angekündigt hat 😃.
Danke, dass du das gemacht hast. Ich finde es sieht sehr gut aus.

**Comment by 2Abendsegler** [comment]
Bekommst du von jedem Commit ne Mail? Ich nicht. Das lässt sich bestimmt einstellen. Das muss ja nervig sein.

Ich musste etliches ausprobieren bis das mit den 3 Punkten (usw) einigermaßen aussah. Und ein Bild wollte sich nicht aktualisieren. Das musste ich deshalb nicht nur hochladen sondern auch vorher löschen.

Danke fürs Feedback. Dann warte ich noch auf Feedback von @capoaira. Ist ja aber nicht dringend.

**Comment by Ruko2010** [comment]
Nicht von jedem, nur bei den Issues, die ich auch selbst erzeugt habe.

**Comment by 2Abendsegler** [comment]
Ok, das ist mal gut zu wissen. Das passiert vermutlich nur dann, wenn man beim commit das Issue mit angibt, was ich für gewöhnlich mache. Da werde ich mal etwas sparsamer mit umgehen. :)

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Ich habe vor etwa 5 Minuten nochmal Bilder mit geändertem Logo hochgeladen. Ich habe dabei keine Issue Nummer im Commit angegeben. Hast du eine Mail vom Commit bekommen?

**Comment by capoaira** [comment]
Ich finde es sieht gut und übersichtlich aus. 👍
Die Searchmap fehlt noch aber ich denke die wolltest du noch hinzufügen sobald alles fertig ist.

> Mensch, dass war sicher eine riesige Arbeit, so oft wie meine Uhr eine neue Email angekündigt hat 😃.

Ich habe gelernt, dass meine Uhr nur bis 25 Zählen kann😂
Ich habe nie wirklich Nachrichten für commits bekommen, Immer nur die für die PRs und alle Nachrichten in Issues. Heute sind mir die commits das erste Mal aufgefallen. 

>Bekommst du von jedem Commit ne Mail? Ich nicht. Das lässt sich bestimmt einstellen. Das muss ja nervig sein.

Den Commit an sich kann man leider nicht ausschalten, zumindest nicht alleine. Entweder bekommt nichts zu den Issues mit, oder mit Commits.

**Comment by 2Abendsegler** [comment]
> Die Searchmap fehlt noch aber ich denke die wolltest du noch hinzufügen sobald alles fertig ist.

Yep.
Es fehlt auch eigentlich noch die Freunde Seite. Das wollte ich mir noch ansehen, ob ich hier noch was zusammenbasteln kann. 

> Heute sind mir die commits das erste Mal aufgefallen.

Das verstehe ich nicht. Du hattest bisher noch gar nicht hier im Issue gestanden, wieso bekommst du dann auch Nachrichten zu den Commits. Dubios.

**Comment by capoaira** [comment]
> Das verstehe ich nicht. Du hattest bisher noch gar nicht hier im Issue gestanden, wieso bekommst du dann auch Nachrichten zu den Commits. Dubios.

Ich habe die repo auf Watch. Eigentlich hatte ich das so eingestellt, um über neue Issues Informiert zu werden. Die Funktion gibt es aber nicht einzeln...
