### ISSUE TITLE
Set black as text color in search field

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [2Abendsegler/GClh#662]
**Describe the bug**
Text, written into the searchfield, may become completely unreadable.

It seems as if the value for the searchfield's text color is taken from config for "Linklist" -> "Font color at menu".  As the background of the menu topics is dark green, one probably configures a brighter color for the topics, to make them more readable.  Unfortunately the background of the searchfield is bright itself - and if it's input text color is the same as the (bright) menu topics color, it's really hard or even impossible to read the written text ...

**To Reproduce**
1. Choose a bright color for "Linklist" -> "Font color at menu", e. g. F0F0F0.
2. Activate "Linklist" -> "Show searchfield"
3. Save config and reload page
4. Input text into searchfield ...

**Expected behavior**
Text put into searchfield should be black, resp. clearly readable.

**Screenshots**
![searchfield](https://user-images.githubusercontent.com/9889015/40030410-562172ce-57e2-11e8-99b1-d16cd720b096.jpg)

**Desktop:**
 - OS: Windows 7
 - Browser: Firefox, v59.0.3 (32-bit)
 - GClh v0.9.6

**Additional context**
This was working one or two versions ago.  Moreover I managed to get black a few days ago, but it was for just an hour or so and I was unable to reproduce it.

**Comment by 2Abendsegler** [comment]
- Done.
![grafik](https://user-images.githubusercontent.com/22332216/40188996-92e58248-59fb-11e8-8280-e09d2602c26c.png)
- Testet for all kind of GC pages.
- Changelog maintained.

**Comment by MagpieFourtyTwo** [comment]
Thanks a lot! You're doing a REALLY great job!  ;)

**Comment by Ruko2010** [comment]
@MagpieFourtyTwo The fix will be rolling out with the new Version 😉
