### ISSUE TITLE
More than one loading area and VIP button on enhanced map popup

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#667]
**Describe the bug**
More than one loading area and VIP button on enhanced map popup.

**To Reproduce**
1. Go to map https://www.geocaching.com/map/
2. Click on cache icon and before loading is complete
3. Click on another cache icon

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22332216/40211113-08afe9e4-5a49-11e8-9c41-92f9cda6dc35.png)

**Desktop (please complete the following information):**
 - Win 8.1
 - FF 59.0.3 (64-bit)
 - GClh v0.9.6

**Comment by Ruko2010** [comment]
Kannst du das irgendwie reproduzieren? Bei mir läuft alles einwandfrei.
Hast du GClh vielleicht 2 mal laufen 😉?

**Comment by Ruko2010** [comment]
Selbst wenn ich wie wild rum klicke (ohne auf das fertigladen zu warten), dann hab ich das Popup nur einmal.
Aber vielleicht ist meine Internetverbindung auch zu gut. ich schau mal ob ich eine langsame Verbindung simulieren kann.

**Comment by Ruko2010** [comment]
Ok, mit simulierter 2G Verbindung kann ich den Bug ein wenig nachstellen (Aber auch nicht immer).
Da ich mir das Popup sowieso nochmal anschauen/überarbeiten will, schau ich mal ob ich da was ändern kann.
Ich will mal die Methode über das direkte Template von @CachingFoX versuchen. Mal schauen ob das geht.

**Comment by 2Abendsegler** [comment]
Ich hab tatsächlich im Moment eine ziemlich langsame Verbindung, das erleichtert das Reproduzieren. Ich bekomme es aber auch nicht immer hin und auch nur doppelt, dreifach geht nicht.

**Comment by 2Abendsegler** [comment]
- Done: Es wird geprüft, ob es die zusätzliche Info zum Cache schon gibt.
`if ($('#popup_additional_info_' + gccode)[0]) return; `
- Tested
- Changelog maintained
