### ISSUE TITLE
Elevation of waypoints with hidden coordinates are shown as +0m

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#670]
**Describe the bug**
The elevation of waypoints with hidden coordinates are shown as '+0m'

**To Reproduce**
1. Open listing [GC37E1T](https://www.geocaching.com/geocache/GC37E1T_funchal-centrum-11-11-11-tb-hotel)
2. Scroll down to 'Additional Waypoints'
3. See waypoint 'Final' - first waypoint
4. See column 'Elevation' (last column)

**Expected behavior**
The elevation of waypoints with hidden coordinates should be shown as 'n/a'. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1838534/40231418-66306286-5a9b-11e8-8462-a4be804542b0.png)

**Desktop**
 - OS: Windows, MacOS
 - Browser: Firefox
 - Version 59.0.2

**Additional context**
- Used elevation service is Open-Elevation
- Version 0.9.6 of GCLH

**Comment by Ruko2010** [comment]
@CachingFoX bei solchen Issues wäre es günstig, wenn du einen Link zu einem Beispiel-Listing mit in die Beschreibung aufnimmst. Auch wenn du das jetzt übernimmst, wenn die Issue nur allgemein erstellt wird, erstell sowas dem Bearbeiter unter Umständen viel Arbeit ;).

**Comment by CachingFoX** [comment]
The bug only occurs with elevation service Open-Elevation. With the Google elevation service 'n/a' is shown.
