### ISSUE TITLE
Show number of acquired souvenirs

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#672]
I want to see the number of the acquired souvenirs. At the '[Your Souvenirs](https://www.geocaching.com/my/souvenirs.aspx#)' page . This should also work on the public profile page (old and new):
- [old public profile](https://www.geocaching.com/profile/?u=UHU15&tab=souvenirs)
- [new public profile](https://www.geocaching.com/p/default.aspx?u=UHU15&tab=souvenirs#profilepanel)

**Describe the solution you'd like**
The number of souvenirs should shown in brackets at the heading "Your Souvenirs" or "Souvenirs" like "Your Souvenirs (123)". A tool tip of the value could explain what the number means.
![grafik](https://user-images.githubusercontent.com/1838534/40232131-e11dad94-5a9d-11e8-9c1c-33f33645a077.png)

**Comment by Ruko2010** [comment]
Der Vorschlag gefällt mir 😃
