### ISSUE TITLE
New Map / Beta Map

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#678]
Groundspeak make tests with a new map - called beta map: https://www.geocaching.com/play/map

At the moment GClh has no effect on this page.

Features:
- Filter results by:
-- types (no groups anymore)
-- Difficulty and terrain (ranges)
-- Size
-- More: Found, Hide, Disabled, Own coordinates, Name, Not Found By, Hidden By, Min FavPoints
- Map Layer Menu is now graphical (Geocaching (OSM-based), Google Road Map, Google Satellite
- Page can called by URL including parameters: https://www.geocaching.com/play/map?lat=32.63333&lng=-16.9&zoom=12&asc=false&sort=favoritepoint&st=Funchal%2C+Madeira
- Caches in the Drafts are marked with an ! as icon
- Caches on the map are shown in a list on the left side. Cache details can be shown
- Layout is corresponding to the smartphone app

**Comment by CachingFoX** [comment]
Some impressions:

![grafik](https://user-images.githubusercontent.com/1838534/40412195-e7a1f4f8-5e72-11e8-80d3-e32e82ccbf87.png)

![grafik](https://user-images.githubusercontent.com/1838534/40412228-f989756a-5e72-11e8-9385-1e152820175b.png)

![grafik](https://user-images.githubusercontent.com/1838534/40412238-04cc3ee4-5e73-11e8-8d32-dea2d79b4f32.png)

**Comment by Ruko2010** [comment]
Ok, dann sollten wir uns überlegen, welche Features wir in der alte Map eingebaut hatten und ob wir diese überhaupt noch brauchen.
Die zweite Frage wäre, ob es sich jetzt schon lohnt hier etwas anzupassen, solange das Feature noch Beta ist.

**Comment by CachingFoX** [comment]
@Ruko2010 Nein vor schnelle Aktivitäten machen keine Sinn. Offiziell ist die Beta Karte noch nicht ausgerollt. Ich denke, GS wird es wie beim letzten Mal mit der Beta Karte machen. Beide Karten werden erst einmal nebeneinander existieren.

Eine Stoffsammlung von Anpassungen wäre aber bestimmt schon einmal nicht schlecht.

**Comment by Ruko2010** [comment]
The new Beta-Map is gone 😃. Let's see if it will be used in production or deleted 😉.
I'll close this one, but leave the storage label for later use.

**Comment by Ruko2010** [comment]
@MagpieFourtyTwo du hast recht, sie ist wieder da, aber nicht für alle Leute. Sie ist immer noch Beta und nun sogar für die meisten Leute komplett verschwunden (nicht mal mehr über den Link abrufbar). Darum waren wir immer noch mit neuen Features. Aber Ideen sammeln ist natürlich nicht verboten ;):

Hier der FAQ Eintrag dazu:
https://www.geocaching.com/help/index.php?pg=kb.chapter&id=105&pgid=917

**Comment by MagpieFourtyTwo** [comment]
Strange - ich habe sie mir mit dem Link 
https://www.geocaching.com/play/map?zoom=11&asc=false&sort=favoritepoint&hf=1&ho=1
ins GClh Menü eingebunden und kann sie völlig problemlos nutzen.

Aber so schön die Karte auch ist, ein grosser Nachteil ist mir inzwischen doch aufgefallen: Durch die Sortierung nach Favos werden einem (auch) in der Karte gar nicht alle Caches angezeigt, sondern z. B. wirklich nur die nach Favos besten 50.  Das war zunächst etwas überraschend, weil so nicht erwartet, und dann deutlich "gewöhnunsbedürftig".  Die alternativen Sortierungen "Oldest" und "Newest" finde ich zudem ziemlich sinnfrei, eine nach Entfernung fehlt komplett.  Da müssten sie für meine Begriffe eh noch nachbessern.

**Comment by Ruko2010** [comment]
Bei mit geht die Karte auch noch. Ich habe aber letztens bei einem Freund gesehen, als ich ihm die Karte zeigen wollte, das er bei Eingabe des Links direkt auf die alte Karte geleitet wurde. Er konnte die also gar nicht erst aufrufen.

Die Begrenzung auf Caches find ich aber auch komisch. Vor allem, dass man nicht sieht, dass es diese Begrenzung gibt. So könnte es sein, dass man neue Caches "übersieht" weil sie einfach nicht angezeigt werden...
