### ISSUE TITLE
Link to found caches in Czechia is missing (Statistics/Map)

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#691]
**Describe the bug**
There is no link to the found caches in Czechia in the country list of the statistics / map side.

**To Reproduce**
1. Go to https://www.geocaching.com/my/statistics.aspx
2. Click on tab 'Map' 
3. Scroll down to Caches You've Found in the World, scroll to Czechia (if exisits)
4. There is no link

**Expected behavior**
Link to the found caches in Czechia by me (in the Advanced Search)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1838534/40585111-48a3b42a-61ad-11e8-8470-8fa3116dbd8a.png)

**Desktop**
 - OS: Windows 7
 - Browser: Firefox
 - Version: 58

**Additional context**
Reason: Czechia is renamed from 'Czech Republic' to 'Czechia' by Groudspeak

**Comment by Ruko2010** [comment]
i have a similar issue. On the list of Caches found in the USA, Geogia gets a Link (I think to "georgien", where I haven't found any caches of cause):

![image](https://user-images.githubusercontent.com/2239440/40589710-9481ddb4-61f2-11e8-8b04-515dd1c8f7b2.png)
