### ISSUE TITLE
Mark more than one Pocket Query for generating without refreshing page for each

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#702]
**Describe the solution you'd like**
Mark more than one Pocket Query for generating without refreshing page for each.

---
- [x] Enhance script
- [x] Test script
- [x] Merge script
- [x] Maintain changelog ...
- [x] Merge changelog ...

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Wie erzeugst du denn deine animierten gifs? :)

**Comment by Ruko2010** [comment]
Also die Checkliste in dem Issue finde ich toll 😃.
Zu deiner Frage. ich nutze Kap (https://getkap.co/), aber das gibt es leider nur für den Mac. das ist wirklich cool. man markiert einfach einen Bereich, drückt auf Record und los gehts. Dann kann man daraus ein Video oder Gif machen in einer Größe wie man will.
Wird dir als Windows User aber nicht viel nützen. Schau mal ob hier vielleicht was nützliches dabei ist: https://www.heise.de/download/products/systemsoftware/bildschirm-recorder#?cat=systemsoftware%2Fbildschirm-recorder

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Ich bekomme das nicht so schön hin wie du, aber ich hab was gemacht. Sieht irgendwie dreckig aus, das gif. Vielleicht find ich noch was anderes. Ich mach hier aber trotzdem zu.

**Comment by Ruko2010** [comment]
Du hast recht, die Qualität des gifs ist nicht so toll, aber die Funktion dafür umso mehr 😉.
