### ISSUE TITLE
Problem mit mehreren Scripts

### ISSUE THREAD

**Issue by Cappa-d** [2Abendsegler/GClh#71]
Ich habe jetzt mehrere Dinge ausgetestet, aber bisher finde ich keine Lösung. 

In meinem Browser sind mehrere Skripte installiert und bisher war es nie ein Problem. Allerdings scheitert es zusammen mit GClh. Haben andere den Fall auch?

Installierte Skripts (Ausführungsreihenfolge - wenn alle aktiviert sind):

- GClh (1)
- GCComment (2)
- GCVote (3) -- zu 99 % aus auf Grund der Probleme

Sind alle drei aktiviert, dann steigt GCComment aus. Ändere ich die Reihenfolge macht ein anderes Skript Probleme. Ist GClh deaktiviert gehen die beiden anderen zusammen.

Genutzter Browser: FF 50.1.0
Greasemonkey 3.9
GClh 0.2.2.4
GCComment 90
GC-Vote

**Comment by 2Abendsegler** [comment]
Im geoclub Forum gepostet.
https://geoclub.de/forum/viewtopic.php?f=117&t=79383&p=1263982#p1263981
