### ISSUE TITLE
Updating names of countries

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#722]
The name of some countries have been changed.

**Changes**
* Czech **Republic** -> Czech*ia* (already changed with issue #691)
* British Indian Ocean Territories -> British Indian Ocean Territor**y**
* Cape Verde -> Ca**bo** Verde
* Ivory Coast -> Côte d'Ivoire
* French Southern Territories ->French Southern **and Antarctic** Territories 
* Heard Island And Mcdonald Islands -> Heard Island *a*nd Mc**D**onald Islands
* Macau -> Maca**o**
* Pitcairn **Islands** -> Pitcairn
* Reunion -> R**é**union
* South Georgia and Sandwich Islands -> South Georgia and **the South** Sandwich Islands
* St Barthelemy -> S**ain**t Barthélemy
* St Pierre Miquelon -> S**ain**t Pierre **and** Miquelon
* St Vince Grenadines -> S**ain**t Vincent **and the** Grenadines
* Svalbard and Jan Mayen -> Svalbard and Jan Mayen **Islands**
* Wallis And Futuna Islands -> Wallis **a**nd Futuna Islands
* East Timor -> Timor-Leste

**Comment by Ruko2010** [comment]
@CachingFox müssen wir hier noch mehr machen? Oder sind die Änderungen aus dem update schon in deinen Änderungen enthalten: https://forums.geocaching.com/GC/index.php?/topic/348956-release-notes-website-region-names-july-2-2018/

**Comment by CachingFoX** [comment]
Das muss ich mir mal ansehen. Sark kommt mir unbekannt vor.

**Comment by CachingFoX** [comment]
Hier gibt es leider noch einmal Handlungsbedarf. Ich habe ein Skript geschrieben, welches automatisch die benötigten Listen aus der PQ Seite erzeugt. Dies wäre schon vor 14 Tagen hilfreich gewesen. Ich werde die notwendigen Anpassungen heute oder morgen einchecken.

**Comment by Ruko2010** [comment]
Super, Danke. Ich habs leider nicht eher gesehen 😉. War erst in einer Resleasenote im GC Forum

**Comment by CachingFoX** [comment]
Kein Ding. Die Änderung waren letztes Mal auch noch nicht vorhanden. Mit dem Skript sollte zukünftig solche Änderung sehr einfach machbar sein. Ich stelle die Änderung und das Skript heute Abend noch bereit.

**Comment by Ruko2010** [comment]
👍
