### ISSUE TITLE
Freundesliga: Nach klick auf "See more" haben die neuen Freunde keine VIP Icons

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#734]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2239440/42093905-4835afd2-7bae-11e8-98cb-2884c2178673.png)

**To Reproduce**
1. Go to https://www.geocaching.com/play/friendleague
2. Click on 'See more'

**Expected behavior**
Neu angezeigte Freunde sollten ein VIP Icon haben.

**Comment by 2Abendsegler** [comment]
Ich hab zu wenig Freunde, bis dahin bin ich nie gekommen. :)

**Comment by Ruko2010** [comment]
Dann muss ich das ja übernehmen 😃
