### ISSUE TITLE
GClh didn't work in Firefox 61.0.1

### ISSUE THREAD

**Issue by stepborc** [2Abendsegler/GClh#744]
**Describe the bug**
Open geocaching.com with acivated Tampermonkey (including GClh) didn't start the script.

**To Reproduce**
1. Open Firefox with https://www.geocaching.com/my/default.aspx

**Desktop (please complete the following information):**
 - MacOS, Linux
 - firefox
 - Version 61.0.1

**Comment by stepborc** [comment]
Hi Ruko2010,

I opened the Console. The the attached screenshot.
![deepinbildschirmfoto_bereich auswahlen_20180724091547](https://user-images.githubusercontent.com/8976718/43122693-3d6d43b2-8f22-11e8-8f53-acdbc317c1e6.png)

**Comment by stepborc** [comment]
On my Linux with Firefox Desktop I tried your solution. Yes it works. I'll will try later on the Mac Installation.

**Comment by Ruko2010** [comment]
We have some Users reporting this problem, but it seams to be related with Tampermonkey and not GClh. In this cases it is importent to have a backup of your Configuration. So you can just reinstall everything 😉
