### ISSUE TITLE
Logs nachladen ohne Funktion

### ISSUE THREAD

**Issue by arbor95** [2Abendsegler/GClh#745]
**Describe the bug**
Logs nachladen geht nicht

**To Reproduce**
1. Go to 'https://www.geocaching.com/geocache/GC1HJHK_55' or another cache with enough logs
2. Click on 'Scrollbar'
3. Scroll down to 'end of page'
4. Should see publish log

**Expected behavior**
if you scroll down enough , you should the publish log.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: [W10
 - Browser [chrome
 - Version [68.0.3440.84 (Offizieller Build) (64-Bit)

**Additional context**
all other scripts deactivated.

**Comment by 2Abendsegler** [comment]
@arbor95 
Thanks for the message!

@Ruko2010 
![grafik](https://user-images.githubusercontent.com/22332216/43861519-60b54bda-9b57-11e8-9f14-c65534ec02f8.png)
VIPs werden entsprechend auch nicht mehr aufgebaut. Bei Button "Show all logs" werden zwar die Logs alle aufgebaut, aber es wird nicht alles richtig dargestellt. Zumindest ist das aber ein Workaround.
Das ist ein Prio high, oder? Ich setz es, ändere es bitte wieder ab, falls du es anders beurteilst. Kannst du das übernehmen?

@arbor95 
Workaround: Please use the button "Show all logs".

**Comment by Ruko2010** [comment]
Ja Prio High ist völlig in Ordnung.
Auch das schau ich mir heute Abend an.
Ich denke das es irgendwie die Funktion "endlessScroll" nicht mehr gibt. Eventuell hatte GC da was eingebunden was nun weg ist. Ich schau mal, ob es reicht wenn wir diese jQuery Erweiterung über unser Script mit einbinden.

**Comment by Ruko2010** [comment]
Ich habe versucht das "endlessScroll" script manuell hinzuzufügen aber das scheint nicht zu klappen. @2Abendsegler @CachingFoX hat jemand eine Idee wie man die Funktion ersetzen könnte?

**Comment by Ruko2010** [comment]
Ich glaube ich weis auch, warum es nicht geht. Wenn ich es richtig sehe, dann wird die Funktion endlessScroll nicht bei uns im Script aufgerufen, sondern direkt auf der GC Seite (über unsafeWindow.$(window).endlessScroll). Wenn ich nun also das Endless Scroll Script bei uns über ein @require hinuzufüge, dann ist es ja nur im GClh sichtbar, aber nicht für code, der direkt auf der GC-Seite ausgeführt wird.

**Comment by Ruko2010** [comment]
Scheint doch nicht richtig zu gehen...ich sehe gerade, dass es den gleichen Effekt hat, wenn man den ganzen Block einfach auskommentiert...^^
Wahrscheinlich hat GC seine Funktion zum Nachladen der Logs umgestellt. Wenn jemand gern mitmachen möchte, sei er herzlich willkommen 😉

**Comment by 2Abendsegler** [comment]
Hab noch 10 min Internet, dann erst gegen So Abend wieder. Kann im Moment nicht mit einsteigen.

**Comment by Ruko2010** [comment]
Ich hab jetzt das EndlessScroll Script über Inject auf die GC Seite mit eingebracht, aber da ist immer noch was quer :/
Ich schau mir das heute Abend weiter an. Aktueller Stand ist bei mir im Repo.

**Comment by Ruko2010** [comment]
Ich weis noch nicht genau wann ich heute Abend zu Hause bin, aber ich würde mich dann gleich nochmal damit beschäftigen. Ansonsten hätte ich noch einen Hotfix:
- das EndlessScroll raus nehmen (logs werden dann aber nicht mehr nachgeladen beim Scrollen nach unten 😔)
- das hier dafür einbauen (sehr unschön, aber das Script würde erstmal keine Fehler mehr werfen und man kann trotzdem alle Logs anzeigen lassen):

![image](https://user-images.githubusercontent.com/2239440/43960383-2384f970-9cb2-11e8-8e8b-3a826c6b02d7.png)

@2Abendsegler wenn du damit einverstanden bist bring ich heute Abend eine neue Version raus. Entweder mit dem richtigen Fix (wenn ich es bis dahin hin bekomme), wenn nicht, mit dem (hässlichen) Hotfix. Aktueller Stand mit Hotfix ist in meinem Repo: https://github.com/Ruko2010/GClh/tree/bug/issue-745

**Comment by Ruko2010** [comment]
Ich habe jetzt die Komplette Funktion umgebaut und selbst ein "endless Scroll" implementiert. Der aktuelle Stand ist in meinem Repo: https://github.com/Ruko2010/GClh/tree/bug/issue-745

Das einzige Problem, dass ich noch habe ist, dass GC beim "runterscrollen" ja auch versucht die Logs nachzuladen. Ich schau mal, ob ich das noch abschalten kann, denn sonst kommt immer der Loader, obwohl man die Logs von GC ja nicht mehr braucht.

Ich muss das Script auch noch in den verschiedenen Browsern testen. @2Abendsegler @CachingFoX falls ihr Zeit/Lust habt, könnt ihr es ja auch bei euch mal ausprobieren.

**Comment by 2Abendsegler** [comment]
Moin, bin erst jetzt wieder online, sorry.

Das Coding kann meines Erachtens entfernt werden.

if (isTM === false)
{ // Do something }
else
{ // do something else }

**Comment by Ruko2010** [comment]
Hmm...sieht komisch aus...ja ich schau rein. Danke fürs drüber schauen.

**Comment by Ruko2010** [comment]
Ich hab mal mein Script auf Version 0.9.9 zurück gesetzt, da war der Fehler auch schon. Den Button sollte man also nur einmal drücken (dürfen) 😉. Das einfachste wäre glaube ich, ihn deaktiviert zu lassen, wenn der Reload der Logs fertig ist, und ihn nicht wieder zu aktivieren. Dann kann der User ihn nicht nochmal drücken.

**Comment by 2Abendsegler** [comment]
Das wär aber nicht richtig. Der Button soll mehrfach nutzbar sein, war er ja auch mal. Damit ich zwischen verschiedenen Selektionen wechseln kann. Also beispielsweise die Logs der VIPs, der founds, alle, der not found, alle ... :)
Wir können ja auch ein neues Ticket aufmachen.

**Comment by Ruko2010** [comment]
Ah ok, ich dachte der lädt immer alle Logs. Ja dann mach am besten ein neues Ticket auf.

**Comment by 2Abendsegler** [comment]
Der Button läd ja auch immer alle Logs. Aber ich kann nebendran auf die VIPs drücken um nur die zu sehen, dann wieder auf den Button um alle zu sehen ...
Ich mach mal ein Ticket auf.

**Comment by Ruko2010** [comment]
Ich glaube da ist noch etwas mehr im Argen. Auch der Wechsel zwischen den Sektions geht nicht mehr richtig. Nach dem ersten Wechsel kommt dann ein Fehler.
