### ISSUE TITLE
Alert if gclh_error is called (only in developer mode)

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#752]
As a developer of GClh I use the script often like a normal user; without an open console. If a critical error (function gclh_error is called) occurs I don't see it. Often I don't recognize if a feature is damaged.

If an error is shown more incisively I would helps to recognize a problem with GClh earlier.

I could be looks like the Guru Mediation at Amiga machines, a red bounded box at the top of the screen. (no blink!)

![grafik](https://user-images.githubusercontent.com/1838534/43995545-5e955098-9daf-11e8-94b7-385e88468344.png)

The alert should only be shown for developers or person who are interested. The alert should only be shown to users which are enable the developer mode (a new option at settings). The developer mode option is disabled by default.

The alert should include the error messages of all occurred errors. The stacktrace is still available at the console.

**Comment by Ruko2010** [comment]
I think this is a great Idea. I would use another name for the config switch. Maybe other users will support us on tracking bugs. Maybe we can call it supporterMode or BugFinderMode or something else. 

Do you have an implementation in mind?

**Comment by CachingFoX** [comment]
I have a prototype of the implementation. I will uploaded at my repo clone. The implemenation based on v0.9.9. I will updated it to v0.9.10 as soon as possible.

My idear was to create a switch which can be used for other features which are only relevant for developers. But I if you suggest a single option for a single feature it will be okay.

**Comment by CachingFoX** [comment]
At the current implementation the name of the option is still 'Developer Mode' and can be found under *GClh Config / Sync* > *Activate the developer mode*.

**Comment by CachingFoX** [comment]
I merge the version v0.9.10 into the feature branch.

**Known issues**
The function is not really thread-safe. If two threads entered the `gclh_error()` at the first time, two elements will be created. But I think this is a low risk.

**Comment by Ruko2010** [comment]
If you plan the add more options for developers, maybe we create a new Config Section "developer" and place the new configs there. Maybe it should be a bit smaller than then the "regular" options.
I'll look into the new feature soon

**Comment by CachingFoX** [comment]
Yes, I can do it. I will prefer the name "Development" (because we do not configure the developer). Where should I locate the new section. At the end of the settings, after GClh Config / Sync, create a subsection of GClh Config / Sync?

**Comment by Ruko2010** [comment]
I would place it at the end of the settings under "Linklist / Navigation". @2Abendsegler your thoughts?
You can create a new point "Development" and there a subpoint.

**Comment by CachingFoX** [comment]
Add new section 'Development' at the end of the Config Dialog. Remove option from GClh config section. 
Name of the new option: "Show an alert if an internal error occurs" (internal name: settings_gclherror_alert)

**Comment by 2Abendsegler** [comment]
@CachingFoX 
Ich habs schon an anderer Stelle geschrieben, wollte aber nicht dass du es übersiehst. Also nochmal ...
**Die Anzeige der Errors ist echt super!** :)

(Off-Topic: Es reicht wenn du Ruko2010 als Reviewer anforderst, er hat das Zepter. ;) )

**Comment by CachingFoX** [comment]
@2Abendsegler Danke :-) -- Ich habe mich von der guten alten Guru Meditation vom Amiga inspirieren lassen. :-)
