### ISSUE TITLE
Logs with Many Pictures: Picture container floats out of viewport

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#754]
**Describe the bug**
When you add many pictures to a log, the picturecontainer floats out of the viewport

**To Reproduce**
1. Go to https://www.geocaching.com/geocache/GC4AB38_the-j-files-v-odyssissi
2. Scroll down to Log of "The Ranis Boys"

**Expected behavior**
Picture Container has a maxwidth of the surrounding countainer and pictures get a second (or more) row.

**Screenshots**
![image](https://user-images.githubusercontent.com/2239440/44017909-55345a36-9eda-11e8-900f-2adf5e9e9dba.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome
 - Version: 68.0.3440.106 (Offizieller Build) (64-Bit)

**Comment by Ruko2010** [comment]
Since this is a design issue, i'll like to here your ideas on my fix @2Abendsegler 
I removed the table surrounding the pictures and added some space between them:

![image](https://user-images.githubusercontent.com/2239440/44029509-dc5b79ae-9efd-11e8-8b07-ff69906314fe.png)

**Comment by Ruko2010** [comment]
The fix is in my Repo: https://github.com/Ruko2010/GClh/tree/bug/issue-754-picsoverflow

**Comment by 2Abendsegler** [comment]
Ich hab das hier auch gleich mitgemacht. GS hat hier die Aufbereitung der Table geändert. 
PR #758 Wait for merge

**Comment by 2Abendsegler** [comment]
Ich hatte nicht reingeschaut ob du schon was gemacht hast. Schaus dir bitte an. Wenn deins besser paßt, dann schmeiß meine beiden Zeilen beginnend mit css ... wieder raus. :)
