### ISSUE TITLE
Preview of Pictures in Logs throws Error

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#755]
**Describe the bug**
If you hover over a small picture in the logs, an error is thrown in the console.

**To Reproduce**
1. Go to https://www.geocaching.com/geocache/GC4AB38_the-j-files-v-odyssissi
2. Scroll down to a log with pictures.
3. Hover over a picture to enlarge it
4. Go to the console and see the error:
![image](https://user-images.githubusercontent.com/2239440/44018107-00d55070-9edb-11e8-8eab-a22927d7d054.png)

**Expected behavior**
No Error in the console.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68.0.3440.106 (Offizieller Build) (64-Bit)

**Comment by Ruko2010** [comment]
Problem is in the following function (around line 5559):
![image](https://user-images.githubusercontent.com/2239440/44032502-9085bfb2-9f07-11e8-9a8b-a05a32ddf449.png)

if you comment outthe last part
![image](https://user-images.githubusercontent.com/2239440/44032515-9b495cf6-9f07-11e8-8c7b-d4ca79355072.png)

everything works fine. I'm not sure why this function is called a second time.

**Comment by Ruko2010** [comment]
Ok, I found it 😃. jQuery has two functions `load()`. One that reloads Data and inserts it into the html element, and one, which is a shorthand for `.on( "load", handler )`, weired.

Maybe jQuery confuses these two. So if I change the shorthand with the full function it works fine.

**Comment by Ruko2010** [comment]
Now the Thumbs on the Listing page throw an error :/.
I'll look into this again.

**Comment by Ruko2010** [comment]
Again, removing the second part fixes the error, but I'm not sure what it may be breaking.

**Comment by Ruko2010** [comment]
@2Abendsegler any idea?

**Comment by 2Abendsegler** [comment]
PR #758 Wait for merge
