### ISSUE TITLE
Button Show all logs and other sections do not work

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#761]
**Describe the bug**
Wenn der Button Show all logs einmal gedrückt wurde gibt es bei einem erneuten drücken des Buttons oder einer anderen Section eine Fehlermeldung wie folgt:
![grafik](https://user-images.githubusercontent.com/22332216/44141328-1d2767d8-a07d-11e8-9430-729fb00f87fe.png)

**To Reproduce**
1. Go to a Listing for example https://www.geocaching.com/geocache/GC4AB38_the-j-files-v-odyssissi
2. Click on Button Show all logs
3. Click again on Button Show all logs or on an other section Button (VIPs, founds ...)
4. See error in console

**Desktop (please complete the following information):**
 - Windows
 - FF
 - 61.0.1 (64-Bit)

**Comment by Ruko2010** [comment]
Also ich denke irgendwas ist da komplett defekt!
Ich habe im alten Code mal ein paar Logausgaben hinzugefügt (function gclh_filter(logs)):
`var tbodys = (document.getElementById("cache_logs_table2") || document.getElementById("cache_logs_table")).getElementsByTagName("tbody");
                    console.log((document.getElementById("cache_logs_table2") || document.getElementById("cache_logs_table")));
                    console.log(tbodys);`

In Ausgabe 1 wird die "cache_logs_table2" zurück gegeben, soweit so gut. Nun gehe ich zu folgendem Cache: https://www.geocaching.com/geocache/GC1BANR_jenaer-unterwelt-2
und klicke auf die DNF-Logs um die zu filtern. Es werden Keine tbodys gefunden. Klicke ich nun auf die "Find-logs" (das dauert kurz, denn es sind 800 Funde 😉) werden knapp 70 tbodys gefunden. Das sind aber nicht die Logs an sich, sondern die Tabellen, die für die Bilder aufgebaut werden.

Ich denke GS hat hier gravierend was geändert und die Funktion findet leider nicht mehr die Zeilen aus der Tabelle um sie zu löschen.

Was ich aber nicht verstehe ist, dass unsere Funktion, die die neuen Logs hinzufügt, dass eigentlich auch über einen tbody macht. Aber in der cache_logs_table2 gibt es keine tbodys für die logs. Ich versteh das nicht...

**Comment by 2Abendsegler** [comment]
Ich versuche mich mal daran.

**Comment by 2Abendsegler** [comment]
Der Button show all logs und die Sections funktionieren wieder. Das Löschen der vorhandenen Logs wird nun anders durchgeführt. Soweit so gut. 

Andere Dinge funktionieren aber nicht korrekt:
- Logs Loading beim Scrollen wird nicht gestoppt. Ich habe versucht das zu korrigieren, ich verstehe aber vieles im gclh_dynamic_load nicht und ich hab aufgegeben. Dazu mache ich ein neues Ticket auf.
- Logs Loading durch GS wird nicht mehr gestoppt. Die function disablePageAutoScroll funktioniert meines Erachtens nicht mehr. Das führt auch zu dem Effekt, dass Logs im neuen template nachgeladen werden, obwohl wir mit dem gclh noch garnicht so weit sind. Das ist Bestandteil von #792. 
- Zum besseren Verständnis müßten zahlreiche Dinge geändert werden, inbesondere der ganze TBODY Kram der völlig verwirrend ist. Das wäre aber so viel, dass ich nicht mehr sicherstellen kann dass noch alles wie gewohnt funktioniert. Ich hatte schon begonnen, habs aber wieder zurückgedreht.
- Und schon wieder wurde von GS an dem Output der Bilder in den Logs geändert, nun das dritte Mal in kurzer Zeit. Das ist so nervig. Ich lass das jetzt so, das ist nicht schlimm.
