### ISSUE TITLE
Refactor helper functions

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#772]
The GClh script has a lot of thin helper functions. There is no specific section for these helper functions. Some functions are in a function context, some function are global, some are located at the end of the file, some functions are located in the middle of the script, ....

Some examples:
- roundTO
- lat2tile(lat,zoom)
- long2tile(lon,zoom) 
- tile2long(x,z)
- tile2lat(y,z)
- DegtoDMS
- DectoDeg
- toDec
- trim
- html_to_str
- decode_innerHTML
- urldecode
- urlencode
- caseInsensitiveSort
- in_array
- ....

**Possible actions**
- make nested helper functions global
- move helper functions in an extra file
- find duplicates or unify similar functions
- generate an overview of all functions

**Comment by Ruko2010** [comment]
I think we should refactor this step by step, and not all in once to reduce errors and side effects.

**Comment by 2Abendsegler** [comment]
Do not change a running system ... 
ohne Not
:)

**Comment by 2Abendsegler** [comment]
Kleinigkeiten sind bereits hier erfolgt: #1310

**Comment by 2Abendsegler** [comment]
Ich habe alle benannten Functions und ein paar wenige zusätzlich in einem eigenen Bereich zusammengefasst. Ich habe immer eine Function nach der anderen irgendwo weggenommen und sie dann wieder an anderer Stelle eingefügt. Schon deshalb ist es ziemlich sicher, dass keine verschwunden ist. Der eigene Bereich ist am Ende der Verarbeitung zu den geocaching Seiten, noch im mainGC. Auch deshalb dürfte es keine Probleme geben.

Zusätzlich gibt es noch den globalen Bereich mit den wenigen Functions die auch außerhalb der geocaching Seiten verwendet werden. Dieser Bereich wurde nicht erweitert. Wenn wir dort etwas benötigen, dann kann man sich in der Sammlung zu den GC Seiten bedienen und die Function dorthin verschieben.

Ich habe die Überschriften im Programm überarbeitet wie folgt:
```
// 1. Declaration, Init, Start ($$cap)
// 2. Google Maps ($$cap)
// 3. Project GC ($$cap)
// 4. Openstreetmap ($$cap)
// 5. GC asynchron ($$cap)
// 6. GC ($$cap) (For the geocaching webpages.)
// 6.1 GC - Main ($$cap) (For the geocaching webpages.)
// 6.2 GC - Functions ($$cap) (Functions for the geocaching webpages.)
// 6.3 GC - User defined searchs ($$cap) (User defined searchs on the geocaching webpages.)
// 6.4 GC - Find Player ($$cap) (Find Player on the geocaching webpages.)
// 6.5 Config ($$cap) (GClh Config on the geocaching webpages.)
// 6.5.1 Config - Main ($$cap) (GClh Config on the geocaching webpages.)
// 6.5.2 Config - Functions ($$cap) (Functions for GClh Config on the geocaching webpages.)
// 6.5.3 Config - Reset ($$cap) (Functions for GClh Config Reset on the geocaching webpages.)
// 6.5.4 Config - Sync ($$cap) (Functions for GClh Config Sync on the geocaching webpages.)
// 6.6. GC - General Functions ($$cap) (Functions generally usable on geocaching webpages.)
// 7. Global Functions ($$cap) (Functions global usable.)
```
Die Programmteile sind nicht hierarchisch wie die Überschriften, die Programmteile wurden nicht verändert. Die Überschriften wurden sinngemäß gebildet. Die Programmteile im Config Bereich wurden also nicht weiter untergliedert, nur die Überschriften, die die Themen sinngemäß abbilden. 

Die neue Sammlung der allgemein verwendbaren Funktions ist 6.6 GC - General Functions.
Die kleine bereits vorhandene globale Sammlung ist 7. Global Functions.

Anhand der von GitHub angezeigten Änderungen lässt sich das ganze nur schwer überschauen, weil GitHub hier vieles etwas durcheinander anzeigt. Ich schlage vor, dass wir das Script alle aufspielen und damit unsere tägliche Geocaching "Arbeit" machen. Das sind dann schon mal viele Tests. Ich habe schon ziemlich viel getestet, werde aber noch weitermachen. Die Änderungen befinden sich bereits im collector.

@Ruko2010, @capoaira und andere:
Wollen wir mit dem Testen so vorgehen?
Gibt es Anmerkungen, Verbesserungsvorschläge?

**Comment by Ruko2010** [comment]
Klasse! War sicher eine Menge Arbeit. Ich lade mir eh meist den aktuellen Collector für die tägliche Arbeit, also für mich kein Problem.

**Comment by capoaira** [comment]
Wow, das sieht nach echt viel Arbeit aus. Ich nutze auch meistens den Collector.

**Comment by 2Abendsegler** [comment]
```
	<li>
		<strong>New:</strong> Refactor helper functions. [<a href="https://github.com/2Abendsegler/GClh/issues/772" title="Issue 772">772</a> / <a href="https://www.geocaching.com/profile/?u=2Abendsegler" title="Thanks to 2Abendsegler">2Abendsegler</a>]<br><br>
	</li>

```
