### ISSUE TITLE
On Paste in Log, Signature is added also if the pasted log contains the signature

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#776]
**Describe the bug**
If you past a text for a log and have enabled a signature, the signature is added to the log (via GClh), also if the pasted text contains the signature. This should be avoided.

**To Reproduce**
1. Go to new logging page
2. Insert a Text in the Logging Field, that already contains your signature
3. See that the signature is now twice in the log

**Expected behavior**
If pasted text (or the textfield itself, maybe from a draft or something) contains the signature, do not add it again.

**Screenshots**
![kapture 2018-08-21 at 13 45 54](https://user-images.githubusercontent.com/2239440/44399698-c8ce6d00-a548-11e8-8c52-2f143df4c8b9.gif)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome

**Comment by 2Abendsegler** [comment]
Ich glaube wenn bei den Drafts die Signatur schon gesetzt werden soll, das ist ja ein Parameter, dann wird sie nicht nochmal auf der Logseite gesetzt. 

Es wird für einige Sekunden immer wieder geprüft ob das Log leer ist, gegebenenfalls wird die Signatur gesetzt. Wenn also das Log auf der Logseite geleert wird, dann wird die Signatur deshalb erneut gesetzt. Von GS wird zeitverzögert das Log geleert, so dass die bereits von uns eingestellte Signatur wieder gelöscht wird. Das nur zum Hintergrund und vielleicht zum besseren Verständnis für die entsprechend entwickelte Wiederholung des Einbaus der Signatur.
