### ISSUE TITLE
Refactoring: Waypoint handling (elevation, link to FloppsMap, BRouter)

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#777]
The waypoint information for feature elevation, FloppsMap, BRouter are extract from the HTML page. There are two separate functions: one for elevation and one for FloppsMap and BRouter link.

The current functions use human readable text (or name of images) to identify different types of waypoints from the waypoint table. These texts can be changed by Groudspeak (see #771) and after that the feature is broken. There are two way to extract the listing and the original listing coordinates. 

For feature FloppsMap and BRouter link there a separate functions with very similar code (code duplication)

GS move the waypoint edit page from a dedicated page (www.geocaching.com/hide/wptlist.aspx) into the normal listing edit page. Modification/processing for Elevation, link to FloppsMap and BRouter for this page can be removed.

Idea: Every listing page includes an JavaScript object which includes all information about waypoints. These structure can be used instead of extracting the data from HTML code. The structure includes additional information like waypoint type (id).

Benefit of the refactoring:
- reduce code (remove duplicate)
- remove bugs
- waypoint handling will be robuster 
- remove dead code
- include additional external services like FloppsMap will be easier

**Comment by Ruko2010** [comment]
I agree. I'm also using the extra Javascript Objects in the Additional-MapPopup to get the last 25 logs.

**Comment by CachingFoX** [comment]
Change way of waypoint data collection. The next changes will be refactor the function to build links to both map services FloppsMap and BRouter.

**Comment by CachingFoX** [comment]
### Improve center of map for BRouter

**Current center and zoom**
![grafik](https://user-images.githubusercontent.com/1838534/44568951-16312100-a779-11e8-8d2c-b9cc47958260.png)

**Better: Route doesn't under map controls** (zoom level is only changed)
![grafik](https://user-images.githubusercontent.com/1838534/44568960-20ebb600-a779-11e8-94d0-ea1dedc8d720.png)

**Route is center at the free area of the map** (zoom level is changed and center is shifted)
![grafik](https://user-images.githubusercontent.com/1838534/44568992-3d87ee00-a779-11e8-9cff-07316aa996d3.png)

**Comment by CachingFoX** [comment]
### Remote API for GPSVisualizer
http://www.gpsvisualizer.com/map_input?special=wikipedia&format=google&bg_map=google_map&sp_width=50km&google_zoom_level=8&google_wpt_labels=1&form:data=name,latitude,longitude%0D%22Geocaching%22,50.368611,12.913611

**seen by** 
https://tools.wmflabs.org/geohack/geohack.php?pagename=Geocaching&params=50_22_7_N_12_54_49_E

**Comment by CachingFoX** [comment]
The refactoring is finished. 

In the future the zoom level and center calculation have to be adapted for two scenarios:
* non full-screen maps
* full-screen maps with transparent overlays (left and right side)
