### ISSUE TITLE
Describe how one can install GClh on android.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#783]
Beschreiben wie man GClh unter Android installieren kann.

Wir wollen Android zwar nicht supporten, wir könnten aber trotzdem einen Weg beschreiben wie man den GClh unter Android installieren kann. Ich teste seit einigen Tagen den GClh auf einem S8+ mit Android 8. Das macht zwar nur eingeschränkt Sinn weil der Bildschirm trotzdem zu klein ist, aber es geht hier ja auch nur um grundlegende Tests und eine Analyse wie man ihn unter Android zum Laufen bringt. 

Wo könnten wir die Informationen unterbringen? In den [FAQs](https://github.com/2Abendsegler/GClh/blob/master/docu/faq.md)?
Ich weiß nicht ob wir es unter den [Installationtipps](https://github.com/2Abendsegler/GClh/blob/master/docu/tips_installation.md#de) machen sollten, weil wir den GClh unter Android wohl nicht supporten wollen, zumindest ist das im Moment meine Meinung.

Was meint ihr?

**Comment by Ruko2010** [comment]
Ich würde einfach in den Installationstipps ganz unten (in der jeweiligen Sprache) eine Sektion machen "Experimental" oder so ähnlich. Dann schreibst du, dass wir es zwar nicht supporten, und das nicht alle Funktionen klappen werden (z.B.: dropbox?) aber das es jemand gern ausprobieren kann. In die FAQ Kannst du dann Linken auf die InstallTipps

**Comment by 2Abendsegler** [comment]
Ja, danke. Das scheint mir gut so, werd ich so machen.

**Comment by 2Abendsegler** [comment]
Entgegen den Erwartungen funktioniert Drop-Box in beide Richtungen.

Was geht nicht:

- Drag & Drop Operation: Im Config Link in Linklist schieben und Position in Linklist verschieben.

**Comment by MagpieFourtyTwo** [comment]
> Entgegen den Erwartungen funktioniert Drop-Box in beide Richtungen.

Kann ich so nicht bestätigen, zumindest was das authenticate angeht.
Wobei ich damit aktuell auch auf einem Win7-PC wieder mal Probleme habe ...

> Was funktioniert nicht oder nicht richtig:
(...)
>     * GClh startet nicht: Tabs in Firefox schließen, Firefox beenden, Firefox starten, GC Seite anwählen.
>       (Hier scheint es noch Probleme zu geben zwischen FF und Tampermonkey insbesondere wenn FF mit bestehenden Tabs zu GC Seiten gestartet wird.)

Das ist interessant - denn das Problem haben wir hier auch auf zwei Win7-Laptops ab und an.  Da hat bisher nur geholfen, entweder Tampermonkey noch mal drüber zu installieren oder TM in den AddOns zu deaktivieren, Firefox öffnen, TM wieder aktivieren und FF noch mal schliessen und öffnen.

Könnte das evtl. das gleiche Problem sein?

Ach ja: Tampermonkey wirft bei mir auch gern mal alle installierten Scripte weg und tut so, als wäre er gerade erst installiert worden - passiert das auch noch sonst wem?  Dann würde ich das Problem eher bei TM sehen als bei GClh2 ...

**Comment by 2Abendsegler** [comment]
(Sorry für die späte Antwort, ich war ein paar Tage verschollen. ;) )

> Könnte das evtl. das gleiche Problem sein?

Wenn auf dem Laptop der Tab vom letzten Start des FF ist, man hat also FF nicht geschlossen sondern mit in den Ruhezustand geschickt, dann könnte das Problem das Gleiche sein. 
 
> Ach ja: Tampermonkey wirft bei mir auch gern mal alle installierten Scripte weg und tut so, als wäre er gerade erst installiert worden - passiert das auch noch sonst wem? Dann würde ich das Problem eher bei TM sehen als bei GClh2 ...

Unwahrscheinlich dass es etwas mit GClh zu tun hat. Deine Windows Systeme sind einfach alt, da kümmert man sich halt eher weniger drum dass noch alles funktioniert. Mir ist aber auch kein Fall bekannt, wo Scripte gelöscht werden.

**Comment by MagpieFourtyTwo** [comment]
Ok, Tabs in den Ruhemodus, das könnte gut sein.  Ich meine mich aber auch zu erinnern, dass das auch schon bei wiederhergestellten Tabs der vorherigen Sitzung passiert ist ...  werden wir beobachten.

Was das "alt" angeht: Win 7 ist nach wie vor das beste (aka "zuverlässigste") Produktivsystem, das man verwenden kann. Nicht umsonst hat MS den Support für die Pro und Ultimate-Versionen verlängert.

**Comment by 2Abendsegler** [comment]
A. Was funktioniert nicht oder nicht richtig:

2. Es ist nicht der GClh der nicht startete, sondern Tampermonkey. Das Resultat ist zwar das Gleiche, aber wir könnten daran nichts ändern. 
Seit einigen Wochen und einigen FF beta Updates passiert das bei meiner Installation aber nicht mehr.
Hat man aber damit Probleme, vielleicht in älteren Android Versionen, dann sollte man die Tabs in FF beta immer schließen und sie nicht im Hintergrund bestehen lassen bis man sie wieder braucht.

**Comment by MagpieFourtyTwo** [comment]
Wie anderswo schon geschrieben reicht es bei "ausbleibendem GClh" in aller Regel aus, TamperMonkey in der Liste der AddOns zu deaktivieren und wenige Sekunden später gleich wieder zu aktivieren. Wechselt man danach in das Tab zurück, in dem GClh vorher nicht aktiviert wurde, startet er dann ohne weitere Useraktionen und bereitet die Seite auch von alleine neu auf.

**Comment by 2Abendsegler** [comment]
zu A. 2. Ausbleibender GClh _(nicht Android spezifisch in FAQs aufnehmen)_:
- > ... reicht es bei "ausbleibendem GClh" in aller Regel aus, TamperMonkey in der Liste der AddOns zu deaktivieren und wenige Sekunden später gleich wieder zu aktivieren. Wechselt man danach in das Tab zurück, in dem GClh vorher nicht aktiviert wurde, startet er dann ohne weitere Useraktionen und bereitet die Seite auch von alleine neu auf. 
_(MagpieFourtyTwo)_
- > Da hat bisher nur geholfen, entweder Tampermonkey noch mal drüber zu installieren oder TM in den AddOns zu deaktivieren, Firefox öffnen, TM wieder aktivieren und FF noch mal schliessen und öffnen. 
_(MagpieFourtyTwo)_
- Tabs mit in Ruhezustand schicken kann auch dazu führen dass TM nicht anläuft. 
_(Hab ich auch mal versucht unter Win8.1, FF; MagpieFourtyTwo)_
- Gleiches kann auch bei der Widerherstellung von Tabs passieren. 
_(Konnte ich selbst noch nicht provozieren; MagpieFourtyTwo)_

@MagpieFourtyTwo
Hier geht es ja primär um Android. Stammt das Know How aus dem Win7 Umfeld oder auch direkt aus Versuchen unter Android? 
Falls Letzteres, welche Android Version nutzt du? Sind dir noch andere Dinge aufgefallen, die nicht richtig funktionieren?

**Comment by 2Abendsegler** [comment]
zu **1. Drag & Drop Operation funktionieren grundsätzlich nicht:**
- GClh Config: Im Kapitel "Linklist / Navigation" kann in der rechten Spalte "Linklist" die Reihenfolge nicht geändert werden. Würde sich quasi umgehen lassen indem man die Linklist der Reihe nach aufbaut, das hineinhängen in die Linklist funktioniert ja aber auch nicht.  
- GClh Config: Im Kapitel "Linklist / Navigation" können von der linken Spalte "Default links" keine neuen Einträge in die rechte Spalte "Linklist" gehängt werden.  

zu **3. Hover over field funktioniert regelmäßig durch antippen:**
- Icons auf Karte: In der Karte läßt sich das Icon "Go to Map" nicht anwählen, das ist eine Ausnahme. Das Icon daneben für die Karten Styles läßt sich hingegen anwählen _(hier könnte man sich vielleicht den Unterschied mal ansehen)_. 
- Vorschau Bilder (Listings, Gallerien): Funktioniert schon durch antippen, gleichzeitig wird durchs Antippen jedoch auch die normale Anzeige des Bildes in groß aktiviert. 
- GClh Config: Infos hinter Fragezeichen anzeigen funktioniert durch antippen.

zu **4. Rechte Maustaste funktioniert regelmäßig durch antippen und halten:**
- Zum auf- bzw. einklappen aller GClh Config Kapitel.
- Link in neuem Tab aufmachen. 

**5. Keine Linklist:** 
- Kein gewohntes Menü oben, Linklist ist rechts seitlich im Menü; Seiten: Dashboard, Search, Map ...: Im Firefox "Desktop-Seite" aktivieren.

**6. Keine Funktionstasten / F-Tasten mit der Standard Android Tastatur:**
- F2 zum Speichern ... funktioniert nicht (GClh Config, Bookmarklisten, PQ, Hide ...).
- F4 bzw. F10 zum Aufrufen des GClh Config bzw. GClh Sync funktionieren nicht.

**7. Installation Firefox:**
- Mit Firefox beta ist "Firefox beta unter Android" gemeint.

**8. Installation GClh:** 
- Konfiguration mit Konfigurationsdatei für Android: Wir könnten eine Konfigurationdatei zur Verfügung stellen, die die nicht richtig funktionierenden Features unter Android deaktiviert. Das könnte dann per GClh Sync manuell importiert werden. Das ist kein Entwicklungsaufwand, hier müssen lediglich die Settings zusammengestellt werden und in einer .txt Datei abgelegt werden.

**Comment by MagpieFourtyTwo** [comment]
>     * Da hat bisher nur geholfen, entweder Tampermonkey noch mal drüber zu installieren oder TM in den AddOns zu deaktivieren, Firefox öffnen, TM wieder aktivieren und FF noch mal schliessen und öffnen.
>       _(MagpieFourtyTwo)_

Der Punkt ist vom darüber stehenden überholt worden, d. h. Neuinstallaiton ist nicht erforderlich.

**Comment by 2Abendsegler** [comment]
zu **7. Installation Firefox:**
- Oder auch Firefox for Android Stable. _(Entsprechende Links mitgeben.)_
