### ISSUE TITLE
Calling Config from new dashboard do not work correct.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#784]
**Describe the bug**
Calling Config from new dashboard do not work correct.

**To Reproduce**
1. Go to new dashboard https://www.geocaching.com/account/dashboard
2. F4
3. Choose Linklist
4. See error in custom links

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22332216/44540511-535ccb00-a707-11e8-9fa7-f5cba62523e5.png)

**Desktop (please complete the following information):**
 - Windows
 - FF
 - 61.0.1 (64-Bit)

**Comment by 2Abendsegler** [comment]
![grafik](https://user-images.githubusercontent.com/22332216/44540707-f9a8d080-a707-11e8-912e-174d8cdeb869.png)

**Comment by Ruko2010** [comment]
Strange...I can't see anything wrong (without your fix):
![image](https://user-images.githubusercontent.com/2239440/44566665-12989c80-a76f-11e8-92d5-a6c5bf0a1c6f.png)

But with your fix it is also working. So maybe just a Windows Issue?!

**Comment by 2Abendsegler** [comment]
Bei dir ist der Raum zwischen Ankreuzfeld und Eingabefeld viel größer als bei mir. Insofern bricht es bei dir nicht um. 
Der Mac nutzt halt den Platz besser aus. :) Im nächsten Leben werd ich mir auch einen zulegen, hihi.

**Comment by Ruko2010** [comment]
Was machst du hier noch online, ich dachte du bist im Urlaub 😉
Ich war früher auch ein Windows Kind, aber seit ich auf Arbeit einen Mac habe, will ich keinen Windows Rechner mehr (auch zu Hause nicht). Ich finde einfach, man hat den Vorteil von Windows (Oberfläche, Leicht zu Bedienen) und von Linux (Arbeit über die Konsole, gut Konfigurierbar, usw.) in einem Gerät. Und da ich eh iPhone/iPad nutze synct das alles auch noch super miteinander. 
Aber ich will niemand bekehren, dass muss jeder für sich selbst entscheiden. Sind halt nicht billig die Teile 😃.

**Comment by 2Abendsegler** [comment]
Ja genau, mach jetzt auch Schluß. Bin bei ner guten Freundin zum Geburtstag, meine erste Etappe sozusagen, gibt jetzt Frühstück. :)
