### ISSUE TITLE
0.2.3 Different section are doubled

### ISSUE THREAD

**Issue by stepborc** [2Abendsegler/GClh#79]
After updating to 0.2.3 different section (Config Menu, Map selector, last log overview) are doubled.

Using Firefox 50.1.0 on Win7 and Xubuntu.

**Comment by 2Abendsegler** [comment]
Das sollte mit der neuen Version 0.2.3.1 behoben sein.
Ein geänderter Namespace hat zu diesem Effekt geführt. Allerdings nicht bei mir, auch jetzt bei der Korrektur nicht. Wer die beiden schon installiert hat, sollte den unteren entfernen. Vorher sicherheitshalber die .db Datei sichern! Anschließend v0.2.3.1 aufspielen. 

https://geoclub.de/forum/viewtopic.php?f=117&t=79425&p=1264055#p1264052
