### ISSUE TITLE
First loaded logs are not correct.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#792]
**Describe the bug**
Die ersten Logs, die im Standard geladen werden, werden scheinbar nicht immer durch den GClh erneuert. 

**To Reproduce**
Ich kann das Problem im Moment nicht nachvollziehen. Der Screen aus dem [Swissforum](https://www.swissgeocacheforum.ch/forum/topic/12872-gc-little-helper-ii/?do=findComment&comment=75097) zeigt aber derartige Logs. 

![grafik](https://user-images.githubusercontent.com/22332216/44694888-8210d380-aa70-11e8-9ac2-8426ee77b242.png)
https://www.geocaching.com/geocache/GC1D49B

Scheinbar werden die VIP ... Buttons für die ersten 25 Logs oder so nicht gesetzt. Das heißt die 25 Logs scheinen nicht erneuert zu werden. Der Avatar in den ersten 25 Logs wird einmal erzeugt und einmal nicht.
 
**Desktop (please complete the following information):**
Windows FF 61.0.2
Mac FF 61.0.2

**Comment by 2Abendsegler** [comment]
Das scheint gar kein Fehler zu sein.
Mein Beitrag im Forum:

---
 Bleiben wir mal bei dem Beispiel von Znuk weil ich dort den Link habe.

 

Ich kann das Problem nachstellen, wenn ich sofort wenn das Listing angezeigt wird nach unten scrolle um neue Logs zu laden. Wenn ich aber etwas warte, dann werden auch die oberen Logs entsprechend aufbereitet. Meines Erachtens gibt es gar keinen Fehler. :D

 

Das Problem entsteht weil ihr vermutlich nicht die schnellste Leitung habt und/oder GS besonders langsam ist und/oder besonders viele Logs vorhanden sind (hier 1359).

Bevor der GClh die Logs korrekt darstellen kann, muß er zuerst alle Logs laden, das dauert. Erst dann kann er alle Logs richtig aufbereiten. Sind die Logs beim nachladen durchs runterscrollen schon durch den GClh geladen, dann werden sie sofort annähernd richtig dargestellt. Deshalb sieht das komisch aus. Versteht ihr? 

 

Probiert es einfach aus indem ihr mal abwartet bis die Loading Kennzeichnung bei den VIP Boxen oben rechts im Listing verschwindet. Bitte vorher auch alle anderen Scripte deaktivieren, auch Ghostery.

**Comment by Ruko2010** [comment]
@2Abendsegler heißt das, wir müssen nichts machen?

**Comment by 2Abendsegler** [comment]
Das letzte Feedback ist nicht ganz so ausgefallen wie erwartet, aber zuerst mal egal. 

Wir sollten die Logs um die GClh Features ergänzen sobald sie geladen sind. Wir sollten also nicht warten bis alle Logs geladen sind. Beim den Logs scheint ja aber noch mehr zu tun.

Das ist dann nun doch prio hoch.

Und wo hatte ich es noch erwähnt ...?
Do not change a running System!

Wir haben die Greasemonkey Unterstützung gekillt, weil es das Coding etwas einfacher gemacht hat. 

Das war falsch! 
Solche Anpassungen sind fast immer falsch! 
Zwei Anwender sind deshalb gegen die Wand gelaufen. Klar dass die Dunkelziffer viel höher ist.

Und, Off-Topic, sie sind auch beim #772 falsch!

**Comment by Ruko2010** [comment]
@2Abendsegler 
> Wir haben die Greasemonkey Unterstützung gekillt, weil es das Coding etwas einfacher gemacht hat.
Das war falsch!
Solche Anpassungen sind fast immer falsch!

Das sehe ich etwas anders. Wir haben die Unterstützung für Greasmonkey raus genommen und das auch angekündigt (schon vor langer Zeit). Wenn die User nicht drauf hören, dann ist das an sich nicht unser Problem. Wenn wir GM wieder unterstützen wollen, dann sollten wir das auch offiziell tun und uns bemühen den Code für beide Kompatibel zu halten. Ich finde es aber unsinnig den Code komplizierter zu machen um etwas zu unterstützen, dass wir nicht mehr unterstützen.
Da wir diese intention aber nicht hatten und GM komplett gekickt haben, brauchen wir auf so etwas auch keine Rücksicht nehmen. Ich weis du willst keine User verprellen, aber wir müssen uns entscheiden. Wollen wir GM unterstützen oder nicht? Wenn nein, dann müssen user die GM nutzen damit leben, dass nicht alles funktioniert. Wenn doch, dann sollten wir das auch offiziell tun. Beides zu machen ist zu viel Arbeit für ein Projekt, dass wir alle nur in unserer Freizeit erledigen!
Ich hoffe das klang jetzt nicht schärfer als es beabsichtigt war.

Aber zurück zum Topic. Ich denke der Teil mit dem Laden der Logs muss komplett überarbeitet werden, da GC hier grundlegend etwas geändert hat (siehe mein letzter Beitrag bei #761)

**Comment by 2Abendsegler** [comment]
Genaugenommen haben wir nicht gesagt dass wir Greasemonkey nicht mehr unterstützen, sondern dass ab FF Version 57 Greasemonkey nicht mehr unterstützt wird. So war es ja auch entwickelt. Wir waren noch zweigleisig im Hinblick darauf dass es ja noch welche gibt die mit FF Version < 57 arbeiten.

Und nun haben wir diese Verfügbarkeit leichtfertig weggemacht. Hier gibt es nichts zu deuteln. Das waren du und ich, wir haben beschlossen es so zu machen. Wir haben die Auswirkungen nicht richtig bedacht und das ist eben auch häufig schwierig weil man so im Detail nicht drinsteckt. Und deshalb ist es in aller Regel falsch und hier im Besonderen. :)

Wir müssen hier nicht einer Meinung sein. Das ist etwas Grundlegendes, entweder man macht es oder eben nicht. Ich gehöre zu denjenigen die kein Refactoring oder Ähnliches durchführen, schon deshalb weil es der Kunde nicht bezahlt, also im echten Leben. Wird der Code komplizierter dadurch dann ist das halt so. Dafür bau ich aber keine Fehler ein weil ich etwas nicht bedenke.


Eigentlich bin ich aber noch online wegen eben den Logs. Ich hab mir folgendes überlegt und auch etwas rumgespielt.
- Wir ersetzen das Log Template durch unser eigenes. GS trägt hier also eher keine Schuld, diesmal.
- Vergiss mal die tbodys, das sind nur die Bilder in den Logs.
- Konzentrier dich mal auf die "logs".

Ich vermute wir ersetzen das Template für die Bilder in den Logs nicht komplett. Womöglich gab es bisher bei allen Templates für die Bilder ein tbody, ganz gleich ob es Bilder gab oder nicht. Jetzt ist es so, dass es nur dann ein tbody zu den Bildern gibt, wenn es Bilder gibt. Zumindest könnte ich mir vorstellen dass es so funktionieren könnte. Die Idee dahinter könnte sein, dass wir ein zu löschendes Log an diesem tbody erkannt haben. Wir löschen diese Logs und bauen sie anschließend neu auf. 

Es scheint also etwas einfacher ...

**Comment by Ruko2010** [comment]
> Und nun haben wir diese Verfügbarkeit leichtfertig weggemacht. Das waren du und ich, wir haben beschlossen es so zu machen. Wir haben die Auswirkungen nicht richtig bedacht und das ist eben auch häufig schwierig weil man so im Detail nicht drinsteckt. Und deshalb ist es in aller Regel falsch und hier im Besonderen. :)

Das sehe ich auch so, es waren du und ich, daran hab ich auch nichts gerüttelt 😃(mir lag es auch fern schuld zu zuweisen). Ich kann mir die Änderungen aus der letzten Version ja nochmal anschauen. Vielleicht bekomm ich die Unterstützung für GM wieder rein.
https://www.ghacks.net/2017/09/21/greasemonkey-4-firefox-57-compatibility/
Wenn GM wieder geht in der neuen Version, können wir auch gern die Unterstützung wieder offiziell machen. Die Frage ist, was wir dafür alles ändern müssen 😉.

> Vergiss mal die tbodys, das sind nur die Bilder in den Logs.

Ich dachte die tbodys wären die Logs. Wenn das wirklich nur die Tabellen mit den Bildern sind, dann wird es eventuell etwas einfacher. Ich versteh leider noch nicht alle zusammenhänge beim (nach)laden der Logs, aber mit dem Ansatz werde ich mich nochmal ran setzen und weiter testen

**Comment by 2Abendsegler** [comment]
Die Arbeiten am Issue #761 haben folgende Erkenntnis gebracht:
- Das Nachladen der Logs, durchs sofortiges Runterscrollen wenn die ersten Logs angezeigt werden, wird durch GS durchgeführt. Die function disablePageAutoScroll funktioniert nicht mehr. 
Zum Verständnis: So ziemlich das Erste was wir in diesem Umfeld machen ist das Ersetzen des Log Templates. Scrollt der User nach unten ist das Log Template schon ersetzt. Dann springt das Nachladen der Logs durch GS an und und die Logs sehen dann fast so aus wie unsere eigenen.
- Ich habe mal etwas rumgespielt und überlegt wie wir selbst die ersten Logs schneller im richtigen Template darstellen können. Theoretisch geht das. Beim Lesen der Logs müßten wird dann prüfen ob wir genügend Logs bereits gelesen haben und könnten dann die Logs in Table cache_logs_table ersetzen bzw. direkt in cache_logs_table2 aufbauen. Das machen wir ja bereits, aber erst nachdem wir alle Logs gelesen haben. Problematisch ist, dass wir zum Zeitpunkt des Lesens die Datenstruktur "logs" noch nicht bestückt haben, wir also hier das Rad schon wieder neu erfinden müssen. Das ist es auch was ich meinte zu wissen, als der Fehler im Swissforum erschien. Wir sind mit den heutigen Funktionen nicht in der Lage vor dem Laden aller Logs bereits welche nachzuladen. Die Änderungen sind meines Erachtens erheblich. Ich möchte sie nicht angehen.
- Wir sollten also das Nachladen von GS über function disablePageAutoScroll unterbinden. Das ist dann für die User ein Schritt zurück. Trotzdem wäre das mein Vorschlag.
- Wenn sich jemand findet der den Umbau durchführt um vorzeitig Logs nachzuladen bzw die ersten Logs vorzeitig zu ersetzen, dann soll er das tun. Meine Empfehlung ist es aber nicht, weil auch sicherlich Folgearbeiten entstehen werden, weil hier sicherlich nicht alles bedacht wird.

**Comment by 2Abendsegler** [comment]
Das eigentliche Problem, dass die ersten Logs nicht um VIP ... ergänzt wurde, hat nichts mit GClh zu tun sondern lag am Script GeoMaps. Wird das Script nach GClh gestartet dann ist das eigentliche Problem damit gelöst.
[Beitrag im Swissforum](https://www.swissgeocacheforum.ch/forum/topic/12872-gc-little-helper-ii/?do=findComment&comment=75118)

@Ruko2010 
Ich schlage vor wir schließen das Issue und machen ein neues Issue auf zum Thema GS nachladen unterbinden (function disablePageAutoScroll).

**Comment by Ruko2010** [comment]
Klingt nach einem Plan
