### ISSUE TITLE
Tune line break for owner in additional popup on map.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#798]
Tune line break for owner in additional popup on map.
Wir haben ja jetzt mehr Platz. Maximale Weite von 110 auf 145 Pixel erhöhen.

**Comment by 2Abendsegler** [comment]
Hab keine Ahnung wie man das sauber zurückdreht.
Ich ändere es nun ab über einen weiteren PR.

**Comment by Ruko2010** [comment]
Ja so geht es natürlich, aber man kann es auch "sauber" machen 😃. Wenn man einen "ordentlichen" Git Client nutz, kann man einen Commit auswählen und "Revert Commit" klicken. Dann werden alle Änderungen aus dem Commit zurück gedreht:

![image](https://user-images.githubusercontent.com/2239440/44738882-7ec02b00-aaf6-11e8-8e01-aa1f8469fa3a.png)
Ob es auch über die Weboberfläche von Git geht weis ich gar nicht. Da fehlt mir einfach die schöne "Timeline"-Ansicht, wie man sie in einem Git-Client hat.
