### ISSUE TITLE
Show elevation on additional popup on the map.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#802]
**Describe the solution you'd like**
Show elevation on additional popup on the map.

Dabei müssen auch geänderte Koordinaten berücksichtigt werden.
Als Title sowas wie "Elevation data from Google Elevation", wie bei den Daten im Listing auch.

**Additional context**
![x2](https://user-images.githubusercontent.com/22332216/44712435-05eab000-aab1-11e8-9d92-cb20fcd869e4.JPG)
([Zur Karte mit diesem Cache](https://www.geocaching.com/map/default.aspx?lat=42.61055&lng=1.57895#?ll=42.6038,1.46972&z=17))

**Comment by CachingFoX** [comment]
This looks nice. But we should wait with the implementation. The feature elevation will be refactored with #777. After changes from #777 are integrated we can check how we implement this idea.

**Comment by CachingFoX** [comment]
I move the issue to the next milestone (v0.9.13). After the milestone v0.9.12 is release I will have a look on this new feature. I think we need some modification at the elevation features and I want get in conflicts with some other modification I have already done for v0.9.12 at waypoint elevation.

**Comment by Ruko2010** [comment]
@CachingFoX is there a simple function that can be called to get the elevation for the cache, or do you have to rewrite some parts of your code?
Something like
`var elevation = getElevation(lat,lon);` or
`var elevation = getElevation(GCCode);`

**Comment by CachingFoX** [comment]
@Ruko2010 Yes and No. And more no :cry: 

There is the function `getElevations(index,locations)` The first parameters give the index of the elevation service and the second parameter is a array of lat/long objects (=a string with two comma separated decimal numbers for latitude and longitude). The functions calls them self to use alternative elevation service, if primary service is not available. At the moment there are only two services (primary, secondary). The function is asynchronous. 

I think there are three points have to be changed:

1) The function `getElevations()` contains GUI specific parts:
```
function getElevations(serviceIndex,locations) {
    if (serviceIndex >= elevationServices.length || elevationServices<0 ) {
        /* GUI: query elevation fails, mark elevation labels at cache listing */
        $('.waypoint-elevation').each(function (index, value) {
            $(this).html('<span title="Fail to load elevation data">???</span>');
        });
        return;
    }

     /* GUI: sets/change the tooltip (if another service is used) */
    $('.waypoint-elevation').each(function (index, value) {
        $(this).html('<img src="' + urlImages + 'ajax-loader.gif" title="Load elevation data for the waypoint from '+elevationServices[serviceIndex]['name']+'."/>');
    });

    /* GUI: sets n/a for waypoints without coordinates */
    $('.waypoint-elevation-na').each(function (index, value) {
        $(this).html('n/a');
    });

   ....
```
2) The handler functions for the different elevation services transforms the result and calls `addElevationToWaypoints()`. The function addElevationToWaypoints() sets the elevation values of the elevation labels.

3) Initialize the array of elevation services (`elevationServices`) have to be done somewhere else. Check also `elevationServicesData`

**Comment by Ruko2010** [comment]
Will you make the changes 😃? it's your baby 😉...
