### ISSUE TITLE
Tune additional popup on map.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#805]
**Describe the bug**
Tune additional popup on map.
Der zweite Block bricht in Deutsch bei Geländewertung um. Auch wenn wir eigentlich nur Englisch unterstützen ...

![grafik](https://user-images.githubusercontent.com/22332216/44734485-516d8000-aaea-11e8-98b5-d6deee4aa9b7.png)

**Comment by 2Abendsegler** [comment]
Und jetzt sieht es in CZ so aus.
![grafik](https://user-images.githubusercontent.com/22332216/44735135-df963600-aaeb-11e8-9807-478e4e6325fa.png)

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Ich glaube wir sollten das mit den 60 / 40 zurücknehmen. GS hat die Bezeichnungen so gewählt, wie Platz zur Verfügung stand. Irgendwo werden die Teile nun umbrechen.

Ich würde es gerne zurückdrehen. Was meinst du?

**Comment by Ruko2010** [comment]
Ja nimm es zurück. Die hätten ja auch einfach D und T Wertung schreiben können😉

**Comment by 2Abendsegler** [comment]
Rejected.
