### ISSUE TITLE
Include GPSVisualizer as an additional map service like Flopps Map

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#807]
**Describe the solution you'd like**
I'd like to have GPSVisualizer as a new map service like Flopps Map or BRouter to see waypoints of a geocache on a map. GV offers a lot of possibilities to visualize waypoint data on a map.

GPSVisualizer is map tool available under [www.gpsvisualizer.com](https://www.gpsvisualizer.com). GV is a tool similar to Flopp's Map with a lot of features. The main goal of GV is to create a map with own elements like waypoints or polygons. But I find it very helpful for Geocaching, too. GPSVisualizer can read and convert GPS data from many sources. The simplest  way to insert data is a textfield with comma separated values. GV is a good choice if you have to handle a lot of GPS data.

**Step 1**
![grafik](https://user-images.githubusercontent.com/1838534/44832096-ba0f4680-ac29-11e8-8776-2329811ea571.png)
Link to GPSVisualizer also available at sidebar

**Step 2**
![grafik](https://user-images.githubusercontent.com/1838534/44832071-921fe300-ac29-11e8-85f2-83fc4ee8cf36.png)
The link transfers the data from the listing page (marked yellow)  into the input for of GV. The user can make many configurations. Click on the button "Draw the map" (marked red) opens a map with the waypoints

**Step 3**
![grafik](https://user-images.githubusercontent.com/1838534/44832163-00fd3c00-ac2a-11e8-8641-cb3c439e134c.png)
Map with waypoints

**Features**
* 161m radius of physical stages
* different icons for waypoints types
* use cache type icon for listing coordinates

**Additional context**
This features needs refactoring from #777

**Comment by Ruko2010** [comment]
@CachingFoX Can you describe the feature more detailed (or a screenshot)? I have no idea what you mean with "GPSVisualizer".

**Comment by CachingFoX** [comment]
@Ruko2010 I have extend the description with more details and screenshots. 

With the refactoring in #777 it will be very easy to implement this feature.

**Comment by CachingFoX** [comment]
Open issues
* ~~~check icons for all caches type~~~
* ~~~use short urls~~~
* zoom calculation

For zoom calculation the common code parts have to be changed. At the moment the calculation function TileMapZoomLevelForBoundaryBox() use the complete screen width and height. The function have to be adapt to service with no full-screen maps. Or GPSVisualizer have to be configured to show the map alway in full-screen mode.

**Comment by Ruko2010** [comment]
@CachingFoX thanks for extending the description. A had not heared of this service, but I think it is a good addition to brouter and flopps.
