### ISSUE TITLE
Three error occurs on "Unpublished Cache" page from the new dashboard

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#809]
**Describe the bug**
If I open the page Unpublished Caches from the new dashboard I got three errors:
- Linklist, Default Links on new dashboard:: box is undefined
- Improve new dashboard:: nav is null
- Aufbau Links zum Aufruf von Config, Sync und Find Player:: $(...)[0] is undefined

**To Reproduce**
- Log into www.geocaching.com
- Open the new dashboard
- Goto Unpublished Caches: [https://www.geocaching.com/account/dashboard/unpublishedcaches](https://www.geocaching.com/account/dashboard/unpublishedcaches)
- See web console

**Expected behavior**
No errors

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1838534/44863402-544caa00-ac7d-11e8-8125-6fbb73d026c9.png)

**Desktop (please complete the following information):**
* Windows 7 64-bit
* Firefox 61.0.2
* Tampermonkey v4.7.5788
* GClh 0.9.11

**Analysis**
Reason for error # 3: The function is_page("dashboard") returns true if the url begins with https://www.geocaching.com/account/dashboard. If there a subpage like the unpublished caches the funtions also returns true.

**Effects**
* For error # 3: nothing
* For error # 1 and # 2: unknown

**Comment by Ruko2010** [comment]
Saw rhis today while publishing my new event, but I hadn‘t had the time to report it, funny :)

**Comment by CachingFoX** [comment]
I had not time in the last day to report it. New event interesting :-)

**Comment by CachingFoX** [comment]
I think I know the solution to fix it.

**Comment by CachingFoX** [comment]
There are seven section which use is_page("dashboard")

* :heavy_multiplication_x: **line 887**: Header layout
* :heavy_multiplication_x: **line 951**: New width
* :question:  **line 1017**: Linklist on top
* :heavy_check_mark:  **line 4018**: Linklist, Default Links on new dashboard.
* :heavy_check_mark:  **line 5487**: Improve new dashboard.
* :question: **line 7178**:  Save trackable uid from dashboard
* :heavy_check_mark:  **line 7261**: Aufbau Links zum Aufruf von Config, Sync und Find Player

**Comment by CachingFoX** [comment]
* :heavy_check_mark: **line 887**: Header layout **dashboard section**
* :heavy_check_mark: **line 951**: New width **dashboard section**
* :heavy_check_mark: **line 1017**: Linklist on top **dashboard section**
* :heavy_check_mark:  **line 4018**: Linklist, Default Links on new dashboard. **dashboard only**
* :heavy_check_mark:  **line 5487**: Improve new dashboard. **dashboard only**
* :heavy_check_mark: **line 7178**:  Save trackable uid from dashboard **dashboard only**
* :heavy_check_mark:  **line 7261**: Aufbau Links zum Aufruf von Config, Sync und Find Player **dashboard only**
