### ISSUE TITLE
Error messages at 'All Geocaches' on the public profile

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#818]
**Describe the bug**
Two error messages at the second page of 'All Gecocaches' in the public profile
- Show Profile Link: malformed URI sequence
- VIP VUP:: malformed URI sequence

**To Reproduce**
1. Go to [https://www.geocaching.com/seek/nearest.aspx?u=M%26M%20F%C3%BCrth](https://www.geocaching.com/seek/nearest.aspx?u=M%26M%20F%C3%BCrth)
2. Go to second page

**Expected behavior and effects**
No error messages. Clarify what is missing.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1838534/44954807-e258a880-aea8-11e8-9d19-ff808edb5be3.png)

**Desktop (please complete the following information):**
-    Windows 7 64-bit
-    Firefox 61.0.2
-    Tampermonkey v4.7.5788
-    GClh 0.9.11

**Comment by CachingFoX** [comment]
This error doesn't occurs on the first page.

**Comment by CachingFoX** [comment]
At [https://www.geocaching.com/seek/nearest.aspx?u=PeMoCacher](https://www.geocaching.com/seek/nearest.aspx?u=PeMoCacher) the errors don't occur.

**Comment by CachingFoX** [comment]
- okay F **%C3%BC** rth [M&M Fürth](https://www.geocaching.com/seek/nearest.aspx?u=M%26M%20F%C3%BCrth)
- failed F **%u00fc** rth [M&M Fürth](https://www.geocaching.com/seek/nearest.aspx?u=M%26M+F%u00fcrth)
- okay F**ü**rth [M&M Fürth](https://www.geocaching.com/seek/nearest.aspx?u=M%26M+Fürth)

It looks like GClh have problems with encoding of **ü** as **%u00fc**

**Comment by 2Abendsegler** [comment]
Ich hab nur mal kurz reingeschaut, weil ich ja beim Auffinden der Users auf der Seite, nicht in der URL, in der letzten Version Änderungen gemacht hatte. Hat aber damit nichts zu tun.

Hier hast Du wohl Recht. Allerdings hat das mit ü schon funktioniert, nicht nur auf der ersten Seite. Vermutlich sind das erneut Änderungen von GS ab der 2ten Seite.

**Comment by CachingFoX** [comment]
The error occurs in function decodeURIComponent() in function urldecode()
`     function urldecode(s) {
        ....
        s = decodeURIComponent(s);
        ....
    } `

**Comment by CachingFoX** [comment]
[https://en.wikipedia.org/wiki/Percent-encoding#Non-standard_implementations](https://en.wikipedia.org/wiki/Percent-encoding#Non-standard_implementations)

> There exists a non-standard encoding for Unicode characters: %uxxxx, where xxxx is a UTF-16 code unit represented as four hexadecimal digits. This behavior is not specified by any RFC and has been rejected by the W3C. The eighth edition of ECMA-262 still includes an escape function that uses this syntax, along with encodeURI and encodeURIComponent functions, which apply UTF-8 encoding to a string, then percent-escape the resulting bytes.

**Comment by CachingFoX** [comment]
See at [https://github.com/golang/go/issues/11249](https://github.com/golang/go/issues/11249). There is an implementation of a function which can solve our problem or give us an idea how we can find a solution.

```
func decodeUnicodeEscapedChars(s string) string {
 re := regexp.MustCompile('%u[0-9ABCDEF]{4}')
 return re.ReplaceAllStringFunc(s, func(s string) string {
    t, err := strconv.Unquote("\"" + "\u" + s[2:] + "\"")
    if err != nil {
        panic(err)
    }
    return t
})
```

**Comment by CachingFoX** [comment]
This function could be help [https://jsfiddle.net/ouhLc072/3/](https://jsfiddle.net/ouhLc072/3/)

```
function unicodeToChar(text) {
   return text.replace(/%u[\dA-F]{4}/gi, 
          function (match) {
               return String.fromCharCode(parseInt(match.replace(/%u/g, ''), 16));
          });
}
```

**Comment by CachingFoX** [comment]
Okay obrige Funktion in `function urldecode()` eingebaut. Weitere Probleme tretten auch in einem Dropbox Teil auf (_Dropbox auth token bereitstellen_) `function parseQueryString()`

.
