### ISSUE TITLE
Link to personal Ignore List at section List in sidebar of the new dashboard

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#819]
**Describe the solution you'd like**
In the section Lists in the sidebar of the new dashboard a link to the personal Ignore List is missing. Embedded link to personal Ignore List in sidebar of the new dashboard. 

**Describe alternatives you've considered**
The id of the Ignore List is personally and can be changed. The link have to be a dynamic link. If the link is click the script have to be query the current id of the ignore list and open this list.

**Additional context**
See also here #815

**Comment by CachingFoX** [comment]
The smart link works for me at Windows & Chrome  :thinking: :question: :question: :question:

**Comment by CachingFoX** [comment]
@Ruko2010 It test it with MacOS and Chrome - it works for me. :thinking: 
Please can you check if you can see the link to the ignore list at the end of the page [https://www.geocaching.com/account/lists](https://www.geocaching.com/account/lists).

**Comment by CachingFoX** [comment]
@Ruko2010 there are two possible reasons:
- you don't have an Ignore List (please can you check it)
- you are not a premium member :joy: - if there a function to find out if the use is PMO or basic member

**Comment by CachingFoX** [comment]
@Ruko2010 Please can you check my fix.

**Comment by Ruko2010** [comment]
@CachingFoX you are right. I don't have an ignore list 😃. So can you please hide the link if no list is found? Or maybe you disable the Link an add a hint (on hover) that the user does not have a list.
But I think hiding the Link is the better solution. Otherwise other users will be confused if they click on the link and nothing happens.

**Comment by CachingFoX** [comment]
@Ruko2010 A life without Ignore List? Whaaat! ;-)
At the moment you will get an alert. I think an alert will be better because if the link doesn't shown the user can be confused. The alert gives the user the info that he has no IL.

**Comment by Ruko2010** [comment]
@CachingFoX für was braucht man denn eine Ignore liste? Caches sind da um gefunden zu werden 😉. Und da ich sowohl hohe D- als auch hohe T-Wertungen mag, gibt es für mich keinen Grund Caches auf die Ignoreliste zu setzen 😉.
Was setzt ihr denn für Caches auf die Ignore Listen?

Aber ja, die Möglichkeit mit dem alert finde ich ok, solange da drin steht, warum es nicht geht 😉.

**Comment by Ruko2010** [comment]
😱
