### ISSUE TITLE
Errors on unpublished Caches

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#826]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2239440/44999875-b9c3d200-afc0-11e8-990c-fb5d7c6e22c5.png)

**To Reproduce**
1. Go to https://www.geocaching.com/geocache/GC7J5C9_in-teufelsnamen (@CachingFoX you have to log out before of cause 😉)
2. See error

**Expected behavior**
no Error

**Comment by CachingFoX** [comment]
Oh no! I will check it :fox_face:

**Comment by CachingFoX** [comment]
Another link: https://www.geocaching.com/geocache/GC7J5C8_eile-mit-weile

**Comment by CachingFoX** [comment]
VIP VUP is not a :fox_face:-:bug: (fox-bug) :speak_no_evil:

**Comment by CachingFoX** [comment]
Okay bug 1 and 3 are resolved in two ways:
- improve error handling for OpenElevation service
- block elevation request without waypoints

bug 2 (VIP VUP) is a little bit difficult. The try/catch block is 700 lines long :unamused:

**Comment by CachingFoX** [comment]
There is an uncatched error: `TypeError: $.template is undefined`

```
gclh_updateTmpl                    GC7J5C8_eile-mit-weile:1:31
<anonym>                           GC7J5C8_eile-mit-weile:1:769
injectPageScript                   userscript.html:12948:5
mainGC                             userscript.html:7020:21
start/<                            userscript.html:1433:17
resolveWith                        userscript.html:7:15710
done                               userscript.html:7:15604
start                              userscript.html:1422:5
.....
```

**Comment by CachingFoX** [comment]
> Expected behavior
no Error

Done :smile:

**Comment by Ruko2010** [comment]
@CachingFoX I know you implemented an solution, but I think the main problem is the same as #833 . GClh "thinks" it is on a cache listing page (which indeed is right), but it can't find any of the elements needed (because they are not there), because the cache is unpublished. So maybe it would be a better (and faster) approach not to "heal" the symptoms but the problem. Just let the functions "know" they are on on unpublished cache page and don't run at all.

I think of something like (in the function `is_page` on the `cache_listing`-block
`if(typeof $(.UnpublishedCacheSearchWidget) == 'undefined') status = false;`

Similar implementation as in PR #834

**Comment by Ruko2010** [comment]
So if we add more functions for the cache listing page, it could be that they are failing too (in the future). With my approach this would not happen.

**Comment by CachingFoX** [comment]
@Ruko2010. Yes you are absolutely right. But please merge also my fix. This includes general error handling for the OpenElevation service. Thank you

**Comment by Ruko2010** [comment]
I implemented my suggestion in your PR and will merge it in the evening.
