### ISSUE TITLE
4 Errors on Log Page

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#833]
**Describe the bug**
In the current collector, when I try to log a cache I'll get the following 4 errors:
![image](https://user-images.githubusercontent.com/2239440/45012728-acd2cd00-b018-11e8-8a8b-41748161adb4.png)

I think this is due to out changes made in the current version.

**To Reproduce**
1. Go to a cache and create a new log.
2. See error

**Expected behavior**
no Error

**Comment by CachingFoX** [comment]
You you have already referenced #826. I think three of the four errors will be resolved by #826.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Das sind normale Links zu Cache Listings. Das benötigen wir. Hier ein Beispiel das entsteht wenn man einen Cache aus dem neuen Dashboard aus der Recently Viewed Liste aufruft.
https://www.geocaching.com/geocache/GC30AYY
