### ISSUE TITLE
Show both tabs "Active Pocket Queries" and "Pocket Queries Ready for Download" together of one page. 

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#835]
**Is your feature request related to a problem? Please describe.**
Show both tabs "Active Pocket Queries" and "Pocket Queries Ready for Download" together of one page. Only in compact mode. Remove the Tabs completely.

**Comment by 2Abendsegler** [comment]
Show both tabs "Active Pocket Queries" and "Pocket Queries Ready for Download" together of one page. 
Nur im compact mode.
Der Parameter muss aktiviert werden, er steht standardmäßig auf "false".
 
Bilder für Changelog:

![x1](https://user-images.githubusercontent.com/22332216/45057280-8141f800-b095-11e8-9678-dc054d2fe3a1.jpg)

![x2](https://user-images.githubusercontent.com/22332216/45057287-843ce880-b095-11e8-8fc4-5f4660162569.JPG)

**Comment by Ruko2010** [comment]
Mir gefällt es sehr gut!
