### ISSUE TITLE
Check Function helper/gclh_dev_cs_ids.user.js

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#841]
@CachingFoX Ich habe gesehen, dass es viele Änderungen mit dem GoLive v0.9.12 in helper/gclh_dev_cs_ids.user.js gibt. Da haben wir doch aber gar nichts gemacht oder? Es kann sein, dass das aus einer meiner "alten" Branches kam. Wenn das so ok ist, dann lass es, aber falls die Änderungen nicht beabsichtigt waren, dann sag Bescheid und ich mache es Rückgängig. Ich habe ein Backup der Version 0.9.11

**Comment by CachingFoX** [comment]
@Ruko2010 Ich schau es mir an.

**Comment by CachingFoX** [comment]
@Ruko2010 dafür habe wir ja ne Versionsverwaltung. Die Änderung kann auch von mir kommen. Ich hab da so ein Gefühl.

**Comment by CachingFoX** [comment]
Also ich hab es mir angesehen. Die Änderungen kommen von mir. Sollten eigentlich nicht ins Produktivsystem. Leider sind die Funktionen nicht gerade aussagekräftig benannt. Abc und xyz ;-). Ich mach schön.

@Ruko2010 soll ich die Änderung in den collector merge? Hat ja keine (unmittelbare) auf das User Script.

**Comment by CachingFoX** [comment]
@Ruko2010 Gibt es da in Git nicht so Art Labels dafür? Oder sollte man nicht von jeder releasten Version ein Branch erzeugen?

Ich finde Zip-Dateien blähen das Repo unschön auf, zumal die Infos eigentlich da sein sollte. Mir fehlt für Git aber auch noch eine gewisse Routine und Kniffe. 

Aber danke für die Info.

**Comment by Ruko2010** [comment]
Ich setze zusätzlich bei mir im Git-Client Tags, aber die werden nicht ins GitHub übertragen, keine Ahnung warum. 
Sooo groß sind die Zips nicht, darum find ich es nicht schlimm. Ich glaub du kannst auch in deinen Usereinstellungen für das Repo Verzeichnisse ausschließen, dann sind sie bei dir lokal weg. Und online ist es ja egal wie groß die sind. Speicherplatz kostet ja bei GitHub nichts 😉. Aber du hast recht. Nötig sind sie nicht.
Für jede Version einen Branch zu machen wird irgendwann zu unübersichtlich.

**Comment by 2Abendsegler** [comment]
Es gibt die [Releases](https://github.com/2Abendsegler/GClh/releases), wäre das nicht der richtige Ort?

**Comment by Ruko2010** [comment]
Doch, genau das 😃. @2Abendsegler als ich das Projekt von dir übernommen habe, hatte ich mal gefragt warum du das nicht nutzt, und ich hab deine Technik halt übernommen. Aber eventuell wäre es nicht verkehrt auf Releases umzustellen. Dann sparen wir uns das ZIP Backup und haben immer online eine Übersicht.

**Comment by Ruko2010** [comment]
Und die User können sich auch eine alte Version des Scripts einfach laden. Also Win-Win 😃

**Comment by 2Abendsegler** [comment]
Ja ich weiss. Jetzt suchen wir aber doch zuerst einen Platz für die alten Versionen. Die Installation über den Master betrifft das ja zuerst mal nicht.

**Comment by Ruko2010** [comment]
Nein. Es geht ja nur drum, dass wir ein Backup der alten Versionen haben. Und wenn wir das über Releases machen, können sich die User selbst auch alte Versionen runter laden.
Ich werde mal das GoLive Dokument beim nächsten Release anpassen.

**Comment by Ruko2010** [comment]
@CachingFoX Ist das hier eigentlich fertig?

**Comment by CachingFoX** [comment]
@Ruko2010 Ja
