### ISSUE TITLE
[PQ splitter] Implement all filter for PQ splitter, show progress of created PQs, work with suggested values, work with all languages.

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#843]
<del>- [ ] Hidden between</del>
- [x] Cache type
- [x] Cache size
- [x] Difficulty / Terrain
- [x] Hide (found, owned, not found)
- [x] Hide premium
- [x] Centre/radius (km)

**Comment by Ruko2010** [comment]
"Hidden between" benötigt man nicht auf der PQ-Seite, da der Filter um die PQSplitter selbst implementiert ist.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Moin,

hatte die Tage mal etwas mit deinem PQ-Splitter rumgespielt und wollte daran etwas basteln. 

Im Moment geht das glaube ich nur auf Deutsch, weil es bei der Behandlung der Sprache noch einen Bug gibt. Außerdem wird zwar eine Fehlermeldung ausgegeben wenn nicht de oder en, es werden aber trotzdem PQ erzeugt. Ich würde diese Fehler gerne beheben und auch gerne alle Sprachen ermöglichen, falls ich das hinbekomme.

Ist das ok, oder willst du dein Baby allein haben? Kannst das ruhig sagen, ich nehme niemandem sein Baby weg. 😁 

Steht bei mir überhaupt der aktuelle Stand, oder hast du bei dir schon fleißig weitergemacht? 

LG und einen schönen Arbeitstag Frank

**Comment by 2Abendsegler** [comment]
@Ruko2010 🖖

Habe noch etwas weiter in deinem PQ Splitter gestöbert und rumprobiert.

Das ist eine super Sache. 👍 

Am Anfang dachte ich bei der einen oder anderen Sache, wieso denn das und warum denn an dieser Stelle im Coding. Aber so langsam verstehe ich mehr. Hast du klasse eingebaut, da kann ich mir wirklich was abschauen, richtig durchdacht, nicht wie vielfach der Kram von GS. 🤭

Das angedachte Handling der Sprachen sollte funktionieren, allerdings sind die Monatsnamen nicht in allen Sprachen korrekt vom Seiteninhaber gesetzt worden. 🙄 Beispielsweise fehlt beim August in französisch das Dach im Août. Deshalb kann französisch nicht verwendet werden, sobald dort ein Aout vorkommt.

Naja ... wollte nur mal soweit meinen Respekt bekunden. 👍 ... 🤤 ... 😂

PS: Ich hatte auch gerade noch etwas in den Emojis gestöbert, sieht man. 😂

**Comment by Ruko2010** [comment]
Danke 😃. Das hört man gern. Der Splitter hat auch lange gedauert, aber ich nutz ihn gern im urlaub wenn ich kein internet habe (Australien/USA usw.).
Meinst du wir müssen was machen wegen August im Französischen? Ich hab grad gar keinen Überblick mehr, was für Sprachen alles gehen und welche nicht.
Eventuell sollte man bei Projekt GC einfach mal hinschreiben und bescheid geben, dass da was fehlt.

**Comment by Ruko2010** [comment]
Ich seh grad, dass du ja davor noch was geschrieben hast 😃.
Also, du kannst gern weiter basteln. Ich freu mich wenn du es besser machst bzw. weiter entwickelst 😃.

**Comment by 2Abendsegler** [comment]
Ja, ich glaube das war viel Arbeit bis das mal so gestanden hat. Es ist halt so, dass ich an einer Winzigkeit anfange, und dann sehe ich das noch und das noch und hab noch die Idee und noch weitere ... . Und so sehen plötzlich die Programmteile ganz anders aus. In etwa so läuft das gerade. Es ist nicht so dass etwas schlecht wäre, man kann nur halt häufig noch einen drauf setzen.

Beispiel: Ich hatte den Splitter gestartet und er lief quasi direkt gegen die Wand. Hatte glaube ich englisch gewählt und wegen eines kleinen Bugs hat er auf deutsch geprüft. Dann hat er eine Fehlermeldung ausgegeben, hat aber trotzdem noch PQs angelegt. Zuerst wollte ich den kleinen Bug beheben. Dann habe ich gedacht, ist doch irgendwie blöd wenn jetzt einer von den 24 Franzosen kommt und natürlich in Französisch angemeldet ist. Französisch ging natürlich noch nicht, ist ja auch nur für de und en vorgesehen. Und dann waren da die nicht ganz sauberen Benennungen auf der Seite in zahlreichen Sprachen, die hart bestraft werden, indem man den Monat nicht in eine Nummer umwandeln kann. Und dann weiß ich nie was in Englisch grossgeschribeen werden soll. Ich mach das immer nach Gefühl, du scheinbar auch. :) Ich habe [das hier](https://www.lernenundhelfen.de/lernhilfen/englisch/englisch-gross-und-kleinschreibung.htm
) mal kurz durchgesehen und will nun auch das anpassen ... 

Ich könnte jetzt noch ne halbe Ewigkeit weiter erzählen, was mir noch aufgefallen ist und was auch noch schön wäre ... Bei meinen eigenen Programmen geht es mir ja auch ständig so, wenn ich ne Weile nicht reingeschuat habe. 

Irgendwann habe ich so viel an deinem PQ Splitter geändert und erweitert dass du ihn nicht mehr wiedererkennst. Dabei kann ich diese Dinge überhaupt nur umsetzen, weil es aus meiner Sicht wirklich richtig gut entwickelt ist. Ich hätte es so niemals hinbekommen, ganz ehrlich. Ich will auch nicht dass du die Lust ganz verlierst noch mitzumischen.

Ich werde ein paar Dinge oder auch mehr einbauen. Das sollte alles insbesondere die Stabilität verbessern, was die Sprachen relevanten Dinge betrifft und auch die Kommunikation mit dem User, also richtige englische Schreibweise und Fehlermeldung zum richtigen Zeitpunkt. Ich habe gerade einen Lauf ... 😄

**Comment by Ruko2010** [comment]
Keine Sorge. Selbst wenn am Ende etwas komplett anderes im Code ist und ich das nicht mehr wieder erkenne: mach ruhig! Hauptsache es wird besser und/oder stabiler.
Mir geht es bei den Funktionen eigentlich nie drum, dass das meine "babys" sind. Mir gehts um die Funktionalität an sich. Und wenn die läuft ist alles in Butter. Und wenn du es verbessern kannst, umso besser 😃.

> Ich will auch nicht dass du die Lust ganz verlierst noch mitzumischen.

Das tut ich nicht, aber bei mir ist das Geocachen gerade irgendwie in den Hintergrund gerückt. Es sind viele andere Dinge, die mehr Prio haben. Das tut mir Leid für unser Projekt hier, aber ich weis auch nicht, ob sich das in absehbarer Zeit ändern wird. Darum bin ich so inaktiv. Nicht weil ich die Lust verloren hab, sondern sich einfach der Fokus verschoben hat.

Darum nochmal im Klartext: Pass ruhig an was du für richtig hältst, ich bin nicht böse 🙂

**Comment by 2Abendsegler** [comment]
- [ ] Implement all possible filter of the PQ splitter page of Project GC.
- [ ] Show "Number of PQs completed", "Number of PQs in progress" and  "Total number of PQs to be done".
- [ ] Restriction for difficulty and terrain, because only contiguous areas for difficulty and terrain can be specified on the PQ page.

**Comment by 2Abendsegler** [comment]
Merged with #2017
