### ISSUE TITLE
PQ error because of missing last column "Send to GPS".

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#844]
**Describe the bug**
PQ error because of missing last column "Send to GPS".

**To Reproduce**
1. Go to the list of one of your PQs
2. See error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22332216/45132859-d6176880-b192-11e8-8a57-53585240316e.png)

**Desktop (please complete the following information):**
 - Win 8.1
 - FF 61.0.1 (64-Bit)
 - GClh v0.9.12

**Comment by 2Abendsegler** [comment]
![grafik](https://user-images.githubusercontent.com/22332216/45133161-217e4680-b194-11e8-87f0-f71cfd640477.png)

**Comment by Ruko2010** [comment]
@2Abendsegler Ich kann den Fehler nicht nachstellen. Auf welche Seite genau muss ich gehen? Du sagst PQ, aber der Screenshot ist doch eine Übersicht meiner Caches die ich gefunden habe, oder?

Ich bin auf folgendem Link: https://www.geocaching.com/seek/nearest.aspx?ul=2Abendsegler# und sehe keinen Fehler (natürlich ohne deine Anpassungen 😉)

**Comment by Ruko2010** [comment]
"Show compact layout in pocket queries" ist an

**Comment by Ruko2010** [comment]
Ahhh, es muss auch "Show compact layout in all nearest lists (without PQ)" an sein, dann kommt auch der Fehler 😃

**Comment by 2Abendsegler** [comment]
Ja, du hast natürlich recht. Für mich sind das alles PQ. Und der Fehler ist wohl auch in allen vorhanden gewesen.
Das bedeutet jetzt übrigens mal wieder einen Rückschritt bei GS, weil man hier nun nicht mehr aufs GPS downloaden kann.

**Comment by Ruko2010** [comment]
Ich weis, aber leider kann man nicht alle Funktionen nachbauen, die GS entfernt. Und wenn ich den Blogeintrag richtig gelesen habe, hat diese Funktion sowieso nicht zuverlässig funktioniert. Ich denke eher die wollen ihr "Send to Garmin Express" pushen und sich von Altlasten befreien.
