### ISSUE TITLE
Error on Cachelisting Page [addElevationToWaypoints_OpenElevation()]

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#847]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2239440/45148473-a0d93d80-b1c7-11e8-8dc1-74851e535066.png)

The Error is displayed and the elevations are not loaded.

**To Reproduce**
It is hard to reproduce, because the error does not occur every time. Last time I seen it on https://www.geocaching.com/geocache/GC7B761_goethe-und-schiller-in-jena-ganz-privat

Maybe it has something to do with the 5 Waypoints and therefore many calls to the elevation service.

**Expected behavior**
See elevation and no error.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 68.0.3440.106

**Comment by CachingFoX** [comment]
I can not reproduce the error. I think is a temporary problem, but...

... I think the elevation service doesn't return a json file. The service returns an HTML page or something else. The error behavior of the OpenElevation service is not very good.

@Ruko2010 @2Abendsegler If you get an error message like the reported one, please can you open the web console and make a screenshot of the error message. In case of error the response data will be printed out. The following screenshots shows the output in case of an error (for testing with good data)

OpenElevation service:
![grafik](https://user-images.githubusercontent.com/1838534/45204516-c590ec00-b27f-11e8-8083-0686e6f0b5ae.png)

Google Elevation service:
![grafik](https://user-images.githubusercontent.com/1838534/45204626-1accfd80-b280-11e8-9407-03b3c17fe64d.png)

I implemented an error handling system, to catch problems with an service. Their is a chain of service which will be tried step by step. If a service doesn't work (returns an error) or an unexpected error (invalid json file, ...) occurs the script tries to contact the next service in the chain (if configured in the settings). After all services are tried without access, the load animation will be stopped and replaced with '(error)' and a tooltip with more information.

In case of unexpected error a message will be print out at the web console, but the chain doesn't stop. But there is an bug in the error handling system which breaks the chain of load elevation data.

Improve the error handling of elevation service again, I implement the method ontimeout(), onerror() and onabort() for GM_xmlhttpRequest(). The error handling is very simple, but I should be helps to see what is happend if one of the callback are called.

**Comment by Ruko2010** [comment]
I can't reproduce the Problem today, but I'll post the console-content if I see it again.

**Comment by CachingFoX** [comment]
I added an workaround for cases if OpenElevation returns malformed data (non JSON data). If the content doesn't start with a {, the next elevation service is called.

Add console output and call the next elevation service if GM_xmlhttpRequest returns with onerror(), ontimeout() and onabort()

If no more elevation services are available. The load animation will be stopped and replaced with ???.

**Comment by CachingFoX** [comment]
In cases of error (???) I need the console output.

**Comment by CachingFoX** [comment]
Today I got also the error. OpenElevation service response:

```
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.13.5</center>
</body>
</html>

```
