### ISSUE TITLE
[EDGE] Tampermonkey - problems (Dropbox)

### ISSUE THREAD

**Issue by DrakMrak** [2Abendsegler/GClh#85]
1. Don't import setting from DropBox - **problem**
2. Don't import setting from Manual Data - **problem**
3. Save settings are OK (after restart EDGE is correct) - **correct** 
Other things working OK I thing...

Problem are only 1) and 2)

_It's not urgent it was just an attempt to EDGE_

**Comment by 2Abendsegler** [comment]
(Only in german, sorry I'm in a hurry, wants to go to the Karvendel for hiking and climbing.)

Unser lieber Kollege [Ruko2010](https://www.geocaching.com/profile/?u=Ruko2010) hat die neue DropBox API zur Synchronisierung der Konfigurationsdaten im GC little helper II eingebaut. Sie steht im Moment als Beta Version zur Verfügung und kann manuell installiert werden. Aus technichen Gründen verbleibt es dabei bei Versionsnummer 0.8.6. 

Die neue Funktionalität kommt regulär vorraussichtlich erst Ende Oktober. 

Nach der Installation der Beta Version kann über den GClh Sync (F10 Taste) eine Synchronisation der GClh Konfigurationsdaten in den eigenen DropBox Account durchgeführt werden. Bei der Authentifizierung wird ein "Token" gespeichert, sodass die Authentifizierung nur einmalig durchgeführt werden muss. Der "Token" kann im Rahmen der GClh Config Funktionalität "Reset / Reset dynamic and unused data" wieder gelöscht werden, so dass man eine Authentifizierung mehrfach testen kann bzw. sich auf unterschiedlichen DropBox Accounts anmelden kann.

Die Beta Version kann [hier](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) installiert werden.
Zurück zur regulären Version kommt man [hier](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js).

Falls ihr mit der Beta Version arbeitet, dann meldet bitte eure Ergebnisse (OKs bzw. Fehler) hier an dieser Stelle.

Vielen Dank an [Ruko2010](https://www.geocaching.com/profile/?u=Ruko2010) für die super Implementierung und die tolle Zusammenarbeit. :)

LG Frank

**Comment by DrakMrak** [comment]
It seems to work well :)
- Login to the dropbox was correct
- Save seting OK
- Load back OK too
- the contents of the .json file seem to be OK
I'll test it on more computers... later

**Comment by DrakMrak** [comment]
Firefox Tampermonkey - OK
EDGE Tampermonkey - OK

**Comment by 2Abendsegler** [comment]
Thanks for your messages.
http://geoclub.de/forum/viewtopic.php?f=117&t=79726&p=1276524#p1276524

You can close it, if you want. 
We implement it with Milestone v0.8.7.

**Comment by 2Abendsegler** [comment]
Firefox Tampermonkey? Really, I think this could not be. You use Greasemonkey, right?

**Comment by GFEMajor** [comment]
Ich mach das hier auch zu. Falls es noch Probleme gibt, einfach wieder öffnen.
