### ISSUE TITLE
New link in dashboard to ignore list does not work with right mouse.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#851]
**Describe the bug**
New link in dashboard to ignore list does not work with right mouse.

**To Reproduce**
1. https://www.geocaching.com/account/dashboard
2. Try right mouse on link ignore list

**Comment by Ruko2010** [comment]
Also a Typo in the alert if no Ignore list is found (please)
![image](https://user-images.githubusercontent.com/2239440/45209232-b4021100-b28c-11e8-9171-93c44798dbda.png)

**Comment by Ruko2010** [comment]
Maybe this will help?
https://stackoverflow.com/questions/12365339/javascript-event-for-open-in-new-tab

**Comment by CachingFoX** [comment]
I will check this

**Comment by 2Abendsegler** [comment]
Ich habe mir das Problem mal angesehen. 

Eigentlich ist die Funktionsweise ähnlich wie wenn ich aus dem Dashboard den Link zum GClh Config mit der Rechten Maustaste / Link in neuem Tab ... aufrufe. Es wird zuerst das Dashboard nochmal in einem neuen Fenster aufgerufen. Erst dort wird der GClh Config aufgerufen. Das Gleiche mach ich nun auch hier. Zuerst Dashboard in neuem Fenster aufrufen und dort dann die Ignore List ID besorgen und falls keine da ist dann Fehlermeldung ausgeben.

Das läuft soweit. Ich stell es mal in einen PR dann könnt ihr es euch mal ansehen.
