### ISSUE TITLE
Preselection map for BRouter does not work.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#852]
**Describe the bug**
Preselection map for BRouter does not work.

**To Reproduce**
1. https://www.geocaching.com/geocache/GC1X2R2
2. Choose BRouter map Outdoors
![grafik](https://user-images.githubusercontent.com/22332216/45179699-8c259580-b219-11e8-98ed-8ed4cd777e8b.png)
3. See wrong map on BRouter
![grafik](https://user-images.githubusercontent.com/22332216/45179780-c2631500-b219-11e8-9c03-f114aa8aba33.png)

**Comment by CachingFoX** [comment]
see also #853.
FloppsMap works

**Comment by CachingFoX** [comment]
URL is wrong: There is an **plus symbol +** after the layer name
http://brouter.de/brouter-web/#zoom=17&lat=42.6256&lon=1.60222&layer=OpenTopoMap+&lonlats=1.60222,42.6256&nogos=&profile=trekking&alternativeidx=0&format=geojson

URL is okay
http://brouter.de/brouter-web/#zoom=17&lat=42.6256&lon=1.60222&layer=OpenTopoMap&lonlats=1.60222,42.6256&nogos=&profile=trekking&alternativeidx=0&format=geojson
