### ISSUE TITLE
Preselection map for GPS Visualizer does not work.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#853]
**Describe the bug**
Preselection map for GPS Visualizer does not work.

**To Reproduce**
1. https://www.geocaching.com/geocache/GC1X2R2
2. Choose GPS Visualizer map Google sattelit
![grafik](https://user-images.githubusercontent.com/22332216/45180028-795f9080-b21a-11e8-8159-f5ae2c7d62a1.png)
3. See wrong map on GPS Visualizer
![grafik](https://user-images.githubusercontent.com/22332216/45180099-b592f100-b21a-11e8-8a1b-ae558946fc60.png)

**Comment by CachingFoX** [comment]
D'oh! I will check and fix it.

**Comment by CachingFoX** [comment]
**Reason**
Layer are not included in URL
