### ISSUE TITLE
Profile (Settings) Shows error

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#854]
**Describe the bug**
I get different Errors on different Accounts:
Our GClh Account throws this (Currently on Safari):
![image](https://user-images.githubusercontent.com/2239440/45218722-e6ba0280-b2a8-11e8-94a1-f065d9ed8d67.png)
My own Account throws this (Currently on Chrome):
![image](https://user-images.githubusercontent.com/2239440/45218777-0fda9300-b2a9-11e8-90ff-c44a1798651e.png)

**To Reproduce**
1. Go to https://www.geocaching.com/account/settings/profile
2. See error

**Expected behavior**
No Error 😃

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome, safari

**Comment by 2Abendsegler** [comment]
case "publicProfile":
            if (url.match(/\.com\/(profile|p\/)/)) status = true;
            break;
Wer hat die ganzen **\.com** rausgemacht? Bitte wieder reinmachen bzw. zurückholen. Es ist ein Unterschied ob profile direkt hinter .com/ kommt oder weiter hinten in der url steht. 

Ich glaube das sind Änderungen die überhaupt nichts mit einem Issue zu tun haben. Man war nur mal gerade in der Nähe des Codings. Menno, so was macht man nicht weil man in der Regel nicht alle Auswirkungen abschätzen kann.

**Comment by CachingFoX** [comment]
@2Abendsegler Doch es gab ein Issue #809 dazu. is_page("dashboard") hat auch bei der Seite "Unpublished Caches" zugeschlagen, da diese Seite eine Unterseite von /dashboard/... ist. Allerdings sollen auch einige Teil des Skriptes auf die Unterseiten von dashboard wirken. Daher habe ich is_page() wie folgt erweitert:

```
        case "dashboard":
            if (url.match(/\/account\/dashboard$/)) status = true;
            break;
        case "dashboard-section":
            if (url.match(/\/account\/dashboard/)) status = true;
            break;
```

Damit sicher erkannt wird, ob wir uns auf dem Dashboard befinden oder auf einer Unterseite muss geprüft werden, ob `/dashboard` am Ende steht oder nicht. Bisher wurde aber gegen location.href geprüft. href enthält hostname, Pfad, Hash und Parameter. Hash und Parameter können nun ein Problem darstellen, wenn wir feststellen wollen, ob wir uns auf dem Dashboard oder einer Unterseite befinden, wenn Hash oder Parameter in der URL stehen.

Ich habe zwei Vorschläge zur Lösung

**Option 1:** Hostname zum Pfad dazunehmen und .com wieder aufnehmen
```
        var url = document.location.hostname+document.location.pathname;
        ....
        case "dashboard":
            if (url.match(/\.com\/account\/dashboard$/)) status = true;
            break;
```

**Option 2:** Nur gegen den Pfad prüfen, dafür aber von Beginn des Strings
```
        var url = document.location.pathname;
        ....
        case "dashboard":
            if (url.match(/^\/account\/dashboard$/)) status = true;
            break;
```

**Comment by CachingFoX** [comment]
@2Abendsegler Bitte review doch beide Lösungsmöglichkeiten. Welche würdest du Vorschlagen?

**Comment by 2Abendsegler** [comment]
Sorry, ich hatte Issue #809 nicht im Blickfeld. 

Ich kann das aber nicht reviewen weil ich nicht ohne weiteres überblicken kann wo die Änderungen überall hinschlagen. Das war genau mein Punkt, dass die Auswirkungen der Änderungen, auch deine jetzigen Vorschläge, nicht abschätzbar sind. 

Bei solchen zentralen Punkten muß die Devise sein, so wenig wie möglich in die bestehenden Programmabläufe einzugreifen, am Besten gar nicht.

Ich hab das jetzt auf die Schnelle mal wie folgt gemacht. "settings" ist immer schon ne Sammelstelle gewesen für alle möglichen Dinge wo nur das Menü und vielleicht noch ein paar Kleinigkeiten vom GClh aufgebaut werden. Das kann ich nun auch hier nutzen. Ich weiß nicht ob das jetzt für alles paßt, ich hab nur mal kurz getestet. Ich mein es spricht auch nicht grundsätzlich etwas dagegen einen neuen Eintrag mit dashboard-section zu machen, eben dann so wie meine Ergänzungen bei "settings".  (Natürlich die .com wieder einbauen.)


        case "settings":
            if (url.match(/\/account\/(settings|lists|drafts|dashboard\/unpublishedcaches)/)) status = true;
            break;
        case "dashboard":
            if (url.match(/\/account\/dashboard/) && !url.match(/\/account\/dashboard\/unpublishedcaches/)) status = true;
            break;
Reicht das nicht vielleicht aus?

**Comment by 2Abendsegler** [comment]
@Ruko2010 @CachingFoX 
Mir fällt noch etwas auf. 
Ich habe etwas sauer reagiert, auch teils bei den anderen Issues die ich alle so hingerotzt habe. Das war nicht angemessen und das tut mir leid. 

Meine Reaktion entstand deshalb, weil ich schon immer fand, dass ich es meinen Kunden nicht zumuten möchte fehlerhaftes auszuliefern. Das war auf der Arbeit so und ist jetzt auch nicht anders. Wenn wir mit jeder Version so viele Fehler einbauen wie wir berichtigen dann wollen einige Kunden den GClh nicht mehr nutzen. Ich gehöre auch dazu. Nun kann man natürlich sagen, dann sollen sie es halt bleiben lassen. Dann stellt sich allerdings die Frage für wen wir den GClh betreiben. Ich nutze nur ganz wenige Scripte, weil mir zuviel "rumgebastelt" wird und die Arbeit die ich dann bei Fehlern habe den Nutzen übersteigt. 

Das was wir mit 0.9.12 ausgeliefert haben, war nach meinem Ermessen nicht mehr in Ordnung. Fehler passieren immer mal, ist schon klar. Fehler wegen ungenügendem Testen sind aber vermeidbar. Wir sollten wieder anfangen anständig und umfänglich zu testen und uns die Codeänderungen ansehen, am Besten nach dem 4 Augen Prinzip.

**Comment by Ruko2010** [comment]
Vielleicht sollten wir uns überlegen ob wir automatisierte Tests einführen können. Auf dem gebiet Javascript weis ich nicht ob es da was gibt, aber zumindest mit Selenium könnte man wenigstens ein paar Sachen abdecken (jede seite einmal aufrufen und prüfeb ob Fehler kommen). Eventuell gibt es auch TestFrameworks, sowas was UnitTest für PHP. Kennt sich da einer von euch aus? Eventuelle bietet Git da auch etwas an?

**Comment by CachingFoX** [comment]
@2Abendsegler Kein Thema. Da die Bugs ja auch wirklich auf meinen Mist gewachsen sind.

@Ruko2010  Unit-Test während wünschen wert. Allerdings interagiert GClh doch nahe zu ausschließlich mit der GC Seite. Für einzelne Funktionen wie z.B. is_page() könnten wir relativ einfach aber trotzdem Test erstellen. Evtl. müssten wir dann aber die Struktur des Skripts ändern. Also aktuell habe ich noch keinen wirklichen Plan wie wir das angehen könnten. 

Ich habe mir ein paar Gedanken gemacht, ich/wie wir in Zukunft dieses Probleme verhindern:

### Risikobewertung der Änderung ###
Schon vor dem Release habe ich mir gedacht, es wäre vielleicht gut/hilfreich, wenn wir als Labels noch eine Risikobewertung bei den Issues angeben könnten. Z.B. 
- risk:low - könnte man für kleine Änderungen nehmen, die keine weiteren Auswirkung haben und lokal begrenzt sind, z.B. Typos, Änderung in einer Funktion die nur einmal verwendet wird, ...
- risk:normal - für Änderungen, die an wenigen Stellen durchgeführt werden, bei der nur wenig Auswirkung auf das gesamte Skript zu befürchten sind, bei einem Fehler sind nur einzelne Features (<=3) von GClh betroffen
- risk:high - für Änderungen, die an zentralen Komponenten / Funktionen wie z.B. is_page(), gemacht werden, die großen Einfluss auf das Skript haben können 

Bei risk:high sollte man seine Änderung im Issue/Pull Request beschreiben

### Anpassung meiner Arbeitsweise ###
Bisher habe ich wie folgt gearbeitet: 
- Ich habe in meinen Clone einen Branch 'collector', den ich regelmäßig aus dem Master aktualisieren. 
- Arbeite ich an einen Feature oder möchte ich einen Bugfix machen, dann aktualisieren ich noch einmal meinen 'collector' und erstelle davon einen Branch (issue-xxx), mache dort die Änderungen. 
- Wenn ich  fertig bin, dann pushe ich die Änderung/den issue-Branch auf Github und stelle einen Pull Request. 
- Anschließend wechsle ich wieder zum meinen 'collector'. 

**Nachteil**:  Die Änderung ist aktuell noch nicht im collector, sondern isoliert in einem Branch. Während meiner täglichen Arbeit mit www.geocaching.com kann ich aber das Feature nicht testen.

Ich habe meine Arbeitsweise wie folgt angepasst: 
- Im Prinzip wie das oben beschriebene Vorgehen
- Für den täglich Betrieb verwende ich nicht mehr den Branch collector, sondern einen separaten Branch privaten Collector names collector-fox'
- Im Anschluss an die Arbeiten an einem Issue merge ich diesen in den privaten Collector

**Vorteil**: Ich kann meine Änderung im täglichen Betrieb mit der Geocaching Seite testen.

Wie geht ihr vor?

###  Verhindern von kurzfristigen Änderungen ###
Änderungen länger im collector "abhängen" lassen.  Änderungen sollten ein bis zwei Wochen im collector sein bevor diese live gehen. D.h. keine großen Änderungen (nur noch Fixes für die gemachten Änderungen) mehr ein bis zwei Wochen vor dem Release.

Normale Änderungen müssen in den nächsten Milestone. Evtl. wäre ich eine Releaseplanung gut.

**Comment by 2Abendsegler** [comment]
Risikobewertung find ich ne gute Idee, sollten wir so machen wie beschrieben.

Zwei Wochen im collector lassen wäre schön, aber ich finde jetzt schon, dass es zu lange dauert bis Fehler, insbesondere die von GS, berichtigt werden. Beispielsweise der aktuelle Fehler in den PQs und Nearest Listen finde ich ziemlich nervig. Das ist jetzt nichts Lebensnotwendiges, man kann den Compact Modus ausschalten und gut wäre. Das mache ich nur nicht, auch weil ich mich so sehr an den Compact Modus gewöhnt habe. Solche Fehler sollten aus meiner Sicht in 2-3 Tagen berichtigt werden, weil sie die Verwendung der gesamten Seite behindern. Noch heftigere Probleme wie vor kurzem die fehlende Möglichkeit zum Speichern der GClh Konfiguration, sollten noch schneller geregelt werden. Lediglich Fehler in einzelnen kleineren Funktionen, wie beispielsweise der Tag beim Event, haben Zeit. Neue Features, so schön es auch ist an ihnen weiter zu arbeiten, sollten hinten anstehen. Zuerst sollten mal die Fehler beseitigt werden ... beim Kunden.
So hatte ich es auch in der Vergangenheit gehandhabt. Das ist natürlich jetzt viel schwieriger, weil GS eben überall und ständig irgendwelche Änderungen macht. Trotzdem wäre das aus meiner Sicht immer noch das Ziel.

Hilfreich wäre meines Erachtens wenn Änderungen so schnell wie möglich im Collector landen. Ich würde dann auch hingehen und immer wieder entsprechend aktualisieren, so dass ich auch die Änderungen im täglichen Betrieb teste. 

Zum persönlichen Vorgehen: 
Ich verwende recht viel Zeit zum Testen. Ich überleg mir welche Szenarien entstehen können und die werden dann auch konsequent durchgetestet soweit das geht. 
Der Grund ist auch ganz einfach: Ich habe absolut keine Lust nochmal an der gleichen Stelle zu arbeiten. Und ich will mich nicht unter Zeitdruck bringen. Solange ich noch bei der Entwicklung bin kann ich mir die Zeit selbst einteilen so wie ich will. Sind die Anpassungen aber schon beim Kunden, entscheidet quasi der Kunde wann ich tätig werden muß. Das mag ich gar nicht. 
Ansonsten arbeite ich immer noch mit dem Tampermonkey Editor, old school. Kein Schnickschnack.
