### ISSUE TITLE
Need to scroll down to see image description in pop-up mode

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#862]
**Describe the bug**
When you click an image thumbnail within a log GCLh loads and displays its bigger version. In case it is large enough it fills up the whole browser window and leaves no space for the image description.

**To Reproduce**
1. open https://coord.info/GCKRQ5
2. scroll down to Janny1977 log from 2018-09-07
3. click the second image from the ones attached to his log
4. you'll see this:
![obrazek](https://user-images.githubusercontent.com/9153595/45409114-9955e080-b66e-11e8-9508-ab723f5e683d.png)

5. now scroll a little bit down and the image description will appear:
![obrazek](https://user-images.githubusercontent.com/9153595/45409245-f3ef3c80-b66e-11e8-8832-ea2908570a71.png)

6. browse left/right for next images and soon you'll find it inconvenient to always have to scroll down to see whether there is a description.

**Expected behavior**
When the description is present display the image a bit smaller to make enough room for the description below. Or display it  as an overlay in the bottom of the picture (above the "View log" button).

**Desktop (please complete the following information):**
 - OS: windows 7 x64 SP1
 - Browser: Firefox
 - Version: 62.0

**Comment by 2Abendsegler** [comment]
It's a new GS feature. :)

**Comment by Ruko2010** [comment]
@2Abendsegler if I disable GClh the picture has a small size and everything is showing up. So it should be an GClh Issue 😉

**Comment by Ruko2010** [comment]
Would moving the fance-box-title over the image a solution?
![image](https://user-images.githubusercontent.com/2239440/45864546-9b105a00-bd7a-11e8-8084-6a4ef8247bc6.png)

**Comment by Ruko2010** [comment]
Or we stick to the GC style overlay and just enlarge the image?!

**Comment by Ruko2010** [comment]
> Do you mean to simply enlarge the entire original Groundspeak box with the image and "View log" and "Print Picture" links and the description underneath?

Yes.
@2Abendsegler I'm not sure why there is a change to the original layout at all? I like it 😃. My suggestion would be to move to the original Layout and just enlarge the image to full screen (if this is possible). What do you say? Or do I miss some dependency here?

**Comment by 2Abendsegler** [comment]
We talk about a bigger screen like a TV screen. The old original used not the whole screen. This was the reason of the development. Pontiac_CZ has such a big screen. Perhaps the new original do it, I do not know. Try it. 
And you know my understanding of our work, do not change a running system without any reason. :)

I'm now unavailable ...

**Comment by Ruko2010** [comment]
I don't speak about the size. My questions was, Why did we change the layout of the enlarged image in first place and not used the one from GC with just a larger image?

But for now, to change as little as possible I will just move the description/buttons.

**Comment by Ruko2010** [comment]
@PontiacCZ I investigated this a little bit and I think this is not a bug, but a feature 😃. In the first line, there is the Name of the picture and with scrolling down you can read the description.
Are you sure, that this has been changed? I installed an old version of GClh and saw the exact same output.
Problem with you example image is, that there is no image title entered, only a description.
![image](https://user-images.githubusercontent.com/2239440/45880541-877be800-bda8-11e8-8d7e-8fc03921b93e.png)
![image](https://user-images.githubusercontent.com/2239440/45880544-8ba80580-bda8-11e8-9448-7bbaa64084fd.png)

**Comment by Ruko2010** [comment]
You can try this when you install my dev-branch: https://github.com/Ruko2010/GClh/raw/bug/issue-862_imageDescription/gc_little_helper_II.user.js

**Comment by PontiacCZ** [comment]
I am testing it, looks good. The description is now in one line with "View log" link which I don't mind. 

But I have run into another issue with longer description - when the description does not fit within the screen width, the browser creates a scroll bar which partly covers the text.

![obrazek](https://user-images.githubusercontent.com/9153595/45886455-7c7d8380-bdb9-11e8-8fd2-984d1439a37e.png)

**Comment by Ruko2010** [comment]
Ok, I found the issue. I was always wandering why the title was showing "outside" of the box, when it should be displayed "inside", like GC does it initially. I was a typo. Somebody who wrote the code wrote "titlePostion" instead of "titlePosition".

@PontiacCZ 
I pushed it to the same branch, can you please re-install https://github.com/Ruko2010/GClh/raw/bug/issue-862_imageDescription/gc_little_helper_II.user.js 
and check the result?

**Comment by Ruko2010** [comment]
I think this is the default behavior of the fancybox extension Groundspeak uses. I see no option in the fancybox extension which could handle this different. So If you could live with this solution, I will close the issue.

**Comment by PontiacCZ** [comment]
You're right, that is its default behavior, just verified it with Tampermonkey off. But at least one can see that there's a description taking more than one line (rare situation anyway) and can scroll down if he desires to.
Thank you for your time and great work and I am actually closing it myself right away. :)
