### ISSUE TITLE
Activate "Run this query every week on the days checked" when checking weekday

### ISSUE THREAD

**Issue by c-h-b** [2Abendsegler/GClh#864]
**Describe the solution you'd like**
When checking a weekday **in the list of pocket queries**, I'd like the option "Run this query every week on the days checked" to be activated automatically.
Perhaps this behaviour could be controlled by a GClh Config II setting.

**Comment by Ruko2010** [comment]
@c-h-b Isn't it easier to check this option when creating the PQ? If you do not select a weekday on creation it will not be created, but if you then later check the weekday in the list of PQs, it will be enabled.

**Comment by c-h-b** [comment]
@Ruko2010 This is true, but when I generate 34 new PQs with your great new tool "Generate PQs from Output of Project-GC PQSplit", I have to check the weekdays subsequently. For selecting the "every week" option, each PQ has to be edited individually. If the option could be set automatically when checking the weekday in the list (especially with the "compact layout"), it would be a big simplification.

**Comment by c-h-b** [comment]
Ah, I see and understand your point. I'm glad to hear that the feature is on your list. No need to hurry, as my PQs are now configured correctly (after forgetting to set the weekly option at first and wondering why the PQs were not generated in the following week :o) ).
Thank you for your great work!

**Comment by Ruko2010** [comment]
I added it to this ticket, if you want to follow: https://github.com/2Abendsegler/GClh/issues/861
