### ISSUE TITLE
Small map does not show up

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#865]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2239440/45750437-5e741f80-bc0f-11e8-8f55-4758dd52772c.png)
Looks like an Key-Issue?

**To Reproduce**
1. Go to any Listing
2. See error

**Expected behavior**
Small Map shows up.

**Comment by Ruko2010** [comment]
hmm...I faced this problem on several cache pages, but now they are all working again. Maybe a temporary Problem that solves itself 👍

**Comment by Mitchsa** [comment]
Problem still exists.

With me it shows the error message for each listing.

**Comment by Ruko2010** [comment]
I'm also facing this problem again. I'll reopen this one.

**Comment by CachingFoX** [comment]
Google sends an error message with the image. Use the development tools to analyse the error message in answer header of the image request.

I think Google has restricted the limit of static maps without key.

CachingFoX

**Comment by Ruko2010** [comment]
Google has not only restricted the API Limit, it has completely removed (free) calls without key. I'm not sure why this map is working at all (at the start of the day):
https://developers.google.com/maps/documentation/maps-static/usage-and-billing

We should consider removing this map or switch to another (free) map service for it.

**Comment by MarcusBi** [comment]
Es ist tatsächlich so,dass es malgeht, dann mal wieder nicht. Wegen der Umstellung der Lizenzbedingungen seitens Google für den  Zugriff auf ihre Maps macht es natürlich Sinn, auf einen andere Karte zu wechseln. Allerdings fände ich die Möglichkeit auch ganz gut, wenn man seinen "eigenen" Google-API-Key (soweit vorhanden) in den Optionen eingeben könnte und die Benutzung der GoogleMaps somit weiterhin möglich wäre...

**Comment by Ruko2010** [comment]
@MarcusBi Ich glaube die wenigsten Leute haben einen eigenen API-Key für Google. Darum macht es denke ich mehr Sinn auf einen anderen Kartenanbieter zu wechseln.

**Comment by MarcusBi** [comment]
Da hast du zu 100% Recht. Ich dachte auch eher an eine zusätzliche Möglichkeit...
(ok...es ist nur,weil ich zu faul bin nach jedem Update meinen API-Key ins Script reinzuhämmern :)

Über kurz oder lang kann ich mir allerdings vorstellen, dass andere Kartenanbieter ebenfalls auf einen Key umstellen werden (MapBox, Bing, ...)

**Comment by Ruko2010** [comment]
Wenn ich es richtig sehe, dann kann man bei Bing als "Not-for-profit" 50000 Transaktionen (also Maps) pro Tag darstellen. @2Abendsegler wäre das eine Überlegung wert dorthin zu wechseln?

![image](https://user-images.githubusercontent.com/2239440/46606911-47826800-caff-11e8-9e38-9a73c1d28ae5.png)

**Comment by CachingFoX** [comment]
c:geo läd doch auch static maps von Google. Wie wird geht c:geo damit um?

**Comment by CachingFoX** [comment]
Wäre OSM eine Alternative? 
http://staticmap.openstreetmap.de/

**Comment by CachingFoX** [comment]
OSM static map is already used in PQ settings.

**Comment by CachingFoX** [comment]
OSM static map has also restricted the access:

See edit pocket query:

![grafik](https://user-images.githubusercontent.com/1838534/46674129-addcb880-cbdb-11e8-8bd3-6dd6033d2a50.png)

**Comment by Ruko2010** [comment]
Gerade bei GC Tour gesehen, die sind auf https://leafletjs.com/ umgestiegen.

**Comment by CachingFoX** [comment]
Also eine echte Karte. Mit Leaflet.js habe ich schon einige Erfahrung. Ich kann mich daran probieren.

**Comment by Ruko2010** [comment]
Vielleicht kann man damit auch eine statische Karte machen?
Ich hab mir die Sache noch nicht genau angeschaut

**Comment by CachingFoX** [comment]
Scheinbar ja: https://chriswhong.github.io/static-leaflet-example/ -- Aber ich sehe da kein Vorteil. Es wird einfach der dragging mode deaktiviert.

**Comment by Ruko2010** [comment]
:). Das hab ich auch gerade gefunden. Aber du hast recht. Das Dragging zu deaktivieren bringt keinen Vorteil, da können wir es auch an lassen. Da die Map aber recht klein ist, würde ich alle controls ausblenden.

**Comment by CachingFoX** [comment]
Habe etwas mit dem Framework leaflet.js experimentiert. Für die PQ settings sieht es schon ziemlich gut aus:

![grafik](https://user-images.githubusercontent.com/1838534/46791892-5d339f80-cd42-11e8-8d48-c31c62556af5.png)

implementiert
* Koordinaten sind Kartezentrum / Karte kann nicht verschoben werden
* Marker im Zentrum / Karte ist zentriert
* Radius
* Automatischer Zoom (best fit)
* Manuelles Zoomen
* Map Style: Mapnik
* Karte wird nur bei der Option "By Coordinates" angezeigt. Bei allen anderen Optionen wird die Karte ausgeblendet
* leaflet.js/leaflet.css wird nur bei Bedarf geladen

geplant
* (geplant) Map Style kann in Settings ausgewählt werden

**Comment by LittleJohn-DD** [comment]
>  Update meinen API-Key ins



> 
> 
> Da hast du zu 100% Recht. Ich dachte auch eher an eine zusätzliche Möglichkeit...
> (ok...es ist nur,weil ich zu faul bin nach jedem Update meinen API-Key ins Script reinzuhämmern :)
> 
> Über kurz oder lang kann ich mir allerdings vorstellen, dass andere Kartenanbieter ebenfalls auf einen Key umstellen werden (MapBox, Bing, ...)

WIe und wo kann ich das im script ändern?

**Comment by Ruko2010** [comment]
@CachingFoX das sieht schonmal gut aus! Bin gespannt 😃.

@LittleJohn-DD such einfach im Script nach `maps.google.com/maps/api/staticmap` und hänge ein neuen Parameter dran: `&key=YOURAPIKEY`
Beispiel (ca. Zeile 2160):
`var url = 'url(' + http + '://maps.google.com/maps/api/staticmap?zoom=' + zoom_value + '&size=248x248' + '&maptype=roadmap&'`
ändern in:
`var url = 'url(' + http + '://maps.google.com/maps/api/staticmap?zoom=' + zoom_value + '&size=248x248' + '&maptype=roadmap&key=YOURAPIKEY&'`

**Comment by Ruko2010** [comment]
- [ ] Cachelisting: Small Map
- [ ] Map on create pocket query page.

**Comment by Ruko2010** [comment]
@CachingFoX ich habe nur die beiden Vorkommen gefunden (hab mal ne Checkliste angelegt). Ist dir noch mehr aufgefallen, oder sind das die einzigen Vorkommen einer statischen Karte die nicht mehr gehen?

**Comment by CachingFoX** [comment]
@Ruko2010 Ich habe auch nicht mehr Stellen an den eine statische Karte genutzt wird gefunden.

**Comment by CachingFoX** [comment]
# Settings modifications
## added (Default value)
- settings_pq_previewmap (true)
- settings_pq_previewmap_layer (Geocaching)
- settings_map_overview_layer (Geocaching)
## removed
- no

# Script Header modifications
- new resources leaflet js and css version 0.7.2
- new grant: GM_addStyle

# Modifications gclh_data.js
- yes, added two new base64-coded pictures (map_marker, map_marker_shadow)

# File modifications
- add two new files data/leaflet.js and data/leaflet.css (version 0.7.2)

# Critical modifications 
- replace section "get access token" from map page modification with an own function gclh_GetGcAccessToken(). The function will be also used for preview map on cache page and pq settings
- extend function injectPageScript() with an 3rd parameter to set the id attribute. The new parameter is optional to give backward compatibility 

# Additional information
- Very old version (0.7.2) of leaflet is used, because Groundspeak use this version

**Comment by CachingFoX** [comment]
![grafik](https://user-images.githubusercontent.com/1838534/46978627-c06d5b00-d0cf-11e8-8c81-2ad6c349c5dc.png)
Preview map on PQ settings can be enabled/disabled. Map layer can be configured. The zoom level with the best fix will be used.
 
![grafik](https://user-images.githubusercontent.com/1838534/46978749-088c7d80-d0d0-11e8-9ed9-5fb83b2172b6.png)
Map layer can be configured for overview map in cache listing. Set the zoom level is not new.

In both cases:  If the Geocaching default layer is used, an access token have to be requested to get the tiles of the slippy map. Therefore the OSM layer will be loaded first and after the token is retrieved the OSM layer will be replaced with the Geocaching.

**Comment by 2Abendsegler** [comment]
Ich hab mir die Karten im Listing und in den PQs nun auch mal angesehen. Feine Sache, dass man nun die Karte wählen kann!

Hab noch zwei Kleinigkeiten:

1. Bei mir gibts in den PQs folgende Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/22332216/49988535-637b0d80-ff77-11e8-952f-df8b6708694d.png)
FF 62.0.3 (64-Bit)
Win 8.1
GClh v0.9.13 aus collector vom 14.12.

2. Kann man vielleicht die Kartenbeschreibung etwas verkleinern, ansonsten werden bei langen Kartennamen ... mehr als eine Zeile benötigt wie folgt:
![grafik](https://user-images.githubusercontent.com/22332216/49988728-2a8f6880-ff78-11e8-9b70-ee5a14a7a46b.png)

**Comment by 2Abendsegler** [comment]
Zu 2. Erledigt

![grafik](https://user-images.githubusercontent.com/22332216/50109294-a539db80-0237-11e9-9bce-3a828d8af119.png)
