### ISSUE TITLE
Persönliches Foto als Avatar

### ISSUE THREAD

**Issue by V60GC** [2Abendsegler/GClh#867]
Ich schreibe das in Deutsch, in Englisch könnte dummes Zeug herauskommen :-(

**Describe the solution you'd like**
Ich habe von vielen meiner Freunde persönliche Fotos, die ich in meinem Adressbuch eingebaut habe. Diese Fotos liegen auf dem Rechner alle in einem festen Verzeichnis. Der Dateiname ist (bei Cachern) der Cachername.
Es wäre schön, wenn diese Fotos als Alternative zum Avatar auch in den Webseiten von GC  eingeblendet werden könnten.

Guat Goan
V60

**Comment by Ruko2010** [comment]
Daten von der Festplatte abgreifen wird schwierig. Was gehen könnte wäre die Bilddaten in Base64 zu konvertieren und dann irgendwo zu speichern.
@2Abendsegler was hälst du von der Idee?

**Comment by V60GC** [comment]
Hmm, die Codierung wäre kein Problem (für mich). Das "irgendwo speichern" heißt aber wohl "Cloud". Und das ist für mich, gerade wenn es um personenbezogene Daten, wie es nun einmal Portraits sind, geht, ein NoGo. Bei allen Clouds, die ich für privat kenne, ist der Zugriff der amerikanischen Behörden gesichert, da diese fast alle in USA hosten. 
Ich bin datenschutzmäßig beruflich tätig, daher meine Vorbehalte. :-(

Nun noch eine technische Frage:
Wo liegt das Problem mit dem Festplattenzugriff. Auch JavaScript kennt Filehandlingfunktionen. Gibt es Einschränkungen mit den Interpretern oder schränken die Browser aus nachvollziehbaren Sicherheitsgründen das mittlerweile ein?

**Comment by 2Abendsegler** [comment]
Umwandlung in Base64 ist natürlich prima Idee.

Der Effekt ist sicherlich nett, wird aber wohl nur ganz vereinzelt genutzt werden. 

Der Aufwand ist nicht gering. Der Avatar steht im Cache Listing und in den Profilen alt und neu. Vermutlich ist auch eine passende Grösse ein Thema, damit nicht verzerrt. Beim hovern überm Avatar muss dann vielleicht auch was geändert werden, weiß nicht. Speicherung im config, ansonsten muss hier noch was im Sync erweitert werden. Andererseits macht das die configdaten völlig unleserlich. Also vielleicht doch woanders ohne Sync.  

Ich würde die Entwicklung wahrscheinlich nicht durchführen, weil der Zugewinn in keinem Verhältnis zum Aufwand steht. 

Aber irgendwie fancy ist es schon mit der Umwandlung in Base64 und so.

**Comment by Ruko2010** [comment]
Also mein Plan wäre so gewesen (rein das hinzufügen):
- Unter dem Profilbild ein Upload Button bei dem ein Bild ausgewählt werden kann
- Beim Upload wird das Bild in Base64 codiert und das Bild an sich weggeschmissen. Das base64 wird dann in der Config selbst gespeichert (@2Abendsegler  am besten ein Array aus username oder ID und dem base64 des Bildes, oder?).
So sind die Daten nur lokal bei jedem Benutzer gespeichert (außer natürlich wenn er den Dropbox-Sync nutzt).

Ich sehe es aber auch so, dass der Aufwand für das austauschen des Bildes im Listing/Log/Profil und wo noch immer sehr hoch ist. Also entweder etwas für die Winterstunden oder aber gar nicht...

**Comment by Ruko2010** [comment]
Oder wir legen das in einer anderen Datei ab, und syncen die nicht. Dann wäre es nur lokal. Nur müssten es die User dann auf jedem Rechner einrichten.
Man könnte auch noch einen Konfigwert hinzufügen, ob das über Dropbox mit gesynct werden soll oder nicht.

Aber so oder so ist das viel Aufwand für ein Gimmick 😃

**Comment by V60GC** [comment]
Nice to have ;-)

**Comment by Ruko2010** [comment]
jo. Ich würd es auf jeden Fall mal auf Prio Niedrig drin lassen. Wenn wir Zeit haben machen wir mal ein ProofOfConcept

**Comment by 2Abendsegler** [comment]
`Unter dem Profilbild ein Upload Button` Super Idee
`Array aus Guid und base64 des Bildes` Ja. Den Usernamen nicht mehr verwenden, blank hinten im Usernamen und Sonderzeichen, macht nur wieder unnütz Probleme.

Man könnte dann auch noch einen Configwert machen, am Besten so einen Schieber, mit dem der User angeben kann wie gut er Handstand machen und dabei jodeln kann ... jahahaha. Machs in die Configdatei und gut is. :)

**Comment by Ruko2010** [comment]
`Man könnte dann auch noch einen Configwert machen, am Besten so einen Schieber, mit dem der User angeben kann wie gut er Handstand machen und dabei jodeln kann`
🤣

**Comment by 2Abendsegler** [comment]
Wir schließen alle Issues die älter als ein Jahr sind und nie bearbeitet wurden. Vorerst setzen wir sie ins Lager, damit sie noch auffindbar sind.
