### ISSUE TITLE
Flopps Maps Link in Listing: Link to Google Maps Satellite not working

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#868]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2239440/45821210-ebd77280-bce8-11e8-9fdb-28caae77686d.png)

The Link to Google Maps is working (Linking to "Map")
The Link to Google Maps Hybride is Linking to the "Satellite" on Flopps
The Link to Google Maps Satellite Links also to "Map"

So the last Link should be removed and Hybrid should be renamed to Satellite

**Comment by Ruko2010** [comment]
Also, there are two entries for terrain, so one of them is missing in the map layer definition:

`'terrain':{ maxZoom: 20, displayName: 'Google Maps Terrain' }, 'terrain':{ maxZoom: 20, displayName: 'Google Maps Satellite' }}`

**Comment by Ruko2010** [comment]
I correct my previous statemant. Not "also", this is the bug. Fixing the Label fixes this bug.

**Comment by CachingFoX** [comment]
I think I have already fixed this in another pull request.

**Comment by Ruko2010** [comment]
I did not see it in a PR (even the open ones). Maybe you fixed it just locally?

**Comment by Ruko2010** [comment]
I'll merge it in the collector, so it should do no harm if you have already fixed it in your local repo

**Comment by CachingFoX** [comment]
Sorry my mistake. There is no fix from me side for this bug.

**Comment by Ruko2010** [comment]
ok, but from me 😃
