### ISSUE TITLE
Cachename und Link in Mailvorlage

### ISSUE THREAD

**Issue by V60GC** [2Abendsegler/GClh#873]
Wenn man aus einem Cachlisting heraus einem VIP eine Mail schicken möchte, wäre es hilfreich, wenn man zusätzlich zum Name "Hi xyz," auch noch den Cachename und dessen Link vorgegeben bekäme. Denn meistens will man dem Empfänger ja etwas von dem Cache berichten.

Viele Grüße
V60

**Comment by Ruko2010** [comment]
Die Idee ist gut. Hast du eine Idee, was genau dort stehen sollte?

**Comment by V60GC** [comment]
Es darf auch gerne Subject: Cache "xyz......
lauten. ;-)

**Comment by Ruko2010** [comment]
Mal schauen was sich tun lässt. Natürlich müssen wir es auf Englisch machen 😉. Die Vorlage macht ja an sich nur Sinn, wenn man sich auf einer Cache-Listing Seite befindet, richtig? Denn sonst hat man ja keinen Bezug zu einem Cache.

**Comment by V60GC** [comment]
Genaauuu

**Comment by V60GC** [comment]
Öhh, mmmhh, ja, wenn das so ist.......

können wir das Thema hier beenden. 
Passiert genau das, was ich mir gewünscht habe. 

Ich entdecke fast jeden Tag neues an diesem Tool. Und manchmal muss ich mit der Nase draufgestoßen werden.

Danke
V60

**Comment by V60GC** [comment]
Es funktioniert wie ich es mir vorgestellt habe. Und wahrscheinlich ist noch mehr möglich, wenn man die diversen Variablen sieht. 
Das ist Super.

Aber wenn ihr noch Arbeit sucht: Ich könnte mir dann als Premiumversion noch so etwas vorstellen:

#if# #GCTBName# not null then "Betrifft den Cache #GCTBName# #GCTBLink#" else "" #endif#

**Comment by Ruko2010** [comment]
Siehte, da lern selbst ich noch was 😃. Ich wusste auch nicht, dass das geht 😉

**Comment by 2Abendsegler** [comment]
Gut dass wir drüber gequatscht haben ...

**Comment by Ruko2010** [comment]
Jup. Hab auch gleich mal ne Vorlage angelegt 😃. Ich nutz wahrscheinlich selbst nur 40% von dem was der GClh kann ^^

**Comment by V60GC** [comment]
Hahaha,
wenn die Entwickler noch nicht einmal alle Funktionen kennen, dann muss ich mich ja nicht schämen. 😉

**Comment by Ruko2010** [comment]
Ich bin auch erst vor gut einem Jahr zum Entwicklerteam gestoßen 😉. Ich war vorher auch "nur Nutzer". Da war das Script schon ziemlich weit fortgeschritten. Daher kenne ich viele Sachen auch nicht, immerhin hat das Tool knapp 12000 Zeilen 😉. Darum finde ich es auch schön immer mal wieder auf neue Sachen gestoßen zu werden und darum tauschen wir uns auch rege über Lösungen aus. Einer kennt sich hier aus, der andere da.
Aber schämen musst du dich auf keinen Fall 😉. Man kann nicht alles wissen.

**Comment by Ruko2010** [comment]
@V60GC kann das damit geschlossen werden?
