### ISSUE TITLE
Read the audit log Seite 

### ISSUE THREAD

**Issue by V60GC** [2Abendsegler/GClh#874]
Auf der Read the audit log Seite wäre es schön, wenn hinter den Namen noch die VIP Logos stehen würden. Und je nach Status der Zeilenhintergrund unterschiedlich eingefärbt würde.
Wie schon oben geschrieben: Nice to have ;-)

**Comment by Ruko2010** [comment]
Kannst du noch einen Link posten? Was genau ist die "Read the audit log Seite"?

**Comment by V60GC** [comment]
Das wird nicht funktionieren. Und ich habe schon befürchtet, dass diese Seite sehr unbekannt ist ;-). Selbst unter denen, denen diese Seite(n) zur Verfügung stehen.

Es ist eine Seite, die dem Owner eines "Premiumcaches" zur Verfügung steht. Dort wird angezeigt, welcher Cacher sich die Seite wann und wie oft angesehen hat. Also, so eine art NSA-Seite ;-)
Wenn Du bzw. Ihr noch keinen Premiumcache gelegt habt, wird das schwierig mit der Umsetzung. :-(

![unbenannt](https://user-images.githubusercontent.com/43401329/45948242-74ab2280-bff7-11e8-9736-5606b5d589f7.JPG)

**Comment by Ruko2010** [comment]
Die Seite kannte ich noch gar nicht. Einen PMO-Cache habe ich auch gelegt, also kann ich das testen/umsetzen, aber ich war auf der Seite wirklich noch nie. Darum ist es wichtig immer einen Link (oder die Schritte wie man da hin kommt) zu beschreiben 😉.
Ich nehm es mit auf und werde mich drum kümmern.

**Comment by Ruko2010** [comment]
So in etwa?
![image](https://user-images.githubusercontent.com/2239440/45974812-cdec7380-c042-11e8-90a7-ac8d2d42db85.png)

**Comment by V60GC** [comment]
Genau so hatte ich mir das vorgestellt.
Und die Uhrzeit vielleicht noch in UTC ;-)

Danke
V60

**Comment by Ruko2010** [comment]
Die Uhrzeit kommt ja direkt von GC, da fummel ich mal lieber nicht dran rum 😃. Die aktuelle Anpassung nehm ich mit ins nächste Release.

**Comment by Ruko2010** [comment]
@V60GC nur so für mich, für was nutzt du diese Seite denn?

**Comment by V60GC** [comment]
> Die Uhrzeit kommt ja direkt von GC, da fummel ich mal lieber nicht dran rum 😃. Die aktuelle Anpassung nehm ich mit ins nächste Release.

In den Listings steht unten mittlerweile die Pazific Daylight Time und GMT drin. Da mir das erst die letzten Tage aufgefallen war, dacht ich, dass das von euch da eingebaut wurde. Daher meine Idee das auch anderswo einzubauen. OK, dann legen wir das Thema zu den Akten.
