### ISSUE TITLE
Selection in Message Center is not visible in Firefox

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#878]
**Is your feature request related to a problem? Please describe.**
If you select text in the message Center in FF nothing is visible.

**Describe the solution you'd like**
Selection should be standard color, so you can see what you select.

**Comment by Ruko2010** [comment]
Solution is 
`::-moz-selection {background: #ff0000; color: #ffffff;}`
I have to determine on which pages this should be implemented.

**Comment by Ruko2010** [comment]
I decided to implement it on all pages, because it was missing on so many pages. The downside of this is, that now GClh chooses the color of the selection and not the browser any more. But since I just used "::-moz-selection" it will only effect "gecko"-browsers like Firefox

**Comment by barnoldGEOC** [comment]
I had the impression this was already solved by GC. For me at least averything worked fine again.
see [this gc forum post](https://forums.geocaching.com/GC/index.php?/topic/349848-please-restore-blue-selections-in-ff-and-safari/)

**Comment by Ruko2010** [comment]
Thanks @barnoldGEOC. Than I can remove the coding that fixes this GC Bug. I have testet it without GClh and can confirm, that the highlight color is back.
