### ISSUE TITLE
PQ-Splitter: Problems with Firefox Popup-Blocker

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#886]
**Describe the bug**
The PQ Creation is not stable if the internal Firefox Popup Blocker is activated.

**To Reproduce**
1. Go to https://project-gc.com/Tools/PQSplit?multi_countryregion%5B%5D=Germany%7CTh%C3%BCringen&submit=Filter
2. Make sure the Popupblocker is *enabled*
3. Click on "Create PQ(s)
4. 5 Popups will be opened, if the first of them is closed, the PopupBlocker is activated and breaks the execution.

**Additional context**
Note for me: Possible solution is to check for popup[i] = null

**Comment by Ruko2010** [comment]
https://stackoverflow.com/questions/668286/detect-blocked-popup-in-chrome/1089792#1089792

**Comment by Ruko2010** [comment]
Ich hab mich heute mal damit beschäftigt. Ich habe zwei Lösungen gefunden. Beide finde ich nicht optimal, aber wenigstens etwas kontrollierter. Aktuell bricht FF nach dem ersten Popup ab und zeigt den gelben Balken mit dem Popupblocker an.

1. Lösung: Alle Popups werden im Hintergrund angefragt. Wenn der User die Anfrage für die Popups dann freigibt, dann werden alle verbliebenen Popups gleichzeitig geladen.

2. Lösung: Es wird nach dem zweiten Popup abgebrochen und es wird eine Meldung mit folgendem Text angezeigt: "We detected a Popup Blocker. Please allow Popups for this site, reload the page and try again. Please be aware, that the first two PQs are already be created, so please go to Geocaching.com and delete them."
Der user muss also Popups freigeben und die Seite neu laden. Dann klappt es beim zweiten Lauf. Der User muss dann nur die zwei schon erzeugten PQs wieder löschen.

@2Abendsegler Ich würde gern eine der beiden Lösungen einbauen. Welche findest du besser? Diese Sache tritt ja nur auf, wenn der User das erste mal diese Funktion nutzt. Ab dem zweiten mal sind die Popups dann frei gegeben und das normale Script läuft durch.

**Comment by 2Abendsegler** [comment]
Sorry für die späte Antwort!

Was meinst du bei 1. mit "werden im Hintergrund angefragt"?
Darüber hinaus scheint mir die Lösung doch gut. Oder könnte das gleichzeitige Laden der Popups Probleme machen?

**Comment by Ruko2010** [comment]
> Sorry für die späte Antwort!

kein Problem

> Was meinst du bei 1. mit "werden im Hintergrund angefragt"?
> Darüber hinaus scheint mir die Lösung doch gut. Oder könnte das gleichzeitige Laden der Popups Probleme machen?
Wir hatten das am Anfang mal, dass alle Popups gleichzeitig aufgehen. Das geht bei 5 oder 10 Popups (noch) gut, aber bei 30-40 wird das schwierig. Darum hatte ich damals die Abarbeitung in 5er Schritten implementiert.

**Comment by 2Abendsegler** [comment]
> Wir hatten das am Anfang mal, dass alle Popups gleichzeitig aufgehen. Das geht bei 5 oder 10 Popups (noch) gut, aber bei 30-40 wird das schwierig. Darum hatte ich damals die Abarbeitung in 5er Schritten implementiert.

Ich verstehe den Ablauf noch nicht. 😕 
Das mit den 5er Schritten scheint mir doch in Ordnung. Warum kannst du das nicht beibehalten?
Nochmal zum "Hintergrund". Werden die Popups unsichtbar im Hintergrund per iframe im aktuellen Screen durchgeführt oder wie?

**Comment by Ruko2010** [comment]
Ok, ich versuchs nochmal zu erklären. Wenn kein Popup-Blocker aktiv ist, dann ist alles schick. Dann werden die Popups immer schön so erzeugt, dass maximal 5 Stück gleichzeitig da sind. Die werden nicht im Hintergrund geladen, sondern ganz normal, wie ein Popup.
Problem ist wenn der Popup-Blocker aktiv ist. Dann wird das erste Popup auf gemacht und dann springt der Blocker ein. Das zerschießt leider den ganzen Ablauf. Darum gäbe es wie gesagt die zwei Lösungen von oben. 
Während der Blocker einspringt, kann man aber weitere Popups öffnen, die aber nicht geöffnet werden, sondern im Hintergrund gehalten werden. Wenn man das aber macht, dann kann man nicht mehr testen wie viele offen sind, da die ja nicht geöffnet werden. Darum geht es nur, alle anzufragen, und die werden dann alle zusammen geöffnet. Das ist aber wie gesagt schlecht bei vielen Popups.

Darum fände ich die zweite Lösung besser. Aber dann muss der User halt die erste erstelle PQ wieder löschen, da die beim zweiten mal ja nochmal erzeugt wird.

War das verständlich?

**Comment by 2Abendsegler** [comment]
Ja, verstehe, danke.
Jetzt verstehe ich auch warum beide Lösungen nicht wirklich optimal sind.
Ich finde nun auch dass die zweite Lösung sich besser anhört.

**Comment by Ruko2010** [comment]
ok, dann werd ich das so einbauen. Wann willst du die neue Version rausschmeißen?

**Comment by 2Abendsegler** [comment]
Wollte sie schon längst draußen haben. Ich wollte jetzt nur noch ne Kleinigkeit machen und sie dann morgen oder so raushauen. 
Wenn du deine Sachen noch mit rein haben möchtest, können wir aber auch noch warten.

**Comment by Ruko2010** [comment]
Nee, heute komm ich nicht mehr dazu. Wahrscheinlich erst am Donnerstag. Also hau ruhig raus. Ist ja nicht all zu dringend.

**Comment by 2Abendsegler** [comment]
Merged
Changelog maintained
