### ISSUE TITLE
Log inline and PMO log inline on listing do not work.

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#888]
**Describe the bug**
The Inline Log window is placed right under the logs. So when the script scrolls down to the window it will slide down, because more logs are loaded.

![kapture 2018-10-10 at 13 31 37](https://user-images.githubusercontent.com/2239440/46733514-da9ed780-cc90-11e8-9a42-b2f05d118f26.gif)

Maybe we should consider moving the inline Log frame above the logs to avoid this.

**Comment by 2Abendsegler** [comment]
Das ist ein Bug. Der Logscreen ist einfach etwas nach unten gerutscht.
