### ISSUE TITLE
Development / Workflow

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#893]
@CachingFoX @2Abendsegler 
Wir hatten letztens das Thema, wie wir Bugfixes / kritische Änderungen schneller "zum Kunden" bekommen. Ich habe mir ein paar Gedanken zum Thema gemacht und denke, dass das "Git Workflow"  Konzept sehr gut zu uns passen würde. Hier gibt es dazu ein gutes Thema, das auch einiges Bildlich verdeutlicht. https://infos.seibert-media.net/display/Productivity/Git-Workflows+-+Der+Gitflow-Workflow
Wir müssten dafür nicht mal all zu viel in unserem Repo umstellen, sondern nur etwas "unseren Workflow" anpassen. So wären kritische Bugs schneller behoben und wir müssten nicht immer auf einen neuen Release warten. Ich denke aber, dass es gerade für dich @2Abendsegler eine Umstellung wird, da wir dann viel mit Branches arbeiten (so wie CachingFox und ich das ja schon tun).

Als eine Änderung würde ich daher vorschlagen, die Versionsnummer wenn nötig um eine Stelle zu erweitern. So wäre v0.9.13 die aktuelle Version. Sollte ein Bug schnell gefixt werden müssen, so erhöht sich nur die letzte Stelle, die wir beim ersten Bugfix-Release hinzufügen. Also bekommt das erste Bugfix Release dann die Nummer v0.9.13.1. Das nächste Feature Release würde wieder die v0.9.14 bekommen.
Der Collector wäre weiterhin unser development Branch und die Features werden in separaten Feature-Branches (die vom Develop forken) entwickelt.
Wenn eine Version vorbereitet wird (Changelog schreiben, Screenshots hinzufügen, Versionsnummer erhöhen, Flag Counter setzen, usw.) dann machen wir einen Folk vom aktellen Collector in eine Release Branch. So kann im collector  weiter gearbeitet werden.
Hotfixes ("kleinere" Bugs) forken direkt vom Master und werden auch direkt wieder da rein gemergt (mit Erhöhung der letzten Stelle der Versionsnummer).
Features werden dann in regelmäßigen Abständen im Feature releases veröffentlicht.

Was haltet ihr davon? Gibt es Fragen, Änderungen, Anmerkungen?

**Comment by 2Abendsegler** [comment]
Die Abläufe beim Mergen werden etwas komplizierter und man kann auch etwas vergessen ohne dass es auffällt. Vergißt man beispielsweise den Merge vom Hotfix zum Collector fällt das gar nicht auf, noch nicht mal beim nächsten Release. Es fällt erst dann auf wenn Änderungen an gleicher Stelle in den Master gehen, der Hotfix wieder weg ist, und der Fehler wieder auftritt. 
Wenn man nicht im Thema drin ist, wird es schwieriger ein Hotfix oder auch ein Release an die User zu geben. 
In einer Systemumgebung mit vielen Entwicklern, Projekten geht es vermutlich nicht anders, aber bei uns ... hmm. 

Wenn der Collector nur vollständige und approvte Änderungen enthalten würde, könnte man auch jederzeit eine neues Release mit einem Hotfix raushauen. So hatte ich es gemacht.

Natürlich ist dein Vorschlag viel eleganter und professioneller. 
Und, ich kann damit leben. 
Notwendige Änderungen an meiner Arbeitsweise kann ich jetzt auf Anhieb nicht erkennen.

**Comment by Ruko2010** [comment]
Du hast völlig recht. Wenn man vergisst etwas „zurück“ in den Collector zu mergen dann ist es bei nächster Änderung an gleicher Stelle eventuell weg. Das würde heißen wir dürfen es einfach nicht vergessen 😉. Ein bisschen mehr disziplin muss also rein wenn wir das so machen wollen.

**Comment by Ruko2010** [comment]
Ich glaube das hat sich erstmal erledigt...
