### ISSUE TITLE
Firefox update am 13.10.18

### ISSUE THREAD

**Issue by Hoppels** [2Abendsegler/GClh#894]
seit dem Update sind die Funktionen von gc little helper komplett außer Kraft gesetzt.
Es werden keine VIP's mehr angezeigt. In der Freundesliste die Anzahl der neu geloggten Caches, 
beim Loggen die Smiley's sind weg.......
Eben komplett die ganzen Funktionen.

**Comment by Ruko2010** [comment]
Klingt als ob es ein Problem mit Tampermonkey ist. Deinstalliere es am besten mal und mach es neu drauf

**Comment by CachingFoX** [comment]
Das Problem kenne ich von einen anderen Computer. Dort werden die Userscripte nicht mehr gestartet. Ursache unbekannt. Abhilfe: Alle Firefox Instanzen schließen und wieder öffnen.

**Comment by CachingFoX** [comment]
@Hoppels Konntest du gclh wieder in Gang setzen? Wie sieht es mit anderen User Scripts aus? Laufen diese?

**Comment by MagpieFourtyTwo** [comment]
So, jetzt Tampermonkey mal komplett neu installiert, GClh neu drauf, alte Config geladen: Same same.

Danach in GClh Config beide Resets versucht:
- Zunächst nur dynamic data - das hängt sich nach Klick auf [Ok] auf, der Kreisekringel bleibt nach der ersten Umdrehung stehen.  Das Tab kann zwar geschlossen werden
- Nach einem FF-Kill per Taskmanager noch mal Komplett-Reset auf Default values - das läuft zwar durch, aber anschliessend sind z. B. die Log-Templates immer noch da. Das scheint also auch nicht wirklich zu funkionieren.

Ich blick's nicht ...  :o/

**Comment by MagpieFourtyTwo** [comment]
Nun noch mal mit nem komplett frischen FF-Profil. TM rein, GClh rein, fertig. Danach ein Test-Log-Template angelegt, Log versucht - gleiches Ergebnis. :((

In der Konsole kommt noch folgendes:

```
Loading failed for the <script> with source “https://static.hotjar.com/c/hotjar-441815.js?sv=5”. GC73F5M_red-fuffy:1:1
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”. GC73F5M_red-fuffy:1:1
Loading failed for the <script> with source “https://connect.facebook.net/en_US/fbevents.js”. GC73F5M_red-fuffy:1:1
Loading failed for the <script> with source “https://www.google-analytics.com/plugins/ua/linkid.js”. GC73F5M_red-fuffy:1:1
Loading failed for the <script> with source “https://securepubads.g.doubleclick.net/gpt/pubads_impl_275.js”. GC73F5M_red-fuffy:1:1
SyntaxError: unexpected token: identifier[Learn More] log.aspx:1:644
injectPageScript
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:13664:5
insert_tpl_fkt
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:4251:9
mainGC
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:4138:13
start/<
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:1434:17
resolveWith
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:7:15710
done
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:7:15604
start
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:1428:10
tms_628aafb8_5835_4f1d_b52d_b7947c1fb243
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:13695:1
g</< eval:2:479 anonymous/<
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:4:1
anonymous/<
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:3:55
anonymous
moz-extension://42827dcf-4273-4fe0-9d40-6773ffb4fc82/userscript.html:3:2
g</< eval:2:479 E_c eval:3:293 ka eval line 1 > Function:61:378 create eval line 1 > Function:72:334 e eval line 1 > Function:16:154
ReferenceError: gclh_insert_tpl is not defined[Learn More] log.aspx:1:1 
```

**Comment by MagpieFourtyTwo** [comment]
Ok, Update: Bin bei meinen Tests zwischenzeitlich mehr zufällig auf einen anderen Cache geraten, und in dem hat's plötzlich funktioniert! Also alles Retour, dieses zweite Listing aufgerufen, "Log Cache" ... tut!

Danaxch hab ich auf dem zweiten PC mal versucht, genau diesen Red Fuffy zu loggen, und den mag er dann auch nicht. Also noch andere Caches dieses Owners versucht - und siehe da, das Template Insert funktioniert bei denen ebenfalls nicht.

Wild Guess: Könnte das evtl. mit dem Single Quote im Namen des Owners zusammenhängen ...?

**Comment by MagpieFourtyTwo** [comment]
Hab dann noch mal nen User mit "'" und einem gelegten Cache gesucht (interessant am Rande: Die Cacher mit einem Single Quote im Namen haben i. d. R. nur ein oder zwei Caches geloggt und dann nie wieder was gemacht ;) ), den hier gefunden: [https://coord.info/GCNBTV](https://coord.info/GCNBTV) und zu loggen versucht - Template Insert auch geht nicht,

Das deutet für mich schon ziemlich deutlich auf ein Quoting Problem hin.

Frage: Geht das auf die Schnelle zu lösen oder soll ich damit einen neuen Bug aufmachen?

**Comment by MagpieFourtyTwo** [comment]
CachingFoX wrote:
> Das Problem kenne ich von einen anderen Computer. Dort werden die Userscripte nicht mehr gestartet. Ursache unbekannt. Abhilfe: Alle Firefox Instanzen schließen und wieder öffnen.

Das ist (bei uns) übigens nicht zwingend erforderlich. Es reicht, in die AddOn-Verwaltung zu gehen. Tampermonkey zu deaktivieren, dann zwei Sekunden warten und wieder aktivieren. Sobald das gc.com Tab wieder geöffnet wird, bereitet GClh die Seite auf, neu laden ist also auch nicht erforderlich.

**Comment by MagpieFourtyTwo** [comment]
Ach ja: Tampermonkey "vergisst" auch gern mal die Scripte. Sollte es noch da sein, aber alles obige nicht hilft, einfach noch mal per [https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) drüber installieren. Einstellungen bleiben dabei erhalten.

**Comment by Ruko2010** [comment]
@MagpieFourtyTwo 
> Das deutet für mich schon ziemlich deutlich auf ein Quoting Problem hin.
> 
> Frage: Geht das auf die Schnelle zu lösen oder soll ich damit einen neuen Bug aufmachen?
am besten ein neues Ticket, dass hat mit dem hier ja nichts zu tun. Dann ist es sauber getrennt.

**Comment by MagpieFourtyTwo** [comment]
@Hoppels Ein Feedback und vielleicht ein kleines Dankeschön wäre nett gewesen ...  :/

**Comment by Ruko2010** [comment]
Ich denke ja
