### ISSUE TITLE
Mark images with an geo location in the EXIF data and provide an link to a map service 

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#896]
## Feature
JPEG images can be include a geo location in the metadata (EXIF block). It will be helpful to see which images in the image gallery of a geocache listing have an geo location.

Every image in the gallery is mark if a geo location data block is available or not. If a geo location for an image available a link to a map service with the location is provided.

Additional EXIF data can be shown (like GPS accuracy, orientation, elevation, ...)

Feature should be optional.

## Additional information
- exif.js have to be used to get the EXIF data. Every image have to be log again. 
- exif.js needs a little modification to use GM_xmlhttpRequest
- Footprint of exif.js is 32KB, libary can be load on demand
- Reduce code size, exif.js can be minized

## Screenshot
A quick'n'dirty mock-up: A red border marks an image without GPS tag and green with GPS tag
![grafik](https://user-images.githubusercontent.com/1838534/46980020-a0d83180-d0d3-11e8-9575-fc7c2823c237.png)

**Comment by CachingFoX** [comment]
@Ruko2010 @2Abendsegler What is your opinion?

**Comment by 2Abendsegler** [comment]
Ich seh das Feature für Mysteries auch kritisch. Falls wir das Feature einbauen, ich finde es ja schon nett, dann sollten wir vielleicht die Mysteries ausschließen. Das könnte man dann auch im Configschalter vermerken. 
Ich finde die Bilder sollten nicht angerührt werden. Wenn es EXIFs gibt, dann anzeigen, und gut ist. 
Für den Fall dass es jemand nicht mag, Configschalter vorsehen.

**Comment by CachingFoX** [comment]
@Ruko2010 findige (fauler) User = CachingFoX :rofl: Ja ich mach das :smile: 

Die Darstellung ist erst einmal neben Sache. Mir ging es in erster Linie darum, ob wir überhaupt solch ein Feature einbauen wollen.

Ich glaube der Mystery Solver Skript von Saarfuchs hat so etwas drinnen.

@2Abendsegler Evtl. schwierig es bei Mysteries auszuschließen. Findige User können das Skript dann entsprechend anpassen.

Ich wollte ein Meinungsbild haben. Danke für eure Antworten. Euren Aussagen entnehme ich, dass ihr/wir das Feature nicht in GCLH aufnehmen wollt. Ich muss das Feature nicht zwingend im GCLH haben. Aktuell ist es ein lokales Skript von mir.

**Comment by CachingFoX** [comment]
Ich würde dann das Ticket in den nächsten Tagen schließen. Nochmals danke für die Antwort.

**Comment by 2Abendsegler** [comment]
> Ich würde dann das Ticket in den nächsten Tagen schließen. Nochmals danke für die Antwort.

Ich übernehme mal das Schließen ... 😉
