### ISSUE TITLE
Openrouteservice

### ISSUE THREAD

**Issue by V60GC** [2Abendsegler/GClh#897]
maps.openrouteservice.org

Irgendwie schaffe ich es nicht, mich an den BRouter zu gewöhnen. Währe es möglich den Openrouteservice als Option einzubauen.

Viele Grüße
V60

**Comment by CachingFoX** [comment]
Technische spricht nichts dagegen einen weiteren Dienst aufzunehmen.

`urlTemplate: 'http://maps.openrouteservice.org/directions?n1={center_latitude}&n2={center_longitude}&n3={zoom}&a=null,null,{waypoints}&b=0&c=0&k1=en-US&k2=km',`

Zugklärende Punkte:
- Routing bei den Home Koordinaten beginnen lassen? (kleiner Implementierungsaufwand)
- Kann man die Wegpunkt Namen übergeben oder nur die Koordinaten?
- Unterschiedliche Kartenlayer möglich
- Was bedeuten die Parameter, b,c,k1,k2?

Ein kurzer Test hat ergeben, dass es nach meine Einschätzung ein geringer Aufwand und geringes Risiko ist.

@Ruko2010, @2Abendsegler Umsetzen?

**Comment by 2Abendsegler** [comment]
Das hier hab ich wohl verpaßt. Ja, aus meiner Sicht ok.

**Comment by 2Abendsegler** [comment]
**URL Template**
- n1 Center latitude, wird ergänzt
- n2 Center longitude, wird ergänzt
- n3 Zoom, wird ergänzt
- a Waypoints: latitude, longitude, latitude, longitude, ...
- b Fußgänger spazieren = 2; Fußgänger wandern = 2b
- c Präferenz: schnellste = 0; kürzeste = 1; bevorzugt = 2
- k1 Sprache = en-US, wird ergänzt
- k2 Maßeinheit = km, wird ergänzt
- Die Layer können scheinbar nicht übergeben werden.

---
[Beispiel 1:](https://maps.openrouteservice.org/directions?&a=49.74053,8.63237,49.73614,8.64483,49.75067,8.64773,49.76233,8.65881&b=2b&c=0
)
```
https://maps.openrouteservice.org/directions?&a=49.74053,8.63237,49.73614,8.64483,49.75067,8.64773,49.76233,8.65881&b=2b&c=0
```
Beispiel 1: URL Aufbereitung durch Openrouteservice:
```
https://maps.openrouteservice.org/directions?n1=49.749386&n2=8.647227&n3=14&a=49.74053,8.63237,49.73614,8.64483,49.75067,8.64773,49.76233,8.65881&b=2b&c=0&k1=en-US&k2=km
```

---
[Beispiel 2: GC1FPN1](https://maps.openrouteservice.org/directions?b=2b&c=0&a=48.13595,11.57055,48.13017,11.58348,47.83808,11.50918,47.65735,11.46245,47.58065,11.44732,47.4177,11.46827,47.36425,11.43677,47.13698,11.635,47.07407,11.69252,47.03743,11.64965,46.99473,11.66033,46.80007,11.74377,46.74472,11.83317,46.58953,11.8297,46.51467,11.82388,46.5018,11.81238,46.4391,11.90778,46.38808,12.03307,46.35407,12.03127,46.2619,12.17622,46.06698,12.24488,45.96992,12.21428,45.73667,12.39128,45.54447,12.59937,45.43377,12.33992,48.13595,11.57055,48.13017,11.58348,47.83808,11.50918,47.65735,11.46245,47.58065,11.44732,47.4177,11.46827,47.36425,11.43677,47.13698,11.635,47.07407,11.69252,47.03743,11.64965,46.99473,11.66033,46.80007,11.74377,46.74472,11.83317,46.58953,11.8297,46.51467,11.82388,46.5018,11.81238,46.4391,11.90778,46.38808,12.03307,46.35407,12.03127,46.2619,12.17622,46.06698,12.24488,45.96992,12.21428,45.73667,12.39128,45.54447,12.59937,45.43377,12.33992)
```
https://maps.openrouteservice.org/directions?b=2b&c=0&a=48.13595,11.57055,48.13017,11.58348,47.83808,11.50918,47.65735,11.46245,47.58065,11.44732,47.4177,11.46827,47.36425,11.43677,47.13698,11.635,47.07407,11.69252,47.03743,11.64965,46.99473,11.66033,46.80007,11.74377,46.74472,11.83317,46.58953,11.8297,46.51467,11.82388,46.5018,11.81238,46.4391,11.90778,46.38808,12.03307,46.35407,12.03127,46.2619,12.17622,46.06698,12.24488,45.96992,12.21428,45.73667,12.39128,45.54447,12.59937,45.43377,12.33992,48.13595,11.57055,48.13017,11.58348,47.83808,11.50918,47.65735,11.46245,47.58065,11.44732,47.4177,11.46827,47.36425,11.43677,47.13698,11.635,47.07407,11.69252,47.03743,11.64965,46.99473,11.66033,46.80007,11.74377,46.74472,11.83317,46.58953,11.8297,46.51467,11.82388,46.5018,11.81238,46.4391,11.90778,46.38808,12.03307,46.35407,12.03127,46.2619,12.17622,46.06698,12.24488,45.96992,12.21428,45.73667,12.39128,45.54447,12.59937,45.43377,12.33992
```

**Comment by 2Abendsegler** [comment]
Folgendes gemerged:

- Datei "defi.js" von branch "openrouteservice" auf branch "collector".
- Datei "defi.js" von branch "MASTER_defi.js_openrouteservice" auf branch "master".
- Datei "defi.js" von branch "master" auf branch "collector".

Damit sind alle notwendigen merges für die Datei "defi.js" erledigt und wir können mit dem geänderten Script "gc_little_helper_II.user.js" vom "collector" ganz normal testen, "defi.js" wird von der branch "master" geladen.
So die Theorie ... 🤣 ... ach Quatsch, ich habs ja schon gestestet. 😁

**Comment by 2Abendsegler** [comment]
@V60GC
Hey, kannst du die Änderungen auch mal testen? 

Du kannst [hier den GClh mit Änderungen](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) installieren und testen. 
Anschließend kannst du [hier den GClh im Original](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) wieder installieren.

Mögliche Geocaches zum Testen:

- [München-Venedig / Munich-Venice / Monaco-Venezia](https://coord.info/GC1FPN1) 
- [Deutschlandtour Ost-West](https://coord.info/GC6128Z )
- [MTB-Cache: Rundstrecke Nördliche Bergstraße](https://coord.info/GC4A5J0) 
- [Welsche Loch](https://coord.info/GC6XXYF) 
- [Fretter Loch](https://coord.info/GC87DJY) (Nur ein Waypoint)

**Comment by V60GC** [comment]
Hei,

ich habe es mit einigen mir bekannten Multis getestet. Ergebnis ist sehr
gut. Bei Multis mit vielen WPs mit Koords ist natürlich etwas Nacharbeit
nötig.

Ein Bonbon wäre natürlich, wenn es eine Möglichkeit gäbe, die HomeKords
mit zuberücksichtigen. ;-)

**Comment by 2Abendsegler** [comment]
> Bei Multis mit vielen WPs mit Koords ist natürlich etwas Nacharbeit nötig. 

Welche Nacharbeiten sind denn nötig? Wurden Waypoints nicht gefunden?

> Ein Bonbon wäre natürlich, wenn es eine Möglichkeit gäbe, die HomeKords mit zuberücksichtigen. ;-)

Man könnte eine Einstellung im Config dafür vorsehen. Direkt beim Openrouteservice Link ist das eher mit viel Aufwand verbunden. Würde es im Config helfen?

**Comment by V60GC** [comment]
Zu 2: Ja, über die Config wäre das wohl das Beste, zumal man dort dann
auch beliebige "Startkoords" eingeben könnte.

Zu 1: Das "Nacharbeiten" war jetzt keine Kritik an der angebotenen
Lösung. Das was ich gesehen habe war toll.

Aber

Beispiel: https://coord.info/GC6A1XJ

Der Weg beginnt eigentlich, wenn man die Parkkords mal wegläßt bei der
Station S1. Dann fährt man mit der Schwebenbahn von West nach Ost und
besucht einzelne Stationen. In Barmen wechselt man dann wieder in
Richtung West und besucht weitere Stationen (Teilweise ist die Lösung
aus der Schwebebahn Richtungsabhängig möglich) und erreicht dann
letztlich wieder Vohwinkel und auch die Parkkoords, wo dann auch das
errechnende Ziel liegt.
Ich denke, dass es unmöglich sein wird, durch ein Script diesen Weg je
in der Richtigen Reihenfolge darzustellen. Das meinte ich mit
"Nacharbeiten". Wichtig ist, dass alle WPs mit Koords aufgelistet werden
(das war in allen meinen Tests gegeben). Danach schiebt man die
einzelnen WPs, so wie man sie haben möchte.






Am 14.11.2019 um 08:38 schrieb 2Abendsegler:

**Comment by V60GC** [comment]
Meine Wunsch war ja sowieso eher der Weg von Home oder beliebigen
anderen Startkoords zum Cache, als der Weg von WP zu WP. Daher ist die
Umsetzung, so wie ich sie getestet habe, vielleicht mit der Erweiterung
in der Config die Startkoords einzutragen, vollkommen OK.

Viele Grüße
Uwe

**Comment by 2Abendsegler** [comment]
Hallo Uwe,

> Das "Nacharbeiten" war jetzt keine Kritik an der angebotenen Lösung. Das was ich gesehen habe war toll.

Hatte ich auch gar nicht so verstanden. Zudem wäre konstruktive Kritik auch was Gutes. Alles gut. 😊

> Beispiel: https://coord.info/GC6A1XJ ... Ich denke, dass es unmöglich sein wird, durch ein Script diesen Weg je in der Richtigen Reihenfolge darzustellen. Das meinte ich mit "Nacharbeiten".

Ganz genau, wenn Wege sich kreuzen oder nahe aneinander vorbeikommen ist es wohl sehr schwierig. Die Routing Plattform sollte das ja eigentlich machen, aber je komplizierter es ist desto mehr Irrwege können entstehen. In der Regel ist wohl bei normalen Multis ... nichts oder kaum etwas nachzuarbeiten.

---
Die Verwendung der Homekoordinaten als Startpunkt habe ich noch eingebaut. 
Außerdem habe ich noch das Medium für die Fortbewegung, also Gehen, Fahrrad, Auto ..., bei den Einstellungen mit aufgenommen.

[Hier geht es zu den Einstellungen.](https://www.geocaching.com/my/#GClhShowConfig#a#settings_show_openrouteservice_link)
Du kannst [hier den GClh mit Änderungen](https://github.com/2Abendsegler/GClh/raw/collector/gc_little_helper_II.user.js) installieren und testen. 
Anschließend kannst du [hier den GClh im Original](https://github.com/2Abendsegler/GClh/raw/master/gc_little_helper_II.user.js) wieder installieren.

Wenn das so weit ok ist, dann würden diese Änderungen mit der nächsten Version kommen.

Liebe Grüße
Frank

**Comment by 2Abendsegler** [comment]
@V60GC
Hey Uwe,
ich schließe das Issue mal. 
Falls noch etwas ist, dann bitte melden. Gegebenenfalls machen wir das Issue nochmal auf.
LG Frank
