### ISSUE TITLE
Past events error in foreign bookmarklists and in watchlist

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#898]
**Describe the bug**
Fehler in fremden Bookmarklisten und in der Watchliste.

**To Reproduce**
- Fremde Bookmarklisten
https://www.geocaching.com/bookmarks/view.aspx?guid=36632493-2010-4d83-80f6-779b97ccd513

oder

- Watchliste
https://www.geocaching.com/my/watchlist.aspx

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22332216/47258469-fcbc0500-d49b-11e8-83e9-6c16b2cc2719.png)
![grafik](https://user-images.githubusercontent.com/22332216/47258484-2117e180-d49c-11e8-8479-92d29a0826d2.png)

**Comment by Ruko2010** [comment]
Watchlist wirft immer noch Fehler...

**Comment by 2Abendsegler** [comment]
Sorry, das ist meiner Ungenauigkeit geschuldet. Watchlist ist keine Bookmarkliste. Ich wollte mir nur den langen Issuenamen sparen und hab's nur in der Beschreibung erwähnt.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Ich arbeite daran. Leg die Füße hoch. :)
