### ISSUE TITLE
Enhanced GClh Search

### ISSUE THREAD

**Issue by CachingFoX** [2Abendsegler/GClh#899]
Das bisherige Suchfeld von gclh ermöglicht es nach GC Codes, TB Codes (public und private) zu suchen. Sollte die Eingabe weder eine GC oder ein TB Code sein, dann wird die Eingabe an die alte Suche weitergeleitet (aktuell funktioniert dies nicht mehr).

Das neue Suchfeld soll die bisherige Funktionalität des Suchfeldes mit der Funktionalität "Find Player" vereinigen und dabei für den Benutzer - durch Vorschläge - einen besseren Komfort bieten. Zudem soll die Möglichkeiten der neue GC Suche eingebunden werden:

- Eingabe kann immer als Keyword Suche geöffnet werden
- Vorschläge von Usernamen mit Link auf die Caches des Benutzers
- Aufruf von Listings über GC Code ^GC[A-Z0-9]{1,10}/i
- Aufruf von Trackables über public TB-Code ^TB[A-Z0-9]{1,10}/i
- Aufruf von Trackables über private TB-Code ^[A-Z0-9]{6}/i
- Anzeige von Orten, Statten, Bundesländer die zur Eingabe passen (öffnet die Suche mit dem Ort)
- Durchsuchen der zuletzt geöffneten Caches (Name, GCCode, Owner)

![grafik](https://user-images.githubusercontent.com/1838534/47263924-8a830900-d50b-11e8-9187-e67b323ddc34.png)

Suche nach GCCode
![grafik](https://user-images.githubusercontent.com/1838534/47263848-4b07ed00-d50a-11e8-8b6a-5f866b11633f.png)
![grafik](https://user-images.githubusercontent.com/1838534/47263920-82c36480-d50b-11e8-86a9-d8f32cd74dd2.png)

Suche nach TBCode
![grafik](https://user-images.githubusercontent.com/1838534/47263867-90c4b580-d50a-11e8-9138-38d53e110c98.png)

Usersuche mit Vorschlägen
![grafik](https://user-images.githubusercontent.com/1838534/47263872-ad60ed80-d50a-11e8-9ed6-1cc1e3adc028.png)

Link zur Stichwortsuche
![grafik](https://user-images.githubusercontent.com/1838534/47263887-0c266700-d50b-11e8-9cd5-9c4c44189c2f.png)

Vorschläge für Orte
![grafik](https://user-images.githubusercontent.com/1838534/47263939-b9997a80-d50b-11e8-8655-afe8c2cfd9fd.png)

**Comment by Ruko2010** [comment]
Gefällt mir!!! Sogar sehr

**Comment by 2Abendsegler** [comment]
Wir schließen alle Issues die älter als ein Jahr sind und nie bearbeitet wurden. Vorerst setzen wir sie ins Lager, damit sie noch auffindbar sind.
