### ISSUE TITLE
Message Center: cacher name in greeting doesn't change

### ISSUE THREAD

**Issue by BlueEagle23** [2Abendsegler/GClh#901]
When I go to [Message Center](https://www.geocaching.com/account/messagecenter) and click on a message in the left pane, GClh automatically enters a greeting in the bottom-right message pane. Example: "Hi BlueEagle23,"

However, when I then click on another message from another geocacher, the greeting remains the same. Instead of greeting the geocacher for the current message, the first geocacher's name remains in the greeting.

 - OS: Windows 10
 - Browser: Chrome 70
 - Version: GClh II 0.9.13

**Comment by Ruko2010** [comment]
@2Abendsegler Ich hab mir das nochmal angeschaut aber ich bin zu keiner Lösung gekommen wie man die Sache mit den fehlenden Variablen ersetzen sollte.
Lässt man die einfach weg, dann fehlen ja Infos, die man sonst hätte. In der aktuellen Version muss man also nur den Namen des Owners in seinem Template austauschen, wenn man da was ändert. Wollen wir das Issue also einfach unter "geht nicht" ablegen? Oder hast du eine Idee für einen Fix (Umsetzung würde ich natürlich machen)

**Comment by 2Abendsegler** [comment]
@BlueEagle23 
Are you from USA?
Sorry for german communication, the theme is complicate and is was easier in the native language. ;)

**Comment by Ruko2010** [comment]
@BlueEagle23 the fix is implemented and will be rolled out with the new Version.

**Comment by 2Abendsegler** [comment]
New error with the receiver.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to message center https://www.geocaching.com/account/messagecenter
2. Click on one receiver, the name will changed
3. Click on another receiver, the name will not changed
4. Call console and see error

![grafik](https://user-images.githubusercontent.com/22332216/52881856-280ee200-3166-11e9-9579-2a3898499af6.png)

**Comment by Ruko2010** [comment]
Crap, I think this error is comming up, because we access the msg-center directly and not via a "message this owner" button. So we don't have the text in the URL. I will look into this.

**Comment by 2Abendsegler** [comment]
Yes. 
The older coding handle this.
