### ISSUE TITLE
Log Templates do not work when Owner Name contains a Single Quote(?)

### ISSUE THREAD

**Issue by MagpieFourtyTwo** [2Abendsegler/GClh#902]
**Describe the bug**
Insertion of Log Templates fails when logging e. g. [Red Fuffy](https://coord.info/GC73F5M) by [Can't Stop Crew ](https://coord.info/PRCW7T8) (using old logging page).

**To Reproduce**
1. Define at least one Log Template
2. Go to [Red Fuffy](https://coord.info/GC73F5M) 
3. Click on 'Log geocache' 
4. Click to insert a Log Template
5. Nothing happens (apart from URL getting an add. "#" and input window loosing focus)

**Expected behavior**
Insertion of Log Template's text and Input Window not loosing focus.

**Desktop**
 - OS: Windows 7 Pro, Windows 10 Home
 - Browser: Firefox
 - Version: 63.0.3 (32 and 64bit)

**Additional context**
Performed more tests, where most of the time the above works as expected, then realized the Single Quote, looked for a similar constellation, found [https://coord.info/GCNBTV](https://coord.info/GCNBTV) - and indeed, insertion failed again. Maybe a quoting problem?

BTW: Even factory new profile or re-installing every single component does not make any difference.

**Comment by MagpieFourtyTwo** [comment]
Nop. the Log Templates themselves do not contain the Owner's Name. This variable is just used in my Log Signature. But even that does not matter: I finally tested with an empty/new FF profile, where nothing else was installed than just Tampermonkey and GClh with everything default, apart from just one Log Template which was called "Deschd" and contained "Dis is dr deschd". This was the base for the scenario described above.

**Comment by Ruko2010** [comment]
ok, thank you. I'll check it.
