### ISSUE TITLE
Unification of the line spacing and font size of "Add to list" popup.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#905]
Betrifft "Add to list" Popups auf der Karte und auf der Search Seite. Die Zeilenabstände und Schriftgrössen der "Add to list" Popups wurden so angepaßt wie sie auf den Cache Listing Seiten dargestellt werden.

Alt -----------------------------------------------> Neu
![grafik](https://user-images.githubusercontent.com/22332216/49994195-1ef86d80-ff89-11e8-82b3-79d3fbec50a2.png) ![grafik](https://user-images.githubusercontent.com/22332216/49994321-78f93300-ff89-11e8-87fd-0d85cbaea45e.png)

**Comment by Ruko2010** [comment]
Sehr schön! Getestet im Firefox und Chrome auf Mac.
