### ISSUE TITLE
Wrong  log's date in "latest logs" section of the map pop-up

### ISSUE THREAD

**Issue by PontiacCZ** [2Abendsegler/GClh#922]
Steps to reproduce:

1) open the cache Mlyn Napajedla https://coord.info/GC21E79
2) scroll down to logs and locate nanocrack's log, it's the third one from the top as of today. Note its date - **2018-07-27** (I have set up ISO-like date display)
![obrazek](https://user-images.githubusercontent.com/9153595/50385128-b9665880-06cf-11e9-979a-ff17fad477d9.png)

3) now open the GC map using the "Map this location" link generated by GClh, the map will center on the cache.
4) click the cache icon. On the pop-up window hover over nanocrack's log icon again - the log now displays with the date **2018-10-24**
![obrazek](https://user-images.githubusercontent.com/9153595/50385178-30502100-06d1-11e9-81d8-7220768541c4.png)

**Comment by 2Abendsegler** [comment]
The latest logs in cache listing are ok. Only latest logs in map popup are not always ok. 
nanocrack - 24.10.2018 should be 27.07.2018
MykkyCZ - 23.07.2018 should be 22.07.2018
CassyCZ - 23.07.2018 should be 22.07.2018

The date of the entry seems to be displayed.

**Comment by 2Abendsegler** [comment]
It was already wrong with the previous version 0.9.14.

**Comment by 2Abendsegler** [comment]
@PontiacCZ 
Thanks for the error message.

**Comment by Ruko2010** [comment]
@PontiacCZ thanks for reporting. @2Abendsegler I found the error. For the map-popup, we use the basic information in the js-Object on the listing page, and there are 2 Dates:
![image](https://user-images.githubusercontent.com/2239440/50386688-44ede280-06ec-11e9-8a50-a60d4b3a77e3.png)
I think groundspeak made a change here. I will update the code to only use the visited date.

**Comment by Ruko2010** [comment]
on line 7052 in our code, we use the "created" date:
`lateLog['date'] = initalLogs['data'][i].Created;`

But I have to double check if the "visited" date is always the correct one. It is possible, that for other log types there are other date-types.

**Comment by Ruko2010** [comment]
@PontiacCZ I fixed it in this PR if you don't want to wait till the next release 😉: https://github.com/2Abendsegler/GClh/pull/923
