### ISSUE TITLE
AddElevation incompatible with Ghostery

### ISSUE THREAD

**Issue by technetium** [2Abendsegler/GClh#945]
**Describe the bug**
When I turn on the Ghostery extension GClh stops working

**To Reproduce**
1. Install Ghostery (block everything, yes I'm paranoid)
2. Hit the F12 key to see the console log
3. Open a cache page
4. See error:

GClh_ERROR - AddElevation - https://www.geocaching.com/geocache/GC80V32_gedenkbos: elevationServicesData[3] is undefined
Stacktrace:
mainGC@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:3967:13
start/<@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:1440:17
resolveWith@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:7:15710
done@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:7:15604
start@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:1434:10
tms_21d840ca_09e1_4ba4_b2e5_03b7ed1aabe1@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:13866:1
g</<@eval:2:479
anonymous/<@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:4:1
anonymous/<@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:3:55
anonymous@moz-extension://bad9f2a5-a5a6-436b-9b9e-331b4e3f5982/userscript.html?id=21d840ca-09e1-4ba4-b2e5-03b7ed1aabe1:3:2
g</<@eval:2:479
E_c@eval:3:293
ka@eval line 1 > Function:61:378
create@eval line 1 > Function:72:334
e@eval line 1 > Function:16:154

**Expected behavior**
To see the changes on the cache pages I see when I turn Ghostery off, when Ghostery is turned on.

**Desktop (please complete the following information):**
 - OS: Windos 7
 - Browser: Firefox
 

**Additional context**
The easy solution is of course to turn Ghostery off, but I'd like to be more specific in what I whitelist, so If you can give me a tracker/url I can whitelist that would be nice.

Even better would be a check in the script so if something cannot be loaded this functionality will be skipped and an error message is written to the console (optional)

**Comment by Ruko2010** [comment]
Hi @technetium,
the error message sounds to me more like it is not finding the new elevation service we introduced in the last version. Can you please check if you have the latest version of GClh installed (currently 0.9.14)

**Comment by technetium** [comment]
Installing the 0.9.14 version solved the problem. I don't know how I ended up with 0.9.15. Sorry to have bothered you.

**Comment by 2Abendsegler** [comment]
No problem, you are welcome.
