### ISSUE TITLE
[New Map] Discussion

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#951]
Es ist soweit, die neue Map ist nun für alle verfügbar und ich gehe davon aus, dass sie in ein paar Monaten auch die aktuelle Ansicht ablöst:
https://forums.geocaching.com/GC/index.php?/topic/351038-release-notes-website-new-searchmap-%EF%BB%BF-january-17-2019/

Wir müssen uns nun also Gedanken machen, welche Features wir in der neue Map umsetzen wollen, und vor allem wie. Ich bin dafür, für jedes Feature eine Issue aufzumachen, so dass auch mehrere Leute gleichzeitig an der Sache arbeiten können. Damit man die Sachen leichter findet schlage ich folgenden Titel als Beispiel für die Issues vor:
"[New Map] Show Owner Name in Cache Details"

Ich denke es ist das beste, wenn jeder seine Ideen als Issue auf macht. Dann können wir in den jeweiligen Issues themenspezifisch diskutieren.

**Comment by Ruko2010** [comment]
Was mir dabei gleich noch einfällt. Wir sind ja nun schon bei Version 0.9.15. Die Anpassung der neuen Karte wird ja sicher eine "größere" Sache. Wollen wir da ein neues Major Release daraus machen, also 0.10.X ?

**Comment by 2Abendsegler** [comment]
Gute Vorgehensweise, sollten wir so machen.
Yep, v0.10

**Comment by Ruko2010** [comment]
Da macht jemand Werbung für uns 😃: https://forums.geocaching.com/GC/index.php?/topic/351038-release-notes-website-new-searchmap-%EF%BB%BF-january-17-2019/&do=findComment&comment=5759912

**Comment by Ruko2010** [comment]
Noch eine kleine Erweiterung zur Vorgehensweise. Wollen wir 1. auch kleine Features schon auf die neue Map bringen, oder wollen wir 2. ein großes Bundle schnüren?

Bei Nummer 2 sollten wir uns überlegen, die PRs schon zu machen, aber noch nicht zu mergen. Bei 1 könnten wir etwas agiler arbeiten und die Features nach und nach bringen. Dann wäre die Sache mit der Versionsnummer nur nicht so passend 😃

**Comment by 2Abendsegler** [comment]
(Off-Topic: Cool! Hab Isebar's Beitrag mal ein "like" verpasst. Das ist nicht ungefährlich was er da macht, ich hab für sowas schon mal ne "Abmahnung" kassiert.)

**Comment by 2Abendsegler** [comment]
Wenn das zusammenhängende Dinge sind wie das Popup bei der alten Karte, dann würde ich das zusammenfassen. Auch deshalb damit wir nicht doppelt gleiche Arbeiten machen. Das muss aber nicht unbedingt im PR passieren. Vielleicht sollten wir etwas genauer im Issue beschreiben was gemacht wird. Wenn sich dann jemand dranhängen will weil er Ähnliches machen will, dann per Zuruf PR aufmachen und vielleicht auch einen Bereich kennzeichnen/benennen in dem der Andere dann arbeiten kann. Also so wie beim Changelog, einer stellt schon mal das Gerüst zusammen und dann kann man mit Mehreren daran arbeiten. Trotzdem werden wir dann das meiste in 0.10 veröffentlichen. Ich seh das mit der 0.10 aber auch gar nicht so eng. ;)

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Off-Topic:
> 
> 
> Da macht jemand Werbung für uns smiley: https://forums.geocaching.com/GC/index.php?/topic/351038-release-notes-website-new-searchmap-%EF%BB%BF-january-17-2019/&do=findComment&comment=5759912

Willst du nicht Isebar auch ein like geben? ;)

**Comment by Ruko2010** [comment]
Recht haste 😃. Ist nachgeholt

**Comment by Ruko2010** [comment]
Ich seh schon kommen, die Userzahlen explodieren in der nächsten Version 😅

**Comment by 2Abendsegler** [comment]
Ich habe mir gerade mal die neue Kartenbeschreibung genauer angesehen. In den Details zum Cache gibt es nicht wirklich neues, vielmehr fehlen ja Dinge. Es ist nur etwas netter aufbereitet mit dicken Icons und so ... eben für die Smartphone Cacher.

1.  Vielleicht sollten wir auch hier einen eigenen Bereich schaffen wo wir die ganzen Dinge aus dem unteren Bereich des Popups der alten Karte anzeigen. Vielleicht oberhalb von Description &  Hint.
2. Vielleicht könnte man auch ein Compact Layout machen und die ganzen GS Dinge etwas zusammenschieben. Ich befürchte dass die jetzige Anzeige ja bereits über den gesamten Bildschirm geht.

**Comment by Ruko2010** [comment]
1. Klingt gut
2. Ja gern, aber am besten abschaltbar (obwohl du das sicher eh gemeint hast)

**Comment by 2Abendsegler** [comment]
Ok, hab 2 Issues aufgemacht.

**Comment by 2Abendsegler** [comment]
Weißt du was noch wichtiger ist als die neue Karte?
#663 :D

**Comment by 2Abendsegler** [comment]
Off-Topic: Ich hab alle meine Abos auf alle Issues gelöscht. Wenn du mich erreichen willst dann mit @...

**Comment by 2Abendsegler** [comment]
Ja das glaub ich. :)
Ja, etwas, im Moment ist es mir etwas viel geworden.

**Comment by 2Abendsegler** [comment]
Vielleicht machen wir doch noch eine 0.9.16 mit den ganzen Korrekturen.
Im Moment haben wir ja noch nichts bezüglich der neuen Karte im collector. 
Was meinst du?

**Comment by 2Abendsegler** [comment]
Vielleicht könnten wir die folgenden issues noch versuchen dort mit reinzunehmen.
#901
#962
#976

**Comment by Ruko2010** [comment]
> Vielleicht machen wir doch noch eine 0.9.16 mit den ganzen Korrekturen.
Im Moment haben wir ja noch nichts bezüglich der neuen Karte im collector.
Was meinst du?

da bin ich dafür...

> Vielleicht könnten wir die folgenden issues noch versuchen dort mit reinzunehmen.
#901
#962
#976

Auch das finde ich gut. Dann machen wir die neue Version, wenn die 3 Sachen fertig sind. Und dann bin ich dafür, im nächsten release uns erstmal auf die Map zu konzentrieren.
#901 schau ich mir im laufe der Woche an. Deine Änderungsvorschläge klingen logisch. Ich versuch das so umzusetzen.

**Comment by 2Abendsegler** [comment]
Ich kann mich nicht so richtig aufraffen für die Issues zur neuen Karte. Ich vermute immer schon das Schlimmste, dass es viel viel schwieriger ist als bei der bisherigen Karte. Deine Erfahrungen bestätigen das ja auch. Ich hatte auch gehofft dass CachingFoX bei der neuen Karte mit einsteigt, weil viele Kartenfeatures ja auch sein Baby sind. Außerdem wollte ich auch nichts größeres mehr anfangen wegen dem geplanten Urlaub Richtung Portugal. Ich fürchte hier wird vieles an dir hängen bleiben.

**Comment by 2Abendsegler** [comment]
F... , wenn man von der Search Seite kommt, dann wird immer die neue Karte aufgerufen. Was ein Elend.
https://forums.geocaching.com/GC/index.php?/topic/351901-release-notes-website-new-search-map-april-25-2019/

www.geocaching.com/map - Browse Map
www.geocaching.com/play/map - Search Map (new)

**Comment by 2Abendsegler** [comment]
https://forums.geocaching.com/GC/index.php?/topic/351901-release-notes-website-new-search-map-april-25-2019/&tab=comments#comment-5773223

**Comment by Ruko2010** [comment]
Jap, das Ding ist nun Live für alle

**Comment by 2Abendsegler** [comment]
Off-Topic
@Ruko2010 Wünsche euch einen wunderschönen Urlaub!

**Comment by Ruko2010** [comment]
Danke 😃

**Comment by 2Abendsegler** [comment]
@Ruko2010
Du hast in der aktuellen Version im collector ein paar Layer entfernt. Das sollten wir nur dann machen, wenn die Layer tatsächlich nicht mehr funktionieren, ansonsten ist das Geschrei groß. Etwas was vorhanden ist, das kann man nicht mehr entfernen. 😉 
(Ich habe nicht geprüft, ob das der Fall ist.)

**Comment by Ruko2010** [comment]
Du meinst sicher die Layer von Flopps map, oder? Die haben ihre Auswahl an Karten eingeschränkt, darum habe ich die raus genommen. Da gab es auch ein Ticket dazu.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Ich möchte die nächsten Tage eine neue Version an die User geben. Ist das aus deiner Sicht ok?

**Comment by Ruko2010** [comment]
Na klar, sehr gern.

**Comment by 2Abendsegler** [comment]
@capoaira

> gemerged (kann man das so schreiben?)

Ich glaube das kann man so sagen und schreiben, und falls nicht, scheiß drauf, wir sagens halt so. 😂

Zur weiteren Vorgehensweise mal ein paar Ideen einfach so runter geschrieben ohne Anspruch auf Vollständigkeit und ohne Wertigkeit in der Reihenfolge. Versteh die Abschnitte bitte nicht falsch. Versteh es nicht als Kritik, zumal sowieso nicht alle Themen auf dich anwendbar wären. Versteh es als kleine Anleitung und Hilfestellung, auch um hier etwas Spaß zu haben.  

Es ist etwas lang geworden. Passiert manchmal zu später Stunde. Sorry. 🙄

---
### 1. New Map ist dein Thema, wenn du das möchtest:
Wir können nicht so richtig am selben Thema wie beispielsweise New Map arbeiten. Du kommst dir selbst schon in die Quere, weil du darauf wartest, dass die eine Entwicklung von dir gemerged wird, bevor du mit der nächsten anfangen kannst. 

Ich halte mich jetzt zurück mit dem Thema New Map, es ist bis auf weiteres dein Baby ... sofern du das möchtest. Pack die Sachen so um wie du möchtest ... , zuerst mal. 

Du musst auch nicht für jede Kleinigkeit einen eigenen PR stellen. Du kannst auch mehrere Issues mit einem PR abdecken oder das Ganze irgendwie anders aufsetzen, damit es für die Entwicklung einfacher wird. Du kannst auch Issues um Themen erweitern wenn es Sinn macht. Dann passt man die Überschrift des Issues möglichst an und erwähnt im Changelog die Dinge eben zusammen, beispielsweise so wie bei den neuen Lists Seiten in der aktuellen Version. Da hab ich auch nicht für allen Dreck ein Issue aufgemacht. 

Übernimmst du New Map, musst du deshalb nicht alles für die neue Karte selbst machen. Wenn du mit irgend etwas nicht weiterkommst, dann kannst du fragen oder auch einfach etwas liegen lassen, weil du es nicht machen möchtest. Du musst nicht alles machen, wie bereits geschrieben, und es muss auch nicht sofort sein. Wir haben Zeit damit, mit allem, in aller Regel. Wenn wir keine Lust haben zum entwickeln, oder wichtigeres zu tun haben ..., tse ... dann machen wir hier eben nichts. Wir entscheiden das selbst, du auch. 

Du musst dich auch nicht beeilen, weil du vielleicht Bedenken hast dass andere dir ein Thema wegnehmen. New Map ist dein Thema ... sofern du das möchtest. Und sag wenn du auch noch ein anderes Thema beackern möchtest, vielleicht in der Regel ein Thema nach dem anderen, wenns passt. Hast du ja auch schon gemacht. Initiative ist immer gut.

### 2. Klausuren müssen Vorrang haben:
Eine Sache muss ganz klar sein: Deine Klausuren müssen Vorrang haben. Das musst du beachten. Ich weiß dass es manchmal nett ist etwas kleines, oder wie sich dann während dessen herausstellt auch etwas größeres nebenher zu machen. Man gönnt sich ja gerne mal ein kleines Erfolgserlebnis. Dafür kann man dann das öde Lernen für die Klausuren auch mal zurückstellen. Das geht aber jetzt nicht mehr so einfach, weil du erwähnt hast, dass einige Klausuren anstehen und du noch Schüler bist und ich das jetzt wohl oder übel im Blick habe. 

Mach dir eine ganz wichtige Sache klar: Niemand wird dir für deine Arbeit hier großartig danken. 

Wenn du überhaupt mal Winzigkeiten davon mitbekommst dass deine Arbeiten Gefallen finden, dann ist so etwas wirklich eine Ausnahme. Meist ist so etwas zudem mit neuen Anforderungen verbunden. 

Wir haben etwa 2000 bis 2500 Installationen. Schau mal in die Foren vom geoclub oder geocaching und zähl dort mal wie viel Lob es von den Cachern hinter diesen Installationen gibt. Das ist soo winzig! Und häufig können sie ja auch überhaupt nicht abschätzen wie viel Aufwand es ist, was wir hier machen. 

2Abendsegler hat beispielsweise öfter zu hören bekommen, nicht in den Foren, dass es mehr als unschön von ihnen ist noch keine Caches ausgelegt zu haben, obwohl sie seit 2011 dabei sind und mehr als 3000 Founds zu buche schlagen. Dabei kann ja noch nicht einmal ausgeschlossen werden, dass 2Abendsegler eine Sockenpuppe für eigene Caches nutzen. 

Fakt ist aber, dass im GClh weit mehr Aufwand meinerseits stecken als die meisten für 100 Caches benötigen würden. Ich habe alleine 2016 fast ein halbes Jahr quasi täglich mehr als 8 Stunden mit meinen Javascript Anfängen verbracht, bis ich überhaupt eine Veröffentlichung ins Auge gefasst habe. Es gab vielleicht 25 oder 30 Cacher, die sich bis heute in irgendeiner Weise anerkennend oder dankend geäußert haben ..., in mehr als 3 Jahren. 

Das ist jetzt kein Wehklagen, es ist ein Tatsachenbericht. Ich will das gar nicht werten oder bewerten. Ich will nur feststellen dass diese Dinge so und nicht anders funktionieren bei uns Cachern und auch anderswo in der Gesellschaft. Man sollte dies erkennen und kennen und nicht mit falschen Erwartungen hier mitmachen. 

Ruko2010 hat womöglich etwas mehr Anerkennung über die Zeit erfahren, weil er mehr in der Cacherszene beheimatet zu sein scheint als ich und auch beispielsweise einen Vortrag über den GClh während eines Events gehalten hat. Aber auch das wird sich wohl in engen Grenzen gehalten haben. 

Manchmal wirst du von uns etwas Lob oder Dank erhalten. Dafür nehme ich aber auch in der Regel kein Blatt vor den Mund und sage was mir nicht passt und was man anders machen soll. Ich kann sogar ziemlich nervig sein. 

Also ... du machst das hier für so etwas wie die Ehre, für dein Selbstvertrauen, aus Spaß am entwickeln und aufgrund von anderen Dingen, die nur dich selbst in deinem stillen Kämmerlein betreffen und berühren. Etwas anderes zu erwarten ist fehl am Platz, weil es in den allermeisten Fällen eben nicht kommt. 

Nochmal, das ist wirklich so! Ich meine das hört sich jetzt so an als ob ich dich vergraulen wollte, das ist aber nicht so. Ich sags nur wie es ist.

Nochmal zurück zu deinen Klausuren und anderen schulischen Aktivitäten. Wenn ich mitbekomme dass du diese Dinge zugunsten hiesiger Entwicklungen schleifen lässt, bist du mit zwei Klicks aus dem Projekt draußen und kannst noch nicht mal ein Issue aufmachen oder Kommentare schreiben. Das ist mein voller Ernst, auch wenn ich keineswegs den Oberlehrer spielen will. Der GClh ist so etwas nicht wert und ich bin da fast so rigoros, wie mit dem Thema Nazis, wo ich mich gerade bei mir vor Ort mit Cachern anlege, die einen Cache so ausgelegt haben, dass man dabei um eine Begutachtung von grenzsteinartigen Steinen mit Hakenkreuzen und Odalrunen nicht umhin kommt. Das sind Nazisymbole, deren öffentliche Darstellung mit Freiheitsstrafen von bis zu 3 Jahren geahndet werden. Anstatt den Cache dicht zu machen, findet man es nicht notwendig irgend etwas am Cache zu ändern und will andere Cacher scheinbar weiterhin dazu einladen sich eine Sammlung von Nazidreck anzusehen. Naja ..., zumindest gegen den Eigentümer des Grundstücks auf dem sich die Steinsammlung befindet, habe ich Strafanzeige gestellt. Das ist nicht der Cacheowner, nur warum der Cacheowner eben so etwas in seinem Cache aufrecht erhalten will leuchtet mir nicht ein. Aber daran kann ich nichts ändern, weil scheinbar auch GS die Meinung vertritt, dass das in Ordnung geht. Oh jee ..., ich schweife ab.
Ist aber klar geworden was ich meine, ne?

Gut, dann mal zu den Entwicklungen und drumherum noch ein paar Ideen. 

### 3. Dokumentation im Programm:
Dokumentiere im Programm bitte in Englisch. Ich weiß um die Schwierigkeiten, mach es aber bitte trotzdem. Google Translation kann hier etwas helfen. Mit der Zeit wird es dann auch besser und flüssiger. Dokumentiere das was für später oder was für andere wichtig erscheint zu wissen. Und verwende am Besten so was wie Überschriften für Abschnitte. Mehr Dokumentation im Programm ist nicht nötig. 

Dokumentiere bitte in der Regel in eigenen Zeilen und nicht hinter dem Coding. Vollständige Sätze, mit Groß- und Kleinschreibung, auch mit einem Punkt zum Schluss, kommen dabei gut und machen nicht mehr Aufwand. 

Weißt du, das ganze Thema Dokumentation ist so etwas wie Respekt gegenüber den Kollegen. Man erzeugt auch tatsächlich die Erklärungen meist hauptsächlich für die Kollegen und weniger für sich selbst. Insbesondere gibst du auch Erklärungen für denjenigen, der deine Entwicklungen nochmal testet. Wir testen quasi immer, und ich schau mir immer das Coding an, mal mehr, mal weniger, je nachdem wie risikoreich das Thema ist und wie qualifiziert sich der Kollege bereits gezeigt hat. 

Machs demjenigen der testet und deine Entwicklung abnehmen will nicht unnötig schwer, das gilt fürs Coding an sich wie auch für die Dokumentation im Programm. Wenn das Testen so lange dauern würde wie die Entwicklung, dann fragt sich der Tester zu recht warum er die Entwicklung nicht selbst gemacht hat. Verstehst du? Und wenn es andersherum Hand in Hand geht, dann macht es allen Beteiligten auch mehr Spaß. Und man kann sich auch mit der Zeit mehr erfolgsversprechend herausnehmen und einfach mehr mitreden.

### 4. Dokumentation im Issue:
Dokumentiere im Issue bitte in Englisch. So etwas wie Überschrift und der erste Beitrag mit einer kurzen Beschreibung wie es die Templates für Bugs bzw. Features vorsehen. 

Bitte wenn möglich weiteres im Issue dokumentieren und nicht im PR. Das muss dann nicht mehr in Englisch sein, sofern niemand involviert ist der kein Deutsch kann. 

Wenn man weiß dass man es selbst macht, kann man sich auch mal kürzer fassen und man muss auch nicht immer angeben auf welchem System beispielsweise der Fehler entstanden ist. Gegebenenfalls können wir hier auch nachfragen, man ist ja nicht aus der Welt. 

Oft geht auch schon aus der Überschrift hervor um was es genau geht, dann muss man auch keinen großen Aufwand treiben, nur um noch mehr geschrieben zu haben. Das soll also alles im Rahmen bleiben. 

Andererseits wäre es aber nett, wenn man in Kürze erkennen könnte, um was es beim Issue geht. Und das sollten auch anderssprachige können.

### 5. Vorhandenes Coding nutzen versus etwas richtig schön machen:
Versuche vorhandenes Coding zu nutzen und gleiche Dinge zusammen zu fassen. Anstatt sich beispielsweise am Coding der alten Karte zu orientieren, hast du ein kleines Fässchen aufgemacht. In der Regel würde man sich jedoch am vorhandenen Coding orientieren und wenn möglich auch einiges davon verwenden. Geht auch meist schneller.

Man kann es natürlich auch versuchen netter zu machen, was mit vorhandenem Coding nicht unbedingt funktioniert, zumindest nicht ohne Mehraufwand. Man kann also schon ein Fässchen aufmachen. Dann muss man aber auch bereit sein es richtig schön zu machen, die eigenen Dinge also beispielsweise an die vorhandenen Funktionen und das vorhandene Aussehen auf der Seite anzupassen, so dass es mehr wie aus einem Guss aussieht. Beispielsweise wirkt der Link "Hide Header" irgendwie fehl am Platz. Er ist zu grell blau, er ist zu groß geschrieben, es sollte eigentlich gar kein Link sein sondern eher ein Schalter, ein Button oder so etwas. Einiges davon gilt auch beispielsweise für den Link in der alten Karte, aber man lernt ja dazu. Zudem sitzt dein Link beispielsweise fast dort wo der Button von GC Tour sitzt. Macht man alles etwas kompakter, wo du ja auch schon etwas dran gearbeitet hast, dann werden sich diese Dinge überschneiden. Deshalb wurde der entsprechende Link bei der alten Karte rechts orientiert, was an der entsprechenden Programmstelle bei der alten Karte dokumentiert ist. 

Es ist also immer gut auch etwas über den Tellerrand hinaus zu schauen. Beispielsweise mit den Parametern im Config und mit deren Abhängigkeiten, das war nicht schlecht das gleich für die neuen Parameter vorzusehen.

Du kannst also schon kreativ sein und etwas in die Seite integrieren wie es GS hätte besser machen können. Du solltest keinen dicken fetten Button in rot einbauen weil dir danach ist, wenn es ansonsten nur graue kleine Schalter gibt. Du kannst aber durchaus versuchen dem Ganzen etwas eigenes, ein bisschen eigenes Design, eben ein wenig den eigenen Stempel aufzudrücken, du musst das aber natürlich nicht. 

Ich werde es sagen, wenn ich meine dass du übers Ziel hinaus geschossen bist. Das sollte dann aber auch nicht schlimm sein. Einer muss halt ein wenig auf das gesamte Ding blicken und dann auch mal das ein oder andere zurecht rücken. Beziehungsweise bei uns ist es nicht einer sondern mindestens zwei. Das ist viel besser als einer, weil man dann auch mal ne Pause machen kann.

### 6. Warten aufs Christkind:
Das warten bis etwas eingetreten ist kann nicht ewig dauern. Das muss zeitlich begrenzt werden, immer. Wähle die Zeit großzügig, aber machs nicht ewig. 

Und man muss nicht alles neu erfinden und kann beispielsweise genau hier auch auf das zurückgreifen wie es anderswo im Programm schon gemacht wird. Das hätte man selbst vielleicht anders gemacht, das ist wohl wahr, das ist aber hier nicht ausschlaggebend. Ist es genauso wie an anderen Stellen, verstehen es auch die Kollegen sofort. Siehe waitCount bzw. setTimeout.

### 7. Niemand reißt einem anderen den Kopf ab: 
Niemand reißt dir den Kopf ab wenn du etwas machst was in anderen Augen nicht so passt. Und wenn Fehler passieren ist das genau so. Auch hier macht dich niemand einen Kopf kürzer. Eigentlich geht es nur darum im Fall der Fälle den Schaden weitestgehend zu begrenzen. Dazu kann es auch gehören sich für ein Thema mit dem man sich ganz gut auskennt verantwortlich zu zeigen und selbst an die Fehlerkorrektur zu gehen. Gegebenenfalls müssen wir dann auch ungeplant und sehr kurzfristig eine neue Version raus hauen, hatten wir auch schon. So ist das eben und das ist auch kein Beinbruch. Das funktioniert prima mit Ruko2010 und mir, irgendeiner macht die Version dann auch auf die Schnelle mal fertig.

Dass man für seine Arbeiten im Changelog Erwähnung findet ist nur der Tatsache geschuldet, Dank auszusprechen für die Zeit und den Aufwand den man hier gelassen hat, nicht dafür um einen Schuldigen zu benennen. Das sollte auch klar sein. Wenn ich als derjenige der testet den Fehler nicht gefunden habe, dann wäre ich genauso schuld wie der Entwickler, sofern es überhaupt um eine Schuldfrage ginge. Es geht aber nicht darum, sondern lediglich um eine möglichst reibungslose und schnelle Fehlerkorrektur im Fall der Fälle, um sonst nichts.

---
Dann Knie dich mal rein, wenn ich dich nicht völlig abgeschreckt habe. 😊
Ich geh jetzt ins Bett, muss nämlich um 9:30 schon wieder raus. 🤢

**Comment by capoaira** [comment]
Moin,

Oh, das ist viel Text...

1) Das mit dem warten war wegen dem Mutation observer. Ich hatte angefangen und dann gemerkt, dass das ja in den Observer mit rein kommt.
Ich weiß nicht, ob ich das gesamte Thema übernehmen will bzw. kann. Ich bin halt noch Anfänger.
Ich dachte ich übernehme das ein oder andere Thema, was ich mir zutraue und/oder auf was ich Lust habe. (z.B. die automatischen Aktualisierung, da das der Grund war, warum ich die neue Map nie genutz habe).
Ich hatte das hier so verstanden für jedes neue Thema ein Issue auzumachen. Mit den PRs war ich mir nicht sicher. Jetzt weiß ich das für alles weitere.

2) Das ist Klar. Die beiden schweren habe ich hinter mir, bei einer hatte ich mich verguckt, die ist erst Fr. nächste Woche.
Ich werde das lernen nicht zurückstellen, auch wenn mir das Programmieren Spaß macht. Was bringt es mir, js programmieren zu können, wenn ich deswegen mein Abi verhaue? Die Zeiten wo ich *mal* eine Hausaufgabe vergessen habe weil ich lieber das Wochenende gecacht habe sind seit der 10. Klasse vorbei... Ich habe das im Griff und stehe in fast jedem Fach auf einer guten 2 und habe nicht vor das ins negative zu ändern.

Ich mache das auch nicht für Dank, sondern wegen dem Spaß, weil mir der GClh gefällt und weil ich in Sachen js noch einiges lernen will.
Ich glaube zu sehen, wie viel Arbeit in solch einem Projekt steht, sieht man erst wenn man schonmal etwas selber programmiert hat. Ich habe für die Schule mal mit Scratch eine kleine Animation programmiert und ich weiß nicht wie viele Tage investiert. Keiner der Lehrer hat den Aufwand dahinter verstanden. 

3) Ich muss mich noch daran gewöhnen im Team zu programmieren. Bis jetzt waren mir die Kommentare egal, da nur ich sie verstehen musste. Im englischen ist wenigstens Groß- und Kleinschreibung einfacher😉

Ich gebe ab jetzt mein bestes, darauf zu achten. Wenn ich es vergesse, dann nicht mit Absicht. 

Ich glaube an der Verständlichkeit meines Codings muss ich teilweise noch arbeiten. Ich bin halt noch Anfänger. So langsam stelle ich mich aber von getElement(s)by...() auf den querySelector um. Ich tu mich auch noch mit den Kurzschreibweisen und jquery schwer. Wenn euch da etwas nicht passt, sagt es gerne. Ich bin froh wenn ich mich verbessern kann.

4/5/6) Das werde ich bei meinen nächsten Schritten berücksichtigen. 
Ich habe mich was den Link angeht an der alten Karte orientiert, passe dies aber gerne an. Den Kommentar bei der alten Karte habe ich gesehen und deswegen den Link auch wieder Rechtsbündig gemacht. Ich hätte es mit GC-Tour ausprobieren sollen.
Das ich mich nicht immer am alten Coding orientiere, liegt daran, dass ich immer versuche das Problem selber zu lösen. So lerne ich besser dazu. (Siehe meinen ersten Versuch der automatischen Aktualisierung) 
Das mit dem waitcount kann ich gerne ändern.

7) Das will ich doch hoffen😂

---

Im Moment habe ich das Gefühl, das ich Euch/Dir mehr Arbeit mache, als Euch zu helfen. Das will ich eigentlich gar nicht... (also euch Arbeit zu machen, helfen will ich schon😉)

Gruß capoaira

**Comment by 2Abendsegler** [comment]
>Ich weiß nicht, ob ich das gesamte Thema übernehmen will bzw. kann. Ich bin halt noch Anfänger. Ich dachte ich übernehme das ein oder andere Thema, was ich mir zutraue und/oder auf was ich Lust habe.

Das was du bisher abgeliefert hast macht schon einen guten Eindruck. Von dem Gesichtspunkt her würde ich das nicht als Anfänger bezeichnen. Mach das Thema soweit du kommst und möchtest. Alles cool.

> Ich hatte das hier so verstanden für jedes neue Thema ein Issue auzumachen. Mit den PRs war ich mir nicht sicher. 

Eigentlich machen wir üblicherweise für ein Issue auch einen PRs. Normalerweise handelt es sich aber auch um ein kleineres überschaubares Thema. Hier, wenn eine ganze Seite quasi neu ist, macht es jedoch nur bedingt Sinn danach zu verfahren, weil man sich dadurch nur einschränkt wenn man mehrere eigentlich zusammenhängende Themen auch etwas zusammenpacken möchte. Und letzteres kann es ja nicht sein. 

Also, wir sind hier flexibel was die Zuordnung von Issues zu PRs und umgekehrt angeht.

> Im Moment habe ich das Gefühl, das ich Euch/Dir mehr Arbeit mache, als Euch zu helfen.

Ja, dass ist manchmal der Fall. Und ich muss zugeben, dass ich mir damit auch schwer tue. Ich hatte mich aber am Samstag dazu entschlossen, dich mehr zu unterstützen. Auch deshalb weil du Anmerkungen und Vorschläge umsetzt, es also ein Vorankommen, eine Verbesserung gibt. Und letztlich scheint es dir wirklich Spaß zu machen, was auch eine Voraussetzung dafür ist etwas langfristiger und gemeinsam in einem Team zusammen zu arbeiten.

**Comment by capoaira** [comment]
> Das was du bisher abgeliefert hast macht schon einen guten Eindruck. Von dem Gesichtspunkt her würde ich das nicht als Anfänger bezeichnen. Mach das Thema soweit du kommst und möchtest. Alles cool.

Danke 😊

Ok, dass mit den Issues macht Sinn. Habe ich bei den Hide header und compact Layout gemerkt. 

Jip, programmieren macht mir Spaß. Wenn Fortschritte sichtbar sind, beruhigt mich das :)
Ich wollte mich mal an der eigenen Area #964 versuchen.

**Comment by 2Abendsegler** [comment]
Die Diskussion für die New Map benötigen wir auch nicht mehr, denke ich. Wir haben ja das allgemeine Diskussion Issue.
Ich schließe das.
