### ISSUE TITLE
[New Map] Show Elevation in Cache Details

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#953]
**Describe the solution you'd like**
Show the Elevation of a Cache in the Sidebar

![image](https://user-images.githubusercontent.com/2239440/51371733-506dd700-1afb-11e9-84f8-c5b2321b5bb1.png)

**Comment by 2Abendsegler** [comment]
Wird in "[New Map] Own area on detail screen" #964 abgewickelt.
