### ISSUE TITLE
Show Log Counter when opening cache listing.

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#954]
Frage aus dem Forum: https://geoclub.de/forum/viewtopic.php?f=117&t=80208&p=1291029#p1291029

Moin,

danke für die neue Version.

Kurze Frage, ist es möglich das der "log counter" standardmäßig eingestellt werden kann,
also das immer die Anzahl der Logs angezeigt wird, und nicht erst nachdem ich den Button
gedrückt habe?

Ich finde nur die Einstellung "log counter" an oder aus

**Comment by Ruko2010** [comment]
Wenn ich es richtig sehe, dann müsste man nur die Funktion "showLogCounter()" nach jedem Reload der Logs aufrufen. Ich würde das aber an eine Option koppeln.
Spricht was dagegen?

**Comment by 2Abendsegler** [comment]
Es spricht nichts dagegen mit dem Aufruf des Listings die Counter anzuzeigen. Das kann erst dann passieren wenn alle Logs geladen sind. Erst dann wird auch der Button anwählbar.

Wenn ich mich richtig erinnere, können die Counter aber nur angezeigt werden, wenn keine Einschränkung bei der Anzeige der Logs aktiv ist. Werden also beispielsweise nur die found Logs oder nur die DNFs gewählt, kann der Counter nicht angezeigt werden. 
Insofern würde ich es nur genau so machen wie angefordert. Beim Aufruf des Listings die Counter anzeigen, per Schalter im Config. Alles andere so belassen. Wenn also dann nur die DNFs angezeigt werden sollen ist der Counter wieder weg. Erst wenn dann alle Logs gewählt wird, ist der Button wieder wählbar. Wenn man dann die Counter wieder sehen möchte, Button drücken. Das reicht doch. 

Antwort ist also ja. 
Das kann ich machen, wenn das ok ist.

**Comment by 2Abendsegler** [comment]
... assign es gegebenenfalls zu mir. :)

**Comment by 2Abendsegler** [comment]
Changelog, Screens und Startkonfiguration sind im PR Prepare ...
