### ISSUE TITLE
Logtemplate will not be inserted [Chrome, Safari]

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#962]
**Describe the bug**
On new Logging Page when you select a Template it is not inserted. In Chrome you can click the list again and it is inserted, in Safari you are unable to insert it at all.

**Comment by Ruko2010** [comment]
@2Abendsegler ich find nicht wirklich einen Ansatzpunkt :/

**Comment by 2Abendsegler** [comment]
Vielleicht lassen wir es dann noch etwas stehen und versuchen es in irgendwann später nochmal.

**Comment by Ruko2010** [comment]
@2Abendsegler Ok, dann kann die neue Version ja raus. Ich hab noch ein kleines Feature eingebaut 😉. Da heute Geocaching Stammtisch ist, schaffe ich die neue Version heute nicht. Aber ich kann es Morgen Abend machen...wenn du natürlich Lust hast, kannst du sie auch gern fertig machen, aber wirklich nur wenn du willst 😉.

**Comment by Ruko2010** [comment]
Ich hab mir die Sache mal etwas intensiver angeschaut, und ich verstehe nicht ganz, warum das insert vom Logtemplate über ein "onclick" auf einer Option des Selects realisiert wurde. @2Abendsegler gibt es da einen grund dafür?
ich habe es umgebaut auf ein "onChange" vom umgebenden Select. Schau es dir mal an ob du irgendwelche Unstimmigkeiten feststellst.
Ich habe es getestet in Chrome, FF und Safari.
BTW.: ist es normal, dass das Template immer "angefügt" wird, wenn man dazwischen wechselt?

![kapture 2019-02-25 at 10 22 27](https://user-images.githubusercontent.com/2239440/53327175-93d01800-38e7-11e9-9bb4-8bd13be78e3d.gif)

**Comment by 2Abendsegler** [comment]
Super!
Funktioniert sogar nun aufm Android.
Getestet auf Win 8.1 mit FF und Chrome und auf Android 8.0 mit FF. 

Die Frage kann ich nicht mehr beantworten.

Was meinst du hiermit
> BTW.: ist es normal, dass das Template immer "angefügt" wird, wenn man dazwischen wechselt?
Bei mir bleibt der Cursor bestehen auch wenn ich in einen anderen Tab wechsle und es wird genau am Cursor eingefügt.

**Comment by Ruko2010** [comment]
Ich meinte damit, wenn ich ein Template auswähle, dann wird es eingefügt, wenn ich nun ein anderes auswähle, dann wird das hinten dran gehangen, anstatt das erste zu ersetzen. Das hatte ich so nicht erwartet.

**Comment by 2Abendsegler** [comment]
Ja doch, das soll so sein, so kann man mehrere Templates zusammenmixen. Aber du hast natürlich vom Namen her völlig recht, vielleicht hätte man es nicht Log Template nennen sollen. ;)

**Comment by Ruko2010** [comment]
It's not a Bug, it's a Feature 😃.
Der Name "Log Template" ist schon ok, denn genau das ist es. Aber klarer wäre es, wenn man es "append Logtemplate" nennt, und nicht "insert logtemplate". Aber das ist eine Spitzfindigkeit 😃. Wir lassen es natürlich so wie es ist.
