### ISSUE TITLE
[New Map] Compact layout on detail screens.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#965]
**Describe the solution you'd like**
Compact layout on detail screens.

With config parameter. Start configuration activated.

**Comment by capoaira** [comment]
Moin,
ihr könnt mal gucken, wie es Euch gefällt: https://github.com/capoaira/GClh/tree/New-Map-Compact-Layout

**Comment by 2Abendsegler** [comment]
@capoaira 
Geh mal bitte in dieses Issue und drück mal den Button subscribe. Ansonsten kann ich dich nicht assignen.

**Comment by capoaira** [comment]
Habe subscribe

**Comment by capoaira** [comment]
Habe nochmal das selbe wie schonmal gemacht, nur etwas verändert:
https://github.com/capoaira/GClh/tree/New-Map-Compact-Layout
Wie findet ihr das? Habe ich etwas zu viel entfernt oder etwas vergessen?

**Comment by 2Abendsegler** [comment]
Hm ..., hab das Teil eingespielt und erhalte einen Syntax error.
https://github.com/capoaira/GClh/blob/New-Map-Compact-Layout/gc_little_helper_II.user.js

![grafik](https://user-images.githubusercontent.com/22332216/71557623-d9e69280-2a48-11ea-8a32-915cad24533b.png)

**Comment by capoaira** [comment]
Oh, ich hatte nach dem merge mit "Hide Header" nicht mehr getestet. Dabei ist wohl eine Klammer verschwunden. 
Aber jetzt sind da ein paar Sachen , die ich ändern muss, da Hide header sonst blöd aussieht und die Filter verrutscht sind.
Sorry....

**Comment by capoaira** [comment]
So, jetzt sieht es erstmal so aus, wie ich mir das Vorgestellt habe. 
Die Funktionen, den Header zu verstecken klappt leider nicht mehr.

**Comment by Ruko2010** [comment]
Also bei mir klappt alles soweit. Ich habe mein Coding mal in deins gemerged und meine Werte angepasst, falls das CompactLayout genutzt wird. Das ganze sieht dann so aus. Bist du damit einverstanden?

![image](https://user-images.githubusercontent.com/2239440/72014045-6c640e80-325f-11ea-927b-6996253aef94.png)

**Comment by 2Abendsegler** [comment]
Super, ich finde das sieht klasse aus.
Ich habe das auch gemerged, obwohl ich vielleicht noch ein oder zwei zusätzliche Dinge hätte. Die werde ich anschließend mal zur Diskussion stellen.

@Ruko2010 
Schau dir das Compact Layout auch mal noch an. Falls du noch Änderungswünsche hast ...

**Comment by 2Abendsegler** [comment]
Bitte mach vor erneuten Änderungen eine neue Branch aus dem collector.

**Comment by 2Abendsegler** [comment]
Hier noch weitere Vorschläge fürs Compact Layout:

---
### Cache Liste:
Alt:
![Beispiel 1 1](https://user-images.githubusercontent.com/22332216/72604113-95009e00-391a-11ea-8422-3cba5990ed1f.JPG)
Neu:
![Beispiel 1 2](https://user-images.githubusercontent.com/22332216/72604141-a0ec6000-391a-11ea-864f-4cfa7749afd8.JPG)

1. Wenn der Cache disabled ist, dann wird "Premium" unterschlagen. Das unterschlagen wir dann auch. 
2. Wenn der Cache "Premium" ist, könnten wir das auch in die letzte Zeile setzen. Vielleicht mit dem Symbol. https://www.geocaching.com/images/icons/16/premium_only.png 
![grafik](https://user-images.githubusercontent.com/22332216/72604542-60d9ad00-391b-11ea-94a1-ce462bc811a7.png)
3. Die oberer Zeile könnte gelöscht werden, wenn das disabled durch den Cachenamen erkennbar ist (durchgestrichen, Farbe) und das "Premium" umgesetzt wurde.

---
### Cache Details 1:
Alt:
![Beispiel 2 1](https://user-images.githubusercontent.com/22332216/72604899-10af1a80-391c-11ea-8865-33cfd623ab89.JPG)

1. Anstatt den Cachetyp in Worten in die erste Zeile zu schreiben, könnten wir das verkleinerte Symbol vor den Cachenamen stellen mit title des Cachetyps.
2. Das "Premium" könnten wir so umsetzen wie in der Cache Liste.
3. Die oberer Zeile könnte gelöscht werden wenn das disabled durch den Cachenamen erkennbar ist (durchgestrichen, Farbe), das "Premium" umgesetzt wurde und der Cachetyp als Symbol dargestellt wird.
4. Der grüne Button könnte dann etwas verkleinert werden. 

---
### Cache Details 2:
Alt:
![grafik](https://user-images.githubusercontent.com/22332216/72605449-10634f00-391d-11ea-9535-fba95385d311.png)

1. In diesem Bereich könnte man überall font-size: 12px setzen. Dann ist das etwas ruhiger.

---
### Cache Details 3:
Alt:
![grafik](https://user-images.githubusercontent.com/22332216/72605579-57e9db00-391d-11ea-8e3e-1b2041d94b6f.png)

1. Diesen Bereich könnte man vielleicht noch etwas mehr in der Höhe reduzieren.

---
### Cache Details 4:
Alt:
![grafik](https://user-images.githubusercontent.com/22332216/72605710-94b5d200-391d-11ea-9227-9729b8230dad.png)

1. Als Schriftgröße könnten wir hier font-size: 16px setzen so wie in Activity oder Activity auf 14px reduzieren.

**Comment by 2Abendsegler** [comment]
Habe noch folgendes geändert:
- "settings_searchmap_compact_layout" = true  
Die anderen Compact Layouts haben wir auch fast alle auf true.
- "settings_searchmap_strike_disabled" = true

Habe config_standard.txt für alle Parameter gepflegt im PR #1226.

**Comment by capoaira** [comment]
Die Vorschläge finde ich super.
Soll ich mich daran setzten?

**Comment by 2Abendsegler** [comment]
Wenn Bock und Zeit hast, ja.
Vielleich kommen aber noch Anmerkungen von Ruko2010.

**Comment by capoaira** [comment]
> Bitte mach vor erneuten Änderungen eine neue Branch aus dem collector.

@Ruko2010 wie bringst du deinen Collector auf den neuesten Standt? Wenn ich nur einen Merge mache, wird dieser immer mit die neuen Branches übertragen. Ich habe mir GitKraken installiert, aber davon bin ich etwas erschlagen.

**Comment by Ruko2010** [comment]
Also mir gefällt es auch schon sehr gut. Die Anmerkungen von @2Abendsegler find ich auch gut. Ich selbst lege nicht so viel Wert auf das Compact Layout, darum auch von mir keine Wünsche.

Zum Collector. Das kommt darauf an wie du arbeitest. Nutzt du ein Tool für die Git Sachen oder arbeitest du Hauptsächlich mit der Webseite?

Ich persönliche nutze GitKraken als Visuellen Git-Client. Da ich einen Fork vom 2Abendsegler Repo gemacht habe wurde dieser Automatisch als "Remote-Repo" eingebunden. Das heißt wenn jemand etwas in den Collector schiebt, dann zeigt es mir GitKraken automatisch an und ich mach einfach nur einen Pull auf den Collector und schon ist mein Repo wieder auf dem aktuellen Stand.
Hier sieht man zum Beispiel, dass es im Collector aktuell 31 Änderungen gibt. 
![image](https://user-images.githubusercontent.com/2239440/72617722-ebc9a000-3939-11ea-8887-b9dd62d3073e.png)

Wenn ich nun einen Pull mache, wird hier automatisch mein lokales Repo aktualisisert:
![image](https://user-images.githubusercontent.com/2239440/72617792-0d2a8c00-393a-11ea-8828-71786e43e13b.png)

Wenn ich das gemacht habe, dann erstelle ich davon einfach einen neuen Branch:
![image](https://user-images.githubusercontent.com/2239440/72617856-2df2e180-393a-11ea-8a2e-87c738654924.png)

Sobald ich das dann Pushe, landet es automatisch in meinem Folk und ich kann dann über das Webinterface von Github einen PR auf machen.

**Comment by capoaira** [comment]
Danke. Noch klappt es zwar nicht, aber ich muss nochmal etwas ausprobieren...

**Comment by capoaira** [comment]
Ah, jetzt funktioniert es. Danke 😊👍

**Comment by capoaira** [comment]
Ich werde die letzten Änderungen wahrscheinlich nicht morgen oder am Wochenende schaffen. Die Woche danach bin ich auf Klassenfahrt, also komplett ohne PC. Es wäre schön wenn einer von Euch die letzten Änderungen übernehmen könnte.

**Comment by Ruko2010** [comment]
Wegen mir müssen die Sachen nicht ins aktuelle Release. Wir können es auch noch 1-2 Wochen ruhen lassen. Ich fände es besser, wenn du dein Projekt abschließt.
@2Abendsegler was meinst du?

**Comment by 2Abendsegler** [comment]
Seh ich eigentlich genauso, blöd ist nur dass ich den ersten Teil schon in den Collector gemerged hatte. Deshalb hab ich mir das Issue gestern assigned und bin schon beim rumspielen. Naja, gerade nicht, jetzt fahr ich Fahrrad, aber heute Abend spiel ich weiter.

**Comment by capoaira** [comment]
Es tut mir leid, dass ich die Änderung so spät abgegeben habe. 
Danke, dass du dies noch Umgesetzt hast. Die Änderungen gefallen mir gut 👍

**Comment by 2Abendsegler** [comment]
Zusätzliches:

- [ ] Foren aus Standard Links entfernt
- [ ] Umbenennen von Linklist Elementen:
alt bookmark("Map", "/map/", c.bookmarks);
neu bookmark("Browse Map", "/map/", c.bookmarks);
alt bookmark("Bookmarks", "/account/lists", c.bookmarks);
neu bookmark("Bookmark Lists", "/account/lists", c.bookmarks);

---
Was fehlt noch:

- [ ] Search Map noch integrieren sobald Compact Layout und Own area on detail screen fertig sind

**Comment by 2Abendsegler** [comment]
merged
