### ISSUE TITLE
[New Map] Virtually hit "Search this area" after dragging the map

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#966]
After dragging of the map is finished, the button should be pressed automatically.
Maybe we could hide this button completely if the function is implemented

**Comment by capoaira** [comment]
Moin,
ich habe mich mal hier dran versucht:

```javascript
	if (document.location.href.match(/\.com\/play\/map\//)) {
		try {
			waitUntilDrag();
			function waitUntilDrag() {
				if (document.getElementById('clear-map-control')) {
					console.log('Drag');
					document.getElementById('clear-map-control').click();
					waitUntilDrag();
				} else {
					window.setTimeout(waitUntilDrag, 500);
					console.log('Wait');
				}
			}
		} catch(e) {gclh_error('Virtually hit "Search this area" after dragging the map',e);}
	}
```

Ich frage mich aber, ob das eleganter geht, als jede halbe Sekunde eine Abfrage zu machen. Bzw., ob diese Variante zu viele Ressourcen verbraucht.

**Comment by 2Abendsegler** [comment]
Mutation Observer beobachtet ob Änderungen erfolgt sind. Wir sollten es damit versuchen.

Ich werde dich mal assignen.

**Comment by capoaira** [comment]
Das habe ich versucht, nur mit wenig Erfolg. Man kann keine Id abfragen, die nicht existiert.

**Comment by 2Abendsegler** [comment]
Bei den neuen Listen Seiten wird body einmalig erzeugt, das heißt, ist es mal da, bleibt es auch. Ich habe dort body zur Abfrage genutzt. Und wenn man etwas weiter denkt, ist auch nicht nur dein Issue davon betroffen, sondern auch einige weitere, die dann über den gleichen Mutation Observer bedient werden sollten.

Ich habe es also so gemacht: Check ob body vorhanden ist über ein setTimeout. Wenn vorhanden, dann Mutation Observer aufmachen. Ab dann regelt der Observer die Änderungen.

**Comment by 2Abendsegler** [comment]
Hier noch mein Code, den du quasi leicht verändert verwenden könntest, falls `<body>` dafür geeignet ist. Am besten die Bezeichnungen "Lists" in "Map" ändern, dann müßte das passen. 

```
            // Build mutation observer for body.
            function buildObserverBodyLists() {
                var observerBodyLists = new MutationObserver(function(mutations) {
                    mutations.forEach(function(mutation) {
                        processAll();
                    });
                });
                var target = document.querySelector('body');
                var config = { attributes: true, childList: true, characterData: true };
                observerBodyLists.observe(target, config);
            }

            // Check if mutation observer for body can be build.
            function checkForBuildObserverBodyLists(waitCount) {
                if ($('body')[0]) {
                    if ($('.gclh_buildObserverBodyLists')[0]) return;
                    $('body').addClass('gclh_buildObserverBodyLists');
                   buildObserverBodyLists();
                } else {waitCount++; if (waitCount <= 200) setTimeout(function(){checkForBuildObserverBodyLists(waitCount);}, 50);}
            }

            checkForBuildObserverBodyLists(0);

```

**Comment by capoaira** [comment]
Ok, den body abzufragen ist eine gute Idee. Wenn das was ich jetzt gemacht habe in Ordnung ist, mache ich einen Pull Request. 
Bei den Einstellungen weiß ich nicht, wo ich die hin packen soll, also habe ich `settings_newMap_searchThisAreaAfterDraggingMap` hinzugefügt und auf true gesetzt.
