### ISSUE TITLE
Hide sidebar on map doesn't work with open in new tab.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#967]
**Describe the bug**
Hide sidebar on map doesn't work with open in new tab.

Bei open in new tab wird meist kein load Event gefeuert, witzig. Das gilt für Chrome und Opera und auch für Firefox. 

**To Reproduce**
1. Go to https://www.geocaching.com/map/
2. Wähle Map aus der Linklist mit rechter Maustaste und Öffnen in neuem Tab
3. Wähle nochmal Map aus der Linklist mit rechter Maustaste und Öffnen in neuem Tab
4. Sidebar verschwindet nicht

**Comment by 2Abendsegler** [comment]
Getestet unter Win 8.1 mit FF und Chrome.

**Comment by Ruko2010** [comment]
Supi. Scheint zu klappen, auch wenn ich es sehr schwer hatte das Problem nachzustellen. Bei mir klappt das mit dem Hide der Sidebar fast immer.
