### ISSUE TITLE
Error on window.GCLittleHelper_MapLayerHelper and MutationObserver.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#969]
**Describe the bug**
Error on window.GCLittleHelper_MapLayerHelper and MutationObserver.
Im Enhanced Map Popup werden keine Daten angezeigt. Loading bleibt stehen.
http://geoclub.de/forum/viewtopic.php?f=117&t=80208&start=180#p1291033

**To Reproduce**
??

**Desktop (please complete the following information):**
 - Win 10 Pro 64Bit 1809
 - Chrome

![grafik](https://user-images.githubusercontent.com/22332216/51783350-9d276280-2138-11e9-9c2e-e099386ee20e.png)

![grafik](https://user-images.githubusercontent.com/22332216/51783244-7fa5c900-2137-11e9-83a0-3c1e17a496ee.png)

**Comment by 2Abendsegler** [comment]
Ich kann die Fehler nicht nachstellen und bin etwas ratlos. ;)

**Comment by Ruko2010** [comment]
Ich hab auf Arbeit noch einen Windows 10 Rechner. Ich schau mal ob ich ihn da nachstellen kann

**Comment by Ruko2010** [comment]
@2Abendsegler Ich habe es versucht nachzustellen. Windows 10 mit Chrome. Frisch installiert und GClh drauf gemacht. Es funktioniert alles wie es soll. Ich kann es nicht nachstellen.
Vielleicht hat er nen Popupblocker drauf oder so der irgendwas verhindert, oder ein anderes Script das Quer schießt.
ich bin jedenfalls am Ende mit meinem Latein.

**Comment by Ruko2010** [comment]
So, ich konnte das Problem nachstellen. THC nutzt anstatt der Leaflet Karte die Googlekarte. Klar das dann einige Objekte fehlen und der Code fehl schlägt. Ich werde die Funktion auf der Google Karte abschalten, dass sollte das Problem fixen.

**Comment by Ruko2010** [comment]
@2Abendsegler So, der Fehler ist gefixt. Das einzige Problem, es funktioniert erst beim zweiten Laden nachdem man die Google Map ausgewählt hat. Ich mach mal einen PR und am besten du schaust es dir an ob das so ok ist.

**Comment by 2Abendsegler** [comment]
Was ein Gedöhns, hab auch nicht mehr an die Google Karte gedacht. Haste gut gemacht. ;)

Ich weiß nicht wie ich mich an deinem PR beteiligen kann, hab deshalb einen neuen aufgemacht (#974).

Hab folgendes geändert:
- Die Prüfung ob Leaflet aktiv ist habe ich weiter nach vorne genommen, so dass auch bei den Layern schon gegen den Parameter "gclhLeafletMapActive" geprüft werden kann. (Das ist Issue #973. Issue kann damit rejected werden.)
- Ich kann nicht mehr nachvollziehen warum die Prüfung ob Leaflet aktiv ist in einem zeitlichen Intervall läuft. Alle Informationen sind sofort verfügbar. Ich habe das umgebaut, und ich habe auch den Update des Parameters vor die Ausgabe der Meldung gestellt wenn Google aktiv.  
- Deine Änderung beim Popup zieht nun auch gleich. 

Schaus dir bitte mal an, ob das so nicht besser ist. Und teste gegebenenfalls noch auf dem Mac mit FF und Chrome, hauptsächlich wegen dem zeitlichen Intervall, das ich nicht mehr nachvollziehen kann.

**Comment by Ruko2010** [comment]
@2Abendsegler also wie man sich an einem PR beteiligt über die Weboberfläche weis ich leider auch nicht. Bei mir im Git-Programm kann ich den Branch mit dem PR einfach auschecken. Wenn ich dann dort etwas rein pushe, geht es automatisch in den PR wo es hin gehört, auch wenn der PR von jemand anders ist. Vielleicht gibt es hier etwas dazu:
https://superuser.com/questions/1188943/can-i-submit-commits-to-someone-elses-pull-request-in-my-repository

Geprüft habe ich es im Chrome, FF und Safari, sieht gut aus 😃.
