### ISSUE TITLE
Error on Map when Google Map is selected instead of Leaflet Map

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#973]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2239440/52151692-40fe9a00-2674-11e9-88fe-617d4bd2677a.png)

**To Reproduce**
1. Go to https://www.geocaching.com/map/
2. See error

**Comment by 2Abendsegler** [comment]
Done with issue #969 respectively PR #974.
