### ISSUE TITLE
Geonames elevation error with more than 20 coordinates.

### ISSUE THREAD

**Issue by 2Abendsegler** [2Abendsegler/GClh#976]
**Describe the bug**
Geonames elevation error with more than 20 coordinates.

Geonames kann bei einem Aufruf nur für maximal 20 Koordinaten die Höhen ermitteln. Übergibt man mehr als 20 Koordinaten gibt es keine Ergebnisse. Unsere Datenbeschaffung (GM_xmlhttpRequest) wie auch unsere Zuordnung der ermittelten Höhen im Listing (fkt addElevationToWaypoints) ermöglicht derzeit keine Splittung, keine Ermittlung in Etappen. 

Die Datenbeschaffung wäre noch relativ gut zu kapseln, so dass man sie auch mehrfach für einen Service aufrufen könnte. Die Zuordnung der Höhen ins Listing erscheint jedoch etwas schwieriger weil die Koordinaten im Listing quasi nur durchnummeriert sind. Das scheint nun nicht mehr auszureichen um eine korrekte Zuordnung zu treffen.
Zudem könnte ein weiterer Aufruf von Geonames schneller Ergebnisse liefern als der vorangegangene.

Läuft einer der Aufrufe gegen die Wand, sollte vielleicht für alle Koordinaten der Folgeservice anlaufen.  Wenn zu allen Koordinaten Höhen ermittelt sein müssen, bevor man sie ins Listing stellt, wäre das Zuordnungsproblem kein Problem mehr und der Folgeservice würde im Falle eines Fehlers die Höhen ins Listing stellen, weil bei Geonames letztlich nicht für alle Koordinaten Höhen ermittelt wurden.  

**To Reproduce**
1. Go to https://www.geocaching.com/geocache/GC2VFGP_pfalzerwald-durchquerung-x

**Screenshots**
![grafik](https://user-images.githubusercontent.com/22332216/52248821-7f07f200-28f0-11e9-9386-6448c4e2ca1b.png)

**Desktop (please complete the following information):**
All

**Comment by Ruko2010** [comment]
Ich hab mir die Sache ja nicht angeschaut, aber vielleicht kann man dem Request auch irgendwie eine ID mit geben, wo es aufgerufen wurde, so dass man es im Response wieder zuordnen kann.

**Comment by 2Abendsegler** [comment]
... die Koords sind schon umgewandelt, insfern ist der Vergleich schwierig.
Aber die gemeinsame Idee scheint zu funktionieren. Ist nur etwas problematisch zu testen.

**Comment by 2Abendsegler** [comment]
Testdaten:

1. Bei Anzahl Lokations pro Aufruf = 1 (maxLocations = 1): 
Die Ergebnisse kommen zeitlich total unterschiedlich zurück, was ja gut ist zum Testen, die Einsortierung funktioniert. 
2. maxLocations = 20:
Die angehängte Liste hab ich sortiert. Anschließend hab ich maxLocations auf 20 gesetzt und abgeglichen mit den zuvor in 1. ermittelten Höhen. Das passt. 
3. Ein weiterer Abgleich mit OpenElevations passt auch.

https://coord.info/GC6RH0Y
maxLocations = 1:
```
lats=49.44117&lngs=8.17133& / addListIndex: 0  / ListIndex: 0  / +187m 
lats=49.44192&lngs=8.09502& / addListIndex: 1  / ListIndex: 1  / +485m 
lats=49.44622&lngs=8.14368& / addListIndex: 2  / ListIndex: 2  / +297m 
lats=49.44047&lngs=8.0903&  / addListIndex: 3  / ListIndex: 3  / +468m 
lats=49.438&lngs=8.09137&   / addListIndex: 4  / ListIndex: 4  / +474m 
lats=49.44028&lngs=8.09052& / addListIndex: 5  / ListIndex: 5  / +464m 
lats=49.41195&lngs=8.11018& / addListIndex: 6  / ListIndex: 6  / +365m 
lats=49.41047&lngs=8.11447& / addListIndex: 7  / ListIndex: 7  / +444m 
lats=49.44278&lngs=8.10627& / addListIndex: 8  / ListIndex: 8  / +417m 
lats=49.41493&lngs=8.13278& / addListIndex: 9  / ListIndex: 9  / +493m 
lats=49.41673&lngs=8.13987& / addListIndex: 10 / ListIndex: 10 / +531m 
lats=49.41105&lngs=8.06777& / addListIndex: 11 / ListIndex: 11 / +479m 
lats=49.41638&lngs=8.1387&  / addListIndex: 12 / ListIndex: 12 / +527m 
lats=49.44412&lngs=8.15878& / addListIndex: 13 / ListIndex: 13 / +285m 
lats=49.44117&lngs=8.17133& / addListIndex: 14 / ListIndex: 14 / +187m 
lats=49.4447&lngs=8.12817&  / addListIndex: 15 / ListIndex: 15 / +277m 
lats=49.44113&lngs=8.1692&  / addListIndex: 16 / ListIndex: 16 / +192m 
lats=49.44197&lngs=8.15895& / addListIndex: 17 / ListIndex: 17 / +196m 
lats=49.44323&lngs=8.15777& / addListIndex: 18 / ListIndex: 18 / +266m 
lats=49.44788&lngs=8.12252& / addListIndex: 19 / ListIndex: 19 / +358m 
lats=49.44292&lngs=8.10355& / addListIndex: 20 / ListIndex: 20 / +431m 
lats=49.43118&lngs=8.08345& / addListIndex: 21 / ListIndex: 21 / +480m 
lats=49.40992&lngs=8.11608& / addListIndex: 22 / ListIndex: 22 / +455m 
lats=49.41058&lngs=8.12273& / addListIndex: 23 / ListIndex: 23 / +487m 
lats=49.42527&lngs=8.15928& / addListIndex: 24 / ListIndex: 24 / +362m 
```

Die gleichen Tests nochmal mit https://coord.info/GC2VFGP, passt auch.

**Comment by Ruko2010** [comment]
Sehr cool!
