### ISSUE TITLE
Save As Pocket Query - Default settings for new pocket queries do not work

### ISSUE THREAD

**Issue by Donnerknispel** [2Abendsegler/GClh#978]
**Describe the bug**
When uing "Save As Pocket Query" form the map the default settings for new pocket queries do not work

**To Reproduce**
1. Go to map
2. Click on 'Save As Pocket Query'
3. The Pocket Query page opens, but the default settings for new pocket queries do not work.

**Expected behavior**
When creating a Pocket Query by opening the “Your Pocket Queries” page an clicking on “Create a new Query” the default settings for new pocket work.
The default settings should also apply when clicking on 'Save As Pocket Query' on the map page.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox
 - Version: 65.0 (64-Bit)

**Additional context**
This is my first bug report, so have mercy

**Comment by Ruko2010** [comment]
Hi @Donnerknispel and thanks for reporting a bug. Can you please be more specific. What exactly does not work? Can you save the PQ, or is something else failing?
If I go to the map, hit "save as pocket query" and on the next page hit save everything works fine.
Maybe you can attache a Screenshot of the problem.

**Comment by Donnerknispel** [comment]
Hi @Ruko2010, by "does not work" I wanted to say, that the default settings for new pocket queries are not applied, when creating a query by "Save As Pocket Query" from the map page.
When creating a query by clicking on “Create a new Query” on the Your Pocket Queries” page the settings for new pocket queries.

Hope the explanation helps.

**Comment by Ruko2010** [comment]
Ah, ok. Now I know what you meant 😃and I think I'll have a solution for this. I will discuss the solution with @2Abendsegler if he sees any problems. If not the fix will be rolled out in the next version.

**Comment by Ruko2010** [comment]
@Donnerknispel If you want to implement the fix before the new Version, go to the script editor and change line 3844 (current Version) from
`if (($("p.Success").length <= 0) && (document.location.href.match(/\.com\/pocket\/gcquery\.aspx$/) || document.location.href.match(/\.com\/pocket\/gcquery\.aspx\/ll=/))) {`
to
`if (($("p.Success").length <= 0) && (document.location.href.match(/\.com\/pocket\/gcquery\.aspx$/) || document.location.href.match(/\.com\/pocket\/gcquery\.aspx\?ll=/))) {`

**Comment by Donnerknispel** [comment]
It worx
Thanx

**Comment by 2Abendsegler** [comment]
@Ruko2010
Yes fine.
