### ISSUE TITLE
Replace Logs faster with Logs Loaded by GClh

### ISSUE THREAD

**Issue by Ruko2010** [2Abendsegler/GClh#995]
As now, GClh is waiting for all logs to be loaded until it replaces the logs with our own template.
It would be nice if the logs are replaced, while they are loaded, so they are replaced much faster and are much more consistent for the user. See details in #663 and #991

**Comment by Ruko2010** [comment]
@2Abendsegler das sit leider nicht ganz so einfach wie gedacht 😃. Die komplette initiale load Log Funktion ist darauf ausgelegt, erst die logs zu ersetzen, wenn sie vollständig geladen wurden. Ich versuche es umzubauen, aber das wird sicher nicht einfach. Ich setz das Risk mal auf High, da wir da auch einiges kaputt machen können.

**Comment by Ruko2010** [comment]
Ich überlege, ob es vielleicht mehr Sinn macht erstmal "schnell" die Anzahl der Logs, die beim ersten laden angezeigt werden (30?!) zu laden und den rest "gleich" zu lassen...dann haben wir schonmal 30 logs und der rest kann im Background mit der VIP-Liste laden...

**Comment by Ruko2010** [comment]
Problem an der aktuellen version:
es wird über das "geocache.logbook" eine Anzahl von Logs geladen, und zwar 100. wenn es mehr als 100 logs gibt, dann halt öfter. 
Es gibt nun 2 Möglichkeiten.
1. Ich verringere die Anzahl der zu ladenden Logs z.B. auf 25. Dann hab ich aber 4 mal so viele Request.
2. Ich verringere nur den ersten Aufruf auf 25. Dann habe ich aber das Problem, dass ich im zweiten Aufruf keine 100 Logs abrufen kann, denn so wie ich es sehe, kann ich keinen "startlog" angeben. Das heißt entweder ich lad die ersten 25 nochmal mit (und muss die dann aber irgendwie überspringen), oder ich lad noch 3x25 und dann erst 100...

**Comment by Ruko2010** [comment]
Vielleicht fällt mir auch noch was besseres ein...mal schauen

**Comment by 2Abendsegler** [comment]
Die Anzahl der ersten Logs sind in der Standardkonfiguration 30 Logs. Den Parameter kann man aber im config anpassen. Insofern kann man die nicht unbedingt mal schnell laden.
 
Spontan stellt sich bei mir gerade ein ganz mulmiges Gefühl ein wenn ich daran denke das Laden der Logs komplett umzustellen, hohes Risiko ist sicherlich gerechtfertigt. Wir sollten hier möglichst nicht viel bis gar nichts ändern. 

Nur mal laut gedacht ... Vielleicht könnten wir warten bis die anfänglichen Logs über die bisherigen Routinen geladen wurden, um sie dann für die Anzeige zu nutzen ...

**Comment by Ruko2010** [comment]
Wie bereits beschrieben besteht das Problem darin, dass die Funktion, die die Logs hinzufügt immer darauf ausgelegt ist, dass schon alle Logs geladen sind, denn es werden nicht nur die Logs hinzugefügt, sondern auch die VIPs/VUPs aufgebaut und noch ein paar Sachen mehr. Und das umzustellen ist ein schwierige Sache.

Das Problem, dass du bei den Great Story buttons beschreibst (mehreres Austauschen der Log Templates durch verzögerte nachladen) kann man auch recht einfach umgehen. Man blendet einfach sofort die Tabelle mit den ursprünglichen Logs aus.
Nachteil: Bis alle Logs geladen sind, ist erstmal gar nichts zu sehen.

**Comment by Ruko2010** [comment]
Ich habs mal implementiert. Es wird die ursprüngliche Tabelle sofort ausgeblendet und dann werden "schnell" die ersten 30 Logs geladen. Im Hintergrund lädt dann der Rest wie gewohnt nach. Ich weis nicht, ob das so das gelbe vom Ei ist, aber schau es dir vielleicht mal an.
https://github.com/Ruko2010/GClh/raw/test_load_first_logs_fast/gc_little_helper_II.user.js

Die Sache mit Great Story bitte erstmal ignorieren, ich hatte den branch aus meiner Branch erstellt, wo das schon mit drin war. Aber gerade bei den first 30 hab ich die Funktionen komplett weg gelassen.

**Comment by 2Abendsegler** [comment]
Hmm ... wir wollten ja eigentlich Dinge verbessern ...
Ich habs mir noch nicht angesehen.

---
Vorschlag:
Neue Logs die durchs scrollen erzeugt werden, werden schon fast korrekt angezeigt, weil unser log-template dann ja schon zur Verfügung steht. Ich hab mir das mal zu Nutzen gemacht, die GS Logs gelöscht und durch unsere eigenen ersetzt.

Bau das mal ein, ruf dann ein Listing auf, scroll nach unten zum ersten Log und aktualisiere dann die Seite, dann siehst du was ich meine.

```
                function gclh_load_helper(count) {
                    var url = http + "://www.geocaching.com/seek/geocache.logbook?tkn=" + userToken + "&idx=" + curIdx + "&num=100&decrypt=false";
                    GM_xmlhttpRequest({
                        method: "GET",
                        url: url,
                        onload: function(response) {
                            requestCount--;
                            var dataElement = JSON.parse(response.responseText);
                            data[dataElement.pageInfo.idx] = dataElement;
                            if (numPages == 1) {
                                numPages = data[count].pageInfo.totalPages;
                                for (curIdx = 2; curIdx <= numPages; curIdx++) {
                                    requestCount++;
//-->xxxx
//                                    gclh_load_helper(curIdx);
//<--xxxx
                                }
                            }
//-->xxxx
                            setTimeout(function() { // nur damit man die Änderungen sieht
                                $('#cache_logs_table').find('tbody').children().remove();
                                var json = data[dataElement.pageInfo.idx];
                                logs = logs.concat(json.data);
                                for (var i = 0; i < 30; i++) {
                                    if (logs[i]) {
                                        var newBody = unsafeWindow.$(document.createElement("TBODY"));
                                        unsafeWindow.$("#tmpl_CacheLogRow_gclh").tmpl(logs[i]).appendTo(newBody);
                                        unsafeWindow.$(document.getElementById("cache_logs_table2") || document.getElementById("cache_logs_table")).append(newBody.children());
                                    }
                                }
                            }, 1000);
//                            if (requestCount <= 0) gclh_load_dataHelper();
//<--xxxx
                        }
                    });
                }
```

**Comment by Ruko2010** [comment]
Das sieht vielversprechend aus! Aber nur damit ich nicht verquer denke. Das darf dann eigentlich nur beim ersten Call ausgeführt werden. Aus der Funktion "gclh_load_dataHelper" muss dann alles raus, was die Logs verändert.
Aber durchdenke müsste man noch was passiert, wenn gleich alle Logs angezeigt werden sollen. Dann müsste die Funktion (ohne das löschen der alten Logs) ja für alle Calls aufgerufen werden. Genau das gleiche, wenn sich jemand gern 120 Logs zum Start anzeigen lassen will.

**Comment by Ruko2010** [comment]
Ok, ich habs mal umgebaut und es sieht wirklich gut aus!
https://github.com/Ruko2010/GClh/raw/test_load_first_logs_faster_2/gc_little_helper_II.user.js

Ein Problem habe ich nun noch entdeckt. Wenn man herunter scrollt, während noch nicht alle Logs geladen sind, dann fügt er irgendwie welche doppelt hinzu. Das muss ich mal noch überprüfen. hier ein guter Testcache mit vielen Logs:
https://www.geocaching.com/geocache/GC6069_the-old-city-hall-message

Vielleicht müssen wir einfach das Nachladeevent deaktivieren solange noch nicht alles da ist. 
Weiterhin habe ich noch mit einer festen Größe von 30 Logs gearbeitet die initial angezeigt werden. Dass muss auch noch gemacht werden.
Die Great Story Sache hab ich erstmal weg gelassen. Da kümmere ich mich drum wenn das hier läuft. Daher ist der Branch auch vom aktuellen Collector.

**Comment by 2Abendsegler** [comment]
Alsoooo ... mein Vorschlag diente lediglich dazu den Effekt darzustellen, sonst nichts. ;)

- Das Löschen und Neuaufbauen der von GS angezeigten Logs sollte direkt nach dem Insert unseres Log Templates stattfinden und nicht in der Leseroutine wie im Vorschlag.
- Wir sollten hier nur mit id=cache_logs_table arbeiten. Damit kommen wir dann auch dem Aufbau der Logs durch den GClh nicht in die Quere. Der GClh baut ja in id=cache_logs_table2 auf und sorgt auch dafür dass id=cache_logs_table verborgen wird. Dass Logs doppelt angezeigt werden könnte auch damit zusammenhängen.
- Die gewählte Anzahl der anzuzeigenden Logs ist hier nicht relevant, weil wir uns ja noch bei den Logs von GS aufhalten, also in id=cache_logs_table.
- Das Nachladeevent können wir nicht deaktivieren, weil es unter Umständen ne Minute dauern kann, bis alle Logs geladen sind, wenn man noch ne langsame Leitung hat.

Wenn du möchtest kann ich mich hier auch mal versuchen.

**Comment by 2Abendsegler** [comment]
Ich hoffe ich war nicht zu patzig ... hast vermutlich zu tun mit eurem Event ... übrigens coole Idee.

**Comment by Ruko2010** [comment]
Patzig? Nein nein, keine Sorge. Ich war diese Woche komplett außer Gefecht gesetzt. Ich lag nur im Bett und hab sowohl Handy als auch Laptop nur von weitem gesehen. Jetzt gehts langsam wieder Bergauf und ich kann wieder was tun.
Das Event ist soweit durchgeplant, fehlt noch ein wenig Ausrüstung und ich muss meinen "Vortrag" noch vorbereiten, aber das wird schon 😉.
So, nun zu deinen Anmerkungen.
>Das Löschen und Neuaufbauen der von GS angezeigten Logs sollte direkt nach dem Insert unseres Log Templates stattfinden und nicht in der Leseroutine wie im Vorschlag.

ja schon klar, war ja auch nur ne "demo" 😃. Ich bau es dann natürlich noch etwas "schöner" in einzelnen Funktionen, aber vom zeitlichen Ablauf wird es wohl so werden, so dass die Probleme die jetzt auftreten, dann wohl auch auftreten werden.

>Wir sollten hier nur mit id=cache_logs_table arbeiten. Damit kommen wir dann auch dem Aufbau der Logs durch den GClh nicht in die Quere. Der GClh baut ja in id=cache_logs_table2 auf und sorgt auch dafür dass id=cache_logs_table verborgen wird. Dass Logs doppelt angezeigt werden könnte auch damit zusammenhängen.

Hä? Jetzt steh ich ein wenig auf dem Schlauch. Willst du die ersten "schnellen" Logs in die "alte" GC Tabelle werfen ("cache_logs_table")?
Mein Verfahren hätte vorgesehen, dass wir sofort "unsere" "cache_logs_table2" aufbauen mit den neuen Logs. So hab ich das auch umgesetzt. Ich schmeiß sofort die GC Logs raus und ersetze nach dem ersten call (100 Logs geladen) mit unseren Logs. Das geht auch sehr flink, nur wie gesagt muss ich mir noch die aufgetretenen Probleme anschauen.

>Die gewählte Anzahl der anzuzeigenden Logs ist hier nicht relevant, weil wir uns ja noch bei den Logs von GS aufhalten, also in id=cache_logs_table.

Das bestätigt meine Vermutung, dass du zum aufbau der ersten Logs nicht auf das erste Laden des ersten calls des "logbuchs" warten willst. Aber ich denke, dass ist sinnvoller. Ich mach dann mal ein paar testst mit langsamen Verbindungen, um zu schauen wie praktikabel das ganze ist.

> Das Nachladeevent können wir nicht deaktivieren, weil es unter Umständen ne Minute dauern kann, bis alle Logs geladen sind, wenn man noch ne langsame Leitung hat.

recht haste, ich finde schon eine Lösung.

So, jetzt aber genug geschrieben, jetzt wird gecoded 😃

**Comment by Ruko2010** [comment]
@2Abendsegler Also, ich hab noch ein bisschen gebastelt und auch ein paar Tests mit einer "slow 3G"-Verbindung gemacht. Sowohl die initialen logs (ich habs mal auf 120 erhöht) also auch das laden der vollständigen Logs geht recht schnell (was man so schnell nennen kann, bei Slow 3G 😃).
Doppellogs habe ich nun auch nicht mehr beobachtet (und auch in den Logs nicht mehr nachvollziehen können).
Vielleicht schaust du es dir mal an? Hier der Link:
https://github.com/Ruko2010/GClh/raw/test_load_first_logs_faster_2/gc_little_helper_II.user.js

**Comment by 2Abendsegler** [comment]
Ich finde nicht dass es sinnvoller ist auf das Laden der ersten Logs zu warten bis wir sie anzeigen. Nicht nur wegen der Zeit, sondern auch insbesondere wegen des großen Eingriffs in das Ladecoding, wo wir kaum alle Fälle werden testen können. 
Wenn wir die GS Logs nehmen könnten und sie nach unserem Template neu aufbauen könnten, wäre das viel sicherer. Das Ladecoding würde unberührt bleiben. Und der quasi einzige Unterschied für den User wären die VIPs, die noch nicht gekennzeichnet sind.

Ich hab kurz reingeschaut:
1. Die Zeit ist nun schon spürbar die es dauert bis die Logs angezeigt werden. Mit dem Button "Go to Logs" bin ich ja schnell unten bei den Logs. Und wenn GS mal nicht so schnell anwortet, dann wird es noch länger dauern. 
2. Der Button Show Counter funktioniert nicht mehr.
3. Wenn ich nach unten scrolle und nachladen lasse bevor wir mit dem Laden der Logs fertig sind, enthält das Endergebnis im Bereich des Nachladens andere Logs als wenn ich nicht hätte nachladen lassen.
4. Wenn ich mehr als 100 Logs als Startwert haben möchte werden nur 100 Logs geladen. 

Hab mit https://www.geocaching.com/geocache/GC4MEGA_big-appel mit 4700 Logs getestet.

**Comment by Ruko2010** [comment]
Das heißt du willst alles so lassen wie es ist, und nur eine zweite, zusätzliche Routine einbauen, die die GC-Logs umbaut? Macht das dann sinn? Dann kann ich ja auch nur die Logs umbauen, die schon da sind, oder? Das sind dann auch so um die 30 Stück, oder?
Ich finde, das ist wieder so eine halb-gare Lösung. Ich fände es besser, lieber auf die ersten 100 Logs zu warten, aber du hast das Thema "schneller die Logs laden" angeschnitten, also entscheide du 😃.
Wenn du willst, schau es dir vielleicht auch nochmal an.

**Comment by 2Abendsegler** [comment]
Ich hab mirs nochmal überlegt. Wenn es einfach machbar wäre von vorne herein unsere Logs zu laden, dann würde ich das auch bevorzugen. Leider sind dazu aber ziemlich große Eingriffe in das bestehende Coding notwendig. Und die Wahrscheinlichkeit von Fehlern wäre schon erheblich, weil sich das ganze nicht wirklich gut und umfassend testen lässt.
Und das quasi nur dafür, dass die VIPs sofort richtig mit angezeigt werden. Ansonsten sieht es ja so aus wie unsere eigenen Logs. 

Ich wäre froh wenn wir an dieser Stelle die Möglichkeit von Fehlern ausschließen könnten.

Also ja, ja, ja, 25 oder 26 Logs.

**Comment by Ruko2010** [comment]
Jetzt muss ich aber doch nochmal doof fragen. Dann haben wir doch aber das gleiche Problem wie vorher oder? GC bau die Logs auf, wir löschen sie, bauen sie nach unseren vorgaben neu und dann ersetzen wir sie noch einmal mit den "komplett" geladenen Logs. Dann springt das doch auch 3 mal hin und her, oder?

**Comment by 2Abendsegler** [comment]
Bisher springt das doch gar nicht. Lediglich die fehlenden Bilder in den GS Logs, bzw. das fehlen des Platzes für die Bilder verursacht eine Verschiebung, wenn wirs mit unseren Logs ersetzen. Wenn wir die GS Logs nun direkt nach dem Insert unseres Log Templates ändern, dann fällt auch das weg, weil wir dann schnell genug sind, dass man sich noch gar nicht weiter unten in den Logs befinden kann. Und wenn wir unsere Logs dann reindonnern und die anderen löschen, dann sieht das genauso aus wie zuvor und der User steht an der gleichen Stelle wie zuvor. 
Das heißt es fällt überhaupt nicht auf, dass wir hier mehrfach etwas ersetzen. Auch nicht wenn wir uns weiter unten in den Logs befinden. So zumindest meine Erfahrung.

**Comment by Ruko2010** [comment]
Also wäre der Ablauf so:

1. Alle bleibt wie es ist 😃
2. Wir löschen die (27) GC logs und parsen uns die infos raus, die wir brauchen
3. Wir fügen die GC logs, die wir gerade geparst haben nochmal über das neue Template hinzu.


Was ich aber noch nicht so richtig raus habe. Eigentlich ersetzen wir doch schon das Template für die Logs recht zeitig. Warum nimmt dann GC nicht schon unser neues Template, anstatt die Logs mit dem alten Template aufzubauen...

**Comment by 2Abendsegler** [comment]
Ich glaube die Logs von GS sind schon da bevor unser Script anläuft, die Anzeige am Bildschirm dauert nur etwas.

**Comment by 2Abendsegler** [comment]
... ansonsten, ja genau.

**Comment by Ruko2010** [comment]
ok. Dann schau ich mal ob das so klappt. Aber ich glaub wir brauchen nichtmal was rausparsen, denn die initial logs gibt es ja schon als JS-Object im Code.

**Comment by Ruko2010** [comment]
https://github.com/Ruko2010/GClh/raw/feature/load_logs_faster/gc_little_helper_II.user.js

Ich habe im Code gesehen, dass genau das schonmal versucht wurde, aber irgendwie klappte das nicht. darum hab ich die Funktion angepasst. Das einzige was nicht geht, ist die fancybox der Bilder. Das verstehe ich leider überhaupt nicht, warum das nicht will. Vielleicht ist das an der Stelle das Fancybox script noch nicht geladen?!?! Vielleicht findest du eine Lösung. Ansonsten sollte es das sein, was du wolltest, oder?
Ich hatte mal zum testen noch ein 

`css += "#cache_logs_table {background-color: blue;}";`

eingefügt, damit man besser sieht was passiert.

**Comment by 2Abendsegler** [comment]
**Boah eh, geile Sache, genau so. :)**

Wenn du noch ein setTimeout einbaust dann klappt es auch mit der fancybox. Frag mich nicht warum es dann geht, ich weiß es nicht.
```
setTimeout(function(){
            unsafeWindow.$("#cache_logs_table tbody").children().remove();

            var initialLogs = unsafeWindow.initialLogs;
            var inclAvatars = chromeUserData.includeAvatars || unsafeWindow.includeAvatars || includeAvatars;

            for (var i = 0; i < initialLogs.data.length; i++) {
                var newBody = unsafeWindow.$(document.createElement("TBODY"));
                unsafeWindow.$("#tmpl_CacheLogRow_gclh").tmpl(initialLogs.data[i]).appendTo(newBody);
                unsafeWindow.$(document.getElementById("cache_logs_table")).append(newBody.children());
            }
            unsafeWindow.$('a.tb_images').fancybox({'type': 'image', 'titlePosition': 'inside'});
            gclh_add_vip_icon();
            setLinesColorInCacheListing();
}, 0);
```

**Comment by Ruko2010** [comment]
WTF? Warum klappt es mit Timeout, aber nicht ohne??? Vor allem ein Timeout mit 0 Sekunden. Das macht doch gar keinen Sinn 😃. Aber egal, es klappt.

Ich mach den PR auf und dann kannst du ja gern nochmal ausführlich testen.
