### ISSUE TITLE
"Past Events" in bookmarklists and watchlists don't work with the new event time.

### ISSUE THREAD

**Issue by V60GC** [2Abendsegler/GClh#997]
**Describe the bug**
In den BM-Listen zeigt Past Events(0|0) an, obwohl vergangene Events vorhanden sind.
Vermutlich seit die Uhrzeit mit angezeigt wird.

Viele Grüße
V60

**Comment by 2Abendsegler** [comment]
Danke für die Fehlermeldung. 

Ja, das hängt bestimmt mit den Änderungen bezüglich der Uhrzeit zusammen.

**Comment by 2Abendsegler** [comment]
@Ruko2010 
Das Event Datum ist nicht mehr "end: new Date(2014, 06-1, 21)" sondern erweitert um die Uhrzeit "end: new Date(2014, 06-1, 21," (nach dem Komma kommt dann die Uhrzeit). Theoretisch läßt sich auch die Uhrzeit mit abfragen, hier wären dann aber vermutlich noch Zeitzonen zu berücksichtigen. Das muss aber auch nicht sein, fand ich.

Getestet in eigenen und fremden Bookmarklisten und in Watchlist. 

Bitte noch Changelog pflegen. Wegen fehlender branch für v0.9.17 kann ich das ja nicht.

**Comment by Ruko2010** [comment]
Ja die Uhrzeit kann man vernachlässigen. macht nur mehr probleme, als das es vorteile bringt. Sehr schön gemacht 😉.
